### ISSUE TITLE
RHEL 8 CIS 5.5.3 Ensure password reuse is limited updating wrong file

### ISSUE THREAD

**Issue by bmarshmn** [ComplianceAsCode/content#10012]
the updates are done in /etc/pam.d/system-auth, but per CIS should be done against system-auth in the current authselect profile.
As is, future authselect runs will loose the pam_pwhistory.so updates

https://workbench.cisecurity.org/sections/1149671/recommendations/1873474

**Comment by marcusburghardt** [comment]
The rules related to `pam_pwhistory.so` were recently updated and are covering all authselect cases.
More details in #[9994](https://github.com/ComplianceAsCode/content/pull/9994) and #[10021](https://github.com/ComplianceAsCode/content/pull/10021)
