### ISSUE TITLE
Unexpected rule for STIG item RHEL-08-010130

### ISSUE THREAD

**Issue by rmetrich** [ComplianceAsCode/content#10010]
#### Description of problem:

From [StigViewer](https://www.stigviewer.com/stig/red_hat_enterprise_linux_8/2021-12-03/finding/V-230233), RHEL-08-010130 is supposed to apply on content of `/etc/login.defs`.
The implementation is indeed matching, as shown below:

- `./linux_os/guide/system/accounts/accounts-pam/set_password_hashing_algorithm/set_password_hashing_min_rounds_logindefs/rule.yml`

    ~~~
    stigid@rhel8: RHEL-08-010130
    ~~~

- `./products/rhel8/profiles/stig.profile`

    ~~~
    # RHEL-08-010130
    - set_password_hashing_min_rounds_logindefs
    ~~~

**However** other STIG files we have reference another rule applying to *pam_unix* instead (**accounts_password_pam_unix_rounds_password_auth**):

- `./controls/stig_rhel8.yml`

    ~~~
    -   id: RHEL-08-010130
        levels:
            - medium
        title: The RHEL 8 password-auth file must be configured to use a sufficient number
            of hashing rounds.
        rules:
            - accounts_password_pam_unix_rounds_password_auth
        status: automated
    ~~~

- `./linux_os/guide/system/accounts/accounts-restrictions/password_storage/accounts_password_pam_unix_rounds_password_auth/rule.yml`:

    ~~~
    references:
        anssi: BP28(R32)
        disa: CCI-000196
        srg: SRG-OS-000073-GPOS-00041
        stigid@ol8: OL08-00-010130
    ~~~

#### SCAP Security Guide Version:

Master branch at latest commit (*df7f366b448537773fc6025475c3d8f184c51b01*)

#### Operating System Version:

N/A

#### Steps to Reproduce:

N/A

**Comment by vojtapolasek** [comment]
Hello, just a note that although the file controls/stig_rhel8.yml exists, it is not used in any profile yet.

**Comment by vojtapolasek** [comment]
The file has been completely dropped, see https://github.com/ComplianceAsCode/content/pull/10023
Does it solve your issue?
