### ISSUE TITLE
Bootloader passwords in kickstarts

### ISSUE THREAD

**Issue by Mab879** [ComplianceAsCode/content#10024]
#### Description of problem:
It appears that we are misusing encrypted passwords in our kickstart.

See #10014 
And https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/installation_guide/sect-kickstart-syntax#idm140126369022480

#### SCAP Security Guide Version:
master

#### Operating System Version:
Any OS with kickstarts

#### Steps to Reproduce:

Viewing the file

#### Actual Results:
Not using kickstart correctly.

#### Expected Results:
Using kickstart encrypted passwords correctly.

**Comment by comps** [comment]
Closing as fixed by https://github.com/ComplianceAsCode/content/pull/10499
