### ISSUE TITLE
RHEL 9 ACSC ISM Official Profile - Ansible Remediation Role - set -o pipefail issue

### ISSUE THREAD

**Issue by rodlilearns** [ComplianceAsCode/content#10046]
#### Share the context

The Ansible Remediation Role for RHEL 9 ACSC ISM Official Profile has a failure point.

#### Description of problem:

The task `Get all world-writable directories with no sticky bits set` fails.

#### Proposed change:

The tasks uses `set -o pipefail issue` which bypasses a non-zero return code if a shell exits with a non-zero return code.

However, we don't want this to fail the task.

I added a `ignore_errors: true` at the end of the task, to keep the playbook going.

#### References:

1.https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425#set--e--u--x--o-pipefail

**Comment by marcusburghardt** [comment]
We can use the macro introduced by https://github.com/ComplianceAsCode/content/pull/10912
I am working on a PR to update the `dir_perms_world_writable_sticky_bits` rule.
