### ISSUE TITLE
ansible-machine-hardening CIS Server Level 2 failed on package_rpcbind_removed

### ISSUE THREAD

**Issue by comps** [ComplianceAsCode/content#10081]
#### Description of problem:
```
Rules not passing after remediation:
xccdf_org.ssgproject.content_rule_package_rpcbind_removed - fail 
```

#### SCAP Security Guide Version:
master as of 2023-01-16

#### Operating System Version:
RHEL-9.2 / 8.8 / 7.9+EUS

#### Steps to Reproduce:

1. `oscap xccdf eval --progress --profile xccdf_org.ssgproject.content_profile_cis --results cis-xccdf-results.xml --report cis.html /ssg-rhel8-ds.xml`
2.
3.
4.

**Comment by marcusburghardt** [comment]
This issue was also present in the weekly productization tests with master of 2023-01-21.

**Comment by mildas** [comment]
`rpcbind` package is `beakerlib` dependency and gets installed right after machine reboot.
I have excluded the rule from test - https://src.fedoraproject.org/tests/scap-security-guide/pull-request/31
