### ISSUE TITLE
file_permissions_unauthorized_world_writable failing after reboot

### ISSUE THREAD

**Issue by marcusburghardt** [ComplianceAsCode/content#10112]
#### Description of problem:

The `file_permissions_unauthorized_world_writable` rule is failing after reboot when the system is scanned and remediated using `anssi_bp28_high` profile.

#### SCAP Security Guide Version:

master as of 2023-01-21

#### Operating System Version:

RHEL9

#### Steps to Reproduce:

1. Scan and remediate the system using `anssi_bp28_high` profile.
2. Reboot the system.
3. Scan the system again after reboot.
4. The `xccdf_org.ssgproject.content_rule_file_permissions_unauthorized_world_writable` rule will fail.

#### Actual Results:

xccdf_org.ssgproject.content_rule_file_permissions_unauthorized_world_writable - fail

#### Expected Results:

xccdf_org.ssgproject.content_rule_file_permissions_unauthorized_world_writable - pass

#### Additional Information/Debugging Steps:

**Comment by vojtapolasek** [comment]
@marcusburghardt  thank you for reporting the issue. I was not able to reproduce the problem on latest RHEL 9. Moreover, I tested upstream productization runs and all the files reported as world writable in the report are related to the testing infrastructure. I think this can be closed. Do you agree?

**Comment by marcusburghardt** [comment]
> @marcusburghardt thank you for reporting the issue. I was not able to reproduce the problem on latest RHEL 9. Moreover, I tested upstream productization runs and all the files reported as world writable in the report are related to the testing infrastructure. I think this can be closed. Do you agree?

@vojtapolasek , I didn't check the reported files but if they were created after the remediation, by the testing infrastructure, I agree.
