### ISSUE TITLE
Request Merge Rights

### ISSUE THREAD

**Issue by teacup-on-rockingchair** [ComplianceAsCode/content#10130]
#### Github ID:

* [teacup-on-rockingchair](https://github.com/teacup-on-rockingchair)

#### About me:

* My name is Yavor Georgiev and I am Consultant working with SUSE on the project for the last two years
* I have been part of the efforts to add support for SUSE platforms of the DISA, PCI-DSS, ANSSI and CIS efforts
* As well I have contributed to some test procedures and  templates used by the project

#### Reason for having merge rights:

*  Products (SUSE)
*  Product-specific profiles
*  Shared resources

#### List of PRs:

1. #9990 
2. #9871
3. #9613 
4. #9484 
5. #9419 
6. #9195

**Comment by Mab879** [comment]
Thanks for volunteering! I approve.

**Comment by mildas** [comment]
Amazing! I approve.

**Comment by jan-cerny** [comment]
This is very valuable work! I approve.

**Comment by marcusburghardt** [comment]
Yavor is contributing with significant improvements in the project through high quality PRs. I approve.

**Comment by marcusburghardt** [comment]
Since this request already achieved 2 more approvals than the necessary, it would be great to give you a live welcome in order to conclude this process. I will contact you via Gitter to find a suitable time. Thanks again.

**Comment by marcusburghardt** [comment]
Project maintainers came together in a welcome session for Yavor on 2023-04-21. Unfortunately, not all maintainers were able to attend the session. I introduced Yavor and highlighted some of his contributions to the project. We are happy to welcome you Yavor!

As of now, Yavor is officially a project maintainer and a reference for SUSE-related topics.
