### ISSUE TITLE
products/alinux2 && products/alinux3: fix some missing rules in the cis profile.

### ISSUE THREAD

**Issue by hustliyilin** [ComplianceAsCode/content#10137]
#### Description of problem: There are some missing rules updated by this repo recently, so we need to  
 update them in both Alibaba Cloud Linux 2 and Alibaba Cloud Linux 3.

**Comment by Mab879** [comment]
@hustliyilin Can you please confirm that this can be closed since #10138 has been merged? If more work needs to be done that's fine, I just wanted to check.

**Comment by hustliyilin** [comment]
OK, thanks. I close it now.
