### ISSUE TITLE
Request Merge Rights

### ISSUE THREAD

**Issue by Xeicker** [ComplianceAsCode/content#10176]
#### Github ID:

* @Xeicker 

#### About me:

* I'm a security assurance engineer at Oracle
* I'm in the team maintaining scap-security-guide package for OL distros
* My interactions with this project has been updating OL content, or updating generic content, when it affects Oracle products

#### Reason for having merge rights:

I would like to be granted merge/commit rights on the following areas

* Products (for Oracle products)
* Product-specific profiles (also for profiles for the Oracle products)

#### List of PRs:

1. https://github.com/ComplianceAsCode/content/pull/9967
1. https://github.com/ComplianceAsCode/content/pull/10123
1. https://github.com/ComplianceAsCode/content/pull/9935
1. https://github.com/ComplianceAsCode/content/pull/9919
1. https://github.com/ComplianceAsCode/content/pull/9751
1. https://github.com/ComplianceAsCode/content/pull/9693

**Comment by ggbecker** [comment]
I approve.

**Comment by evgenyz** [comment]
@Mab879, @ggbecker, @marcusburghardt What is the status of the request? Can we close the bug?

**Comment by marcusburghardt** [comment]
> @Mab879, @ggbecker, @marcusburghardt What is the status of the request? Can we close the bug?

No! I am taking care of this request.

**Comment by freddieRv** [comment]
I approve as well!

**Comment by marcusburghardt** [comment]
I also approve.
Since this request already achieved more than the necessary approvals, it would be great to give you a live welcome in order to conclude this process. I will contact you via Gitter to find a suitable time. Thanks again.

**Comment by marcusburghardt** [comment]
Project maintainers came together in a Welcome Session for Edgar on 2024-04-23.
From now on, Edgar is officially a project maintainer and reference on topics related to Oracle.
