### ISSUE TITLE
Rule firewalld_sshd_port_enabled fails some test scenarios

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#10171]
#### Description of problem:
During our review of productization test output of "/CoreOS/scap-security-guide/Sanity/test-rules-scenarios-per-rule (Regression 1/2)" we encountered that some test scenarios for rule rule_firewalld_sshd_port_enabled fail with both Ansible and Bash remediations when Automatus was executed in "rule" mode.

#### SCAP Security Guide Version:
Current upstream master as of 2023-02-04 as of HEAD 40118e3

#### Operating System Version:
RHEL 8 and RHEL 9

#### Steps to Reproduce:

1.  python3 /tmp/tmp.AvvFMWQIt9/rpmbuild/BUILD/scap-security-guide-0.1.67/tests/test_suite.py rule                 --libvirt qemu:///system test_suite_vm                 --datastream /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml                 --mode online                 --remediate-using bash --slice 1 2                 --duplicate-templates                 --no-reports                                  audit_rules_privileged_commands selinux_all_devicefiles_labeled mount_option_nodev_removable_partitions mount_option_noexec_removable_partitions mount_option_nosuid_removable_partitions selinux_policytype sshd_set_idle_timeout use_pam_wheel_for_su grub2_admin_username grub2_uefi_password selinux_state sshd_rekey_limit kernel_trust_cpu_rng package_rsyslog_installed gnome_gdm_disable_xdmcp auditd_audispd_syslog_plugin_activated no_shelllogin_for_systemaccounts ensure_redhat_gpgkey_installed accounts_user_interactive_home_directory_exists file_groupownership_home_directories file_permissions_home_directories chronyd_or_ntpd_set_maxpoll file_permissions_sshd_private_key accounts_passwords_pam_faillock_deny accounts_passwords_pam_faillock_deny_root accounts_passwords_pam_faillock_interval accounts_passwords_pam_faillock_unlock_time accounts_password_pam_unix_remember no_empty_passwords display_login_attempts accounts_password_pam_pwhistory_remember_system_auth accounts_password_pam_pwhistory_remember_password_auth sudo_custom_logfile firewalld_sshd_port_enabled configure_openssl_crypto_policy rsyslog_remote_tls rsyslog_remote_tls_cacert ssh_client_rekey_limit sshd_set_keepalive audit_basic_configuration audit_immutable_login_uids audit_ospp_general accounts_passwords_pam_faillock_enforce_local sysctl_kernel_unprivileged_bpf_disabled_accept_default

#### Actual Results:
some rules are evaluated as pass instead of expected fail during initial stage

```
INFO - xccdf_org.ssgproject.content_rule_firewalld_sshd_port_enabled
INFO - Script customized_zone_configured.pass.sh using profile (all) OK
ERROR - Script customized_zone_without_ssh.fail.sh using profile (all) found issue:
ERROR - Rule evaluation resulted in pass, instead of expected fail during initial stage 
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_firewalld_sshd_port_enabled'.
INFO - Script new_zone_configured.pass.sh using profile (all) OK
ERROR - Script new_zone_without_ssh.fail.sh using profile (all) found issue:
ERROR - Rule evaluation resulted in pass, instead of expected fail during initial stage 
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_firewalld_sshd_port_enabled'.
ERROR - Script only_nics_configured.fail.sh using profile (all) found issue:
ERROR - Rule evaluation resulted in pass, instead of expected fail during initial stage 
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_firewalld_sshd_port_enabled'.
INFO - Script only_zones_configured.fail.sh using profile (all) OK
INFO - Script zones_and_nics_configured.pass.sh using profile (all) OK
INFO - Script zones_and_nics_ok_no_custom_files.pass.sh using profile (all) OK
INFO - Script zones_and_nics_ok_port_changed.pass.sh using profile (all) OK
```

#### Expected Results:
all test scenarios pass

#### Additional Information/Debugging Steps:

no

**Comment by marcusburghardt** [comment]
@jan-cerny , could you confirm which OpenSCAP version was used, please? This should be already fixed by #10162 , which was merged today.

**Comment by marcusburghardt** [comment]
> @marcusburghardt openscap `1.3.7-1.el8` was used.

Thanks for confirming it was already `1.3.7`.
> 
> Productization build was created from Friday's master thus it's expected to fail as #10162 wasn't merged yet.

Yes, as I mentioned in the my previous comment, the PR was merged today and the issue should be already fixed. We only need to wait the new tests to confirm.

**Comment by jan-cerny** [comment]
Yes, openscap-1.3.7-1.el9.x86_64.rpm and openscap-1.3.7-1.el8.x86_64.rpm were used in the productization run and the SSG is upstream master as of 2023-02-04 as of HEAD https://github.com/ComplianceAsCode/content/commit/40118e39a1f168077bf6ef33e56af3cd3c8c11a7.

**Comment by marcusburghardt** [comment]
I can confirm it is fixed for RHEL8 and RHEL9, but it is now manifested in RHEL7. This is because RHEL7 is not yet using openscap-scanner 1.3.7. The `firewalld_sshd_port_enabled` rule was updated following a bug fix in the `xmlcontent` probe in the scanner, as mentioned in #10162. It should be fixed in RHEL7 once openscap-scanner is updated there.

**Comment by mildas** [comment]
`firewalld_sshd_port_enabled` is not part of any RHEL7 profile and so it has been unselected from RHEL7 tests. On RHEL8 and RHEL9 the rule passes. Closing

**Comment by jan-cerny** [comment]
FTR we have this reported in https://bugzilla.redhat.com/show_bug.cgi?id=2176081
