### ISSUE TITLE
Miss report sshd variables

### ISSUE THREAD

**Issue by elacour** [ComplianceAsCode/content#10197]
#### Description of problem:

anssi_np_nt28_high compliance run against debian 11 wrongly reports that some values (ClientAliveCountMax, ClientAliveInterval) are not optimal, thougt there have been set in a file in /etc/ssh/sshd_config.d/

#### SCAP Security Guide Version:
1.3.7

#### Operating System Version:
Debian 11

#### Steps to Reproduce:

1. Install a debian 11 system
2. Put a file "hardening.conf" in /etc/ssh/sshd_config.d/ with content: "ClientAliveCountMax 0"
3. restart ssh service
4. run oscap check for debian 11, profile anssi_np_nt28_high

#### Actual Results:
Set SSH Client Alive Count Max to zero failed (medium)

#### Expected Results:
Set SSH Client Alive Count Max to zero pass.

#### Additional Information/Debugging Steps:

Best would be to check running ssh variables with "sshd -T | grep -i ClientAliveCountMax. Or at least check all files in /etc/ssh/sshd_config.d/ if any.

**Comment by a-skr** [comment]
Checking running ssh variables would not work when scanning containers or VM images offline.

**Comment by Mab879** [comment]
Due to the limits of OVAL we cannot check the running config. So unfortunately our current checks are the best we can do.
