### ISSUE TITLE
Missing Ubuntu 18.04 STIG

### ISSUE THREAD

**Issue by candrews** [ComplianceAsCode/content#10208]
#### Description of problem:
DISA publishes a STIG document for Ubuntu 18.04 on their download site at https://public.cyber.mil/stigs/downloads/

The specific archive is: https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/U_CAN_Ubuntu_18-04_LTS_V2R10_STIG.zip

However, ComplianceAsCode doesn't seem to have this STIG.

#### SCAP Security Guide Version:
[v0.1.66](https://github.com/ComplianceAsCode/content/releases/tag/v0.1.66)

#### Operating System Version:
Ubuntu 18.04

#### Steps to Reproduce:

1. Extract [scap-security-guide-0.1.66.zip](https://github.com/ComplianceAsCode/content/releases/download/v0.1.66/scap-security-guide-0.1.66.zip)
2. Run `oscap info ssg-ubuntu1804-ds.xml`

#### Actual Results:
```
$ oscap info ssg-ubuntu1804-ds.xml 
Document type: Source Data Stream
Imported: 2023-02-03T04:33:37

Stream: scap_org.open-scap_datastream_from_xccdf_ssg-ubuntu1804-xccdf.xml
Generated: (null)
Version: 1.3
Checklists:
	Ref-Id: scap_org.open-scap_cref_ssg-ubuntu1804-xccdf.xml
		Status: draft
		Generated: 2023-02-03
		Resolved: true
		Profiles:
			Title: Profile for ANSSI DAT-NT28 Average (Intermediate) Level
				Id: xccdf_org.ssgproject.content_profile_anssi_np_nt28_average
			Title: Profile for ANSSI DAT-NT28 High (Enforced) Level
				Id: xccdf_org.ssgproject.content_profile_anssi_np_nt28_high
			Title: Profile for ANSSI DAT-NT28 Minimal Level
				Id: xccdf_org.ssgproject.content_profile_anssi_np_nt28_minimal
			Title: Profile for ANSSI DAT-NT28 Restrictive Level
				Id: xccdf_org.ssgproject.content_profile_anssi_np_nt28_restrictive
			Title: CIS Ubuntu 18.04 LTS Benchmark
				Id: xccdf_org.ssgproject.content_profile_cis
			Title: Standard System Security Profile for Ubuntu 18.04
				Id: xccdf_org.ssgproject.content_profile_standard
		Referenced check files:
			ssg-ubuntu1804-oval.xml
				system: http://oval.mitre.org/XMLSchema/oval-definitions-5
			ssg-ubuntu1804-ocil.xml
				system: http://scap.nist.gov/schema/ocil/2
Checks:
	Ref-Id: scap_org.open-scap_cref_ssg-ubuntu1804-oval.xml
	Ref-Id: scap_org.open-scap_cref_ssg-ubuntu1804-ocil.xml
	Ref-Id: scap_org.open-scap_cref_ssg-ubuntu1804-cpe-oval.xml
Dictionaries:
	Ref-Id: scap_org.open-scap_cref_ssg-ubuntu1804-cpe-dictionary.xml
```

Note that there is no profile with id `xccdf_org.ssgproject.content_profile_stig`

#### Expected Results:
There should be a profile with id `xccdf_org.ssgproject.content_profile_stig` for Ubuntu 18.04.

**Comment by dodys** [comment]
We (Canonical) don't have any plans on having this on ComplianceAsCode, as we only started doing DISA STIG implementations with 20.04, but feel free to send PRs to add it and we will gladly review it.

**Comment by dodys** [comment]
This bug has been open for a while and there was no contributions to it.
Therefore I'm closing it as not planned and if someone ever contributes it, we will gladly review it.
