### ISSUE TITLE
test scenarios for rule selinux_all_devicefiles_labeled are failing on RHEL 9

### ISSUE THREAD

**Issue by vojtapolasek** [ComplianceAsCode/content#10232]
#### Description of problem:
Some test scenarios for the rule mentioned in the title are failing.

#### SCAP Security Guide Version:
master as of eab94a2ffa373afdf47951fc2b0c299c87c8d7b5

#### Operating System Version:
RHEL 9

#### Steps to Reproduce:

1. ./build_product rhel9
2.cd tests/
3. python automatus.py rule --libvirt qemu:///system rhel9 selinux_all_devicefiles_labeled

#### Actual Results:
Following errors appear:
ERROR - Script regular_file_device_t.pass.sh using profile (all) found issue:
ERROR - Rule evaluation resulted in fail, instead of expected pass during initial stage 
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_selinux_all_devicefiles_labeled'.
ERROR - Script symlink_with_wrong_label.pass.sh using profile (all) found issue:
ERROR - Rule evaluation resulted in fail, instead of expected pass during initial stage 
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_selinux_all_devicefiles_labeled'.
INFO - xccdf_org.ssgproject.content_rule_selinux_policytype

#### Expected Results:
No errors appear during tests.

**Comment by mildas** [comment]
Issue is still relevant.

**Comment by Mab879** [comment]
I'm having issues reproducing this locally. This might be something that only in the testing environment.

```
$ ./automatus.py rule --libvirt qemu:///system automatus_rhel_9_2 --datastream ../build/ssg-rhel9-ds.xml selinux_all_devicefiles_labeled
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/mburket/review/ComplianceAsCode/content/tests/logs/rule-custom-2023-03-14-1429/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_selinux_all_devicefiles_labeled
INFO - Script block_device_device_t.fail.sh using profile (all) OK
WARNING - No remediation is available for rule 'xccdf_org.ssgproject.content_rule_selinux_all_devicefiles_labeled'.
INFO - Script char_device_unlabeled_t.fail.sh using profile (all) OK
WARNING - No remediation is available for rule 'xccdf_org.ssgproject.content_rule_selinux_all_devicefiles_labeled'.
INFO - Script regular_file_device_t.pass.sh using profile (all) OK
INFO - Script symlink_with_wrong_label.pass.sh using profile (all) OK
```

**Comment by Mab879** [comment]
This seems to be a RHEL 9.3+ only bug.

**Comment by Mab879** [comment]
The device at issue appears to be `/dev/userfaultfd`. There is a BZ for this https://bugzilla.redhat.com/show_bug.cgi?id=2175290.
