### ISSUE TITLE
Build and Test AIDE Database | Incorrect for ubuntu profiles on ansible snippet

### ISSUE THREAD

**Issue by samwozencroft** [ComplianceAsCode/content#10257]
#### Description of problem:

Current block is:

name: Build and Test AIDE Database
command: /usr/sbin/aide --init
changed_when: true
when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]
tags:

CJIS-5.10.1.3
NIST-800-53-CM-6(a)
PCI-DSS-Req-11.5
aide_build_database
low_complexity
low_disruption
medium_severity
no_reboot_needed
restrict_strategy

Correct block should be:

name: Build and Test AIDE Database
command: /usr/bin/aide --init
changed_when: true
when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]
tags:
CJIS-5.10.1.3
NIST-800-53-CM-6(a)
PCI-DSS-Req-11.5
aide_build_database
low_complexity
low_disruption
medium_severity
no_reboot_needed
restrict_strategy

#### Details:

This content is not aligned with content from _<insert the other party name here>_

The misalignment affects these profiles:

- Ubuntu

The misalignment affects these rules:

- AIDE Database

#### Outcome:

- [ ] This project's content can be  improved:
  - [ ] Check needs to be improved. AIDE Build and Test check
  - [ ] Remediation needs to be improved.
- [ ] The external content's check is faulty - the other party needs to be notified, they have work to do.

#### SCAP Security Guide Version:

OpenSCAP command line tool (oscap) 1.2.17
Copyright 2009--2017 Red Hat Inc., Durham, North Carolina.

==== Supported specifications ====
XCCDF Version: 1.2
OVAL Version: 5.11.1
CPE Version: 2.3
CVSS Version: 2.0
CVE Version: 2.0
Asset Identification Version: 1.1
Asset Reporting Format Version: 1.1
CVRF Version: 1.1

==== Capabilities added by auto-loaded plugins ====
SCE Version: 1.0 (from libopenscap_sce.so.8)

**Comment by dodys** [comment]
@samwozencroft could you please test the change made in the draft PR mentioned above and let us know of any issues.
