### ISSUE TITLE
RHEL7 GUI Kickstart install of CIS Workstation Level 2 aborts

### ISSUE THREAD

**Issue by yuumasato** [ComplianceAsCode/content#10280]
#### Description of problem:
Installation of a RHEL7 GUI via Kickstart with CIS Worksation Level 2 fails.
The Anaconda logs seem to indicate that the mountpoints don't exist.

This might have the same root cause as https://github.com/ComplianceAsCode/content/issues/10277
I decided to file two issues, as the error outputs are different.

#### SCAP Security Guide Version:
Upstream as of 2ce85d7

#### Operating System Version:
RHEL7

#### Steps to Reproduce:

Example command:
1. virt-install --name=test_suite_vm             --memory=4096 --vcpus=2 --hvm             --network bridge=virbr0 --disk path=<disk image path>,size=20             --location <rhel7 compose url> --initrd-inject ssg-rhel7-cis_workstation_l2-ks.cfg --wait 0             --graphics vnc --extra-args "ks=file:/ssg-rhel7-cis_workstation_l2-ks.cfg ksdevice=eth0 console=ttyS0 inst.graphical notmux systemd.journald.forward_to_console=1" --noautoconsole
2.
3.
4.

#### Actual Results:
Installation fails with:
```
[  170.643805] anaconda[1454]: spoke is ready: OSCAPSpoke
[  170.644756] anaconda[1454]: setting OSCAPSpoke status to: Everything okay
[  170.672144] anaconda[1454]: Thread Done: OSCAPguiWaitForDataFetchThread (139806815905536)
[  170.711255] anaconda[1454]: spoke is ready: OSCAPSpoke
[  170.712303] anaconda[1454]: setting OSCAPSpoke status to: Misconfiguration detected
[  170.729475] anaconda[1454]: spoke is ready: OSCAPSpoke
[  170.730316] anaconda[1454]: setting OSCAPSpoke status to: Misconfiguration detected
[  177.021303] chronyd[1675]: Source 45.33.53.84 replaced with 38.229.54.9
[ 2241.668795] chronyd[1675]: Source 45.83.234.123 replaced with 104.194.8.227
/usr/share/beakerlib/testing.sh: line 896: 36336 Killed                  timeout --signal=KILL 1h unbuffer virsh console test_suite_vm
```

#### Expected Results:
Installation finishes with profile applied.

**Comment by mildas** [comment]
>  The Anaconda logs seem to indicate that the mountpoints don't exist.
Yes, it is the same problem as for RHEL9 - missing `/dev/shm` partition in kickstart.
