### ISSUE TITLE
account_passwords_pam_faillock_dir is missing an SRG reference

### ISSUE THREAD

**Issue by comps** [ComplianceAsCode/content#10310]
#### Description of problem:
A downstream test has reported that "SRG" is "missing" from the STIG profile for `account_passwords_pam_faillock_dir`.

#### SCAP Security Guide Version:
master as of 2023-03-06

#### Operating System Version:
2023-03-04 compose of RHEL-9.2

**Comment by jan-cerny** [comment]
@comps Could the downstream test be changed to a CTest test? At the first sight, I think that can only perform some XPath query and that's possible easily.

**Comment by jan-cerny** [comment]
> Could the downstream test be changed to a CTest test? At the first sight, I think that can only perform some XPath query and that's possible easily.

That way we would prevent introducing these issues to upstream before merging.

**Comment by jan-cerny** [comment]
@comps That's great news! I love hearing this! My idea was that this type of test can be simplified so much that it can be even included directly in this repo.
