### ISSUE TITLE
Results XCCDF has `reference` element with empty `href` violating specification

### ISSUE THREAD

**Issue by candrews** [ComplianceAsCode/content#10332]
#### Description of problem:
The [XCCDF 1.2 Specification section 6.2.6](https://csrc.nist.gov/CSRC/media/Publications/nistir/7275/rev-4/final/documents/nistir-7275r4_updated-march-2012_clean.pdf) says that `<reference`> elements can have an `href`  property with a URI.
![image](https://user-images.githubusercontent.com/194713/224780461-2222ed6e-f774-4a29-abd0-c77e7504b1bf.png)

However, ComplianceAsCode is generating `href` values of the empty string. It should instead either set the `href` to a URI, or not have an `href` property at all.

#### SCAP Security Guide Version:
0.1.66
OpenSCAP version 1.3.8

#### Operating System Version:
Linux

#### Steps to Reproduce:

1. `sudo oscap-podman ubuntu:20.04 xccdf eval --fetch-remote-resources --results report.xml --profile xccdf_org.ssgproject.content_profile_stig /usr/share/xml/scap/ssg/content/ssg-ubuntu2004-ds.xml`
2. Look for `<reference href=""`

#### Actual Results:
There are many cases of `<reference`> elements with `href` values of empty string.

#### Expected Results:
All `<reference>` elements should have `href` properties with a URI value.

**Comment by Mab879** [comment]
The two PRs above have been merged. I have reviewed data streams and this is no longer an issue. Thanks again for reporting.
