### ISSUE TITLE
CPE machine and container identification check fails

### ISSUE THREAD

**Issue by cortesana** [ComplianceAsCode/content#10356]
#### Description of problem:
Running evaluation against the host system returns an unexpected result in `ssg-installed_env_is_a_machine` and `ssg-installed_env_is_a_container` definitions.

#### SCAP Security Guide Version:
Upstream of `c1a404e`

#### Operating System Version:
RHEL7, RHEL8, RHEL9

#### Steps to Reproduce:

1. Build RHEL9 datastream (you may also build RHEL7 or RHEL8)
2. Run `oscap oval eval --id oval:ssg-installed_env_is_a_container:def:1 --oval-id scap_org.open-scap_cref_ssg-rhel9-oval.xml /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml`
3. Run `oscap-vm image /var/lib/libvirt/images/rhel9_image.qcow2 oval eval --id oval:ssg-installed_env_is_a_machine:def:1  --oval-id scap_org.open-scap_cref_ssg-rhel9-oval.xml /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml`

#### Actual Results:
`OpenSCAP Error: No definition with ID: oval:ssg-installed_env_is_a_container:def:1 in definition model.`
`OpenSCAP Error: No definition with ID: oval:ssg-installed_env_is_a_machine:def:1 in definition model.`

#### Expected Results:
The evaluation is run successfully and there are no errors.

**Comment by Mab879** [comment]
@jan-cerny I reverted 43932abe800ed8d1ee556d61035549e898fcb614 locally and that seemed to fix the issue. Do you have a better idea? Should we be just copy over the two OVAL files we need?

**Comment by cortesana** [comment]
Hello @jan-cerny,
The context of this issue is a failure in the `Sanity/cpe-machine-container` productisation test that appeared in versions RHEL7, RHEL8 and RHEL9.
The steps to reproduce provided are directly derived from the productisation test.

**Comment by jan-cerny** [comment]
This was an issue in the test Sanity/cpe-machine-container and after this test was fixed it is passing in this week productization run on RHEL 7, 8 and 9.
