### ISSUE TITLE
In RHEL9 DS there is no definition for rule rsyslog_files_ownership or rsyslog_files_groupownership

### ISSUE THREAD

**Issue by hunter86bg** [ComplianceAsCode/content#10380]
#### Description of problem:
At https://github.com/ComplianceAsCode/content/blob/master/controls/cis_rhel9.yml#L1670-L1679 we have a definition for 2 rules that are missing in the DS file for RHEL9, but the status is set to 'automated'.

#### SCAP Security Guide Version:
scap-security-guide-0.1.66-1.el9_1.noarch

#### Operating System Version:
RHEL 9.1

#### Steps to Reproduce:

1. [cis_rhel9.xml](https://github.com/ComplianceAsCode/content/blob/master/controls/cis_rhel9.yml#L1670-L1679) claims that the rule is automated
2. Verify that there are no bash/ansible files in [ rsyslog_files_groupownership](https://github.com/ComplianceAsCode/content/tree/master/linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_files_groupownership)
3. Verify that there are no bash/ansible files in [rsyslog_files_ownership](https://github.com/ComplianceAsCode/content/tree/master/linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_files_ownership)
4. The rules do not exist in /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml

#### Actual Results:
The rule to exist and adjust the system to a compliant state.

#### Expected Results:
Either the rules exist in ssg-rhel9-ds.xml or the status is set to  'partial' at https://github.com/ComplianceAsCode/content/blob/master/controls/cis_rhel9.yml#L1675

**Comment by hunter86bg** [comment]
@jan-cerny ,

I'm not sure where you see it but I clearly do not see the rule in the CIS L1 Server profile:

```
# xmllint --xpath "//*[local-name()='data-stream-collection']/*[local-name()='component' and @id='scap_org.open-scap_comp_ssg-rhel9-xccdf.xml']/*[local-name()='Benchmark' and @id='xccdf_org.ssgproject.content_benchmark_RHEL-9']/*[local-name()='Profile' and @id='xccdf_org.ssgproject.content_profile_cis_server_l1']/*[local-name()='select']/@*[local-name()='idref' or local-name()='selected']" /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml | paste -d " " - - | grep rsyslog
 idref="xccdf_org.ssgproject.content_rule_package_rsyslog_installed"  selected="true"
 idref="xccdf_org.ssgproject.content_rule_rsyslog_files_permissions"  selected="true"
 idref="xccdf_org.ssgproject.content_rule_rsyslog_nolisten"  selected="true"
 idref="xccdf_org.ssgproject.content_rule_service_rsyslog_enabled"  selected="true"
 idref="xccdf_org.ssgproject.content_group_rsyslog_sending_messages"  selected="false"
```

**Comment by jan-cerny** [comment]
Aha! I now understand when the confusion comes from, it's the profile selections. In scap-security-guide-0.1.66-1.el9_1.noarch, the rules were present in the data stream, but they were not selected in cis_server_l1 whereas in current master they are selected in that profile. But, the control files are always in sync with profile selections because internally the profile selections are generated from the control files. So let's conclude this as fixed by https://github.com/ComplianceAsCode/content/pull/10241

**Comment by hunter86bg** [comment]
Does this mean that if I enable the 2 rules in the tailor file, they will be also evaluated ?
