### ISSUE TITLE
Website install instructions don't work for Ubuntu 22.04

### ISSUE THREAD

**Issue by chrisposito** [ComplianceAsCode/content#10396]
#### Description of problem:
[https://www.open-scap.org/security-policies/scap-security-guide/#install](https://www.open-scap.org/security-policies/scap-security-guide/#install) states:

> You can install SCAP Security Guide on Ubuntu 18.04 and newer using apt:
> 
> `apt install ssg-base ssg-debderived ssg-debian ssg-nondebian ssg-applications`
> 

This doesn't work. Result on an up to date Ubuntu 22.04 LTS system is:
`sudo apt install ssg-base ssg-debderived ssg-debian ssg-nondebian ssg-applications
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package ssg-base
E: Unable to locate package ssg-debderived
E: Unable to locate package ssg-debian
E: Unable to locate package ssg-nondebian
E: Unable to locate package ssg-applications
`
#### SCAP Security Guide Version:
N/A

#### Operating System Version:
Ubuntu 22.04.2 LTS

#### Steps to Reproduce:

1. Follow the website provided installation steps for Ubuntu 18.04+ on Ubuntu 22.04

#### Actual Results:
`sudo apt install ssg-base ssg-debderived ssg-debian ssg-nondebian ssg-applications
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package ssg-base
E: Unable to locate package ssg-debderived
E: Unable to locate package ssg-debian
E: Unable to locate package ssg-nondebian
E: Unable to locate package ssg-applications
`

#### Expected Results:
Installation completes

**Comment by Mab879** [comment]
@dodys any thoughts on this?

**Comment by dodys** [comment]
Ubuntu 22.04 doesn't have any of those packages because debian removed them back in 2021, for more information:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=993368
They were re-added end of last year and will be available in 23.04.

**Comment by radekcrlik** [comment]
@dodys Hi, I can comfirm that I was able to install on Ubuntu 23.04. But I see no *-ds.xml files for Ubuntu 23.04. Only for version 22.04. But using this creates a report when all checks are marked as: notapplicable.

Does it mean that oscap cannot be used on Ubuntu 22.04 and 23.04?

**Comment by dodys** [comment]
> @dodys Hi, I can comfirm that I was able to install on Ubuntu 23.04. But I see no *-ds.xml files for Ubuntu 23.04. Only for version 22.04. But using this creates a report when all checks are marked as: notapplicable.
> 
> Does it mean that oscap cannot be used on Ubuntu 22.04 and 23.04?

We don't have CIS for non-LTS releases such as 23.04. CIS and DISA only publish benchmarks for LTS releases.
Therefore you should either use Ubuntu 20.04 or 22.04. For both you could either use our official tool [Ubuntu Security guide](https://ubuntu.com/security/certifications/docs/usg) or try to build from scratch.

I'm closing this bug for now.
