### ISSUE TITLE
mount_option_dev_shm_noexec fails after remediation

### ISSUE THREAD

**Issue by Mab879** [ComplianceAsCode/content#10391]
#### SCAP Security Guide Version:
https://github.com/ComplianceAsCode/content/commit/e544b5222e77f7f4d65372fc5cc059ca168a7181

#### Operating System Version: 
RHEL 8.8
RHEL 9.2
RHEL 7.9

#### Steps to Reproduce:

1. Install RHEL 8 with a GUI using the OSPP or STIG profile

#### Actual Results:
`mount_option_dev_shm_noexec` fails

#### Expected Results:
`mount_option_dev_shm_noexec` passes

#### Additional Information/Debugging Steps:
None

**Comment by marcusburghardt** [comment]
It is also failing in RHEL7.9

**Comment by evgenyz** [comment]
As far as I can see the rule `mount_option_dev_shm_noexec` is not selected in RHEL9 OSPP or STIG profiles. This is strange.
