### ISSUE TITLE
Bug Rules not detecting correctly on CentOS8

### ISSUE THREAD

**Issue by The-Linux-Guy** [ComplianceAsCode/content#10412]
#### Share the context

While applying CIS L1 Policy to CentOS 8 servers there appears to be an issue with a couple of rules

#### Description of problem:

Rule File path is incorrect for CentOS
xccdf_org.ssgproject.content_rule_grub2_uefi_password

Currently = /boot/efi/EFI/redhat/user.cfg
Correct = /boot/efi/EFI/centos/user.cfg

This is causing the rule not to work

Folder Paths causing issues here too
xccdf_org.ssgproject.content_rule_sysctl_net_ipv4_conf_all_accept_redirects

this line 
for f in /etc/sysctl.d/*.conf /run/sysctl.d/*.conf /usr/local/lib/sysctl.d/*.conf; do

these don't exist /run/sysctl.d/*.conf /usr/local/lib/sysctl.d/*.conf

the first one is correct though /etc/sysctl.d/*.conf Not sure how this is detecting though but also appears to be a false positive it is correctly set on the host but showing failed.

#### Proposed change:

Please see above

**Comment by Mab879** [comment]
CentOS 8 and CentOS Stream 8 are no longer supported. If this is still a bug on CentOS Stream 9+ please open separate issues for each bug.
