### ISSUE TITLE
Rule enable_authselect fails a test scenario

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#10429]
#### Description of problem:
During a review of #10427, we have discovered that the rule `enable_authselect` fails test scenarios `remediable.fail.sh` for both Bash and Ansible remediations.

#### SCAP Security Guide Version:
current upstream master as of HEAD 7a9bb5fc5d5599a0090a36f3c846739956134545 as of 2023-04-05

#### Operating System Version:
RHEL 8

#### Steps to Reproduce:

1. python3 tests/automatus.py rule --libvirt qemu:///system ssgts_rhel8  --scenario remediable.fail.sh enable_authselect
2. python3 tests/automatus.py rule --libvirt qemu:///system ssgts_rhel8 --remediate-using ansible --scenario remediable.fail.sh enable_authselect

#### Actual Results:
```
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/jcerny/work/git/scap-security-guide/logs/rule-custom-2023-04-05-0850/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_enable_authselect
INFO - Script remediable.fail.sh using profile (all) OK
ERROR - Rule evaluation resulted in error, instead of expected fixed during remediation stage 
ERROR - The remediation failed for rule 'xccdf_org.ssgproject.content_rule_enable_authselect'.
```

#### Expected Results:
The test scenario `remediable.fail.sh` doesn't error.

#### Additional Information/Debugging Steps:
The results after remediation visualized in a graph suggest that the reason of the fail is that symlinks `/etc/pam.d/fingerprint-auth` , `/etc/pam.d/smartcard-auth` and `/etc/pam.d/system-auth` do not exist after remediation.

**Comment by marcusburghardt** [comment]
It was likely caused by this commit https://github.com/ComplianceAsCode/content/commit/d72b598164fffc9a7dfb98f5a383ec6719e4cbce also part of https://github.com/ComplianceAsCode/content/pull/10348
