### ISSUE TITLE
[RFE] Implement recently added "30-pci-dss-v31.rules" audit rules into SSG PCI DSS profiles

### ISSUE THREAD

**Issue by iankko** [ComplianceAsCode/content#1044]
Steve Grubb (audit package maintainer for Red Hat and Fedora distributions) recently provided guidance of expected form of the syscall audit rules that should be implemented when the system compliance against [PCI DSS v3.1](https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-1.pdf) standard is attempted.

These rules:
&nbsp; &nbsp; [1] https://fedorahosted.org/audit/browser/trunk/rules/30-pci-dss-v31.rules?order=date

are going to be shipped in future versions of the audit package as audit guidance FWIW to PCI DSS v3.1 standard.

We need the:
- XCCDF,
- OVAL, and
- remediation parts

implemented in the currently provided PCI DSS profiles for `RHEL/6` and `RHEL/7` products.

**Comment by matejak** [comment]
The rule description is now insufficient to be acted upon.
