### ISSUE TITLE
Authselect Integrity Check Failed During Ansible Playbook Runs

### ISSUE THREAD

**Issue by Mab879** [ComplianceAsCode/content#10447]
#### Description of problem:

Playbooks that use auth_select

#### SCAP Security Guide Version:
43e268f

#### Operating System Version:
RHEL 9,2, RHEL 8.8, RHEL 7.9

#### Steps to Reproduce:

1. Run Playbooks that use rule with Authselect rules
2.
3.
4.

#### Actual Results:
```

TASK [Limit Password Reuse: password-auth - Informative message based on the authselect integrity check result] ***
fatal: [localhost]: FAILED! => {
    "assertion": "result_authselect_check_cmd.rc == 0",
    "changed": false,
    "evaluated_to": false,
    "msg": [
        "authselect integrity check failed. Remediation aborted!",
        "This remediation could not be applied because an authselect profile was not selected or the selected profile is not intact.",
        "It is not recommended to manually edit the PAM files when authselect tool is available.",
        "In cases where the default authselect profile does not cover a specific demand, a custom authselect profile is recommended."
    ]
}
````

#### Expected Results:
Playbook executes without failures 

#### Additional Information/Debugging Steps:

None

**Comment by marcusburghardt** [comment]
It is related to https://github.com/ComplianceAsCode/content/pull/10427.
We were aware that other issues could be reveled after the fix.

I will propose a fix for this new issue soon.

**Comment by marcusburghardt** [comment]
Actually, I already proposed a fix for this issue in this PR: https://github.com/ComplianceAsCode/content/pull/10430
