### ISSUE TITLE
Gate (AR / RHEL) / Build, Lint Ansible Roles on Fedora Latest (Container) (pull_request) failing

### ISSUE THREAD

**Issue by jhrozek** [ComplianceAsCode/content#10483]
#### Description of problem:
It looks like after upgrade to F-38, the ansible jobs are failing and blocking PRs. @ggbecker thinks that most likely a new version of ansible lint is triggering a new fail that we have not addressed yet or we don't waive it properly

this ticket tracks the issue

example of failing test:
https://github.com/ComplianceAsCode/content/actions/runs/4762488904/jobs/8504306684?pr=10476

#### Steps to Reproduce:

1.
2.
3.
4.

**Comment by Mab879** [comment]
This has been fixed on a temporary basis in #10484, which as been merged to master. I will keep this issue open as we need to figure out why this happens in F38.
