### ISSUE TITLE
utils/autoprodtyper.py not recognizing rules from controls file 

### ISSUE THREAD

**Issue by j-ode** [ComplianceAsCode/content#10513]
#### Description of problem:

The autoprodtyper.py script does nothing if the profile that it is used with uses a controls file only.

#### SCAP Security Guide Version:

Latest master

#### Operating System Version:

F37

#### Steps to Reproduce:

1. run ./utils/autoprodtyper.py <product> <profile> on a profile that uses a controls file and has rules that do not have the specified <product> in prodtype

#### Actual Results:

Nothing happens. I have to manually add the rules in question to the .profile file before the controls file is referenced so that the script picks them up and fixes the prodtype.

#### Expected Results:

The rules in the profile's controls file that do not have the <product> prodtype have it added correctly.

**Comment by Mab879** [comment]
Prodtypes are no longer a part of this project closing.
