### ISSUE TITLE
Bash remediation of mount_option template incorrectly handles commented lines

### ISSUE THREAD

**Issue by vojtapolasek** [ComplianceAsCode/content#10526]
#### Description of problem:

Recently merged PR introduces a change to OVAL which can correctly process also commented lines in /etc/fstab. The PR is https://github.com/ComplianceAsCode/content/pull/10518
Unfortunately, the Bash remediation does not work (produces error) in case the /etc/fstab contains a commented line which is correct, and this line is followed by an uncommented incorrect line.

#### SCAP Security Guide Version:

master as of cad3f18d8fc8d04aca15e6fa4145c39674539c72  

#### Operating System Version:

RHEL 8

#### Steps to Reproduce:

1. create this test scenario in shared/templates/mount_option/tests:
``` bash
#!/bin/bash

# platform = multi_platform_all
. $SHARED/partition.sh

clean_up_partition {{{ MOUNTPOINT }}}

create_partition
make_fstab_given_partition_line {{{ MOUNTPOINT }}} ext2 {{{ MOUNTOPTION }}}

# comment last line added above to be ignored
sed -Ei '${s/^/#/}' /etc/fstab

make_fstab_given_partition_line {{{ MOUNTPOINT }}} ext2 defaults

mount_partition {{{ MOUNTPOINT }}} || true
```
2. ./build_product rhel8
3. ce tests
4. python automatus.py template --libvirt qemu:///system rhel8 mount_option

#### Actual Results:

The created test scenario makes the scan finish with an error.

#### Expected Results:
The scenario should be passing.

#### Additional Information/Debugging Steps:
Ansible remediation works correctly.

**Comment by dodys** [comment]
I think that this PR might have fixed this issue:
https://github.com/ComplianceAsCode/content/pull/10754

**Comment by jan-cerny** [comment]
Unfortunately, the bug is still reproducible using the scenario above.

**Comment by dodys** [comment]
> Unfortunately, the bug is still reproducible using the scenario above.

this test already exists in `shared/templates/mount_option/tests/fstab_comment.pass.sh` and it is passing for me. I wonder if there's anything else that we are missing here.

**Comment by vojtapolasek** [comment]
@dodys  the test scenario you mention tests something else. The test scenario in the PR dewscription puts there a correct line and comments it out, then it adds wrong line. The test scenario you mention adds correct line, comments it out, then it adds correct line again.
