### ISSUE TITLE
Rule file_groupownership_sshd_private_key fails after remediation

### ISSUE THREAD

**Issue by cortesana** [ComplianceAsCode/content#10592]
#### Description of problem:

The `file_groupownership_sshd_private_key` rule is failing after remediation when checking the following profiles:
- CIS Workstation Level 2 with GUI.

#### Operating System Version:

`RHEL 9.2`, `RHEL 8.8`, `RHEL 7.9`

#### Steps to Reproduce:

1. Build RHEL9 datastream (you may also build RHEL7 or RHEL8)
2. Run
```
oscap xccdf eval         --profile xccdf_org.ssgproject.content_profile_cis_workstation_l2 --report  xccdf_org.ssgproject.content_profile_cis_workstation_l2.html         --results-arf xccdf_org.ssgproject.content_profile_cis_workstation_l2-xccdf-arf-results.xml         --results xccdf_org.ssgproject.content_profile_cis_workstation_l2-xccdf-results.xml --oval-results         /tmp/ssg-rhel9-ds.xml 2>/tmp/stderr.txt
```
3. Evaluate the results.

#### Actual Results:
```
xccdf_org.ssgproject.content_rule_file_groupownership_sshd_private_key - fail
```

#### Expected Results:
```
xccdf_org.ssgproject.content_rule_file_groupownership_sshd_private_key - pass
```

**Comment by mildas** [comment]
Passed in last productization. Closing
