### ISSUE TITLE
Rule file_permissions_sshd_private_key fails after remediation

### ISSUE THREAD

**Issue by cortesana** [ComplianceAsCode/content#10593]
#### Description of problem:

The `file_permissions_sshd_private_key` rule is failing after remediation when checking the following profiles:
- CIS Server Level 2 in the `Sanity/machine-hardening` test case.

#### Operating System Version:

`RHEL 8.8`

#### Steps to Reproduce:

1. Build RHEL8 datastream.
2. Run
```
oscap xccdf eval --progress --profile xccdf_org.ssgproject.content_profile_cis --results cis-xccdf-results.xml --report cis.html /ssg-rhel8-ds.xml
```
3. Evaluate the results.

#### Actual Results:
```
xccdf_org.ssgproject.content_rule_file_permissions_sshd_private_key - fail
```

#### Expected Results:
```
xccdf_org.ssgproject.content_rule_file_permissions_sshd_private_key - pass
```

#### Additional Information/Debugging Steps:

Related to [this issue](https://github.com/ComplianceAsCode/content/issues/10594).

**Comment by mildas** [comment]
Passed in last productization. Closing
