### ISSUE TITLE
firewalld_loopback_traffic rules failing after remediation

### ISSUE THREAD

**Issue by cortesana** [ComplianceAsCode/content#10613]
#### Description of problem:
The `firewalld_loopback_traffic_restricted` and `firewalld_loopback_traffic_trusted` rules are failing after remediation in the following testcases for these profiles:
- Sanity/ssg-kickstarts for CIS Server Level 2.
- Sanity/ssg-kickstarts for CIS Workstation Level 2 (GUI) .
- Sanity/ssg-kickstarts for CIS Workstation Level 2.

#### Operating System Version:

`RHEL 9.2`

#### Steps to Reproduce:

1. Build RHEL9 datastream.
2. Run
```
oscap xccdf eval         --profile xccdf_org.ssgproject.content_profile_cis --report  xccdf_org.ssgproject.content_profile_cis.html         --results-arf xccdf_org.ssgproject.content_profile_cis-xccdf-arf-results.xml         --results xccdf_org.ssgproject.content_profile_cis-xccdf-results.xml --oval-results         /tmp/ssg-rhel9-ds.xml 2>/tmp/stderr.txt

```
3. Evaluate the results.

#### Actual Results:
```
xccdf_org.ssgproject.content_rule_firewalld_loopback_traffic_restricted - fail
xccdf_org.ssgproject.content_rule_firewalld_loopback_traffic_trusted - fail
```

#### Expected Results:
```
xccdf_org.ssgproject.content_rule_firewalld_loopback_traffic_restricted - pass
xccdf_org.ssgproject.content_rule_firewalld_loopback_traffic_trusted - pass
```

**Comment by mildas** [comment]
@marcusburghardt Could you confirm it's same as `firewalld_sshd_port_enabled`?

https://github.com/ComplianceAsCode/content/issues/9746#issuecomment-1298701718
> The firewalld_sshd_port_enabled can't be remediated during installation as its remediation requires running firewalld which doesn't. Output from remediation:

> Running in chroot, ignoring command 'is-active'
Running in chroot, ignoring command 'is-active'
FirewallD is not running
Running in chroot, ignoring command 'restart'
FirewallD is not running
FirewallD is not running

**Comment by marcusburghardt** [comment]
> @marcusburghardt Could you confirm it's same as `firewalld_sshd_port_enabled`?
> 
> [#9746 (comment)](https://github.com/ComplianceAsCode/content/issues/9746#issuecomment-1298701718)
> 
> > The firewalld_sshd_port_enabled can't be remediated during installation as its remediation requires running firewalld which doesn't. Output from remediation:
> 
> > Running in chroot, ignoring command 'is-active'
> > Running in chroot, ignoring command 'is-active'
> > FirewallD is not running
> > Running in chroot, ignoring command 'restart'
> > FirewallD is not running
> > FirewallD is not running

I can confirm it is the same case @mildas 
```
Running in chroot, ignoring command 'is-active'
FirewallD is not running
FirewallD is not running
FirewallD is not running
```

**Comment by jan-cerny** [comment]
FTR I confirm this issue is still present in the current upstream master branch as of 2023-05-29 as of HEAD 47955e5289e104a1ebcb928caec593aea3af43d5 on RHEL 9.2 in downstream tests in "/CoreOS/scap-security-guide/Sanity/ssg-kickstarts for CIS Server Level 2",  "/CoreOS/scap-security-guide/Sanity/ssg-kickstarts for CIS Workstation Level 2" and "/CoreOS/scap-security-guide/Sanity/ssg-kickstarts for CIS Workstation Level 2 (GUI)" .

**Comment by marcusburghardt** [comment]
Like the `firewalld_sshd_port_enabled`, I believe this can also be waived for kickstarts tests.

**Comment by jan-cerny** [comment]
Both rules have been waived in the downstream test.
