### ISSUE TITLE
Error in rule accounts_umask_interactive_users

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#10658]
#### Description of problem:
During the downstream test `/CoreOS/scap-security-guide/Sanity/test-hardening-pkg-update PCI-DSS, OSPP, STIG_GUI (GUI)` the rule `accounts_umask_interactive_users` evaluates as `error` in the after-remediation scan using the STIG GUI profile.

#### SCAP Security Guide Version:
current upstream master branch as of 2023-05-29 as of HEAD https://github.com/ComplianceAsCode/content/commit/47955e5289e104a1ebcb928caec593aea3af43d5

#### Operating System Version:
RHEL 8.8

#### Steps to Reproduce:

1. ssh -o ServerAliveInterval=15 -q -tt admin@192.168.122.247 "echo admin123 | sudo -S oscap xccdf eval         --verbose DEVEL --verbose-log-file verbose.log         --progress --oval-results --remediate --profile xccdf_org.ssgproject.content_profile_stig_gui --report report.html         scap-security-guide-0.1.66-1.el8_4-ssg-rhel8-ds.xml 1>stdout 2>stderr"
2. ssh -o ServerAliveInterval=15 -q -tt admin@192.168.122.247 "echo admin123 | sudo -S oscap xccdf eval         --verbose DEVEL --verbose-log-file verbose.log         --progress --oval-results  --profile xccdf_org.ssgproject.content_profile_stig_gui --report report.html         scap-security-guide-0.1.66-1.el8_4-ssg-rhel8-ds.xml 1>stdout 2>stderr"

#### Actual Results:
xccdf_org.ssgproject.content_rule_accounts_umask_interactive_users:error

#### Expected Results:
no error

#### Additional Information/Debugging Steps:
There is `Waiving accounts_umask_interactive_users rule` in the test output log.

**Comment by mildas** [comment]
GUI creates binary file in home directory. It's again https://bugzilla.redhat.com/show_bug.cgi?id=2058536 and https://bugzilla.redhat.com/show_bug.cgi?id=2033246

**Comment by jan-cerny** [comment]
Can we skip this binary file in the OVAL?

**Comment by mildas** [comment]
@jan-cerny Let's ignore the error there. It is waived in many tests. Unfortunately `test-hardening-pkg-update` has waiving enabled only for Phase 4 (new package version), so it will fail there when hardening with old package.
