### ISSUE TITLE
Rule zipl_bootmap_is_up_to_date fails to remediate

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#10654]
#### Description of problem:
After applying the remediation for CUI profile and reboot the rule `zipl_bootmap_is_up_to_date` fails.

This happens on:

- RHEL 8 Ansible Playbook for CUI profile
- RHEL 8 with bash remediation performed by oscap
- RHEL 9 with bash remediation performed by oscap

This happens during the `/CoreOS/scap-security-guide/Sanity/ansible-machine-hardening CUI` and `/CoreOS/scap-security-guide/Sanity/machine-hardening CUI` downstream test.

This test fails only when executed on s390x architecture. It passes on all other architectures.

#### SCAP Security Guide Version:
current upstream master branch as of 2023-05-29 as of HEAD https://github.com/ComplianceAsCode/content/commit/47955e5289e104a1ebcb928caec593aea3af43d5

#### Operating System Version:
RHEL 8, RHEL 9

#### Steps to Reproduce:

RHEL 8 Ansible:

1. ansible-playbook  -i "localhost," -c local --skip-tags "ensure_gpgcheck_globally_activated,ensure_gpgcheck_local_packages,ensure_gpgcheck_never_disabled,ensure_gpgcheck_repo_metadata,ensure_redhat_gpgkey_installed,no_direct_root_logins,set_firewalld_default_zone,firewalld_sshd_disabled,service_sshd_disabled,iptables_sshd_disabled,sshd_disable_root_login,sshd_disable_empty_passwords,disable_host_auth,harden_sshd_crypto_policy,configure_etc_hosts_deny,sudo_add_noexec,accounts_password_set_max_life_existing,package_nfs-utils_removed,package_gssproxy_removed,accounts_password_set_max_life_existing,mount_option_.*,package_rsync_removed,package_rpcbind_removed,dir_perms_world_writable_sticky_bits,file_permissions_unauthorized_world_writable," /usr/share/scap-security-guide/ansible/rhel8-playbook-cui.yml
2. reboot
3. oscap xccdf eval --progress --profile xccdf_org.ssgproject.content_profile_cui --results cui-xccdf-results.xml --report cui.html /ssg-rhel8-ds.xml

On RHEL 8 with Bash remediation:
1. oscap xccdf eval --progress --remediate --profile xccdf_org.ssgproject.content_profile_cui --report /cui_remediate_report.html /ssg-rhel8-ds.xml
2. reboot
3. oscap xccdf eval --progress --profile xccdf_org.ssgproject.content_profile_cui --results cui-xccdf-results.xml --report cui.html /ssg-rhel8-ds.xml

On RHEL 9 with Bash remediation:

1. oscap xccdf eval --progress --remediate --profile xccdf_org.ssgproject.content_profile_cui --report /cui_remediate_report.html /ssg-rhel9-ds.xml
4. reboot
5. oscap xccdf eval --progress --profile xccdf_org.ssgproject.content_profile_cui --results cui-xccdf-results.xml --report cui.html /ssg-rhel9-ds.xml

#### Actual Results:
xccdf_org.ssgproject.content_rule_zipl_bootmap_is_up_to_date - fail

#### Expected Results:
xccdf_org.ssgproject.content_rule_zipl_bootmap_is_up_to_date - pass

#### Additional Information/Debugging Steps:

no

**Comment by ggbecker** [comment]
This rule is about checking if the 
`
  Make sure that <tt>/boot/bootmap</tt> is newer than <tt>/boot/loader/entries/*.conf</tt>
  and <tt>/etc/zipl.conf</tt>
`

And the ansible remediation does not consider files from `/boot/loader/entries/*.conf` so far, so it doesn't run the command to update the file:

https://github.com/ComplianceAsCode/content/blob/27d74f673dd6e0f50db7aff7dcc36bf70ea2e5ed/linux_os/guide/system/bootloader-zipl/zipl_bootmap_is_up_to_date/ansible/shared.yml#L19

Also note that this remediation applies only to RHEL8
https://github.com/ComplianceAsCode/content/blob/27d74f673dd6e0f50db7aff7dcc36bf70ea2e5ed/linux_os/guide/system/bootloader-zipl/zipl_bootmap_is_up_to_date/ansible/shared.yml#L1

This is most likely what's causing the issue.

One simple fix would be to run the command every time the same as in the bash remediation:
https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/bootloader-zipl/zipl_bootmap_is_up_to_date/bash/shared.sh

@yuumasato

**Comment by ggbecker** [comment]
It might make sense to think about rule reordering as well (for example to put this rule to the end of the benchmark:

https://github.com/ComplianceAsCode/content/blob/27d74f673dd6e0f50db7aff7dcc36bf70ea2e5ed/ssg/build_yaml.py#L551-L559

**Comment by ggbecker** [comment]
> @ggbecker I have updated the issue description because I continue with the productization review and I have now found this issue happened also in the `/CoreOS/scap-security-guide/Sanity/machine-hardening CUI` on RHEL 9 and RHEL 8. That is the test that runs the bash remediations.

It can definitely be a problem in the rule ordering as well.

**Comment by mildas** [comment]
Unfortunately, this is again https://github.com/openscap/openscap/issues/1880
CUI profile machine-hardening is newly in productization, so this profile wasn't tested on s390x before. But as OSPP has same rules, we already hit it there:
 https://src.fedoraproject.org/tests/scap-security-guide/blob/main/f/Library/scap-results/rule_waivers/rhel8/ospp-fail#_4
> passes in initial scan, during remediation phase other zipl rules break it, but this rule is not remediated

**Comment by mildas** [comment]
https://src.fedoraproject.org/tests/scap-security-guide/pull-request/37
Issue can be closed after merging waiver update PR.

**Comment by vojtapolasek** [comment]
Waiver merged, closing th issue.
