### ISSUE TITLE
Fatal error in CIS Workstation L1 RHEL 7 Ansible Playbook

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#10657]
#### Description of problem:
During RHEL downstream test "CoreOS/scap-security-guide/Sanity/test-ansible-playbook-run CIS Workstation (GUI)" the Ansible Playbook fails in the task "Test for existence /boot/grub2/grub.cfg".

#### SCAP Security Guide Version:
current upstream master branch as of 2023-05-29 as of HEAD https://github.com/ComplianceAsCode/content/commit/47955e5289e104a1ebcb928caec593aea3af43d5

#### Operating System Version:
RHEL 7.9

#### Steps to Reproduce:

1. ansible-playbook  --skip-tags ensure_gpgcheck_never_disabled,configure_opensc_nss_db --private-key=/root/.ssh/ssg_id_ecdsa -i "192.168.122.227," /usr/share/scap-security-guide/ansible/rhel7-playbook-cis_workstation_l1.yml'

#### Actual Results:
```

TASK [Test for existence /boot/grub2/grub.cfg] *********************************
fatal: [192.168.122.227]: FAILED! => {"msg": "The conditional check '\"/boot/efi\" not in ansible_mounts | map(attribute=\"mount\") | list' failed. The error was: error while evaluating conditional (\"/boot/efi\" not in ansible_mounts | map(attribute=\"mount\") | list): 'ansible_mounts' is undefined\n\nThe error appears to be in '/usr/share/scap-security-guide/ansible/rhel7-playbook-cis_workstation_l1.yml': line 4281, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n      - no_reboot_needed\n    - name: Test for existence /boot/grub2/grub.cfg\n      ^ here\n"}
```

#### Expected Results:
no fatal fail

#### Additional Information/Debugging Steps:
no

**Comment by Mab879** [comment]
I have been unable to reproduce this and my rerun of this test passed.

**Comment by jan-cerny** [comment]
That's great news, but can we somehow check that `ansible_mounts` is defined before we execute the remediation task?

**Comment by ggbecker** [comment]
`ansible_mounts` is a variable defined by Ansible. It could be that in a older version of Ansible this variable is not defined.

Maybe checking if it is defined first makes sense, we just need to know what are the implications of not running the rest of the commands.
