### ISSUE TITLE
Expose a profile variable in jinja templating

### ISSUE THREAD

**Issue by wokis** [ComplianceAsCode/content#10662]
#### Share the context

Sometimes CIS and STIG remediations diverse just a tiny bit making a copy of such rule unnecessary. For example the rule `audit_rules_suid_privilege_function` in CIS calls for `auid!=unset` while STIG calls for `euid=0` and duplicating the rule seems like a lot of code duplication just for this small change.

#### Description of problem:

A variable could be used (in the same way it was used for `sshd_strong_kex`) however such variable would have to contain the entire set of audit rules as a simple `true` and `false` variable wouldn't work since the jinja templating currently doesn't support `if`-statements against variables.
Something like this doesn't unfortunately work: 
```
rules:
    - audit_rules_suid_privilege_function 
    - audit_rules_suid_privilege_function_cis_profile=cis

...

options:
    default: "false"
    cis: "true"

...

{{% if audit_rules_suid_privilege_function_cis_profile == "true" %}}
```

This seems unnecessarily complicated however as something like the following would be much better.
```
{{% if profile == "cis" %}}
```

#### Proposed change:

Expose the profile to the jinja templating as a variable so that `{{% if profile == "cis" %}}` would be possible in rules and remediations just like `{{% if product == "rhel" %}}` is today.

**Comment by Mab879** [comment]
Unfortunately, profiles are not a build time consideration.  Due to the nature of SCAP, things like fixes and variables are global (per product) for all profiles. Due this we cannot introduce a Jinja variable for profiles.

**Comment by marcusburghardt** [comment]
Currently, it is not easy to implement such functionality. If possible, it would demand huge efforts so there is no plan to work on this. It would be still valid to propose changes for the benchmarks in order to keep the requirements aligned. Sometimes there is no relevant technical impact in one syntax or another. So, it is worth to confirm and propose changes to CIS or STIG.
