### ISSUE TITLE
Rule accounts_password_pam_retry fails

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#10665]
#### Description of problem:
I perform a manual install of a RHEL 8.9 or 9.3 VM with the STIG profile with the latest upstream content. After first boot I perform a scan, but the rule `xccdf_org.ssgproject.content_rule_accounts_password_pam_retry` fails unexpectedly,

See the HTML report and ARF in the attachment:
[stig.zip](https://github.com/ComplianceAsCode/content/files/11614349/stig.zip)

This problem has been discovered by the `Profile remediation in Anaconda` downstream test.

#### SCAP Security Guide Version:
current upstream master branch as of 2023-05-29 as of HEAD https://github.com/ComplianceAsCode/content/commit/47955e5289e104a1ebcb928caec593aea3af43d5

#### Operating System Version:
RHEL 8.9, RHEL 9.3

#### Steps to Reproduce:

1. Install RHEL 8.9 or 9.3 virtual machine, minimal installation, from ISO, manually, using graphical anaconda installation, with the STIG profile from a ssg-rhel8-ds.xml or ssg-rhel9-ds.xml served via HTTP server. 
2. after first boot, copy `ssg-rhel8-ds.xml` (`ssg-rhel9-ds.xml`) to the VM and run `sudo oscap xccdf eval --report stig_final.html --results-arf stig_final.xml --profile stig ./ssg-rhel8-ds.xml` (`./ssg-rhel9-ds.xml`)

#### Actual Results:
rule `xccdf_org.ssgproject.content_rule_accounts_password_pam_retry` fails

#### Expected Results:
rule `xccdf_org.ssgproject.content_rule_accounts_password_pam_retry` passes

#### Additional Information/Debugging Steps:
no

**Comment by jan-cerny** [comment]
I have extended the description. Originally, this ticket was about RHEL 9 but I have found that the same problem occurs also on RHEL 8.

**Comment by jan-cerny** [comment]
@marcusburghardt Thanks for the great investigation. I can see that this is the type of problem where we need run scan and remediation twice. I agree with closing.

**Comment by mildas** [comment]
@marcusburghardt Thanks, for investigation. I also agree with closing.
