### ISSUE TITLE
Unexpected notapplicable rules in RHEL 7 HIPAA

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#10682]
#### Description of problem:
This problem has been discovered in the downstream test `/CoreOS/scap-security-guide/Sanity/ssg-kickstarts for HIPAA`.

#### SCAP Security Guide Version:
Current upstream stabilization-v0.1.68 branch as of 2023-06-02 as of HEAD https://github.com/ComplianceAsCode/content/commit/b630293fe6731860b9c004ec7c72deff3f99e410.

#### Operating System Version:
RHEL-7.9-updates-20230531.0

#### Steps to Reproduce:

1. Install RHEL 7 VM with a HIPAA profile and run an after run scan.

#### Actual Results:
```
There are unexpected "notapplicable" results:
xccdf_org.ssgproject.content_rule_dconf_db_up_to_date - notapplicable
xccdf_org.ssgproject.content_rule_dconf_gnome_remote_access_credential_prompt - notapplicable
xccdf_org.ssgproject.content_rule_dconf_gnome_remote_access_encryption - notapplicable
xccdf_org.ssgproject.content_rule_sshd_disable_compression - notapplicable
```

#### Expected Results:
no unexpected notapplicable results

#### Additional Information/Debugging Steps:
It seems that there is some waiver list that doesn't contain these rules. You need to verify if the "notapplicable" results are really unexpected or if they are expected.

**Comment by mildas** [comment]
Closing as it is not an issue. Notapplicable results are only informational and expected.
