### ISSUE TITLE
recursive file mode setting breaks sudo

### ISSUE THREAD

**Issue by naugler** [ComplianceAsCode/content#10687]
#### Description of problem:
Don't remove setuid bit from everything in /usr/bin, because that's where /usr/bin/sudo lives

#### SCAP Security Guide Version:
1.67

#### Operating System Version:
Ubuntu 20.04

#### Steps to Reproduce:

1. Execute task DISA-STIG-UBTU-20-010423: `ansible-playbook -i localhost, -c local /opt/ssg/ansible/ubuntu2004-playbook-stig.yml --tags "DISA-STIG-UBTU-20-010423"`
2. Try using sudo: `sudo echo hello`

#### Actual Results:
`sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set`

#### Expected Results:
`hello`

**Comment by Mab879** [comment]
@dodys may have more information on this. 

However, I'm not seeing room to allow this under [UBTU-20-010423](https://stigaview.com/products/ubuntu2004/v1r7/UBTU-20-010423/).

**Comment by naugler** [comment]
UBTU-20-010423 looks like it pertains to directories only

**Comment by Mab879** [comment]
You are correct, thanks for correction. I agree there is some bug in the remediation in the `dir_permissions_binary_dirs` rule.

To add little bit more this conversation it appears that [UBTU-20-010456](https://stigaview.com/products/ubuntu2004/v1r7/UBTU-20-010456/) does applies to files. But the DISA remediation doesn't remove SETUID bit, the title states it should remove the SUID bit from system commands.

Looking at `file_permissions_binary_dirs` it using `find(1)` vs just native Ansible commands `dir_permissions_binary_dirs`.

**Comment by dodys** [comment]
I cannot reproduce that at all and as Matthew said, that rule does not seem to be the issue.
Could you please confirm which rule is giving this issue and provide more information so we can try to reproduce it? Also an output of /usr/bin/sudo permissions before and after remediation would be great.

**Comment by dexterle** [comment]
I'm also running into this problem. This is happening within the `dir_permissions_binary_dirs` located [here](https://github.com/ComplianceAsCode/content/tree/master/linux_os/guide/system/permissions/files/permissions_within_important_dirs/dir_permissions_binary_dirs)

Sudo before running task
```
$ ls -la /usr/bin | grep -i "sudo$"
-rwsr-xr-x  1 root   root      166056 Jan 19  2021 sudo
```

Reproduce:
```
$ ansible-playbook ubuntu2004-playbook-stig.yml --tags "UBTU-20-010423"
$ ls -la | grep -i "sudo$"
-rwxr-xr-x  1 root   root      166056 Jan 19  2021 sudo
```

The suid bit is removed from the rule.

**Comment by dodys** [comment]
> I'm also running into this problem. This is happening within the `dir_permissions_binary_dirs` located [here](https://github.com/ComplianceAsCode/content/tree/master/linux_os/guide/system/permissions/files/permissions_within_important_dirs/dir_permissions_binary_dirs)
> 
> Sudo before running task
> 
> ```
> $ ls -la /usr/bin | grep -i "sudo$"
> -rwsr-xr-x  1 root   root      166056 Jan 19  2021 sudo
> ```
> 
> Reproduce:
> 
> ```
> $ ansible-playbook ubuntu2004-playbook-stig.yml --tags "UBTU-20-010423"
> $ ls -la | grep -i "sudo$"
> -rwxr-xr-x  1 root   root      166056 Jan 19  2021 sudo
> ```
> 
> The suid bit is removed from the rule.

thanks for providing more information. I will take a look at it this week
