### ISSUE TITLE
file_permission_user_init_files rule failing after kickstart installation

### ISSUE THREAD

**Issue by marcusburghardt** [ComplianceAsCode/content#10688]
#### Description of problem:

The `file_permission_user_init_files` rule is failing after a kickstart installation with STIG and STIG GUI profiles selected.

#### SCAP Security Guide Version:

master branch as of 2023-06-03

#### Operating System Version:

RHEL9.2, RHEL8.8 and RHEL7.9

#### Steps to Reproduce:

1. Install a VM using `ssg-rhel9-stig-ks.cfg` or `ssg-rhel9-stig_gui-ks.cfg` kickstart files
2. After installation, scan the system using the STIG or STIG GUI profiles
```
e.g: oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_stig --report  xccdf_org.ssgproject.content_profile_stig.html         --results-arf xccdf_org.ssgproject.content_profile_stig-xccdf-arf-results.xml  --results xccdf_org.ssgproject.content_profile_stig-xccdf-results.xml --oval-results /tmp/ssg-rhel9-ds.xml
```

#### Actual Results:

xccdf_org.ssgproject.content_rule_file_permission_user_init_files - fail

#### Expected Results:

xccdf_org.ssgproject.content_rule_file_permission_user_init_files - pass

#### Additional Information/Debugging Steps:

During the remediation, two files were fixed:
```
/home/admin/.bashrc | regular | 1000 | 1000 | 492 | rw-r-----
/home/admin/.bash_profile | regular | 1000 | 1000 | 141 | rw-r-----
```
After the remediation, the system was scanned again and the rule failed because two new files were found without proper permissions:
```
/home/admin/.bashrc | regular | 1000 | 1000 | 492 | rw-r-----
/home/admin/.bash_profile | regular | 1000 | 1000 | 141 | rw-r-----
/home/testuser/.bash_profile | regular | 1001 | 1001 | 141 | rwxr-x---
/home/testuser/.bashrc | regular | 1001 | 1001 | 492 | rwxr-x---
```
Apparently, the `testuser` user was created during the remediation, after the `file_permission_user_init_files` rule remediation be applied.

**Comment by marcusburghardt** [comment]
@mildas , could it be related to the test environment routines?

**Comment by mildas** [comment]
@marcusburghardt Yes, it is. The `admin` user is ok because it is created before OAA https://github.com/ComplianceAsCode/content/blob/master/products/rhel8/kickstart/ssg-rhel8-stig-ks.cfg#L57 and `testuser` is added in post-install section. To make it pass, we can either update waivers or update post-install section to set proper permissions for those files.

**Comment by mildas** [comment]
> I am not sure how exactly would be the waiver for this specific case. Is it possible to filter this specific user?
Otherwise, it would seem simpler to update the post-install section.

Specific profile for kickstart test can be waived. But specific user cannot.
Could you update the post-install section?

**Comment by marcusburghardt** [comment]
This issue was caused by the test environment routines and not by the content.
The test environment is already fixed. More specifically, the post-install section was updated.
So, I am closing this issue.

**Comment by marcusburghardt** [comment]
> Hello, I am reopening the issue as it manifested again in productization run on June 17th. /home/testuser/.bashrc and /home/testuser/.bash_profile are still there with rwxr-x--- permissions.

I just saw there was an additional update after the fix I proposed last week. It seems to be related to an incompatibility in RHEL7 but also impacted the variables used in %post section, breaking the fix. I am checking this.

**Comment by comps** [comment]
This still happens in productization runs on ~ 1st of July.

**Comment by marcusburghardt** [comment]
The issue cause was found in the test environment and confirmed this is not a content issue. We are now testing the fix.

**Comment by jan-cerny** [comment]
FTR this issue is present in the latest upstream master productization run on RHEL 9 on the latest upstream master branch as of 2023-07-21 as of HEAD a96ccb9
