### ISSUE TITLE
OpenSCAP is not supporting for Windows Server with XCCDF evaluation & CIS Benchmark

### ISSUE THREAD

**Issue by kumar6429** [ComplianceAsCode/content#10694]
#### Steps to Reproduce:

1. Log into Windows Server 2016.
2. Download the STIG compliance checklist and upload to SCC 5.7.1.
3. Now run the local scan , select that particular profile (STIG for Windows 2016)
4. The results will be saved to location you specify in SCC 5.7.1
5. How to perform XCCDF evaluation with CIS Benchmark for windows server 2016 via command line or power shell script?
6. How to install the OpenSCAP & SCAP Compliance checker software via power shell script?

#### Actual Results: 

PS C:\SCAP\SCAP Report\Sessions\2023-05-26_093808\Results\SCAP\XML> oscap xccdf eval --fetch-remote-resources --profile Microsoft Windows Server 2016 - cpe:/0 --results-arf win-arf.xml --report win16-report.html
OpenSCAP Error: Unable to open file: 'Windows' [c:\projects\openscap\src\source\oscap_source.c:287]
PS C:\SCAP\SCAP Report\Sessions\2023-05-26_093808\Results\SCAP\XML>

#### Additional Information / Debugging Steps:

**Comment by Mab879** [comment]
OpenSCAP's is currently [not well-supported](https://github.com/OpenSCAP/openscap/blob/acdbe77736a74f7adc50c967ff18cb16e96165cf/docs/windows.md?plain=1#L1). We would be happy to see pull requests on [OpenSCAP](https://github.com/OpenSCAP/openscap)  to help improve this.

@evgenyz Is there anything you want to add?
