### ISSUE TITLE
 Ubuntu 18.04 , 20.04 or 22.04 is not supporting XCCDF evualtion & CIS Benchmark

### ISSUE THREAD

**Issue by kumar6429** [ComplianceAsCode/content#10691]
#### SCAP Security Guide Version: 
apt-get install libopenscap8
apt install ssg-base ssg-debderived ssg-debian ssg-nondebian ssg-applications

#### Steps to Reproduce:

1. Log into Ubuntu system
2.  Run the OpenSCAP evaluation command as below.

ssm-user@vmc-tf-OpenSCAP-Ubuntu2004-vmc-on-aws-1:/usr/bin$ oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_cis_level1_server /usr/share/xml/scap/ssg/content/ssg-ubuntu2004-ds.xml
OpenSCAP Error: Unable to open file: '/usr/share/xml/scap/ssg/content/ssg-ubuntu2004-ds.xml' [../../../src/source/oscap_source.c:284]

3.  I don't see XCCDF SSG profile on this system for Ubuntu 18.04 / 20.04 / 22.04
ssm-user@vmc-tf-OpenSCAP-Ubuntu2004-vmc-on-aws-1:/usr/bin$ cd /usr/share/xml/scap/ssg/content
ssm-user@vmc-tf-OpenSCAP-Ubuntu2004-vmc-on-aws-1:/usr/share/xml/scap/ssg/content$ ls -l | grep ubuntu
-rw-r--r-- 1 root root      578 Jul 26  2018 ssg-ubuntu1404-cpe-dictionary.xml
-rw-r--r-- 1 root root    40395 Jul 26  2018 ssg-ubuntu1404-cpe-oval.xml
-rw-r--r-- 1 root root   742456 Jul 26  2018 ssg-ubuntu1404-ds.xml
-rw-r--r-- 1 root root    41971 Jul 26  2018 ssg-ubuntu1404-ocil.xml
-rw-r--r-- 1 root root   397360 Jul 26  2018 ssg-ubuntu1404-oval.xml
-rw-r--r-- 1 root root   230476 Jul 26  2018 ssg-ubuntu1404-xccdf.xml
-rw-r--r-- 1 root root      578 Jul 26  2018 ssg-ubuntu1604-cpe-dictionary.xml
-rw-r--r-- 1 root root    40395 Jul 26  2018 ssg-ubuntu1604-cpe-oval.xml
-rw-r--r-- 1 root root   743081 Jul 26  2018 ssg-ubuntu1604-ds.xml
-rw-r--r-- 1 root root    42001 Jul 26  2018 ssg-ubuntu1604-ocil.xml
-rw-r--r-- 1 root root   397681 Jul 26  2018 ssg-ubuntu1604-oval.xml
-rw-r--r-- 1 root root   230777 Jul 26  2018 ssg-ubuntu1604-xccdf.xml
ssm-user@vmc-tf-OpenSCAP-Ubuntu2004-vmc-on-aws-1:/usr/share/xml/scap/ssg/content$

4. Install both OpenSCAP & SSG by running below commands.
apt-get install libopenscap8
apt install ssg-base ssg-debderived ssg-debian ssg-nondebian ssg-applications
5. Even after I am unable to run XCCDF evaluation with CIS Benchmarks for Ubuntu 18.04 / 20.04 / 22.04

**Comment by Mab879** [comment]
@dodys can you help here?

**Comment by dodys** [comment]
I'm closing this for now

**Comment by dodys** [comment]
I'm closing this for now
