### ISSUE TITLE
Update Ubuntu 20.04 STIG from v1r1 to v1r8

### ISSUE THREAD

**Issue by dexterle** [ComplianceAsCode/content#10722]
#### Description of problem:

The Ubuntu 20.04 STIG in this project is currently at version v1r1:
https://github.com/ComplianceAsCode/content/blob/v0.1.66/products/ubuntu2004/profiles/stig.profile#L3

The latest Ubuntu 20.04 STIG version available is v1r8: https://public.cyber.mil/stigs/downloads/

#### Proposed change:

We should update the STIG profile to reflect the latest version.

**Comment by dodys** [comment]
This is a duplicate of #10325
Therefore I'm closing this ticket.
