### ISSUE TITLE
Container images scanning profile

### ISSUE THREAD

**Issue by GoliTech** [ComplianceAsCode/content#10797]
#### Description of problem:
Where can container image scanning profiles be found?

#### Steps to Reproduce:

1.
2.
3.
4.

**Comment by ggbecker** [comment]
The regular profiles should be used for scanning container images. The rules that are not applicable will return `not applicable` when scanning containers. These rules are marked as `machine` as you can see here for example: https://github.com/ComplianceAsCode/content/blob/a50e53666f47bf59cbad1f8736d74fbdbf63428f/linux_os/guide/services/base/service_rdisc_disabled/rule.yml#L43
