### ISSUE TITLE
Configuration option being used for aide.conf is deprecated

### ISSUE THREAD

**Issue by thedarave** [ComplianceAsCode/content#10858]
#### Description of problem:

In Ubuntu 22.04 the following warning message appears:
WARNING: /etc/aide/aide.conf:201: Using 'database' is DEPRECATED. Update your config and use 'database_in' instead (line: 'database=file:/var/lib/aide/aide.db')

#### Details:

This content is not aligned with content from _<insert the other party name here>_

The misalignment affects these profiles:

- Ubuntu 22.04

The misalignment affects these rules:

- Build and Test AIDE Database

#### Outcome:

- [X] This project's content can be  improved:
  - [ ] Check needs to be improved.
  - [X] Remediation needs to be improved.
- [ ] The external content's check is faulty - the other party needs to be notified, they have work to do.

####  External Content's Version:
Aide 0.17.4
Ubuntu 22.04.2 LTS minimal

**Comment by dodys** [comment]
please see #8838

**Comment by dodys** [comment]
I'm closing this issue, since we have it also on #11929
