### ISSUE TITLE
setuptools in rawhide broken on Python 3.12

### ISSUE THREAD

**Issue by sarnold** [ComplianceAsCode/content#10862]
#### Description of problem:
Python 3.12 has removed some deprecated (since 3.4 even) `imp` bits that breaks pkg_resources in rawhide build.

#### SCAP Security Guide Version:
master branch (and others) with Py3.12 and distro not-the-latest setuptools

#### Operating System Version:
GH CI ubuntu-latest

#### Steps to Reproduce:

1. run the Build workflow
2. check status of jobs
3. rawhide job fails immediately

#### Additional Information/Debugging Steps:

1. review this PR: https://github.com/python/cpython/pull/98573

#### Possible solutions:
1. refactor to use importlib/other
2. use the patched pkgutil in [v66.1.0](https://setuptools.pypa.io/en/latest/history.html#v66-1-0) or newer

**Comment by marcusburghardt** [comment]
Fixed by https://github.com/ComplianceAsCode/content/pull/10819
