### ISSUE TITLE
how to write a rule which maybe need a shell or python script to check

### ISSUE THREAD

**Issue by StevenYGui** [ComplianceAsCode/content#10899]
#### Description of problem:
This is not an issue, more accurately a consultation.
I want to add a rule that can be checked by oscap, but this rule does not check kernel sysctl parameters or file permissions. I want to implement the check process through shell or python scripts. (For example, run the find command in the automatic path to search for files that meet certain naming rules.) Does the current ssg support this mode? How to write the yml or oval file?

thank you and waiting for your feedback

#### SCAP Security Guide Version:
0.1.49

#### Operating System Version:
centos

#### Steps to Reproduce:

1.
2.
3.
4.

**Comment by StevenYGui** [comment]
thank you, let me try.

**Comment by marcusburghardt** [comment]
@StevenYGui did it work for you?
