### ISSUE TITLE
Rule service_rpcbind_disabled is failing after CIS workstation L2 kickstart installation

### ISSUE THREAD

**Issue by vojtapolasek** [ComplianceAsCode/content#10901]
#### Description of problem:
After you perform an installation of RHEL 8 with kickstart for CIS workstation level 2, the rule service_rpcbind_disabled fails during the oscap scan.

#### SCAP Security Guide Version:

stabilization-v0.1.69 branch as of 2023-07-20

#### Operating System Version:

RHEL 8

#### Steps to Reproduce:

1. perform kickstart installation with kickstart for CIS workstation level 2, choose the "system with GUI" when installing
2. examine test results provided after the installation

#### Actual Results:

rule service_rpcbind_disabled is reported as "fail"

#### Expected Results:

rule service_rpcbind_disabled is reported as "pass"

**Comment by marcusburghardt** [comment]
I don't remember where, but I think this was already discussed in the past. Maybe it is related to a dependency relationship with another package or service?

**Comment by vojtapolasek** [comment]
@marcusburghardt  you are probably right: https://github.com/ComplianceAsCode/content/issues/10143 might be good to read.

**Comment by marcusburghardt** [comment]
Maybe it was "not applicable" during the installation phase. Then fails right after the install. I wonder if it would be properly fixed if a second round of scan / remediation happens after reboot.

**Comment by marcusburghardt** [comment]
It should be ok now. The test was disabled. Thanks @mildas

**Comment by marcusburghardt** [comment]
For some reason, the `nfs-utils` package was included in this rule by this commit: https://github.com/ComplianceAsCode/content/commit/9676acc40bfff48818b517a8660ea54c6d06aa8a
I already proposed a fix for this: https://github.com/ComplianceAsCode/content/pull/10907

This rule replaced the `package_rpcbind_removed` rule in CIS profiles for RHEL about six months ago.

However, regardless of the fix I will propose, the rule seems to be working as expected:
- During the installation, the `rpcbind` package is installed to satisfy the `nfs-utils` dependency.
- Right after the installation, the `rpcbind` service is not started but is enabled:
```
systemctl status rpcbind
● rpcbind.service - RPC Bind
   Loaded: loaded (/usr/lib/systemd/system/rpcbind.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:rpcbind(8)
```
- It makes the rule to fail after the installation.
- But after the remediation the service is properly disabled.

It seems another case of rule dependencies which can be solved with a second round of scan/remediation, like reported in this issue: https://github.com/OpenSCAP/openscap/issues/1880

@mildas and @vojtapolasek , could you confirm this case, please?

**Comment by marcusburghardt** [comment]
Still present in last productization review.

**Comment by vojtapolasek** [comment]
I can confirm that the problem can be solved by one more remediation after the installation.

**Comment by vojtapolasek** [comment]
https://github.com/RHSecurityCompliance/contest/pull/55

**Comment by vojtapolasek** [comment]
It manifested also during the latest stabilization with kickstart installation of cis_ws_l1.

**Comment by marcusburghardt** [comment]
https://github.com/RHSecurityCompliance/contest/pull/55 was merged yesterday. It should be good for the next round of tests.

**Comment by marcusburghardt** [comment]
It is no longer present in last productization tests. FYI @mildas @comps
