### ISSUE TITLE
Rule sysctl_net_ipv4_ip_forward fails after hardening CIS workstation_l2

### ISSUE THREAD

**Issue by vojtapolasek** [ComplianceAsCode/content#10937]
#### Description of problem:

After hardening a GUI system with cis_workstation_l2 profile, the rule sysctl_net_ipv4_ip_forward fails.

#### SCAP Security Guide Version:

stabilization branch as of 6f9c4c4d47a3cb9188f8cf7b0e3bf0cbeddad3c7 

#### Operating System Version:

RHEL 7

#### Steps to Reproduce:

1. Install a VM with GUI.
2. ./build_product rhel7 && cd tests/
3. python automatus.py profile --libvirt <your_libvirt_config> --remediate-using oscap  cis_workstation_l2

#### Actual Results:

Rule sysctl_net_ipv4_ip_forward is reported as failed in final scan.

#### Expected Results:

Rule sysctl_net_ipv4_ip_forward is passing in final scan.

#### Additional Information/Debugging Steps:

I have slight suspicion that it might be similar to https://github.com/ComplianceAsCode/content/issues/9316

**Comment by mildas** [comment]
Another missing waiver - https://src.fedoraproject.org/tests/scap-security-guide/blob/main/f/Library/scap-results/rule_waivers/rhel7/cis_workstation_l2-gui-fail#_2

**Comment by marcusburghardt** [comment]
I no longer see this error.
