### ISSUE TITLE
Firewalld rules failing after CCN advanced Anaconda installation

### ISSUE THREAD

**Issue by vojtapolasek** [ComplianceAsCode/content#10939]
#### Description of problem:

Rules firewalld_loopback_traffic_trusted and firewalld_loopback_traffic_restricted are failing after performing Anaconda install of RHEL 9 with CCN advanced profile selected.

#### SCAP Security Guide Version:

stabilization branch as of 6f9c4c4d47a3cb9188f8cf7b0e3bf0cbeddad3c7  

#### Operating System Version:

RHEL 9

#### Steps to Reproduce:

Perform Anaconda installation of a machine and select CCN Advanced profile. REview scan results after installation.

#### Actual Results:

Rules are failing.

#### Expected Results:

Rules are passing.

#### Additional Information/Debugging Steps:

Rules are passing when using Automatus locally.

**Comment by jan-cerny** [comment]
It seems to be similar to https://github.com/ComplianceAsCode/content/issues/10613

**Comment by mildas** [comment]
Yep, it seems as missing waiver in Contest.

**Comment by marcusburghardt** [comment]
Waivers are working.
