### ISSUE TITLE
Invalid TMUX tasks defined by latest version of ansible-role-rhel8-stig 

### ISSUE THREAD

**Issue by PowerTester** [ComplianceAsCode/content#10957]
#### Description of problem:

Issue:
The tmux.conf tasks use a similar pattern when adding in a new line to
the file; However, this tasks uses an invalid option for the create
parameter.

Fix:
Updated the create parameter to use 'true' in alignment with
all other tmux.conf tasks that add lines to the file.

#### SCAP Security Guide Version:

N/A

#### Operating System Version:

N/A

#### Steps to Reproduce:

1. Apply the ansible playbook: https://github.com/RedHatOfficial/ansible-role-rhel8-stig to a RHEL 8 instance

#### Actual Results:

Playbook fails

TASK [stig-rhel8 : Insert correct line into /etc/tmux.conf] ********************
    fatal: [default]: FAILED! => changed=false
    msg: 'argument ''create'' is of type <class ''NoneType''> and we were unable to convert to bool: <class ''NoneType''> cannot be converted to a bool'

#### Expected Results:

Playbook succeeds

#### Additional Information/Debugging Steps:
Project : [ansible-role-rhel8-stig](https://github.com/RedHatOfficial/ansible-role-rhel8-stig)
Line 13702 in `tasks/main.yml`

https://github.com/RedHatOfficial/ansible-role-rhel8-stig/commit/46bd632c64e2ac94eeb0052d6c0bfc8d6f946e7e

**Comment by ggbecker** [comment]
This is already resolved in the latest version 0.1.69: https://github.com/ComplianceAsCode/content/commit/948d0f6911c5128ff8ebdf6517a937d410d52c55

The galaxy roles need to be updated to latest version, I will try to ping the maintainer to update the roles there.
