### ISSUE TITLE
`configure_tmux_lock_*` rules result in `notaplicable` -> `fail`

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#11031]
#### Description of problem:
`configure_tmux_lock_after_time`, `configure_tmux_lock_command`, and `configure_tmux_lock_keybinding` are failing after RHEL8/RHEL9 profile remediation that include those rules (OSPP, CUI, STIG). 

#### SCAP Security Guide Version:
5a89c8c

#### Operating System Version:
RHEL8/RHEL9

#### Steps to Reproduce:

1. `oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_cui --progress --remediate /var/tmp/contest-hardening-host-os-oscap-cui/modified_datastream.xml`
2. Reboot
3. `oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_cui --progress --remediate /var/tmp/contest-hardening-host-os-oscap-cui/modified_datastream.xml | grep configure_tmux_lock`

#### Actual Results:
```
xccdf_org.ssgproject.content_rule_configure_tmux_lock_after_time:fail
xccdf_org.ssgproject.content_rule_configure_tmux_lock_command:fail
```

#### Expected Results:
```
xccdf_org.ssgproject.content_rule_configure_tmux_lock_after_time:pass
xccdf_org.ssgproject.content_rule_configure_tmux_lock_command:pass
```

#### Additional Information/Debugging Steps:
During remediation the rules result in `notapplicable` and during final scan they fail. Probably https://github.com/OpenSCAP/openscap/issues/1880 again, needs to be confirmed there's no other way to make them green.

**Comment by ggbecker** [comment]
This is basically the problem that a rule (package_tmux_installed) in the profile makes other rules become applicable after it gets remediated. And the rule ordering does not help here because of the nature how scan/remediation works in OpenSCAP. First scan all rules and then remediates all rules. The only fix would be scan one rule and remediate and so on.

**Comment by ggbecker** [comment]
A second scan/remediation should solve the problem though.

**Comment by mildas** [comment]
Ok, if that's expected it should be waived in contest and closed. Same as we did for similar problematic rules from https://github.com/OpenSCAP/openscap/issues/1880

**Comment by Mab879** [comment]
PR in https://github.com/RHSecurityCompliance/contest/pull/67
