### ISSUE TITLE
SEGFAULT when evaluating DISA rule

### ISSUE THREAD

**Issue by cortesana** [ComplianceAsCode/content#11101]
#### Description of problem:
A SEGFAULT occurs when scanning a VM using a DISA datastream (Server with GUI).
The SEGFAULT occurred while evaluating the final state of DISA's STIG profile on the `SV-230346r877399` rule.

#### SCAP Security Guide Version:
current upstream master branch as of 2023-09-04

#### Operating System Version:
RHEL 8

#### Steps to Reproduce:

1. Evaluate the state of DISA's STIG profile on a RHEL 8 machine by running:
```
oscap xccdf eval             --profile '(all)' --report final_disa_stig.html --oval-results             --results-arf disa-xccdf-arf-results.xml /tmp/disa-stig-rhel8-v1r10-xccdf-scap.xml
```
#### Actual Results:
```
Title
	[1mRHEL 8 must limit the number of concurrent sessions to ten for all accounts and/or account types.[0;0m
Rule
	xccdf_mil.disa.stig_rule_SV-230346r877399_rule
Ident
	CCI-000054
bash: line 1:  2837 Done                    echo admin123
      2838 Segmentation fault      | sudo -S oscap xccdf eval --profile '(all)' --report final_disa_stig.html --oval-results --results-arf disa-xccdf-arf-results.xml /tmp/disa-stig-rhel8-v1r10-xccdf-scap.xml
```

#### Expected Results:
```
Title
	[1mRHEL 8 must limit the number of concurrent sessions to ten for all accounts and/or account types.[0;0m
Rule
	xccdf_mil.disa.stig_rule_SV-230346r877399_rule
Ident
	CCI-000054
Result
	[32mpass[0m
```

#### Additional Information/Debugging Steps:
This causes an additional failure when the ARF result files to fail to be copied to the host machine.

**Comment by Mab879** [comment]
In quick attempt I was unable to reproduce this . However, [openscap/opencap ](https://github.com/OpenSCAP/openscap) would be better spot to report segfaults in the `oscap` command.

**Comment by cortesana** [comment]
Thanks for catching this, @Mab879 - Closing this in favor of https://github.com/OpenSCAP/openscap/issues/2029
