### ISSUE TITLE
audit_rules_privileged_commands rule is failing in ANSSI NT28 High profile evaluation

### ISSUE THREAD

**Issue by cortesana** [ComplianceAsCode/content#11103]
#### Description of problem:
The `audit_rules_privileged_commands` rule is failing in tests during ANSSI  NT28 High profile evaluation.

#### SCAP Security Guide Version:
Current upstream master branch as of 2023-09-04

#### Operating System Version:
RHEL 7

#### Steps to Reproduce:

1. `oscap xccdf eval  --profile xccdf_org.ssgproject.content_profile_anssi_nt28_high --progress --report report.html --results results.xml --oval-results contest-ds.xml `

#### Actual Results:
```
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands:fail
2023-09-02 11:24:57 test.py:71: lib.results.report_plain:171: FAIL audit_rules_privileged_commands
W: oscap:     Obtrusive data from probe!
```
#### Expected Results:
```
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands:pass
2023-09-02 11:24:57 test.py:71: lib.results.report_plain:171: PASS audit_rules_privileged_commands
```

**Comment by jan-cerny** [comment]
Both this issue and #11104 appear in the same test (/CoreOS/scap-security-guide/hardening/ansible/anssi_nt28_high).

**Comment by marcusburghardt** [comment]
It is not longer present in the last productization review. It was likely fixed by https://github.com/ComplianceAsCode/content/pull/11117
