### ISSUE TITLE
Rules failing as misaligned with DISA

### ISSUE THREAD

**Issue by cortesana** [ComplianceAsCode/content#11105]
#### Description of problem:
The `display_login_attempts` rule and the `audit_rules_login_events_faillock` rule are failing checks due to misalignments with DISA in the following tests:
- disa-content-alignment-remediations Bash (GUI)
- disa-content-alignment-remediations Ansible (GUI)
- disa-content-alignment-remediations Ansible
- disa-content-alignment-remediations Bash
- disa-content-alignment-kickstart (GUI)
- disa-content-alignment-kickstart

#### SCAP Security Guide Version:
Current upstream master branch as of 2023-09-04

#### Operating System Version:
RHEL 7

#### Steps to Reproduce:
1. `compare_results.py ssg-stig-viewer.xml disa-xccdf-arf-results.xml`

#### Actual Results:
```
[   FAIL   ] :: Misalignments not passing after waiving:
  CCE-27275-7 SV-86899 - SV-204605r858478_rule display_login_attempts                                                     pass - fail
  CCE-80383-3 CCE-80383-3 - SV-204540r853930_rule audit_rules_login_events_faillock
```

#### Expected Results:
No rules are misaligned after waiving.

**Comment by marcusburghardt** [comment]
Regarding the `display_login_attempts` rule, it is probably related to https://github.com/ComplianceAsCode/content/issues/9031.

The rule is correct but STIG description needs to be updated.

**Comment by marcusburghardt** [comment]
I don't see results about the `audit_rules_login_events_faillock` rule. Which one is failing or passing?

**Comment by jan-cerny** [comment]
@marcusburghardt  In my run the `audit_rules_login_events_faillock` is passing in SSG but  `xccdf_mil.disa.stig_rule_SV-204540r853930_rule` is failing in DISA.

**Comment by marcusburghardt** [comment]
Still present in last productization review.
