### ISSUE TITLE
sshd_use_strong_macs rule passes when a failure is expected

### ISSUE THREAD

**Issue by cortesana** [ComplianceAsCode/content#11107]
#### Description of problem:
The sshd_use_strong_macs rule rule is failing in several tests during generation fix for E8 profile:
- hardening/ansible/with-gui/e8
- hardening/ansible/e8

#### SCAP Security Guide Version:
Current upstream master branch as of 2023-09-04

#### Operating System Version:
RHEL 7

#### Steps to Reproduce:

1. `oscap xccdf generate --profile (all) fix /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml`

#### Actual Results:
```
xccdf_org.ssgproject.content_rule_sshd_use_strong_macs:pass
2023-09-02 11:36:50 test.py:71: lib.results.report_plain:171: FAIL sshd_use_strong_macs (waive: expected fail/error, got pass)
```

#### Expected Results:
```
xccdf_org.ssgproject.content_rule_sshd_use_strong_macs:fail
2023-09-02 11:36:50 test.py:71: lib.results.report_plain:171: PASS sshd_use_strong_macs (waive: expected fail/error, got pass)
```

**Comment by jan-cerny** [comment]
This issue is still present in the latest productization run on RHEL 7.9 using scap-security-guide built from the latest master as of 2023-09-09 as of HEAD https://github.com/ComplianceAsCode/content/commit/7c741f2b542fffcd60f685cdb1f754fec0ba44c6

**Comment by vojtapolasek** [comment]
This needs waivers to be removed. This PR into Contest repo fixes it:
https://github.com/RHSecurityCompliance/contest/pull/71

**Comment by marcusburghardt** [comment]
Still present in last productization review.

**Comment by matusmarhefka** [comment]
Closing, waivers were removed in https://github.com/RHSecurityCompliance/contest/pull/71
