### ISSUE TITLE
Ansible CIS Fails when /etc/bashrc doesn't exist Ubuntu 22.04

### ISSUE THREAD

**Issue by benhosmereop** [ComplianceAsCode/content#11118]
#### Description of problem:
Using the automated ansible play provided under

#### SCAP Security Guide Version:
0.1.69

#### Operating System Version:
Ubuntu 22.04

```
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

#### Steps to Reproduce:

1. Create an Ubuntu server based on Ubuntu 22.04.2 provided from Canonical
2. During the install enable SSH
3. Download the SCAP content
4. Install ansible using pip
5. `ansible-playbook -i "localhost," -c local scap-security-guide-0.1.69/ansible/ubuntu2204-playbook-cis_level1_server.yml --become -K`

#### Actual Results:
```
...
TASK [Check if umask in /etc/bashrc is already set] *************************************************************************************************************************
ok: [localhost]

TASK [Replace user umask in /etc/bashrc] ************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'umask_replace.found > 0' failed. The error was: error while evaluating conditional (umask_replace.found > 0): 'dict object' has no attribute 'found'. 'dict object' has no attribute 'found'\n\nThe error appears to be in '/home/bhosmer/ansible-cis.yaml': line 1536, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Replace user umask in /etc/bashrc\n      ^ here\n"}

PLAY RECAP ******************************************************************************************************************************************************************
localhost                  : ok=85   changed=10   unreachable=0    failed=1    skipped=7    rescued=0    ignored=0
...
```
#### Expected Results:
The play should succeed despite the file not existing

**Comment by benhosmereop** [comment]
On my test machine, it seems like the file is actually `/etc/bash.bashrc` perhaps.

**Comment by dodys** [comment]
> On my test machine, it seems like the file is actually `/etc/bash.bashrc` perhaps.

We (Ubuntu) don't support the ansible remediations, if you wanna provide a fix to it we will gladly review it

**Comment by benhosmereop** [comment]
@dodys 
I don't quite understand when you say:
>we (Ubuntu)
Can you clarify?

I'd like to make an attempt at a fix regardless though. Can you point me to some ideas about where to start?

I realize the Ansible remediations are generated from the oscap tool. I've done this myself. It's not clear hos oscap generates these though.

Thanks in advance.

**Comment by dodys** [comment]
> @dodys I don't quite understand when you say:
> 
> > we (Ubuntu)
> 
> Can you clarify what you mean?

The project here has two main types of remediation, either through bash or ansible. We (Canonical/Ubuntu) support bash, any issues with it we will investigate and fix it. On the other hand everything related to Ansible is community maintained, we will glad review and test it before merging, but we won't be investigating and fixing it.
But anyway, I went ahead and took a look at it and it was simple enough to provide a fix, see PR mentioned above.

> 
> I'd like to make an attempt at a fix regardless though. Can you point me to some ideas about where to start?
> 

Yes, we have the workshop documentation here: https://github.com/ComplianceAsCode/content/tree/master/docs/workshop
This will allow you to understand more about the source code here and how to test it and contribute in the future.

**Comment by marcusburghardt** [comment]
Fixed by https://github.com/ComplianceAsCode/content/pull/11124
