### ISSUE TITLE
UID Owner mismatch for logfiles

### ISSUE THREAD

**Issue by fkaute** [ComplianceAsCode/content#11149]
#### Description of problem:
The owner of all log files written by rsyslog should be syslog.
The shell/ansible code snippet do chown files to UID 104, which is user 'systemd-timesync' on my ubuntu 22.04.3 os.
the report passes with this because it checks if UID = 104.
After a reboot, os sets ownership back to syslog(107) and the report fails.
According to description, the rule does not set ownership to user syslog(107) but UID=104 and the report is not looking up the correct UID (104 = systemd-timesync instead of 107 = syslog)

#### SCAP Security Guide Version:
ssg-ubuntu2204-ds.xml
xccdf_org.ssgproject.content_profile_standard

oscap --version
OpenSCAP command line tool (oscap) 1.3.7
Copyright 2009--2021 Red Hat Inc., Durham, North Carolina.

==== Supported specifications ====
SCAP Version: 1.3
XCCDF Version: 1.2
OVAL Version: 5.11.1
CPE Version: 2.3
CVSS Version: 2.0
CVE Version: 2.0
Asset Identification Version: 1.1
Asset Reporting Format Version: 1.1
CVRF Version: 1.1

#### Operating System Version:
Ubuntu 22.04.3

#### Steps to Reproduce:

1. Apply code snippets from rule 'Ensure Log Files Are Owned By Appropriate User'
2. generate report
3. report passes but owner is not syslog for some logfiles
4. chown to syslog fails the rule

I assume rule and test should set/check for UID 107 instead of 104?!

**Comment by mpurg** [comment]
Hi @fkaute 

This is from a clean install of 22.04.3:
```
$ cat /etc/lsb-release; uname -r; grep syslog /etc/passwd
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
6.2.0-34-generic
syslog:x:104:111::/home/syslog:/usr/sbin/nologin
```
Did you do any customization to your base Ubuntu installation?

**Comment by mpurg** [comment]
Apologies, I should have specified I was using the desktop installation.
I checked now on a clean server installation of 22.04.3 and can confirm the syslog user has UID=107.

The reason you see a different kernel version is that the desktop and server installations by default
track different kernels (see https://ubuntu.com/kernel/lifecycle).

I'll look into it.
