### ISSUE TITLE
[Question]: How to add a pci-dss.profile for an OS?

### ISSUE THREAD

**Issue by Jingshui1037** [ComplianceAsCode/content#11204]
#### Description of problem:

I found in the [01_introduction.md document](https://github.com/ComplianceAsCode/content/blob/master/docs/manual/developer/01_introduction.md#decomposition) that PCI-DSS  is product-independent profile (PIP) . In addition, I also found that Redhat and Oracle provided the corresponding pci-dss.profile in the code repository. 

![image](https://github.com/ComplianceAsCode/content/assets/135581562/fb723d7f-57ea-4a17-976f-d4852ec56fcd)

If the OS vendor who is familiar with the PCI-DSS protocol wants to add pci-dss.profile for her OS in openscap,  could she develop the corresponding pci-dss.profile according to the PCI-DSS official protocol directly without publishing the corresponding Benchmark on the PCI-DSS official website (like CIS)?

**Comment by Mab879** [comment]
Thanks for opening this issue.

PCI-DSS is a higher level benchmark than the CIS benchmarks. The CIS benchmarks are prescriptive on each operating system version on how to configure it. PCI-DSS on the other hand has a boarder scope, focusing on how to secure cardholder data across an org. 


> If the OS vendor who is familiar with the PCI-DSS protocol wants to add pci-dss.profile for her OS in openscap, could she develop the corresponding pci-dss.profile according to the PCI-DSS official protocol directly without publishing the corresponding Benchmark on the PCI-DSS official website (like CIS)?

I believe that is correct.

**Comment by Jingshui1037** [comment]
OK, Thanks.
