### ISSUE TITLE
Bad ANSSI reference in linux_os rules

### ISSUE THREAD

**Issue by dhuberson** [ComplianceAsCode/content#11304]
#### Description of problem:

A lot of rules refer to bad ANSSI references.

**Ex:**
linux_os/guide/system/permissions/files/permissions_important_account_files/file_permissions_etc_gshadow/rule.yml
This rule refer to ANSSI : BP28(R36) but the good reference is BP28(R50)

#### SCAP Security Guide Version:

Master version

#### Operating System Version:

linux_os

#### Steps to Reproduce:

Reference : ANSSI-BP-028

**Impacted rules:**
mount_option_proc_hidepid
mount_option_nodev_nonroot_local_partitions
mount_option_boot_noexec
mount_option_home_noexec
mount_option_tmp_noexec
mount_option_var_noexec
mount_option_var_log_noexec
mount_option_var_tmp_noexec
mount_option_boot_nosuid
mount_option_opt_nosuid
mount_option_srv_nosuid
mount_option_tmp_nosuid
mount_option_var_nosuid
mount_option_var_log_nosuid
mount_option_var_tmp_nosuid
aide_build_database
sysctl_net_ipv6_conf_all_accept_ra_defrtr
sysctl_net_ipv6_conf_default_accept_ra_defrtr
sysctl_net_ipv6_conf_all_accept_ra_pinfo
sysctl_net_ipv6_conf_default_accept_ra_pinfo
sysctl_net_ipv6_conf_all_accept_ra_rtr_pref
sysctl_net_ipv6_conf_default_accept_ra_rtr_pref
aide_verify_acls
aide_verify_ext_attributes
sysctl_net_ipv6_conf_all_autoconf
sysctl_net_ipv6_conf_default_autoconf
rsyslog_remote_tls_cacert
sysctl_net_ipv6_conf_all_router_solicitations
sysctl_net_ipv6_conf_default_router_solicitations
dnf-automatic_apply_updates
dnf-automatic_security_updates_only
sysctl_net_ipv4_conf_default_secure_redirects
sysctl_net_ipv6_conf_all_max_addresses
sysctl_net_ipv6_conf_default_max_addresses
sysctl_kernel_pid_max
aide_scan_notification
aide_periodic_cron_checking
accounts_polyinstantiated_tmp
accounts_polyinstantiated_var_tmp
selinux_policytype
postfix_client_configure_mail_alias
sebool_deny_execmem
sebool_polyinstantiation_enabled
accounts_passwords_pam_faillock_deny_root
sebool_secure_mode_insmod
rsyslog_remote_tls
no_direct_root_logins
sysctl_net_ipv4_conf_all_accept_redirects
sysctl_net_ipv6_conf_all_accept_redirects
sysctl_fs_suid_dumpable
sysctl_net_ipv4_conf_default_accept_redirects
sysctl_net_ipv6_conf_default_accept_redirects
sysctl_net_ipv4_conf_all_secure_redirects
sysctl_net_ipv4_conf_all_accept_source_route
sysctl_net_ipv6_conf_all_accept_source_route
sysctl_net_ipv4_conf_default_accept_source_route
sysctl_net_ipv6_conf_default_accept_source_route
sysctl_net_ipv4_ip_forward
sysctl_net_ipv4_conf_all_send_redirects
sysctl_net_ipv4_conf_default_send_redirects
sysctl_kernel_modules_disabled
postfix_network_listening_disabled
sshd_disable_root_login
sebool_selinuxuser_execheap
sebool_selinuxuser_execstack
sebool_ssh_sysadm_login
sysctl_kernel_perf_event_paranoid
sysctl_kernel_sysrq
sudoers_no_command_negation
enable_authselect
timer_dnf-automatic_enabled
sysctl_fs_protected_hardlinks
sysctl_fs_protected_symlinks
sysctl_net_ipv4_icmp_ignore_bogus_error_responses
sysctl_net_ipv4_conf_all_rp_filter
sysctl_net_ipv4_conf_default_rp_filter
sysctl_net_ipv4_tcp_rfc1337
sysctl_net_ipv4_tcp_syncookies
sysctl_kernel_randomize_va_space
partition_for_boot
partition_for_home
partition_for_opt
partition_for_srv
partition_for_tmp
partition_for_usr
partition_for_var
partition_for_var_log
partition_for_var_log_audit
partition_for_var_tmp
file_permissions_ungroupowned
no_files_unowned_by_user
file_permissions_unauthorized_sgid
file_permissions_unauthorized_suid
dir_perms_world_writable_root_owned
audit_rules_privileged_commands_sudo
ensure_gpgcheck_never_disabled
ensure_gpgcheck_local_packages
ensure_gpgcheck_globally_activated
rsyslog_files_groupownership
rsyslog_files_ownership
rsyslog_remote_loghost
file_permissions_unauthorized_world_writable
sudo_add_requiretty
sudo_add_use_pty
accounts_password_pam_dcredit
accounts_password_pam_minlen
accounts_password_pam_lcredit
accounts_password_pam_ocredit
accounts_password_pam_ucredit
sudo_add_noexec
ensure_redhat_gpgkey_installed
package_rsyslog-gnutls_installed
selinux_state
security_patches_up_to_date
sudo_add_ignore_dot
sudo_add_env_reset
sudo_add_umask
rsyslog_files_permissions
accounts_umask_etc_bashrc
accounts_umask_etc_profile
accounts_umask_etc_login_defs
sudo_remove_no_authenticate
sudo_remove_nopasswd
sudoers_explicit_command_args
package_aide_installed
package_dnf-automatic_installed
install_PAE_kernel_on_x86-32
package_sudo_installed
grub2_enable_iommu_force
sysctl_kernel_perf_cpu_time_max_percent
accounts_password_pam_unix_remember
sysctl_kernel_perf_event_max_sample_rate
accounts_passwords_pam_faillock_deny
prefer_64bit_os
sysctl_vm_mmap_min_addr
package_ypbind_removed
package_telnet_removed
package_tftp_removed
sysctl_kernel_dmesg_restrict
sysctl_kernel_kptr_restrict
sysctl_kernel_yama_ptrace_scope
grub2_password
accounts_tmout
accounts_passwords_pam_faillock_interval
sysctl_net_ipv4_ip_local_port_range
accounts_passwords_pam_faillock_unlock_time
set_password_hashing_algorithm_systemauth
accounts_maximum_age_login_defs
accounts_password_minlen_login_defs
sshd_set_idle_timeout
grub2_uefi_admin_username
grub2_uefi_password
enable_pam_namespace
package_dhcp_removed
package_rsh_removed
package_rsh-server_removed
package_sendmail_removed
package_setroubleshoot_removed
package_setroubleshoot-plugins_removed
package_setroubleshoot-server_removed
package_talk_removed
package_talk-server_removed
package_telnet-server_removed
package_tftp-server_removed
package_xinetd_removed
package_ypserv_removed
file_permissions_etc_gshadow
file_permissions_etc_passwd
file_permissions_etc_shadow
file_permissions_sshd_private_key
dir_perms_world_writable_sticky_bits
file_owner_etc_gshadow
file_owner_etc_shadow

#### Actual Results:

Bad ANSSI reference in rules.

#### Expected Results:

Check and fix ANSSI references BP28(RXX) in listed rules and others.

**Comment by marcusburghardt** [comment]
Fixed by https://github.com/ComplianceAsCode/content/pull/11556
