### ISSUE TITLE
Rule `audit_rules_privileged_commands` remediation does not support offline mode

### ISSUE THREAD

**Issue by evgenyz** [ComplianceAsCode/content#11345]
#### Description of problem:

The `$(awk '/nodev/ { print $2 }' /proc/filesystems | paste -sd,)` part of the Bash remediation fails when `/proc` is not available. We should try to avoid using it.

This is not a blocker as we can work around the problem in IB, but we should aim for offline-ready remediations.

#### SCAP Security Guide Version:

master

#### Operating System Version:

any

#### Steps to Reproduce:

1. Try to harden an IB image using CIS profile.

#### Actual Results:

Image is not properly remediated.

#### Expected Results:

Image is properly remediated.

IB Workaround: https://github.com/osbuild/osbuild/pull/1485

**Comment by marcusburghardt** [comment]
Are you aware of any way to create a remediation specific for ImageBuilder?
