### ISSUE TITLE
OSCAL Import Job Fails When Ran

### ISSUE THREAD

**Issue by Mab879** [ComplianceAsCode/content#11371]
#### Description of problem:
The OSCAL import introduce by #11286 

#### SCAP Security Guide Version:
https://github.com/ComplianceAsCode/content/commit/af19b67c1cede41bdbdca5c957cfe2c1d1d45552

#### Operating System Version:
`ubuntu-latest` in GitHub Actions

#### Steps to Reproduce:

1. Let the import job run
2. Observe the failure

#### Actual Results:
Job Passed

#### Expected Results:
Job Failed

#### Additional Information/Debugging Steps:
https://github.com/ComplianceAsCode/content/actions/runs/7155732155

**Comment by jpower432** [comment]
Will do @Mab879

**Comment by jpower432** [comment]
@Mab879 It appears this is a difference in where `act` supports GitHub env context and where the actions runners do. I will submit a PR to fix.
