### ISSUE TITLE
Ansible Playbooks fail to install a package

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#11399]
#### Description of problem:
The tests `/CoreOS/scap-security-guide/hardening/ansible` fail in most of their profile variants, except `cis` profiles:
- anssi_bp_28_high
- cui
- e8
- hipaa
- ism_o
- ospp
- pci-dss
- stig

It also happens in the `with-gui` alternative of this test.

The Ansible Playbook always fails on tasks that install a package, but it's not always the same package.

For example, in the STIG profile Playbook:

```

TASK [Ensure tmux is installed] ************************************************
fatal: [192.168.123.237]: FAILED! => {"changed": false, "msg": "Failed to validate GPG signature for tmux-2.7-3.el8.x86_64: Public key for tmux-2.7-3.el8.x86_64.rpm is not installed"}
```

Usually, there are some successful package installation earlier in the playbook run. We can suspect that some other task that is executed in between breaks this.

#### SCAP Security Guide Version:
current upstream master branch as of 2023-12-18 as of HEAD 73b1433

#### Operating System Version:
RHEL-8.10.0-updates-20231218.3

#### Steps to Reproduce:

1. ansible-playbook -v -i  ${IP}, --private-key /var/lib/libvirt/images/contest.sshkey /usr/share/scap-security-guide/ansible/rhel8-playbook-stig.yml

#### Actual Results:
Fatal error during Playbook run, Playbook terminates, test fails.

#### Expected Results:
Playbook finishes successfully.

#### Additional Information/Debugging Steps:
No

**Comment by jan-cerny** [comment]
I suspect that there can be something cheesy in the new compose because the fail isn't reproducible in the released RHEL 8.9.

**Comment by marcusburghardt** [comment]
It seems to be an infrastructure issue. In the provided example, Ansible is not able to confirm the `tmux` package came from a trusted source. This error should not be expected in a properly configured environment and I believe it is correct to fail the tasks when this happens.

It would be possible to use `ansible.builtin.rpm_key` or `ansible.builtin.yum_repository` modules to workaround this but this should not be the intention.

**Comment by jan-cerny** [comment]
This issue is still present as of 2023-12-21 using scap-security-guide-0.1.72-1.gitefb6e59.el8.src.rpm on RHEL-8.10.0-updates-20231220.49.

**Comment by jan-cerny** [comment]
This issue is still present as of 2024-01-02 using scap-security-guide-0.1.72-1.gitd15e2fe.el8.src.rpm / RHEL-8.10.0-20240101.1

**Comment by comps** [comment]
> It seems to be an infrastructure issue. 

It possibly isn't, since the bash remediation seems to be working fine (?).

The environment is one where repositories have `gpgcheck=0` and are without `gpgkey=`, and the bash remediations seem to correct that to `gpgcheck=1` and importing the Red Hat release key (via another rule).

It's only the ansible remediation that somehow doesn't fix this case.

Note that `gpgcheck=0` is not the default in customer-facing RHEL installations, but it's still a valid configuration that our rules should likely be able to deal with.

**Comment by jan-cerny** [comment]
Yes, the issue doesn't manifest in tests that run the Bash remediations, it happens only with Ansible remediations.
