### ISSUE TITLE
Add alinux2/alinux3 support for pci-dss compliance.

### ISSUE THREAD

**Issue by rain-Qing** [ComplianceAsCode/content#11397]
#### Description of problem:
Add pci-dss.profile compliance to alinux2 and alinux3 products.

#### SCAP Security Guide Version:
master

#### Expected Results:
`alinux2` and `alinux3` can be scanned and hardened for pci-dss compliance using the `oscap` command.

**Comment by marcusburghardt** [comment]
Closed by https://github.com/ComplianceAsCode/content/pull/11398

**Comment by marcusburghardt** [comment]
The PR https://github.com/ComplianceAsCode/content/pull/11398 is actually for the Issue https://github.com/ComplianceAsCode/content/issues/11396. Reopened.
