### ISSUE TITLE
Add anolis23/anolis8 support for pci-dss compliance.

### ISSUE THREAD

**Issue by rain-Qing** [ComplianceAsCode/content#11396]
#### Description of problem:
Add pci-dss.profile compliance to anolis23 and anolis8 products.

#### SCAP Security Guide Version:
master

#### Expected Results:
`anolis23` and `anolis8` can be scanned and hardened for pci-dss compliance using the `oscap` command.

**Comment by marcusburghardt** [comment]
Closed by https://github.com/ComplianceAsCode/content/pull/11398
