### ISSUE TITLE
ensure_redhat_gpgkey_installed fails

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#11409]
#### Description of problem:
Rule `ensure_redhat_gpgkey_installed` fails after Ansible remediation of a HIPAA profile on RHEL 8 as a part of daily productization run in the test `/CoreOS/scap-security-guide/hardening/ansible/hipaa`. It also happens for Ansible remediation of a ANSSI high with GUI on RHEL 8 in `/CoreOS/scap-security-guide/hardening/ansible/with-gui/anssi_bp28_high`.

#### SCAP Security Guide Version:
current upstream master branch as of 2024-01-02 as of HEAD d15e2fe

#### Operating System Version:
RHEL-8.10.0-20240101.1

#### Steps to Reproduce:

1. ansible-playbook -v -i ${IP},  /usr/share/scap-security-guide/ansible/rhel8-playbook-hipaa.yml

#### Actual Results:
xccdf_org.ssgproject.content_rule_ensure_redhat_gpgkey_installed:fail

#### Expected Results:
xccdf_org.ssgproject.content_rule_ensure_redhat_gpgkey_installed:pass

#### Additional Information/Debugging Steps:
This could be related to issue https://github.com/ComplianceAsCode/content/issues/11399 where we fail to install a package due to a fail of verifying a GPG signature.

**Comment by mildas** [comment]
Issue has been fixed in https://github.com/ComplianceAsCode/content/pull/11413. Closing
