### ISSUE TITLE
Rule service_bluetooth_disabled fails after Anaconda installation

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#11498]
#### Description of problem:
Rule `service_bluetooth_disabled` fails during productization with RHEL8 CIS Workstation Level 2 profile on Server with GUI package set.

#### SCAP Security Guide Version:
ad25a5b

#### Operating System Version:
RHEL 8

#### Steps to Reproduce:

1. Install CIS Server Level 2 hardened system (use OAA)
2. oscap xccdf eval --remediate --results=/root/openscap_data/eval_remediate_results.xml --report=/root/openscap_data/eval_remediate_report.html --profile=xccdf_org.ssgproject.content_profile_cis_workstation_l2 /root/openscap_data/contest-ds.xml

#### Actual Results:
service_bluetooth_disabled fails

#### Expected Results:
no unexpected fails

#### Additional Information/Debugging Steps:
I suspect the issue comes from Anaconda environment limitation.

**Comment by mildas** [comment]
The rule fails only in CIS Workstation Level 2 with GUI. It doesn't fail in other CIS profiles, thus it doesn't seem as Anaconda environment limitation.

**Comment by jan-cerny** [comment]
It could still be an Anaconda environment limitation. From the HTML report opened during installation, we can see that the rule service_bluetooth_disabled passed during the installation because it can't find the systemd unit bluetooth.service. Therefore the remediation wasn't executed.

The rule isn't part of CIS Workstation Level 1. It is part of both Server levels profiles, but during an installation of RHEL server/minimal, the package bluez providing the bluetooth service isn't installed by default. Since the package bluez isn't present, the rule service_bluetooth_disabled passes both during installation and after installation. This can explain why it doesn't fail in other CIS profiles.

Therefore I think it can be similar to past experience https://github.com/ComplianceAsCode/content/issues/5713 or https://bugzilla.redhat.com/show_bug.cgi?id=1834716.

We had an idea that we could solve this by adding a new rule package_bluez_disabled and adding this rule to  CIS Workstation Level 2 profile alongside to the service_bluetooth_disabled. This rule would ensure that the package bluez won't be installed. I verified that this isn't possible in the Anaconda installation. The bluez package is a dependency of various GNOME packages and therefore its removal conflicts with the Server with GUI package selection.
This will break the installation by the following message:

```

 Problem 1: package gnome-bluetooth-1:3.34.3-1.el8.x86_64 from AppStream requires bluez >= 5.0, but none of the providers can be installed
  - conflicting requests
  - package bluez-5.63-1.el8.x86_64 from anaconda is filtered out by exclude filtering
 Problem 2: package NetworkManager-bluetooth-1:1.40.16-14.el8.x86_64 from anaconda requires bluez >= 4.101-5, but none of the providers can be installed
  - conflicting requests
  - package bluez-5.63-1.el8.x86_64 from anaconda is filtered out by exclude filtering
 Problem 3: package gnome-shell-3.32.2-55.el8.x86_64 from AppStream requires gnome-bluetooth(x86-64) >= 1:3.9.0, but none of the providers can be installed
  - package gnome-bluetooth-1:3.34.3-1.el8.x86_64 from AppStream requires bluez >= 5.0, but none of the providers can be installed
  - conflicting requests
  - package bluez-5.63-1.el8.x86_64 from anaconda is filtered out by exclude filtering
 Problem 4: package gnome-control-center-3.28.2-37.el8.x86_64 from AppStream requires gnome-bluetooth(x86-64) >= 1:3.18.2, but none of the providers can be installed
  - package gnome-bluetooth-1:3.34.3-1.el8.x86_64 from AppStream requires bluez >= 5.0, but none of the providers can be installed
  - conflicting requests
  - package bluez-5.63-1.el8.x86_64 from anaconda is filtered out by exclude filtering
 Problem 5: package gnome-shell-3.32.2-55.el8.x86_64 from AppStream requires gnome-bluetooth(x86-64) >= 1:3.9.0, but none of the providers can be installed
  - package chrome-gnome-shell-42.1-1.el8.x86_64 from AppStream requires gnome-shell, but none of the providers can be installed
  - package gnome-bluetooth-1:3.34.3-1.el8.x86_64 from AppStream requires bluez >= 5.0, but none of the providers can be installed
  - conflicting requests
  - package bluez-5.63-1.el8.x86_64 from anaconda is filtered out by exclude filtering
 Problem 6: package gnome-shell-3.32.2-55.el8.x86_64 from AppStream requires gnome-bluetooth(x86-64) >= 1:3.9.0, but none of the providers can be installed
  - package gdm-1:40.0-27.el8.x86_64 from AppStream requires gnome-shell, but none of the providers can be installed
  - package gnome-bluetooth-1:3.34.3-1.el8.x86_64 from AppStream requires bluez >= 5.0, but none of the providers can be installed
  - cannot install the best candidate for the job
  - package bluez-5.63-1.el8.x86_64 from anaconda is filtered out by exclude filtering
 Problem 7: package gdm-1:40.0-27.el8.x86_64 from AppStream requires gnome-shell, but none of the providers can be installed
  - package gnome-shell-3.32.2-55.el8.x86_64 from AppStream requires gnome-bluetooth(x86-64) >= 1:3.9.0, but none of the providers can be installed
  - package gnome-initial-setup-3.28.0-11.el8.x86_64 from AppStream requires libgdm.so.1()(64bit), but none of the providers can be installed
  - package gnome-bluetooth-1:3.34.3-1.el8.x86_64 from AppStream requires bluez >= 5.0, but none of the providers can be installed
  - conflicting requests
  - package bluez-5.63-1.el8.x86_64 from anaconda is filtered out by exclude filtering
 Problem 8: package gnome-shell-extension-common-3.32.1-37.el8.noarch from AppStream requires gnome-shell >= 3.32.1, but none of the providers can be installed
  - package gnome-shell-extension-apps-menu-3.32.1-37.el8.noarch from AppStream requires gnome-shell-extension-common = 3.32.1-37.el8, but none of the providers can be installed
  - package gnome-shell-3.32.2-55.el8.x86_64 from AppStream requires gnome-bluetooth(x86-64) >= 1:3.9.0, but none of the providers can be installed
  - package gnome-classic-session-3.32.1-37.el8.noarch from AppStream requires gnome-shell-extension-apps-menu = 3.32.1-37.el8, but none of the providers can be installed
  - package gnome-bluetooth-1:3.34.3-1.el8.x86_64 from AppStream requires bluez >= 5.0, but none of the providers can be installed
  - conflicting requests
  - package bluez-5.63-1.el8.x86_64 from anaconda is filtered out by exclude filtering
```

WDYT?

**Comment by marcusburghardt** [comment]
> Yes, that understanding is correct. The systemd unit isn't known by the scanner during the installation because it reads the status of the installing system, not the status of the installed system.
> 
> Adding a rule that would explicitly ask for installation of the bluez package wouldn't change anything in this situation. The packages are installed before the oscap is executed.

Got it. So it a technical limitation. It is a similar case where a remediation for a requirement (install a package, for example) impacts another requirement (to configure a service introduced by the package installation) which was previously `not applicable` or have `passed`. In these cases it is necessary to scan and remediate the system again, in this case, after the installation.

**Comment by vojtapolasek** [comment]
@jan-cerny  Do I understand it correctly that the rule fails when the scan is performed after installation, but if the scan plus remediation is performed, then it gets remediated correctly?

**Comment by jan-cerny** [comment]
@vojtapolasek Yes, you understand that correctly. Users need to perform additional remediation after first start of the new system.

**Comment by jan-cerny** [comment]
Closing, it's a longstanding issue with OAA: https://bugzilla.redhat.com/show_bug.cgi?id=1834716
