### ISSUE TITLE
Review configure_crypto_policy tests with OSPP profile

### ISSUE THREAD

**Issue by marcusburghardt** [ComplianceAsCode/content#11516]
#### Description of problem:

Automatus tests can't conclude the tests scenarios for `configure_crypto_policy` rule in RHEL 9 for whenever `FIPS:OSPP` policy is selected. It is the case for the following test scenario scripts:
- missing_nss_config.fail.sh
- nss_config_as_file.pass.sh
- nss_config_as_symlink.pass.sh
- policy_fips_ospp_set.pass.sh
- missing_policy_file.fail.sh
- missing_policy.fail.sh
- wrong_policy.fail.sh

What is common on these scripts is the use of `update-crypto-policies --set "FIPS:OSPP"` command in the test scenario itself or during the remediation, in `fail.sh` scenarios.

#### SCAP Security Guide Version:

master and stabilization-0.1.72 branches as of 2024-01-31

#### Operating System Version:

RHEL 9

#### Steps to Reproduce:

1. ./build_product rhel9
2. ./tests/automatus.py rule --libvirt qemu:///session rhel9 --datastream build/ssg-rhel9-ds.xml --dontclean --remediate-using bash configure_crypto_policy

#### Actual Results:

The terminal is locked waiting to insert the root password.

#### Expected Results:

All test scenario scripts conclude as expected.

#### Additional Information/Debugging Steps:

Not an ideal neither complete solution, but for the mentioned test scenario scripts, the `fail.sh` ones can be updated with `remediation = none`. This would avoid the `"FIPS:OSPP"` policy to be applied.

For the `pass.sh` ones it is not so simple. We should figure out how to allow ssh access after applying the `"FIPS:OSPP"` policy.

**Comment by vojtapolasek** [comment]
Hello. I am unable to reproduce the issue. I tried connecting from both Fedora 38 and Fedora 39 to RHEL 9.4 machine and I can't reproduce the issue.
Even after enabling the FIPS:OSPP cryptopolicy manually on the RHEL machine, I can still connect without problems.
When following the steps to reproduce, I receive only following errors, which don't look so scary:
```
...
WARNING - Script policy_default_set.pass.sh - profile xccdf_org.ssgproject.content_profile_standard not found in data stream
...
ERROR - Script cis_l2.pass.sh using profile xccdf_org.ssgproject.content_profile_cis_workstation_l2 found issue:
ERROR - Rule xccdf_org.ssgproject.content_rule_configure_crypto_policy has not been evaluated! Wrong profile selected in test scenario?
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_configure_crypto_policy'.
INFO - Script policy_default_cis_l1.pass.sh using profile xccdf_org.ssgproject.content_profile_cis_server_l1 OK
ERROR - Script policy_default_cis_l1.pass.sh using profile xccdf_org.ssgproject.content_profile_cis_workstation_l1 found issue:
ERROR - Rule xccdf_org.ssgproject.content_rule_configure_crypto_policy has not been evaluated! Wrong profile selected in test scenario?
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_configure_crypto_policy'.
```

**Comment by marcusburghardt** [comment]
Thanks for this information @vojtapolasek . Since you couldn't reproduce the session issue mentioned in the description using fresh installed VMs, it is likely my local test environment has something more or less that is impeding an ssh connection when `FIPS:OSPP` policy is selected.

So I checked again the original tests and the errors there match with the errors in your test environment:
`ERROR - Rule xccdf_org.ssgproject.content_rule_configure_crypto_policy has not been evaluated! Wrong profile selected in test scenario?`

**Comment by marcusburghardt** [comment]
Hum, it seems this is not a new issue. See https://github.com/ComplianceAsCode/content/issues/10895

**Comment by marcusburghardt** [comment]
In the original description of this issue I also questioned an OVAL tests included in the rule.
For this, I filed a separate issue to not mix two different topics on the same issue: https://github.com/ComplianceAsCode/content/issues/11536

**Comment by mildas** [comment]
@marcusburghardt Do you agree with closing this issue, as it's duplicate of #10895 ?

**Comment by marcusburghardt** [comment]
> @marcusburghardt Do you agree with closing this issue, as it's duplicate of #10895 ?

Yes, let's centralize in https://github.com/ComplianceAsCode/content/issues/10895
