### ISSUE TITLE
Amazon Linux 2 --fetch-remote-sources points to invalid RHEL7 link

### ISSUE THREAD

**Issue by sgonza20** [ComplianceAsCode/content#11539]
#### Description of problem:

The amzn2 security guide references an invalid RHEL7 link: https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2

#### Details:

This content is not aligned with content from Red Hat. The link that OpenSCAP uses for fetching remote sources on Amazon Linux 2  `--fetch-remote-sources` is attempting to fetch it from _https://www.redhat.com/security/data/oval/v2/RHEL7/rhel-7.oval.xml.bz2_, though the link is no longer valid.

The misalignment affects these profiles:

- /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
- /usr/share/xml/scap/ssg/content/ssg-amzn2-ds.xml

The misalignment affects these rules:

- ...

#### Outcome:

- [ ] This project's content can be  improved:
  - [ ] Check needs to be improved.
  - [ ] Remediation needs to be improved.
- [ ] The external content's check is faulty - the other party needs to be notified, they have work to do.

**Comment by sgonza20** [comment]
Possible new RHEL7 link: [rhel-7.oval.xml.bz2](https://www.redhat.com/security/data/oval/v2/RHEL7/rhel-7.oval.xml.bz2)

**Comment by Mab879** [comment]
Thanks for opening this issue. 

Unfortunately, this project doesn't contain any content for Amazon Linux. You will need to contact their support to have them fix this issue.

As always, we would be happy to accept contributions to add Amazon Linux content.

This issue fixed here in https://github.com/ComplianceAsCode/content/pull/10842.

Hope this helps.
