### ISSUE TITLE
Rule configure_bashrc_tmux fails after hardening/installation

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#11569]
#### Description of problem:
The rule configure_bashrc_tmux fails in the daily productization tests in these tests:
- /CoreOS/scap-security-guide/hardening/oscap/stig
- /CoreOS/scap-security-guide/hardening/host-os/oscap/stig
- /CoreOS/scap-security-guide/hardening/oscap/with-gui/stig_gui

#### SCAP Security Guide Version:
current upstream master as of 2024-02-08 as of HEAD as of 8734eed

#### Operating System Version:
RHEL 9 (RHEL-9.4.0-updates-20240208.39)

#### Steps to Reproduce:

1. oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_stig --progress --remediate --report /var/tmp/contest-hardening-host-os-oscap-stig/remediation.html /var/tmp/contest-hardening-host-os-oscap-stig/modified_datastream.xml

#### Actual Results:
xccdf_org.ssgproject.content_rule_configure_bashrc_tmux:fail

#### Expected Results:
xccdf_org.ssgproject.content_rule_configure_bashrc_tmux:pass

#### Additional Information/Debugging Steps:
The problem can be related to the fact that `package_tmux_installed` is `fail` during the initial scan therefore the `configure_bashrc_tmux` is `notapplicable` during the initial scan, so the remediation installs tmux but doesn't remediate `configure_bashrc_tmux` but that rule becomes applicable  during the final scan and fails.

related to: https://github.com/ComplianceAsCode/content/pull/11561

**Comment by jan-cerny** [comment]
We have opened a PR to change waivers in contest: https://github.com/RHSecurityCompliance/contest/pull/99

**Comment by mildas** [comment]
Closing, it's issue in openscap https://github.com/OpenSCAP/openscap/issues/1880
