### ISSUE TITLE
Rule installed_OS_is_vendor_supported is misaligned with DISA

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#11649]
#### Description of problem:
The `installed_OS_is_vendor_supported` rule is misaligned with DISA disa-stig-rhel9-v1r0-xccdf-scap.xml benchmark (available in `content/shared/references`).

#### Details:
RHEL9 is not recognized as supported version.

#### Outcome:
SSG scan result: pass
DISA scan result: fail

#### SCAP Security Guide Version:
18cf4d8

####  External Content's Version:
RHEL 9 STIG V1R2

**Comment by ggbecker** [comment]
cat /etc/redhat-release
Red Hat Enterprise Linux release 9.0 (Plow)

Our regex doesn't match this:

https://github.com/ComplianceAsCode/content/blob/c0ed7eeb89dfe755e7a54fc26e4cd54afc04ea76/shared/checks/oval/installed_OS_is_rhel9.xml#L53


Whereas, DISA STIG is using:

`^\s*Red Hat Enterprise Linux release 9\.(\d+)`

from https://github.com/ComplianceAsCode/content/blame/master/shared/references/disa-stig-rhel9-v1r1-xccdf-scap.xml#L5078

**Comment by ggbecker** [comment]
The DISA content only allows currently supported/released RHEL versions (at this moment up to 9.3).

```
        <textfilecontent54_state xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5#independent" id="oval:mil.disa.stig.ind:ste:20000005" version="1">
          <subexpression datatype="int" operation="equals">3</subexpression>
        </textfilecontent54_state>
```

this comes from the DISA SCAP file.
https://github.com/ComplianceAsCode/content/blob/master/shared/references/disa-stig-rhel9-v1r1-xccdf-scap.xml#L33576

**Comment by ggbecker** [comment]
I can confirm that this test was run on a yet to be released RHEL9.4 compose therefore this is not an actual issue.

@mildas The SCAP content coming from DISA only accepts RHEL versions that have been already released, in this case up to 9.3.

I'm not sure if something can be done on the testing side to prevent issues like this. If we move the testing to github actions and test only on released RHEL versions, this would not manifest anymore.

**Comment by mildas** [comment]
We plan to stick with unreleased RHEL versions to test our content on upcoming package updates. And we would like to keep that also in github actions if that would be doable (as now we do on CentOS Stream).

Thus, unfortunately this seems as permanent waiver for Contest we can't do anything about.

**Comment by Mab879** [comment]
Is there anything else that be done on this issue?

Sounds like permanent waiver is needed then we can close this issue.

**Comment by mildas** [comment]
I've created Contest waiver update PR. When that's merged, this issue should be closed.
