### ISSUE TITLE
Rule kernel_module_tipc_disabled is misaligned with DISA

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#11650]
#### Description of problem:
The `kernel_module_tipc_disabled` rule is misaligned with DISA disa-stig-rhel9-v1r0-xccdf-scap.xml benchmark (available in content/shared/references).

#### Details:
<details>
  <summary>DISA benchmark fails on</summary>
<h4><span class="label label-primary">/etc/modprobe.d contains a file that contains 'install tipc /bin/true'</span> 
        <span class="label label-default">oval:mil.disa.stig.ind:tst:23049700</span> 
        <span class="label label-danger">false</span></h4><h5>No items have been found conforming to the following objects:</h5><h5>Object <strong><abbr>oval:mil.disa.stig.ind:obj:23049700</abbr></strong> of type
                <strong>textfilecontent54_object</strong></h5>
Path | Filename | Pattern | Instance
-- | -- | -- | --
/etc/modprobe.d | .* | ^[ \t]*install[ \t]+tipc[ \t]+/bin/true[ \t]*$ | 1
</details>

<details>
  <summary>SSG benchmark passes on</summary>
<h4><span class="label label-primary">kernel module tipc disabled</span> 
        <span class="label label-default">oval:ssg-test_kernmod_tipc_disabled:tst:1</span> 
        <span class="label label-success">true</span></h4><h5>Following items have been found on the system:</h5>
Path | Content
-- | --
/etc/modprobe.d/tipc.conf | install tipc /bin/false

</details>

See the detailed content of /etc/modprobe.d/tipc.conf and what is DISA looking for.

#### Outcome:
SSG scan result: pass
DISA scan result: fail

#### SCAP Security Guide Version:
https://github.com/ComplianceAsCode/content/commit/18cf4d8ba4c07083d8b3182a1bb44d66f8e324d0

####  External Content's Version:
RHEL 9 STIG V1R2

**Comment by Mab879** [comment]
Since this uses the `kernel_module_disabled` template I think all rules that use this template might cause an issue.

**Comment by mildas** [comment]
No idea what has changed, but the rule started to pass. I will remove the waiver from Contest and closing this issue
