### ISSUE TITLE
accounts_umask_etc_bashrc is misaligned with DISA

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#11700]
#### Description of problem:
accounts_umask_etc_bashrc is misaligned with DISA

#### Details:
DISA's rule marks this line in `/etc/bashrc` as offending:
```
[ `umask` -eq 0 ] && umask 022 
```

But this line is a part of block of code under condition for non-login shells so I think this line shouldn't be flagged.

#### Outcome:
SSG result: pass
DISA result: fail

The issue is present in these test variants:
- oscap
- ansible
- anaconda

#### SCAP Security Guide Version:
Current upstream master as of 2024-03-12 as of HEAD cbbca44.

####  External Content's Version:
DISA STIG RHEL 9 V1R1

**Comment by Mab879** [comment]
This needs more investigation. The check DISA is doing is following the letter of the check.
See https://stigaview.com/products/rhel9/v1r2/RHEL-09-412055/
