### ISSUE TITLE
sysctl_kernel_yama_ptrace_scope is misaligned with DISA

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#11704]
#### Description of problem:
sysctl_kernel_yama_ptrace_scope is misaligned with DISA

#### Details:
DISA rule finds different values in different places:

```
/etc/sysctl.conf	kernel.yama.ptrace_scope = 1
/usr/lib/sysctl.d/10-default-yama-scope.conf	kernel.yama.ptrace_scope = 0
/lib/sysctl.d/10-default-yama-scope.conf	kernel.yama.ptrace_scope = 0
/etc/sysctl.d/99-sysctl.conf	kernel.yama.ptrace_scope = 1
```

Similar to: https://github.com/ComplianceAsCode/content/issues/9307

#### Outcome:
SSG result: pass
DISA result: fail

The issue is present in these test variants:
- oscap
- ansible
- anaconda

#### SCAP Security Guide Version:
Current upstream master as of 2024-03-12 as of HEAD cbbca44.

####  External Content's Version:
DISA STIG RHEL 9 V1R1

**Comment by Mab879** [comment]
It must be defined in one place is not required by the STIG. See [RHEL-09-213080](https://stigaview.com/products/rhel9/latest/RHEL-09-213080).

**Comment by mildas** [comment]
Closing as duplicate of https://github.com/ComplianceAsCode/content/issues/9307
