### ISSUE TITLE
sssd_enable_pam_services lacks Ansible remediation

### ISSUE THREAD

**Issue by Mab879** [ComplianceAsCode/content#11753]
#### Description of problem:
The `sssd_enable_pam_services` rule fails after remediation with the ANSSI High profile 

#### SCAP Security Guide Version:
7a23c33

#### Operating System Version:
RHEL8/RHEL9

#### Steps to Reproduce:

1. Install RHEL 8/9 with the ANSSI High
2. Run a Ansible scan on the ANSSI High profile
3. Observe the failure

#### Actual Results:
Rule fails

#### Expected Results:
Rule passes

**Comment by vojtapolasek** [comment]
The rule does not have Ansible remediation. I changed the title.
The waiver for productization is here: https://github.com/RHSecurityCompliance/contest/pull/130
