### ISSUE TITLE
Inquiry Regarding Handling of "pkg_manager" Variable for Systems Without Package Manager

### ISSUE THREAD

**Issue by ZenByld** [ComplianceAsCode/content#11767]
Hello,

I am currently adding a product to complianceAsCode. This product is based on Linux but built with Buildroot. Therefore, I do not have a package manager in my system. In my product.yml file, there is a mandatory variable called pkg_manager. Consequently, I am forced to set the pkg_manager to yum, apt-get, etc. This leads to incorrect scan reports, with statuses consistently showing as "unknown" and errors of the type "OVAL object 'rpminfo_object' is not supported."

Could you please advise on how to handle the "pkg_manager" variable for systems that do not have a package manager?

Thank you in advance for your assistance.

**Comment by Mab879** [comment]
Thanks for your question.

So the `pkg_manager` field  is used heavily to see if a package is installed by the given package manager. Many rules that are not directly related to packages' installation state still use the package manager check to if package is installed for applicability reasons. Unfortunately, the project isn't well setup for systems without a  package manager.

What rules (or types of rules) are looking to use?
