### ISSUE TITLE
R38 ANSSI wrong file permissions

### ISSUE THREAD

**Issue by obp-anssi** [ComplianceAsCode/content#11779]
Rule [file_permissions_sudo](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/software/sudo/file_permissions_sudo/rule.yml) should cover ANSSI [R38](https://github.com/ComplianceAsCode/content/blob/master/controls/anssi.yml#L897) but does not.

The recommendation states :
```
A group dedicated to the use of sudo must be created. Only the members of this group should have the right to run sudo.
```
And the example given is `-rwsr-x---. 2 root sudogrp [...] /usr/bin/sudo`, so 4750.
Ref : https://cyber.gouv.fr/en/publications/configuration-recommendations-gnulinux-system

The idea is that *only* the users part of the group can execute the binary. However, the current rule is testing for 4111 thus allowing any user to execute it.

The pull request https://github.com/ComplianceAsCode/content/pull/11584 seem to say that 4111 is not possible (not sure why), but what about 4750 ?

If it's not possible to set 475***0*** for some reason, then the [R38](https://github.com/ComplianceAsCode/content/blob/master/controls/anssi.yml#L897) should not have the status `automated`.

**Comment by Mab879** [comment]
Agreed, this shouldn't automated at this time. 

See #11788
