### ISSUE TITLE
dnf-automatic_security_updates_only fails after Ansibe remedation

### ISSUE THREAD

**Issue by Mab879** [ComplianceAsCode/content#11773]
#### Description of problem:
dnf-automatic_apply_updates rules in fail after Ansible remedation.

#### SCAP Security Guide Version:
978d2c6

#### Operating System Version:
RHEL 9

#### Steps to Reproduce:

1. Remediate System with anssi_bp28_high using Ansible
2. Scan the system
3. Observe the failure
4.

#### Actual Results:
Rule fails

#### Expected Results:
Rule passes

#### Additional Information/Debugging Steps:

- https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/managing_software_with_the_dnf_tool/assembly_automating-software-updates-in-rhel-9_managing-software-with-the-dnf-tool#doc-wrapper
- https://dnf.readthedocs.io/en/latest/automatic.html

**Comment by marcusburghardt** [comment]
Closing by the same reason of #11772 
More details in [this comment](https://github.com/ComplianceAsCode/content/issues/11772#issuecomment-2060909057)
