### ISSUE TITLE
CCE-90811-1 is `notselected` by SSG, however for DISA STIG it `fail`

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#11803]
#### Description of problem:

The content is misaligned with an external (third party) content that targets the same policy - typically, this means that a system hardened by our content doesn't pass the scan by the external content.

#### Details:
Rule CCE-90811-1 which is `sshd_set_idle_timeout` is `notselected` in our content. The equivalent rule in DISA STIG checks the requirement and results in fail.

#### Outcome:
SSG and DISA contents are aligned

#### SCAP Security Guide Version:
latest master

####  External Content's Version:
REHL9 V1R2

**Comment by Mab879** [comment]
Should be easy fix add rule to control, maybe fix text.

**Comment by Mab879** [comment]
Set the `requires` on `sshd_set_idle_timeout` to `sshd_set_keepalive`
