### ISSUE TITLE
Chronyd rules' link http://chrony.tuxfamily.org link times out

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#11801]
#### Description of problem:
Couple of chronyd rules references http://chrony.tuxfamily.org web. But in recent productization run, the link times out.

#### SCAP Security Guide Version:
latest master

#### Operating System Version:
RHEL7, RHEL8, RHEL9

#### Steps to Reproduce:

1. Access http://chrony.tuxfamily.org in your browser

or

1. In Python3
```
import requests
requests.get('http://chrony.tuxfamily.org', timeout=10, headers={'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64;)'})
```

#### Actual Results:
Link times out

#### Expected Results:
Link is removed from content

#### Additional Information/Debugging Steps:
If the link starts to work reliably, we can leave it in content and close issue.

**Comment by comps** [comment]
This is fixed by https://github.com/ComplianceAsCode/content/pull/11799 (pls merge)
