### ISSUE TITLE
Content is not SCAP valid

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#11810]
#### Description of problem:
SCAPVal tool revealed datastreams are not scap valid because of SRC-330.

#### SCAP Security Guide Version:
latest master

#### Operating System Version:
RHEL7, RHEL8, RHEL9

#### Steps to Reproduce:

1. Download SCAPVal https://csrc.nist.gov/csrc/media/Projects/Security-Content-Automation-Protocol/tools/scap/1.3/scapval-1.3.6-rc3.zip
2. Unzip
3. `$ tests/run_scapval.py --scap-version 1.3 --scapval-path ~/Downloads/scapval-1.3.6-rc3/scapval-1.3.6.jar --datastream build/ssg-rhel8-ds.xml`

#### Actual Results:
```
Build dir: build
Testing ssg-rhel8-ds.xml ...
    SRC-330: FAIL
ssg-rhel8-ds.xml: FAIL
```

#### Expected Results:
No error

**Comment by jan-cerny** [comment]
The specific errors are in this form (example):

```
'Error: The given @idref attribute 'xccdf_org.ssgproject.content_group_apparmor' must match a the @id or @cluster-id attributes of a 'Rule' or 'Group' element. See the XCCDF 1.2.1 specification, Section 6.5.3. - TEST: /*//xccdf:Rule[@id=$idref or @cluster-id=$idref]|/*//xccdf:Group[@id=$idref or @cluster-id=$idref]'
```

This is caused by unused groups being removed from the data stream but they are still referenced from profiles.

**Comment by vojtapolasek** [comment]
It is caused by this PR: https://github.com/ComplianceAsCode/content/pull/11800
Test passes when you checkout the repo before it got merged.
