### ISSUE TITLE
Possibly add ensure_gpgcheck_local_packages ds_unselect for ANSSI

### ISSUE THREAD

**Issue by Mab879** [ComplianceAsCode/content#11926]
#### Description of problem:
This rule appears to be causing issues with productization.

#### SCAP Security Guide Version:
https://github.com/ComplianceAsCode/content/commit/0b096bc4d27936b5adf992817f6df250fe8a5501

#### Operating System Version:
RHEL 7.9

#### Actual Results:
Tests pass

#### Expected Results:
Tests fail

#### Additional Information/Debugging Steps:
None

**Comment by vojtapolasek** [comment]
This issue did not happen so far. I am closing it for now, but thank you for being proactive and notifying us.
