### ISSUE TITLE
sudo is broken in testing environment with ANSSI High

### ISSUE THREAD

**Issue by Mab879** [ComplianceAsCode/content#11925]
#### Description of problem:
sudo is broken in testing environment

#### SCAP Security Guide Version:
0b096bc

#### Operating System Version:
RHEL 7.9

#### Actual Results:
`bash: /usr/bin/sudo: Permission denied`

#### Expected Results:
sudo works

#### Additional Information/Debugging Steps:
#11586 and related PRs should be investigated

**Comment by vojtapolasek** [comment]
This has been resolved by excluding the rule file_permissions_sudo when performing tests.
