### ISSUE TITLE
accounts_umask_etc_bashrc is misaligned with RHEL 9 STIG

### ISSUE THREAD

**Issue by vojtapolasek** [ComplianceAsCode/content#11937]
#### Description of problem:

The rule accounts_umask_etc_bashrc is misaligned with its DISA counterpart.
The STIG is https://stigaview.com/products/rhel9/v1r3/RHEL-09-412055/
After remediating RHEL 9 with STIG Ansible playbook provided by the content repo and then using oscap to perform scan, the rule from the content repo is reported as "pass", while the rule within the SCAP file provided by DISA is reported as "fail".
The rule ID in the DISA file is xccdf_mil.disa.stig_rule_SV-258072r926203_rule.

#### SCAP Security Guide Version:

stabilization-v0.1.73, commit 0b096bc4d27936b5adf992817f6df250fe8a5501 

####  External Content's Version:
DISA SCAP version is v1r1.

**Comment by jan-cerny** [comment]
We had a similar issue lately: https://github.com/ComplianceAsCode/content/issues/11700 and it's marked as fixed by https://github.com/ComplianceAsCode/content/pull/11822.

**Comment by jan-cerny** [comment]
I have found in the test logs in the ARF results that the Playbook creates this:

```
    [ `umask` -eq 0 ] &amp;&amp; umask 027022
```

and the OVAL check accepts this as to pass the rule.

**Comment by vojtapolasek** [comment]
Wow, that does not look like valid command, especially the second umask, right?

**Comment by jan-cerny** [comment]
yes, you're correct, the umask here isn't valid, there should be just three digits after the umask
