### ISSUE TITLE
firewalld_sshd_port_enabled fails to remediate on aarch64

### ISSUE THREAD

**Issue by vojtapolasek** [ComplianceAsCode/content#11936]
#### Description of problem:

When remediating STIG profile on RHEL 9.4 on aarch64, the rule firewalld_ssh_port_enabled failed to remediate.

#### SCAP Security Guide Version:

stabilization-v0.1.73, commit 0b096bc4d27936b5adf992817f6df250fe8a5501 
#### Operating System Version:

RHEL 9.4

#### Steps to Reproduce:

- remediate whole STIG profile through oscap

#### Actual Results:

The rule seems to be remediated, the remediation does not exit with an error, but the final check fails.

#### Expected Results:

The final check passes.

#### Additional Information/Debugging Steps:

This might be some anomaly because this does not manifest on other RHEL versions.

**Comment by jan-cerny** [comment]
We need to reproduce if it fails deterministically

**Comment by jan-cerny** [comment]
I didn't reproduce it using contest today.

In the specific instance where this failed in the stabilization productization run the reason of the fail was that after the remediation there were 4 network interfaces but only 2 of them had the public zone set.

However, the test machine that I have now has only 1 network interface and the rule passes there after the remediation.

**Comment by jan-cerny** [comment]
I have created a VM with multiple network ifaces and it passed there, that means I haven't reproduced the issue there.

I think it's related to a specific property of these ifaces.

I think we need to watch if it happens again and once it happens we need to examine the ifaces on the offending system.

**Comment by vojtapolasek** [comment]
It did not happen in the last stabilization run. It might be some anomaly, let's wait for one more run and if it does not appear, this can be closed.

**Comment by vojtapolasek** [comment]
The issue did not appear. It was probably some anomaly.
