### ISSUE TITLE
test scenario for service_bluetooth_disabled is not causing expected fail

### ISSUE THREAD

**Issue by vojtapolasek** [ComplianceAsCode/content#11949]
#### Description of problem:

There is a test scenario which should make the rule service_bluetooth_disabled fail. But the rule passes when it is executed.

- service_enabled.fail.sh

#### SCAP Security Guide Version:

stabilization-v0.1.73, commit 0b096bc4d27936b5adf992817f6df250fe8a5501 

#### Operating System Version:

RHEL 8.6

#### Steps to Reproduce:

1. ./build_product rhel8
2. cd tests/
3. python automatus.py rule --libvirt qemu:///system <domain_name> --remediate-using oscap service_bluetooth_disabled

#### Actual Results:

The scan after applying test scenario should return "fail", but it returns "pass".

#### Expected Results:

The test scenario returns "fail" and the remediation is performed. The final result should be "pass".

**Comment by Mab879** [comment]
Locally I cannot reproduce:

```
$ ./automatus.py rule --datastream ../build/ssg-rhel8-ds.xml --remediate-using oscap  --libvirt qemu:///system automatus_rhel_8_6 service_bluetooth_disabled
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/mburket/Developer/ComplianceAsCode/content/tests/logs/rule-custom-2024-05-06-1614/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_service_bluetooth_disabled
INFO - Script service_enabled.fail.sh using profile (all) OK
INFO - Script service_disabled.pass.sh using profile (all) OK
```

**Comment by Mab879** [comment]
Needs more investigation from the testing env.
