### ISSUE TITLE
chronyd_or_ntpd_set_maxpoll fails after RHEL 7 STIG remediation

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#12035]
#### Description of problem:
Rule chronyd_or_ntpd_set_maxpoll  fails in Contest test /hardening/host-os/oscap/stig on RHEL 7.

#### SCAP Security Guide Version:
current upstream master as of 2024-05-29 as of HEAD 4cddad2

#### Operating System Version:
RHEL-7.9-20240526.n.0

#### Steps to Reproduce:

1. oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_stig --progress --report /var/tmp/contest-hardening-host-os-oscap-stig/remediation.html --remediate /var/tmp/contest-hardening-host-os-oscap-stig/remediation-ds.xml

#### Actual Results:
error, rule fails after remediation

#### Expected Results:
rule passes after remediation

#### Additional Information/Debugging Steps:
Probably caused by https://github.com/ComplianceAsCode/content/pull/11958

**Comment by vojtapolasek** [comment]
I can't reproduce it in local VM.It might have to do something with the Contest environment.

**Comment by jan-cerny** [comment]
This issue affects only RHEL 7. But, RHEL 7 end of life is on 2024-06-30 which is sooner than the next upstream release. That means that any fix for this issue wouldn't get to RHEL 7. Therefore I prefer not spending time here.
