### ISSUE TITLE
[Product Removal Request] RHEL7

### ISSUE THREAD

**Issue by Mab879** [ComplianceAsCode/content#12044]
#### Product to be removed:

RHEL 7

#### Reason for Product removal:

* Product End-Of-Maintenance is on 2024-06-30 according to [Red Hat](https://www.redhat.com/en/technologies/linux-platforms/enterprise-linux/rhel-7-end-of-maintenance). 
 
* Added: 2024-06-03 21:57 UTC Red Hat also stated that they no longer plan on updating RHEL 7 content after 2024-06-30, see the [Red Blog](https://www.redhat.com/en/blog/red-hat-enterprise-linux-7-end-compliance-content-june-30-2024) for more details.

#### Last contributors for the respective product:

1. @Mab879 
2.  @marcusburghardt 
3. @jan-cerny 
4. @evgenyz 
5. @vojtapolasek

#### Deadline to receive comments or objections:
2024-06-24 17:00 (UTC)

**Comment by GitYukari** [comment]
Strongly disagree. RHEL 7 is reaching end of _maintenance_ but it is not _end of life_. The announcement you linked explains:

> End of Maintenance (EOM) means that you will lose access to critical and important impact security advisories (RHSAs) and urgent priority bug fix advisories (RHBAs).
> Red Hat Enterprise Linux 7 will reach end of maintenance on June 30, 2024, but it is not reaching End of Life. 
> End of Life (EOL) occurs when a product or service is discontinued. Organizations that use the product will have to migrate to a new solution to continue receiving full support, updates, and security fixes.
>Additionally, CentOS Linux 7 will reach End of Life (EOL) on June 30, 2024. **Users [who migrate to Red Hat ](https://www.redhat.com/en/technologies/linux-platforms/enterprise-linux/centos-migration?cicd=32h281b)will convert their systems to Red Hat Enterprise Linux 7. From there, they can either upgrade to a newer version of Red Hat Enterprise Linux, or you can take advantage of Extended Lifecycle Support (ELS)**.

To align with that, it would be reasonable to remove CentOS, but not RHEL 7 until 2028 when the ELS ends according to: https://access.redhat.com/support/policy/updates/errata#Life_Cycle_Dates

**Comment by Mab879** [comment]
I also should have linked this: https://www.redhat.com/en/blog/red-hat-enterprise-linux-7-end-compliance-content-june-30-2024

Red Hat is not planning on updating this content after 30 June 2024.

**Comment by marcusburghardt** [comment]
The existing profiles for RHEL7 are stable and will continue there as they are.
As stated [here](https://www.redhat.com/en/blog/red-hat-enterprise-linux-7-end-compliance-content-june-30-2024) the compliance content won't receive updates after June 30, 2024.
Therefore, I don't see a reason to keep the product active in Upstream and their respective CI tests also consuming Upstream resources after this date. I support the product removal in Upstream after End-Of-Maintenance.

**Comment by vojtapolasek** [comment]
I think the blog post linked by @Mab879  explains it all. The content will not disappear from RHEL, it will just not be updated anymore.
