### ISSUE TITLE
Rule descriptions not up-to-date with the latest STIG

### ISSUE THREAD

**Issue by 0intro** [ComplianceAsCode/content#12088]
#### Description of problem:

The rule descriptions are not up-to-date with the latest STIG.

For example, after the update of the [RHEL 9 STIG](https://github.com/ComplianceAsCode/content/commit/cefcc10d5a9b855f1ae8c2029b890bb416dd49b0), the [policy/stig/shared.yml](https://github.com/ComplianceAsCode/content/blob/e7644a0bf5d3993fd229ff6965c758881ea85e83/linux_os/guide/system/permissions/restrictions/sysctl_kernel_yama_ptrace_scope/policy/stig/shared.yml) description of the `sysctl_kernel_yama_ptrace_scope` rule was updated:

But the `vuln_discussion` section is duplicated. The first one is the previous one and the new one appears at the end of the file.

```
vuldiscussion: |-
    Unrestricted usage of ptrace allows compromised binaries to run ptrace on another processes of the user. Like this, the attacker can steal
    sensitive information from the target processes (e.g. SSH sessions, web browser, etc) without any additional assistance from the user (i.e. without resorting to phishing).

[...]

vuln_discussion: |-
    Unrestricted usage of ptrace allows compromised binaries to run ptrace on other processes of the user. Like this, the attacker can steal sensitive information from the target processes (e.g., SSH sessions, web browser, etc.) without any additional assistance from the user (i.e., without resorting to phishing).
```

And the [rule.yml](https://github.com/ComplianceAsCode/content/blob/e7644a0bf5d3993fd229ff6965c758881ea85e83/linux_os/guide/system/permissions/restrictions/sysctl_kernel_yama_ptrace_scope/rule.yml) description was not updated:

```
rationale: |
    Unrestricted usage of ptrace allows compromised binaries to run ptrace
    on another processes of the user. Like this, the attacker can steal
    sensitive information from the target processes (e.g. SSH sessions, web browser, ...)
    without any additional assistance from the user (i.e. without resorting to phishing).
```

#### SCAP Security Guide Version:

`master` branch as of 2024-06-24 (644de124aa3df25282588a1b89fc28d1ea009e53).

**Comment by Mab879** [comment]
Thanks for opening this issue.

We have a script to update the policy files `./utils/import_disa_stig.py `.

It's basic and requires manual review but it helps a lot.

We usually don't update the `description` or `rationale` due to DISA's changes.

I will make a note to update these files once DISA releases a new version. Which should be in late July.
