### ISSUE TITLE
Rule timer_dnf-automatic_enabled fails after hardening

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#12119]
#### Description of problem:
Productization started to fail on these test paths:

- /hardening/host-os/ansible/cui/timer_dnf-automatic_enabled
- /hardening/host-os/ansible/ospp/timer_dnf-automatic_enabled

The rule `timer_dnf-automatic_enabled` fails after host OS hardening. According to the HTML report or ARF results, the rule fails because the `dnf-automatic.timer` property `LoadState` is `inactive`. I am able to consistently reproduce this situation in Contest. It's interesting that after logging via SSH to the machine the timer is enabled and the `LoadState` is `loaded`.  The problem seems to be that the timer started a few minutes after the OpenSCAP scan has finished.

There is interesting data in the journalctl output:

```
Jul 02 11:39:39 redacted oscap[1466]: Evaluation finished. Return code: 2, Base score 98.890480.

... SNIP ...


Jul 02 11:41:32 redacted systemd[1]: chrony-wait.service: start operation timed out. Terminating.
Jul 02 11:41:32 redacted systemd[1]: chrony-wait.service: Main process exited, code=exited, status=1/FAILURE
Jul 02 11:41:32 redacted systemd[1]: chrony-wait.service: Failed with result 'timeout'.
Jul 02 11:41:32 redacted systemd[1]: Failed to start Wait for chrony to synchronize system clock.
Jul 02 11:41:32 redacted systemd[1]: Reached target System Time Synchronized.
Jul 02 11:41:32 redacted systemd[1]: Started daily update of the root trust anchor for DNSSEC.
Jul 02 11:41:32 redacted systemd[1]: Started dnf-automatic timer.
Jul 02 11:41:32 redacted systemd[1]: Reached target Timers.
Jul 02 11:41:32 redacted systemd[1]: Starting The restraint harness....
Jul 02 11:41:32 redacted systemd[1]: Started Command Scheduler.

```

#### SCAP Security Guide Version:
current upstream master as of 2024-07-02 as of HEAD unknown

#### Operating System Version:
RHEL-8.10.0-20240617.22

#### Steps to Reproduce:

1. run /hardening/host-os/ansible/ospp/
2. systemctl status dnf-automatic.timer

#### Actual Results:
timer_dnf-automatic_enabled fails

#### Expected Results:
timer_dnf-automatic_enabled passes

#### Additional Information/Debugging Steps:

The Bash remediations are already waived in contest:

```
# Beaker-specific, possibly;
# same for dnf-automatic and rsyslog (??), is this fully random?
/hardening/host-os/oscap/[^/]+/package_dnf-automatic_installed
/hardening/host-os/oscap/[^/]+/timer_dnf-automatic_enabled
/hardening/host-os/oscap/[^/]+/package_rsyslog-gnutls_installed
```

**Comment by mildas** [comment]
There is no plan for RHEL 8.10 CC certification and thus no plans with OSPP (our CUI is wrong and just a copy of OSPP) profile. We've decided to label it as `blocked` as we don't want to spend time on this.

If it appears in other profiles, we can remove the label.

**Comment by ggbecker** [comment]
This looks like a time synchronization issue that is not worth investing time. For RHEL9 OSPP profile this rule is also selected and doesn't manifest any problems.

**Comment by ggbecker** [comment]
And if we consider that eventually after some time the service is correctly loaded, I don't think is part of CaC to try and fix this waiting time issue.

**Comment by ggbecker** [comment]
@mildas I'd suggest we close this one, what do you think?

**Comment by mildas** [comment]
@ggbecker Yes, agree. Closing
