### ISSUE TITLE
[Product Removal Request] Debian 10

### ISSUE THREAD

**Issue by Mab879** [ComplianceAsCode/content#12111]
#### Product to be removed:

Debian 10

#### Reason for Product removal:

* Product End-Of-Life (EOL) was on 2024-06-30 according to the [Debian Wiki](https://wiki.debian.org/LTS)

#### Last contributors for the respective product:

1. @richardmaciel-canonical

#### Deadline to receive comments or objections:

2024-07-22 18:00 UTC (use `date -d '2024-07-22 18:00 UTC'` to translate to your local time)

**Comment by a-skr** [comment]
Debian 8, 9 and 10 are still supported as part of ELTS support (see Debian wiki: https://wiki.debian.org/LTS/Extended). End Of Life is 30 June, 2029 for Debian 10.

Wether you want to support ELTS versions or not is up to you.

**Comment by Mab879** [comment]
Thanks for your comment about ELTS. In the past we have removed Debian 9 see https://github.com/ComplianceAsCode/content/issues/9443 when the normal LTS ends. RHEL 7 (#12112 and #12044)  got a similar treatment recently as well.
