### ISSUE TITLE
Removal of uos20 due to inactivity

### ISSUE THREAD

**Issue by inntran** [ComplianceAsCode/content#12135]
#### Product to be removed:
uos20, full name is: "UnionTech OS Server 20"

#### Reason for Product removal:

* Lack of contribution:
  * The last update for this product happened on 2022-06-25, through the PR#8779
  * No issues are filed or discussions were created for this product within last 2 years.

#### Last contributors for the respective product:

1. @binyanling
1. @2544246302

#### Deadline to receive comments or objections:

2024-07-28 00:00 (UTC)
* Hint: An initial timeframe of 21 days should be set.

**Comment by yijiyouyu** [comment]
What steps are required to restore the UOS V20 product?
