### ISSUE TITLE
SCAP Compilation Error When Using --rule-id with a Single SCE Rule

### ISSUE THREAD

**Issue by yu410621** [ComplianceAsCode/content#12228]
Hello

#### Description of problem:
I am encountering an error when attempting to compile a SCAP content using the --rule-id parameter to specify a single Security Content Automation Protocol (SCE) rule.

#### Steps to Reproduce:

1.Select any existing SCE rule within the project.
2.Compile the content while specifically targeting this rule using the following command:
`ADDITIONAL_CMAKE_OPTIONS="-DSSG_SCE_ENABLED=ON" ./build_product fedora --rule-id set_ip6tables_default_rule`
3.The compilation process fails with the following error message:
`[ 53%] [fedora-content] generating ssg-fedora-oval.xml`
`Error copying file "/root/github/content/build/fedora/ssg-fedora-oval.xml" to "/root/github/content/build/ssg-fedora-oval.xml".`
`make[3]: *** [fedora/CMakeFiles/generate-ssg-fedora-oval.xml.dir/build.make:75：ssg-fedora-oval.xml] Error 1`
`make[2]: *** [CMakeFiles/Makefile2:695：fedora/CMakeFiles/generate-ssg-fedora-oval.xml.dir/all] Error 2`

#### Additional Information:
I understand that OVAL rules are generally preferred within this project, but there are certain scenarios where SCE rules are necessary. I encountered this issue while attempting to compile a custom SCE rule.

**Comment by yu410621** [comment]
Hello all,

I'm new to the content project and I'm wondering if it's problematic to compile a single SCE rule individually. 
Could you please share your experiences and insights on this?

Thank you!

**Comment by Mab879** [comment]
Thanks for reporting this issue. It seems that the thin data streams code doesn't like SCE.

You scan still compile a normal data stream and use `oscap`'s `--rule` to limit what is scanned.

However, this should be fixed at some point.

**Comment by yu410621** [comment]
> Thanks for reporting this issue. It seems that the thin data streams code doesn't like SCE.
> 
> You scan still compile a normal data stream and use `oscap`'s `--rule` to limit what is scanned.
> 
> However, this should be fixed at some point.

@Mab879 Thank you for your guidance.
