### ISSUE TITLE
firewalld_sshd_port_enabled fails on aarch64 in ism_o profile

### ISSUE THREAD

**Issue by vojtapolasek** [ComplianceAsCode/content#12233]
#### Description of problem:

The rule mentioned in the title fails when ism_o profile is remediated and evaluated on AARCH64 system.

#### SCAP Security Guide Version:

master as of d9086f6c3f5d1392e1116486d5a5208c8cba7f8d

#### Operating System Version:

RHEL 9.0

#### Steps to Reproduce:

1. provision AARCH64 machine with RHEL 9.0
2. perform hardening of the CUI profile with something like

```
oscap xccdf eval --remediate --profile ism_o ssg-rhel9-ds.xml
```

#### Actual Results:

The mentioned rule is reported as failing in the final report, although the remediation looks to be performed correctly.

#### Expected Results:

The rule is reported as passing.

#### Additional Information/Debugging Steps:

It seems that the OVAL check of the rule fails because of this particular test:  test_firewalld_sshd_port_enabled_all_nics_in_zones

**Comment by Mab879** [comment]
```
[root@rhel9]# oscap xccdf eval --remediate --profile ism_o --rule xccdf_org.ssgproject.content_rule_firewalld_sshd_port_enabled ssg-rhel9-ds.xml 
--- Starting Evaluation ---

Title   Enable SSH Server firewalld Firewall Exception
Rule    xccdf_org.ssgproject.content_rule_firewalld_sshd_port_enabled
Ident   CCE-89175-4
Result  fail


--- Starting Remediation ---

Title   Enable SSH Server firewalld Firewall Exception
Rule    xccdf_org.ssgproject.content_rule_firewalld_sshd_port_enabled
Ident   CCE-89175-4
Result  error
```

The remediation might be suspect.

**Comment by mildas** [comment]
@Mab879 are you sure `firewalld` and `NetworkManager` are on?
I wasn't able to reproduce it in `--rule` mode when those services are started:
```
[root@hpe-apollo-cn99xx-14-vm-28 ~]# oscap xccdf eval --remediate --rule xccdf_org.ssgproject.content_rule_firewalld_sshd_port_enabled ssg-rhel9-ds.xml
--- Starting Evaluation ---

Title   Enable SSH Server firewalld Firewall Exception
Rule    xccdf_org.ssgproject.content_rule_firewalld_sshd_port_enabled
Ident   CCE-89175-4
Result  fail


--- Starting Remediation ---

Title   Enable SSH Server firewalld Firewall Exception
Rule    xccdf_org.ssgproject.content_rule_firewalld_sshd_port_enabled
Ident   CCE-89175-4
Result  error

[root@hpe-apollo-cn99xx-14-vm-28 ~]# systemctl start NetworkManager; systemctl start firewalld
[root@hpe-apollo-cn99xx-14-vm-28 ~]# oscap xccdf eval --remediate --rule xccdf_org.ssgproject.content_rule_firewalld_sshd_port_enabled ssg-rhel9-ds.xml
--- Starting Evaluation ---

Title   Enable SSH Server firewalld Firewall Exception
Rule    xccdf_org.ssgproject.content_rule_firewalld_sshd_port_enabled
Ident   CCE-89175-4
Result  fail


--- Starting Remediation ---

Title   Enable SSH Server firewalld Firewall Exception
Rule    xccdf_org.ssgproject.content_rule_firewalld_sshd_port_enabled
Ident   CCE-89175-4
Result  fixed
```

^ aarch64, RHEL 9.0.0 GA compose

**Comment by mildas** [comment]
> I recently found a similar error on the STIG aarch64 test as well.
But this time it's 9.2. ISM in 9.0 is fine.

**Comment by Mab879** [comment]
I think that makes sense to exclude loop back.

**Comment by jan-cerny** [comment]
yes it probably makes sense to apply it on all interface types except loopback
