### ISSUE TITLE
Update profile to DISA STIG RHEL 9 V2R1

### ISSUE THREAD

**Issue by christopher-davidson** [ComplianceAsCode/content#12237]
#### Description of problem:

The content is misaligned as it currently uses V1R3 of the STIG for RHEL 9. 

#### Details:

The misalignment affects these profiles: STIG, STIG with GUI

The misalignment affects these rules:
### 
- See STIG version history. https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/U_RHEL_9_V2R1_STIG.zip

**Comment by Mab879** [comment]
Thanks for opening this issue.

I have reviewed the changes made in V2R1 there no substantive changes to the benchmark. 

The only changes where updates to CCI numbers and minor capitalization changes.

That being said updates will happen soon.
