### ISSUE TITLE
Rule enable_fips_mode fails to remediate on RHEL-10

### ISSUE THREAD

**Issue by matusmarhefka** [ComplianceAsCode/content#12405]
#### Description of problem:
Tested with OSPP profile. The rule `enable_fips_mode` remediation is applied to the system but after reboot in the successive scan it fails. This is caused by OVAL test `test_etc_system_fips` which is evaluated as false because `/etc/system-fips` file is not found on the system.

#### SCAP Security Guide Version:
db7b59bd68cbca5c6f536e2dd9ec8e3f8e0629cc

#### Operating System Version:
RHEL-10

**Comment by Mab879** [comment]
`/etc/system-fips` is no longer supported. See this [commit](https://gitlab.com/redhat-crypto/fedora-crypto-policies/-/commit/a782a5578b3ef67d9bf6d8e6999807183f8e3ebc).

**Comment by Mab879** [comment]
Also noted it will be removed in the RHEL 9 deprecation notes, https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/9.0_release_notes/deprecated_functionality#deprecated-functionality_security
