### ISSUE TITLE
alpine support

### ISSUE THREAD

**Issue by colton-freeman** [ComplianceAsCode/content#12417]
i apologize in advance, im sure you get this question all the time. 

i could not find anything about this in the previously opened issues nor in any docs in this repo. 

is there any planned support for alpine in the future?

**Comment by Mab879** [comment]
Thanks for opening this issue. Products are added by the community or by the companies behind the products. I have not heard of any plans to add it, but pull requests are welcome to add it.

**Comment by colton-freeman** [comment]
ah, that makes sense. thank you for the response.
