### ISSUE TITLE
RHEL8 STIG - Rules missing identifiers

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#12421]
#### Description of problem:
Each STIG rule should have CCI, SRG, and STIGID references, but during testing I have discovered these missing:

List of rules missing CCI reference:
 - package_postfix_installed - missing CCI
 - enable_authselect - missing STIG ID

#### SCAP Security Guide Version:
master

#### Operating System Version:
RHEL 8

**Comment by Mab879** [comment]
May be solved by https://github.com/ComplianceAsCode/content/pull/12374

**Comment by mildas** [comment]
@Mab879 tested latest master and most of CCI are there. However, I've discovered 2 missing identifiers in STIG rules. See updated issue description

**Comment by Mab879** [comment]
`enable_authselect` missing a STIG ID is expected.

**Comment by mildas** [comment]
Could you provide context for expected no STIG ID for `enable_authselect`? So I have reasoning for permanent waiver

**Comment by Mab879** [comment]
There is no rule in the STIG for enabling authselect, but that rule is needed so our other authselect rules work.
