### ISSUE TITLE
RHEL9 STIG - Rules missing CCI

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#12424]
#### Description of problem:
A lot of RHEL9 STIG rules are missing CCI reference:
- dconf_db_up_to_date
- file_groupowner_etc_shadow
- file_permissions_cron_hourly
- package_openssh-clients_installed
- file_groupowner_etc_group
- file_owner_cron_d
- file_groupowner_etc_gshadow
- file_owner_cron_weekly
- mount_option_var_nodev
- file_groupowner_etc_passwd
- file_groupowner_crontab
- partition_for_var_tmp
- package_sudo_installed
- file_groupowner_cron_d
- package_policycoreutils-python-utils_installed
- file_groupowner_backup_etc_shadow
- dconf_gnome_disable_user_list
- ssh_keys_passphrase_protected
- aide_build_database
- file_owner_cron_hourly
- file_owner_cron_daily
- package_chrony_installed
- mount_option_home_nodev
- file_permissions_cron_weekly
- sysctl_net_ipv4_icmp_ignore_bogus_error_responses
- configure_crypto_policy
- firewalld_sshd_port_enabled
- package_gnutls-utils_installed
- package_audispd-plugins_installed
- file_permissions_cron_monthly
- auditd_freq
- configure_kerberos_crypto_policy
- file_permissions_cron_d
- file_groupowner_cron_hourly
- auditd_write_logs
- file_owner_sshd_config
- file_owner_crontab
- file_permissions_cron_daily
- configure_bind_crypto_policy
- package_subscription-manager_installed
- configure_libreswan_crypto_policy
- file_groupowner_sshd_config
- file_groupowner_cron_weekly
- mount_option_boot_nodev
- file_owner_cron_monthly
- package_nfs-utils_removed
- file_permissions_crontab
- package_nss-tools_installed
- package_crypto-policies_installed
- logind_session_timeout

#### SCAP Security Guide Version:
RHEL9

#### Operating System Version:
master

**Comment by Mab879** [comment]
May be solved by #12374

**Comment by mildas** [comment]
@Mab879 I did re-run with latest master and all rhel9 references are now correct. Thanks!
