### ISSUE TITLE
Blueprint fix generation ignores tailoring file

### ISSUE THREAD

**Issue by kingsleyzissou** [ComplianceAsCode/content#12444]
#### Description of problem:
If I add a tailoring file as an argument to generate a toml  blueprint file for osbuild, the fix ignores the rules specified in the tailoring file.

#### SCAP Security Guide Version:
0.1.74

#### Operating System Version:
fc40

#### Steps to Reproduce:

1. `autotailor -u  "rule_partition_for_var" -p cis  /usr/share/xml/scap/ssg/content/ssg-cs9-ds.xml cis > tf.xml`
2. `oscap xccdf generate fix --profile cis --tailoring-file tf.xml --fix-type blueprint /usr/share/xml/scap/ssg/content/ssg-cs9-ds.xml`

#### Actual Results:
Inspect the generated blueprint and a mountpoint option is there for the `/var` partition.

I have not tested other customizations such as enabled and disabled/masked services, but I assume it's the same.

#### Expected Results:
No `/var` partition in the generated toml document (or other tailored items)

**Comment by kingsleyzissou** [comment]
cc @evgenyz

**Comment by evgenyz** [comment]
Aha, okay.

`W: oscap: Selector ID(xccdf_org.ssgproject.content_rule_rule_partition_for_var) does not exist in Benchmark and it will be ignored.` 

You should use either `partition_for_var` or `xccdf_org.ssgproject.content_rule_partition_for_var`.

**Comment by kingsleyzissou** [comment]
Ahhh right of course 🤦‍♂️ really silly mistake there. Thanks for that 🙏 

Obviously it's just easier to copy the full rule name to avoid these mistakes, it just makes the commands more verbose

**Comment by kingsleyzissou** [comment]
Closing because this was user error
