### ISSUE TITLE
The scenario `lenient_value_full.fail.sh` of the rule `sshd_set_maxstartups`  is failing.

### ISSUE THREAD

**Issue by Mab879** [ComplianceAsCode/content#12677]
#### Description of problem:
The scenario `lenient_value_full.fail.sh` of the rule `sshd_set_maxstartups`  is failing.

#### SCAP Security Guide Version:
bf4ee4558d4e5f2e5dbdd80eae99f44a9d913b46

#### Operating System Version:
RHEL 8/9

#### Steps to Reproduce:

1. `./build_product -j $(nproc) rhel10 rhel8 rhel9`
2. `./automatus.py rule --datastream ../build/ssg-rhel9-ds.xml --libvirt qemu:///system automatus_rhel9_4 sshd_set_maxstartups`

#### Actual Results:
```
ERROR - Script lenient_value_full.fail.sh using profile (all) found issue:
ERROR - Rule evaluation resulted in pass, instead of expected fail during initial stage 
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_sshd_set_maxstartups'.
```

#### Expected Results:
Test passes.

#### Other Information 
Related #12668

**Comment by mpurg** [comment]
Sorry about that. See proposed fix #12682
