### ISSUE TITLE
Ubuntu Linux 24.04 LTS Benchmark content (Version: Draft 0.1.76) causes oscap to crash

### ISSUE THREAD

**Issue by bhattisatish** [ComplianceAsCode/content#12718]
#### Description of problem:
While running the latest Ubuntu 24.04 LTS benchmark against the oscap 1.3.9 in Ubuntu 24.04 causes oscap to crash.

#### SCAP Security Guide Version:
Version: 0.1.76
draft (as of 2024-12-13)

#### Operating System Version:
Distributor ID: Ubuntu
Description: Ubuntu 24.04.1 LTS
Release: 24.04
Codename: noble

#### Steps to Reproduce:

1.  `git clone https://github.com/complianceascode/content.git`
2.  `cd content/` and `./build_product ubuntu2404` and `cd ..`
3.  Run either of the following commands:
     - `oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_cis_level1_workstation --results arf1.xml --report report1.html content/build/ssg-ubuntu2404-ds.xml`
     - `oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_cis_level2_workstation --results arf2.xml --report report2.html content/build/ssg-ubuntu2404-ds.xml`
    
#### Actual Results:
Causes `oscap` command to crash with
```
oscap: ./src/XCCDF_POLICY/xccdf_policy.c:627: xccdf_policy_is_item_selected: Assertion `false' failed.
Aborted (core dumped)
```
[Debug log](https://github.com/user-attachments/files/18127263/eval.log.gz)

#### Expected Results:
A successful run with _**arf1.xml**_ with the results and **_report1.html_** with the final evaluation report.

#### Additional Information/Debugging Steps:

Refers: https://github.com/OpenSCAP/openscap/issues/2188
The debug log is available. [eval.log.gz](https://github.com/user-attachments/files/18127263/eval.log.gz)

The output of `build_product ubuntu2404` is also available at [content-build.tar.gz](https://github.com/user-attachments/files/18136277/content-build.tar.gz)

**Comment by dodys** [comment]
current content for Ubuntu 24.04 is still in progress. Not all the rules are working or tested against it.
Therefore I would recommend waiting.

**Comment by evgenyz** [comment]
It looks like it's a Ubuntu's OpenSCAP package problem.

**Comment by mpurg** [comment]
I narrowed it down to the `conflicts` line which was introduced to the `sshd_enable_warning_banner_net` rule recently: https://github.com/ggbecker/content/blob/44b40aabae514e54b8dbbb237f0b4547ed7f254b/linux_os/guide/services/ssh/ssh_server/sshd_enable_warning_banner_net/rule.yml#L49

The issue disappears when I remove it.
