### ISSUE TITLE
Add support for Internationalization

### ISSUE THREAD

**Issue by pthierry38** [ComplianceAsCode/content#1309]
I propose to support internationalization for guides and benchmarks, using xml markup to support various languages (based on https://www.w3.org/TR/xml-i18n-bp/#DevLang for example), allowing the generations of guides and benchmarks for each supported languages.

We can first support English language first, and add others after, when the support for internationalization is ready.

**Comment by redhatrises** [comment]
Using Zanata (http://zanata.org/) should be looked into for this as `publican` is supported which should make it easy to translate over to SSG.

**Comment by chagara** [comment]
you should look into https://www.transifex.com as they provide a free project to open source programs. Tons of places use it and makes translation easier.

**Comment by redhatrises** [comment]
Support for internationalization would be great, but I don't think that we will be able to get to this at all unless someone is willing to contribute and work on this. Closing until someone is willing to take this up and work on it.
