### ISSUE TITLE
Create a rule that verifies that the source of base images are trusted sources

### ISSUE THREAD

**Issue by thetuxracer** [ComplianceAsCode/content#1349]
Docker images should be built from trusted and official docker or docker partner repositories. Examples would be registry.access.redhat.com or registries marked official on docker.io. To accomplish this, the image's hash can be inspected. For Red Hat base images, SHA is [publicly available](https://registry.access.redhat.com/v1/repositories/library/rhel7/tags). I do not know of APIs to check SHAs of official images hosted on hub.docker.com, this is something that I would like to hear alternate approaches.

We can highlight this in the report in case the user has deliberately used a custom image.

**Comment by matejak** [comment]
To rephrase the issue - there should be a rule applicable only to containers that will make sure that e.g. a RHEL7 container image is based on correct bas images.
Remarks:
* It doesn't make sense to have remediations for this rule - how do you rebase a container image?
* The check requires having access to image hashes from inside the scanned container, which may not be possible.
