### ISSUE TITLE
oscap-docker should verify absence of sshd package inside the image

### ISSUE THREAD

**Issue by thetuxracer** [ComplianceAsCode/content#1351]
Running ssh inside the container necessitates the installation of openssh server/client and adds to complexity of security management because its difficult to audit and keep track of ssh keys. It also becomes difficult to consume security updates to the openssh packages caused by CVE/RHSA. Docker provides an inbuilt way to obtain shell access to a container which should be used rather than an ssh package. 

In case the package is found to be installed, the report can flag the practice.

**Comment by matejak** [comment]
Having SSH installed in a container may be legitimate - imagine e.g. an SFTP container.
