### ISSUE TITLE
firewalld_sshd_port_enabled rule doesn't work when using Kickstart

### ISSUE THREAD

**Issue by mathieu-grondin** [ComplianceAsCode/content#1639]
After using "stig-rhel7-server-upstream" profil on my centos, I can't sign in with ssh but I can locally sign in .

And when I manually execute "firewall-cmd --permanent --add-service=ssh" command. I can sign in by using ssh.

**Comment by redhatrises** [comment]
@mathieu-grondin can you please provide the version of scap-security-guide that you are using?

**Comment by xmtrcv** [comment]
I have experienced this issue as well with _"xccdf_org.ssgproject.content_profile_stig-rhel7-server-upstream"_ (and also with _"stig-rhel7-server-upstream"_) using version **0.1.31**.

It also occurrs with a version of scap-security-guide-master downloaded on 20170103.

For the time being, adding the following to my remediation script (run at first boot after kickstart) to overcomes the issue: `firewall-offline-cmd --service=ssh`

**Comment by mpreisler** [comment]
Could be related to https://bugzilla.redhat.com/show_bug.cgi?id=1401069

**Comment by mathieu-grondin** [comment]
I tested its with the master branch dated 2016 11 25 (just two or three day before 1.31) and with the master branch dated 2017 01 11 (on 1.31 version)

**Comment by redhatrises** [comment]
Since this issue happens in a kickstart environment, I have created the following issue https://github.com/OpenSCAP/oscap-anaconda-addon/issues/19 for the Oscap Anaconda plugin to handle firewalld rules which is IMO the best way of fixing this issue.

**Comment by cpellitt** [comment]
You can fix this by checking if firewalld is running and using firewall-offline-cmd if it isn't. Then it will work in all environments, kickstart or otherwise.

```
# Use firewall-offline-cmd if firewalld is not running
if [ "$(systemctl is-active firewalld.service)" == "active" ]; then
   firewall_cmd="/bin/firewall-cmd --permanent"
else
   firewall_cmd="/bin/firewall-offline-cmd"
fi

if [ $sshd_listening_port -ne 22 ]; then
   $firewall_cmd --add-port=$sshd_listening_port/tcp
else
   $firewall_cmd --add-service=ssh
fi
```
