### ISSUE TITLE
Clean generated files & update templates and csv files

### ISSUE THREAD

**Issue by ybznek** [ComplianceAsCode/content#1668]
We had/have lot of files in repository (remediations/oval). Most of such files was once generated from some templates & csv files and then were these files pushed into repository. Later, some of them were updated manually.

Every new product is created by copy&paste of old product. So we have LOT of duplicates in files. When somebody fix e.g. remediations in RHEL7, RHEL6 remediations still contain old code.

It is very hard to maintain, because in such amount of files, we cannot see e.g. we have remediation script for some rule, but we miss oval check for it.

When I needed to add ansible remediations to several products, it wasn't able to do that without copy/pasting of new ansible. So I started to do cleaning of generated files and started to generate these files during build. It is much easier to change it from one place than in maybe hundreds of generated files. It is partially done( for remediations).

Currently I need to finish this change with oval files.

Final set of scripts for product are build from:
- **shared files generated from templates**  - e.g. `package_<package_name>_removed` - shared for all products
- **shared static files**  - for very specific check, or special case of standard check
- **product files generated from templates**
- **product static files**

So e.g. you can have shared template for **package*removed** (dnf remove `<package name>`) and many product can use it without copy&paste. But If you create our own package*removed template in our product, you can use own implementation e.g. (apt-get remove `<package name>`).

How are files generated : **CSV** + **template** => **files**
e.g.  **packages_removed.csv** + **template_package_removed** => **package_abrt_removed.xml**, **package_acpid_removed.xml**, ...

So my current plan(for every product):
1. **remove** generated files
2. update **.csv** files and start to use **templates** (be able to generate files from point 1)
3. files what cannot be generated move to **"static"** folder
4. delete **input** folder

This should reduce amount of files and then it will be easier to fix bugs or find duplicated files(it is easier to compare 1 vs 1 template, than compare 20 vs 20 files).
Once we reduce amount of files, it should be much easier to modify whole structure.

I am going to produce lot of PRs.
- they should mostly contains points 1 and 2 from plan
- they shouldn't change output datastreams (no bugfixing in general)
- I use https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/utils/compare_generated.sh to check whether I changed something - I compare datastreams before and after changes
- I check it for oval_5.10 and oval_5.11 https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/product-make.include#L47
- I will try to do independent PR, so reviewer should be able to merge several PRs into one and then check them

Do you have any better ideas?

**Comment by pthierry38** [comment]
I agree with this idea. There is a lot of duplication between various products. Yet there is some work to support real shared templates. In the case of your example (packages that need to be removed) there is a difference between deb based and rpm-based products

```shell
$ diff -u Debian/8/templates/template_package_removed  RHEL/6/input/oval/templates/template_package_removed 
--- Debian/8/templates/template_package_removed	2017-01-23 13:06:52.606471743 +0100
+++ RHEL/6/input/oval/templates/template_package_removed	2017-01-23 13:06:37.878467344 +0100
@@ -5,21 +5,21 @@
     <metadata>
       <title>Package PKGNAME Removed</title>
       <affected family="unix">
-        <platform>Debian 8</platform>
+        <platform>Red Hat Enterprise Linux 6</platform>
       </affected>
-      <description>The DEB package PKGNAME should be removed.</description>
+      <description>The RPM package PKGNAME should be removed.</description>
     </metadata>
     <criteria>
       <criterion comment="package PKGNAME is removed"
       test_ref="test_package_PKGNAME_removed" />
     </criteria>
   </definition>
-  <linux:dpkginfo_test check="all" check_existence="none_exist"
+  <linux:rpminfo_test check="all" check_existence="none_exist"
   id="test_package_PKGNAME_removed" version="1"
   comment="package PKGNAME is removed">
     <linux:object object_ref="obj_package_PKGNAME_removed" />
-  </linux:dpkginfo_test>
-  <linux:dpkginfo_object id="obj_package_PKGNAME_removed" version="1">
+  </linux:rpminfo_test>
+  <linux:rpminfo_object id="obj_package_PKGNAME_removed" version="1">
     <linux:name>PKGNAME</linux:name>
-  </linux:dpkginfo_object>
+  </linux:rpminfo_object>
 </def-group>
```
For most of the templates, the differences are not so hard but the oval generation need to be updated with new variables (like PKGTYPE for example, to separate 'rpm' and 'dpkg' in the above file). I can't say right now if it can be done easily for all templates

More generally, I'm not sure to understand what you want to deploy as shared. The csv content or the generated output will be harder to share. pkg names vary beetween distributions, which make harder to support real shared csv content, even if templates can be.

**Comment by ybznek** [comment]
We have Fedora & RHEL5/RHEL6/RHEL7, they can share same templates.
Or e.g we have universal **package_command** - it could be used in shared template and be used by all distributions.
You can have shared files (e.g. for permission check of /etc/shadow),

**Comment by redhatrises** [comment]
@ybznek where do you plan on putting the `platform/` dir which contains the CPE dictionaries as well as `testoval.py`?

**Comment by ybznek** [comment]
@redhatrises 

- I think we should move **testoval.py** somewhere to shared directory and don't copy/paste it again and again. Maybe shared/utils ?

```
$ find . -name testoval.py -exec md5sum {} \; | sort
22610e932c7dc2e8d8722f6568ee6db3  ./Webmin/input/oval/testoval.py
756623cb3ff18150b99f1df4e34ffeff  ./shared/oval/testoval.py
c7561f1bdda6881b916170060920a6e9  ./JBoss/EAP/5/input/oval/testoval.py
c7561f1bdda6881b916170060920a6e9  ./JBoss/Fuse/6/input/oval/testoval.py
c7561f1bdda6881b916170060920a6e9  ./OpenStack/RHEL-OSP/7/input/oval/testoval.py
ca5d890b4192e2b2ac6b3f474bdfe87f  ./Chromium/input/oval/testoval.py
ca5d890b4192e2b2ac6b3f474bdfe87f  ./Fedora/input/oval/testoval.py
ca5d890b4192e2b2ac6b3f474bdfe87f  ./Firefox/input/oval/testoval.py
ca5d890b4192e2b2ac6b3f474bdfe87f  ./JRE/input/oval/testoval.py
ca5d890b4192e2b2ac6b3f474bdfe87f  ./WRLinux/input/oval/testoval.py
ce97bca010fdf515af40becd812f844c  ./Debian/8/input/oval/testoval.py
ce97bca010fdf515af40becd812f844c  ./RHEL/5/input/oval/testoval.py
ce97bca010fdf515af40becd812f844c  ./RHEL/6/input/oval/testoval.py
ce97bca010fdf515af40becd812f844c  ./RHEL/7/input/oval/testoval.py
ce97bca010fdf515af40becd812f844c  ./SUSE/11/input/oval/testoval.py
ce97bca010fdf515af40becd812f844c  ./Ubuntu/14.04/input/oval/testoval.py
ce97bca010fdf515af40becd812f844c  ./Ubuntu/16.04/input/oval/testoval.py
```
- Maybe it was wrong idea to plan to remove whole **input**. I will rather remove only **input/oval***
- Current plan is removing generated files and be able to generate them during build. Whole structure can be considered later.

@redhatrises If you have idea how create SSG directory structure, please share your opinion. I know that current temporary state is inconsistent and confusing. It is somewhere between old & new state. But old copy&paste way is not good for future. We are not able to see bugs in such many files.

**Comment by ybznek** [comment]
Here you can see duplicate files in repository https://github.com/OpenSCAP/scap-security-guide/issues/802#issuecomment-278172965
Templates are generated, so they contain some little change often.

**Comment by pthierry38** [comment]
@ybznek Ok. I didn't know the universal package_command, I'll look after that to see how to use it in the case of dpkg based templates.
For file permissions, if all distributions are FHS compliant -or enough for most of the checks-, you are right, we can share most of all the permission checks (both templates and csv).
I'll check which tree-view in the shared directory would be efficient to support all RH-and-derivatives / RPM-based (including SuSE ?) / all-Linux / Debian-and-derivatives - shared csv, as templates can use multi_platform_xxx
It would be great to find a simple & efficient way to share them

**Comment by ybznek** [comment]
OVALs in products like Firefox, Chromium, JRE,... weren't generated from templates, but they could be. But these files contains lot of comments, text descriptions, etc. And CSV required to store such values would be too complicated. So I have decided to not make templates for these files.

**Comment by redhatrises** [comment]
> - I think we should move **testoval.py** somewhere to shared directory and don't copy/paste it again and again. Maybe shared/utils ?

This file was designed to be copy/paste as it makes the testing of "static" OVAL file easier. So, it should move with the "static" OVAL files.

The `platform/` directory should move up a level as it currently exists in the `oval/` directory.

**Comment by ybznek** [comment]
What are our opinions about structure?
current is


```
- templates/
	-template file
	-template file
	- csv
		- csv file
		- oval_5.11
			- csv file
	- static
		- bash
			- not generated remediations
		- oval
			- not generated oval checks
```

Tips:
```
- input
	- templates/
		-template file
		-template file
		- csv
			- csv file
			- oval_5.11
				- csv file
	- bash
		- not generated remediations
	- oval
		- not generated oval checks
```

```
- input
	- templates_oval
		- csv file
		- template file
		- template file

	- templates_bash
		-template file
		-template file
		- csv file

	- templates_oval_5.11
		- template file
		- template file
		- csv file
	- bash
		- not generated remediations
	- oval
		- not generated oval checks
```

**Comment by mpreisler** [comment]
Personally I'd like to move to a structure where related xccdf, oval, bash, ansible and anaconda snippets are closely together, perhaps even in a folder. I feel like this would make it less likely they will go out of sync with each other. It would also help us separate a library of checks that are written in a universal way from products that pick from this library to form profiles. This is long term wishful thinking though.

I also suggest having OVAL 5.10 and 5.11 in the same file, separated with markup - can be XSLT markup using `xsl:if` or something like that. That will collapse one dimension of the structure and make things easier to follow. Most importantly it will get rid of the ambiguity of which OVAL will be used in the end.

**Comment by radzy** [comment]
@mpreisler : I would go one step further than having related templates for xccdf, oval, bash, etc in a directory.  I would prefer that the slice-and-dice be along related functionality throughout, not just in templates.  Having "everything" related to one area of functionality together would make it a lot easier to work with.  For example, audit_rules_privileged_commands_sudo might be shared/function/audit_rules_privileged_commands_sudo/{xccdf.xml,oval.xml,remediation.sh} and so on.

**Comment by rsprudencio** [comment]
What about a shared CPE-dict? Now we have some CPEs that are used across platforms, for detecting machine-only and container-only rules.

**Comment by ybznek** [comment]
@mpreisler 
> I also suggest having OVAL 5.10 and 5.11 in the same file, separated with markup - can be XSLT markup using xsl:if or something like that. That will collapse one dimension of the structure and make things easier to follow. Most importantly it will get rid of the ambiguity of which OVAL will be used in the end.

Maybe we could put everything into one file and have **no templates in product/ directories**. It would also help us to share between deb-based and rpm-based distributions, etc.
```
- shared
	- templates
		- package_installed
			- create.py
			- bash
			- oval
			- ansible

		- package_removed
			- create.py
			- bash
			- oval
			- ansible
```

Artificial example of **package_installed/bash** (for remediations, we would probably use oval-version = * everywhere):
```
########################################################################
# platform = multi_platform_rhel, multi_platform_fedora
# oval-version = *
package_command install PKGNAME

########################################################################
# platform = Debian8, Ubuntu16.04, Ubuntu16.10
# oval-version = *
apt-get install PKGNAME

########################################################################
# platform = Debian8
# oval-version = oval_5.11
magic_command install PKGNAME
```
(We could use xml format for that file, too). Last matching variant would be used . We could also add some build checks for duplicates in sections, ...

**Hierarchy**: (right: higher priority) `generated < shared static < product static`. If you want to use only generated files in your product (without shared static files), you can remove relevant `#platform` from shared static file.

@mpreisler @radzy Thank you for suggestions, I don't want to ignore them, but I need more explanation of them.

@mpreisler
Stupid question: We have bash generated from templates and one of product needs to have static bash file for that. How to deal with that?

@radzy 
Do you want to put a all variants of templates/static scripts (for all products) in one folder?

Or do you want to replicate same structure in product, to override it?
example:
```
shared/function/audit_rules_privileged_commands_sudo/{xccdf.xml,oval.xml,remediation.sh}
RHEL/7/function/audit_rules_privileged_commands_sudo/remediations.sh
```
I am a bit afraid, that this change is maybe too significant.

@rsprudencio 
I don't see "many" duplicates in cpe currently, but IMHO we definitely should reduce duplicates as much as possible. Copy&Paste is maybe fastest way at the beginning. But later it will probably cause horrible pain.

**Comment by redhatrises** [comment]
Closing as a lot of this work has been done.
