### ISSUE TITLE
Support Rsyslog queues in XCCDF and OVAL

### ISSUE THREAD

**Issue by cpellitt** [ComplianceAsCode/content#1690]
CCE-27343-3 Ensure Logs Sent To Remote Host fails if using the newer rsyslog syntax.

Example:
```
*.* action(type="omfwd"
      queue.type="linkedlist"
      queue.filename="example_fwd"
      action.resumeRetryCount="-1"
      queue.saveOnShutdown="on"
      target="example.com" port="6514" protocol="tcp"
     )
```

Example is provided from:
[https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/s1-working_with_queues_in_rsyslog.html#sec-Using_the_New_Syntax_for_rsyslog_queues](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/s1-working_with_queues_in_rsyslog.html#sec-Using_the_New_Syntax_for_rsyslog_queues)

**Comment by marcusburghardt** [comment]
RainerScript syntax is already supported in main rules.
