### ISSUE TITLE
Fedora 24/25 Vendor STIG Outdated/Missing.

### ISSUE THREAD

**Issue by linux-modder** [ComplianceAsCode/content#1695]
Been using RHEL/CentOS7 and Fedora 25 machines, looking at the xccdf files it appears that the Fedora Vendor STIG mentioned at Defense In Depth has yet to be  merged.

Is there a url to manually pull these in (with or without scap-workbench)?

**Comment by redhatrises** [comment]
@linux-modder can you provide any more information such as what specifically you are looking for as well as what was perhaps mentioned as part of Defense In Depth.

**Comment by shawndwells** [comment]
bump to @rprice @mpreisler (they presented at Defense in Depth)

**Comment by linux-modder** [comment]
@shawndwells  @rprice  remember the STIG table talk about mentioning the vendor stig and its blessing via DISA statement:

What do I use if there is no STIG?

Answer:
DISA FSO developed Security Requirement Guides (SRGs) to address technology areas. In the absence of a STIG, an SRG can be used to determine compliance with DoD policies. If there is no applicable SRG or STIG, industry or vendor recommended practices may be used. Examples include Center for Internet Security Benchmarks, Payment Card Industry requirements or the vendor's own security documentation.

The STIG in scap-workbench does not seem to reflect the same stig mentioned and talked about at DiD.

**Comment by redhatrises** [comment]
Closing. Fedora is not a certified or US Gov certified system, so it will most likely never have a STIG.
