### ISSUE TITLE
needs mapping/rule: SRG-OS-000375-GPOS-00160, SV-87059r2_rule, RHEL-07-041004 (multifactor auth)

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#1864]

**Comment by shawndwells** [comment]
Group id="V-72435"><title>SRG-OS-000375-GPOS-00160</title><description>&lt;GroupDescription&gt;&lt;/GroupDescription&gt;</description><Rule id="SV-87059r2_rule" severity="medium" weight="10.0"><version>RHEL-07-041004</version><title>The operating system must implement smart card logons for multifactor authentication for access to privileged accounts.</title><description>&lt;VulnDiscussion&gt;Using an authentication device, such as a CAC or token that is separate from the information system, ensures that even if the information system is compromised, that compromise will not affect credentials stored on the authentication device.^M
^M
Multifactor solutions that require devices separate from information systems gaining access include, for example, hardware tokens providing time-based or challenge-response authenticators and smart cards such as the U.S. Government Personal Identity Verification card and the DoD Common Access Card.^M
^M
A privileged account is defined as an information system account with authorizations of a privileged user.^M
^M
Remote access is access to DoD nonpublic information systems by an authorized user (or an information system) communicating through an external, non-organization-controlled network. Remote access methods include, for example, dial-up, broadband, and wireless.^M
^M
This requirement only applies to components where this is specific to the function of the device or has the concept of an organizational user (e.g., VPN, proxy capability). This does not apply to authentication for the purpose of configuring the device itself (management).^M
^M
Requires further clarification from NIST.^M
^M
Satisfies: SRG-OS-000375-GPOS-00160, SRG-OS-000375-GPOS-00161, SRG-OS-000375-GPOS-00162&lt;/VulnDiscussion&gt;&lt;FalsePositives&gt;&lt;/FalsePositives&gt;&lt;FalseNegatives&gt;&lt;/FalseNegatives&gt;&lt;Documentable&gt;false&lt;/Documentable&gt;&lt;Mitigations&gt;&lt;/Mitigations&gt;&lt;SeverityOverrideGuidance&gt;&lt;/SeverityOverrideGuidance&gt;&lt;PotentialImpacts&gt;&lt;/PotentialImpacts&gt;&lt;ThirdPartyTools&gt;&lt;/ThirdPartyTools&gt;&lt;MitigationControl&gt;&lt;/MitigationControl&gt;&lt;Responsibility&gt;&lt;/Responsibility&gt;&lt;IAControls&gt;&lt;/IAControls&gt;</description><reference><dc:title>DPMS Target Red Hat 7</dc:title><dc:publisher>DISA</dc:publisher><dc:type>DPMS Target</dc:type><dc:subject>Red Hat 7</dc:subject><dc:identifier>2777</dc:identifier></reference><ident system="http://iase.disa.mil/cci">CCI-001948</ident><ident system="http://iase.disa.mil/cci">CCI-001953</ident><ident system="http://iase.disa.mil/cci">CCI-001954</ident><fixtext fixref="F-78787r2_fix">Configure the operating system to implement smart card logon for multifactor authentication to uniquely identify privileged users.^M
^M
Enable smart card logons with the following commands:^M
^M
#authconfig --enablesmartcard --smartcardaction=1 --update^M
# authconfig --enablerequiresmartcard --update</fixtext><fix id="F-78787r2_fix" /><check system="C-72635r2_chk"><check-content-ref name="M" href="DPMS_XCCDF_Benchmark_RHEL_7_STIG.xml" /><check-content>Verify the operating system requires smart card logons for multifactor authentication to uniquely identify privileged users.^M
^M
Check to see if smartcard authentication is enforced on the system with the following command:^M
^M
# authconfig --test | grep -i smartcard^M
^M
The entry for use only smartcard for logon may be enabled, and the smartcard module and smartcard removal actions must not be blank.^M
^M
If smartcard authentication is disabled or the smartcard and smartcard removal actions are blank, this is a finding.</check-content></check></Rule></Group>

**Comment by trevor-vaughan** [comment]
This is a heck of a requirement for systems that don't have actual physical users.

**Comment by ggbecker** [comment]
Requirement has been removed from STIG in version v1r4 as it can be stated from: https://vaulted.io/library/disa-stigs-srgs/red_hat_enterprise_linux_7_security_technical_implementation_guide/V-72435?version=V1R1&compareto=V1r4

Closing since it's not required anymore.
