### ISSUE TITLE
[DISA] RHEL-07-010130: Rule title/check mismatch

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#1892]
DISA title:
``When passwords are changed or new passwords are established, the new password must contain at least one lower-case character.``

DISA check:
``Configure the operating system to lock an account for the maximum period when three unsuccessful logon attempts in 15 minutes are made. Modify the first three lines of the "auth" section of the "/etc/pam.d/system-auth-ac" and "/etc/pam.d/password-auth-ac" files to match the following lines: Note: RHEL 7.3 and later allows for a value of “never” for "unlock_time". This is an acceptable value but should be used with caution if availability is a concern. auth required pam_faillock.so preauth silent audit deny=3 even_deny_root fail_interval=900 unlock_time=604800 auth sufficient pam_unix.so try_first_pass auth [default=die] pam_faillock.so authfail audit deny=3 even_deny_root fail_interval=900 unlock_time=604800 and run the "authconfig" command.``

**Comment by salderma** [comment]
This has been opened with DISA's ticket system as well.  Also, the Title, Description, and Check Content fields are all matching in nature, it's the Fix Text / Remediation field that is incorrect.  I believe DISA has interpreted this mismatch the same way.

**Comment by shawndwells** [comment]
On 4/3/17 2:17 PM, salderma wrote:
> This has been opened with DISA's ticket system as well. Also, the
> Title, Description, and Check Content fields are all matching in
> nature, it's the Fix Text / Remediation field that is incorrect. I
> believe DISA has interpreted this mismatch the same way.

To help track w/DISA, any chacne you have a DISA ticket number?

This isn't to replace official DISA support channels. If we keep track
of things here, we can (1) ensure the matching OpenSCAP does not contain
the issues; (2) help the broader community track known issues with DISA
content.

Thanks!

**Comment by salderma** [comment]
STS-017072 is the ticket number I was given when I emailed about this control.

**Comment by jamescassell** [comment]
Fixed in V1R3: "Updated RHEL-07-010130 - Updated the fix text to match the requirement."

**Comment by redhatrises** [comment]
Fixed. Closing.
