### ISSUE TITLE
What SELinux booleans to include in base profiles?

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#1964]
There are ~304 SELinux booleans. What ones should we put into our base profiles, e.g. STIG and OSPP?

In the very near term, I think we should select rules that are part of the base OS (e.g. selinuxuser_*, unconfined_*, daemons_*, ... ) and desktop (xguest_*, xserver_*).  Get something in for the next SSG release.

After that we can expand the templating system (e.g. for httpd_* checks, add OVAL template to ensure httpd installed) for next SSG release.

Is that sane?

**Comment by shawndwells** [comment]
Initial PR of just system booleans: https://github.com/OpenSCAP/scap-security-guide/pull/1965

**Comment by redhatrises** [comment]
@shawndwells this doesn't appear to be much traction on this. Should we keep this open?

**Comment by trevor-vaughan** [comment]
@redhatrises If this is a discussion track, I would leave it open. Otherwise, no thoughts.

**Comment by redhatrises** [comment]
This has really gained no traction or discussion. Please re-open to start a discussion so that we can have actionable items.
