### ISSUE TITLE
Incorrect detection of unconfined services in RHEL 7

### ISSUE THREAD

**Issue by sshimko** [ComplianceAsCode/content#1989]
In RHEL 6 the assumption was made that anything running in initrc_t was an unconfined domain. In RHEL 7, anything labeled bin_t causes init_t to transition to unconfined_service_t. Hence, the old check is not sufficient for RHEL 7. 

Instead, it should check for both initrc_t and unconfined_service_t, as SysV scripts can still be present and will run in initrc_t, in addition to normal systemd units.

**Comment by marcusburghardt** [comment]
Please, reopen with more details if still relevant. Inform the relevant benchmark and rules.
