### ISSUE TITLE
file access checks do not take account of write access to parent directories

### ISSUE THREAD

**Issue by realname0000** [ComplianceAsCode/content#1992]
I have posted an article about use of oscap on Fedora 26: 
  http://www.zen19351.zen.co.uk/article_series/oscap_file_checks.html  
about the check  
Ensure that Root's Path Does Not Include World or Group-Writable Directories  
Rule ID accounts_root_path_dirs_no_write  

The same problem also affects  
Verify that System Executables Have Restrictive Permissions  
Rule ID file_permissions_binary_dirs  

The article links to demo code on github that shows how more comprehensive testing could be done.

**Comment by redhatrises** [comment]
Closing as there is no traction on this.
