### ISSUE TITLE
hardcoded auid range in audit_rules_*

### ISSUE THREAD

**Issue by hex2a** [ComplianceAsCode/content#2017]
In most `audit_rules_*` OVALs/XCCDFs the auid is hardcoded (`-F auid>=1000`), although `UID_MIN` / `UID_MAX` might be set to different values in `/etc/login.defs`

e.g.:
https://github.com/OpenSCAP/scap-security-guide/blob/73d97d4d2b6d151784b46185c193c92e0ad23b5b/shared/xccdf/system/auditing.xml#L1141

this was fixed for `no_shelllogin_for_systemaccounts` in #1298

**Comment by shawndwells** [comment]
In theory we could place the uid in a variable and compare against. Important, however other tickets need resolution for 0.1.39.

Assigning this 0.1.40 so it doesn't keep getting kicked down the road.

**Comment by yuumasato** [comment]
In `product.yaml` file it is possible to define a value for `UID_MIN` and `auid` values, see example in [rhel6/product.yml](https://github.com/OpenSCAP/scap-security-guide/blob/5fe43cdbf2df9a982db6ac2a18e1663a1bc7da39/rhel6/product.yml#L18). But this is a build time setting, not a value that is customizable.

**Comment by matejak** [comment]
Fix for this is not trivial or obvious, so I am postponing to 0.1.41

**Comment by marcusburghardt** [comment]
auid is currently defined by product parameters
