### ISSUE TITLE
DISA feels 60 day maximum password lifetime is not being enforced in OpenSCAP content (RHEL-07-010260)

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#2040]
DISA check test:

> Check whether the maximum time period for existing passwords is restricted to 60 days.
> awk -F: '$5 > 60 {print $1}' /etc/shadow
> If any results are returned that are not associated with a system account, this is a finding.

**Comment by shawndwells** [comment]
Technically this is true. SSG does not check max age of existing user accounts.

This rule should be dropped. In order for existing users to have passwords over 60 days, the system must have been explicitly configured out of compliance (which would be audited), the user would be created (also audited), and then the system placed back into compliance (again audited).

DISA should drop this rule.

**Comment by kresss** [comment]
@shawndwells what you said is not entirely true. Users that are created during system installation are created out of compliance. Enforcing compliance during the system install - as it stands today - is not a viable solution.

**Comment by tbrunell** [comment]
Spoke with DISA FSO.  The rule should stay.  Passwords of non-system user accounts need to be brought into compliance using the associated fix.  If the account cannot function with a password that needs to be changed, a letter can be submitted explaining what the account is used for.

**Comment by redhatrises** [comment]
Closing as this rule `accounts_password_set_max_life_existing` exists in the profile. Please re-open if you feel that it is not there.
