### ISSUE TITLE
DISA: SSG does not rate-limit via firewalld

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#2064]
> RHEL-07-040510
The operating system must protect against or limit the effects of Denial of Service (DoS) attacks by validating the operating system is implementing rate-limiting measures on impacted network interfaces.
----
> "DoS is a condition when a resource is not available for legitimate users. When this occurs, the organization either cannot accomplish its mission or must operate at degraded capacity. This requirement addresses the configuration of the operating system to mitigate the impact of DoS attacks that have occurred or are ongoing on system availability. For each system, known and potential DoS attacks must be identified and solutions for each type implemented. A variety of technologies exist to limit or, in some cases, eliminate the effects of DoS attacks (e.g., limiting processes or establishing memory partitions). Employing increased capacity and bandwidth, combined with service redundancy, may reduce the susceptibility to some DoS attacks."
----
> "Verify the operating system protects against or limits the effects of DoS attacks by ensuring the operating system is implementing rate-limiting measures on impacted network interfaces.
Check the firewall configuration with the following command:
Note: The command is to query rules for the public zone.
 firewall-cmd --direct --get-rule ipv4 filter IN_public_allow rule ipv4 filter IN_public_allow 0 -p tcp -m limit --limit 25/minute --limit-burst 100  -j ACCEPT
If a rule with both the limit and limit-burst arguments parameters does not exist, this is a finding."
----
> Create a direct firewall rule to protect against DoS attacks with the following command:
Note: The command is to add a rule to the public zone.
firewall-cmd --direct --add-rule ipv4 filter IN_public_allow 0 -p tcp -m limit --limit 25/minute --limit-burst 100  -j ACCEPT"
-----
> CCI-002385
The information system protects against or limits the effects of organization-defined types of denial of service attacks by employing organization-defined security safeguards.
NIST SP 800-53 Revision 4 :: SC-5

**Comment by shawndwells** [comment]
This rule has no value. This is an information system requirement that should not be expressed by rate limiting the operating system to 25 connections/sec.

@tbrunell - another "Drop from DISA content"

**Comment by tbrunell** [comment]
DISA is investigating this to determine if the rule is needed and how to best implement since the current check only checks the public zone and the rule could adversely effect system performance.

**Comment by tbrunell** [comment]
DISA investigating if https://access.redhat.com/solutions/2725481 is a good solution for protection from DoS attacks.

**Comment by shawndwells** [comment]
On 7/17/17 2:35 PM, tbrunell wrote:
>
> DISA investigating if https://access.redhat.com/solutions/2725481 is a
> good solution for protection from DoS attacks.
>

For very specific type of attacks, sure. Has nothing to do with this
ticket though.

**Comment by tbrunell** [comment]
Sure it does.  The control is about limiting the effectiveness of DoS attacks.  The solution in the STIG was to use firewalld, which is not necessarily a good fit.  The other solution, although just protecting from some attacks may be a better approach to solving the control requirement.  Dropping, as you proposed, does nothing to meet the requirement.

**Comment by redhatrises** [comment]
The rule `configure_firewalld_rate_limiting` exists in SSG and in the DISA profile. Closing
