### ISSUE TITLE
DISA: SSG does not check if logs offloaded via rsyslog

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#2068]
> Red Hat Missing

**Comment by shawndwells** [comment]
@tbrunell it's clear DISA did not even look at the content:

https://github.com/OpenSCAP/scap-security-guide/blob/master/RHEL/7/input/profiles/ospp-rhel7.xml#L150

**Comment by tbrunell** [comment]
@shawndwells The rule you referenced matches a rule in the STIG.  I think they are wondering about the "rsyslog_nolisten" rule.  There was no corresponding rule in the copy of the SSG content that they received in February.

**Comment by shawndwells** [comment]
Looks like DISA was using out of date content. They will be updating for TCP/UDP/RELP to align with rsyslog_nolisten

**Comment by tbrunell** [comment]
Rule exists with additional protocol options for rsyslog.  Will massage with DISA.

**Comment by redhatrises** [comment]
Closing as SSG already complies with this.
