### ISSUE TITLE
DISA: SSG does not check for shosts files

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#2069]
> Red Hat Missing (RHEL-07-040550)

**Comment by shawndwells** [comment]
yes we do:
https://github.com/OpenSCAP/scap-security-guide/blob/master/RHEL/7/input/profiles/ospp-rhel7.xml#L274

@tbrunell the game of DISA clearly not even reviewing the content prior to giving hundreds of lines of feedback is getting old. Have about 50 lines, out of 250+, left so will finish... but this needs to be the last time we do something like this for them. They either need to rebase against the DoD consensus content or GTFO.

**Comment by shawndwells** [comment]
(1) DISA should update check text to look inside users homedirs, not entire system
(2) RHT needs to update XCCDF to clearly state the rule checks shosts and rhosts

**Comment by shawndwells** [comment]
Also, service_rlogin_disabled ensures this service is disabled. Why bother checking for these files at all?

**Comment by trevor-vaughan** [comment]
What about `automounted` home directories. Need to skip anything digging in remote homedirs if using automount (or NFS/AFS/whatever).

**Comment by redhatrises** [comment]
Rule exists closing
