### ISSUE TITLE
TMOUT checks should be removed

### ISSUE THREAD

**Issue by kenglish-pfi** [ComplianceAsCode/content#2115]
TMOUT harkens from the era of the VT-100 terminal.  No other application suffers this ridiculous burden.  Email doesn't exit after 15 minutes of inactivity, your editor doesn't exit after 15 minutes of inactivity.  Why do we still apply this onerous requirement to the shell?  When was the last time you saw a terminal hooked directly into a server on a serial port?  I spend more time logging in to some systems than I do working on them because no one dares admit that this setting is no longer needed.  Stop the madness.  Just because this setting was a good idea in 1978 does not mean it is a good idea today.  Shell inactivity once meant that the user had walked away from their console while logged in.  It no longer means this.  My shell windows are protected by the same screen lock as my email application:  my locking screen saver.

**Comment by shawndwells** [comment]
bump to @tbrunell for his discussions w/DISA FSO

**Comment by konstruktoid** [comment]
"Shell inactivity once meant that the user had walked away from their console while logged in. "
... or forgot to exit that `root` shell. 

One reason for removing TMOUT is these guides (STIGS, CIS, ...) should start adapting to `systemd`.

**Comment by kresss** [comment]
I agree with the sentiment that this check should be removed. It does not work with today's workflows or the way that systems are used with modern GUIs. That aside, my biggest problem with this requirement is that it provides little to no real security functionality since it is easily overridden by unprivileged users.

**Comment by kenglish-pfi** [comment]
It is not easily overwritten by unprivileged users.  The environment variable is set as read-only in a system file that an unprivileged user cannot change.  The shells that an unprivileged user are allowed to choose from all respect this value.  (It wouldn't bother me nearly as much if it were easily overridden).  "Fixing" this requires debugging your own login shell and poking the memory address of the value checked by the branch condition.  Most production systems don't have gdb installed.

**Comment by kresss** [comment]
@kenglish-pfi I will take a look at my system when I get a chance later, but I am using running a STIG'ed RHEL 7 system. I know this is off topic, but thanks for the info. It could be some other misconfiguration on my part.

**Comment by kresss** [comment]
@kenglish-pfi ok I am missing something. Standard RHEL 7.3 build. I set TMOUT in /etc/profile per the STIG. As a normal user I login and I am able to change TMOUT in my shell and it is honored. The shell (bash) does not exit after 5 minutes. Are you saying this should work differently?

**Comment by kenglish-pfi** [comment]
The line
     export TMOUT=900
is usually followed by:
     readonly TMOUT
If you do not set readonly then yes, the user can change the value

**Comment by kenglish-pfi** [comment]
The earliest reference I can find via Google Books is:  Rebecca Thomas, Rik Farrow "UNIX Administration Guide for System V" Prentice Hall, 1989 

https://books.google.com/books?id=N9tQAAAAMAAJ&q=Unix+TMOUT&dq=Unix+TMOUT&hl=en&sa=X&ved=0ahUKEwi2kuvI2_LUAhUM2oMKHX8SAU04UBDoAQhJMAg

TMOUT Time until automatic logoff

**Comment by tbrunell** [comment]
Talked with DISA today.  They feel that the rule should stay, but with the addition of the "readonly TMOUT" line in /etc/profile.  

They are willing to look at a systemd approach if an efficient way of doing this can be found to replace TMOUT.

**Comment by kenglish-pfi** [comment]
Who did you talk to at DISA?

**Comment by shawndwells** [comment]
On 7/17/17 2:29 PM, tbrunell wrote:
> Talked with DISA today. They feel that the rule should stay, but with
> the addition of the "readonly TMOUT" line in /etc/profile.

Thanks for tracking all these with DISA, Ted!

**Comment by redhatrises** [comment]
Closing as DISA is keeping this rule.

**Comment by trevor-vaughan** [comment]
@shawndwells That's what we currently do but everything should really go into /etc/profile.d.

Also, `csh` can't set readonly variables so do we ban `csh` or what?

**Comment by trevor-vaughan** [comment]
@shawndwells Actually, I don't see how this replaces `TMOUT` at all according to https://www.freedesktop.org/software/systemd/man/logind.conf.html.

This seems to indicate that action that a system will take if *all* user sessions are idle. Not just booting someone off of a terminal if they're idle.

**Comment by shawndwells** [comment]
On 9/5/18 1:29 PM, Trevor Vaughan wrote:
>
> @shawndwells <https://github.com/shawndwells> Actually, I don't see 
> how this replaces |TMOUT| at all according to 
> https://www.freedesktop.org/software/systemd/man/logind.conf.html.
>
> This seems to indicate that action that a system will take if /all/ 
> user sessions are idle. Not just booting someone off of a terminal if 
> they're idle.
>

Looks like we both started RTFM'ing the freedesktop docs.... I saw that 
too =/
Lame.

**Comment by redhatrises** [comment]
Prefer a new one be opened for systemd stuff.

**Comment by trevor-vaughan** [comment]
@shawndwells As part of the `TMOUT` stuff, there really needs to be a tool to log all active sessions. I've seen a bunch of hack-arounds, but `TMOUT` is completely circumvented by such advanced techniques as using....`cat`.

**Comment by shawndwells** [comment]
On 9/5/18 2:34 PM, Trevor Vaughan wrote:
> @shawndwells <https://github.com/shawndwells> As part of the |TMOUT| 
> stuff, there really needs to be a tool to log all active sessions. 
> I've seen a bunch of hack-arounds, but |TMOUT| is completely 
> circumvented by such advanced techniques as using....|cat|.

Could you give TLog a try?
https://github.com/Scribery/tlog
https://github.com/Scribery/tlog

/me trolls

**Comment by trevor-vaughan** [comment]
Maybe....https://github.com/simp/pupmod-simp-tlog

**Comment by szycha76** [comment]
Readonly `$TMOUT` variable is particularly harmful in connection with programs such as `tmux` or `screen` when one wants to execute a command in a separate pane while working on something else in another pane or window.  Therefore I have put below a few ideas on
### How to circumvent read-only TMOUT, parts 1-5
1. `alias stay='date; while true; do echo -n .; sleep 1h; done'` - just type `stay` if you want your session to stay.
2. Or type `vim` instead - VIm is not affected by `$TMOUT`
3. In TMOUT-tainted environment, type `env - csh`; then `env - bash --norc --noprofile`; then carefully execute whatever needed from your `.bashrc` and/or `.bash_profile` files - you should get your working environment that won't disappear after several minutes.
4. `sleep 800h` should also do the trick.
5. The last one is your favourite, because it's all yours, since it has been left as an exercise to the reader.

Have fun.

**Comment by tblazejczyk-qblox** [comment]
I would agree. Enforcing `TMOUT` is the most stupid thing ever. Killing productivity for developers using terminals a lot and forcing them to use awkward workarounds There are lock screen mechanisms that will be active after N minutes anyway. Enforced by security profiles. SSH servers have own settings.  What is the point? I'm dealing with CIS2 RHEL 9 Workstation. I could understand that setting for servers but not for workstations. If a sane admin will read this comment, please do [How to set Timeout (TMOUT) for all users except few in Red Hat Enterprise Linux?](https://access.redhat.com/solutions/664483). Red Hat Insights and `openscap` will be happy and `TMOUT` check will pass.

**Comment by konstruktoid** [comment]
systemd 252 and later, the `TMOUT` setting are configured as: 

```ini
[Login]
KillUserProcesses=true
KillExcludeUsers=root user1 user2                                                                                                                                                                          IdleAction=lock
IdleActionSec=15min
RemoveIPC=true
StopIdleSessionSec=900
```

`KillExcludeUsers` can be use to exclude users as @tblazejczyk-qblox suggested.
