### ISSUE TITLE
RHEL7 - allow disabling IPv6 using /etc/default/grub

### ISSUE THREAD

**Issue by rybal06** [ComplianceAsCode/content#2126]
The Disable IPv6 checks are looking specifically for sysctl parameters to be configured to disable IPv6. On RHEL 7, the preferred method to do this is to change grub configuration to pass ipv6.disable=1. This disables ipv6 at a lower level that sysctl, and the sysctl parameters to configure ipv6 are not configurable when disabled at kernel boot time.
https://access.redhat.com/solutions/8709 (requires RH logon)

Sysctl options when disabled via grub bootloader (no results):
`# sysctl -p | grep -i ipv6'
 #
The preferred method is to add this option to /etc/default/grub:
`GRUB_CMDLINE_LINUX="ipv6.disable=1"`

The dss is already scanning for `GRUB_CMDLINE_LINUX="audit=1"`, it should check for ipv6 being disabled from that same file in an OR clause that also checks sysctl.

**Comment by redhatrises** [comment]
The preferred method is not disabling the IPv6 module in the kernel. This breaks a whole slew of networking services and functionality especially when you get into things like cloud services and advanced networking e.g. bonding, etc. hence DISA putting into the STIG to allow the IPv6 kernel module to load/unload but disable access and usage of IPv6 to all interfaces which is how it is currently set. What security guide produced by DSS is this rule listed in?

**Comment by rybal06** [comment]
You are correct- and it is not in a security guide produced by DSS that I am aware of.  I had just followed RedHat's guide which lists it as the first option, and this method avoids issues with postfix not starting. RedHat lists using sysctl as a secondary option on RHEL7.  I am not sure if a difference exists between disabling via modprobe and grub bootloader.

Is it practical to have the OVAL support checking for the grub method or the sysctl method instead of only sysctl?

**Comment by redhatrises** [comment]
It would be a separate XCCDF rule/OVAL check as the implications of disabling in grub vs sysctl are very different.

**Comment by linux-modder** [comment]
For those that have a need for ipv6, would such an xccdf / oval have a check for proper non auto-conf but still secure?

**Comment by bgjoseluis** [comment]
Hello all,


just to help.


Related to what @redhatrises said:

"This breaks a whole slew of networking services and functionality especially when you get into things like cloud services and advanced networking e.g. bonding, etc."

Please could you go in more detail about it, which services?.

And also, related to "functionality", it is about the dependency between modules bonding and ipv6? (https://bugzilla.redhat.com/show_bug.cgi?id=531873), if yes, in newer versions doesn't appears to happen (i've tried it on 6.9 and 7.4).

Anyway, in RHEL7 there is no ipv6 module it is built in kernel, so the remediation shouldn't be using sysctl -w and sysctl.conf (key --> net.ipv6.conf.all.disable_ipv6)?

Many thanks for your help and time.

JLBG

PS; please excuse me if i have not expressed correctly, english is not my natural language.

**Comment by yuumasato** [comment]
Hello,

regarding original issue of having a rule that checks for grub configuration `ipv6.disable=1`, there is a new rule `grub2_ipv6_disable_argument`.
Originally implemented in #5324 and fixed in #5547.

Without going into discussion of which is recommended or causes less problems, I'm closing this issue.
I think an opinionated choice can be made by the Profile, and individuals or organization can tailor if choice made doesn't suit them.
