### ISSUE TITLE
SSG updates for NIST 800-53 rev4?

### ISSUE THREAD

**Issue by lorengordon** [ComplianceAsCode/content#2135]
It appears that many of the control references in the ssg xml files are still specific to NIST 800-53 rev3. I'm having trouble figuring out or tracing out how the content is generated or maintained, so figured I'd just open an issue. Are there any plans to update the content to reflect NIST 800-53 rev4? How can I help?

For example, AC-19(d) is deprecated in rev4, but the results of a openscap scan still reference it. And yes, the url for the pdf is pointing to rev4, but that just seems to be causing some extra confusion among our assessors since the controls are no longer relevant.

**Comment by linux-modder** [comment]
+1 for helping, but let me know where I'd be best utilized.

**Comment by shawndwells** [comment]
There might not be an easy way to do this =/

The only way I can immediately think of is to manually go through all rules, one by one, and check if the mapping is still valid. Aka, the CCE->NIST mappings for USGCB:

http://people.redhat.com/swells/scap-security-guide/tables/table-rhel7-nistrefs-ospp-rhel7.html

**Comment by lorengordon** [comment]
Eef. Ok. So, where are the mappings in the repo? I'm really struggling to understand how things get from the repo structure to the distributed xml files (xccdf, cpe-*, ds, etc). I've also noticed NIST doing a nicer job providing [parseable formats](https://nvd.nist.gov/800-53), so maybe some of this can be automated...

**Comment by shawndwells** [comment]
On 7/11/17 7:42 AM, Loren Gordon wrote:
> Eef. Ok. So, where are the mappings in the repo? I'm really struggling
> to understand how things get from the repo structure to the
> distributed xml files (xccdf, cpe-*, ds, etc). I've also noticed NIST
> doing a nicer job providing parseable formats
> <https://nvd.nist.gov/800-53>, so maybe some of this can be automated...

They're scattered in the XCCDF through the use of ``ref`` tags. Example:
https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/xccdf/system/auditing.xml#L2129

``<ref nist="AU-12(c)" disa="172,2884"
ossrg="SRG-OS-000392-GPOS-00172,SRG-OS-000463-GPOS-00207,SRG-OS-000465-GPOS-00209"
cui="3.1.7" />``

If you guys are interested in updating the mappings, perhaps we can hop
on a webex next week? We can run through the "how" of updating mappings
and do a few together, to get you started. Figure out what the best
workflow might be.

**Comment by lorengordon** [comment]
@shawndwells Sure, would be great to chat about how to proceed. You can reach me at loren at plus3it.com

**Comment by linux-modder** [comment]
Count me in for a webex

**Comment by GaryGapinski** [comment]
I'd like to participate in any related webex and/or updates. I can prepare a list of existing references if that would be useful.

**Comment by linux-modder** [comment]
@GaryGapinski if you have the cycles to generate such a list I'd be game for looking at / working on.

**Comment by lorengordon** [comment]
I was kind of thinking it would be good to rename the existing tags to `nist-800-53.rev3`, and add a new tag `nist-800-53.rev4`. There's already work on rev5, so we know this isn't the last time this'll happen...

(Any ideas on how to automate some of this?)

**Comment by GaryGapinski** [comment]
@linux-modder I'll create a list of references with rule IDs and titles.
@lorengordon Separate hrefs (one for each SP 800-53 version) are a good idea. As references are sprinkled all over a large number of files, this might be easily done with <oXygen/> XML Editor (which can do a global replace on a large number of files) or some similar facility.

**Comment by GaryGapinski** [comment]
References attached. Input was RHEL7 XCCDF build from master branch.
[refs.zip](https://github.com/OpenSCAP/scap-security-guide/files/1155357/refs.zip)

The origins of these are found subordinate to ```shared/xccdf``` (there are 853 occurrences, many of which have no NIST citation, with 5 others in ```RHEL/7/input/auxiliary/nist_support.xml```). The "raw" citations reference only controls, not revision+control, so any cleanup accommodating multiple 800-53 revisions would require altering not only the ```<ref>```s but the build logic.

**Comment by shawndwells** [comment]
Made a quick Doodle poll to get everyones availability. Times in US EST.

https://doodle.com/poll/p4qedwknwieyv2nu

**Comment by pcactr** [comment]
I only just saw this mentioned on gov-sec -- I'm willing to assist with these updates too.

**Comment by jan-cerny** [comment]
Hi @shawndwells @lorengordon Can this be closed?

**Comment by lorengordon** [comment]
I'm unaware whether any work has been on the issue. I believe it is still an issue.

**Comment by shawndwells** [comment]
On 4/18/19 5:53 AM, Loren Gordon wrote:
> I'm unaware whether any work has been on the issue. I believe it is 
> still an issue.



Still outstanding, and rev5 is (apparently) right around the corner too.

**Comment by jan-cerny** [comment]
@lorengordon @shawndwells Thank you for clarification.

**Comment by shawndwells** [comment]
Have been meaning to close this long-standing ticket out! @redhatrises led a hackathon to remap all of the RHEL and CoreOS rules. Updated existing mappings, removed old (rev3) ones. Should be good now!
