### ISSUE TITLE
Fixes applies but oval check fails

### ISSUE THREAD

**Issue by MollyJoBault** [ComplianceAsCode/content#2195]
I've been doing some testing today.  I have some errors that seem to be similar so I figured I would make tickets for the ones I didn't know how to fix.

The below rules say the fix was applied successfully.  If I look in the filesystem, it looks like the fix was applied successfully but oval check says it failed.  Are these incomplete or is the oval check broken?

```
	xccdf_org.ssgproject.content_rule_aide_use_fips_hashes - fix applied, oval check fails - NA for CentOS 7.3 since it isn't a cerified FIP system
	xccdf_org.ssgproject.content_rule_mount_option_tmp_nodev - fix applied, oval check fails
	xccdf_org.ssgproject.content_rule_mount_option_tmp_noexec - fix applied, oval check fails 
	xccdf_org.ssgproject.content_rule_mount_option_tmp_nosuid - fix applied, oval check fails
	xccdf_org.ssgproject.content_rule_mount_option_var_tmp_bind - fix applied, oval check fails
	xccdf_org.ssgproject.content_rule_file_permissions_etc_shadow - fix applied, oval check fails
	xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands - fix applied, oval check fails (format different than description, does this matter?)
	xccdf_org.ssgproject.content_rule_audit_rules_kernel_module_loading_init - fix applied, oval check fails (format different than description)
	xccdf_org.ssgproject.content_rule_audit_rules_kernel_module_loading_delete - fix applied, oval check fails (format different than description)
	xccdf_org.ssgproject.content_rule_umask_for_daemons - fix applied, oval check fails
```

**Comment by redhatrises** [comment]
Can you provide more information such as the fstab and mtab file and what the actual audit fixes were? I am also assuming that this is the latest off of the master?

**Comment by MollyJoBault** [comment]
You are correct, this is the latest off of the master.  

In fstab, 

- nodev, noexec, nosuid are applied to the tmp dir.  
- /var/tmp and /tmp are bind'ed. 

[fstab.txt](https://github.com/OpenSCAP/scap-security-guide/files/1191263/fstab.txt)
[mounts.txt](https://github.com/OpenSCAP/scap-security-guide/files/1191266/mounts.txt)

[root@devgobah-1112 openscap_data]# ls -al /etc/shadow
----------. 1 root root 948 Jul 31 11:03 /etc/shadow

**Comment by redhatrises** [comment]
You don't happen to have the scan results that you can share do you?

**Comment by MollyJoBault** [comment]
Scan results.
[openscap_data.zip](https://github.com/OpenSCAP/scap-security-guide/files/1191309/openscap_data.zip)

**Comment by laserfox** [comment]
Hello,

I have ran into similar problems:

xccdf_org.ssgproject.content_rule_audit_rules_file_deletion_events - fix applied, oval check fails
xccdf_org.ssgproject.content_rule_audit_rules_kernel_module_loading - fix applied, oval check fails
xccdf_org.ssgproject.content_rule_audit_rules_networkconfig_modification - fix applied, oval check fails
xccdf_org.ssgproject.content_rule_audit_rules_media_export - fix applied, oval check fails

Let me know if you need anything

**Comment by redhatrises** [comment]
@laserfox how did you apply the fix?

**Comment by redhatrises** [comment]
@MollyJoBault @laserfox can either one test this with the latest release?

**Comment by MollyJoBault** [comment]
@redhatrises I won't be able to test this.

**Comment by laserfox** [comment]
Hi RedHatRises,

Most of the rules pass now. Having trouble with:

xccdf_org.ssgproject.content_rule_audit_rules_login_events

This is failing for some unknown reason, despite having the required remediation in place.

details:

cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.5 (Maipo)
rpm -qf /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
scap-security-guide-0.1.36-9.el7_5.noarch

for i in $(echo tallylog faillock lastlog); do grep $i /etc/audit/audit.rules; done
-w /var/log/tallylog -p wa -k logins
-w /var/run/faillock/ -p wa -k logins
-w /var/log/lastlog -p wa -k logins

Regards

Jamie

**Comment by yuumasato** [comment]
@laserfox Hello, thanks for testing these rules

> -w /var/run/faillock/ -p wa -k logins

Can you try removing the trailing slash in path so that it is like this `/var/run/faillock`?
Audit functionality will remain the same, and the check should pass.

**Comment by marcusburghardt** [comment]
This issue can no longer be reproduced. Since this is an old issue, probably it was already fixed this meantime.
