### ISSUE TITLE
audit_rules_privileged_commands broken up?

### ISSUE THREAD

**Issue by MollyJoBault** [ComplianceAsCode/content#2255]
I'm a bit confused.  Is the first a super-set of the second?  Is there a plan to drop the first?  

Right now the audit for content_rule_audit_rules_privileged_commands is failing.  The others seem to be working.

Right now there is:
`content_rule_audit_rules_privileged_commands`
and
```
content_rule_audit_rules_privileged_commands_chage
content_rule_audit_rules_privileged_commands_chsh
content_rule_audit_rules_privileged_commands_crontab
content_rule_audit_rules_privileged_commands_gpasswd
content_rule_audit_rules_privileged_commands_newgrp
content_rule_audit_rules_privileged_commands_pam_timestamp_check
content_rule_audit_rules_privileged_commands_passwd
content_rule_audit_rules_privileged_commands_postdrop
content_rule_audit_rules_privileged_commands_postqueue
content_rule_audit_rules_privileged_commands_pt_chown
content_rule_audit_rules_privileged_commands_ssh_keysign
content_rule_audit_rules_privileged_commands_su
content_rule_audit_rules_privileged_commands_sudo
content_rule_audit_rules_privileged_commands_sudoedit
content_rule_audit_rules_privileged_commands_umount
content_rule_audit_rules_privileged_commands_unix_chkpwd
content_rule_audit_rules_privileged_commands_userhelper
```
With the STIG roll-out logic, both of these are being enabled for the STIG profiles.  Is the plan to get rid of the first or are they really doing separate pieces of logic?

**Comment by redhatrises** [comment]
`audit_rules_privileged_commands` is for `el6` as well as any profile that does not specifically break out the audit rules as the STIG does.

**Comment by mpreisler** [comment]
We have had this question raised in the community at least twice. I think we need an XML comment in the XCCDF code.

**Comment by MollyJoBault** [comment]
To replay this back, the RHEL7 STIGs call out both the broken out and non-broken out privileged audit rules?  I think I might be still confused. :)

**Comment by redhatrises** [comment]
> To replay this back, the RHEL7 STIGs call out both the broken out and non-broken out privileged audit rules? I think I might be still confused. :)

@MollyJoBault you are correct. The RHEL7 STIG calls out both. `RHEL-07-030360` contains the non-broken out privileged audit rules.

**Comment by MollyJoBault** [comment]
content_rule_audit_rules_privileged_commands check is not passing currently.  I've looked at the oval source and I'm unsure why it is failing.
[checkdevel-audit_rules_privileged_commands.txt](https://github.com/OpenSCAP/scap-security-guide/files/1229067/checkdevel-audit_rules_privileged_commands.txt)

**Comment by redhatrises** [comment]
Do you have auditing configured for each of the following records?
````
'subexpression'='/usr/sbin/netreport'
'subexpression'='/usr/libexec/utempter/utempter'
'subexpression'='/usr/lib/polkit-1/polkit-agent-helper-1'
'subexpression'='/usr/sbin/usernetctl'
'subexpression'='/usr/bin/screen'
'subexpression'='/usr/bin/mount'
'subexpression'='/usr/bin/pkexec'
'subexpression'='/usr/bin/write'
'subexpression'='/usr/bin/pmount'
'subexpression'='/usr/bin/wall'
'subexpression'='/usr/bin/ssh-agent'
'subexpression'='/usr/bin/pumount'
'subexpression'='/usr/bin/ksu'
'subexpression'='/usr/bin/cgclassify'
'subexpression'='/usr/bin/cgexec'
'subexpression'='/usr/bin/chfn'
'subexpression'='/usr/lib64/dbus-1/dbus-daemon-launch-helper'
````

**Comment by redhatrises** [comment]
@MollyJoBault adding `--oval-results` can be your friend.

**Comment by MollyJoBault** [comment]
@redhatrises 

I do indeed have all of those records ... in fact ... I have **5** of each!  I know, over achiever!

```
[root@devgobah-1112 rules.d]# pwd
/etc/audit/rules.d
[root@devgobah-1112 rules.d]# grep pumount *
privileged.rules:-a always,exit -F path=/usr/bin/pumount -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged
privileged.rules:-a always,exit -F path=/usr/bin/pumount -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged
privileged.rules:-a always,exit -F path=/usr/bin/pumount -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged
privileged.rules:-a always,exit -F path=/usr/bin/pumount -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged
privileged.rules:-a always,exit -F path=/usr/bin/pumount -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged

```

**Comment by yuumasato** [comment]
@MollyJoBault Hello

The failing test is `test_arpc_bin_count_equals_rules_count_augenrules`, which ultimately compares the two following variables:
- `variable_count_of_suid_sgid_binaries_on_system` whose value is 51;
- `variable_count_of_privileged_commands_having_audit_definition_augenrules` whose value is 17;

The number of binaries found differ from the number of rules found in `/etc/auditd/rules.d/*.rules`

In the attached txt are the 51 binaries found in the system with `setuid` or `setgid` set.
[object_system_privileged_commands.txt](https://github.com/OpenSCAP/scap-security-guide/files/1812650/object_system_privileged_commands.txt)

**Comment by shawndwells** [comment]
will try and address for 0.1.39 release

assigning to self.

**Comment by jamescassell** [comment]
I'm also running into the issue of content_rule_audit_rules_privileged_commands failing on rhel6 the counts mismatch.

**Comment by redhatrises** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1430633 for this issue. Right now, `object_system_privileged_commands` is what is throwing an error in the OVAL and causing the issue or one of the issues.

**Comment by redhatrises** [comment]
This issue appears to be fixed. Please reopen if you notice the same behaviors.
