### ISSUE TITLE
aide initialize needs to be the last rule executed

### ISSUE THREAD

**Issue by MollyJoBault** [ComplianceAsCode/content#2299]
The order of aide remediations is incorrect - the remediation running  aide initialize is executed before some other aide remediations.  Any changes after the initialize is run will and are flagged as an aide check failures.

**Comment by shawndwells** [comment]
On 9/6/17 3:12 PM, MollyJoBault wrote:
> Right now the aide initialize is run in the middle of the remediation.
> Any changes after the initialize is run will be flagged as an aide
> check failures.

Would moving the rule selector to the very bottom of the profile handle
this?

**Comment by yuumasato** [comment]
AFAIK what determines the order of evaluation is determined by order of Rules in Benchmark, the selectors in Profiles do no affect this.
So, probably solution would be to move `shared/xccdf/system/software/integrity.xml` down in `shared/xccdf/shared_guide.xslt`.

**Comment by dahaic** [comment]
I would prefer to have some more formal mechanism (at least in the build system) for this. It's the same as with installation of packages, it would be better to be explicit, instead of moving snippets of code and leaving comment notices.

**Comment by marcusburghardt** [comment]
Centralized in https://github.com/ComplianceAsCode/content/issues/2556
