### ISSUE TITLE
Update Ubuntu 16.04 with Final DISA STIG Ver1 Rel1

### ISSUE THREAD

**Issue by ajd394** [ComplianceAsCode/content#2349]
DISA Risk Management Executive has released the Canonical Ubuntu 16.04 Security Technical Implementation Guide (STIG) Version 1 Release 1. The requirements of the STIG become effective immediately. The STIG is available on IASE at https://iase.disa.mil/stigs/os/unix-linux/Pages/index.aspx.

**Comment by TomaszDom** [comment]
[U_Canonical_Ubuntu_V1R1_STIG.zip](https://github.com/OpenSCAP/scap-security-guide/files/1343540/U_Canonical_Ubuntu_V1R1_STIG.zip)

It disappeared from the official website (https://iasecontent.disa.mil/stigs/zip/U_Canonical_Ubuntu_V1R1_STIG.zip)

**Comment by ajd394** [comment]
I asked DISA why it disappeared and here is their response:

> Good afternoon,
> 
> There was an error in the STIG and our management decided to pull the STIG. It's being updated and will be reposted ASAP.
> 
> Brian R. Snodgrass
> IT Specialist (INFOSEC)
> DISA Risk Management Executive
> RE11 Cyber Standards Branch
> Commercial (717) 267-9162
> DSN 312-570-9162
> brian.r.snodgrass2.civ@mail.mil (NIPR)
> brian.r.snodgrass2.civ@mail.smil.mil (SIPR)

**Comment by GlennBell** [comment]
I started running through the STIG posted above.  There are several errors, the most notable is requiring running the command 'passwd -d root' (V-75445). This deletes root's passwd, i.e. no password required to login, quite the opposite of what was intended.
I'm not sure how this was published in the first place, that is a huge error.

**Comment by compuguy** [comment]
@ajd394 Any updates on this?

**Comment by GlennBell** [comment]
The updated Ubuntu STIG has not been re- released (See https://iase.disa.mil/stigs/os/unix-linux/Pages/index.aspx).

Another issue I discovered, per Canonical, the required FIPS 140-2 packages are only available though a commercial support contract. Contracts start at $2000.

**Comment by wmesser** [comment]
The Ubuntu STIG has been re-issued.

**Comment by redhatrises** [comment]
If anyone wants to contribute this content, that would be great!

**Comment by shaharglazner** [comment]
@redhatrises 
Hey,
I want to generate the stig_overlay.xml for Ubuntu 16.04 using [the documentation](https://github.com/ComplianceAsCode/content/blob/master/docs/manual/developer_guide.adoc#5-updating-reference-and-overlay-content), does it make sense?

Any other things to notice before?

**Comment by dodys** [comment]
This issue has been inactive since 2019 and Ubuntu 16.04 is in ESM since 2021, which make me believe that people moved to newer releases. Therefore I'm closing it.
