### ISSUE TITLE
Common Criteria references and information should be cross-linked and explained

### ISSUE THREAD

**Issue by trevor-vaughan** [ComplianceAsCode/content#2461]
#### Description of problem:

This stems from the STIG requirement for `screen` for virtual terminal locking per [this mailing list discussion](https://lists.fedorahosted.org/archives/list/scap-security-guide@lists.fedorahosted.org/thread/NKLI3G6WERYRCTMIXSKWFO4N7IEGT2WR/). Basically, if there is a reason that one technology is chosen over another, then there should be an actionable cross-reference between the two policies.

Additionally, any additional configuration information from the other standard (in this case the Common Criteria Protection Profile) should be inherited by the referencing standard for a complete configuration solution.

**Comment by redhatrises** [comment]
Closing. Screen is no longer being used going forward. Also, we know have references to the OSPP profiles starting with OSPP 4.2
