### ISSUE TITLE
Multiple Problems When Using tmpfs for /tmp

### ISSUE THREAD

**Issue by ferricoxide** [ComplianceAsCode/content#2475]
#### Description of problem:

Our security rules require the use of `/tmp`-intensive utilities like A/V tools. As a result, we implement `/tmp` as a tmpfs pseudofilesystem in all of our builds to curtail the massive bog-down resultant of meeting the A/V mandate. Unfortunately, the SCAP content is not written to gracefully handle these problems

#### SCAP Security Guide Version:

0.1.34 (appears to be similar in newer releases)

#### Operating System Version:

* Red Hat (and CentOS) 7.4.1708

#### Steps to Reproduce:

1. Launch an instance with 7.4.1708 with latest patch-sets and `/tmp` as tmpfs
2. Run scap-scan/remediate
3. Parse results and note failures
4. Validate system and note further oddities

#### Actual Results:

- `/var/tmp` is a bind-mount of `/tmp` - this breaks applications expecting cross-boot data-persistence for `/var/tmp`
- Options for `/tmp`, while present, are a _side effect_ of having set them on `/var/tmp` rather than directly on `/tmp`

#### Expected Results:

- All tests related to `/tmp` and `/var/tmp` pass (for the right reasons)
- `/var/tmp` is _not_ a bind-mount of `/tmp`

#### Addition Information/Debugging Steps:

- When using tmpfs for `/tmp`, mount-options should be specified within the associated systemd unit-files:
    - Modifying the unit files in `/usr/lib/systemd` is a non-starter, as this will cause the RPM validation against the owning RPM to fail
    - Not sure if systemd will honor `/etc/systemd` overrides for mounts, though.
- Similarly, when scanning for `/tmp` being on its own filesystem, lack of a `/tmp` line within `/etc/fstab` should not result in failures
- There should be no bind-mount line for `/var/tmp` in /etc/fstab

**Comment by redhatrises** [comment]
@ferricoxide can you please provide the profile that you are using? If you are using the STIG profile, you will probably have to open a ticket with DISA on this issue.

**Comment by ferricoxide** [comment]
Oofda... 80% of the time I've sent emails to the address listed on the IASE site I've gotten back zero respons. :neutral_face: : 

@shawndwells : Ideas?

**Comment by jan-cerny** [comment]
We have rule `mount_option_var_tmp_bind` that requests that 

```
  8     The <tt>/var/tmp</tt> directory is a world-writable directory. Bind-mount
  9     it to <tt>/tmp</tt> in order to consolidate temporary storage into one
 10     location protected by the same techniques as <tt>/tmp</tt>. 
```
So we would probably need to add the opposite rule.

**Comment by marcusburghardt** [comment]
Currently, there are equivalent rules for `/tmp` and `/var/tmp` and they are included in main profiles.
