### ISSUE TITLE
Bash Remediations

### ISSUE THREAD

**Issue by cpellitt** [ComplianceAsCode/content#2494]
I have a large collection of bash scripts that were created to be used with the SSG Disa STIG profile. Some scripts were modified from what is currently is in the SSG, and others are entirely new. I am uploading all of them, in case any are helpful for further SSG development.

[bash_fixes.tar.gz](https://github.com/OpenSCAP/scap-security-guide/files/1563311/bash_fixes.tar.gz)

All the scripts use SSG rule names, and work without modification if copied into the appropriate fix directories.

**Comment by jan-cerny** [comment]
@cpellitt thank you very much. Could you please make a pull request instead?

**Comment by cpellitt** [comment]
I have never done a pull request before, so I am not familiar with process. I submitted one as a test:
https://github.com/ComplianceAsCode/content/pull/4291

If that works out, I might be able to do some more, but I don't have a lot of time to work on this.

I maintain my own bash scripts, but I do have a few things I do differently, which I am not sure how well would merge.

I create a backup of every file that is modified. None of the existing scripts do that, so I am not sure if it is a welcome change.

I add comments to configuration files with the matching STIG ID. Some of the existing scripts use the CCE ID, which makes sense because it is not specific to a certain profile, but I still prefer the STIG ID for my own purposes. There might be a way to substitute the ID based on the profile used, but this seems like a non-trivial task.

**Comment by ggbecker** [comment]
I don't see any open discussions here since #4291 has been fully addressed and the original topic has been addressed in #2538. Closing it. Feel free to reopen if needed.
