### ISSUE TITLE
fix for xccdf_org.ssgproject.content_rule_set_firewalld_default_zone missing with no explanation

### ISSUE THREAD

**Issue by ghost** [ComplianceAsCode/content#2516]
#### Description of problem:
Generating the bash fix for set_firewalld_default_zone results in the following fix:
`# FIX FOR THIS RULE IS MISSING`

#### SCAP Security Guide Version:
0.1.36-1.el7.centos

#### Operating System Version:
CentOS Linux release 7.4.1708 (Core)

#### Steps to Reproduce:

1. Generate bash fixes for NIST 800-171

#### Actual Results:
```
###############################################################################
# BEGIN fix (215 / 359) for 'xccdf_org.ssgproject.content_rule_set_firewalld_default_zone'
###############################################################################
(>&2 echo "Remediating rule 215/359: 'xccdf_org.ssgproject.content_rule_set_firewalld_default_zone'")
# FIX FOR THIS RULE IS MISSING
# END fix for 'xccdf_org.ssgproject.content_rule_set_firewalld_default_zone'
```

#### Expected Results:
```
firewall-cmd --set-default-zone=drop

firewall-cmd --permanent --zone=drop --add-service=ssh

```

#### Addition Information/Debugging Steps:
This fix existed in a previous version of the scap-security-guide.  Usually when a fix is not enabled, there is a comment in the html results listing why.  For example, some missing fixes reference an outstanding RHEL bug (like the fix for enabling repo metadata gpg check).

Since scanning a system will list this as a fail, there should be an explanation as to why there is no fix currently available.

**Comment by yuumasato** [comment]
You are right, we should add some information on why the remediation went missing, but I'm not sure if adding a warning to XCCDF Rule is best option.

As quick explanation, remediation was dropped because it was locking down systems after remediation. For more info check #2202 and #2328.

**Comment by marcusburghardt** [comment]
There is already updated and includes a warning message about the automated remediation: https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/network/network-firewalld/ruleset_modifications/set_firewalld_default_zone/rule.yml
