### ISSUE TITLE
Dependent rules to be selected together for successful remediation

### ISSUE THREAD

**Issue by dahaic** [ComplianceAsCode/content#2556]
#### Description of problem:
Some rules are dependent on different rule to be passing, for example installation of AIDE is necessary for other AIDE checks to remediate correctly. https://bugzilla.redhat.com/show_bug.cgi?id=1465681

It would be great to have PR gating check, that would find such dependencies and check for them.

#### SCAP Security Guide Version:
0.1.36

**Comment by jan-cerny** [comment]
Hi @dahaic, thanks for reporting this problem. We currently do not define the rule order which would be  necessary to run the remediation for the rule package_aide_installed before other AIDE remediations. I suggest changing the title of this issue to "Implement rule ordering relation". And I suggest creating a new separate ticket to track the upstream test coverage of https://bugzilla.redhat.com/show_bug.cgi?id=1465681

**Comment by marcusburghardt** [comment]
Related to a OpenSCAP issue: https://github.com/OpenSCAP/openscap/issues/1880
