### ISSUE TITLE
rhel 7.5 beta: set_firewalld_default_zone still fails after remediation

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#2578]
#### Steps to Reproduce:

1.
2.
3.
4.

**Comment by redhatrises** [comment]
https://github.com/OpenSCAP/oscap-anaconda-addon/pull/64 will help address this issue.

**Comment by yuumasato** [comment]
This is not a blocker for release.

**Comment by matejak** [comment]
Do we even have a remediation for this? I took a quick look and couldn't find one.

**Comment by yuumasato** [comment]
There was remediation for `set_firewalld_default_zone`, see https://github.com/OpenSCAP/scap-security-guide/pull/2328 for reason why it was dropped.

**Comment by matejak** [comment]
I am closing the issue - as there is no remediation any more, the issue lost it's substance.
