### ISSUE TITLE
rhel 7.5 beta: firewalld_sshd_port_enabled still fails after remediation

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#2586]

**Comment by nzwulfin** [comment]
This looks to be an issue with the XPATH expression in the OVAL check.

Using an online XPATH tool and a default public.xml zone file, the check in the OVAL below fails with No Match
  <ns3:xpath>/service/service[@name='ssh']</ns3:xpath>

Changing the XPATH to /zone/service[@name='ssh'] (services direct children of the zone) results in:
Element='<service name="ssh"/>'

Changing the XPATH to //service[@name='ssh'] (any service with a name of ssh) results in:
Element='<service name="ssh"/>'

Which is more correct for the intent of the check? I'm not really an XML expert or in firewalld zone files.  With some guidance I could build a local test / PR.

**Comment by redhatrises** [comment]
https://github.com/OpenSCAP/oscap-anaconda-addon/pull/64 will help address this issue.

**Comment by yuumasato** [comment]
This is not a blocker for release.

**Comment by matejak** [comment]
Remediation has been dropped as part of #2328. Therefore, I am closing this issue, as failing when there is no remediation is expected.
