### ISSUE TITLE
RFE Generate an "all-included" profile in each product

### ISSUE THREAD

**Issue by mpreisler** [ComplianceAsCode/content#2601]
#### Description of problem:
Right now SSG has multiple profiles for each product with the default profile having no rules. If I want to search through the "library" of all available rules I can't really do it unless I tailor and select all rules. The alternative is to use the search function in SCAP Workbench. It would be great to have a "all" profile that has all rules, if only for the HTML guide that can be searched through when creating new profiles.

**Comment by matejak** [comment]
This is a valid point, but a HTML document is clumsy - it would contain hundreds of rules, and you would only have fulltext search to find what you want. This is not scalable.
By the way, searching YAML files using grep etc. also doesn't have to work - YAML doesn't work well with those line-based tools.
As the rule count grows, one would probably want to filter rules according to some criteria, and then search the title/description/rationale texts. In other words, it looks like that new functionality has to be developed.

**Comment by jan-cerny** [comment]
@matejak This functionality is present in the HTML report so it can be reused in the guide
