### ISSUE TITLE
Composition of Bash remediations is difficult to use

### ISSUE THREAD

**Issue by matejak** [ComplianceAsCode/content#2640]
Bash remediations are generated from templates (e.g. files in `shared/fixes/bash` directory). If those templates happen to use some shared functionality, the remediation will contain their definitions.

So far so good, but as noted in #2629, user doesn't have sufficient means of control over how the expansion happens and workarounds have to be used in order to trigger the expansion at the top of the file and prevent it later.

The build system should allow some degree of control over it, so identifying duplicated code and sharing it across multiple remediations is easy.

**Comment by Mab879** [comment]
Templates and Jinja should this closing.
