### ISSUE TITLE
Allow specifying rsyslog package name

### ISSUE THREAD

**Issue by jokajak** [ComplianceAsCode/content#2642]
#### Description of problem:
We use rsyslog7 on RHEL6 which means the shared package_rsyslog_installed check fails. It would be nice if the package name were a variable that could be customized.

#### SCAP Security Guide Version:
0.1.28
xccdf_org.ssgproject.content_profile_stig-rhel6-server-upstream

#### Operating System Version:
scap-security-guide-0.1.28-3.el6.noarch

#### Steps to Reproduce:

1. Install RHEL6
2. Install rsyslog7 using yum shell (See https://access.redhat.com/solutions/1260253 for more details)
3. Set package_rsyslog_name variable to rsyslog7
4. Perform SCAP check

#### Actual Results:
package_rsyslog_installed fails

#### Expected Results:
Set package_rsyslog_name variable to rsyslog7
package_rsyslog_installed passes

**Comment by ggbecker** [comment]
https://github.com/ComplianceAsCode/content/pull/6142 updates the package name to use `rsyslog7` instead since it's the latest available version in RHEL6
