### ISSUE TITLE
add pam_mkhomedir ?

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#2718]
consider updating https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/guide/system/accounts/accounts-session/file_ownership_home_directories.rule#L27 with https://linux.die.net/man/8/pam_mkhomedir

**Comment by shawndwells** [comment]
also https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/guide/system/accounts/accounts-session/file_permissions_home_directories.rule

**Comment by jamescassell** [comment]
Would be nice to have.  If I remember correctly, it didn't work correctly with RHEL 6 due to SELinux issues.

**Comment by jamescassell** [comment]
from the RHEL 7.5 release notes:

> Note that even after applying this update, SELinux might still prevent pam_mkhomedir from creating the home directory, which is the expected SELinux behavior. To ensure pam_mkhomedir is allowed to create the home directory, modify the SELinux policy using a custom SELinux module, which enables the required paths to be created with the correct SELinux context. (BZ#1509338)

**Comment by jamescassell** [comment]
I've opened a ticket with Red Hat: https://access.redhat.com/support/cases/#/case/02091031

**Comment by redhatrises** [comment]
So... this is a nice idea, but how well does this work with CIFS and NFS?

**Comment by marcusburghardt** [comment]
`pam_oddjob_mkhomedir` is a better option than `pam_mkhomedir.so` and the current documentation and tools (like authselect) already use it. I am closing this outdated issue.
