### ISSUE TITLE
failure: Require Client SMB Packet Signing, if using mount.cifs

### ISSUE THREAD

**Issue by jamescassell** [ComplianceAsCode/content#2752]
#### Description of problem:
Check CCE-26792-2 fails if samba-common is not installed.

#### SCAP Security Guide Version:
0.1.38, stig-rhel6-disa profile

#### Operating System Version:
RHEL 6.9

#### Steps to Reproduce:

1. Run oscap against system without cifs mounts or samba-common installed
2. see failure

#### Actual Results:
failure

#### Expected Results:
pass

#### Addition Information/Debugging Steps:
The xccdf does not require samba-common to be installed.  i believe the following line is causing the failure.
`
shared/checks/oval/mount_option_smb_client_signing.xml:        <extend_definition comment="samba-common installed" definition_ref="package_samba-common_installed" />
`

**Comment by redhatrises** [comment]
@jamescassell this is expected behaviour as `samba-common` provides `/etc/samba/smb.conf`

**Comment by jamescassell** [comment]
@redhatrises would not a system be compliant if samba-common is not installed?  What is checking /etc/samba/smb.conf?  as far as I can see, the oval is otherwise only checking `/etc/fstab` and `/etc/mtab`

**Comment by marcusburghardt** [comment]
RHEL6 no longer present in the project.
