### ISSUE TITLE
stig-rhel6-disa profile includes /dev/shm

### ISSUE THREAD

**Issue by jamescassell** [ComplianceAsCode/content#2753]
#### Description of problem:
The RHEL 6 STIG V1R18 makes no mention of /dev/shm

```
Add nodev Option to /dev/shm - Fail
Add noexec Option to /dev/shm - Fail
Add nosuid Option to /dev/shm - Fail
```

#### SCAP Security Guide Version:
0.1.38

#### Operating System Version:
RHEL 6.9

#### Steps to Reproduce:

1. Perform manual STIG remediation
2. run oscap profile stig-rhel6-disa

#### Actual Results:
failed

```
Add nodev Option to /dev/shm - Fail
Add noexec Option to /dev/shm - Fail
Add nosuid Option to /dev/shm - Fail
```

#### Expected Results:
no rule present

#### Addition Information/Debugging Steps:
the RHEL 6 STIG only mentions `nodev` and `nosuid` in the context of being required for "remote file systems."  `noexec` is only mentioned in the case of `/tmp` and "remote file systems."

**Comment by jamescassell** [comment]
https://access.redhat.com/support/cases/#/case/02079384

**Comment by shawndwells** [comment]
@tbrunell @tedbrunell another one to check with DISA about before we drop upstream.

**Comment by shawndwells** [comment]
(temp assigning this to Ted)

**Comment by jamescassell** [comment]
DISA added this in V1R20
