### ISSUE TITLE
adjtimex removed from RHEL 6 STIG

### ISSUE THREAD

**Issue by jamescassell** [ComplianceAsCode/content#2756]
#### Description of problem:
V1R16 of RHEL 6 STIG removed the requirement to audit adjtimex.

#### SCAP Security Guide Version:
0.1.38

#### Operating System Version:
RHEL 6.9

#### Steps to Reproduce:

1. remediate system per STIG
2. run oscap
3. see failure for `audit_rules_time_adjtimex`

#### Actual Results:
```
Record attempts to alter time through adjtimex - Fail
```

#### Expected Results:
rule not present

**Comment by jamescassell** [comment]
https://access.redhat.com/support/cases/#/case/02079384

**Comment by shawndwells** [comment]
True enough that it's not in there. Hard to believe DISA would no longer want auditing of time changes.

@tbrunell @tedbrunell could you check with DISA if removing this wasn't an oversight?

**Comment by jamescassell** [comment]
Here's the changelog entry from V1R16: `Removed V-38635 - Removed the requirement as there is not an adjtimex in hwclock, and it has not been replaced with another command.`

**Comment by shawndwells** [comment]
@jamescassell appreciate the reference (and opening the tickets!).

Unfortunately DISA did not coordinate these changes with Red Hat, DoD CIO, DoD CISO, NSA, NIST, the DoD DAA council, or the CNSSI committees. Should they have, they would have learned that adjtimex is still in RHEL and calls to it change the system clock. 

Other DoD policies (especially any based off NIST 800-53) require auditing changes to system time settings. Very surprising DISA would drop this, so we want to double check with them.

**Comment by tedbrunell** [comment]
adjtimex is not installed by default in RHEL 6.9, nor is it available during installation.  Since it would take manual intervention to install the package, I think that we can safely drop this from SSG unless we decide that we should keep it in case someone decides to install the busybox package. (https://access.redhat.com/solutions/35012)

**Comment by redhatrises** [comment]
@tbrunell unfortunately that is actually not entirely true or an accurate solution article. It leads people to believe that `adjtimex` is part of the busybox package. It is actually apart of the Linux Kernel hence it being a syscall. Here is some of the kernel code reference: https://github.com/torvalds/linux/blob/master/kernel/time/ntp.c

**Comment by tedbrunell** [comment]
@redhatrises Okay - that makes sense.  I will pass it along to see if DISA will put it back into the DoD STIG that they publish.

**Comment by jamescassell** [comment]
Looks like after someone followed up w/ DISA, this was added to the V1R20 STIG.
