### ISSUE TITLE
Enable CI/CD for Ansible roles at https://github.com/Ansible-Security-Compliance

### ISSUE THREAD

**Issue by redhatrises** [ComplianceAsCode/content#2762]
#### Description of problem:
Ansible roles need to have a CI/CD workflow to Ansible Galaxy rather than pushed occasionally or with every release. 

#### SCAP Security Guide Version:
master

#### Actual Results:
Nothing

#### Expected Results:
https://github.com/Ansible-Security-Compliance roles are updated with every master update.

**Comment by dahaic** [comment]
@redhatrises what is the reasoning for this request? Currently we do not really check every PR functionally. SSG Test Suite is not even designed with gating in mind. We can utilize it to check for problems once per release (in ideal case once per week), but every PR? That would result in blindly pushing playbooks which only quality is they are buildable.

**Comment by redhatrises** [comment]
@dahaic we need this for strategic objectives and competitive pressures. Ideally the week that Summit ends.

> SSG Test Suite is not even designed with gating in mind. 

When would that be done? 

> Pushing every PR? That would result in blindly releasing playbooks whose only quality is ... ?

And.... what is the difference between what is done now? I really don't think that this is an issue with how things are currently done. Also, you are always going to have bugs.

**Comment by redhatrises** [comment]
Closing as we are handling this through regular release and such.
