### ISSUE TITLE
Provide index html page for easy access to all generated html build artefacts

### ISSUE THREAD

**Issue by dahaic** [ComplianceAsCode/content#2780]
#### Description of problem:
We do generate html guides for all profiles, tables for some of the references references (ANSSI, PCIDSS, CCE). Access is a bit clumsy though, as these are all separate guides.

If we provide index page which aggregates all this artefacts with convenient description, it will be easier for our users to use SSG to the fullest.

#### SCAP Security Guide Version:
0.1.38

**Comment by jan-cerny** [comment]
@dahaic Could it be published on https://static.open-scap.org/ instead of having to update this page manually?

**Comment by dahaic** [comment]
Idea is to generate this index page during build time as well. So it will provide similar functionality to https://static.open-scap.org/ just on a local machine.

**Comment by shawndwells** [comment]
This would be really useful. Good idea!

**Comment by jan-cerny** [comment]
@dahaic Does https://jenkins.complianceascode.io/job/scap-security-guide-stats/HTML_20Guides and https://jenkins.complianceascode.io/job/scap-security-guide-stats/HTML_20Mapping_20Tables satisfy your need?

**Comment by ggbecker** [comment]
They just don't have nice description, it's a plain list of files and you need to save it and open the guide/table locally due to some security constraints.

**Comment by ggbecker** [comment]
We do have a webpage containing latest main branch built guides and other artifacts: https://complianceascode.github.io/content-pages/

It's also possible to generate them locally with something like:

```
      - name: Build
        run: cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug
        working-directory: ./build
      - name: Build Guides and Mapping Tables
        run: ninja -j2
        working-directory: ./build
      - name: Build Statistics
        run: ninja html-stats html-profile-stats -j2
        working-directory: ./build
      - name: Generate HTML pages
        run: utils/generate_html_pages.sh $PAGES_DIR
```

https://github.com/ComplianceAsCode/content/blob/master/.github/workflows/gh-pages.yaml
