### ISSUE TITLE
Un-namespaced 'reference' tags in 0.1.38 ssg-centos7-ds.xml

### ISSUE THREAD

**Issue by solind** [ComplianceAsCode/content#2801]
#### Description of problem:

There are "reference" tags (e.g., on line 65 of ssg-centos7-ds.xml) with no namespace, and since there is no default namespace defined for the XML document, the tags are invalid.

#### SCAP Security Guide Version:

0.1.38

#### Operating System Version:

n/a

**Comment by redhatrises** [comment]
Thanks for reporting @solind!

**Comment by redhatrises** [comment]
@solind Do you mind adding an example of correctly anchored expressions for documentation completeness?

**Comment by matejak** [comment]
This is still valid, here is an example of that "reference tag":

These are part of the `ssg-install_hids` OVAL definition:
```
            <reference ref_id="CCE-26818-5" source="CCE"/>
            <reference ref_id="install_hids" source="ssg"/>
```

**Comment by yuumasato** [comment]
This should be fixed by: https://github.com/ComplianceAsCode/content/pull/4049 (not released yet)

> This is still valid, here is an example of that "reference tag":

I discussed with @matejak, and the snippet is from release 0.1.43.

So I believe we can close this.
