### ISSUE TITLE
Un-anchored regular expressions in 0.1.38 CentOS7 STIG

### ISSUE THREAD

**Issue by solind** [ComplianceAsCode/content#2808]
Similar to #2604 -- there are a large number of un-anchored regular expressions in the 0.1.38 release, specifically, in ssg-centos7-ds.xml, e.g.:

In partition_objects and many textfilecontent54_objects:
- oval:ssg-obj_network_disable_ddns_interfaces_dhclient:obj:1
- oval:ssg-object_aide_crontabs_checking:obj:1
- oval:ssg-object_aide_crontabs_notification:obj:1
- oval:ssg-object_bootloader_uefi_password:obj:1
- oval:ssg-object_mount_option_var_tmp:obj:1
- etc.

And also in a symlink_state:
- oval:ssg-state_disable_xwindows_runlevel:ste:1

**Comment by redhatrises** [comment]
Thanks @solind for identifying this! Do you mind adding an example of correctly anchored expressions for documentation completeness?

**Comment by solind** [comment]
Sure, let us take for example oval:ssg-obj_network_disable_ddns_interfaces_dhclient:obj:1, defined as follows:

```
        <ns6:textfilecontent54_object id="oval:ssg-obj_network_disable_ddns_interfaces_dhclient:obj:1" version="1">
          <ns6:filepath operation="pattern match">/etc/dhclient.*\.conf</ns6:filepath>
          <ns6:pattern operation="pattern match">^[\s]*send[\s]+host-name.*$</ns6:pattern>
          <ns6:instance datatype="int">1</ns6:instance>
        </ns6:textfilecontent54_object>
```

The regular expression in the filepath entity is not anchored.  If it were anchored, it would look like this:

```
          <ns6:filepath operation="pattern match">^/etc/dhclient.*\.conf</ns6:filepath>
                                                  ^
                                                  |
                                                  +- I added this left-anchor
```

With the anchor, the interpreter can restrict itself to looking for matches under /etc. But without the anchor, the entire file-system must be searched. For example, a possible legal match for "/etc/dhclient.*\.conf" could be the file "/tmp/etc/dhclient-foo.conf".  But that's not what this object actually was written to match, it's really supposed to look under /etc only.

Does that help?

**Comment by redhatrises** [comment]
@solind that's perfect. I just want to make sure that it is documented for future contributors, etc.

**Comment by solind** [comment]
FYI, these issues persist in 0.1.39.  There are dozens of un-anchored filepath-based patterns throughout the content, e.g.:

oval:ssg-obj_dhcp_client_domain-named:obj:1
oval:ssg-obj_dhcp_client_domain-name-servers:obj:1
oval:ssg-obj_dhcp_client_nis-domain:obj:1
oval:ssg-obj_dhcp_client_nis-servers:obj:1
oval:ssg-obj_dhcp_client_ntp-servers:obj:1

etc.

**Comment by redhatrises** [comment]
Thanks @solind. We have yet to look at and address this issue.
