### ISSUE TITLE
pam_faillock tally persistence

### ISSUE THREAD

**Issue by sshimko** [ComplianceAsCode/content#2851]
pam_faillock modifications don't appear to specify a location on the filesystem to store the account tally state. The default location seems to be /var/run/faillock, which isn't persistent by default on some distros.

I think any content touching faillock should probably set the location for tally state via "dir=" parameter in the PAM configuration to ensure the content reflects distro defaults.

**Comment by yuumasato** [comment]
Interesting issue,
one way to address this would be to define an XCCDF:Value for `dir=`, that will only be used as part of remediation. Advantage of this approach is that one can tailor this value.
Another option is to have a value defined in `product.yml`, specifying default tally log dir for each product. Advantage of this approach is that it is streamlined to work out of the box, but without tailoring capabilities.
A third approach can combine both above, the value in `product.yml` would set the default XCCDF:Value for each product.

**Comment by ggbecker** [comment]
@yuumasato In the first option you could put the tailored directory in the rule description.

**Comment by marcusburghardt** [comment]
Just linking some STIG references to the topic:
https://www.stigviewer.com/stig/red_hat_enterprise_linux_8/2021-12-03/finding/V-230339
https://www.stigviewer.com/stig/red_hat_enterprise_linux_8/2021-12-03/finding/V-250315

**Comment by marcusburghardt** [comment]
Solved by the inclusion of a new rule for `pam_faillock.so` `dir` option.
#9170
