### ISSUE TITLE
Kernel parameters checks should use syctl

### ISSUE THREAD

**Issue by tranca** [ComplianceAsCode/content#2852]
#### Description of problem:
When I run the oscap tool with the profile "common" of "ssg-debian8-xccdf.xml, the following test fails: "Enable Randomized Layout of Virtual Address Space".
The tool is looking for the value "kernel.randomize_va_space = 2" in the file "/etc/sysctl.conf" and doesn't find it.
However, I get the following output from the sysctl command:
`$ sysctl kernel.randomize_va_space`
`kernel.randomize_va_space = 2`

As mentioned in the issue "Kernel module checks should use lsmod #2651" The tool could use a priority system in which if it doesn't find the value in a config file, looks for the value in another location. The command `sysctl -a` could be used to list all kernel parameters actually used.

#### SCAP Security Guide Version:
0.1.31-5 - SCAP Guides and benchmarks targeting Debian 8

#### Operating System Version:
Debian 8

#### Steps to Reproduce:

1. `sudo oscap xccdf eval --profile common --cpe ssg-debian8-cpe-dictionary.xml ssg-debian8-xccdf.xml`
2. Checks the results

**Comment by redhatrises** [comment]
Thanks for reporting @tranca. 

OVAL is the language used to scan and check all the configurations in each location that sysctl checks can be configured, so using `sysctl -a` doesn't/won't work. What has to be done is checking `/proc/modules` for the correct "runtime" configuration, but the configuration file(s) also have to be checked to verify the check is correctly configured. Where do you currently have `kernel.randomize_va_space` configured to be the correct value?

**Comment by ajd394** [comment]
@redhatrises  Runtime values for these kernel parameters are located at `/proc/sys/kernel/`  not `/proc/modules`

**Comment by tranca** [comment]
Hi,

I found the correct value in the file "/proc/sys/kernel/randomize_va_space".

@ajd394: Thanks for the tip

**Comment by ajd394** [comment]
The current profile check (and that for v1.31) requires both static AND runtime (using sysctl) checks. 
https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/checks/oval/sysctl_kernel_randomize_va_space.xml

@redhatrises The unix extension for OVAL has sysctl checks. 
https://github.com/CISecurity/OVALRepo/blob/master/oval_schemas/5.11.2/unix-definitions-schema.xsd#L2352

There are both static and runtime OVAL checks for this item 

https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/checks/oval/sysctl_runtime_kernel_randomize_va_space.xml

https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/checks/oval/sysctl_static_kernel_randomize_va_space.xml

**Comment by redhatrises** [comment]
@tranca it is expected that both runtime and static configurations checks are correct. Where did you configure `kernel.randomize_va_space`?

**Comment by ajd394** [comment]
http://man7.org/linux/man-pages/man5/sysctl.conf.5.html

> /run/sysctl.d/*.conf
> /etc/sysctl.d/*.conf
> /usr/local/lib/sysctl.d/*.conf
> /usr/lib/sysctl.d/*.conf
> /lib/sysctl.d/*.conf
> /etc/sysctl.conf

**Comment by ajd394** [comment]
i believe you can use grub to modify kernel parameters at boot so you could look there too

**Comment by pietro** [comment]
`kernel.randomize_va_space = 2` is set as default at kernel build time if 1) the arch supports it and 2) `CONFIG_COMPAT_BRK` was not enabled when the kernel was built.

As @ajd394 said you can disable address space randomization by passing `norandmaps` to the kernel as a boot parameter. That will show up as 0 on `/proc/sys/kernel/randomize_va_space`. The kernel boot parameters can be checked at `/proc/cmdline`

**Comment by marcusburghardt** [comment]
Debian 8 is no longer present in the project.
