### ISSUE TITLE
group_auditd_data_retention rules and expected values

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#2871]
## Description of problem:
There are several rules, that are checking string values in audit (`/etc/audit/auditd.conf`) or audisp-plugin (`/etc/audisp/audisp-remote.conf`) configs and these values tells system, what should happen if something happened... But some values are correct for ssg, which doesnt make sense for me (e.g. Is it really ok to ignore, that it is starting to to get low space on disk? etc.), so Id like to start discussion about these values.
I will try to shortly describe each option that is tested by rule, possible values, describe values and open discussion which values are expected in ssg (= what I got after running `tests/test_suite.py`) and why, because I'd expected anything else. (+ tests, that I used for testing values)
Tested on RHEL 7.5

### rule_auditd_data_retention_max_log_file_action
Tells the system what action to take when the system has detected that the max file size limit has been reached.
Values: 
- :red_circle: **ignore** - does nothing. I'd expect fail, but scan exits with return code 0. [max_log_file_action_ignore.fail.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_data_retention_max_log_file_action/max_log_file_action_ignore.fail.sh)

- **syslog** - will issue a warning to syslog. Pass, I think its ok. [max_log_file_action_syslog.pass.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_data_retention_max_log_file_action/max_log_file_action_syslog.pass.sh)

- :red_circle: **suspend** - will cause audit daemon to stop writing records to the disk. I'd expect fail but scan exits with return code 0. [max_log_file_action_suspend.fail.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_data_retention_max_log_file_action/max_log_file_action_suspend.fail.sh)

- **rotate** - will cause audit daemon to rotate the logs. Pass, I think its ok. [max_log_file_action_rotate.pass.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_data_retention_max_log_file_action/max_log_file_action_rotate.pass.sh)

- **keep_logs** - similar to rotate except it does not use the num_logs setting (it wont rewrite old ones). Pass, I think its ok. [max_log_file_action_keep_logs.pass.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_data_retention_max_log_file_action/max_log_file_action_keep_logs.pass.sh)

### rule_auditd_data_retention_flush
Flushing data to disk.
Values:
- **none** - no special effort is made to flush the audit records to disk. Pass. [flush_none.fail.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_data_retention_flush/flush_none.fail.sh)

- :red_circle: **incremental** - freq parameter is used to determine how often an explicit flush to disk is issued. I'd expect pass, but scan has exited with return code 2, why? [flush_incremental.pass.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_data_retention_flush/flush_incremental.pass.sh)

- :red_circle: **incremental_async** - very much like incremental except the flushing is done asynchronously for higher performance. I'd expect pass, but scan has exited with return code 2, why? [flush_incremental_async.pass.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_data_retention_flush/flush_incremental_async.pass.sh)

- **data** - tells the audit daemon to keep the data portion of the disk file sync'd at all times. Pass, I think its ok. [flush_data.pass.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_data_retention_flush/flush_data.pass.sh)

- :red_circle: **sync** - tells the audit daemon to keep both the data and meta-data fully sync'd with every write to disk. Pass, I think its ok. [flush_sync.pass.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_data_retention_flush/flush_sync.pass.sh)

### rule_auditd_data_retention_admin_space_left_action
Tells the system what action to take when the system has detected that it is low on disk space. (both rules has same values)
Values:

- **ignore** - audit daemon does nothing. Pass. [admin_space_left_action_ignore.fail.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_data_retention_admin_space_left_action/admin_space_left_action_ignore.fail.sh)

- :red_circle: **syslog** - will issue a warning to syslog. I'd expect pass but scan has exited with return code 2, why? [admin_space_left_action_syslog.pass.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_data_retention_admin_space_left_action/admin_space_left_action_syslog.pass.sh)

- :red_circle: **rotate** - will rotate logs, losing the oldest to free up space. I'd expect pass but scan has exited with return code 2, why? [admin_space_left_action_rotate.pass.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_data_retention_admin_space_left_action/admin_space_left_action_rotate.pass.sh)

- :red_circle:  **email** - will send a warning to the email account specified in action_mail_acct as well as sending the message to syslog. I'd expect pass but scan has exited with return code 2, why? [admin_space_left_action_email.pass.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_data_retention_admin_space_left_action/admin_space_left_action_email.pass.sh)

- :red_circle: **exec /path-to-script** - will execute the script. Pass, I think its ok. [admin_space_left_action_exec.pass.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_data_retention_admin_space_left_action/admin_space_left_action_exec.pass.sh)

- **suspend** - will cause the audit daemon to stop writing records to the disk. Pass. [admin_space_left_action_suspend.fail.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_data_retention_admin_space_left_action/admin_space_left_action_suspend.fail.sh)

- **single** - will cause the audit daemon to put the computer system in single user mode. Pass. [admin_space_left_action_single.pass.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_data_retention_admin_space_left_action/admin_space_left_action_single.pass.sh)

- **halt** - will cause the audit daemon to shutdown the computer system. Pass. [admin_space_left_action_halt.fail.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_data_retention_admin_space_left_action/admin_space_left_action_halt.fail.sh)

- :red_circle: **exec /path-to-script** - execute the script. I'd expect pass but scan has exited with return code 2, why? [admin_space_left_action_exec.pass.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_data_retention_admin_space_left_action/admin_space_left_action_exec.pass.sh)

## rule_auditd_data_retention_space_left_action
Tells the system what action to take when the system has detected that it is low on disk space. (both rules has same values)
Values:

- **ignore** - audit daemon does nothing. Pass. [space_left_action_ignore.fail.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_data_retention_space_left_action/space_left_action_ignore.fail.sh)

- :red_circle: **syslog** - will issue a warning to syslog. I'd expect pass but scan has exited with return code 2, why? [space_left_action_syslog.pass.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_data_retention_space_left_action/space_left_action_syslog.pass.sh)

- **rotate** - will rotate logs, losing the oldest to free up space. I'd expect pass but scan has exited with return code 2, why? [admin_space_left_action_rotate.pass.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_data_retention_admin_space_left_action/admin_space_left_action_rotate.pass.sh)

- **email** - will send a warning to the email account specified in action_mail_acct as well as sending the message to syslog. Pass. [space_left_action_email.pass.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_data_retention_space_left_action/space_left_action_email.pass.sh)

- :red_circle: **exec /path-to-script** - will execute the script. Pass, I think its ok. [admin_space_left_action_exec.pass.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_data_retention_admin_space_left_action/admin_space_left_action_exec.pass.sh)

- **suspend** - will cause the audit daemon to stop writing records to the disk. Pass. [space_left_action_suspend.fail.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_data_retention_space_left_action/space_left_action_suspend.fail.sh)

- **single** - will cause the audit daemon to put the computer system in single user mode. Pass. [space_left_action_single.fail.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_data_retention_space_left_action/space_left_action_single.fail.sh)

- **halt** - will cause the audit daemon to shutdown the computer system. Pass. [space_left_action_halt.fail.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_data_retention_space_left_action/space_left_action_halt.fail.sh)

- :red_circle: **exec /path-to-script** - execute the script. I'd expect pass but scan has exited with return code 2, why? [space_left_action_exec.pass.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_data_retention_space_left_action/space_left_action_exec.pass.sh)

### rule_auditd_audispd_network_failure_action
Tells the system what action to take whenever there is an error detected when sending audit events to the remote system.

-  :red_circle: **ignore** - the remote logging app does nothing. I'd expect fail but scan has exited with return code 0, why? [network_failure_action_ignore.fail.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_audispd_network_failure_action/network_failure_action_ignore.fail.sh)

- **syslog** - it will issue a warning to syslog. Pass, I think its ok. [network_failure_action_syslog.pass.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_audispd_network_failure_action/network_failure_action_syslog.pass.sh)

- **exec /path-to-script** - execute the script. Pass, I think it is ok. [network_failure_action_exec.pass.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_audispd_network_failure_action/network_failure_action_exec.pass.sh)

-  :red_circle: **suspend** - will cause the remote logging app to stop sending records to the remote system. I'd expect fail but scan has exited with return code 0, why? [network_failure_action_suspend.fail.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_audispd_network_failure_action/network_failure_action_suspend.fail.sh)

- **single** - will cause the remote logging app to put the computer system in single user mode. Pass, is it ok? [network_failure_action_single.pass.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_audispd_network_failure_action/network_failure_action_single.pass.sh)

-  :red_circle: **halt** - will cause the remote logging app to shutdown the computer system. I'd expect fail but scan has exited with return code 0, why? [network_failure_action_halt.fail.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_audispd_network_failure_action/network_failure_action_halt.fail.sh)

-  :red_circle: **stop** - will cause the remote logging app to exit, but leave other plugins running. I'd expect fail but scan has exited with return code 0, why? [network_failure_action_stop.fail.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_audispd_network_failure_action/network_failure_action_stop.fail.sh)

- **warm_once** - like warn_once_continue  execept  that  the  event  is  not dequeued. Pass, I think its ok. [network_failure_action_warm_once.pass.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_audispd_network_failure_action/network_failure_action_warm_once.pass.sh)

- **warm_once_continue** - like syslog execept that only one message is put in syslog until  an  event  is  successfully  transferred. Pass. [network_failure_action_warm_once_continue.pass.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_audispd_network_failure_action/network_failure_action_warm_once_continue.pass.sh)

### rule_auditd_audispd_disk_full_action
Tells the system what action to take if  the remote end signals a disk full error.

- :red_circle: **ignore** - the remote logging app does nothing. I'd expect fail but scan has exited with return code 0, why? [disk_full_action_ignore.fail.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_audispd_disk_full_action/disk_full_action_ignore.fail.sh)

- **syslog** - it will issue a warning to syslog. Pass, I think its ok.  [disk_full_action_syslog.pass.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_audispd_disk_full_action/disk_full_action_syslog.pass.sh)

- **exec /path-to-script** - execute the script. Pass, I think it is ok. [disk_full_action_exec.pass.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_audispd_disk_full_action/disk_full_action_exec.pass.sh)

- :red_circle: **suspend** - will cause the remote logging app to stop sending records to the remote system. I'd expect fail but scan has exited with return code 0, why? [disk_full_action_suspend.fail.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_audispd_disk_full_action/disk_full_action_suspend.fail.sh)

- **single** - will cause the remote logging app to put the computer system in single user mode. Pass, is it ok? [disk_full_action_single.pass.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_audispd_disk_full_action/disk_full_action_single.pass.sh)

- :red_circle: **halt** - will cause the remote logging app to shutdown the computer system. I'd expect fail but scan has exited with return code 0, why? [disk_full_action_halt.fail.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_audispd_disk_full_action/disk_full_action_halt.fail.sh)

- :red_circle: **stop** - will cause the remote logging app to exit, but leave other plugins running. I'd expect fail but scan has exited with return code 0, why? [disk_full_action_stop.fail.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_audispd_disk_full_action/disk_full_action_stop.fail.sh)

- **warm_once** - like warn_once_continue  execept  that  the  event  is  not dequeued. Pass, I think its ok. Pass, I think its ok. [disk_full_action_warm_once.pass.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_audispd_disk_full_action/disk_full_action_warm_once.pass.sh)

- **warm_once_continue** - like syslog execept that only one message is put in syslog  until  an  event  is  successfully  transferred. Pass. [disk_full_action_warm_once_continue.pass.sh](https://github.com/mildass/scap-security-guide/blob/auditd_data_retention_tests/tests/data/group_system/group_auditing/group_auditd_data_retention/rule_auditd_audispd_disk_full_action/disk_full_action_warm_once_continue.pass.sh)

I'd like to discuss above mentioned values, which we are expecting, why we are expecting them and if is it ok. 
It looks for me, that every value in these audits configs is correct for ssg, but I dont think, that it is correct.

**Comment by ggbecker** [comment]
@mildass Do you have any update on this? People mentioned about some probable PR you have created, is this true?

**Comment by mildass** [comment]
@ggbecker There were a lot of PRs, which had changed scripts from this issue. I'll check them and update/close this issue, if it's solved.
