### ISSUE TITLE
Rules for non-UEFI grub.cfg cannot remediate UEFI systems

### ISSUE THREAD

**Issue by yuumasato** [ComplianceAsCode/content#2872]
#### Description of problem:
This may sound obvious, but for example:
Rule description of Rule `file_permissions_grub_cfg` says `grub.cfg` file should have permissions 600 or stronger. Mentions location of both files, `/boot/grub2/grub.cfg` and `/boot/efi/EFI/redhat/grub.cfg`, and will check for permissions in both places. (for `/boot/efi/EFI/redhat/grub.cfg` it will actually check for 700).
But [remediation](https://github.com/OpenSCAP/scap-security-guide/blob/master/shared/fixes/bash/file_permissions_grub2_cfg.sh) associated with it only fixes `/boot/grub2/grub.cfg`, for non-UEFI systems.

So rule can evaluate whether a system has its `grub.cfg` file with correct permissions on both systems, but can only fix permission on one type.

This also happens for Rules:
- `file_user_owner_grub2_cfg`
- `file_group_owner_grub2_cfg`

#### SCAP Security Guide Version:
scap-security-guide-0.1.39

#### Steps to Reproduce:

1. Install a system with UEFI boot
1. Break the rule (`chmod 644 /boot/efi/EFI/redhat/grub.cfg`)
1. Scan a system with UEFI boot with a profile with Rule `file_group_owner_grub2_cfg` selected , for example, rht-ccp profile
1. Rule will fail, try to remediate
1. Rule will try to remediate `/boot/grub2/grub.cfg`

#### Actual Results:
Rule tries to remediate `/boot/grub2/grub.cfg`

#### Expected Results:
Permissions on file `/boot/efi/EFI/redhat/grub.cfg` are fixed.

#### Addition Information/Debugging Steps:

Possible solutions are either:
- Improve remediation for `file_.*_grub2_cfg` rules to be capable of fixing UEFI systems, or
- Separate completely checks and description.

**Comment by redhatrises** [comment]
The following rules exist to handle EFI permissions:
- `file_owner_efi_grub2_cfg`
- `file_groupowner_efi_grub2_cfg`
- `file_permissions_efi_grub2_cfg`

The above rules should be used for EFI systems, and remediations are generated on builds. Closing.

**Comment by iokomin** [comment]
@redhatrises, IMO file_*_efi_grub2_cfg rules existence is not a problem solution yet.
It should be considered you can run same profile on both UEFI and non-UEFI systems. If both set of rules added to profile under evaluation you will have _efi_ rules always failing on non-UEFI systems and vice versa. 
Does it all make sense?

**Comment by shawndwells** [comment]
Looks like the OVAL do not evaluate for file existence before pass/fail. 

For remediations we can add an evaluation to make sure file exists before trying to chown/chgrp/chmod.

**Comment by redhatrises** [comment]
> @redhatrises, IMO file_*_efi_grub2_cfg rules existence is not a problem solution yet.
> It should be considered you can run same profile on both UEFI and non-UEFI systems. If both set of rules added to profile under evaluation you will have _efi_ rules always failing on non-UEFI systems and vice versa.
> Does it all make sense?

This is what profile tailoring is for and is what is expected in compliance environments. Rules are added and removed using tailoring based on environment for the specific profiles.

**Comment by shawndwells** [comment]
Some (most?) of the default profiles will have both these rules inside of them though. Having all the profiles require tailoring prior to being usable would not be a great user experience. Seems reasonable to create conditional checks (if file exists, evaluate or set perms).

**Comment by yuumasato** [comment]
Original point of this issue was just about misalignment in expectation of rule, check and fix.
The description and check was about permissions in both UEFI and non-UEFI systems, while remediation only fixed non-UEFI systems.

From discussions, it seems that each system should be handled by its own set of rules, be present in the profile and only manifest when applicable.

This seems like, CPE Applicability Language is the way to go. There could be a check for applicability for UEFI and non-UEFi rules.
And this way a UEFI rule would result in not-applicable in non-UEFI systems.

**Comment by yuumasato** [comment]
The original issue is actually fixed in: https://github.com/ComplianceAsCode/content/pull/4193
