### ISSUE TITLE
fix for rpm_verify_permissions invalidates file_permissions_grub2_cfg

### ISSUE THREAD

**Issue by michaeldayCA** [ComplianceAsCode/content#2892]
#### Description of problem:
In the NIST 800-171 remediations script, the fix for rpm_verify_permissions is at position 318 and the fix for file_permissions_grub2_cfg is at position 183.

This means that the grub2_cfg fix will set permissions to 600 on the /boot/grub2/grub.cfg, then have its changes subsequently undone when rpm_verify_permissions runs and sets the permissions back to 644 on /boot/grub2/grub.cfg.

This causes the xccdf_org.ssgproject.content_rule_file_permissions_grub2_cfg rule to fail when the system is scanned.

#### SCAP Security Guide Version:
0.1.39-2.el7.centos

#### Operating System Version:
CentOS Linux release 7.5.1804 (Core)

#### Steps to Reproduce:

1. Generate and run the bash remediations script for the NIST 800-171 profile

#### Actual Results:
Final permissions of /boot/grub2/grub.cfg are -rw-r--r--

#### Expected Results:
Final permissions of /boot/grub2/grub.cfg are -rw-------

#### Suggested Fix:
Move the remediation for file_permissions_grub2_cfg so that it is run after rpm_verify_permissions when the bash remediation script is generated

#### Addition Information/Debugging Steps:
```
bash-4.2# chmod 600 /boot/grub2/grub.cfg
bash-4.2# ls -al /boot/grub2/grub.cfg 
-rw-------. 1 root root 3928 Jun  1 12:20 /boot/grub2/grub.cfg
bash-4.2# cat fix.sh 
#!/bin/bash

###############################################################################
# BEGIN fix (318 / 358) for 'xccdf_org.ssgproject.content_rule_rpm_verify_permissions'
###############################################################################
(>&2 echo "Remediating rule 318/358: 'xccdf_org.ssgproject.content_rule_rpm_verify_permissions'")

# Declare array to hold list of RPM packages we need to correct permissions for
declare -a SETPERMS_RPM_LIST

# Create a list of files on the system having permissions different from what
# is expected by the RPM database
FILES_WITH_INCORRECT_PERMS=($(rpm -Va --nofiledigest | grep '^.M' | cut -d ' ' -f4-))

# For each file path from that list:
# * Determine the RPM package the file path is shipped by,
# * Include it into SETPERMS_RPM_LIST array

for FILE_PATH in "${FILES_WITH_INCORRECT_PERMS[@]}"
do
        RPM_PACKAGE=$(rpm -qf "$FILE_PATH")
        SETPERMS_RPM_LIST=("${SETPERMS_RPM_LIST[@]}" "$RPM_PACKAGE")
done

# Remove duplicate mention of same RPM in $SETPERMS_RPM_LIST (if any)
SETPERMS_RPM_LIST=( $(echo "${SETPERMS_RPM_LIST[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' ') )

# For each of the RPM packages left in the list -- reset its permissions to the
# correct values
for RPM_PACKAGE in "${SETPERMS_RPM_LIST[@]}"
do
        rpm --setperms "${RPM_PACKAGE}"
done
# END fix for 'xccdf_org.ssgproject.content_rule_rpm_verify_permissions'

bash-4.2# chmod +x fix.sh
bash-4.2# ./fix.sh 
Remediating rule 318/358: 'xccdf_org.ssgproject.content_rule_rpm_verify_permissions'
chmod: cannot access ‘/etc/sysconfig/kvm’: No such file or directory
chmod: cannot access ‘/var/lib/rpm/__db.004’: No such file or directory
chmod: cannot access ‘/var/lib/rpm/__db.005’: No such file or directory
chmod: cannot access ‘/var/lib/rpm/__db.006’: No such file or directory
chmod: cannot access ‘/var/lib/rpm/__db.007’: No such file or directory
chmod: cannot access ‘/var/lib/rpm/__db.008’: No such file or directory
chmod: cannot access ‘/var/lib/rpm/__db.009’: No such file or directory
chmod: cannot access ‘/etc/X11/xorg.conf.d/00-keyboard.conf’: No such file or directory
chmod: cannot access ‘/etc/machine-info’: No such file or directory
chmod: cannot access ‘/etc/systemd/system/runlevel2.target’: No such file or directory
chmod: cannot access ‘/etc/systemd/system/runlevel3.target’: No such file or directory
chmod: cannot access ‘/etc/systemd/system/runlevel4.target’: No such file or directory
chmod: cannot access ‘/etc/systemd/system/runlevel5.target’: No such file or directory
chmod: cannot access ‘/var/lib/systemd/backlight’: No such file or directory
chmod: cannot access ‘/var/lib/systemd/clock’: No such file or directory
chmod: cannot access ‘/var/lib/systemd/rfkill’: No such file or directory
bash-4.2# ls -al /boot/grub2/grub.cfg 
-rw-r--r--. 1 root root 3928 Jun  1 12:20 /boot/grub2/grub.cfg
```

**Comment by yuumasato** [comment]
Sure, scanning order of rules is determined by their order within the Benchmark.
It makes sense to have `rpm_verify_permissions` and others rules that set default vendor configuration first (broad configuration), then rules that change specific system config can come later.

If one is using bash remediation role, or profile playbook, the remediations will be fighting each other, and the last to run wins. And if `rule_rpm_verify_permissions` is before `file_permissions_grub2_cfg` the system will be compliant.

But note that, regardless of rule order, if one is doing oscap scan, there will always be a `fail` in either of the rules, and remediating one of the rules that failed will make the other rule fail. I'm not sure how to deal with this.

**Comment by marcusburghardt** [comment]
Related to https://github.com/OpenSCAP/openscap/issues/1880
