### ISSUE TITLE
Update NIST 800-171 profile

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#2927]
Today, NIST is releasing an update for Special Publication (SP) 800-171 Revision 1, Protecting Controlled Unclassified Information in Nonfederal Systems and Organizations. This errata update includes minor editorial changes to selected CUI security requirements, some additional references and definitions, and a new appendix (Appendix F, “Discussion”) that contains an expanded discussion about each CUI requirement.

 

Publication details: https://csrc.nist.gov/publications/detail/sp/800-171/rev-1/final

CSRC Update: https://csrc.nist.gov/News/2018/NIST-Publishes-Errata-Update-for-SP-800-171-Rev-1

 

__________
NIST Computer Security Division
Email: sec-cert@nist.gov   (Attn: NIST FISMA Team)
Notification sent out by: Pat O'Reilly, NIST Computer Security Division

**Comment by marcusburghardt** [comment]
Reference no longer available. Likely outdated.
