### ISSUE TITLE
xccdf_org.ssgproject.content_rule_set_firewalld_default_zone for DISA STIG RHEL-07-040810 does not properly address the STIG

### ISSUE THREAD

**Issue by amitkumar50** [ComplianceAsCode/content#2964]
#### Description of problem:
Rule ID xccdf_org.ssgproject.content_rule_set_firewalld_default_zone for DISA STIG RHEL-07-040810 does not properly address the STIG. The title, description, rationale, and oval check are to set the firewall DefaultZone to drop. However, the actual STIG only requires that firewalld is active and rules are configured. There is no mention of setting the default zone

#### SCAP Security Guide Version:
scap-security-guide-0.1.36-7.el7.noarch

#### Operating System Version:
rhel-7

#### Steps to Reproduce:
As per: http://iase.disa.mil/stigs/os/unix-linux/Pages/index.aspx

U_Red_Hat_Enterprise_Linux_7_V1R4_Manual_STIG/U_Red_Hat_Enterprise_Linux_7_STIG_V1R4_Manual-xccdf.xml
STIG only requires that firewalld is active and rules are configured. There is no mention of setting the default zone

In /usr/share/xml/scap/ssg/content/.ssg-rhel7-ds.xml xccdf_org.ssgproject.content_rule_set_firewalld_default_zone
The title, description, rationale, and oval check are to set the firewall DefaultZone to drop

**Comment by dahaic** [comment]
The content you refer to is based on V1R1 which AFAIK had this "Drop" policy. (Thats just clarification). It is indeed a bug, thank you for the report.

**Comment by jan-cerny** [comment]
We try to align with the latest STIG V2R2. Is this still the case with V2R2?

**Comment by jan-cerny** [comment]
We have checked the STIG and there is no mention of the default zone to be set to drop.
