### ISSUE TITLE
is_valid_cce should check check-digit

### ISSUE THREAD

**Issue by cipherboy** [ComplianceAsCode/content#3044]
Per requirement A17 [here](http://people.redhat.com/swells/nist-scap-validation/scap-val-requirements-1.2.html), the last digit in CCE identifiers is a "check-digit". However, `is_valid_cce` [does not](https://github.com/OpenSCAP/scap-security-guide/blob/master/ssg/checks.py#L44-L53) validate these digits. 

It isn't immediately clear how to validate these check digits. Feedback is necessary before continuing.

**Comment by cipherboy** [comment]
I agree with your description of what it is currently doing.

This bug was about extending the validations to also verify the check
digit.

Just like is_valid_cce currently prevents labels like "TBD", we could have
it prevent off-by-one typos like 1234-5 vs 1234-6. See the link about
requirement A17:

 A17 N/A This is an additional, common-sense check. CCE number is in an
invalid format or the check-digit does not match. It should be of format
CCE-XXXX-X or CCE-XXXXX-X where each X is a digit, and the final X is a
check-digit.

This is something that we might need to ask NIST about. At the time I had
not seen the correct document describing the computation of the check
digit.


If this isn't desired, we can close the issue.

**Comment by mpreisler** [comment]
IMO it is desired, this would be a nice feature. I am all for keeping it open.

**Comment by redhatrises** [comment]
funny enough that is what they test for.
```
test="if(@system eq 'http://cce.mitre.org' or @system eq 'CCE') then matches(., '^CCE-\d+-\d$')
```
But maybe this is the code that you are looking for to validate the checksum?
```
test="if((@system eq 'http://cce.mitre.org' or @system eq 'CCE') and matches(., '^CCE-\d+-\d$')) 
then (sum(for $j in (for $i in reverse(string-to-codepoints(concat(substring(.,5,string-length(.)-6),substring(.,string-length(.),1))))[position() mod 2 = 0] return ($i - 48) * 2, 
for $i in reverse(string-to-codepoints(concat(substring(.,5,string-length(.)-6),substring(.,string-length(.),1))))[position() mod 2 = 1] return ($i - 48)) return ($j mod 10, $j idiv 10)) mod 10) eq 0 else true()"
```

**Comment by cipherboy** [comment]
Making @redhatrises's comment a little more readable for the future....

```
test="
if (
  (@system eq 'http://cce.mitre.org' or @system eq 'CCE')
  and
  matches(., '^CCE-\d+-\d$')
) then (
  sum (
    for $j in (
      for $i in reverse(
        string-to-codepoints(
          concat(
            substring(., 5, string-length(.)-6),
            substring(., string-length(.), 1)
          )
        )
      )[position() mod 2 = 0] return ($i - 48) * 2,
      for $i in reverse(
        string-to-codepoints(
          concat(
            substring(., 5, string-length(.)-6),
            substring(., string-length(.), 1)
          )
        )
      )[position() mod 2 = 1] return ($i - 48)
    ) return ($j mod 10, $j idiv 10)
  ) mod 10
) eq 0
else true()"
```

The logic internally is a bit more dense to parse and I haven't quite worked through all of it.

**Comment by cipherboy** [comment]
For reference based on discussion with @redhatrises:

The language in question is XPath. A hack at validation is:

```python
# concat(substr ... , substr ...) -- just remove
# non-digit characters. Since we've already validated
# format, this hack suffices:
cce = cce.replace('-', '')[3:]

# string-to-codepoints - 48 is the same as int
# Add in the reverse too. Double list cast is necessary:
# map isn't reversible, and generator isn't indexable
digits = list(reversed(list(map(int, cce))))

# Even indices are doubled. Coerce to list for list addition.
# However, XPath uses 1-indexing so "evens" and "odds"
# are swapped from Python.
evens = list(map(lambda i: i*2, digits[1::2]))
odds = digits[0::2]

# XPath generally flattens things; I'm leaving them as 
# tuples here.
tuples = map(lambda j: [j % 10, j // 10], evens + odds)
value = sum(sum(tuples, [])) % 10

# Valid CCE <=> value == 0
```

**Comment by redhatrises** [comment]
Just for future documentation, CCE is calculated with the Luhn Algorithm. See the following:

- https://cce.mitre.org/lists/entries.html
- https://csrc.nist.gov/Projects/Security-Content-Automation-Protocol/faqs
- https://en.wikipedia.org/wiki/Luhn_algorithm
