### ISSUE TITLE
Please review the nullok option in /etc/pam.d/sssd-shadow

### ISSUE THREAD

**Issue by patrickdung** [ComplianceAsCode/content#3061]
#### Description of problem:
/etc/pam.d/sssd-shadowutils specify nullok in pam

#### SCAP Security Guide Version:
scap-security-guide-0.1.38-1.fc28.noarch
openscap-scanner-1.2.16-3.fc28.x86_64

#### Operating System Version:
Fedora 28

#### Comment:
There are checking and recommendation to disable null password login.
I am not sure this file is related to login or changing password.
If it is related to login (via sssd), than it should be checked and removing nullok should be suggested.

**Comment by marcusburghardt** [comment]
I didn't find evidence that `/etc/pam.d/sssd-shadowutils` is still used. Also, the current benchmarks which requires to remove the `nullok` option intend to not allow accounts without a password defined:

https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_empty_passwords/rule.yml
