### ISSUE TITLE
Add jinja macro substitution in shared/bash_remediation_functions

### ISSUE THREAD

**Issue by iokomin** [ComplianceAsCode/content#3139]
#### Description of problem:
It is required to create fix for ol7 audit_rules_time_adjtimex rule which is expected to reuse existing rhel7 bash fix. audit_rules_time_adjtimex.sh implemented as custom scripts for rhel6 and rhel7 which just import rhel6_perform_audit_adjtimex_settimeofday_stime_remediation and rhel7_fedora_perform_audit_adjtimex_settimeofday_stime_remediation from bash_remediation_functions correspondingly. These functions use the same logic with the only one line difference for augenrules which is applicable for rhel7 only:
`>       fix_audit_syscall_rule "augenrules" "$PATTERN" "$GROUP" "$ARCH" "$FULL_RULE"`

To avoid custom audit_rules_time_adjtimex.sh cloning it sounds reasonable to utilize augenrules line conditionally depending on platform, merge to functions in one and move audit_rules_time_adjtimex.sh to shared/fixes/bash. Unfortunately current SSG version doesn't support macro substitution for files from bash_remediation_functions to implement following logic:
`{{%- if product == "rhel7" -%}}
fix_audit_syscall_rule "augenrules" "$PATTERN" "$GROUP" "$ARCH" "$FULL_RULE"
{{%- endif -%}}`

Suggested to add this functionality.

#### SCAP Security Guide Version:
v0.1.39

#### Operating System Version:
OL7, RHEL7, RHEL6

#### Steps to Reproduce:

1. Review  rhel6_perform_audit_adjtimex_settimeofday_stime_remediation.sh, rhel7_fedora_perform_audit_adjtimex_settimeofday_stime_remediation.sh and audit_rules_time_adjtimex.sh content and usage
2.
3.
4.

#### Actual Results:
each platform has it's own audit_rules_time_adjtimex.sh fix script implementation 

#### Expected Results:
all platforms use shared fix

**Comment by redhatrises** [comment]
@iokomin are you saying the Oracle Linux 7 does not have or use augenrules?

**Comment by iokomin** [comment]
@redhatrises OL7 fix is the same as RHEL7 has. Suggested snippet provided just for requested macro usage example in case of rhel6 and rhel7 merge. Taking into account OL7 product this condition will be _"if product in ["ol7", "rhel7"]"_.

**Comment by cipherboy** [comment]
@iokomin Tell me if I didn't understand something. :)

@redhatrises To clarify, I think what the original issue by @iokomin mentioned was just about merging `rhel6` and `rhel7`; `rhel6` doesn't seem to have `augenrules`. So the difference between:
 - `./shared/bash_remediation_functions/rhel6_perform_audit_adjtimex_settimeofday_stime_remediation.sh`
 - `./shared/bash_remediation_functions/rhel7_fedora_perform_audit_adjtimex_settimeofday_stime_remediation.sh`

Is one content line: 

```bash
diff ./shared/bash_remediation_functions/rhel7_fedora_perform_audit_adjtimex_settimeofday_stime_remediation.sh ./shared/bash_remediation_functions/rhel6_perform_audit_adjtimex_settimeofday_stime_remediation.sh
4,5c4,5
< # system calls on Red Hat Enterprise Linux 7 or Fedora OSes
< function rhel7_fedora_perform_audit_adjtimex_settimeofday_stime_remediation {
---
> # system calls on Red Hat Enterprise Linux 6 OS
> function rhel6_perform_audit_adjtimex_settimeofday_stime_remediation {
12d11
< 
28c27
< 	# Perform the remediation for both possible tools: 'auditctl' and 'augenrules'
---
> 	# Perform the remediation itself
30d28
< 	fix_audit_syscall_rule "augenrules" "$PATTERN" "$GROUP" "$ARCH" "$FULL_RULE"
```

So we could collapse those two by a `jinja` macro and update it to one shared one:

```
{{% if product != 'rhel6' %}}
fix_audit_syscall_rule "augenrules" "$PATTERN" "$GROUP" "$ARCH" "$FULL_RULE"
{{% endif %}}
```

(@iokomin ^ I think this is the correct conditional, as `fedora` should also have augenrules.)

It appears @iokomin wishes to simplify the logic of `rhel6`/`rhel7` handling, so that adding `ol7` is easy and can just be "use the new common file `perform_audit_adjtimex_settimeofday_stime_remediation.sh`", because it _does_ use `augenrules`. Otherwise, he'd have to rename `rhel7_fedora_perform_audit_adjtimex_settimeofday_stime_remediation.sh` -> `rhel7_fedora_ol7_perform_audit_adjtimex_settimeofday_stime_remediation.sh`, and update the references and the function and the comments, which is about as much work as removing the rhel6 specific one and adding a jinja macro. Plus, this makes SSG better. :)

**Comment by redhatrises** [comment]
> `rhel6` doesn't seem to have `augenrules`

This is not true at all. `rhel6` does have augenrules. So, the change requested here still doesn't make sense.

**Comment by cipherboy** [comment]
@redhatrises Then shouldn't we do the even simpler fix and remove the `rhel6` one and rename the `rhel7` one to be a shared one? Why doesn't the `rhel6` have augenrules in the remediation?

**Comment by redhatrises** [comment]
@cipherboy probably because it wasn't in the initial `rhel6` releases. I haven't been following the unshadowing of audit rules. Pro

**Comment by matejak** [comment]
@redhatrises This issue is mainly about adding jinja capabilities to shared remediation functions. The use case that motivated this may be resolved using other means, but the ability to use jinja in shared remediations may be useful for another use cases.

**Comment by redhatrises** [comment]
Thanks @matejak. So to some degree... dup of #2811

**Comment by iokomin** [comment]
@cipherboy You are right about simplification. Suggested condition (just in rhel7 and ol7) proposed based on existing fix content which is different for rhel6 and rhel7. It should be noticed fedora wasn't in the supported platforms list while mentioned in rhel7_fedora_perform* function name. In case augenrules supported on all mentioned platforms merge existing files into one common perform_audit_adjtimex_settimeofday_stime_remediation.sh looks reasonable for me. 
Note: Unfortunately I don't have neither rhel* nor fedora on hand to verify new changes, thus to be sure nothing is broken trying to modify existing content only adding ol7 where needed.

@matejak, @redhatrises I agree, this case could be considered as a dup of #2811.

@redhatrises Speaking about audit rules from my side I could propose PR to merge existing rules into shared perform_audit_adjtimex_settimeofday_stime_remediation.sh with augenrules applied for all platforms including rhel6 and fedora. Unfortunately testing will be performed on OL7 only. Changes are minor and looks obvious, should work on other platforms as well. Please let me know if it works for you.

**Comment by matejak** [comment]
@iokomin I have checked now and I have to say that jinja works even for shared bash remediation functions. The best way to check for it is to see the remediation in the HTML guide, or to take a look at the `build/<target>/bash-fixes.xml`.
I won't close this issue as you seem to be solving another problem. I am not sure about the issue title though.

**Comment by iokomin** [comment]
@matejak Could you please have a look at dev branch https://github.com/iokomin/scap-security-guide/tree/jinja2_bash_remediation_functions ?

Bash fix for audit_rules_time_adjtimex generation returns original jinja macro:
` 
$ profile=pci-dss; oscap xccdf eval --results=profile_$profile.result.xml --check-engine-results --oval-results --report=profile_$profile.result.html --profile=$profile ssg-ol7-xccdf.xml
$ oscap xccdf generate fix --profile pci-dss profile_pci-dss.result.xml > fix.sh
$ cat fix.sh
--cut
        # Perform the remediation for both possible tools: 'auditctl' and 'augenrules'
        fix_audit_syscall_rule "auditctl" "$PATTERN" "$GROUP" "$ARCH" "$FULL_RULE"
    {{% if product == "rhel7" %}}
        fix_audit_syscall_rule "augenrules" "$PATTERN" "$GROUP" "$ARCH" "$FULL_RULE"
    {{% endif %}}
done

}

perform_audit_adjtimex_settimeofday_stime_remediation
# END fix for 'audit_rules_time_adjtimex'
`
Am I misusing anything?

**Comment by redhatrises** [comment]
@iokomin the change to evaluate the product is incorrect. It needs to handle if auditctl or augenrules is used like `perform_audit_rules_privileged_commands_remediation.sh`

**Comment by iokomin** [comment]
@redhatrises I didn't have any intention to change existing logic, thus suggested change was just a result of merge of two existing scripts without logic change to make it more 'shared' :) 

jinja2_bash_remediation_functions branch was created just as a test example for @matejak to check if jinja macro works in bash remediation functions - despite claimed to work it didn't for me for some reason. Would be thankful if anyone would take a look and explain if macro is incorrect here.

As suggested above to distinct two separate problems let's consider this issue as a dup of #2811 and discuss perform_audit_adjtimex_settimeofday_stime_remediation logic in a separate PR. This one can be closed as reported macro issue commented.

Note on previous comment:
I should notice though auditctl or augenrules handling logic implemented in imported fix_audit_syscall_rule function in the same way it is done in suggested perform_audit_rules_privileged_commands_remediation.sh, thus I don't see much difference here. 
In fact in case of perform_audit_rules_privileged_commands_remediation both tools called as well but just on fix script level, see  ./rhel7/fixes/bash/audit_rules_privileged_commands.sh.
And finally, reading auditctl and augenrules docs it looks reasonable for me to use them both in rhel7 and rhel6 as well as rhel6 supports augenrules.

**Comment by matejak** [comment]
@iokomin Excuse me, I have tried again with your branch, and I take it back - content in `bash-fixes.xml` is not relevant.

**Comment by redhatrises** [comment]
The two scripts have been merged. Jinja enhancements to bash remediation functions is being tracked in #2811. Closing.
