### ISSUE TITLE
RHEL-07-010010: SSG rule description insufficient

### ISSUE THREAD

**Issue by dclee27** [ComplianceAsCode/content#3148]
#### Description of problem:

SSG is missing the step to reset user and group ownership.

#### SCAP Security Guide Version:

SSG(20180718)

#### Expected Results:

Add the following (or similar) to the end of the description

Reset the user and group ownership of files within a package with the following command:

#rpm --setugids <packagename>

**Comment by redhatrises** [comment]
This is broken out into a separate rule `rpm_verify_ownership` per NIST CCE and NCP. `--setperms` and `--setugids` should not be in the same rule and should be broken out.

**Comment by dclee27** [comment]
Thanks for the explanation. 
Is `rpm_verify_ownership` scheduled to be brought into the RHEL7 SSG? I noticed that the DoD STIG has them together and that `rpm_verify_ownership` is a `TBD` for RHEL7.

**Comment by redhatrises** [comment]
This has been fixed upstream.
