### ISSUE TITLE
Some RHEL6 rules unexpectedly don't have STIG IDs

### ISSUE THREAD

**Issue by matejak** [ComplianceAsCode/content#3167]
RHEL6 rules s.a.
* `ldap_client_start_tls`
* `ldap_client_tls_cacertpath`
* `audit_rules_time_adjtimex`

are reported by the `profile-stats` script to not have all the STIG ID references in RHEL6 XCCDF file. For instance, `ldap_client_start_tls` has
```
<reference href="http://iase.disa.mil/stigs/os/unix-linux/Pages/index.aspx">RHEL-06-000252</reference>
```
but misses reference with `href="http://iase.disa.mil/stigs/Pages/stig-viewing-guidance.aspx"` that is denoted as `stig_ns` in `constants.py`.

For example, rule `package_openldap-servers_removed` contains both STIG ID-related references: 
```
<reference href="http://iase.disa.mil/stigs/os/unix-linux/Pages/index.aspx">RHEL-06-000256</reference>
<reference href="http://iase.disa.mil/stigs/Pages/stig-viewing-guidance.aspx">SV-50428r2_rule</reference>
```

The `ldap_client_start_tls` rule definition clearly shows the intention to specify the STIG ID, as it contains
```
references:
    stigid@rhel6: RHEL-06-000252
```
so it is surprising that it is reported as ID-less. Is this expected due to some other circumstances beyond our control, or is it a bug?

**Comment by ggbecker** [comment]
Those are rules that got removed from the STIG benchmark

`ldap_client_start_tls`
`ldap_client_tls_cacertpath`
```
V1R13
- Removed V-38625, V-38626.
28 October 2016
```

`audit_rules_time_adjtimex`
```
V1R16 - Removed V-38635 - Removed the requirement
as there is not an adjtimex in hwclock, and it has
not been replaced with another command.
28 July 2017
```

So when the [`add_stig_references.py`](https://github.com/ComplianceAsCode/content/blob/master/cmake/SSGCommon.cmake#L161) is executed, it can't find the references in the benchmark and that won't produce any reference in the xccdf generated for these rules that are not present in the STIG benchmark anymore.

The question is, should we remove STIG id from the references section when an item is removed from the STIG benchmark?

**Comment by Mab879** [comment]
Closing this issue out due to RHEL6 EOL. We can open a new issue for the removal of STIG IDs if needed.
