### ISSUE TITLE
xinet.d / systemctl overlap

### ISSUE THREAD

**Issue by cipherboy** [ComplianceAsCode/content#3174]
As noticed by @redhatrises in #3156, some rules (such as `rsh`, `rlogin`, and `telnet`) describe both disabling via `xinet.d` and `systemctl`. We should split these rules and ensure that each one has a unique CCE.

**Comment by matejak** [comment]
Just for reference - those rules mainly dwell under `linux_os/guide/services/obsolete`, so maybe the solution is to get rid of them rather to spend time with them?

**Comment by cipherboy** [comment]
That's fair I think. Obviously @redhatrises or @shawndwells are better people to ask if we can remove the `rsh` & friends rules... But if not, we could just remove references to `xinet.d` and only have `systemctl` instructions.

**Comment by shawndwells** [comment]
If the rules are selected in a profile they should be addressed/updated.

**Comment by matejak** [comment]
I confirm that they are included in wide range of profiles, so just getting rid of them is not an option.

**Comment by marcusburghardt** [comment]
The current `prodtype` list of the mentioned rules are only using products with systemd, where xinetd is no longer applicable in these cases. Also, these rules uses the same template, which properly checks and remediates the systems.

So, this issue is obsolete. I am closing it.
