### ISSUE TITLE
rsyslog log ownership validate

### ISSUE THREAD

**Issue by cipherboy** [ComplianceAsCode/content#3181]
We need to check our rsyslog log ownership rules (group and unix user owner) and validate that they are correct for all arches. I'm thinking Debian-like are wrong on the Unix user owner. #3126 appears to fix the group ownership on these platforms.

**Comment by marcusburghardt** [comment]
#9789

**Comment by marcusburghardt** [comment]
The `rsyslog_files_ownership` and `rsyslog_files_groupownership` seems to be already correct. If any change is needed for specific distro, it is pretty straightforward to update after #9789
