### ISSUE TITLE
xccdf_org.ssgproject.content_rule_audit_rules_kernel_module_loading Result  fail even with latest rules and both entries in /etc/audit/audit.rules

### ISSUE THREAD

**Issue by rshade** [ComplianceAsCode/content#3210]
#### Description of problem:
On CentOS Linux release 7.5.1804 (Core), with openscap-1.2.17-1.el7 with scap-security-guide built from master as well as scap-security-guide-0.1.40-2.el7 I still get a failure on auditd rules. 

`oscap xccdf eval --fetch-remote-resources --profile standard --results-arf arf.xml --report report.html /usr/share/xml/scap/ssg/content/ssg-centos7-ds.xml`

```
Title   Ensure auditd Collects Information on Kernel Module Loading and Unloading
Rule    xccdf_org.ssgproject.content_rule_audit_rules_kernel_module_loading
Result  fail
```

```
 grep modules /etc/audit/audit.rules
-a always,exit -F arch=b32 -S init_module -S delete_module -k modules
-a always,exit -F arch=b64 -S init_module -S delete_module -k modules
-w /usr/sbin/insmod -p x -k modules
-w /usr/sbin/rmmod -p x -k modules
-w /usr/sbin/modprobe -p x -k modules
```
#### SCAP Security Guide Version:
scap-security-guide-0.1.40-2.el7 & master

#### Operating System Version:
CentOS Linux release 7.5.1804

#### Steps to Reproduce:

1. Add repo: 
```
[openscapmaint-openscap-latest]
name=Copr repo for openscap-latest owned by openscapmaint
baseurl=https://copr-be.cloud.fedoraproject.org/results/openscapmaint/openscap-latest/epel-7-$basearch/
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/openscapmaint/openscap-latest/pubkey.gpg
repo_gpgcheck=0
enabled=1
```
2. install scanner, and scap-security-guide
3. oscap xccdf eval --fetch-remote-resources --profile standard --results-arf arf.xml --report report.html /usr/share/xml/scap/ssg/content/ssg-centos7-ds.xml
4.

#### Actual Results:
Failure

#### Expected Results:
Everything to pass, this is the last rule to fix.

**Comment by yuumasato** [comment]
Hello, thank you for filing this.

First, please make sure that auditd is configured to use `auditctl`. If not, either switch to `auditctl` or move the rules to `/etc/audit/rules.d/`.
Second, the rule is also checking for `finit_module` and `create_module` syscalls, please add them to your rules file. The description on the rule is misleading and a fix has already been proposed.

**Comment by rshade** [comment]
@yuumasato thank you so much for the help. They were already present in modules.rules from a `remediate` call. I updated /etc/audit/rules.d/modules.rules with your suggestions, and I am now compliant:
`
 cat /etc/audit/rules.d/modules.rules
-a always,exit -F arch=b32 -S create_module -S finit_module -S init_module -S delete_module -k modules
-a always,exit -F arch=b64 -S create_module -S finit_module -S init_module -S delete_module -k modules
-w /usr/sbin/insmod -p x -k modules
-w /usr/sbin/rmmod -p x -k modules
-w /usr/sbin/modprobe -p x -k modules
`
Thank you for your help.

**Comment by rshade** [comment]
I would say autoclose this with #3213

**Comment by redhatrises** [comment]
#3213 has been merged. Closing.
