### ISSUE TITLE
Remove leftovers from shared/checks/oval

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#3245]
#### Description of problem:

We have moved everything under linux_os directory. However, there is still a bunch of files in shared/checks/oval directory.

I think it will be really confusing for a newcomer if  they will see this directory. Then it will not be clear for them where they should contribute their OVALs.

These files should be removed or reduplicated.

#### SCAP Security Guide Version:
current master, as of 3rd September 2018

#### Operating System Version:
all

#### Steps to Reproduce:

1. cd shared/checks/oval
2. ls
3.
4.

#### Actual Results:
Many files are in shared/checks/oval

#### Expected Results:
No files are in shared/checks/oval or only meaningful files are in shared/checks/oval

**Comment by cipherboy** [comment]
These should also be audited in the product checks directory `<product>/checks/oval`, as I do recall a few not being moved.
