### ISSUE TITLE
Developer Guide doesn't fully reflect the latest structural changes

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#3246]
#### Description of problem:
I have read SCAP Security Guide Developer Guide https://github.com/OpenSCAP/scap-security-guide/blob/master/docs/manual/developer_guide.adoc . I think that certain parts are outdated or no longer applicable, because recently some structural changes have been done.

For example
* "Important Top Level Directory Descriptions" table doesn't describe linux_os
* 5.1.2. Product Structure/Layout is outdated 
* Directory stucture at the beginning of Section 8 Contributing with XCCDFs, OVALs and remediations doesn't contain linux_os
* formatting is broken at some places

It will be needed to review and update the text completely.

#### SCAP Security Guide Version:
current upstream master as of 3rd September 2018

#### Operating System Version:
all

#### Steps to Reproduce:

1. read SCAP Security Guide Developer Guide
2.
3.
4.

#### Actual Results:
SCAP Security Guide Developer Guide contains outdated information.

#### Expected Results:
SCAP Security Guide Developer Guide is fully updated and reflects the latest structural changes.

**Comment by matejak** [comment]
This is, in a way, a good issue for people starting with the project, as they are ones the most likely to bump into this issue.
