### ISSUE TITLE
Add Security Policies for Ubuntu 18.04.1 LTS (Bionic Beaver)

### ISSUE THREAD

**Issue by maxverro** [ComplianceAsCode/content#3291]
Add security policies in the SCAP Security Guide for Ubuntu 18.04.1 LTS (Bionic Beaver). It seems that none exists yet on the open-scap web site.

https://www.open-scap.org/security-policies/choosing-policy/

http://releases.ubuntu.com/18.04/

**Comment by redhatrises** [comment]
@MaxVerro if you can contribute this content, that would be great! Otherwise, our cycles are limited to begin to contribute this content.

**Comment by iacopo-papalini** [comment]
The content in the ubuntu1804 directory seems to (almost) work.
I was able to run many tests out of the box (keeping in mind this bug: https://github.com/ComplianceAsCode/content/issues/2421).

However I found out that many tests are 'notapplicable' - specifically all the tests with `platform: machine`.
The file `content/ubuntu1804/cpe/ubuntu1804-cpe-dictionary.xml` is missing the `<cpe-item name="cpe:/a:machine">` section that is present, for example, in the Red Hat equivalent file.

By copying the definition from the and building again, I got almost all the controls either failed or passed (no `notapplicable` control). Unfortunately the command raises a lot of warnings, even if the report is successfully built:
`No definition with ID: oval:ssg-installed_OS_is_ubuntu1804`
`        :def:1 in definition model. [../../../../src/OVAL/results/oval_resultSystem.c:375]`

I'm ignorant enough to not submit a pull request until I have figured out if the message is a true error or a false one.
Hope this helps.

**Comment by jwieren** [comment]
@iacopo-papalini - Are you able to provide the final `ubuntu1804-cpe-dictionary.xml` you used?

Thanks,
Jono

**Comment by iacopo-papalini** [comment]
@jwieren it's in my fork - https://github.com/iacopo-papalini/content/blob/master/ubuntu1804/cpe/ubuntu1804-cpe-dictionary.xml
By the way, by building from scratch in another machine I didn't experience the errors anymore.

**Comment by shaharglazner** [comment]
@redhatrises 
Hey,
I want to generate the `stig_overlay.xml` for Ubuntu 18.04 using [the documentation](https://github.com/ComplianceAsCode/content/blob/master/docs/manual/developer_guide.adoc#5-updating-reference-and-overlay-content), does it make sense? 

Any other things to notice before?

**Comment by redhatrises** [comment]
@shaharglazner it actually does not make sense to generate the stig overlay using the Red Hat STIG. You should use the Ubuntu STIG to generate the overlay.

**Comment by shaharglazner** [comment]
@redhatrises 
Actually, that's what I meant. Sorry if I was misunderstood.

**Comment by willumpie** [comment]
Hi, Like to join this project to update the ubuntu 18.04 content

**Comment by redhatrises** [comment]
@willumpie please feel free to starting adding content!

**Comment by willumpie** [comment]
Hi, I forked the content repo, and busy adding the tests for the Ubuntu  18.04 CIS profile.

**Comment by willumpie** [comment]
First part is in review: https://github.com/ComplianceAsCode/content/pull/5722

**Comment by ondrj** [comment]
It would be nice-to-have as 20.04 is already out :) Great job @willumpie , thank you.

**Comment by willumpie** [comment]
@Ondrj: 
As far as I can see, there is at the moment not a 20.04 LTS benchmark available.
If there is one available, please let me know. I will check if I can add them.

At the moment I have added the CIS Ubuntu 18.04 LTS v.1.0.0 profile, but now see there is a new version available... Now downloading it. 

btw: a lot of rules are not enabled or linked to the cis profile. feel free to add them.

**Comment by Mab879** [comment]
@dodys @richardmaciel-canonical just wanted check with you two on this issue and see if you wanted to add anything else. We have some 1804 and 2004 in the repo now.

**Comment by dodys** [comment]
@Mab879 we don't have anything else for 18.04 right now. We might come with some stuff in the future but I believe you can close this ticket and new ones can be opened if needed.
