### ISSUE TITLE
Split chrony and ntp

### ISSUE THREAD

**Issue by redhatrises** [ComplianceAsCode/content#3315]
Much like the dconf rules and checks, we need and should split the chronyd and ntpd into separate rules and checks for NIST CCE in addition to make the rules clear as well as ntp's deprecation.

**Comment by linuxdan** [comment]
FWIW:  I found that I had to keep using NTP on RHEL 7 due to IdM/free-ipa's dependency on it.

**Comment by redhatrises** [comment]
Thanks @linuxdan. IdM is changing this.

**Comment by Mab879** [comment]
These rules appear to split now. Thank you!
