### ISSUE TITLE
Checks for Ubuntu 18.04 LTS, when available? Any workaround? Any tips?

### ISSUE THREAD

**Issue by SleepyLctl** [ComplianceAsCode/content#3323]
Hello,

#### Description of problem:
I want to set up a security baseline for Ubuntu 18.04 LTS. Unfortunately, there are no .xml checks available. What are the options?

#### Operating System Version:
Ubuntu 18.04 LTS

#### Actual Results:
The tests for Ubuntu 16 does not work

#### Expected Results:
Compliance check for Ubuntu 18.04 LTS - best-practice, CIS, NIS whatever. Just something to start with. Is there any way how to modify checks for Ubuntu 16?

#### Addition Information/Debugging Steps:
I would like to have ANY kind of check for Ubuntu 18.04 LTS so I can set SOME security baseline. However seems nothing exists?

**Comment by matusmarhefka** [comment]
Hello,

I think you can start with the standard profile from [ubuntu1604](https://github.com/ComplianceAsCode/content/tree/master/ubuntu1604) product and port it to 18.04 release. We would appreciate your help :)

In `selections` section you can see all the rules which are selected for the profile. If you want to see how the specific rule looks like (for example rule `sshd_disable_root_login`):
```
$ find ./ -name sshd_disable_root_login
./linux_os/guide/services/ssh/ssh_server/sshd_disable_root_login
```
For more details see our [developer guide](https://github.com/ComplianceAsCode/content/blob/master/docs/manual/developer_guide.adoc). I think you will be interested in the section 8. Contributing with XCCDFs, OVALs and remediations. For creating a new product (ubuntu1804) you can get inspired by our [example](https://github.com/ComplianceAsCode/content/tree/master/example) product or by the already existing [ubuntu1604](https://github.com/ComplianceAsCode/content/tree/master/ubuntu1604) product.

In case you have more questions feel free to ask.

**Comment by xhudik** [comment]
Hi, I'm about to create ubuntu1804 profile: https://github.com/xhudik/content/pull/1
based on Ubuntu1604. While `cmake` works fine, build (`make`) generates errror:
`OpenSCAP Error: Unable to open file: Error: Can't locate "installed_OS_is_ubuntu1804" definition in "/home/me/sources/SCAP_SecurityGuide/build/ubuntu1804/oval-unlinked.xml`

Any idea?

**Comment by mpreisler** [comment]
@xhudik You need to add the file here: https://github.com/ComplianceAsCode/content/tree/master/shared/checks/oval

It will most likely be very similar to the ubuntu1604 version. The purpose of this file is to figure out whether the OS being scanned is ubuntu 18.04, this is necessary for CPEs (platform detection) and other rules.

Hope this helps!

**Comment by xhudik** [comment]
then I do have many warnings like:
```
WARNING: OVAL definition 'service_systemd-timesyncd_enabled' extends non-existing 'package_systemd_installed', removing it from OVAL definitions.
WARNING: OVAL check 'postfix_client_configure_mail_alias' was not found, removing <check-content> element from the XCCDF rule.
...
```

Is it ok, or it should be fixed somehow?

**Comment by xhudik** [comment]
guys, this can be closed (implemented in https://github.com/ComplianceAsCode/content/pull/3340), thx

**Comment by jan-cerny** [comment]
@xhudik Basically the warning is there because some of the OVAL checks are marked they are just for RHEL, even if they would be technically suitable for Ubuntu, as I already mentioned in my last comment in https://github.com/ComplianceAsCode/content/pull/3340

**Comment by jan-cerny** [comment]
@xhudik try to run this to figure out which rules are missing checks.

```
. .pyenv.sh
python build-scripts/profile_stats.py --profile standard --benchmark build/ssg-ubuntu1804-xccdf.xml --all
````

**Comment by redhatrises** [comment]
Closing per https://github.com/ComplianceAsCode/content/issues/3323#issuecomment-423074896
