### ISSUE TITLE
Lack of = sign in /etc/audit/auditd.conf breaks  auditd

### ISSUE THREAD

**Issue by cmattern-rht** [ComplianceAsCode/content#3325]
#### Description of problem:
YAML syntax in ansible-rhel7-pci-dss-role/tasks/main.yml at 518 and 577 make modifications to
/etc/audit/auditd.conf which lack the required = sign and, in the case of max_log_file, create multiple,
potentially inconsistent instances of the setting.

#### SCAP Security Guide Version:
Master v0.1.40

#### Operating System Version:
RHEL 7.5

#### Steps to Reproduce:

1. ansible-playbook  -i "finsrv01.mobile.roninprinciples.com," playbook.yml
2. kill auditd and then start or reboot the server
3. auditd will not start 

#### Actual Results:

 journalctl -xe will reveal:
```
-- Subject: Unit auditd.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit auditd.service has begun starting up.
Sep 15 19:44:05 finsrv01.mobile.roninprinciples.com auditd[8661]: Missing equal sign for line 37 in /etc/audit/auditd.conf
Sep 15 19:44:05 finsrv01.mobile.roninprinciples.com auditd[8661]: Not processing any more lines in /etc/audit/auditd.conf
Sep 15 19:44:05 finsrv01.mobile.roninprinciples.com auditd[8661]: The audit daemon is exiting.
Sep 15 19:44:05 finsrv01.mobile.roninprinciples.com kernel: type=1130 audit(1537040645.354:235480): pid=1 uid=0 auid=4294967295 ses=
Sep 15 19:44:05 finsrv01.mobile.roninprinciples.com systemd[1]: auditd.service: control process exited, code=exited status=6
Sep 15 19:44:05 finsrv01.mobile.roninprinciples.com systemd[1]: Failed to start Security Auditing Service.
-- Subject: Unit auditd.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit auditd.service has failed.
-- 
-- The result is failed.
```
#### Expected Results:

auditd would start successfully and begin using updated parameters

#### Addition Information/Debugging Steps:

EDIT by @mpreisler: formatting

**Comment by redhatrises** [comment]
This should be fixed now. Closing.
