### ISSUE TITLE
documentation is outdated for profile directory structure

### ISSUE THREAD

**Issue by xhudik** [ComplianceAsCode/content#3339]
#### Description of problem:
https://github.com/ComplianceAsCode/content/blob/master/docs/manual/developer_guide.adoc
states that each profile should have structure with required dirs, e.g
```
$ tree -d rhel7

rhel7
├── checks
│   └── oval
├── cpe
├── fixes
│   ├── ansible
│   └── bash
├── kickstart
├── overlays
├── profiles
├── templates
│   ├── csv
├── transforms
└── utils

13 directories
```
in fact in reality, it miss many required (e.g. `cheks`, `fixes`) dirs and it looks like:
```
tree -d rhel7/
rhel7/
├── cpe
├── kickstart
├── overlays
├── profiles
├── templates
│   └── csv
└── transforms

7 directories
```

#### Steps to Reproduce:

1. clone github 
2. run `tree -d rhel7/`

**Comment by jan-cerny** [comment]
@xhudik Yes, nice observation, the documentation is outdated and I believe we need to fix it.
If you encounter anything that's wrong in the docs, feel free to send us a pull request :smile: 

The reason why some directories are missing is that most of the checks and fixes have been moved under `linux_os` directory. The reason for that move was that most of the stuff is applicable to all Linux distributions. Having the files at single place prevents us from copying files over and over. The differences between the Linux distributions are handled by macros.
