### ISSUE TITLE
STIG AMBIGUITY - RHEL-07-040720 - If the Trivial File Transfer Protocol (TFTP) server is required, the TFTP daemon must be configured for secure mode

### ISSUE THREAD

**Issue by linuxdan** [ComplianceAsCode/content#3344]
#### Description of problem:
STIG says:
Check Text: Verify the TFTP daemon is configured to operate in secure mode.
Check to see if a TFTP server has been installed with the following commands:

yum list installed | grep tftp-server

tftp-server.x86_64 x.x-x.el7 rhel-7-server-rpms

If a TFTP server is not installed, this is Not Applicable.
If a TFTP server is installed, check for the server arguments with the following command: 

grep server_arge /etc/xinetd.d/tftp  

server_args = -s /var/lib/tftpboot

If the "server_args" line does not have a "-s" option and a subdirectory is not assigned, this is a finding.
Fix Text: Configure the TFTP daemon to operate in secure mode by adding the following line to "/etc/xinetd.d/tftp" (or modify the line to have the required value):
server_args = -s /var/lib/tftpboot

For Red Hat Satellite, that line in that file is 
server_args     = -v -s /var/lib/tftpboot -m /etc/tftpd.map

Tenable, in their infinite brainlessness, fail that because it is not an exact match

The file itself cannot be permanently changed because it is hard-coded thru Puppet and Forman and goodness-knows-what-else.

Other than fixing the typo in the grep line, the wording needs to change to permit variations.
Maybe saying something like "server_args = [other options] -s /var/lib/tftpboot [more options]"
I am shooting from the hip/in the dark on this.

#### STIG Version:
Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018

**Comment by trevor-vaughan** [comment]
@linuxdan I think that the text is perfectly clear.

If using `tftpd`, you must have a `-s <directory>` entry in the options string.

If Tenable is triggering this as a finding, then that is a bug in their software, not the prose text.

**Comment by linuxdan** [comment]
They say that they are doing exactly what the STIG tells them to do. 
Which, to them, means exactly matching what the STIG says should be returned from the Greg command. 
Tenable won’t budge, so I am approaching the issue from the other end.

**Comment by shawndwells** [comment]
I think there's a legitimate bug in the SSG content over this.

While the XCCDF says ``-s`` should be an option, the OVAL is looking for an exact match:
https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/services/obsolete/tftp/tftpd_uses_secure_mode/oval/shared.xml#L20

`````
  <ind:textfilecontent54_object id="object_tftpd_uses_secure_mode" version="1">
    <ind:filepath>/etc/xinetd.d/tftp</ind:filepath>
    <ind:pattern operation="pattern match">^[\s]*server_args[\s]+=[\s]+\-s[\s]+.+$</ind:pattern>
    <ind:instance datatype="int">1</ind:instance>
  </ind:textfilecontent54_object>
`````

**Comment by shawndwells** [comment]
@linuxdan would you be interested in creating the PR to update the regex? Happy to work with you on creating a patch!

**Comment by linuxdan** [comment]
Sure

**Comment by linuxdan** [comment]
Like I said above, how would we do “server_args = [other options] -s /var/lib/tftpboot [more options]"
I do not understand the OVAL regex

**Comment by redhatrises** [comment]
setting the line below should work:

```
^[\s]*server_args[\s]+=.*[\s]+\-s[\s]+.+$
```

**Comment by linuxdan** [comment]
Is this it ?
https://oval.mitre.org/language/about/re_support_5.6.html

**Comment by shawndwells** [comment]
@linuxdan yes, that's it. basically anything that would work in ``sed`` will work

**Comment by shawndwells** [comment]
i use https://regex101.com/ to test my regex for OVAL

**Comment by shawndwells** [comment]
and yes, @redhatrises , that appears to be the regex we need 👍

**Comment by linuxdan** [comment]
OK
I will work on it and get back to you all.

**Comment by shawndwells** [comment]
@linuxdan how can we help with your PR? Docs on creating a PR can be found here:
https://github.com/ComplianceAsCode/content/blob/master/docs/manual/developer_guide.adoc#patch-creation

**Comment by linuxdan** [comment]
^[\s]*server_args[\s]+=[\s]+\-s[\s]+.+$
^[\s]*server_args[\s]+=.*[\s]+\-s[\s]+.+$

Ah-ha !  A small but strategic addition !
I had to get them together to see it.
Many thanks, @redhatrises

**Comment by redhatrises** [comment]
yeah. No problem @linuxdan

**Comment by linuxdan** [comment]
@shawndwells 
Just give me time to work it. Would you believe this is my first contribution for which I am doing the PR ?

**Comment by shawndwells** [comment]
That's awesome! There's been lots of code structure changes lately which means some docs might be out of date. Let us know if something isn't documented well/unclear/confusing and we'll help out.

**Comment by linuxdan** [comment]
OK, I used the UI approach and made the fork and inserted the change and followed thru with thee pull request.

How's it look ?

**Comment by shawndwells** [comment]
Looked great, and merged! 

Note this will fix upstream SSG/ComplianceAsCode content. 3rd parties, e.g. Tenable, will still have to update their compliance engines. They may need to be tipped off as well.
