### ISSUE TITLE
FIPS evaluations incomplete - lacking  /proc/sys/crypto/fips_enabled

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#3516]
Current fips checks only evaluate FIPS=1 in kernel.

They should be evaluating /etc/system-fips and /proc/sys/crypto/fips_enabled

(thanks to Tomas Mraz and Steve Grubb for pointing this out!)

**Comment by yuumasato** [comment]
New `enable_fips_mode` rule from #3623 addresses check of `/etc/system-fips`.
Its remediation (`fips-mode-setup --enable`) will enable FIPS, and thus `/proc/sys/crypto/fips_enabled` will be set, but the rule doesn't check for it.

**Comment by redhatrises** [comment]
@shawndwells with the new fips rules, and new way to enable fips, I don't think that we need to check this anymore, do you agree?

**Comment by shawndwells** [comment]
@redhatrises https://github.com/ComplianceAsCode/content/pull/3623 was for RHEL8.... what about RHEL7?

**Comment by jan-cerny** [comment]
The rule enable_fips_mode already depends on a check of `/proc/sys/crypto/fips_enabled`.

https://github.com/ComplianceAsCode/content/blob/3f665429d76cc76e7f3eb9e4bebcd822c992c04f/linux_os/guide/system/software/integrity/fips/enable_fips_mode/oval/shared.xml#L14

We have fixed it in #3623

**Comment by yuumasato** [comment]
@jan-cerny Well observed, RHEL8 should be fine.
But the rule for rhel7 doesn't check sysctl`crypto.fips_enabled`.

**Comment by Mab879** [comment]
RHEL 7 has been removed from the project. See #12093 for more details.

Closing since RHEL7 has been removed from the project.
