### ISSUE TITLE
Passing custom rule from v0.1.39 to v0.1.41

### ISSUE THREAD

**Issue by TomberryToby** [ComplianceAsCode/content#3537]
#### Description of problem:
I am trying to tranfer some rules/checks that where made in SSG v0.1.39 to the new version of SSG v0.1.41.
I undestrand that the name and location of all these files need to be changed and maybe some text inside the file. But can you explain how ?

I try to copy a simple rule named package_ntp_removed.rule/xml, rename the rule file, oval and change the location as below. 
├── package_ntp_removed
│   ├── oval
│   │   └── shared.xml
│   └── rule.yml
└── group.yml

At first I had an error because the rule.yml needed some change inside (ocil line < > transform to `<pre> </pre>`).
I use Scap Workench to scan and look at result.
Than a had an error because the workbench say it couldn't find the oval even though the file was at the correct location.

Could you help me ?

#### SCAP Security Guide Version:
Old version v0.1.39  - file
New version V0.1.41 -system

#### Operating System Version:
CentOS Linux release 7.5.1804 (Core) 

#### Steps to Reproduce:

1. Explain how to create a new rule and oval in v0.1.41
2. What is the difference with the v0.1.39 ?

#### Actual Results:
Error while trying the command make -j4 in the build folder or scan saying rule "notchecked"

#### Expected Results:
Scan working and result similare to those of v0.1.39

**Comment by redhatrises** [comment]
@TomberryToby what checks are you trying to migrate from SSG version 0.1.39? All checks are migrated already.

**Comment by TomberryToby** [comment]
Hi, it is a custom rule made by us, a new rule and oval/checks pair created for our need in shared/guide/our_foulder/ in the v0.1.39. So it could not have been migrated as it was not pushed to SSG.

Could you help me understand how to migrate them ? If needed I can send you some of them to see what is the trouble.

**Comment by redhatrises** [comment]
> Hi, it is a custom rule made by us, a new rule and oval/checks pair created for our need in shared/guide/our_foulder/ in the v0.1.39. So it could not have been migrated as it was not pushed to SSG.
> 
> Could you help me understand how to migrate them ? If needed I can send you some of them to see what is the trouble.
> 
> The checks goes from account password testing, to package installing or removing, service installing or removing and ssh configuration.

@TomberryToby if you can provide the content, that would be great. Also @shawndwells has a point, the checks could be integrated to save headaches in the future.

**Comment by TomberryToby** [comment]
Sorry, the rule are not mine alone so I will have to wait for next week to know if it is okay to have them all integrated.

All these checks are for rhel 7.
How could I send you some of the rule et oval files ?

**Comment by redhatrises** [comment]
@TomberryToby you can actually upload the files to this ticket. Archive (.tar, .gz, .xz, .bz2, etc.) form would be best.

**Comment by TomberryToby** [comment]
Here are some rule and checks, I hope this can help.  
[rule_for_git.zip](https://github.com/ComplianceAsCode/content/files/2528829/rule_for_git.zip)

**Comment by redhatrises** [comment]
@TomberryToby it looks like these rules already exist in the current content. Not sure what the issues are considering the rules already exist. Are you looking to create a custom profile, or ... ?

**Comment by TomberryToby** [comment]
These rules where probably added in 0.1.41, we worked until now on 0.1.39. Thank you most of the problem will be fixed, I will check all the rule.

It seems that the problem came from a difference in writting the description, racional and ocil line of the rule.yml file. Could you explain the change done or why they would not work anymore when they worked in v0.1.39?

For exemple the reason the configure_firewalld_ports rule was not working in the new version, the difference lay in the description line.
v0.1.41 your rule.yml	{{{ describe_firewalld_allow(proto="tcp", service="ssh") }}}
v0.1.39 our rule		<firewalld-desc-macro allow="true" proto="tcp" service="ssh" />

**Comment by redhatrises** [comment]
@TomberryToby when I go through the `rule_for_git.zip`, there are no custom rules. There are only rules that already exist currently in SSG master. So, what custom rule do you need help with because I don't see it in the zip file?

**Comment by redhatrises** [comment]
@TomberryToby bump

**Comment by redhatrises** [comment]
Closing as author is unresponsive.
