### ISSUE TITLE
Request for clarification - "interactive users"

### ISSUE THREAD

**Issue by linuxdan** [ComplianceAsCode/content#3544]
#### Description of problem:
In the section of the SSG labelled Account and Access Control, sub-section Secure Session Configuration Files for Login Accounts (and elsewhere) there are a number of rules that refer to "(local) interactive users".   Would it be safe to say that a login is "interactive" if the shell field from /etc/passwd exists in /etc/shells and is not "nologin" ?

#### SCAP Security Guide Version:
DISA STIG for Red Hat Enterprise Linux 7

#### Operating System Version:
Red Hat Enterprise Linux 7

**Comment by shawndwells** [comment]
On 10/23/18 7:53 AM, Daniel E. White wrote:
>
>
>         Description of problem:
>
> In the section of the SSG labelled Account and Access Control, 
> sub-section Secure Session Configuration Files for Login Accounts (and 
> elsewhere) there are a number of rules that refer to "(local) 
> interactive users". Would it be safe to say that a login is 
> "interactive" if the shell field from /etc/passwd exists in 
> /etc/shells and is not "nologin" ?
>

"Interactive users" reflects accounts which can authenticate into an 
interactive shell, such as bash, upon logon. Generally equivalent to 
saying "these accounts are for humans who logon to the system."

Setting the shell to /bin/false, /sbin/nologin, or even /bin/true, is 
indicative that a given account is *not* for an interactive user. Our 
OVAL will also accept /bin/sync and /sbin/shutdown and /sbin/halt as 
indicative an account is non-interactive.

OVAL code that evaluates this:
https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-restrictions/root_logins/no_shelllogin_for_systemaccounts/oval/shared.xml#L77#L82

In being thorough, human/interactive accounts should have a UID greater 
than UID_MIN and less than UID_MAX as defined in /etc/login.defs. The 
OVAL checks UIDs outside this range and ensures they have a 
non-interactive shell set.

**Comment by linuxdan** [comment]
Thanks for a complete and thorough response

**Comment by linuxdan** [comment]
How about a dash of Python-Fu ?
I did it like this because, on RHEL 7 anyway, `etc/shells` contains
both `/sbin/nologin` and `/usr/sbin/nologin`
```python
#!/usr/bin/env python

import json

nono_shells = [ 'nologin', 'sync', 'shutdown', 'halt' ]

with open('/etc/shells') as shell_in:
    shell_list = [line.rstrip('\n') for line in shell_in]
    shell_in.close()

for clam in shell_list:
    lastword = clam.split('/')[-1]
    if lastword in nono_shells:
        shell_list.remove(clam)

with open('/etc/passwd') as passwd_in:
    passwd_list = [line.rstrip('\n') for line in passwd_in]
    passwd_in.close()

passwd_array = []

for logg in passwd_list:
    passwd_hash = {}
    chopp = logg.split(':')

    passwd_hash['username'] = chopp[0]
    passwd_hash['password'] = chopp[1]
    passwd_hash['uid']      = chopp[2]
    passwd_hash['gid']      = chopp[3]
    passwd_hash['info']     = chopp[4]
    passwd_hash['homedir']  = chopp[5]
    passwd_hash['shell']    = chopp[6]
    
    if passwd_hash['shell'] in shell_list:
        passwd_array.append(passwd_hash)

print json.dumps(passwd_array, indent=4, sort_keys=True)
```

**Comment by shawndwells** [comment]
Whatever works for you!

Added ``/usr/sbin/nologin`` to the parameters that the OVAL will accept:
https://github.com/ComplianceAsCode/content/pull/3547
