### ISSUE TITLE
DISA STIG Desription Mismatch with Test

### ISSUE THREAD

**Issue by HewittJC** [ComplianceAsCode/content#3560]
#### Description of problem:

The description of the `Verify Permissions on SSH Server Private *_key Key Files` control mismatches from what it actually looks for. 

#### SCAP Security Guide Version:

I think 1.2 if I am looking at the right thing.

#### Operating System Version:

MacOS High Sierra as scanner.
CentOS 7.4 as the target system.

#### Steps to Reproduce:

1. Look at the guide

#### Actual Results:

It states:

```
$ sudo chmod 0640 /etc/ssh/*_key
```

#### Expected Results:

While the OVal details appears as:

![screen shot 2018-10-26 at 1 43 30 pm](https://user-images.githubusercontent.com/28607855/47583359-315d1000-d925-11e8-902a-20a5aa900d02.png)

#### Summary

As you can see from the photo, those should add up to an octal value of `0600`, not `0640`

**Comment by redhatrises** [comment]
This is an issue with the STIG content. `0640` is the correct octal.

**Comment by HewittJC** [comment]
@redhatrises is there somewhere else I should open the issue then?
