### ISSUE TITLE
tt vs code - which to use?

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#3583]
Some code, like jinja macros, use ``<code>``. Other places in xccdf/yaml use ``<tt>``.

Which should we standardize on?

**Comment by redhatrises** [comment]
I think ultimately neither and we should use Markdown-style syntax that will it converted to XML.

**Comment by jan-cerny** [comment]
I think it doesn't matter because they're rendered the same. 

The <tt> tag defines teletype text. The <code> tag defines a piece of computer code. The <tt> tag doesn't exist in HTML5, but we use XHTML in our reports.

I like @redhatrises 's idea.

**Comment by trevor-vaughan** [comment]
I would suggest using reStructuredText/Sphinx instead of Markdown for the rich linking and output options that it provides.

Also, then everything could just be auto-published to ReadTheDocs, which would be nice.

**Comment by matejak** [comment]
I personally like reSt, but I consider it too heavy for our simple rule descriptions. You can write a book using Sphinx, but we just need a couple of paragraphs/links/lists/monospace.

**Comment by marcusburghardt** [comment]
Use whatever you like. There is no strict recommendation now.
