### ISSUE TITLE
Rule - security_patches_up_to_date.rule  not working

### ISSUE THREAD

**Issue by TomberryToby** [ComplianceAsCode/content#3599]
#### Description of problem:
The rule "Ensure Software Patches Installed" is not working on centos7 and redhat7.
The error is :  None of the check-content-ref elements was resolvable. 

#### SCAP Security Guide Version:
In version v0.1.39 shared/guide/system/software/updating/security_patches_up_to_date.rule 
In version v0.1.41 linux_os/guide/system/software/updating/security_patches_up_to_date/rule.yml 

#### Operating System Version:
Centos7 and RedHat7

#### Steps to Reproduce:

1. Try to check "Ensure Software Patches Installed" with oscap or scap-workbench
2. See the result
3.
4.

#### Actual Results:
Rule : Not Checked
Error :  None of the check-content-ref elements was resolvable. 

#### Expected Results:
Rule : Fail or Pass

**Comment by redhatrises** [comment]
@TomberryToby this will never work on CentOS. Are you behind a proxy or does the machine not have access to redhat.com?

**Comment by TomberryToby** [comment]
[report_patch.zip](https://github.com/ComplianceAsCode/content/files/2607440/report_patch.zip)
Thank for the information.
My centos machine is behind a proxy so this maybe the reason.
However for my AWS RedHat 7 which is on LAN, I get the same error.

```
 sudo oscap xccdf eval --profile xccdf_or g.ssgproject.content_profile_patch --tailoring-file ssg-rhel7-ds-tailoring_patch.xm l --report report_patch.html --results-arf result_patch.xml ssg-rhel7-ds.xml
WARNING: This content points out to the remote resources. Use `--fetch-remote-resou rces' option to download them.
WARNING: Skipping https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.x ml.bz2 file which is referenced from XCCDF content
Title   Ensure Software Patches Installed
Rule    xccdf_org.ssgproject.content_rule_security_patches_up_to_date
Ident   CCE-26895-3
Result  notchecked
```

What is strange is that I can wget the file and can ping the redhat website. Could you help me?
[security_patches_up_to_date.zip](https://github.com/ComplianceAsCode/content/files/2607455/security_patches_up_to_date.zip)

` wget https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2
--2018-11-22 09:43:24--  https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2
Resolving www.redhat.com (www.redhat.com)... 23.38.217.179, 2a02:26f0:6e00:188::d44, 2a02:26f0:6e00:182::d44
Connecting to www.redhat.com (www.redhat.com)|23.38.217.179|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 642947 (628K) [application/x-bzip2]
Saving to: ‘com.redhat.rhsa-RHEL7.xml.bz2.1’

100%[==========================================>] 642,947     1.15MB/s   in 0.5s

2018-11-22 09:43:25 (1.15 MB/s) - ‘com.redhat.rhsa-RHEL7.xml.bz2.1’ saved [642947/642947]
`

`ping redhat.com
PING redhat.com (209.132.183.105) 56(84) bytes of data.
64 bytes from redirect.redhat.com (209.132.183.105): icmp_seq=1 ttl=223 time=140 ms
64 bytes from redirect.redhat.com (209.132.183.105): icmp_seq=2 ttl=223 time=140 ms
64 bytes from redirect.redhat.com (209.132.183.105): icmp_seq=3 ttl=223 time=140 ms
64 bytes from redirect.redhat.com`

**Comment by jan-cerny** [comment]
It tells you to use --fetch-remote-resources option. Have you tried that?

**Comment by TomberryToby** [comment]
I tried, the code is below, but I though that the problem was not from this. Is my command line wrong ?

```
sudo oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_patch --tailoring-file ssg-rhel7-ds-tailoring_patch.xml --report report_patch.html --results-arf  --fetch-remote-resources https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2  result_patch.xml ssg-rhel7-ds.xml
OpenSCAP Error: Unable to open file: 'https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2' 
```

**Comment by jan-cerny** [comment]
@TomberryToby Don't put the URL there, and put the `result_patch.xml` right after `--results.arf`. Something like this:

sudo oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_patch --tailoring-file ssg-rhel7-ds-tailoring_patch.xml --report report_patch.html --results-arf  result_patch.xml --fetch-remote-resources   ssg-rhel7-ds.xml

**Comment by TomberryToby** [comment]
I don't think this is an older kernel, could you look at my kernel and give me your feedback, please ?

cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.6 (Maipo)

uname -a
Linux ip-xxx-xx-xx-xxx.eu-west-1.compute.internal 3.10.0-957.el7.x86_64 #1 SMP Thu Oct 4 20:48:51 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by redhatrises** [comment]
@TomberryToby please provide the output of ‘rpm -qa | grep kernel’ as
‘uname -a’ doesn’t show the installed kernels.

**Comment by TomberryToby** [comment]
Here the result, thank you for your help.

```
rpm -qa | grep kernel
kernel-3.10.0-957.el7.x86_64
kernel-tools-3.10.0-957.el7.x86_64
kernel-3.10.0-862.el7.x86_64
kernel-tools-libs-3.10.0-957.el7.x86_64
kernel-3.10.0-862.14.4.el7.x86_64
```

**Comment by redhatrises** [comment]
> Here the result, thank you for your help.
> 
> ```
> rpm -qa | grep kernel
> kernel-3.10.0-957.el7.x86_64
> kernel-tools-3.10.0-957.el7.x86_64
> kernel-3.10.0-862.el7.x86_64
> kernel-tools-libs-3.10.0-957.el7.x86_64
> kernel-3.10.0-862.14.4.el7.x86_64
> ```

@TomberryToby I can't be 100% as you didn't add `--oval-results` to your scan, but the issue could be  that you have an older kernel installed. As you can see from above, `kernel-3.10.0-862.14.4.el7.x86_64` and `kernel-3.10.0-862.el7.x86_64` are installed which is most likely why the scan is failing. You would need to remove the older kernels and re-run the scan.

**Comment by redhatrises** [comment]
Closing as no further information has been provided to help resolve the issue.
