### ISSUE TITLE
Ansible remediation for 'Disable SSH Support for User Known Hosts' breaks sshd when there are Match groups

### ISSUE THREAD

**Issue by eclausell** [ComplianceAsCode/content#3645]
#### Description of problem:
Encountered on RHEL 7.5. If /etc/sshd_config contains a Match block, the current remediation

#### SCAP Security Guide Version:
0.1.38 

#### Operating System Version:
RHEL 7.5

#### Steps to Reproduce:

1. On system with ansible (2.4.2), openssh, openscap-scanner and  scap-security-guide installed, (and /etc/ansible/hosts configured for the local), modify /etc/ssh/sshd_config so that it:
  Does not have a ignoreUserKnownHosts configuration
  Has a Match group at the end of the file, e.g. 
```
Subsystem sftp internal-sftp
Match Group users
    ChrootDirectory /home
    AllowTCPForwarding no
    X11Forwarding no
    ForceCommand internal-sftp
<EOF>
```
2. Run the RHEL 7.5 Stig playbook, for the sshd_disable_user_known_hosts rule.
`ansible-playbook --tags=sshd_disable_user_known_hosts  /usr/share/scap-security-guide/ansible/ssg-rhel7-role-stig-rhel7-disa.yml`

#### Actual Results:
![image](https://user-images.githubusercontent.com/20073280/49538038-1b316080-f890-11e8-84fb-09f37f99da6e.png)

Fails because the IgnoreUserKnownHosts entry is added at the end of the file and is considered part of the Match group.
#### Expected Results:
![image](https://user-images.githubusercontent.com/20073280/49537915-d60d2e80-f88f-11e8-8ece-4e1509e347b4.png)

With IgnoreUserKnownHosts added before first Match group .

#### Addition Information/Debugging Steps:
There are likely similar problems with other sshd_config remediation tasks and bash remediations that append to sshd_config.

**Comment by yuumasato** [comment]
@eclausell Would adding to beginning of file be a better approach? Could there be similar problems?

**Comment by eclausell** [comment]
I believe that would work.

**Comment by ggbecker** [comment]
Ensure that bash remediation also has the same behavior.
