### ISSUE TITLE
cmake error with make zipfile

### ISSUE THREAD

**Issue by afcollins** [ComplianceAsCode/content#3735]
#### Description of problem:
When I try to build the content using the zipfile target, there is an invalid cmake command being generated.

#### SCAP Security Guide Version:
Building from source:
```
[root@dns content]# git log -1
commit b7b54d27e4c5797ad741c6a2ef73612159c566c9
Merge: bec53b9 f8fe170
Author: Jan Černý <jcerny@redhat.com>
Date:   Mon Feb 4 13:21:29 2019 +0100

    Merge pull request #3731 from matejak/ssgts_libvirt_fix

    Test suite libvirt fix and Dockerfiles refresh.
```
#### Operating System Version:
```
# uname -a
rhel7
Linux dns 3.10.0-862.11.6.el7.x86_64 #1 SMP Fri Aug 10 16:55:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

#### Steps to Reproduce:
1. make zipfile

#### Actual Results:
```
[root@dns build]# make zipfile/fast
[100%] Building zipfile at /root/content/build/zipfile/scap-security-guide-0.1.43.zip
remove_dir
make_dir
copy license
mkdir
CMake Error: cmake version 2.8.12.2
Usage: /usr/bin/cmake -E [command] [arguments ...]
Available commands: 
```

#### Expected Results:
To complete successfully.

#### Addition Information/Debugging Steps:
Added echo statements to the generated CMakeFiles/zipfile.dir/build.make (between lines 54 and 66), and the offending cmake statement is:
` 62         /usr/bin/cmake -E copy /root/content/rhel{6,7}/kickstart/*-ks.cfg zipfile/scap-security-guide    -0.1.43/kickstart
`

**Comment by afcollins** [comment]
I found the offending line in CMakeFiles/zipfile.dir/build.make, but do not immediately know where the source is to generate this line.  Looks like the problem is rhel{6,7} resolving to multiple source arguments, and cmake only accepts one?

**Comment by redhatrises** [comment]
@afcollins any reason as to why you are not getting the built release zip file at https://github.com/ComplianceAsCode/content/releases/download/v0.1.42/scap-security-guide-0.1.42.zip?

**Comment by redhatrises** [comment]
Looks like `cmake -E copy` doesn't support wildcards in 2.8.12, so `cmake/SSGCommon.cmake` needs to be fixed.

Offending lines:
```
COMMAND ${CMAKE_COMMAND} -E make_directory "zipfile/${ZIPNAME}/kickstart"
COMMAND ${CMAKE_COMMAND} -E copy "${CMAKE_SOURCE_DIR}/rhel{6,7}/kickstart/*.cfg" "zipfile/${ZIPNAME}/kickstart"
COMMAND ${CMAKE_COMMAND} -E copy "${CMAKE_BINARY_DIR}/ssg-*-ds.xml" "zipfile/${ZIPNAME}"
COMMAND ${CMAKE_COMMAND} -E make_directory "zipfile/${ZIPNAME}/roles"
COMMAND ${CMAKE_COMMAND} -E copy "${CMAKE_BINARY_DIR}/roles/*.sh" "zipfile/${ZIPNAME}/roles"
COMMAND ${CMAKE_COMMAND} -E copy "${CMAKE_BINARY_DIR}/roles/*.yml" "zipfile/${ZIPNAME}/roles"
```

**Comment by yuumasato** [comment]
Globbing the files and then using it to copy may fix the issue.

**Comment by redhatrises** [comment]
Not sure if globbing will work considering the files are generated during build. A cmake script may have to created to fix the issue.... odd how it works with later versions of cmake (it seems).

**Comment by yuumasato** [comment]
> Not sure if globbing will work considering the files are generated during build.

Well, the kickstart files are not generated during build.

**Comment by yuumasato** [comment]
> Offending lines:
> ```
> COMMAND ${CMAKE_COMMAND} -E make_directory "zipfile/${ZIPNAME}/kickstart"
> COMMAND ${CMAKE_COMMAND} -E copy "${CMAKE_SOURCE_DIR}/rhel{6,7}/kickstart/*.cfg" "zipfile/${ZIPNAME}/kickstart"
> COMMAND ${CMAKE_COMMAND} -E copy "${CMAKE_BINARY_DIR}/ssg-*-ds.xml" "zipfile/${ZIPNAME}"
> COMMAND ${CMAKE_COMMAND} -E make_directory "zipfile/${ZIPNAME}/roles"
> COMMAND ${CMAKE_COMMAND} -E copy "${CMAKE_BINARY_DIR}/roles/*.sh" "zipfile/${ZIPNAME}/roles"
> COMMAND ${CMAKE_COMMAND} -E copy "${CMAKE_BINARY_DIR}/roles/*.yml" "zipfile/${ZIPNAME}/roles"
> ```

Oh, do you mean all lines with wildcard fail?

**Comment by redhatrises** [comment]
> Oh, do you mean all lines with wildcard fail? Not just the one for kickstarts?

@yuumasato yes. Seems like the only way to fix it is to do a Cmake script. It is weird in the fact that it workd for Cmake in Fedora but not in RHEL in addition to the fact that CMake says it is not supported. So, what to do?
