### ISSUE TITLE
releases do not include documentation

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#3744]
#### Description of problem:

GitHub releases do not include any of the generated documentation, such as guides or tables, generated during the build.

#### SCAP Security Guide Version:

Any, including latest:

https://github.com/ComplianceAsCode/content/releases/download/v0.1.42/scap-security-guide-0.1.42.zip

#### Steps to Reproduce:

1. wget https://github.com/ComplianceAsCode/content/releases/download/v0.1.42/scap-security-guide-0.1.42.zip
2. unzip 
3. look for documentation
4.

#### Actual Results:
documentation not included

#### Expected Results:
documentation should be included

**Comment by matejak** [comment]
Check out the [upstream build guide](https://github.com/ComplianceAsCode/content/blob/master/docs/manual/developer_guide.adoc#43-build-upstream) - that one is outdated, `make tarball` doesn't work. You have to investigate the `make zipfile` chain and modify it, so the build contains HTML guides.
