### ISSUE TITLE
scap - tcp_wrappers_installed rule requires xinetd to be installed (misleading / bound together)

### ISSUE THREAD

**Issue by redhatrises** [ComplianceAsCode/content#3754]
#### Description of problem:
See https://bugzilla.redhat.com/show_bug.cgi?id=1569304

#### Steps to Reproduce:

1.
2.
3.
4.

**Comment by matejak** [comment]
Quoting the BZ:
> Also, in https://github.com/OpenSCAP/scap-security-guide/pull/1151 there is mention of STIG updated, but it was never added to profile. Does STIG required this rule?

@redhatrises, do you, as author of the PR, recall why the OVAL check couples `tcp_wrappers` and `xinetd`? Current research shows that the OVAL implementation has changed - the rule `linux_os/guide/services/obsolete/inetd_and_xinetd/package_tcp_wrappers_installed` has a templated OVAL that doesn't have any coupling with xinetd.

**Comment by redhatrises** [comment]
@matejak I believe this was from the legacy days of RHEL5/6 when there was a rule to remove inetd/xinetd. I will close this.
