### ISSUE TITLE
check to see if client DNSSEC configured (NIST 800-53 SC-21)

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#3773]
SC-21 requires DNSSEC. Need rules to ensure DNSSEC is configured:

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/sec-securing_dns_traffic_with_dnssec#sec-Security_Guide-Installing_DNSSEC

**Comment by Mab879** [comment]
Not adding until a profile needs it.
