### ISSUE TITLE
update file_owner_var_lib_etcd to be deployment aware 

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#3784]
Permissions are root:root in embedded etcd deployments starting in 3.10 with introduction of static pods.  Permissions are only etcd:etcd when etcd runs on separate hosts from the masters.

Need to update rule to reflect

**Comment by redhatrises** [comment]
@shawndwells should we create a separate etcd standalone profile for these?

**Comment by shawndwells** [comment]
I trust you. Do what you think is right. Once something exists we can get user feedback and iterate as needed.

**Comment by redhatrises** [comment]
@JAORMX starting with OCP4.x, is it no longer recommended or supported to have standalone etcd implementations?

**Comment by Mab879** [comment]
@yuumasato @rhmdnd This this issue still valid?

**Comment by yuumasato** [comment]
I don't think it is relevant anymore.

Altough it points me to an inconsistency in CIS benchmark, :sweat: 

This is the CIS requirement title is:
`1.1.12 Ensure that the etcd data directory ownership is set to
etcd:etcd (Manual)`

Then `Audit` and `Default Value have the following text:

```
Audit:
...
The ownership for this directory on the etcd-member container and on
the container host is root:root.
....
Default Value:
By default, in OpenShift 4, etcd data directory ownership is set to root:root.
```

Will check with CIS, :)
This can be closed.
