### ISSUE TITLE
Ansible remediation on ssh server validation fails

### ISSUE THREAD

**Issue by rchayes** [ComplianceAsCode/content#3803]
#### Description of problem:

All ansible remediation using   _validate: sshd -t -f %s_  fails because full path of sshd must be specified.

#### SCAP Security Guide Version:
0.1.42

#### Operating System Version:
CentOS 7

#### Steps to Reproduce:

Run ssg-centos7-role-nist-800-171-cui.yml playbook against CentOS 7 Minimal install.

#### Actual Results:

TASK [Disable SSH Suport for User Known Hosts] *********************************
fatal: [centostemp]: FAILED! => {"changed": false, "cmd": "sshd -t -f /tmp/tmpzge553", "msg": "[Errno 2] No such file or directory", "rc": 2}

#### Expected Results:

TASK [Disable SSH Support for User Known Hosts] ********************************
changed: [centostemp] => {"backup": "", "changed": true, "msg": "line added"}

#### Addition Information/Debugging Steps:

I can make the changes and submit a pull request changing the validate line.  This would be on 19 different files.  Do these need to be separate pull requests or can they all be included in one?

Original (doesn't work):

- name: Disable SSH Access via Empty Passwords
  lineinfile:
    create: yes
    dest: /etc/ssh/sshd_config
    regexp: ^PermitEmptyPasswords
    line: PermitEmptyPasswords no
    validate: sshd -t -f %s

Revised (Works):

- name: Disable SSH Access via Empty Passwords
  lineinfile:
    create: yes
    dest: /etc/ssh/sshd_config
    regexp: ^PermitEmptyPasswords
    line: PermitEmptyPasswords no
    validate: /usr/sbin/sshd -t -f %s

**Comment by redhatrises** [comment]
@rchayes thanks for the report!

> I can make the changes and submit a pull request changing the validate line. This would be on 19 different files. Do these need to be separate pull requests or can they all be included in one?

You can submit 1 PR for all of the changes.

**Comment by shawndwells** [comment]
On 2/19/19 12:07 PM, RCHAYES wrote:
> I can make the changes and submit a pull request changing the validate 
> line. This would be on 19 different files. Do these need to be 
> separate pull requests or can they all be included in one?



If it's the same change x19, one PR would be great. Thanks for the 
report -- and especially for being willing to submit the PR!
