### ISSUE TITLE
Naming of build-related items

### ISSUE THREAD

**Issue by matejak** [ComplianceAsCode/content#3818]
The #3801 has possible improvements to naming and general code structure. See comments to the PR for reference as in-line comments best describe what's the matter.

This issue basically tracks cosmetic fixes.

**Comment by yuumasato** [comment]
Now I think `combine_remediations.py` should be renamed to something like `resolve_remediations.py`, similar to `resolve_rules`

**Comment by marcusburghardt** [comment]
@matejak is this issue still relevant or could it be closed?

**Comment by Mab879** [comment]
Script has been improved since this issue has been opened. Closing.
