### ISSUE TITLE
URL for OL7 GPG Key fingerprint returns 404

### ISSUE THREAD

**Issue by yuumasato** [ComplianceAsCode/content#3822]
#### Description of problem:
Source URL of OL7 GPG key fingerprint cannot be found.

#### SCAP Security Guide Version:
0.1.43

#### Actual Results:
URL https://docs.oracle.com/cd/E37670_01/E39381/html/ol_import_gpg.html returns 404

#### Expected Results:
The URL points to official page where gpg key fingerprints can be found.

#### Addition Information/Debugging Steps:
It is a URL in a comment, but it shouldn't return 404 anyway.
https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/software/updating/ensure_oracle_gpgkey_installed/bash/shared.sh#L3

**Comment by shawndwells** [comment]
+cc @iokomin

**Comment by shawndwells** [comment]
@iokomin realized you were never added to the GitHub content creators group, which allows ticket assignments. Invite sent.

**Comment by iokomin** [comment]
@shawndwells appreciate for your trust, invitation accepted.
I've checked issue details, product documentation issue observed. As soon as acceptable solution confirmed I'll update URL.
