### ISSUE TITLE
SSG: Typo in auditd kernel module (un)loading remediation script

### ISSUE THREAD

**Issue by jmnielsen7** [ComplianceAsCode/content#3833]
#### Description of problem:

Running the following remediation command results in an error that traces to an apparent typo in the SSG remediation script for RHEL 6 that addresses auditd hardening.

Command:
`sudo oscap xccdf eval --remediate --fetch-remote-resources --profile xccdf_org.ssgproject.content_profile_stig-rhel6-disa --results ~/results.xml ./ssg-rhel6-ds.xml`

The human readable output in the SSG HTML format report for non-compliance under the **_Evaluation Messages_** section: 

> Fix execution completed and returned: 0
> 
> `sed: -e expression #3, char 13: unknown command: `F'`
>
> `sed: -e expression #3, char 13: unknown command: `F'`
> 
> Failed to verify applied fix: Checking engine returns: fail

I traced it to this code block where there is a trailing capital 'F' after a semicolon in a sed command:

> 	\# Check if particular audit rule is already defined
> 	IFS=$'\n'
> 	matches=($(sed -s -n -e "\;${pattern};!d" -e "/${arch}/!d" -e "/${group}/!d;F" /etc/audit/rules.d

#### SCAP Security Guide Version:

0.1.43

#### Operating System Version:

RHEL 6.10

#### Workarounds:

Are there any temporary workarounds? I see the code as reported in the HTML but am not sure where it actually comes from in the SSG unzipped content. In the ssg-rhel6-ds.xml file itself? A quick removal of the errant 'F' should do the trick if I can locate the right file to edit.

**Comment by shawndwells** [comment]
copy/paste from the original ticket

----

Hey @jmnielsen7 , thanks for reporting this! This issue is about content versus the OpenSCAP scanner itself. Since it appears you're using RHEL, a few options:

- The SCAP Security Guide (SSG) content shipping in RHEL is supported by Red Hat. Means you can utilize your Red Hat support subscription and open a case direct with Red Hat. They'll fix it and ship an errata. Cases with Red Hat carry support SLAs whereas upstream/github is a community effort;

- If you'd like to engage with the community through GitHub, we'll want to move the case over to https://github.com/ComplianceAsCode/content. We can't administratively do this -- you'll need to copy/paste your case there.

- If you're interested to submit a PR to fix this, it appears the offending line is in the bash remediations (https://github.com/ComplianceAsCode/content/blob/master/shared/bash_remediation_functions/fix_audit_syscall_rule.sh#L88). We'd be happy to help you through the PR process if you're new to GitHub workflow!

-- edit --
Note that fixing upstream means the patch will automatically be picked up in downstream rebases (e.g. RHEL, OEL, and their derivatives).

**Comment by jmnielsen7** [comment]
@shawndwells Is that .sh script anywhere in the unzipped content for the SSG to where I can manually edit it and invoke it? I suppose in a pinch I can copy and paste the bash script content to a local file and execute that.

**Comment by yuumasato** [comment]
@jmnielsen7 from the zipfile, for rhel6, the the faulty line is in `ssg-rhel6-ds.xml` at line 39886.

A way to extract the script is to use `oscap xccdf generate fix`, for example for profile `pci-dss`:
`$ oscap xccdf generate fix --profile pci-dss  --output profile_fixes.sh ./ssg-rhel6-ds.xml`
Unfortunately this extract scripts for all rules, right now there is no easy way to generate fix for only one rule.

Please, let us know if just removing `F` is sufficient as a fix.

**Comment by jmnielsen7** [comment]
@yuumasato  Is the intent to somehow merge that fix back into the xml? If so how do I do that? In the resulting script from your command provided above (which I ran) the relevant line to patch is on line 2166. Should I just copy and paste the segment of the script pertaining to the auditd patching into a fresh .sh script and manually invoke it like 'sh auditd_patch.sh', or must it be invoked from oscap?

**Comment by yuumasato** [comment]
> Is the intent to somehow merge that fix back into the xml? 

@jmnielsen7 Sure, the place to fix upstream is the [file](https://github.com/ComplianceAsCode/content/blob/master/shared/bash_remediation_functions/fix_audit_syscall_rule.sh#L88) pointed by Shawn.

> If so how do I do that? In the resulting script from your command provided above (which I ran, except with the disa profile specified) the relevant line to patch is on line 2166.

As a local fix, you can just edit the xml file.
There is no process to edit the generated script and merge into the DataStream xml. It is just easier to edit and test the fix.

> Should I just copy and paste the segment of the script pertaining to the auditd patching into a fresh .sh script and manually invoke it like 'sh auditd_patch.sh', or must it be invoked from oscap?

Yes, there will be `BEGIN` and `END` markers delimiting the fix snippet.

**Comment by yuumasato** [comment]
> Yes, there will be `BEGIN` and `END` markers delimiting the fix snippet.

Well, it actually dependes on which version of openscap you are using.

**Comment by jmnielsen7** [comment]
@yuumasato It does not appear to be working. I ran an .sh script with the fixed code and when I ran the osacp remediation again it still flagged the same check as failed. Then I edited the ssg-rhel6-ds.xml on line 39886 and somehow I got the same error reported in the HTML report:


> Fix execution completed and returned: 0
> 
> `sed: -e expression #3, char 13: unknown command: `F'`
>
> `sed: -e expression #3, char 13: unknown command: `F'`
> 
> Failed to verify applied fix: Checking engine returns: fail

Perhaps altering the xml is not enough? Or there is more than one place this sed command exists?

**Comment by jmnielsen7** [comment]
Just a further note, I found the same typo on these lines as well in the xml:

40391
148672
149177

Also I discovered I was using the --fetch-remote-resources flag on the oscap remediation. Would that cause oscap to ignore local XML changes somehow? I'll run a few more tests and see if I get any further.

**Comment by yuumasato** [comment]
@jmnielsen7 The `--fetch-remote-resource` shouldn't affect the outcome of remediation.

**Comment by redhatrises** [comment]
Is this because of `-e "/${group}/!d;F"` in `https://github.com/ComplianceAsCode/content/blob/master/shared/bash_remediation_functions/fix_audit_syscall_rule.sh#L88`?

**Comment by jmnielsen7** [comment]
> Is this because of `-e "/${group}/!d;F"` in `https://github.com/ComplianceAsCode/content/blob/master/shared/bash_remediation_functions/fix_audit_syscall_rule.sh#L88`?

I can't speak to that line number in particular since I'm just dealing with the XML but that command is the one under consideration, and I found it in four places total throughout the XML. It is both the semicolon and the capital F which seem extraneous since I'm not sure anything is supposed to follow !d, and the sed man page doesn't have anything for capital F in any case, so it seems like a typo.

**Comment by jmnielsen7** [comment]
Then again, I'm no expert at sed and I also have no idea what exactly this is parsing for, so maybe it is looking for a literal semicolon somewhere?

**Comment by yuumasato** [comment]
After doing an update of `shared/bash_remediation_functions/fix_audit_syscall_rule.sh` in #7329, I can say that  the semicolon and capital F are not a typo.
They are semicolon is a separator for the next expression, and F instructs `sed` to print the filenames where the expressions matched.

Could it be that the `sed` in RHEL-6.10 doesn't support this?

Well, we don't support content for RHEL6 anymore, and very likely `sed` won't be updated there either.
Closing, please re-open if you have issues with these `sed` expression in other systems.
