### ISSUE TITLE
AC-10 | CCI-000054 | SRG-OS-000027-VMM-000080 |   | The VMM must limit the number of concurrent sessions to ten for all accounts and/or account types. |

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#3841]
AC-10 | CCI-000054 | SRG-OS-000027-VMM-000080 
|   | The VMM must limit the number of concurrent sessions to ten for all accounts and/or account types. | VMM management includes the ability to control the number of users and user sessions that utilize the VMM. Limiting the number of allowed users and sessions per user is helpful in limiting risks related to DoS attacks.This requirement addresses concurrent sessions for VMM accounts and does not address concurrent sessions by single users via multiple VMM accounts. If the concurrent-session limitation of ten is insufficient to support operational requirements, it may be set to a higher value, but it must not be unlimited. |   | Verify the VMM limits the number of concurrent sessions to ten for all accounts and/or account types.If it does not, this is a finding. | Configure the VMM to limit the number of concurrent sessions to ten for all accounts and/or account types. 

| CAT II
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by redhatrises** [comment]
This is mapped in system/accounts/accounts-session/accounts_max_concurrent_login_sessions/rule.yml
