### ISSUE TITLE
AC-17 (2) | CCI-000068 | SRG-OS-000033-VMM-000140 |   | The VMM must use DoD-approved encryption to protect the confidentiality of remote access sessions. | 

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#3847]
AC-17 (2) | CCI-000068 | SRG-OS-000033-VMM-000140 |   | The VMM must use DoD-approved encryption to protect the confidentiality of remote access sessions. | 
Without confidentiality protection mechanisms, unauthorized individuals may gain access to sensitive information via a remote access session.Remote access is access to DoD non-public VMMs by an authorized user (or another VMM) communicating through an external, non-organization-controlled network. Remote access methods include, for example, dial-up, broadband, and wireless.Encryption provides a means to secure the remote connection to prevent unauthorized access to the data traversing the remote access connection (e.g., RDP), thereby providing a degree of confidentiality. The encryption strength of mechanism is selected based on the security categorization of the information. |   | Verify the VMM uses DoD-approved encryption to protect the confidentiality of remote access sessions. If it does not, this is a finding. | Configure the VMM to use DoD-approved encryption to protect the confidentiality of remote access sessions.
 | CAT II
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by redhatrises** [comment]
This is already in services/ssh/ssh_server/sshd_use_approved_ciphers/rule.yml
