### ISSUE TITLE
AU-3 | CCI-000131 | SRG-OS-000038-VMM-000160 |   | The VMM must produce audit records containing information to establish when (date and time) the events occurred. | 

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#3849]
AU-3 | CCI-000131 | SRG-OS-000038-VMM-000160 |   | The VMM must produce audit records containing information to establish when (date and time) the events occurred. | 

Without establishing when events occurred, it is difficult to establish, correlate, and investigate the events leading up to an outage or attack.In order to compile an accurate risk assessment and provide forensic analysis, it is essential for security personnel to know when events occurred (date and time). Associating event types with detected events in the VMM audit logs provides a means of investigating an attack; recognizing resource utilization or capacity thresholds; or identifying an improperly configured VMM. |   | Verify the VMM produces audit records containing information to establish when (date and time) the events occurred. If it does not, this is a finding. | Configure the VMM to produce audit records containing information to establish when (date and time) the events occurred. 

| CAT II
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by redhatrises** [comment]
This should be covered by `system/auditing/service_auditd_enabled/rule.yml`
