### ISSUE TITLE
IA-5 (1) (e) | CCI-000200 | SRG-OS-000077-VMM-000440 |   | The VMM must prohibit password reuse for a minimum of five generations. |

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#3876]
IA-5 (1) (e) | CCI-000200 | SRG-OS-000077-VMM-000440 |   | The VMM must prohibit password reuse for a minimum of five generations. |

 Password complexity, or strength, is a measure of the effectiveness of a password in resisting attempts at guessing and brute-force attacks. If the VMM or application allows the user to consecutively reuse their password when that password has exceeded its defined lifetime, the end result is a password that is not changed as per policy requirements. |   | Verify the VMM prohibits password reuse for a minimum of five generations.If it does not, this is a finding. | Configure the VMM to prohibit password reuse for a minimum of five generations. 

| CAT II
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by redhatrises** [comment]
This should be done in accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_remember/rule.yml

**Comment by redhatrises** [comment]
The default is 5
