### ISSUE TITLE
SC-10 | CCI-001133 | SRG-OS-000163-VMM-000700 |   | The VMM must terminate all network connections associated with a communications session at the end of the session, or as follows: for in-band management sessions (privileged sessions), the session must be terminated after 10 minutes of inactivity; and for user sessions (non-privileged session), the session must be terminated after 15 minutes of inactivity, except to fulfill documented and validated mission requirements. | 

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#3900]
SC-10 | CCI-001133 | SRG-OS-000163-VMM-000700 |   | The VMM must terminate all network connections associated with a communications session at the end of the session, or as follows: for in-band management sessions (privileged sessions), the session must be terminated after 10 minutes of inactivity; and for user sessions (non-privileged session), the session must be terminated after 15 minutes of inactivity, except to fulfill documented and validated mission requirements. | 

Terminating an idle session within a short time period reduces the window of opportunity for unauthorized personnel to take control of a management session enabled on the console or console port that has been left unattended. In addition, quickly terminating an idle session will also free up resources committed by the VMM. Terminating network connections associated with communications sessions includes, for example, de-allocating associated TCP/IP address/port pairs at the VMM level, and de-allocating networking assignments at the application level if multiple application sessions are using a single, VMM-level network connection. This does not mean that the VMM terminates all sessions or network access; it only ends the inactive session and releases the resources associated with that session. |   | Verify the VMM terminates all network connections associated with a communications session at the end of the session, or as follows: for in-band management sessions (privileged sessions), the session must be terminated after 10 minutes of inactivity; and for user sessions (non-privileged session), the session must be terminated after 15 minutes of inactivity, except to fulfill documented and validated mission requirements.If it does not, this is a finding. | Configure the VMM to terminate all network connections associated with a communications session at the end of the session, or as follows: for in-band management sessions (privileged sessions), the session must be terminated after 10 minutes of inactivity; and for user sessions (non-privileged session), the session must be terminated after 15 minutes of inactivity, except to fulfill documented and validated mission requirements. | CAT II
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by redhatrises** [comment]
This is handled in system/accounts/accounts-session/accounts_tmout/rule.yml which is also enabled in the profile.
