### ISSUE TITLE
IA-5 (1) (a) | CCI-001619 | SRG-OS-000266-VMM-000940 |   | The VMM must enforce password complexity by requiring that at least one special character be used. |

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#3920]
IA-5 (1) (a) | CCI-001619 | SRG-OS-000266-VMM-000940 |   | The VMM must enforce password complexity by requiring that at least one special character be used. |

 Use of a complex password helps to increase the time and resources required to compromise the password. Password complexity or strength is a measure of the effectiveness of a password in resisting attempts at guessing and brute-force attacks. Password complexity is one factor in determining how long it takes to crack a password. The more complex the password, the greater the number of possible combinations that need to be tested before the password is compromised. Special characters are those characters that are not alphanumeric. Examples include: ~ ! @ # $ % ^ *. |   | Verify the VMM enforces password complexity by requiring that at least one special character be used.If it does not, this is a finding. | Configure the VMM to enforce password complexity by requiring that at least one special character be used. | CAT II
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by redhatrises** [comment]
This should already by done at accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_ocredit/rule.yml
