### ISSUE TITLE
AC-7 b | CCI-002238 | SRG-OS-000329-VMM-001180 |   | The VMM must automatically lock an account until the locked account is released by an administrator, when three unsuccessful logon attempts in 15 minutes are made. |

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#3943]
AC-7 b | CCI-002238 | SRG-OS-000329-VMM-001180 |   | The VMM must automatically lock an account until the locked account is released by an administrator, when three unsuccessful logon attempts in 15 minutes are made. |

 By limiting the number of failed logon attempts, the risk of unauthorized system access via user password guessing, otherwise known as brute-forcing, is reduced. Limits are imposed by locking the account. |   | Verify the VMM automatically locks an account until the locked account is released by an administrator, when three unsuccessful logon attempts in 15 minutes are made.If it does not, this is a finding. | Configure the VMM to automatically lock an account until the locked account is released by an administrator, when three unsuccessful logon attempts in 15 minutes are made. | CAT II
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by redhatrises** [comment]
This should be already done at accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_unlock_time/rule.yml

**Comment by shawndwells** [comment]
Are all the rules enabled in the profiles though?

**Comment by redhatrises** [comment]
yup
