### ISSUE TITLE
CM-5 (3) | CCI-001749 | SRG-OS-000366-VMM-001430 |   | The VMM must prevent the installation of guest VMs, patches, service packs, device drivers, or VMM components without verification they have been digitally signed using a certificate that is recognized and approved by the organization. |

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#3967]
CM-5 (3) | CCI-001749 | SRG-OS-000366-VMM-001430 |   | The VMM must prevent the installation of guest VMs, patches, service packs, device drivers, or VMM components without verification they have been digitally signed using a certificate that is recognized and approved by the organization. |

Changes to any software components can have significant effects on the overall security of the VMM. This requirement ensures the software has not been tampered with and that it has been provided by a trusted vendor. Accordingly, guest VMs, patches, service packs, device drivers, or VMM components must be signed with a certificate recognized and approved by the organization. Verifying the authenticity of the software prior to installation validates the integrity of the patch or upgrade received from a vendor. This ensures the software has not been tampered with and that it has been provided by a trusted vendor. Self-signed certificates are disallowed by this requirement. The VMM should not have to verify the software again. This requirement does not mandate DoD certificates for this purpose; however, the certificate used to verify the software must be from an approved CA. |   | Verify the VMM prevents the installation of guest VMs, patches, service packs, device drivers, or VMM components without verification they have been digitally signed using a certificate that is recognized and approved by the organization.If it does not, this is a finding. | Configure the VMM to prevent the installation of guest VMs, patches, service packs, device drivers, or VMM components without verification they have been digitally signed using a certificate that is recognized and approved by the organization. | CAT II
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by redhatrises** [comment]
This is in the following rules:

system/software/updating/ensure_gpgcheck_never_disabled/rule.yml
system/software/updating/ensure_redhat_gpgkey_installed/rule.yml
system/software/updating/ensure_gpgcheck_globally_activated/rule.yml
system/software/updating/ensure_gpgcheck_local_packages/rule.yml
