### ISSUE TITLE
AU-12 c | CCI-000172 | SRG-OS-000467-VMM-001880 |   | The VMM must generate audit records when successful/unsuccessful attempts to delete security levels occur. |

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4011]
AU-12 c | CCI-000172 | SRG-OS-000467-VMM-001880 |   | The VMM must generate audit records when successful/unsuccessful attempts to delete security levels occur. |

 Without generating audit records that are specific to the security and mission needs of the organization, it would be difficult to establish, correlate, and investigate the events relating to an incident or identify those responsible for one. Audit records can be generated from various components within the VMM (e.g., module or policy filter). |   | Verify the VMM generates audit records when successful/unsuccessful attempts to delete security levels occur.If it does not, this is a finding. | Configure the VMM to generate audit records when successful/unsuccessful attempts to delete security levels occur. | CAT II
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by redhatrises** [comment]
This is handled already by the following rules:
```
system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_rmdir/rule.yml
system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_renameat/rule.yml
system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_unlinkat/rule.yml
system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_rename/rule.yml
system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_unlink/rule.yml
```
