### ISSUE TITLE
Ansible playbook failing when it attempts to "Enable service pcscd" 

### ISSUE THREAD

**Issue by advocateddrummer** [ComplianceAsCode/content#4052]
#### Description of problem:

"Enable service pcscd" fails

#### SCAP Security Guide Version:

Latest release: v0.1.43

oscap version: 1.2.17

#### Operating System Version:

RHEL 7.6

#### Steps to Reproduce:

1. Generate the Ansible 'fix' file: _oscap xccdf generate fix --profile nist-800-171-cui --template urn:xccdf:fix:script:ansible: /opt/ComplianceAsCode/build/ssg-rhel7-xccdf.xml_
2. Run the remediation playbook: _ansible-playbook -i <hostname,> -u root -k main.yml_

#### Actual Results:

The operation fails when it attempts to "Enable service pcscd"

#### Expected Results:

The playbook should complete.

#### Addition Information/Debugging Steps:

So guys, please be gentle with me if I'm wildly missing the point here, I'm only just now learning how to use this tool. I  have installed this package from source as the package provided by RHEL seems to have even more problems as it seems to be too old. The section of the playbook where this service it being configured seems to me to be out of order. It appears as if _opensc_ provides the _pcscd_ service, but the service is being configured _before_ the playbook attempts to make sure _opensc_ is installed. There are also a couple other things happening in the playbook before this that seem to have to do with _opensc_ which also doesn't seem to be appropriate, even though they don't explicitly break the playbook.

I've fixed this by moving the "Ensure opensc is installed" task from _after_ the "Enable service pcscd" task to _before_ the "Check existence of opensc conf" task. This seems appropriate to me as the next three tasks seem to depend on this package being installed. But, I may be missing something. All I know is that if I make this change, the playbook completes without failing.

I assume this would be an easy PR, but I'm not at all familiar with the source here so I'm not sure what to do to fix this. If I had more time I'd try to figure it out, but for now I'll just create this issue.

I want to thank everybody involved with this project, as it's making my life much easier so far!

**Comment by jan-cerny** [comment]
@yuumasato Is it possible that https://github.com/ComplianceAsCode/content/pull/4041solves this problem?

**Comment by yuumasato** [comment]
> Is it possible that #4041 solves this problem?

It should, although I haven't checked ordering between `pcsc-lite` installed and service enabled.

> All I know is that if I make this change, the playbook completes without failing.

@advocateddrummer Is pcscd service running after playbook completion?

> If I had more time I'd try to figure it out, but for now I'll just create this issue.

Thank you for filing the issue it is always helpful.

**Comment by advocateddrummer** [comment]
It is up and running after the playbook completes, that is after the _modified_ playbook completes where I moved the opensc installation task up several places as I described.

I hope to eventually become more familiar with this framework so I can actually help and issue PRs instead of create issues.

**Comment by redhatrises** [comment]
Basically, `shared/templates/template_ANSIBLE_service_enabled` needs to be updated to run when the package exists.

**Comment by jan-cerny** [comment]
> Basically, shared/templates/template_ANSIBLE_service_enabled needs to be updated to run when the package exists.

Yes, I agree. But there is sometimes a problem that the playbook contains a task to install the package after the task to install the service. And we need to get the task the installs the package executed before the task that enables the service is executed. Can Ansible define dependencies between the tasks?

**Comment by redhatrises** [comment]
A When statement has been added to the template to run the task when the package is installed. Closing.
