### ISSUE TITLE
Ansible format regression

### ISSUE THREAD

**Issue by redhatrises** [ComplianceAsCode/content#4061]
PR #3827 did some major rework to remove XSLT (yay!) especially for Ansible, but it introduced some Ansible formatting issues.

1. Empty line in between tasks. For example:

```
- name: get back device fstype
  shell: mount | grep ' /dev/shm ' | cut -d ' ' -f 5
  args:
      warn: false
  register: device_fstype
  check_mode: false
  changed_when: false
- name: Ensure permission nosuid are set on /dev/shm
  mount:
      path: /dev/shm
      src: '{{ device_name.stdout }}'
      opts: '{{ device_cur_mountoption.stdout }},nosuid'
      state: mounted
      fstype: '{{ device_fstype.stdout }}'
```
should be 

```
- name: get back device fstype
  shell: mount | grep ' /dev/shm ' | cut -d ' ' -f 5
  args:
      warn: false
  register: device_fstype
  check_mode: false
  changed_when: false

- name: Ensure permission nosuid are set on /dev/shm
  mount:
      path: /dev/shm
      src: '{{ device_name.stdout }}'
      opts: '{{ device_cur_mountoption.stdout }},nosuid'
      state: mounted
      fstype: '{{ device_fstype.stdout }}'
```

2. Spacing for sequences. For example:
```
when:
- (device_name.stdout | length &gt; 0)
- ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"
tags:
- mount_option_dev_shm_nosuid
- medium_severity
- configure_strategy
- low_complexity
- high_disruption
- CCE-80839-4
- NIST-800-53-CM-7
- NIST-800-53-MP-2
```
should be

```
when:
  - (device_name.stdout | length &gt; 0)
  - ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"
tags:
  - mount_option_dev_shm_nosuid
  - medium_severity
  - configure_strategy
  - low_complexity
  - high_disruption
  - CCE-80839-4
  - NIST-800-53-CM-7
  - NIST-800-53-MP-2
```

This should be fixed before next release.

**Comment by matejak** [comment]
Here is some context:

Ansible snippets have been processed as YAML files, i.e. they are not treated as a random text, but as YAML by the PyYAML module. Therefore, fine-tuning their appearance means fine-tuning how a YAML data structure is formatted to text by the corresponding module.
Although I think that those formatting changes are not blockers, I agree that the previous formatting was better. I think that giving the build system the possibility to access remediations as data structures is beneficial and valuable, efforts should go into customizing the  data->string formatting.
The [Pretty YAML](https://github.com/mk-fg/pretty-yaml) project does exactly that, so it may be our path to the issue's resolution.

**Comment by jan-cerny** [comment]
@redhatrises At the first sight it seems to be a cosmetic issue. Could you please explain why is it a blocker?
