### ISSUE TITLE
Applying `stig-rhel7-disa profile on RHEL7 creates duplicate rules

### ISSUE THREAD

**Issue by eemperor** [ComplianceAsCode/content#4104]
#### Description of problem:
After running oscap with the  `stig-rhel7-disa` profile on RHEL7, duplicate rules are created in `/etc/audit/rules.d/privileges.rules`.  Repeated execution of oscap causes additional duplicate rules to be appended to the file.

#### SCAP Security Guide Version:
v0.1.43

#### Operating System Version:
Red Hat Enterprise Linux Server 7.6

#### Steps to Reproduce:

1.  Download SCAP Security Guide content v0.1.43

2.  Run command to re-mediate system with `stig-rhel7-disa` profile:

`oscap xccdf eval --remediate --profile stig-rhel7-disa ssg-rhel7-ds.xml`

3.  View created rules file `/etc/audit/rules.d/privileges.rules`

4.  Repeat command in Step 2

5.  Repeat Step 3

#### Actual Results:
The `crontab` rule was extracted as an example.  See below:

After initial oscap execution -
```
-a always,exit -F path=/usr/bin/crontab -F perm=x -F auid>=1000 -F auid!=unset -F key=privileged
-a always,exit -F path=/usr/bin/crontab -F perm=x -F auid>=1000 -F auid!=unset -k privileged
```
After second oscap execution -
```
-a always,exit -F path=/usr/bin/crontab -F perm=x -F auid>=1000 -F auid!=unset -F key=privileged
-a always,exit -F path=/usr/bin/crontab -F perm=x -F auid>=1000 -F auid!=unset -k privileged
-a always,exit -F path=/usr/bin/crontab -F perm=x -F auid>=1000 -F auid!=unset -k privileged
```

#### Expected Results:
Only one rule should be created per STIG requirement and additional execution of oscap should not create duplicate rules.

#### Addition Information/Debugging Steps:
The duplicate rules also causes `augenrules --load` to fail with the following error:
```
Error sending add rule data request (Rule exists)
There was an error in line 106 of /etc/audit/audit.rules
```

**Comment by yuumasato** [comment]
Hello, thank you for filling the issue.

For me, there is not even the need to remediate twice.
It seems that bah remediation [`perform_audit_rules_privileged_commands_remediation.sh`](https://github.com/ComplianceAsCode/content/blob/master/shared/bash_remediation_functions/perform_audit_rules_privileged_commands_remediation.sh) can't recognize entries added by [`fix_audit_syscall_rule.sh`](https://github.com/ComplianceAsCode/content/blob/master/shared/bash_remediation_functions/fix_audit_syscall_rule.sh)

But more interesting, why does `stig-rhel7-disa` profile has both (generical and individual) types of rules for audit privileged commands?
Does it need `audit_rules_privileged_commands` rule, and individual rules for privileged commands, like rule `audit_rules_privileged_commands_passwd`?

**Comment by yuumasato** [comment]
Actually, remediations for `audit_rules_privileged_commands` seem to be working fine.
It looks liike some other remediation is breaking the rules.

**Comment by shawndwells** [comment]
On 3/12/19 8:57 AM, Watson Yuuma Sato wrote:
> Actually, remediations for |audit_rules_privileged_commands| seem to 
> be working fine.
> It looks liike some other remediation is breaking the rules.


I'm able to replicate on my RHEL7 machine. Every time remediation is ran 
new entries are created in both audit.rules and audit.d

**Comment by eemperor** [comment]
Thank you for quickly looking into the issue.

**Comment by jan-cerny** [comment]
This was also reported by https://bugzilla.redhat.com/show_bug.cgi?id=1687826
