### ISSUE TITLE
CoreOS: AC-2(4)	ACCOUNT MANAGEMENT | AUTOMATED AUDIT ACTIONS T

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4121]
https://nvd.nist.gov/800-53/Rev4/control/AC-2?baseline=moderate#enhancement-4

AC-2(4) | ACCOUNT MANAGEMENT \| AUTOMATED AUDIT ACTIONSThe information system automatically audits account creation, modification, enabling, disabling, and removal actions, and notifies [Assignment: organization-defined personnel or roles].
-- | --

**Comment by redhatrises** [comment]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/ac/#AC-2%20(4)
