### ISSUE TITLE
CoreOS: AC-18(1)	WIRELESS ACCESS | AUTHENTICATION AND ENCRYPTION

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4149]
https://nvd.nist.gov/800-53/Rev4/control/AC-18?baseline=moderate#enhancement-1

AC-18(1) | WIRELESS ACCESS \| AUTHENTICATION AND ENCRYPTIONThe information system protects wireless access to the system using authentication of [Selection (one or more): users; devices] and encryption.
-- | --

**Comment by redhatrises** [comment]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/ac/#AC-18%20(1)
