### ISSUE TITLE
CoreOS: AC-19(5)	ACCESS CONTROL FOR MOBILE DEVICES | FULL DEVICE / CONTAINER-BASED ENCRYPTION

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4153]
https://nvd.nist.gov/800-53/Rev4/control/AC-19?baseline=moderate#enhancement-5

AC-19(5) | ACCESS CONTROL FOR MOBILE DEVICES \| FULL DEVICE / CONTAINER-BASED ENCRYPTIONThe organization employs [Selection: full-device encryption; container encryption] to protect the confidentiality and integrity of information on [Assignment: organization-defined mobile devices].

Supplemental Guidance: Container-based encryption provides a more fine-grained approach to the encryption of data/information on mobile devices, including for example, encrypting selected data structures such as files, records, or fields. Related to: MP-5, SC-13, SC-28
-- | --

**Comment by redhatrises** [comment]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/ac/#AC-19%20(5)
