### ISSUE TITLE
CoreOS: AC-20(1)	USE OF EXTERNAL INFORMATION SYSTEMS | LIMITS ON AUTHORIZED USE

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4155]
https://nvd.nist.gov/800-53/Rev4/control/AC-20?baseline=moderate#enhancement-1

The organization permits authorized individuals to use an external information system to access the information system or to process, store, or transmit organization-controlled information only when the organization:

AC-20 (1)(a) | Verifies the implementation of required security controls on the external system as specified in the organization's information security policy and security plan; or
-- | --

AC-20 (1)(b) | Retains approved information system connection or processing agreements with the organizational entity hosting the external information system.
-- | --

Supplemental Guidance: This control enhancement recognizes that there are circumstances where individuals using external information systems (e.g., contractors, coalition partners) need to access organizational information systems. In those situations, organizations need confidence that the external information systems contain the necessary security safeguards (i.e., security controls), so as not to compromise, damage, or otherwise harm organizational information systems. Verification that the required security controls have been implemented can be achieved, for example, by third-party, independent assessments, attestations, or other means, depending on the confidence level required by organizations. 
Related to: CA-2

**Comment by redhatrises** [comment]
See http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/ac/#AC-20%20(1)
