### ISSUE TITLE
CoreOS: AC-20(2)	USE OF EXTERNAL INFORMATION SYSTEMS | PORTABLE STORAGE DEVICES

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4156]
https://nvd.nist.gov/800-53/Rev4/control/AC-20?baseline=moderate#enhancement-2

AC-20(2) | USE OF EXTERNAL INFORMATION SYSTEMS \| PORTABLE STORAGE DEVICESThe organization [Selection: restricts; prohibits] the use of organization-controlled portable storage devices by authorized individuals on external information systems.Supplemental Guidance: Limits on the use of organization-controlled portable storage devices in external information systems include, for example, complete prohibition of the use of such devices or restrictions on how the devices may be used and under what conditions the devices may be used.
-- | --

**Comment by redhatrises** [comment]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/ac/#AC-20%20(2)
