### ISSUE TITLE
CoreOS: AC-21 INFORMATION SHARING

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4157]
https://nvd.nist.gov/800-53/Rev4/control/AC-21

Control Description
The organization:
a. Facilitates information sharing by enabling authorized users to determine whether access authorizations assigned to the sharing partner match the access restrictions on the information for [Assignment: organization-defined information sharing circumstances where user discretion is required]; and

b. Employs [Assignment: organization-defined automated mechanisms or manual processes] to assist users in making information sharing/collaboration decisions.

Supplemental Guidance
This control applies to information that may be restricted in some manner (e.g., privileged medical information, contract-sensitive information, proprietary information, personally identifiable information, classified information related to special access programs or compartments) based on some formal or administrative determination. Depending on the particular information-sharing circumstances, sharing partners may be defined at the individual, group, or organizational level. Information may be defined by content, type, security category, or special access program/compartment.

**Comment by redhatrises** [comment]
See http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/ac/#AC-21
