### ISSUE TITLE
CoreOS: AC-22 PUBLICLY ACCESSIBLE CONTENT

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4158]
https://nvd.nist.gov/800-53/Rev4/control/AC-22

Control Description
The organization:
a. Designates individuals authorized to post information onto a publicly accessible information system;

b. Trains authorized individuals to ensure that publicly accessible information does not contain nonpublic information;

c. Reviews the proposed content of information prior to posting onto the publicly accessible information system to ensure that nonpublic information is not included; and

d. Reviews the content on the publicly accessible information system for nonpublic information [Assignment: organization-defined frequency] and removes such information, if discovered.

Supplemental Guidance
In accordance with federal laws, Executive Orders, directives, policies, regulations, standards, and/or guidance, the general public is not authorized access to nonpublic information (e.g., information protected under the Privacy Act and proprietary information). This control addresses information systems that are controlled by the organization and accessible to the general public, typically without identification or authentication. The posting of information on non-organization information systems is covered by organizational policy.

**Comment by redhatrises** [comment]
This was identified as not applicable. See http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/ac/#AC-22
