### ISSUE TITLE
CoreOS: AU-2(3)	AUDIT EVENTS | REVIEWS AND UPDATES

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4161]
https://nvd.nist.gov/800-53/Rev4/control/AU-2?baseline=moderate#enhancement-3

AU-2(3) | AUDIT EVENTS \| REVIEWS AND UPDATESThe organization reviews and updates the audited events [Assignment: organization-defined frequency].Supplemental Guidance: Over time, the events that organizations believe should be audited may change. Reviewing and updating the set of audited events periodically is necessary to ensure that the current set is still necessary and sufficient.
-- | --

**Comment by redhatrises** [comment]
See http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/au/#AU-2%20(3)
