### ISSUE TITLE
CoreOS: AU-3(1)	CONTENT OF AUDIT RECORDS | ADDITIONAL AUDIT INFORMATION

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4163]
https://nvd.nist.gov/800-53/Rev4/control/AU-3?baseline=moderate#enhancement-1

AU-3(1) | CONTENT OF AUDIT RECORDS \| ADDITIONAL AUDIT INFORMATIONThe information system generates audit records containing the following additional information: [Assignment: organization-defined additional, more detailed information].

Supplemental Guidance: Detailed information that organizations may consider in audit records includes, for example, full text recording of privileged commands or the individual identities of group account users. Organizations consider limiting the additional audit information to only that information explicitly needed for specific audit requirements. This facilitates the use of audit trails and audit logs by not including information that could potentially be misleading or could make it more difficult to locate information of interest.
-- | --

**Comment by redhatrises** [comment]
Fixed in #4873
