### ISSUE TITLE
CoreOS: AU-3(2)	CONTENT OF AUDIT RECORDS | CENTRALIZED MANAGEMENT OF PLANNED AUDIT RECORD CONTENT

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4164]
https://nvd.nist.gov/800-53/Rev4/control/AU-3?baseline=high#enhancement-2

AU-3(2) | CONTENT OF AUDIT RECORDS \| CENTRALIZED MANAGEMENT OF PLANNED AUDIT RECORD CONTENTThe information system provides centralized management and configuration of the content to be captured in audit records generated by [Assignment: organization-defined information system components].

Supplemental Guidance: This control enhancement requires that the content to be captured in audit records be configured from a central location (necessitating automation). Organizations coordinate the selection of required audit content to support the centralized management and configuration capability provided by the information system. Related to: AU-6, AU-7
-- | --

**Comment by redhatrises** [comment]
Fixed in #4873
