### ISSUE TITLE
CoreOS: AU-5(1)	RESPONSE TO AUDIT PROCESSING FAILURES | AUDIT STORAGE CAPACITY

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4167]
https://nvd.nist.gov/800-53/Rev4/control/AU-5?baseline=high#enhancement-1

AU-5(1) | RESPONSE TO AUDIT PROCESSING FAILURES \| AUDIT STORAGE CAPACITYThe information system provides a warning to [Assignment: organization-defined personnel, roles, and/or locations] within [Assignment: organization-defined time period] when allocated audit record storage volume reaches [Assignment: organization-defined percentage] of repository maximum audit record storage capacity.Supplemental Guidance: Organizations may have multiple audit data storage repositories distributed across multiple information system components, with each repository having different storage volume capacities.
-- | --

**Comment by redhatrises** [comment]
Fixed in #4873
