### ISSUE TITLE
CoreOS: AU-5(2)	RESPONSE TO AUDIT PROCESSING FAILURES | REAL-TIME ALERTS

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4168]
https://nvd.nist.gov/800-53/Rev4/control/AU-5?baseline=high#enhancement-2

AU-5(2) | RESPONSE TO AUDIT PROCESSING FAILURES \| REAL-TIME ALERTSThe information system provides an alert in [Assignment: organization-defined real-time period] to [Assignment: organization-defined personnel, roles, and/or locations] when the following audit failure events occur: [Assignment: organization-defined audit failure events requiring real-time alerts].Supplemental Guidance: Alerts provide organizations with urgent messages. Real-time alerts provide these messages at information technology speed (i.e., the time from event detection to alert occurs in seconds or less).
-- | --

**Comment by redhatrises** [comment]
Fixed in #4880
