### ISSUE TITLE
CoreOS: AU-6 AUDIT REVIEW, ANALYSIS, AND REPORTING

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4169]
https://nvd.nist.gov/800-53/Rev4/control/AU-6

Control Description
The organization:
a. Reviews and analyzes information system audit records [Assignment: organization-defined frequency] for indications of [Assignment: organization-defined inappropriate or unusual activity]; and

b. Reports findings to [Assignment: organization-defined personnel or roles].

Supplemental Guidance
Audit review, analysis, and reporting covers information security-related auditing performed by organizations including, for example, auditing that results from monitoring of account usage, remote access, wireless connectivity, mobile device connection, configuration settings, system component inventory, use of maintenance tools and nonlocal maintenance, physical access, temperature and humidity, equipment delivery and removal, communications at the information system boundaries, use of mobile code, and use of VoIP. Findings can be reported to organizational entities that include, for example, incident response team, help desk, information security group/department. If organizations are prohibited from reviewing and analyzing audit information or unable to conduct such activities (e.g., in certain national security applications or systems), the review/analysis may be carried out by other organizations granted such authority.

**Comment by redhatrises** [comment]
This was already identified as not applicable. See http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/au/#AU-6
