### ISSUE TITLE
CoreOS: AU-6(1)	AUDIT REVIEW, ANALYSIS, AND REPORTING | PROCESS INTEGRATION

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4170]
https://nvd.nist.gov/800-53/Rev4/control/AU-6?baseline=moderate#enhancement-1

AU-6(1) | AUDIT REVIEW, ANALYSIS, AND REPORTING \| PROCESS INTEGRATIONThe organization employs automated mechanisms to integrate audit review, analysis, and reporting processes to support organizational processes for investigation and response to suspicious activities.

Supplemental Guidance: Organizational processes benefiting from integrated audit review, analysis, and reporting include, for example, incident response, continuous monitoring, contingency planning, and Inspector General audits. Related to: AU-12, PM-7
-- | --

**Comment by redhatrises** [comment]
This is out of scope for Coreos.
