### ISSUE TITLE
CoreOS: AU-6(3)	AUDIT REVIEW, ANALYSIS, AND REPORTING | CORRELATE AUDIT REPOSITORIES

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4171]
https://nvd.nist.gov/800-53/Rev4/control/AU-6?baseline=moderate#enhancement-3

AU-6(3) | AUDIT REVIEW, ANALYSIS, AND REPORTING \| CORRELATE AUDIT REPOSITORIESThe organization analyzes and correlates audit records across different repositories to gain organization-wide situational awareness.Supplemental Guidance: Organization-wide situational awareness includes awareness across all three tiers of risk management (i.e., organizational, mission/business process, and information system) and supports cross-organization awareness. Related to: AU-12, IR-4
-- | --

**Comment by redhatrises** [comment]
This has been identified as not applicable. See http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/au/#AU-6%20(3)
