### ISSUE TITLE
CoreOS: AU-6(6)	AUDIT REVIEW, ANALYSIS, AND REPORTING | CORRELATION WITH PHYSICAL MONITORING

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4173]
https://nvd.nist.gov/800-53/Rev4/control/AU-6?baseline=high#enhancement-6

AU-6(6) | AUDIT REVIEW, ANALYSIS, AND REPORTING \| CORRELATION WITH PHYSICAL MONITORINGThe organization correlates information from audit records with information obtained from monitoring physical access to further enhance the ability to identify suspicious, inappropriate, unusual, or malevolent activity.Supplemental Guidance: The correlation of physical audit information and audit logs from information systems may assist organizations in identifying examples of suspicious behavior or supporting evidence of such behavior. For example, the correlation of an individual's identity for logical access to certain information systems with the additional physical security information that the individual was actually present at the facility when the logical access occurred, may prove to be useful in investigations.
-- | --

**Comment by redhatrises** [comment]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/au/#AU-6%20(5)
