### ISSUE TITLE
CoreOS: AU-7 AUDIT REDUCTION AND REPORT GENERATION

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4174]
https://nvd.nist.gov/800-53/Rev4/control/AU-7

Control Description
The information system provides an audit reduction and report generation capability that:
a. Supports on-demand audit review, analysis, and reporting requirements and after-the-fact investigations of security incidents; and

b. Does not alter the original content or time ordering of audit records.

Supplemental Guidance
Audit reduction is a process that manipulates collected audit information and organizes such information in a summary format that is more meaningful to analysts. Audit reduction and report generation capabilities do not always emanate from the same information system or from the same organizational entities conducting auditing activities. Audit reduction capability can include, for example, modern data mining techniques with advanced data filters to identify anomalous behavior in audit records. The report generation capability provided by the information system can generate customizable reports. Time ordering of audit records can be a significant issue if the granularity of the timestamp in the record is insufficient.

**Comment by redhatrises** [comment]
Add to audit package which provides aureport.
