### ISSUE TITLE
CoreOS: AU-7(1)	AUDIT REDUCTION AND REPORT GENERATION | AUTOMATIC PROCESSING

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4175]
https://nvd.nist.gov/800-53/Rev4/control/AU-7?baseline=moderate#enhancement-1

AU-7(1) | AUDIT REDUCTION AND REPORT GENERATION \| AUTOMATIC PROCESSINGThe information system provides the capability to process audit records for events of interest based on [Assignment: organization-defined audit fields within audit records].Supplemental Guidance: Events of interest can be identified by the content of specific audit record fields including, for example, identities of individuals, event types, event locations, event times, event dates, system resources involved, IP addresses involved, or information objects accessed. Organizations may define audit event criteria to any degree of granularity required, for example, locations selectable by general networking location (e.g., by network or subnetwork) or selectable by specific information system component. Related to: AU-2, AU-12
-- | --

**Comment by redhatrises** [comment]
Map to audit package
