### ISSUE TITLE
CoreOS: AU-8(1)	TIME STAMPS | SYNCHRONIZATION WITH AUTHORITATIVE TIME SOURCE

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4177]
https://nvd.nist.gov/800-53/Rev4/control/AU-8?baseline=moderate#enhancement-1

AU-8 (1)(a) | Compares the internal information system clocks [Assignment: organization-defined frequency] with [Assignment: organization-defined authoritative time source]; and
-- | --

AU-8 (1)(b) | Synchronizes the internal system clocks to the authoritative time source when the time difference is greater than [Assignment: organization-defined time period].
-- | --

**Comment by redhatrises** [comment]
Fixed in #4873
