### ISSUE TITLE
CoreOS: AU-9(4)	PROTECTION OF AUDIT INFORMATION | ACCESS BY SUBSET OF PRIVILEGED USERS

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4179]
https://nvd.nist.gov/800-53/Rev4/control/AU-9?baseline=moderate#enhancement-4

AU-9(4) | PROTECTION OF AUDIT INFORMATION \| ACCESS BY SUBSET OF PRIVILEGED USERSThe organization authorizes access to management of audit functionality to only [Assignment: organization-defined subset of privileged users].

Supplemental Guidance: Individuals with privileged access to an information system and who are also the subject of an audit by that system, may affect the reliability of audit information by inhibiting audit activities or modifying audit records. This control enhancement requires that privileged access be further defined between audit-related privileges and other privileges, thus limiting the users with audit-related privileges.Related to: AC-5
-- | --

**Comment by redhatrises** [comment]
Closing as we are looking into future capabilities to meet this requirement.
