### ISSUE TITLE
CoreOS: AU-9(2)	PROTECTION OF AUDIT INFORMATION | AUDIT BACKUP ON SEPARATE PHYSICAL SYSTEMS / COMPONENTS

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4180]
https://nvd.nist.gov/800-53/Rev4/control/AU-9?baseline=high#enhancement-2

AU-9(2) | PROTECTION OF AUDIT INFORMATION \| AUDIT BACKUP ON SEPARATE PHYSICAL SYSTEMS / COMPONENTSThe information system backs up audit records [Assignment: organization-defined frequency] onto a physically different system or system component than the system or component being audited.Supplemental Guidance: This control enhancement helps to ensure that a compromise of the information system being audited does not also result in a compromise of the audit records.
-- | --

**Comment by redhatrises** [comment]
http://atopathways.redhatgov.io/product-documents/coreos4/nist-800-53/au/#AU-9%20(2)
