### ISSUE TITLE
CoreOS: AU-12(3)	AUDIT GENERATION | CHANGES BY AUTHORIZED INDIVIDUALS

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4186]
https://nvd.nist.gov/800-53/Rev4/control/AU-12?baseline=high#enhancement-3

AU-12(3) | AUDIT GENERATION \| CHANGES BY AUTHORIZED INDIVIDUALSThe information system provides the capability for [Assignment: organization-defined individuals or roles] to change the auditing to be performed on [Assignment: organization-defined information system components] based on [Assignment: organization-defined selectable event criteria] within [Assignment: organization-defined time thresholds].

Supplemental Guidance: This control enhancement enables organizations to extend or limit auditing as necessary to meet organizational requirements. Auditing that is limited to conserve information system resources may be extended to address certain threat situations. In addition, auditing may be limited to a specific set of events to facilitate audit reduction, analysis, and reporting. Organizations can establish time thresholds in which audit actions are changed, for example, near real-time, within minutes, or within hours. Related to: AU-7
-- | --

**Comment by redhatrises** [comment]
This is inherently met.
