### ISSUE TITLE
Help with SCE rule creation using python checks

### ISSUE THREAD

**Issue by vjayantinse** [ComplianceAsCode/content#4214]
#### Description of problem:
Hi experts,

I am trying to check a simple rule written using python in a SCE enabled OpenSCAP environment. But I am not getting a valid result and the tool returns "not applicable"

#### Operating System Version:
Ubuntu 18.04 Bionic

#### Steps to Reproduce:

1. I created a XCCDF document as per the syntax
2. I wrote a simple file checking code in pythin which should return if file exists and fail if it doesnt
3. I made the 'check-content-ref' to point to the python code
4. The python code has been set to return XCCDF_RESULT_PASS/FAIL when exiting from a condition.

The XCCDF xml file is as below:
<Group id="ubuntu1804" hidden="false">
  <title xml:lang="en-US">Ubuntu Scanning</title>
  <description xml:lang="en-US">Ubuntu CVE Scanning</description>
  <Rule id="test_scan" selected="true" severity="medium">
<title xml:lang="en-US">Test scan for SCE <description xmlns:xhtml="http://www.w3.org/1999/xhtml"; xml:lang="en-US">
      Test description
    </description>
<rationale xmlns:xhtml="http://www.w3.org/1999/xhtml"; xml:lang="en-US">
    Test rationale
    </rationale>
    <ident system="http://cce.mitre.org";>CCE-26828-4</ident>
    <check system="http://open-scap.org/page/SCE";>
      <check-import import-name="stdout" />
      <check-content-ref href="rule01test.py" />
    </check>
  </Rule>
</Group>

The python rule check script is as below:

#! usr/bin/python

import sys
import os
fname = "movies.txt"
if os.path.isfile(fname):
	print(XCCDF_RESULT_PASS)
else:
	print(XCCDF_RESULT_FAIL)

#### Actual Results:

Title    Test scan for SCE
Rule    test_scan
Result    not applicable
#### Expected Results:

Title    Test scan for SCE
Rule    test_scan
Result    pass/fail

**Comment by jan-cerny** [comment]
Does `oscap --version` contain SCE in `==== Capabilities added by auto-loaded plugins ====`?

If you generate HTML report, is there any error message? If you generate XML results using `--results`, does the TestResult section contain any error message?

**Comment by vjayantinse** [comment]
Yes, the oscap version contains ==== Capabilities added by auto-loaded plugins ====?

No error message found in the XML file, just states "not applicable"

**Comment by yuumasato** [comment]
@vjayantinse It is not clear if your openscap was able to load the `SCE` plugin.

For example, in the example below, `oscap` was not able to find the module. Do you have similar output?
```
==== Capabilities added by auto-loaded plugins ====
No plugins have been auto-loaded...
```

This is very likely an issue with [openscap](https://github.com/OpenSCAP/openscap)

**Comment by vjayantinse** [comment]
Hello @yuumasato 

Thanks for your reply. The oscap tool is enabled to load SCE plugins.

When I run oscap -V, I get the similar output as above.

Thanks.

**Comment by yuumasato** [comment]
@vjayantinse I'm sorry, I'm still confused.
The output I pasted was for when `oscap` cannot find the SCE module.

Could you paste output from command line? :)

**Comment by vjayantinse** [comment]
Sorry for the confusion
The output is as below 
![oscap](https://user-images.githubusercontent.com/47958668/55573034-f1216b00-56d6-11e9-869b-b00c462cfe3c.jpg)

**Comment by yuumasato** [comment]
@vjayantinse Sorry for the delay.

Great, SCE engine should be working.
Does your XCCDF have any platform element?
The cause of the result `notapplicable` could be caused by setting a `Rule`, `Group` or `Benchmark` to a platform that is not what you are scanning.
Are you writing the XCCDF by hand or generating with the build system?

Can you attach the files?

**Comment by vjayantinse** [comment]
Got it working. Thanks
