### ISSUE TITLE
All results from rhosp13 scan showing notapplicable

### ISSUE THREAD

**Issue by aarongreen85** [ComplianceAsCode/content#4217]
#### Description of problem:
Trying to run a scan of an openstack node and all results are showing notapplicable

#### SCAP Security Guide Version:
0.1.43 from source

#### Operating System Version:
rhel7.6, rhosp13

#### Steps to Reproduce:

1. Download source tar.
2. Install on openstack director
3. Run `oscap-ssh --sudo heat-admin@ip.ip.ip.ip 22 xccdf eval --profile xccdf_org.ssgproject.content_profile_stig --results ~/openscap/controller0-rhosp13.xml --report ~/openscap/controller0-rhosp13.html /usr/local/share/xml/scap/ssg/content/ssg-rhosp13-ds.xml`
4. See all results as notapplicable

#### Actual Results:
All results from rhosp13 showing notapplicable

#### Expected Results:
All results from rhosp13 showing pass/fail

#### Addition Information/Debugging Steps:
Also ran some addtl lines to see if tweaking the inputs would make a difference and they didn't.

`oscap-ssh --sudo heat-admin@ip.ip.ip.ip 22 xccdf eval --profile xccdf_org.ssgproject.content_profile_stig --results ~/openscap/controller0-rhosp13.xml --report ~/openscap/controller0-rhosp13.html --cpe /usr/local/share/xml/scap/ssg/content/ssg-rhosp13-cpe-dictionary.xml /usr/local/share/xml/scap/ssg/content/ssg-rhosp13-ds.xml`

`oscap-ssh --sudo heat-admin@ip.ip.ip.ip 22 xccdf eval --profile stig --results ~/openscap/controller0-rhosp13.xml --report ~/openscap/controller0-rhosp13.html /usr/local/share/xml/scap/ssg/content/ssg-rhosp13-xccdf.xml`

`oscap-ssh --sudo heat-admin@ip.ip.ip.ip 22 xccdf eval --profile stig --results ~/openscap/controller0-rhosp13.xml --report ~/openscap/controller0-rhosp13.html --cpe /usr/local/share/xml/scap/ssg/content/ssg-rhosp13-cpe-dictionary.xml /usr/local/share/xml/scap/ssg/content/ssg-rhosp13-xccdf.xml`

**Comment by redhatrises** [comment]
@aarongreen85 does this work with installing and running `oscap` directly and not through ssh?

**Comment by jan-cerny** [comment]
I think that the CPE definition might be broken

**Comment by jan-cerny** [comment]
@aarongreen85 There were some fixes recently in https://github.com/ComplianceAsCode/content/pull/4053 . Could you try if it's still reproducible with the latest master?

**Comment by aarongreen85** [comment]
@jan-cerny thanks for pointing me to that issue. That fixed my issue. After fixing that, the checks ran fine.
