### ISSUE TITLE
'When' statements should not include jinja2 templating delimiters such as {{ }} or {% %}

### ISSUE THREAD

**Issue by redhatrises** [ComplianceAsCode/content#4223]
#### Description of problem:
When statements should not include jinja2 templating delimiters such as {{ }} or {% %}
Ansible has been warning against this since 2.3.
See https://github.com/ansible/ansible/issues/22397 

#### SCAP Security Guide Version:
Current

#### Steps to Reproduce:

1.
2.
3.
4.

#### Actual Results:
Multiple warnings for each instance of a delimiter e.g.:
```
[WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: {{ ensure_gpgcheck_never_disabled | bool }}
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: {{ no_reboot_needed | bool }}
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: {{ high_severity | bool }}
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: {{ unknown_strategy | bool }}
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: {{ medium_disruption | bool }}
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: {{ low_complexity | bool }}
```

#### Expected Results:
No warnings.

**Comment by jan-cerny** [comment]
@redhatrises Which playbook do you run?

**Comment by redhatrises** [comment]
This is an issue with every Ansible playbook, but for looking for ansible issues with containers, I specifically used the CJIS profile.

**Comment by jan-cerny** [comment]
@redhatrises It comes from here:
https://github.com/ComplianceAsCode/content/blob/52f965e69c9df5269ede24633b5f19fb7384f210/utils/upload_ansible_roles_to_galaxy.py#L166

I don't know why are the variables typecast this way, they're already defined as a bool variable in the role defaults file, it seems to me we don't have to use this construction.
