### ISSUE TITLE
update rules to evaluate if PAM is installed

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4227]
|rule  | oval | xccdf |
| ------------- | ------------- | ------------- |
| accounts_password_pam_unix_remember  | done | done | 
| accounts_passwords_pam_faillock_deny | done |done | 
| accounts_passwords_pam_faillock_deny_root | done |done | 
| accounts_passwords_pam_faillock_interval | done |done | 
| accounts_passwords_pam_faillock_unlock_time | done | done | 
| accounts_password_pam_dcredit | template_OVAL_accounts_password | done | 
| accounts_password_pam_difok | template_OVAL_accounts_password | done | 
| accounts_password_pam_lcredit | template_OVAL_accounts_password | done | 
| accounts_password_pam_maxclassrepeat | template_OVAL_accounts_password | done | 
| accounts_password_pam_minclass | template_OVAL_accounts_password | done | 
| accounts_password_pam_minlen | template_OVAL_accounts_password | done | 
| accounts_password_pam_ocredit | template_OVAL_accounts_password | done | 
| accounts_password_pam_retry | done  |  done | 
| accounts_password_pam_ucredit | template_OVAL_accounts_password |  done | 
| set_password_hashing_algorithm_systemauth | done |  done |

**Comment by redhatrises** [comment]
Why?

**Comment by redhatrises** [comment]
> Why?

Please provide a lot more context here.

**Comment by shawndwells** [comment]
On 3/27/19 9:32 PM, Gabe Alford wrote:
>
> Please provide a lot more context here.
>

Some systems do not have a PAM stack

**Comment by redhatrises** [comment]
> On 3/27/19 9:32 PM, Gabe Alford wrote: Please provide a lot more context here.
> Some systems do not have a PAM stack

Thanks!

**Comment by yuumasato** [comment]
Fixed in #4271
