### ISSUE TITLE
accounts_maximum_age_login_defs errors with "Referenced variable has no values (oval:ssg-variable_last_pass_max_days_instance_value:var:1)."

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4233]
When running a scan, e.g. rhel7 ospp profile, the accounts_maximum_age_login_defs will always fail:

![image](https://user-images.githubusercontent.com/5713754/55271224-ad1a0a80-527f-11e9-9305-282160034de2.png)

**Comment by jan-cerny** [comment]
Is `PASS_MAX_DAYS` present in your `/etc/login.defs`?

Why do you think it will always fail?

**Comment by shawndwells** [comment]
The OVAL report shows ssg-variable_last_pass_max_days_instance_value as always being empty.

**Comment by jan-cerny** [comment]
Why always?

**Comment by marcusburghardt** [comment]
Old issue without interaction for long time and likely no longer relevant.
