### ISSUE TITLE
update umask checks

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4244]
Existing umask rule (xccdf_org.ssgproject.content_rule_accounts_umask_etc_login_defs) evaluates /etc/login.defs. Some distros/spins will not have shadow-utils (which owns that file), but will ship /etc/bashrc.

Need a check to evaluate /etc/bashrc.

**Comment by matejak** [comment]
Let's not forget that OVAL can contain jinja macros, so it is possible to handle some of the platform-specificity on the jinja level.

**Comment by yuumasato** [comment]
I believe this is fixed by #4241
