### ISSUE TITLE
Beginners Starting Point?

### ISSUE THREAD

**Issue by kclinden** [ComplianceAsCode/content#4272]
#### Description of problem:
I have never written SCAP content before, and am looking at how to get started. I would like to write SCAP content to test compliance on Photon OS against DISA SRGs. I have been all over the wiki pages, but I am still not sure how to get started. The main page makes it look super easy for writing OVAL and XCCDF files using YAML, but I am not sure where to build those yaml files, and how to run them through the framework to generate a XCCDF DS files. I would like to just start with a basic check to validate that root logon is not permitted. 

What am I missing?

#### SCAP Security Guide Version:
Latest

#### Operating System Version:
Photon OS 2.0 and 3.0

**Comment by yuumasato** [comment]
> I have never written SCAP content before, and am looking at how to get started. 
Hello, that is great!

> I would like to write SCAP content to test compliance on Photon OS against DISA SRGs. 

You will need to create a new product for Photon OS. This should guide you: https://github.com/ComplianceAsCode/content/tree/master/example
If anything is not clear, let us know, or suggest changes, :)

> I have been all over the wiki pages, but I am still not sure how to get started. The main page makes it look super easy for writing OVAL and XCCDF files using YAML, but I am not sure where to build those yaml files, and how to run them through the framework to generate a XCCDF DS files.

Have you checked the developer guide? It should give some more insight: https://github.com/ComplianceAsCode/content/blob/master/docs/manual/developer_guide.adoc

> I would like to just start with a basic check to validate that root logon is not permitted.

If the rules already exisits, which is the case, you'd basically create a profile, add the rules you want there, and build.

In the example [profile](https://github.com/ComplianceAsCode/content/blob/master/example/profiles/example.profile#L23), there is already a rule for SSH root login. If you are thinking about console root login, this would be the [rule](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-restrictions/root_logins/no_direct_root_logins).

**Comment by kclinden** [comment]
I am going through the Devleoper Guide, and I am hung up on step 3.3. I downloaded the tar from the releases page per step 3.2. When I unpack the file there is no build directory. I see there is one in the git repo if I were to take the clone repo. Am I missing something with the release route, or is the doc msising something?

**Comment by kclinden** [comment]
So I am using the repo clone route, and when I try to do a build on rhel7 I am getting errors that WARNING: OVAL check `'some check' was not found, removing <check-content> element from the xccdf file.`

**Comment by yuumasato** [comment]
> When I unpack the file there is no build directory. I see there is one in the git repo if I were to take the clone repo. Am I missing something with the release route, or is the doc msising something?

It should be fine with the release tarbal, the `build` directory is just a place to put the build output.

> So I am using the repo clone route, and when I try to do a build on rhel7 I am getting errors that `WARNING: OVAL check 'some check' was not found, removing <check-content> element from the xccdf file.` Is this normal?

Well, they are "normal", but shouldn't be. There are a lot of warnings during the build and while they are not fatal, they are telling that some content may not get to final output.

**Comment by kclinden** [comment]
The warnings seem to be caused by that check not being in the specific OS checks folder. For example the 'file_ownership_home_directories' check doesn't exist in the `../rhel7/checks/oval/` folder. It does exist in the rules directory. If I understand how the oval generation works, the oval files are created via the rules yaml files. Why would this one not get created?

**Comment by kclinden** [comment]
The Developer Guide isn't very clear on how to create a new product. I copy the example directory and modify the applicable files. Does the new product then need to be added to the CMakeList.txt manually?

**Comment by kclinden** [comment]
The Developer Guide isn't very clear on how to create a new product. I copy the example directory and modify the applicable files. Does the new product then need to be added to the CMakeList.txt manually?

**Comment by redhatrises** [comment]
> The Developer Guide isn't very clear on how to create a new product. I copy the example directory and modify the applicable files. Does the new product then need to be added to the CMakeList.txt manually?

@kclinden yes it does.

**Comment by kclinden** [comment]
Am I missing the doc that says where other than the CmakeList I need to add the product?

**Comment by ggbecker** [comment]
Hi @kclinden , in these commits you can see which changes are necessary to have in order to create a new product:
First one is listed in the example README.md file:
https://github.com/ComplianceAsCode/content/commit/bfe5a76495973f5fc000645c68e3e6936543a09f

And the second one, which I recently updated so it should work:
https://github.com/ggbecker/content/commit/a82173c96ae8404ac51b0f3c61470649a64be765
Note: What I did here was: copied entire debian8 directory structure and modified the files.
Note2: Files from this commit were inherited by the debian8 directory:
https://github.com/ggbecker/content/commit/a0e83484e271f5c83fc31ecb146d3b79481ad331

**Comment by ggbecker** [comment]
Hi @kclinden , I would like to let you know that we have written a guide on how to create a new product. If you have time, please give it a shot and let us know about any feedback.

Guide: https://github.com/ComplianceAsCode/content/blob/master/example/README.md

**Comment by marcusburghardt** [comment]
There is an updated documentation in place.
