### ISSUE TITLE
grub2_audit_backlog_limit_argument references wrong configuration

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#4274]
https://github.com/ComplianceAsCode/content/blob/eb4b3f8ed575b84412b54d605123387c77fb95d1/linux_os/guide/system/auditing/grub2_audit_backlog_limit_argument/rule.yml#L29

The correct would be audit=1 instead of audit_backlog_limit=1

It looks like the ocil is incorrect.

Based on: https://github.com/RedHatDemos/SecurityDemos/blob/master/2019Labs/RHELSecurityLab/documentation/lab6_Audit.adoc#lab-6223-exercise-steps

**Comment by shawndwells** [comment]
``audit_backlog_limit`` is a distinct configuration setting requiring its own config check. For reference:
http://blog.siphos.be/2015/05/audit-buffering-and-rate-limiting/

Looks like this could be configured as kernel option or userspace option in audit.rules though. Don't know which one should be evaluated.
