### ISSUE TITLE
Platform targetting of checks/remediations has redundancies

### ISSUE THREAD

**Issue by matejak** [ComplianceAsCode/content#4275]
Remediations / checks can have applicability restricted in two ways:

* file basename (`shared.sh` vs `rhel8.sh`), and
* metadata (`#platform = multi_platform_rhel`).

The metadata approach can handle all possible cases and combinations, so why not to drop the basename approach, treat any basename as `shared`, and use only the metatdata to restrict applicability?

**Comment by redhatrises** [comment]
I agree. We could probably even get rid of the `ansible`, `bash`, etc directories and instead of `shared` do `bash.sh`, `ansible.yml`, etc. 

One question is how to handle bash fixes that are for different operating systems? IIRC, we have a few of those.

**Comment by jan-cerny** [comment]
@matejak That sounds great! 

@redhatrises They could be merged into a single file and use Jinja `if else` macros. 

But removing directories is probably slightly more difficult. For now, I would prefer @matejak's proposal to just ignore file names and treat the files only based on `platform` in the comment header.

**Comment by marcusburghardt** [comment]
I just searched for `rhel7.sh`, `rhel8.sh`, `rhel9.sh` or `rhel.sh` in the content and didn't find any file.
