### ISSUE TITLE
should audit_backlog_limit be a variable

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4282]
Currently ``audit_backlog_limit`` is statically set to ``8192`` via https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/auditing/grub2_audit_backlog_limit_argument/rule.yml#L9

Should this be a variable, or does it truly need to be 8192?

**Comment by yuumasato** [comment]
It can be made into a variable.
8192 is just a safe value for the system to boot, and have enough capacity to store events.

**Comment by marcusburghardt** [comment]
It is not necessary to convert it in a variable since there is not current case asking different values for this option.
