### ISSUE TITLE
auditConfig for master-config.yaml in Openshift for maximumFileRetentionDays incorrectly marked failed

### ISSUE THREAD

**Issue by kanik-suden** [ComplianceAsCode/content#4298]
#### Description of problem:
When running oscap command I am getting false failures in the master report for settings made in the openshift master-config.yaml. Settings under AuditConfig seem to not be found when it scans the file. 

#### SCAP Security Guide Version:
v.0.1.43

#### Operating System Version:
Red Hat Enterprise Linux Server release 7.6 (Maipo)
3.10.0-957.10.1.el7.x86_64 
Openshift 3.11

#### Steps to Reproduce:

1. log into a master node of an openshift 3.11 cluster. 
2. ensure /etc/origin/master/master-config.yaml has correct auditConfig settings listed in debug steps (just the setting, the value can be arbitrary)
3. Install the oscap package for the scan
4. `cd /tmp/ ; wget https://github.com/ComplianceAsCode/content/releases/download/v0.1.43/scap-securit y-guide-0.1.43.zip && unzip scap-security-guide-0.1.43.zip`

5. run `oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_opencis-master --report master-report.html --oval-results ssg-ocp3-ds.xml`
6. Check results in master-report.html for maximumFileRetentionDays outcome.

#### Actual Results:
maximumFileRetentionDays is configured failed because these items were missing:
Object oval:ssg-object_api_server_audit_log_maxage:obj:1 of type textfilecontent54_object

#### Expected Results:
Successful Audit Config maximumFileRetentionDays configured. 

#### Addition Information/Debugging Steps:
Issue seemed to be found with regex used searching during api_server_audit_log_maxage and other AuditConfig tests. Another admin was able to adjust the regex and provide successful results.

Settings for auditConfig section of /etc/origin/master/master-config.yaml (Ours is placed above authConfig in the file, though order shouldn't matter)
```
auditConfig:
  auditFilePath: "/var/lib/origin/logs/ocp-api-audit.log"
  enabled: true
  maximumFileRetentionDays: 30
  maximumFileSizeMegabytes: 500
  maximumRetainedFiles: 7
```

RegEx: `^[\s]*auditConfig:\:(?:[^\n]*\n+)+?[\s]*maximumFileRetentionDays\:[\s]+(\d+)[\s]*$`

Info and Devel log dumps from the oscap command used:
[oscap-devel-2.log](https://github.com/ComplianceAsCode/content/files/3118726/oscap-devel-2.log)
[oscap-info-2.log](https://github.com/ComplianceAsCode/content/files/3118727/oscap-info-2.log)

**Comment by shawndwells** [comment]
Will take a look later today (US EST)

**Comment by shawndwells** [comment]
The current regex was looking for ``auditConfig::`` vs ``auditConfig:``

Specifically, the old:
``^[\s]*auditConfig:\:(?:[^\n]*\n+)+?[\s]*maximumFileRetentionDays\:[\s]+(\d+)[\s]*$``

Vs:
``^[\s]*auditConfig:(?:[^\n]*\n+)+?[\s]*maximumFileRetentionDays\:[\s]+(\d+)[\s]*$``

**Comment by shawndwells** [comment]
Further, the OVAL condition was incorrectly set to ``greater than or equal to``:

`````

  <ind:textfilecontent54_state id="state_api_server_audit_log_maxage" version="1">
    <ind:subexpression datatype="int" operation="greater than or equal">30</ind:subexpression>
  </ind:textfilecontent54_state>
`````

Since this value is the *maximum*, it should be ``less than or equal to``. Fixing that too.

**Comment by shawndwells** [comment]
@kanik-suden Thank you for the bug report! Was exceptionally well written which allowed me to read/review easily. Looks like you created a GitHub account just for reporting this issue -- so thanks for that too!

As noted above the regex was indeed incorrect and looking for ``auditConfig::`` vs ``auditConfig:`` (single ``:``). While looking at the OVAL there was a second bug regarding how the OVAL was processing the value of ``maximumFileRetentionDays``. It was set to ``pass`` on values greater than or equal to ``30``, versus passing when the value is less than or equal to.

Patch submitted to fix this issues via https://github.com/ComplianceAsCode/content/pull/4303. From here there will be peer review of the patch, and upon acceptance, this will be fixed in the next release.

**Comment by shawndwells** [comment]
@kanik-suden the pull request was merged and this will be part of the next release. Thanks again for reporting the bug!
