### ISSUE TITLE
[RHEL/6] Collect all lines matching the specified pattern (AKA "USGCB instance issue")

### ISSUE THREAD

**Issue by iankko** [ComplianceAsCode/content#433]
## The issue:

There's a large number of textfilecontent54 objects collecting only the first match: 

```
$ fgrep -ri '<ind:instance datatype="int">1</ind:instance>' RHEL/6/output/ssg-rhel6-oval.xml | wc -l
207
```

This can be a problem in case of a configuration file where only the last occurrence of a keyword is significant. Even in the case of configurations where only the first instance is significant, presence of repeating keywords is ambiguous.
## Stages of the proposed fix:
- make automated test checking this by each PR for RHEL-6, RHEL-7, Fedora content
- make PRs fixing particular cases of failing services wrt to this issue
- enhance the subcompliance kickstart to also include tests for these cases (to prevent regressions in the future)
## Relevant fixes / PRs:

`/etc/grub.conf` fixes: https://github.com/OpenSCAP/scap-security-guide/pull/437
`/etc/login.defs` instance fixes: https://github.com/OpenSCAP/scap-security-guide/pull/438

**Comment by matejak** [comment]
The point in the issue description is valid, but those referenced PRs look over-engineered. It would be nice to have a second opinion here.

**Comment by marcusburghardt** [comment]
RHEL6 no longer present in the project.
