### ISSUE TITLE
Fix rsyslog_files rules for rsyslog v8.33.0

### ISSUE THREAD

**Issue by iokomin** [ComplianceAsCode/content#4363]
#### Description of problem:
Existing rsyslog_files rules and bash remediation scripts rely on $IncludeConfig directive which is deprecated starting from v8.33.0, include() object should be used instead:
https://www.rsyslog.com/doc/v8-stable/rainerscript/include.html

Affected tests:
- rsyslog_files_groupownership
- rsyslog_files_ownership
- rsyslog_files_permissions

#### SCAP Security Guide Version:
v0.1.43

#### Operating System Version:
Oracle Linux 8
Assume RHEL8 and latest Fedora should be affected as well

#### Steps to Reproduce:
1. run rsyslog_files_permissions evaluation
2. 
3.

#### Actual Results:
OVAL definition marked as failed with "Referenced variable has no values (oval:ssg-var_rfp_log_files_paths:var:1)."

#### Expected Results:
Evaluation passed

#### Addition Information/Debugging Steps:
Bash remediation script for rsyslog_files_permissions should be also revised to take into account  include() object

**Comment by redhatrises** [comment]
This should be fixed in #4379

**Comment by jan-cerny** [comment]
@redhatrises  #4739 is still opened
