### ISSUE TITLE
Undefined Variable Line 148

### ISSUE THREAD

**Issue by kz6fittycent** [ComplianceAsCode/content#4395]
#### Description of problem:
First time running this. Attempted to run "as is" and received the posted error below. Commenting out that section will allow Ansible to run through but then I end up with a black screen at reboot...

#### Operating System Version:
RHEL 7.6

#### Steps to Reproduce:

1. Followed outlined steps on 
2. Ran playbook...
3. Got error below
4. Commented out offending lines, black screen.

#### Actual Results:

```
TASK [RedHatOfficial.rhel7_stig : Ensure permission nosuid are set on /home] ************************
fatal: [192.168.0.126]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'fstype'\n\nThe error appears to have been in '/home/james/.ansible/roles/RedHatOfficial.rhel7_stig/tasks/main.yml': line 148, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Ensure permission nosuid are set on /home\n  ^ here\n"}

```

This is a "default" install of RHEL 7.6. Required partitions are set for DISA STIG. Fully patched. 

Nothing else was done to the install as I was hoping that this could serve as a way to harden post-installation for system admins. 

Let me know if you need further information. 

#### Expected Results:
"working system"

**Comment by ggbecker** [comment]
This ansible playbook is templated and it is generated from using this [file](https://github.com/ComplianceAsCode/content/blob/4fb920765817ace3a7ade77953170ec10a75f24f/rhel7/templates/csv/mount_options.csv#L20). This rule doesn't set fstype and the ansible playbook doesn't have default value assigned. One solution would be change the template to explicitly set the default values, something like: `/home,nosuid,create_fstab_entry_if_needed,ext4,ext4`.

**Comment by kz6fittycent** [comment]
Do'h! Sorry!! I'll go ahead and close this. I figured it was something I was missing. Thanks for your help.
