### ISSUE TITLE
harden chrony by not having it listen

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4465]
## Harden chrony by having it not listen
#CONFIG="/etc/chrony.conf"
#echo -e "port 0" >> $CONFIG

**Comment by jan-cerny** [comment]
Fixed in #4445

**Comment by rptaylor** [comment]
This is no longer applicable in EL8; setting 'port 0' is redundant and unnecessary because the behaviour of newer versions of chrony is to not listen on the NTP port if 'allow' is not defined , which is the default.
