### ISSUE TITLE
Should aes192-cbc be removed from ssh ciphers?

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4468]
Was not mentioned in ospp kickstart.

Might need to check with sgrubb.

**Comment by yuumasato** [comment]
> ref is guide/services/ssh/ssh_server/sshd_use_approved_ciphers/rule.yml

The referenced rule is based on FIPS.

Per analysis by @stevegrubb, OSPP is stricter on allowed ciphers.
 
This should be covered by #4663, which configures `Ciphers` as the intersection between FIPS and OSPP Ciphers.
