### ISSUE TITLE
should ssh MACs be updated?

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4470]
Common criteria list only allows:

#echo -e "MACs hmac-sha2-256,hmac-sha2-512" >> $CONFIG

But rule has:
`````
Only the following message authentication codes are FIPS 140-2 certified on {{{ full_name }}}:
    <br />- hmac-sha1
    <br />- hmac-sha2-256
    <br />- hmac-sha2-512
    <br />- hmac-sha1-etm@openssh.com
    <br />- hmac-sha2-256-etm@openssh.com
    <br />- hmac-sha2-512-etm@openssh.com
    <br /><br />
`````

ref: guide/services/ssh/ssh_server/sshd_use_approved_macs/rule.yml

**Comment by yuumasato** [comment]
This is configured by rule `harden_sshd_crypto_policy`, implemented in #4663

**Comment by shawndwells** [comment]
That PR does not specifically evaluate the SSH config file. This still seems relevant.

**Comment by yuumasato** [comment]
> That PR does not specifically evaluate the SSH config file.

There is no need to, it is done by system-wide crypto policy.

The MAC algorithms (`-oMACs=hmac-sha2-256,hmac-sha2-512`) are set in [line](https://github.com/ComplianceAsCode/content/pull/4663/files#diff-c1cecaa2db852a7f4b2fc99b8b9bc665R4)  and put into file `/etc/crypto-policies/local.d/opensshserver-ospp.config`.
Then `update-crypto-policies` command will put them into effect, more details in rule [description](https://github.com/ComplianceAsCode/content/pull/4663/files#diff-64b069e364050bbf23b4033cefebbc26R8).

**Comment by yuumasato** [comment]
#4676, sets the baseline crypto-policy to FIPS. Which, for SSHD, is not technically necessary as #4663 overrides the policy to use stricter set of algorithms.

End result is crypto-policy FIPS for all backends, plus stricter settings for SSHD.

**Comment by redhatrises** [comment]
Closing this as starting with RHEL8 sshd_use_approved_macs is no longer the rule for referencing if SSH macs are configured correctly.

**Comment by Chalmiller** [comment]
What rule will be used in its stead? I am currently testing a CentOS7 instance and am getting a false negative from this rule.
