### ISSUE TITLE
new rules: tmux

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4479]
## setup tmux
#mv /tmp/tmux.conf /etc/tmux.conf
#restorecon /etc/tmux.conf
#sed -i 's/^fi/  if [ "$PS1" ]; then\n    [[ $TERM != "screen" ]] \&\& exec tmux\n  fi\nfi/' /etc/bashrc
#sed -i '/tmux$/d' /etc/shells

**Comment by yuumasato** [comment]
Closed by #4740, #4885
