### ISSUE TITLE
sed nullok in system-auth

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4480]
#sed -i 's/nullok//' /etc/pam.d/system-auth

**Comment by jan-cerny** [comment]
@shawndwells We already have a rule for this, see: https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_empty_passwords/rule.yml

**Comment by marcusburghardt** [comment]
The rule mentioned in the https://github.com/ComplianceAsCode/content/issues/4480#issuecomment-506360969 is good.
