### ISSUE TITLE
update rhel packages installed

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4483]
required for common criteria profile:

- [x] cryptsetup-luks
- [x] sssd-ipa
- [x] aide
- [x] binutils
- [x] dnf-automatic
- [x] firewalld
- [x] iptables
- [x] ibcap-ng-utils
- [x] openscap-scanner
- [x] policycoreutils
- [x] python-rhsm
- [x] rng-tools
- [x] sudo
- [x] tar
- [x] tmux
- [x] usbguard
- [x] vim
- [x] audispd-plugins
- [x] scap-security-guide

**Comment by ggbecker** [comment]
In RHEL8 the package `python-rhsm` got replaced by `python3-subscription-manager-rhsm`.
