### ISSUE TITLE
need new rule: max_user_namespaces

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4492]
#echo "# If you know you are have containers that need user namespaces," >> $CONFIG
#echo "# you MAY comment out the next line." >> $CONFIG
#echo "user.max_user_namespaces = 0" >> $CONFIG

**Comment by yuumasato** [comment]
Implemented in #4569

**Comment by yuumasato** [comment]
We may want to override rule severity in the profile to `severity: info`. As this rule is considered optional.
