### ISSUE TITLE
additional FIPS checks in ospp profile?

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4500]
current profile includes:

    ## RHEL 8 CCE-80942-6: Enable FIPS Mode
    - enable_fips_mode

But does not include:
    # - sysctl_crypto_fips_enabled
~~# - enable_dracut_fips_module~~
    # - etc_system_fips_exists

Should it?

**Comment by marcusburghardt** [comment]
OSPP was recently updated and relevant requirements reviewed.
