### ISSUE TITLE
need new rule(s): coredump settings

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4502]
Rules to validate the following : 

    #echo "kernel.core_pattern=|/bin/false" >> $CONFIG
    #sed -i "/^#Storage/s/#Storage=external/Storage=none/" /etc/systemd/coredump.conf
    #sed -i "/^#ProcessSize/s/#ProcessSizeMax=2G/ProcessSizeMax=0/" /etc/systemd/coredump.conf
    #systemctl mask systemd-coredump.socket
    #systemctl mask kdump.service

**Comment by yuumasato** [comment]
Fixed by #4650
