### ISSUE TITLE
Update logic in sshd_use_approved_macs

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4503]
Logic in .//guide/services/ssh/ssh_server/sshd_use_approved_macs/rule.yml should not work for CentOS.

Currently will point to Red Hat paperwork for CentOS and other derivative builds.

**Comment by bbaassssiiee** [comment]
The approved MACs do not all pass https://github.com/arthepsy/ssh-audit.git

**Comment by Chalmiller** [comment]
Is this something that is currently being addressed? I am currently testing this on CentOS7 derivative build and it is currently giving off a false negative.

**Comment by redhatrises** [comment]
It is not and won't be as there is no CentOS certification paperwork for these MACs.

**Comment by bbaassssiiee** [comment]
CIS has a benchmark for Centos 7, it has: "5.2.12 Ensure only approved MAC algorithms are used".

This role is useless for Centos, ComplianceAsCode is about paperwork apparently, not about automation for security.

**Comment by marcusburghardt** [comment]
This rule received updates this meantime. Also, some benchmarks also had changes regarding SSHD MACS. Closing. Please, open a new issue with specific details if still relevant.
