### ISSUE TITLE
update audit_rules_mac_modification/rule.yml to modern audit format

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4504]
Existing rule written for old style:

``-w /etc/selinux/ -p wa -k MAC-policy``

Needs to be updated for:

``-a always,exit -F dir=/etc/selinux/ -F perm=wa -F auid>=1000 -F auid!=unset -F key=MAC-policy``

**Comment by marcusburghardt** [comment]
It is not only applicable to `update audit_rules_mac_modification` rule.
We also have to clarify the pros and cons. Updates on this topic will be centralized in https://github.com/ComplianceAsCode/content/issues/9849.
