### ISSUE TITLE
should audit_rules_privileged_commands_chage be included in rhel8?

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4506]
audit_rules_privileged_commands_chage is not currently included in RHEL 8 common criteria profile. Should it be? Was this an oversight?

**Comment by ggbecker** [comment]
It is covered by the following rules:

https://github.com/ComplianceAsCode/content/blob/0085a63292f63f606e94d86a78aa5314cdd002a2/products/rhel8/profiles/ospp.profile#L389-L405
