### ISSUE TITLE
should audit_rules_privileged_commands_chsh be included in rhel8?

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4507]
Another audit rule was left out of rhel 8 common criteria: ``audit_rules_privileged_commands_chsh``

**Comment by ggbecker** [comment]
It is covered by the following rules:

https://github.com/ComplianceAsCode/content/blob/0085a63292f63f606e94d86a78aa5314cdd002a2/products/rhel8/profiles/ospp.profile#L389-L405
