### ISSUE TITLE
need ansible remediations for audit_rules_privileged_commands_* rules

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4508]
Might be able to template using inspiration from audit_rules_privileged_commands/ansible/shared.yml

**Comment by ThiloSolbrig** [comment]
Found ansible remediations for audit rules trying to loop over empty lists, which actually skips replacing audit rules. Is this what you address by issue #4508 or should I rather open a new one?

ol8-playbook-standard.yml version 0.1.62-1.el8, line 7139ff :
...`
    - name: Perform remediation of Audit rules for /usr/bin/at
      block:

        - name: Declare list of syscalls
          set_fact:
            syscalls: []
            syscall_grouping: []

        - name: Check existence of  in /etc/audit/rules.d/
          find:
            paths: /etc/audit/rules.d
            contains: -a always,exit(( -S |,)\w+)*(( -S |,){{ item }})+(( -S |,)\w+)*
              -F path=/usr/bin/at -F auid>=1000 -F auid!=unset (-k\s+|-F\s+key=)\S+\s*$
            patterns: '*.rules'
          register: find_command
          loop: '{{ (syscall_grouping + syscalls) | unique }}'` <-- loop is skipped due to empty lists
...
        - name: Declare found syscalls
          set_fact: syscalls_found="{{ find_command.results | selectattr('matched') |
            map(attribute='item') | list }}" <-- syscalls_found will be empty due to find_command is empty
...
        - name: Replace the audit rule in {{ audit_file }}
          lineinfile:
            path: '{{ audit_file }}'
            regexp: (-a always,exit)(?=.*(?:(?:-S |,)(?:{{ syscalls_per_file[audit_file]
              | join("|") }}))\b)((?:( -S |,)\w+)+)( -F path=/usr/bin/at -F auid>=1000
              -F auid!=unset (?:-k |-F key=)\w+)
            line: \1\2\3{{ missing_syscalls | join("\3") }}\4
            backrefs: true
            state: present
          when: syscalls_found | length > 0 and missing_syscalls | length > 0 <-- "syscalls_found | length > 0" matches and task will be skipped

**Comment by marcusburghardt** [comment]
Rules are covered by the `audit_rules_privileged_commands` template.
