### ISSUE TITLE
missing rhel8 audit rule: audit_rules_privileged_commands_pam_timestamp_check

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4509]
RHEL 8 common criteria does not include ``audit_rules_privileged_commands_pam_timestamp_check``, should it?

**Comment by marcusburghardt** [comment]
https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_pam_timestamp_check/rule.yml
