### ISSUE TITLE
potential duplication of audit rules?

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4517]
existing common criteria profile has the following audit rules:

`````

    ## User add delete modify. This is covered by pam. However, someone could
    ## open a file and directly create or modify a user, so we'll watch passwd and
    ## shadow for writes
    #-a always,exit -F arch=b32 -S openat,open_by_handle_at -F a2&03 -F path=/etc/passwd -F auid>=1000 -F auid!=unset -F key=user-modify
    #-a always,exit -F arch=b64 -S openat,open_by_handle_at -F a2&03 -F path=/etc/passwd -F auid>=1000 -F auid!=unset -F key=user-modify
    #-a always,exit -F arch=b32 -S open -F a1&03 -F path=/etc/passwd -F auid>=1000 -F auid!=unset -F key=user-modify
    #-a always,exit -F arch=b64 -S open -F a1&03 -F path=/etc/passwd -F auid>=1000 -F auid!=unset -F key=user-modify
    #-a always,exit -F arch=b32 -S openat,open_by_handle_at -F a2&03 -F path=/etc/shadow -F auid>=1000 -F auid!=unset -F key=user-modify
    #-a always,exit -F arch=b64 -S openat,open_by_handle_at -F a2&03 -F path=/etc/shadow -F auid>=1000 -F auid!=unset -F key=user-modify
    #-a always,exit -F arch=b32 -S open -F a1&03 -F path=/etc/shadow -F auid>=1000 -F auid!=unset -F key=user-modify
    #-a always,exit -F arch=b64 -S open -F a1&03 -F path=/etc/shadow -F auid>=1000 -F auid!=unset -F key=user-modify
`````

However, these files also have watches on them:
`````


    #################################################################
    ##
    ## Audit Group Add, Delete, and Modify
    ##
    ## These events are covered by PAM. However, someone could
    ## open a file and directly create or modify a user or group, so
    ## we'll watch the files directly for write activity.
    ##
    #################################################################
    
    ## RHEL 8 CCE-80758-6: Record Events that Modify User/Group Information - /etc/group
    - audit_rules_usergroup_modification_group

    ## RHEL 8 CCE-80759-4: Record Events that Modify User/Group Information - /etc/gshadow
    - audit_rules_usergroup_modification_gshadow

    ## RHEL 8 CCE-80761-0: Record Events that Modify User/Group Information - /etc/passwd
    - audit_rules_usergroup_modification_passwd

    ## RHEL 8 CCE-80762-8: Record Events that Modify User/Group Information - /etc/shadow
    - audit_rules_usergroup_modification_shadow
`````

Are these duplicate?

**Comment by shawndwells** [comment]
Looked closer and noticed the ``-F a2&03`` bit. So instead of being duplicate... many new rules need to be created.

**Comment by yuumasato** [comment]
These rules already exist:

>     ## User add delete modify. This is covered by pam. However, someone could
>     ## open a file and directly create or modify a user, so we'll watch passwd and
>     ## shadow for writes
>     #-a always,exit -F arch=b32 -S openat,open_by_handle_at -F a2&03 -F path=/etc/passwd -F auid>=1000 -F auid!=unset -F key=user-modify
>     #-a always,exit -F arch=b64 -S openat,open_by_handle_at -F a2&03 -F path=/etc/passwd -F auid>=1000 -F auid!=unset -F key=user-modify
- https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_etc_passwd_openat/rule.yml
- https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_etc_passwd_open_by_handle_at/rule.yml

>     #-a always,exit -F arch=b32 -S open -F a1&03 -F path=/etc/passwd -F auid>=1000 -F auid!=unset -F key=user-modify
>     #-a always,exit -F arch=b64 -S open -F a1&03 -F path=/etc/passwd -F auid>=1000 -F auid!=unset -F key=user-modify
- https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_etc_passwd_open/rule.yml

>     #-a always,exit -F arch=b32 -S openat,open_by_handle_at -F a2&03 -F path=/etc/shadow -F auid>=1000 -F auid!=unset -F key=user-modify
>     #-a always,exit -F arch=b64 -S openat,open_by_handle_at -F a2&03 -F path=/etc/shadow -F auid>=1000 -F auid!=unset -F key=user-modify
- https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_etc_shadow_openat/rule.yml
- https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_etc_shadow_open_by_handle_at/rule.yml

>     #-a always,exit -F arch=b32 -S open -F a1&03 -F path=/etc/shadow -F auid>=1000 -F auid!=unset -F key=user-modify
>     #-a always,exit -F arch=b64 -S open -F a1&03 -F path=/etc/shadow -F auid>=1000 -F auid!=unset -F key=user-modify
- https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_etc_shadow_open/rule.yml

**Comment by shawndwells** [comment]
Thanks! Updated OSPP PR.
