### ISSUE TITLE
should audit_dac_actions/audit_rules_dac_modification_lchown and audit_unsuccessful_file_modification/audit_rules_unsuccessful_file_modification_lchown be deduplicated?

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4520]
should audit_dac_actions/audit_rules_dac_modification_lchown and audit_unsuccessful_file_modification/audit_rules_unsuccessful_file_modification_lchown be deduplicated?

**Comment by ggbecker** [comment]
- audit_rules_dac_modification_lchown captures all events even if they are successful
- audit_rules_unsuccessful_file_modification_lchown only captures unsuccessful events if the exit code is the following:
https://github.com/ComplianceAsCode/content/blob/0085a63292f63f606e94d86a78aa5314cdd002a2/shared/templates/audit_rules_unsuccessful_file_modification/ansible.template#L20

So, they are different although can be considered a subset of the other.
