### ISSUE TITLE
rhel 8 missing rule, "audit_unsuccessful_file_modification/audit_rules_unsuccessful_file_modification_open_rule_order"

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4524]
RHEL 8 common criteria missing ``audit_unsuccessful_file_modification/audit_rules_unsuccessful_file_modification_open_rule_order``, should it be included?

**Comment by ggbecker** [comment]
It is covered by the following rules:

https://github.com/ComplianceAsCode/content/blob/0085a63292f63f606e94d86a78aa5314cdd002a2/products/rhel8/profiles/ospp.profile#L389-L405
