### ISSUE TITLE
rhel 8 missing rule, "openat_o_creat"

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4532]
rhel 8 common criteria profile missing ``audit_unsuccessful_file_modification/audit_rules_unsuccessful_file_modification_openat_o_creat``, should it be included?

**Comment by ggbecker** [comment]
It is covered by the following rules:

https://github.com/ComplianceAsCode/content/blob/0085a63292f63f606e94d86a78aa5314cdd002a2/products/rhel8/profiles/ospp.profile#L389-L405
