### ISSUE TITLE
Unreachable code on build infrastructure code

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#4581]
#### Description of problem:
Unreachable code on:
https://github.com/ComplianceAsCode/content/blob/d9c6203c9df477c2d7bf1cc73609ea65e9ac0a06/ssg/yaml.py#L178
and
https://github.com/ComplianceAsCode/content/blob/d9c6203c9df477c2d7bf1cc73609ea65e9ac0a06/ssg/build_remediations.py#L318

Investigate if they are still relevant and remove if not.

**Comment by jan-cerny** [comment]
I have checked the code and they both seem to be replaced by the code above them. I suggest removing them.

**Comment by jan-cerny** [comment]
The first one has been removed in #4713 .

**Comment by jan-cerny** [comment]
The second has been removed in #4063 .
