### ISSUE TITLE
complete_ocil_entry_audit_successful_syscall refinement

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4585]
Many of the syscall audit rules require special flags, e.g. ``-F a2&01003``, however the macros such as ``complete_ocil_entry_audit_successful_syscall`` are not aware of them.

The macros or rules should be updated to be more accurate.

**Comment by marcusburghardt** [comment]
Old issue without interaction and likely no longer relevant. Closing.
