### ISSUE TITLE
OVAL check for file permissions fails when the file is not existent

### ISSUE THREAD

**Issue by matejak** [ComplianceAsCode/content#4644]
#### Description of problem:

Fresh installation of RHEL7.7 selecting OSPP profile in custom security section causes file_permissions_sshd_pub_key and file_permissions_sshd_private_key remediation to fail. The files which these rules checks don't exist during RHEL7 installation then the OVAL check fails to verify.

#### Steps to Reproduce:

1. Install RHEL7.7
2. Select OSPP profile in Security Policy section
3. check /root/openscap_data/eval_remediate_report.html
4. Look for rules file_permissions_sshd_pub_key and file_permissions_sshd_private_key

Actual results:
Rule results in error

Expected results:
Rule is fixed or pass

Additional info:
The OVAL check is `templated` in this case, meaning that others rules which use this same OVAL check need to be investigated and evaluated accordingly.

This issue is also tracked at https://bugzilla.redhat.com/show_bug.cgi?id=1721045

**Comment by matejak** [comment]
There are several points here:

- The template `shared/templates/template_..._file_permissions` is not used very much. Respective CSVs s.a. `rhel7/templates/csv/file_dir_permissions.csv` contain entries only for some rules of `file_permissions_..` IDs.
- Usually, those checked files are supposed to exist, it is not expected that they would not exist.
- The SSH keys case can't be tested by the SSG Test Suite, as SSHD doesn't seem to like deletion of its keys even if it is not restarted.

Given that, I propose to consider the SSH check is a specialized one, i.e. to remove it from the template and possibly implement it with the help of jinja OVAL macros.

**Comment by marcusburghardt** [comment]
The expected result is already happening:
```
[root@rhel79 ~]# rm /etc/ssh/*.pub
rm: remove regular file ‘/etc/ssh/ssh_host_rsa_key.pub’? y
[root@rhel79 ~]# rm /etc/ssh/*_key
rm: remove regular file ‘/etc/ssh/ssh_host_rsa_key’? y

[root@rhel79 ~]# oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_stig --rule xccdf_org.ssgproject.content_rule_file_permissions_sshd_pub_key --results-arf /tmp/arf.xml --report /tmp/report.html --oval-results /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
...
Title   Verify Permissions on SSH Server Public *.pub Key Files
Rule    xccdf_org.ssgproject.content_rule_file_permissions_sshd_pub_key
Ident   CCE-27311-0
Result  pass

[root@rhel79 ~]# oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_stig --rule xccdf_org.ssgproject.content_rule_file_permissions_sshd_private_key --results-arf /tmp/arf.xml --report /tmp/report.html --oval-results /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
...
Title   Verify Permissions on SSH Server Private *_key Key Files
Rule    xccdf_org.ssgproject.content_rule_file_permissions_sshd_private_key
Ident   CCE-27485-2
Result  pass
```
