### ISSUE TITLE
Errors during build (OVAL) Ubuntu 16.04 in AWS

### ISSUE THREAD

**Issue by r4yfx** [ComplianceAsCode/content#4672]
#### Description of problem:

-- Scanning for dependencies of ubuntu1604 fixes (bash, ansible, puppet and anaconda)...
-- Scanning for dependencies of ubuntu1604 checks (OVAL)...
-- Configuring incomplete, errors occurred!

#### SCAP Security Guide Version:

0.1.45

#### Operating System Version:
Ubuntu 16.04

#### Steps to Reproduce:

1. AWS Instance  (t2-micro)
2. wget zipped file and unzip
3.  run build_product ubuntu1604

#### Actual Results:
-- Scanning for dependencies of ubuntu1604 fixes (bash, ansible, puppet and anaconda)...
-- Scanning for dependencies of ubuntu1604 checks (OVAL)...
-- Configuring incomplete, errors occurred!

#### Expected Results:
Build/install to complete

#### Addition Information/Debugging Steps:

log only has; 
The system is: Linux - 4.4.0-1088-aws - x86_64

ubuntu@ip-***-***-***-***:~/content-0.1.45$ cat /etc/issue
Ubuntu 16.04.6 LTS \n \l

ubuntu@ip-172-31-22-45:~/content-0.1.45$

**Comment by ggbecker** [comment]
Stale issue. Cleaning up since ubuntu1604 is not supported anymore and should be removed from the project. Other ubuntu products are being tested in github actions. I'm going to create an issue to track the removal of ubuntu1604 product removal.

**Comment by ggbecker** [comment]
example how to build on ubuntu: https://github.com/ComplianceAsCode/content/blob/66996f8cd43ff97923fc65017a14a0701d2a01f3/.github/workflows/gate.yaml#L76
