### ISSUE TITLE
Rule auditd_write_logs passes even if the scanner cannot read respecitve configuration file

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#4700]
#### Description of problem:
The rule `auditd_write_logs` passes even if the configuration from the configuration file can't be read because the user which runs the scanner doesn't have read privileges.

#### SCAP Security Guide Version:
current upstream as of 68aacd11afeeee2b0efde39ed4c0b5a4469b82ad

#### Operating System Version:
Fedora 30, but should affect everything

#### Steps to Reproduce:

1. set `write_logs = no` in ` /etc/audit/auditd.conf`
2. run as normal (non-root) user `oscap xccdf eval --profile ospp --rule xccdf_org.ssgproject.content_rule_auditd_write_logs build/ssg-fedora-ds.xml`

#### Actual Results:
pass

#### Expected Results:
error

#### Addition Information/Debugging Steps:
`-rw-r-----. 1 root root 855 Aug  9 16:09 /etc/audit/auditd.conf`

**Comment by marcusburghardt** [comment]
I believe this issue can be closed. Could you confirm @jan-cerny ?

**Comment by Mab879** [comment]
Fixed.

**Comment by jan-cerny** [comment]
I believe this hasn't been fixed. However, it shouldn't be considered a bug because the users are expected to run oscap as root.
