### ISSUE TITLE
ID and Title of new RHEL7 USGCB profile

### ISSUE THREAD

**Issue by dahaic** [ComplianceAsCode/content#4707]
#### Description of problem:
With the PR #4705 we are cleaning up OSPP profile so it's purely implementation of OSPP guidance. We need to preserve the USGCB profile (originally under ID `ospp`). Aforementioned PR moves it to ID `ncp`. It's not fully understood what is the best ID, but it's preferable to merge the PR and fix this a bit later.

I am setting the BLOCKER label here, as we really need to solve this before the release. And I am assigning Shawn as I believe he has most to say about this :)

**Comment by yuumasato** [comment]
@shawndwells Hello, do you have any updates on this?
