### ISSUE TITLE
Failing check on audit_rules_privileged_commands

### ISSUE THREAD

**Issue by aymeric-dev** [ComplianceAsCode/content#4769]
#### Description of problem:
When I run RHEL7 "STIG" profile remediation, the two following check fails:

    - audit_rules_privileged_commands
    - audit_rules_privileged_commands_newgrp

audit_rules_privileged_commands_newgrp error:

```
sed: -e expression #1, char 93: unterminated address regex
sed: can't read /etc/audit/rules.d/privileged.rules
: No such file or directory
```
Indeed, in /etc/audit/rules.d, I have these files:

> -rw-r--r--. 1 root root 4300 20 août  16:31 30-ospp-v42-remediation.rules
> -rw-r-----. 1 root root   68 20 août  16:31 actions.rules
> -rw-------. 1 root root  163 20 août  16:31 audit.rules
> -rw-r-----. 1 root root  305 20 août  16:31 audit_rules_usergroup_modification.rules
> -rw-r-----. 1 root root  646 20 août  16:31 delete.rules
> -rw-r--r--. 1 root root  160 20 août  16:31 delete.rules?
> -rw-r-----. 1 root root  150 20 août  16:31 export.rules
> -rw-r--r--. 1 root root  102 20 août  16:31 immutable.rules
> -rw-r-----. 1 root root  110 20 août  16:31 logins.rules
> -rw-r-----. 1 root root  543 20 août  16:31 modules.rules
> -rw-r-----. 1 root root 2022 20 août  16:31 perm_mod.rules
> -rw-r--r--. 1 root root  164 20 août  16:31 perm_mod.rules?
> -rw-r-----. 1 root root 3351 20 août  16:31 privileged.rules
> -rw-r--r--. 1 root root   96 20 août  16:31 privileged.rules?
> 

where the "?" is a "\n"

The parameter seems to be duplicated:
the **newgrp [...] -F key=privileged** param is in privileged.rules? file
the **newgrp [...] -k privileged** param is in privileged.rules file

#### SCAP Security Guide Version:
0.1.45

#### Operating System Version:
rhel 7.6

#### Steps to Reproduce:

1. Run oscap remediation with rhel7 stig profile

#### Actual Results:
error

#### Expected Results:
pass

**Comment by trevor-vaughan** [comment]
I'm also seeing this failure in ``v0.1.46``.

```
[root@el7 rules.d]# auditctl -l | grep newgrp
-a always,exit -S all -F path=/usr/bin/newgrp -F perm=x -F auid>=1000 -F auid!=-1 -F key=special-config-changes
-a always,exit -S all -F path=/bin/newgrp -F perm=x -F auid>=1000 -F auid!=-1 -F key=special-config-changes
-a always,exit -S all -F path=/usr/bin/newgrp -F perm=x -F auid>=1000 -F auid!=-1 -F key=setuid/setgid
```
