### ISSUE TITLE
RHEL 8 ansible roles still say they're for RHEL 7

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4833]
RHEL 8 ansible roles still say they're for RHEL 7, e.g.:
https://github.com/RedHatOfficial/ansible-role-rhel8-pci-dss

@redhatrises is this something you could take a look at?

**Comment by redhatrises** [comment]
Looks like this is only an issue with pci-dss. Fixed and closing.

**Comment by shawndwells** [comment]
On 9/13/19 12:29 PM, Gabe Alford wrote:
> Looks like this is only an issue with pci-dss. Fixed and closing.



Thanks!
