### ISSUE TITLE
STIG Viewer reference discrepancy

### ISSUE THREAD

**Issue by abergmann** [ComplianceAsCode/content#4846]
#### Description of problem:

After commit [5a7c92a1c8](https://github.com/ComplianceAsCode/content/commit/5a7c92a1c8) the OpenSCAP STIG Viewer output (```oscap xccdf eval --stig-viewer```) is not working anymore. The output is missing the ```<rule-result/>``` section.

This is caused by different STIG Viewer references between OpenSCAP/openscap and ComplianceAsCode/content. 

Here are the lines in question:

ComplianceAsCode/content: [ssg/constants.py#L40](https://github.com/ComplianceAsCode/content/blob/master/ssg/constants.py#L40)
```stig_ns = "https://public.cyber.mil/stigs/srg-stig-tools/"```

OpenSCAP/openscap: [src/XCCDF/result.c#L73](https://github.com/OpenSCAP/openscap/blob/maint-1.3/src/XCCDF/result.c#L73)
```static const char *DISA_STIG_VIEWER_HREF = "http://iase.disa.mil/stigs/Pages/stig-viewing-guidance.aspx";```

#### SCAP Security Guide Version:
Everything after commit [5a7c92a1c8](https://github.com/ComplianceAsCode/content/commit/5a7c92a1c8).

#### Next
The question is now if we need to roll back this reference inside ComplianceAsCode/content or if we need to adjust the new reference inside OpenSCAP/openscap.

**Comment by redhatrises** [comment]
This ticket needs to be opened against OpenSCAP to handle both as the old urls are no longer valid.

**Comment by redhatrises** [comment]
Closing here as this is an issue with the scanner and not the content.
