### ISSUE TITLE
pam_faillock ... authfail line inserted too early.  Breaks alternative authentication methods, like SSSD and Kerberos

### ISSUE THREAD

**Issue by nwallwo** [ComplianceAsCode/content#4925]
#### Description of problem:
SSG remediation adds a pam_faillock.so line with "authfail", and this line is incorrectly added "after pam_unix.so", when it ought to be added "before pam_deny.so".  This incorrect placement breaks alternative authentication methods, such as Kerberos and SSSD.

If the line had instead been added "before pam_deny.so", this wouldn't be a problem.

#### SCAP Security Guide Version:
scap-security-guide-0.1.43-13.el7.noarch

#### Operating System Version:
RHEL 7.7 Workstation

#### Steps to Reproduce:
I have systems configured to use pam_sss.so or pam_krb5.so for authentication.  
/etc/pam.d/system-auth and /etc/pam.d/password-auth contain these lines:
```
auth        required      pam_env.so
auth        sufficient    pam_unix.so  try_first_pass
auth        requisite     pam_succeed_if.so uid >= 1000 quiet_success
auth        sufficient    pam_sss.so forward_pass
auth        sufficient    pam_krb5.so use_first_pass
auth        required      pam_deny.so
```

Authentication is working as expected.  

I run the remediation, with this command:
oscap xccdf eval --remediate --profile xccdf_org.ssgproject.content_profile_stig-rhel7-disa --results stig-results.xml --report stig-results.html /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml

#### Actual Results:
After remediation, authentication with SSSD or Kerberos no longer works.

/etc/pam.d/system-auth and /etc/pam.d/password-auth contain these lines:
```
auth        required      pam_env.so
auth        required      pam_faillock.so preauth silent deny=3 unlock_time=never even_deny_root fail_interval=900
auth        sufficient    pam_unix.so  try_first_pass
auth        [default=die] pam_faillock.so authfail deny=3 unlock_time=never even_deny_root fail_interval=900
auth        requisite     pam_succeed_if.so uid >= 1000 quiet_success
auth        sufficient    pam_sss.so forward_pass
auth        sufficient    pam_krb5.so use_first_pass
auth        required      pam_deny.so
```

#### Expected Results:
After remediation, authentication with SSSD or Kerberos continues to work.

This could be accomplished if the authfail line were inserted "before pam_deny.so" instead of being added "after pam_unix.so".

For instance: 
```
auth        required      pam_env.so
auth        required      pam_faillock.so preauth silent deny=3 unlock_time=never even_deny_root fail_interval=900
auth        sufficient    pam_unix.so  try_first_pass
auth        requisite     pam_succeed_if.so uid >= 1000 quiet_success
auth        sufficient    pam_sss.so forward_pass
auth        sufficient    pam_krb5.so use_first_pass
auth        [default=die] pam_faillock.so authfail deny=3 unlock_time=never even_deny_root fail_interval=900
auth        required      pam_deny.so
```

#### Addition Information/Debugging Steps:
Adding the authfail line "before pam_deny.so" would be more consistent with the man page for pam_faillock, which says:
"The authfail argument must be used when the module is called after the modules which determine the authentication outcome, failed. Unless the user is already blocked due to previous authentication failures, the module will record the failure into the appropriate user tally file."

Note the part that says "after the modules which determine the authentication outcome".  Inserting the authfail line after pam_unix incorrectly assumes that it is the only module that determines the authentication outcome.

**Comment by t8m** [comment]
This would effectively disable pam_faillock locking of accounts with uid < 1000.

In this concrete configuration the line
`auth        requisite     pam_succeed_if.so uid >= 1000 quiet_success` 
would have to be changed to
`auth  [success=ok default=2] pam_succeed_if.so uid >= 1000`

**Comment by jan-cerny** [comment]
It's definitely a bug.

Other question is whether we should even attempt to remediate PAM if  pam_sssd, pam_ldap, pam_krb5 or pam_pkcs11 is used there, because that might be complex.

**Comment by opoplawski** [comment]
Another possibility:
```
auth       required pam_env.so
auth       required pam_faildelay.so delay=2000000
auth       [default=1 ignore=ignore success=ok] pam_succeed_if.so uid >= 500 quiet
auth       [default=2 ignore=ignore success=ok] pam_localuser.so
auth       required pam_faillock.so preauth silent unlock_time=0 deny=3 fail_interval=900 even_deny_root
auth       sufficient pam_unix.so  try_first_pass
auth       requisite pam_succeed_if.so uid >= 500 quiet_success
auth       sufficient pam_sss.so forward_pass
auth       [default=1 ignore=ignore success=ok] pam_localuser.so
auth       [default=die] pam_faillock.so authfail unlock_time=0 deny=3 fail_interval=900 even_deny_root
auth       required pam_deny.so
```
But I have to agree that mucking with complex pam configurations is likely to be a loosing game.  And since in most of these cases usually no login users are local it's unlikely to be useful.  Also, modifying pam configs breaks tools like authselect, so it would be better if authselect was able to support adding this kind of configuration.

**Comment by marcusburghardt** [comment]
The approach to insert the `pam_faillock.so authfail` line before the `pam_deny.so` makes sense and is aligned to the `authselect` profile. I will create a fix for this.
