### ISSUE TITLE
OpenShift API server audit log check formatting errors

### ISSUE THREAD

**Issue by nkinder** [ComplianceAsCode/content#4941]
#### Description of problem:

The checks for the OpenShift API server audit log configuration have a few issues with regards to the expected config format.  There are 3 checks that are expecting 2 ':' characters after the "auditConfig" string, though only 1 ':' is expected.  In addition the api_server_audit_log_path check is not tolerant of the path being quoted, which causes the check to fail when a quoted patch is provided in the configuration.

#### SCAP Security Guide Version:

master

#### Operating System Version:

NA

#### Steps to Reproduce:

1. Configure OCP with a quoted API server audit log path as shown in the guide example.
2. Run a scan using the ocp3 master profile against a master node.

#### Actual Results:

The api_server_audit_log_path check fails.

#### Expected Results:

The api_server_audit_log_path check should pass.

**Comment by redhatrises** [comment]
Looks like this was fixed in #4942. Closing.
