### ISSUE TITLE
Remove openshift api_server_profiling check

### ISSUE THREAD

**Issue by nkinder** [ComplianceAsCode/content#4943]
The ocp3 opencis-master profile has a check that expects profiling for the API server to be explicitly disabled.  Red Hat has changed their guidance in this area, as API server profiling is protected via RBAC and can be left enabled or disabled as desired.  From a security perspective, we only want to make sure that the web interface for profiling is disabled for the controller.  We already have the controller_disable_profiling check for this.  We should remove the api_server_profiling check.

**Comment by redhatrises** [comment]
Looks like this has been fixed. Thanks @nkinder! Please reopen if not fixed.
