### ISSUE TITLE
OCP4 SCAP content validation is failing

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#4961]
#### Description of problem:
SCAPVal is failing for OCP4 content.

SCAP1.3: https://jenkins.complianceascode.io/job/scap-security-guide-scapval-scap-1.3/119/console
SCAP1.2: https://jenkins.complianceascode.io/job/scap-security-guide-scapval-scap-1.2/120/console

Those are the failing base requirements extracted from:
https://jenkins.complianceascode.io/job/scap-security-guide-scapval-scap-1.2/ws/build/ssg-ocp4-ds-1.2.xml.result.xml
```
    <base-requirement id="SRC-15">
      <status>FAIL</status>
      <derived-requirement id="SRC-15-1">
        <status>FAIL</status>
        <test test-id-ref="scap-general-scap-content-every-cpe-equal-subset2">
          <status>FAIL</status>
          <message>'scap:data-stream scap_org.open-scap_datastream_from_xccdf_ssg-ocp4-xccdf-1.2.xml'</message>
          <location line="3" column="125" href="file:/home/jenkins/workspace/scap-security-guide-scapval-scap-1.2/build/ssg-ocp4-ds-1.2.xml" xpath="/*[local-name()='data-stream-collection' and namespace-uri()='http://scap.nist.gov/schema/scap/source/1.2'][1]/*[local-name()='data-stream' and namespace-uri()='http://scap.nist.gov/schema/scap/source/1.2'][1]"/>
        </test>
```

**Comment by yuumasato** [comment]
>  </base-requirement>
>     <base-requirement id="SRC-15">
>       <status>FAIL</status>
>       <derived-requirement id="SRC-15-1">
>         <status>FAIL</status>
>         <test test-id-ref="scap-general-scap-content-every-cpe-equal-subset2">
>           <status>FAIL</status>

This could be caused by the cpe-dictionaries again, :(.

The other ones are in warnings statuses.

**Comment by ggbecker** [comment]
So, I will remove the warnings... I didn't know exactly if they were a problem or not. Thank you for noticing that.

**Comment by dahaic** [comment]
The result file linked is not accessible to me.

**Comment by ggbecker** [comment]
> The result file linked is not accessible to me.

Unfortunately it got deleted when I re triggered the build on jenkins. I have it here... I'll attach somewhere soon.

**Comment by ggbecker** [comment]
Stabilization branch does not FAIL (scap1.2 ok, scap1.3 pending results) on SCAPVal. And the only difference from master so far is #4933. So it might be some issue with these changes.

**Comment by ggbecker** [comment]
> The result file linked is not accessible to me.
[ssg-ocp4-ds-1.2.xml.result.xml.txt](https://github.com/ComplianceAsCode/content/files/3797449/ssg-ocp4-ds-1.2.xml.result.xml.txt)

**Comment by ggbecker** [comment]
Removing milestone as the issue is not present on stabilization branch.

**Comment by evgenyz** [comment]
Still it's a problem.

How can I run this test manually?

@yuumasato Can you please elaborate where I can find previous problem description and fix?

**Comment by ggbecker** [comment]
> Still it's a problem.
> 
Agree, it's just that I removed the milestone for release 0.1.47 (because the stabilization branch does not contain this issue), but it is still a blocker for master and next releases (0.1.48 and further)
> How can I run this test manually?

There is a tool called `run_scapval.py` which is a python script and you can run a similar command to the one jenkins run:
```
$WORKSPACE/tests/run_scapval.py --scap-version 1.3 --scapval-path /opt/scapval/scapval-1.3.2.jar --build-dir $WORKSPACE/build
```
So you can build only the OCP4 content and run this command. You also must have `scapval-1.3.2.jar`  tool which can be found here: [NIST](https://csrc.nist.gov/Projects/Security-Content-Automation-Protocol/SCAP-Releases/SCAP-1-3) -> specifically this zip file: [SCAPVal 1.3.2](https://csrc.nist.gov/CSRC/media/Projects/Security-Content-Automation-Protocol/tools/scap/1.3/SCAP-Content-Validation-Tool-1.3.2.zip)
> 
> @yuumasato Can you please elaborate where I can find previous problem description and fix?

It seems that some CPEs are missing and I talked to @yuumasato and he thinks that copying the CPE files from RHEL8 to OCP4 product might solve the issue. You may want to give it a try.

**Comment by yuumasato** [comment]
> @yuumasato Can you please elaborate where I can find previous problem description and fix?

@evgenyz When the the `linux_os` rules became part of OCP4 DS, rules with package `platform` became part of it. And they have applicability checks that are defined as CPE OVALs, and these CPEs need to have an entry in the dictionary.
I suspect that just updating the OCP4 CPE dictionary will solve the problem with `scapval`. Something like this https://github.com/ComplianceAsCode/content/pull/4273.

**Comment by yuumasato** [comment]
BTW, It's about time have something smarter for CPE dictionaries.
