### ISSUE TITLE
chronyd_or_ntpd_set_maxpoll does not check pools

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#4964]
#### Description of problem:
Rule chronyd_or_ntpd_set_maxpoll check if all time sources in `/etc/chrony.conf` specified by `server` keyword have `maxpoll` option set. However, it doesn't check sources specified as `pool` or other possible sources. A `pool` seems to be the default option on RHEL 8, at least on my fresh installation there is no `server` specified.

#### SCAP Security Guide Version:
current upstream head as of 7075c11504dba2d18dad33e08ca5e92e97077fc1

#### Operating System Version:
RHEL 8

#### Steps to Reproduce:

1. configure pool in `/etc/chrony.conf` instead of server
2. evaluate  chronyd_or_ntpd_set_maxpoll

#### Actual Results:
maxpoll is checked only on lines starting with `server`

#### Expected Results:
Investigate if it should check also on `pool` or other sources.

**Comment by marcusburghardt** [comment]
I believe this is already fixed. Could you confirm @jan-cerny?

**Comment by Mab879** [comment]
It seems that this still might be an issue.

**Comment by Mab879** [comment]
All being checked: https://github.com/ComplianceAsCode/content/blob/cf82959e3b2a704556427be44b511f82a56e1912/linux_os/guide/services/ntp/chronyd_or_ntpd_set_maxpoll/oval/shared.xml#L43
