### ISSUE TITLE
New rules for authselect

### ISSUE THREAD

**Issue by redhatrises** [ComplianceAsCode/content#4977]
#### Description of problem:

authconfig has been replaced with authselect in Fedora and RHEL8. We need to update rules as such.

**Comment by hgs-creyno08** [comment]
Bump. RHEL8.4 using [this kickstart](https://github.com/ComplianceAsCode/content/blob/master/products/rhel8/kickstart/ssg-rhel8-stig-ks.cfg) currently produces this error.

![authselectError](https://user-images.githubusercontent.com/85173651/126206182-ae2cf051-23b4-4edd-b840-b27efe0e840d.png)

**Comment by marcusburghardt** [comment]
PAM related rules are already updated and compatible with `authselect`.
