### ISSUE TITLE
exec-shield description should be updated

### ISSUE THREAD

**Issue by redhatrises** [ComplianceAsCode/content#4980]
#### Description of problem:

Looks like exec-shield is no longer configurable via sysctl in RHEL8 and Fedora. We should disable the rule for future releases.

**Comment by redhatrises** [comment]
Looks like the a rule needs to be updated for handling RHEL8.

**Comment by marcusburghardt** [comment]
It is unclear the issue here and the `sysctl_kernel_exec_shield` rule seems updated. Closing the issue.
