### ISSUE TITLE
update xccdf for tuned

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#4995]
In https://github.com/ComplianceAsCode/content/pull/4877 , there was a discussion of why tuned is disabled in many regulatory profiles. ``tuned`` runs as root, cannot be configured to run non-privilged, and is installed by default. Many regulatory requirements exist about removing non-essential capabilities, which ``tuned`` qualifies as.

Should the XCCDF description of ``tuned`` be updated to allow for running "per mission need" or similar language? This would ensure that tuned is removed except under specific circumstances.

**Comment by marcusburghardt** [comment]
The current version of `package_tuned_removed` rule already contains warnings and a good description. Also, it is now present in one single profile for `rhel8` and `ol8`. No further action is needed regarding this issue.
