### ISSUE TITLE
Incorrect description provided in report.html for fixing failing rule xccdf_org.ssgproject.content_rule_dconf_gnome_banner_enabled

### ISSUE THREAD

**Issue by amitkumar50** [ComplianceAsCode/content#4997]
#### Description of problem:

Problem-1: dconf not installed test passes.
`# rpm -qa|grep dconf`
`# oscap xccdf eval --rule  xccdf_org.ssgproject.content_rule_dconf_gnome_banner_enabled --profile <> --tailoring-file test.xml --results results.xml --report report.html  ./ssg-rhel7-ds.xml`
WARNING: This content points out to the remote resources. Use `--fetch-remote-resources' option to download them.
WARNING: Skipping https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2 file which is referenced from XCCDF content
Title   Enable GNOME3 Login Warning Banner
Rule    xccdf_org.ssgproject.content_rule_dconf_gnome_banner_enabled
Ident   CCE-26970-4
Result  pass

Problem-2: dconf installed, test failed, applying suggested action items in 'report.html'
`********report.html*************`
In the default graphical environment, configuring the login warning banner text in the GNOME Display Manager's login screen can be configured on the login screen by setting banner-message-text to string 'APPROVED_BANNER' where APPROVED_BANNER is the approved banner for your environment. 

To enable, add or edit banner-message-text to /etc/dconf/db/gdm.d/00-security-settings. For example:

[org/gnome/login-screen]
banner-message-text='APPROVED_BANNER'
Once the setting has been added, add a lock to /etc/dconf/db/gdm.d/locks/00-security-settings-lock to prevent user modification. For example:
/org/gnome/login-screen/banner-message-text
After the settings have been set, run dconf update. When entering a warning banner that spans several lines, remember to begin and end the string with ' and use \n for new lines.
`********************************`
-> After following actions mentioned above scan still fails for above test 'xccdf_org.ssgproject.content_rule_dconf_gnome_banner_enabled'.

What fixed the issue?
`# vim /etc/dconf/db/gdm.d/00-security-settings`
[org/gnome/login-screen]
banner-message-enable=true        <<<<<<<<<<<<<<<<<<<<
banner-message-text=string 'Hello World'
`# vim /etc/dconf/db/gdm.d/locks/00-security-settings-lock`
/org/gnome/login-screen/banner-message-enable
`# dconf update`

So, 'banner-message-enable=true' is missing from report.html.

What fixed the issue?
`# vim /etc/dconf/db/gdm.d/00-security-settings`
[org/gnome/login-screen]
banner-message-enable=true
banner-message-text=string 'Hello World'
`# vim /etc/dconf/db/gdm.d/locks/00-security-settings-lock`
/org/gnome/login-screen/banner-message-enable
`# dconf update`

In which file does the changes go?
./linux_os/guide/system/accounts/accounts-banners/gui_login_banner/dconf_gnome_banner_enabled/rule.yml ?

#### SCAP Security Guide Version:
scap-security-guide-0.1.43-13

#### Operating System Version:
Red Hat Enterprise Linux 7.6

#### Steps to Reproduce:
mentioned above.
1.
2.
3.
4.

#### Actual Results:
After following actions mentioned above scan still fails for above test 'xccdf_org.ssgproject.content_rule_dconf_gnome_banner_enabled'.

#### Expected Results:
Complete steps for fixing the failing rule 'xccdf_org.ssgproject.content_rule_dconf_gnome_banner_enabled' should be provided in 'report.html'.

**Comment by yuumasato** [comment]
Hello @amitkumar50 

> Problem-1: dconf not installed test passes.
> `# rpm -qa|grep dconf`
> `# oscap xccdf eval --rule xccdf_org.ssgproject.content_rule_dconf_gnome_banner_enabled --profile <> --tailoring-file test.xml --results results.xml --report report.html ./ssg-rhel7-ds.xml`
> WARNING: This content points out to the remote resources. Use `--fetch-remote-resources' option to download them.
> WARNING: Skipping https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2 file which is referenced from XCCDF content
> Title Enable GNOME3 Login Warning Banner
> Rule xccdf_org.ssgproject.content_rule_dconf_gnome_banner_enabled
> Ident CCE-26970-4
> Result pass

This is expected to happen If `dconf` is not installed. There is no `dconf` setting to configure, so rule passes, no finding is reported.



> Problem-2: dconf installed, test failed, applying suggested action items in 'report.html'
> `********report.html*************`
> In the default graphical environment, configuring the login warning banner text in the GNOME Display Manager's login screen can be configured on the login screen by setting banner-message-text to string 'APPROVED_BANNER' where APPROVED_BANNER is the approved banner for your environment.
> 
> To enable, add or edit banner-message-text to /etc/dconf/db/gdm.d/00-security-settings. For example:
> 
> [org/gnome/login-screen]
> banner-message-text='APPROVED_BANNER'
> Once the setting has been added, add a lock to /etc/dconf/db/gdm.d/locks/00-security-settings-lock to prevent user modification. For example:
> /org/gnome/login-screen/banner-message-text
> After the settings have been set, run dconf update. When entering a warning banner that spans several lines, remember to begin and end the string with ' and use \n for new lines.
> `********************************`
> -> After following actions mentioned above scan still fails for above test 'xccdf_org.ssgproject.content_rule_dconf_gnome_banner_enabled'.
> 
> What fixed the issue?
> `# vim /etc/dconf/db/gdm.d/00-security-settings`
> [org/gnome/login-screen]
> banner-message-enable=true <<<<<<<<<<<<<<<<<<<<
> banner-message-text=string 'Hello World'
> `# vim /etc/dconf/db/gdm.d/locks/00-security-settings-lock`
> /org/gnome/login-screen/banner-message-enable
> `# dconf update`
> 
> So, 'banner-message-enable=true' is missing from report.html.

The description for the rule seems to be from `dconf_gnome_login_banner_text`, and instructions to fix seem to be for `dconf_gnome_banner_enabled`.
It seems to me that you are looking at description of one rule and how fix a second rule.

**Comment by matusmarhefka** [comment]
@amitkumar50 Any updates here?

**Comment by yuumasato** [comment]
The description of the rules are correct:
- [dconf_gnome_banner_enabled](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-banners/gui_login_banner/dconf_gnome_banner_enabled/rule.yml)
- [dconf_gnome_login_banner_text](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-banners/gui_login_banner/dconf_gnome_login_banner_text/rule.yml)
