### ISSUE TITLE
ansible task "Disable service kdump" does not work in --check mode

### ISSUE THREAD

**Issue by kenyon** [ComplianceAsCode/content#5003]
Ansible task "Disable service kdump" does not work in `--check` mode. See RedHatOfficial/ansible-role-rhel7-stig#18.

**Comment by ggbecker** [comment]
https://github.com/ComplianceAsCode/content/pull/5004 should fix the issue. Basically it adds `check_mode: False` to the template which this rule gets created and should not block anymore from executing the `command` section which only verifies that the socket/service exists.

**Comment by ggbecker** [comment]
Fixed by #5004
