### ISSUE TITLE
why does OSPP remove sendmail?

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#5013]
Was this rule inherited from years past, or is there a reason to explicitly check if sendmail is not installed?

Sendmail is not installed by default on rhel8.

linux_os/guide/services/mail/package_sendmail_removed/rule.yml

**Comment by yuumasato** [comment]
It may not be installed by default but it is available for install.
This is the rationale in the rule:
```
    The sendmail software was not developed with security in mind and
    its design prevents it from being effectively contained by SELinux.  Postfix
    should be used instead.
```
