### ISSUE TITLE
should DoD STIG inherit linux_os/guide/services/nfs_and_rpc/package_nfs-utils_removed/rule.yml ?

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#5014]
Should DoD STIG for RHEL 8 inherit linux_os/guide/services/nfs_and_rpc/package_nfs-utils_removed/rule.yml ?

**Comment by marcusburghardt** [comment]
Actually, the `package_nfs-utils_removed` is currently explicitly removed from STIG profiles. Closing issue.
