### ISSUE TITLE
remove linux_os/guide/services/sssd/package_sssd-ipa_installed/rule.yml from DoD STIG profile

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#5015]
linux_os/guide/services/sssd/package_sssd-ipa_installed/rule.yml should be removed from DoD STIG profile

**Comment by ggbecker** [comment]
Rule `package_sssd-ipa_installed` is not included in any of the profiles anymore at this moment 70c9aeaf0fd45777993b192899d32635930364f4

Closing this. Feel free to reopen if you think otherwise.
