### ISSUE TITLE
RHEL 8 Build should create SRG mapping table with only RHEL 8 rules

### ISSUE THREAD

**Issue by tedbrunell** [ComplianceAsCode/content#5022]
Current RHEL 8 build process creates a SRG mapping table with over 10,000 rows - it should be less than 400 rows.  The SRG mappings in the table belong to a variety of RHEL releases and not just RHEL 8.  Without the correct SRG mappings in the table, it is hard to finish providing information to DISA for the RHEL 8 STIG.

**Comment by isimluk** [comment]
It is my understanding this has been resolved on master already. Please re-open if anything is missing. Thanks!
