### ISSUE TITLE
Ensure Software Patches Installed started to fail

### ISSUE THREAD

**Issue by nunofernandes** [ComplianceAsCode/content#5030]
#### Description of problem:
I have a AMI build that periodically builds new images and I run the openscap to make sure that it's secure. The build as of 11 of November passed the `Ensure Software Patches Installed started to fail` check but this weekend, it failed.

#### SCAP Security Guide Version:
scap-security-guide-0.1.43-13.el7.centos.noarch

#### Operating System Version:
CentOS Linux release 7.7.1908 (Core)

#### Steps to Reproduce:

1. install centos 7 with openscap and scap-security-guide and do a yum -y update
2. reboot into the latest kernel
3. remove old kernels (package-cleanup --oldkernels --count=1)
4. `oscap xccdf eval --fetch-remote-resources --profile xccdf_org.ssgproject.content_profile_pci-dss --rule xccdf_org.ssgproject.content_rule_security_patches_up_to_date  /usr/share/xml/scap/ssg/content/ssg-centos7-ds.xml`

#### Actual Results:
```
Downloading: https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2 ... ok
Title   Ensure Software Patches Installed
Rule    xccdf_org.ssgproject.content_rule_security_patches_up_to_date
Result  fail
```

#### Expected Results:
```
Downloading: https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2 ... ok
Title   Ensure Software Patches Installed
Rule    xccdf_org.ssgproject.content_rule_security_patches_up_to_date
Result  passed
```

#### Addition Information/Debugging Steps:
```
$ wget https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2
$ oscap oval eval com.redhat.rhsa-RHEL7.xml.bz2 
Definition oval:com.redhat.rhsa:def:20193888: true
Definition oval:com.redhat.rhsa:def:20193887: true
Definition oval:com.redhat.rhsa:def:20193872: true
Definition oval:com.redhat.rhsa:def:20193835: true
Definition oval:com.redhat.rhsa:def:20193834: true
Definition oval:com.redhat.rhsa:def:20193286: true
Definition oval:com.redhat.rhsa:def:20193210: true
Definition oval:com.redhat.rhsa:def:20193197: true
Definition oval:com.redhat.rhsa:def:20193193: true
Definition oval:com.redhat.rhsa:def:20193157: true
Definition oval:com.redhat.rhsa:def:20193128: true
Definition oval:com.redhat.rhsa:def:20193127: true
....
Definition oval:com.redhat.rhba:def:20150386: true
Definition oval:com.redhat.rhba:def:20150364: true
Evaluation done.
```

So, all are true and reading https://bugzilla.redhat.com/show_bug.cgi?id=1674381#c5 they should be false so that the "Ensure Software Patches Installed" passes the check.

Any ideas?

Thanks,
Nuno Fernandes

**Comment by jan-cerny** [comment]
Hi @nunofernandes ,
This is one of the differences between RHEL and CentOS. The file provided by Red Hat (https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2) is applicable only to RHEL. If this file is used to scan CentOS systems the scanner reports that the system vulnerable. Unfortunately, CentOS project doesn't provide a similar database of vulnerabilities. AFAIK CentOS doesn't guarantee accuracy of security fixes and doesn't provide any assurance.

**Comment by nunofernandes** [comment]
@jan-cerny yes.. that's been said several times on several places and I do know about that. But it was working last 11 of Nov. I was just trying to debug on what changed. Does anyone has that file from that date so that I can compare them both and see what changed?

**Comment by redhatrises** [comment]
Closing this as Red Hat OVAL CVE feeds actually don't apply to CentOS, and the Red Hat feeds shouldn't work with CentOS since the community cannot guarantee their security fixes which is a huge security risk.
