### ISSUE TITLE
Regular expressions create false positives about sshd_config

### ISSUE THREAD

**Issue by bbaassssiiee** [ComplianceAsCode/content#5051]
#### Description of problem:

The guide presents very complex regexes in the report that do not validate correct configuration of various elements of the secure shell daemon.

#### SCAP Security Guide Version:

- xccdf_org.ssgproject.content_benchmark_RHEL-7
- xccdf_org.ssgproject.content_profile_C2S
- SCAP Workbench 1.1.5, compiled with Qt 4.8.7, using OpenSCAP 1.3.0
- openscap-1.2.17-4.el7.x86_64
- openscap-scanner-1.2.17-4.el7.x86_64

#### Operating System Version:
CentOS Linux release 7.7.1908 (Core)

#### Steps to Reproduce:

1. git clone https://github.com/dockpack/secure_ssh
2. cd secure_ssh
3. molecule converge
4. audit

#### Actual Results:

![image](https://user-images.githubusercontent.com/10671559/70157583-1cb98280-16b6-11ea-893e-8a30e3dab62c.png)

#### Expected Results:

compliance.

**Comment by bbaassssiiee** [comment]
What is all this gibberish?
```
^[\s]*(?i)Protocol[\s]+2[\s]*(?:|(?:#.*))?$
^[\s]*(?i)LogLevel(?-i)[\s]+INFO[\s]*(?:\|(?:#.*))?$
^[\s]*(?i)PermitRootLogin(?-i)[\s]+no[\s]*(?:|(?:#.*))?$
^[\s]*(?i)ClientAliveInterval[\s]+(\d+)[\s]*(?:|(?:#.*))?$
```

**Comment by redhatrises** [comment]
@bbaassssiiee are you running this as root? If not, SSH rules and checks will error out.

**Comment by bbaassssiiee** [comment]
vagrant

**Comment by redhatrises** [comment]
@bbaassssiiee unfortunately at this point in time, scap-workbench cannot get access to root or cannot use ssh keys and such. PRs welcome at https://github.com/OpenSCAP/scap-workbench to fix this.

**Comment by bbaassssiiee** [comment]
vagrant can sudo NOPASSWD
