### ISSUE TITLE
DISA STIG Content should reflect newest RHEL 7 STIG

### ISSUE THREAD

**Issue by Smithe2413** [ComplianceAsCode/content#5080]
#### Description of problem:
Currently the Ansible Role generated from CoC content aligns with an older version of the DISA STIG. The content should reflect v2r5. 

#### Steps to Reproduce:

1.
2.
3.
4.

**Comment by ggbecker** [comment]
RHEL7 STIG existent content has been analysed and updated according to latest version V2R8.

For latest updates in the RHEL7 STIG look for recent closed pull requests with label SSG-DISA RHEL7 STIG Alignment: [V2R8 Pull requests](https://github.com/ComplianceAsCode/content/pulls?q=is%3Apr+is%3Aclosed+label%3A%22SSG-DISA+RHEL7+STIG+Alignment%22)

Feel free to reopen this issue if you disagree with the current state of RHEL7 STIG.
