### ISSUE TITLE
Permissions on SSH Server Private *_key Key Files not sufficient for Ubuntu 18.04

### ISSUE THREAD

**Issue by Scronkfinkle** [ComplianceAsCode/content#5088]
#### Description of problem:
The OpenSSH server requires stricter permissions than the current `0640` and will ignore private keys with those permissions.

#### SCAP Security Guide Version:
0.1.47

#### Operating System Version:
Ubuntu 18.04

#### Steps to Reproduce:

1. Ensure permissions `0640` are set on a private key in `/etc/ssh/` on an Ubuntu 18.04 machine
2. Start the `sshd` daemon

#### Actual Results:
The keys are ignored as they are not set to a permissive enough version
```
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0640 for '/etc/ssh/ssh_host_ed25519_key' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
key_load_private: bad permissions
Could not load host key: /etc/ssh/ssh_host_ed25519_key
```

#### Expected Results:
the openSSH daemon will load the private keys

#### Addition Information/Debugging Steps:
This appears to have been addressed for OpenSUSE, as can be seen here 
https://github.com/ComplianceAsCode/content/blob/1c026ffd0908a0e5fdfc2a99b02cb8b9f353ce60/linux_os/guide/services/ssh/file_permissions_sshd_private_key/rule.yml#L6-L10

Is there a reason why we should use `0640` and not universally enforce `0600`? If the former, then Ubuntu 18.04 needs must be specifically updated to `0600`

**Comment by redhatrises** [comment]
The reason that `0640` is used is so that ssh can sign keys using the `ssh_keys` group vs root which as far as I am aware is a Fedora/RHEL thing.
