### ISSUE TITLE
Adding a new profile to exist product

### ISSUE THREAD

**Issue by shaharglazner** [ComplianceAsCode/content#5102]
#### Description of problem:
My objective is to have a DISA STIG profile in the `ssg` for Ubuntu 16.04, similar to the DISA STIG profile that exists under rhel7. As far as I understand, to accomplish this, I need to generate a `profile` under the `/profiles` directory. Currently, I'm failing to understand how to accomplish that.

So basically my questions are:
1. How a new profile is being generated? (files under the `/profiles` directory) 
   Is it generated manually? Is there an explanation of how to do it?
2. How is `stig_overlay.xml` being used?
3. How can I get the `xccdf` file used by `create-stig-overlay.py` with the `--ssg-xccdf` flag?

Huge thanks!

#### SCAP Security Guide Version:
Latest

#### Operating System Version:
Ubuntu

**Comment by redhatrises** [comment]
Just a reminder, but an official DISA STIG should exist and copy/paste of the rhel7 profile should be avoided.

1. Profiles under `/profile` are manually generated, so you need to create these. You can check out existing profiles to see the format. Recommend calling it `stig.profile`
2. `stig_overlay.xml` is used to create tables and submission docs for DISA.
3. You need an official DISA STIG as well as a built ssg STIG profile for this to work. So make sure to grab the latest Ubuntu STIG from https://public.cyber.mil/stigs/downloads/

There is also some developer docs at https://github.com/ComplianceAsCode/content/blob/master/docs/manual/developer_guide.adoc

**Comment by shaharglazner** [comment]
Thanks!

So as far as I understand, the steps are:

1. Create, manually, a `stig.profile` for Ubuntu 16.04.
2. Build the SSG 
3. Use `create-stig-overlay.py` with the new ssg with the already built STIG profile to create a `stig_overlay.xml`

Am I right?
Any guidelines on how to create the `stig.profile`? Just read the official DISA STIG and transform the paragraphs from there?
Last question - the `create-stig-overlay.py` requires `xccdf` file, it can work with the `ds` file which the ssg builds? (or it builds both?)

**Comment by redhatrises** [comment]
> Thanks!
> 
> So as far as I understand, the steps are:
> 
>     1. Create, manually, a `stig.profile` for Ubuntu 16.04.
> 
>     2. Build the SSG
> 
>     3. Use `create-stig-overlay.py` with the new ssg with the already built STIG profile to create a `stig_overlay.xml`

You need to use the newly built SSG STIG with the Ubuntu DISA STIG to create and update this file.

> 
> 
> Am I right?
> Any guidelines on how to create the `stig.profile`? Just read the official DISA STIG and transform the paragraphs from there?

The stig.profile will only contain XCCDF rules enabled in the profile as well as profile description and title. You will probably want to add the Ubuntu STIG IDs to the SSG references. Make sure that rules implement one configuration change. If some rules don't exist, you will need to create them.

> Last question - the `create-stig-overlay.py` requires `xccdf` file, it can work with the `ds` file which the ssg builds? (or it builds both?)

Use the XCCDF file and not the DS file. Both are built.

If you can contribute all this back, that would be great! As there are people who have asked for Ubuntu STIG content, but we just haven't had the resources to devote to creating it.

**Comment by marcusburghardt** [comment]
FYI @dodys

**Comment by dodys** [comment]
> FYI @dodys

I believe we can close this ticket as there hasn't been any activity in the last 3 years.
