### ISSUE TITLE
SSH banner not correctly set with DISA STIG ansible script

### ISSUE THREAD

**Issue by rlucente-se-jboss** [ComplianceAsCode/content#5123]
#### Description of problem:
The text for the banner is incorrect after the ansible playbook for the RHEL7 DISA STIG is run.

#### SCAP Security Guide Version:
0.1.43-13.el7

#### Operating System Version:
RHEL 7.7 with latest patches and updates

#### Steps to Reproduce and Actual Results:
1. Install minimal RHEL 7 then subscribe and apply all updates
2. Commands with output (edited, full log attached) ...
[edited-log.txt](https://github.com/ComplianceAsCode/content/files/4092765/edited-log.txt)

#### Expected Results:
Proper DoD banner set for remote ssh

#### Addition Information/Debugging Steps:
[complete-log.txt](https://github.com/ComplianceAsCode/content/files/4092738/complete-log.txt)

**Comment by ggbecker** [comment]
I have tested on
`scap-security-guide-0.1.49-13.el7.noarch`
with the following commands and the banner is being applied correctly.


`ansible-playbook -i "localhost," -c local /usr/share/scap-security-guide/ansible/rhel7-playbook-stig.yml --tags sshd_enable_warning_banner,banner_etc_issue`

Note that the file location has changed between these versions, the playbook is now located at: `/usr/share/scap-security-guide/ansible/rhel7-playbook-stig.yml`

Can you try it again?
