### ISSUE TITLE
Ignition remediation doesn't support variables

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#5145]
#### Description of problem:
The way how variables for Ignition remediations will be consumed are still not defined so current master (adbabd9b9d1d0584f94c37e91b1ef2ac1b81ef45) does not preprocess any variable within Ignition remediations.

#### SCAP Security Guide Version:
current master (adbabd9b9d1d0584f94c37e91b1ef2ac1b81ef45)

https://github.com/ComplianceAsCode/content/blob/adbabd9b9d1d0584f94c37e91b1ef2ac1b81ef45/ssg/build_remediations.py#L517-L518

**Comment by shawndwells** [comment]
@ggbecker any update on this?

**Comment by shawndwells** [comment]
Also needed for audit remediations, eg in ``./linux_os/guide/system/auditing/policy_rules/audit_access_failed/rule.yml``

**Comment by shawndwells** [comment]
https://github.com/ComplianceAsCode/content/pull/5595/ also held up by this

**Comment by ggbecker** [comment]
Ignition is basically deprecated by kubernetes remediation and variables are now supported across various places in OCP content
https://github.com/ComplianceAsCode/content/pulls?q=is%3Apr+is%3Aclosed+author%3AVincent056+variable
