### ISSUE TITLE
The test_rhel8_coreos regex no longer matches

### ISSUE THREAD

**Issue by jhrozek** [ComplianceAsCode/content#5161]
#### Description of problem:
With a recent update of RHCOS, at least in our CI, the test_rhel8_coreos regex no longer matches, because RHCOS changed the format of the PRETTY_NAME field in /etc/os-release. The regex in the code expects only a sequence of digits and dots, the PRETTY_NAME field now contains a dash.

This is quite urgent as we're blocked on our CI. I can build custom content but I'm unsure what regex format is used in openscap (seems to be perl-regexes?).

#### SCAP Security Guide Version:
git master

#### Operating System Version:
recently updated RHCOS, /etc/os-release says "Red Hat Enterprise Linux CoreOS 44.81.202002031330-0 (Ootpa)" which seems to be the issue

#### Steps to Reproduce:

1. grab a very recent OCP4 cluster
2. run a scan
3.
4.

#### Actual Results:
the rules that should match do not

#### Expected Results:
rules should match

#### Addition Information/Debugging Steps:
I can provide a cluster upon request. But the crux of the issue seems to be that the regex expects:
`<ind:pattern operation="pattern match">^PRETTY_NAME=&quot;Red Hat Enterprise Linux CoreOS \d+\.(\d)\d+\.\d+\.\d+ \([\w\s]+\)&quot;$</ind:pattern> `and then compares the saved pattern to "8". That used to match the older RHCOS releases where they would use something like `"PRETTY_NAME="Red Hat Enterprise Linux CoreOS 42.81.20191223.0 (Ootpa)"`. But recent versions changed the name to e.g. "`Red Hat Enterprise Linux CoreOS 44.81.202002031330-0 (Ootpa)`".

My suggestion would be to treat the last part of the version string as just a blob.

**Comment by evgenyz** [comment]
I propose: `<ind:pattern operation="pattern match">^PRETTY_NAME=&quot;Red Hat Enterprise Linux CoreOS \d+\.(\d)\d+\.[\d\.\-]+ \([\w\s]+\)&quot;$</ind:pattern>`

**Comment by jhrozek** [comment]
FWIW what Evgeny proposed works for me
