### ISSUE TITLE
SRG map strong entropy rules

### ISSUE THREAD

**Issue by yuumasato** [ComplianceAsCode/content#5169]
#### Description of problem:
The following rules lack SRG mapping:
- [sshd_use_strong_rng](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/services/ssh/ssh_server/sshd_use_strong_rng/rule.yml)
- [openssl_use_strong_entropy](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/software/integrity/crypto/openssl_use_strong_entropy/rule.yml)

#### SCAP Security Guide Version:
0.1.48

**Comment by yuumasato** [comment]
Hello @tedbrunell, can you help with this?
I could not find something that is directly related...

**Comment by redhatrises** [comment]
SRG-OS-000480-GPOS-00227 is the SRG that you would want to map to then.

**Comment by tedbrunell** [comment]
I agree with @redhatrises

**Comment by yuumasato** [comment]
Thank you!
