### ISSUE TITLE
SSH server private key permissions set "too open" on RHEL 6

### ISSUE THREAD

**Issue by KodinLanewave** [ComplianceAsCode/content#5173]
#### Description of problem:
C2S rule is incorrectly defined to set private keys to permissions 0640.  This causes SSHD to ignore the keys as their permissions are too open.  In addition, having group read permission is absolutely not necessary from a security standpoint.  Permissions should be 0600.  If you run remediation rules against systems you will effectively disable the ability to use SSH.

#### SCAP Security Guide Version:
0.1.47

#### Operating System Version:
RHEL 6

#### Steps to Reproduce:

1. Load up latest release of C2S RHEL 6 security guide
2. Find control that checks private key permissions
3. Content rule is incorrect and will break systems if applied
4.

#### Actual Results:
Security guide states private SSH keys should be set to 0640

#### Expected Results:
Security guide _should_ state that private SSH keys should be set to 0600.  0640 causes SSHD to ignore all private keys set this way.

**Comment by ggbecker** [comment]
Ths has been fixed by amending the rule to support both root:root (0600) and root:ssh_keys (0640) permissions mode. This should not happen anymore.

https://github.com/ComplianceAsCode/content/pull/9094
