### ISSUE TITLE
missing build directory

### ISSUE THREAD

**Issue by bert2002** [ComplianceAsCode/content#5176]
#### Description of problem:
Seems that scap-security-guide-0.1.48.tar.bz2 is missing the `build` directory. It is in git and at the tag, but not in the archive.

**Comment by matejak** [comment]
@yuumasato What do you think about this? Should we update the release guide with an explicit instruction to pay attention to that directory, or was it a one-off unlikely event?

**Comment by yuumasato** [comment]
This is not a one-off event, the `CPack` command doesn't add the `build` directory to the tarball.
Not sure if the `CMakeLists.txt` is faulty, or a `CPack` limitation.

The tarball created by GitHub itself contains the `build` directory.
I just compared the 0.1.47 tarballs and differences are that the GitHub tarball contains the empty directories (`build` directory and the ones `.gitkeep` file).

```console
$ diff -bur content-0.1.48 scap-security-guide-0.1.48
Only in content-0.1.48: build
Only in content-0.1.48/debian10: overlays
Only in content-0.1.48/debian8: overlays
Only in content-0.1.48/debian9: overlays
Only in content-0.1.48/fedora: overlays
Only in content-0.1.48/fuse6: overlays
Only in content-0.1.48/fuse6: remedations
Only in content-0.1.48: .github
Only in content-0.1.48: .gitignore
Only in content-0.1.48/ocp3: checks
Only in content-0.1.48/ol7: kickstart
Only in content-0.1.48/ol7: overlays
Only in content-0.1.48/opensuse: overlays
Only in content-0.1.48/rhv4: checks
Only in content-0.1.48/tests: .gitignore
Only in content-0.1.48/ubuntu1404: overlays
Only in content-0.1.48/ubuntu1604: overlays
Only in content-0.1.48/ubuntu1804: overlays
Only in content-0.1.48/wrlinux1019: overlays
Only in content-0.1.48/wrlinux8: overlays
```

We could switch to using GH generated tarballs, but once I was told not to trust them.
Technically they look ok, but one may have trust issues with it. OTOH, with the "semi automation" of release, they are now generated in one of our Jenkins nodes.
I'd like to hear your opinions on it.
