### ISSUE TITLE
Usage section omits the #1 use case - during system install

### ISSUE THREAD

**Issue by gitcnd** [ComplianceAsCode/content#5207]
#### Description of problem:

Selecting a security policy is part of OS install, and anaconda provides a location into which a URL can be placed to fetch the policy.

However - there is no documentation anywhere that I or others can find on what URL goes in there, and your guide (which should tell us) doesn't even mention this use case.

#### SCAP Security Guide Version:

All

#### Operating System Version:

CentOS 8, RedHat 8

#### Steps to Reproduce:

1. Run installer
2. Click "Security Policy" menu option

#### Actual Results:

No clues or hints on what to put as a URL

#### Expected Results:

This guide tells us what URL to use in the "Usage" section

**Comment by redhatrises** [comment]
Please open this ticket against either Red Hat documentation using your subscription or against the OpenSCAP Anaconda Plugin project. The URL can be any URL that contains a valid SCAP datamstream xml file.
