### ISSUE TITLE
Generate content with (pseudo) OVAL 5.11.3 content

### ISSUE THREAD

**Issue by yuumasato** [ComplianceAsCode/content#5208]
#### Description of problem:
Once OpenSCAP has the `yamlfilecontent_probe` implemented, it will need content to consume.

The `yamlfilecontent_test` is not part of OVAL standard yet, see https://github.com/OVAL-Community/OVAL/pull/90 for status.

For the purposes of writing content and testing ti we can pretend the test is part of the next OVAL version, which is 5.11.3. The probe implementation follows similar approach, https://github.com/OpenSCAP/openscap/pull/1480.

#### SCAP Security Guide Version:
0.1.48

#### Actual Results:
- Any content with test for `yamlfilecontent` will fail SCAP validation.

#### Expected Results:
- OVAL content with `yamlfilecontent_test` is added with OVAL 5.11.3 version.
- I'd expect a switch allow toggling inclusion of new, non-standard content. So that when I still can build 100% compliant content.

**Comment by ggbecker** [comment]
@yuumasato @matejak Isn't this fixed by: https://github.com/ComplianceAsCode/content/pull/5326 ?

**Comment by Mab879** [comment]
No longer needed and solved for OCP.
