### ISSUE TITLE
CIS 1.2.5 Ensure package manager repositories are configured (Not Scored)

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#5219]

**Comment by shawndwells** [comment]
[CIS_Red_Hat_Enterprise_Linux_8_Benchmark_v1.0.0 (1).pdf](https://github.com/ComplianceAsCode/content/files/4300856/CIS_Red_Hat_Enterprise_Linux_8_Benchmark_v1.0.0.1.pdf)

**Comment by Mab879** [comment]
Closing as this is marked as a manual check.
