### ISSUE TITLE
CIS 1.4.2 Ensure permissions on bootloader config are configured (Automated)

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#5222]
[CIS_Red_Hat_Enterprise_Linux_8_Benchmark_v1.0.0 (1).pdf](https://github.com/ComplianceAsCode/content/files/4300949/CIS_Red_Hat_Enterprise_Linux_8_Benchmark_v1.0.0.1.pdf)

    ### 1.5.1 Ensure permissions on bootloader config are configured (Scored)
    #### chown root:root /boot/grub2/grub.cfg
    - file_owner_grub2_cfg
    - file_groupowner_grub2_cfg

    #### chmod og-rwx /boot/grub2/grub.cfg
    - file_permissions_grub2_cfg

    #### chown root:root /boot/grub2/grubenv
    #### chmod og-rwx /boot/grub2/grubenv

Need new rules for evaluating grubenv, akin to the grub.cfg checks

**Comment by alexhaydock** [comment]
This requirement itself is actually bugged upstream as it doesn't account for EFI installs which keep their `grub.cfg` in a different place.

It doesn't satisfy CIS CAT Assessor, but for now I can remediate this one on my EFI systems with:

```
chown root:root /boot/efi/EFI/redhat/grub.cfg
chmod og-rwx /boot/efi/EFI/redhat/grub.cfg
chown root:root /boot/grub2/grubenv
chmod og-rwx /boot/efi/EFI/redhat/grubenv
chown root:root /boot/efi/EFI/redhat/grubenv
chmod og-rwx /boot/grub2/grubenv
```

**Comment by ggbecker** [comment]
> This requirement itself is actually bugged upstream as it doesn't account for EFI installs which keep their `grub.cfg` in a different place.
> 
> It doesn't satisfy CIS CAT Assessor, but for now I can remediate this one on my EFI systems with:
> 
> ```
> chown root:root /boot/efi/EFI/redhat/grub.cfg
> chmod og-rwx /boot/efi/EFI/redhat/grub.cfg
> chown root:root /boot/efi/EFI/redhat/grubenv
> chmod og-rwx /boot/efi/EFI/redhat/grubenv
> chown root:root /boot/grub2/grubenv
> chmod og-rwx /boot/grub2/grubenv
> ```

Maybe rules from the UEFI folder should be included in the CIS profile as well.

**Comment by alexhaydock** [comment]
> Maybe rules from the UEFI folder should be included in the CIS profile as well.

This might be a good idea.

Interestingly, the upstream bug for this one in CIS has been open for 4 years without any action: https://workbench.cisecurity.org/community/14/tickets/4720
