### ISSUE TITLE
CIS vs Red Hat: Where to check if SELinux is disabled?

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#5224]
CIS 1.7.1.2 Ensure SELinux is not disabled in bootloader configuration (Scored) evaluates grubenv instead of default/grub. Should both be evaluated?

[CIS_Red_Hat_Enterprise_Linux_8_Benchmark_v1.0.0 (1).pdf](https://github.com/ComplianceAsCode/content/files/4301057/CIS_Red_Hat_Enterprise_Linux_8_Benchmark_v1.0.0.1.pdf)

**Comment by yuumasato** [comment]
In RHEL8 the recommended way to update kernel boot parameters is via grubby:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/system_design_guide/configuring-kernel-command-line-parameters_system-design-guide#changing-kernel-command-line-parameters-for-a-single-boot-entry_configuring-kernel-command-line-parameters

CC @Mab879 @marcusburghardt @vojtapolasek to suggest CIS changes

**Comment by marcusburghardt** [comment]
The Benchmark for RHEL8 v2.0.0 is already updated to use the recommended way. We still need to update the rule, but this will be treated in another initiative. I am closing this issue now.
