### ISSUE TITLE
CIS 1.10 Ensure system-wide crypto policy is not legacy (Scored)

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#5228]
CIS looks for policy != legacy, where existing rules evaluate for a defined policy. Temporarily mapped this rule to configure_crypto_policy but need to evaluate if a new rule should be created instead.

[CIS_Red_Hat_Enterprise_Linux_8_Benchmark_v1.0.0 (1).pdf](https://github.com/ComplianceAsCode/content/files/4301163/CIS_Red_Hat_Enterprise_Linux_8_Benchmark_v1.0.0.1.pdf)

**Comment by yuumasato** [comment]
I'm not sure if need a specific rule to check that the selected crypto-policy is not LEGACY. This specific rule will interfere with level2 policies, and will need to be actively unselected.

And for consistency, for Level2 we will have to add a rule that only expects policies FIPS or FUTURE, adding yet another rule and complexity.

Currently, we just change the selected crypto-policy:
For 1.10 (level 1) we evaluate the configured crypto-policy and set it to default.
For 1.11 (level 2) we just change the selected crypto-policy to future.

This approach is very simple and easy to maintain.

I think we can add notes to the CIS control files and just close this issue.
Thoughts?
