### ISSUE TITLE
CIS 3.4.1.1 Ensure a Firewall package is installed (Scored)

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#5237]
Need new rule for nftables

**Comment by yuumasato** [comment]
Is `nftables` prefered over `firewalld`?
There exists a rule for firewalld already:
https://github.com/ComplianceAsCode/content/blob/master/rhel8/profiles/cis.profile#L429

**Comment by marcusburghardt** [comment]
This requirement is outdated. In addition, there is already rules for `firewalld` and `nftables` packages.
