### ISSUE TITLE
CIS 3.4.2.6 Ensure unnecessary services and ports are not accepted (Not Scored)

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#5241]
Needs rule.

**Comment by alexhaydock** [comment]
In the current RHEL 8 CIS Benchmark (1.0.1), this rule is marked as "Manual" rather than automated. We can probably close this.

**Comment by yuumasato** [comment]
Agreed, basically the old term "Not Scored" means "Manual" now.
