### ISSUE TITLE
CIS 3.4.3.4 Ensure loopback traffic is configured (Scored)

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#5246]
Needs rule.

**Comment by alexhaydock** [comment]
In the current RHEL 8 CIS Benchmark (1.0.1), this rule is marked as "Manual" rather than automated. We can probably close this.

**Comment by yuumasato** [comment]
Item 3.4.3.4 is not manual, I see there: `3.4.3.4 Ensure nftables loopback traffic is configured (Automated)`
