### ISSUE TITLE
CIS 3.4.3.7 Ensure nftables service is enabled (Scored)

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#5249]
Needs new rule.

**Comment by marcusburghardt** [comment]
This requirement will likely be dropped in the future because the nftables is actually the backend for `firewalld`. The preferred service to manage firewall rules in RHEL is firewalld.

**Comment by tuxwielder** [comment]
> This requirement will likely be dropped in the future because the nftables is actually the backend for `firewalld`. The preferred service to manage firewall rules in RHEL is firewalld.

Not for servers it isn't. Firewalld's complexity is actually a security risk IMHO.
