### ISSUE TITLE
CIS 3.4.4.1 Configure IPv4 iptables

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#5251]
Need to investigate it system/network/network-iptables/iptables_ruleset_modifications/set_iptables_default_rule_forward/rule.yml will suffice

**Comment by alexhaydock** [comment]
This is another example of a CIS page that looks like a rule but is more of a context-providing chapter title page. Can probably close this since I don't think we want to remediate this as a rule.
