### ISSUE TITLE
CIS 3.4.4.1.3 Ensure outbound and established connections are configured (Not Scored)

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#5254]
Needs new rule

**Comment by alexhaydock** [comment]
In the current RHEL 8 CIS Benchmark (1.0.1), this rule is marked as "Manual" rather than automated. We can probably close this.

**Comment by yuumasato** [comment]
Agreed, basically the old term "Not Scored" means "Manual" now.
