### ISSUE TITLE
CIS 3.4.4.2.4 Ensure IPv6 firewall rules exist for all open ports (Not Scored)

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#5260]
Needs new rule.

**Comment by alexhaydock** [comment]
In the current RHEL 8 CIS Benchmark (1.0.1), this rule is marked as "Manual" rather than automated. We can probably close this.

**Comment by yuumasato** [comment]
This item is actually marked as "Automated". `3.4.4.2.3` is "Manual" though.

**Comment by yuumasato** [comment]
I see you filed #7191, which is about the same item number.
We can keep that one as it the title is more accurate.

**Comment by alexhaydock** [comment]
I see what I did here - I actually meant to comment on #5259 recommending that one for closure, but this ticket was the one linked next to 3.4.4.2.4 in the current `cis.profile` and I did it quickly without checking. :facepalm: 

https://github.com/ComplianceAsCode/content/blob/958709e473b1c4a479c7cb35982aac09f763291b/products/rhel8/profiles/cis.profile#L528-L530
