### ISSUE TITLE
SSG Test Suite can't run with python2

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#5293]
#### Description of problem:
Recent changes from #5217 prevent running SSG Test Suite with `python2` because of syntax error.
Basically raising an exception from another one is not supported by `python2`:
https://github.com/ComplianceAsCode/content/blob/259369ababc6234bba516430cd31510dbdd3ae02/tests/ssg_test_suite/virt.py#L197

We can either fix that or switch shebangs of python files to something like: `#!/usr/bin/env python3`.
I prefer going with the fix since it's a small change and it's the only thing preventing from running with `python2`.

Results:
./test_suite.py rule --remediate-using bash --libvirt qemu:///session test-suite-rhel8 --datastream ../build/ssg-rhel8-ds.xml audit_rules_sysadmin_actions
```
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/ggasparb/workspace/github/content/tests/logs/rule-custom-2020-03-16-1610/test_suite.log
Traceback (most recent call last):
  File "./test_suite.py", line 333, in <module>
    main()
  File "./test_suite.py", line 329, in main
    options.func(options)
  File "/home/ggasparb/workspace/github/content/tests/ssg_test_suite/rule.py", line 354, in perform_rule_check
    checker.test_target(options.target)
  File "/home/ggasparb/workspace/github/content/tests/ssg_test_suite/oscap.py", line 619, in test_target
    self.start()
  File "/home/ggasparb/workspace/github/content/tests/ssg_test_suite/oscap.py", line 653, in start
    raise RuntimeError(msg)
RuntimeError: Failed to start test environment 'libvirt-based': invalid syntax (virt.py, line 197)
```

**Comment by matusmarhefka** [comment]
It is not only that, for example `TimeoutError` does not exist in python2. Working on fixing this.
