### ISSUE TITLE
xccdf_org.ssgproject.content_rule_sshd_enable_strictmodes false positives

### ISSUE THREAD

**Issue by Klaas-** [ComplianceAsCode/content#5322]
#### Description of problem:
The rule for checking strict mode is presenting a false positive finding.
The option defaults to Yes and is not specified in my sshd_config. Therefore it is "Yes" 
```
$ rpm -qa|grep ssh-server|sort
openssh-server-8.0p1-4.el8_1.x86_64

$ grep -i Strict /etc/ssh/sshd_config
#StrictModes yes
#GSSAPIStrictAcceptorCheck yes

$ man sshd_config
     StrictModes
             Specifies whether sshd(8) should check file modes and ownership of the user's files and home directory before accepting login.  This is normally desirable because novices sometimes
             accidentally leave their directory or files world-writable.  The default is yes.  Note that this does not apply to ChrootDirectory, whose permissions and ownership are checked
             unconditionally.
```

#### SCAP Security Guide Version:
master (20.03.2020)

#### Operating System Version:
Red Hat Enterprise Linux release 8.1 (Ootpa)

#### Steps to Reproduce:

1. don't have StrictModes in sshd_config
2. Run check and receive a fail
3.
4.

#### Actual Results:
fail

#### Expected Results:
pass

It seems this once was fixed in https://github.com/ComplianceAsCode/content/issues/2457 but that fix somehow got lost

**Comment by Klaas-** [comment]
Same for 
xccdf_org.ssgproject.content_rule_sshd_disable_kerb_auth

"KerberosAuthentication no" is expected but it's a default value

```
$ grep -i KerberosAuthentication /etc/ssh/sshd_config
#KerberosAuthentication no
```

**Comment by yuumasato** [comment]
Related PRs:
- enable_strictmodes https://github.com/ComplianceAsCode/content/pull/5310
- KerberosAuthentication https://github.com/ComplianceAsCode/content/pull/5303

**Comment by Klaas-** [comment]
I see the ongoing discussion in #5315 
My personal view: if it is a default it should not be needed to explicitly set it in config.

**Comment by Klaas-** [comment]
I thought some more about this and I think a general approach I would like to see is this:
- Check runtime configuration, just because a setting is in the configuration file does not necessarily mean it is actually used in the running processes, sshd is a bad example though, I do not know of a way to dump the sshd config of a running server
- Check which configuration file is used by running service (in theory one could use a different config file for sshd and currently that is not being checked, right?)
- Check configuration file, but only for the non-default ones; or check against something like sshd -T instead of the file

**Comment by ggbecker** [comment]
We have moved to accepting default values in sshd configuration, so this is not an issue anymore, for example:

https://github.com/ComplianceAsCode/content/blob/7f9d858c8df3c2ec5aeaa5059d4a702472f19e44/linux_os/guide/services/ssh/ssh_server/sshd_enable_strictmodes/rule.yml#L63
