### ISSUE TITLE
Contributor recognition

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#5355]
Update to include contributors in README

**Comment by shawndwells** [comment]
@all-contributors add @redhatrises for code

**Comment by shawndwells** [comment]
@all-contributors please add @isimluk @matejak for code

testing adding multiple people at once

**Comment by shawndwells** [comment]
@all-contributors please add @yuumasato

**Comment by shawndwells** [comment]
@all-contributors please add @redhatrises

**Comment by shawndwells** [comment]
@all-contributors please add @iankko

**Comment by shawndwells** [comment]
@all-contributors please add @jan-cerny

**Comment by shawndwells** [comment]
@all-contributors please add @jeffblank

**Comment by shawndwells** [comment]
@all-contributors please add @cipherboy

**Comment by shawndwells** [comment]
@all-contributors please add @jan-cerny for code

**Comment by shawndwells** [comment]
@all-contributors please add @yuumasato for code

**Comment by shawndwells** [comment]
@all-contributors please add @iankko for code

**Comment by shawndwells** [comment]
@all-contributors please add @jeffblank for code

**Comment by shawndwells** [comment]
@all-contributors please add @cipherboy for code

**Comment by shawndwells** [comment]
@all-contributors please add @matejak for code

**Comment by shawndwells** [comment]
@all-contributors please add @ggbecker for code

**Comment by shawndwells** [comment]
@all-contributors please add @iokomin for code

**Comment by shawndwells** [comment]
@all-contributors please add @vojtapolasek for code

**Comment by shawndwells** [comment]
@all-contributors please add @isimluk for code

**Comment by shawndwells** [comment]
@all-contributors please add @dahaic for code

**Comment by shawndwells** [comment]
@all-contributors please add @diastelo for code

**Comment by shawndwells** [comment]
@all-contributors please add @PThierry for code

**Comment by shawndwells** [comment]
@all-contributors please add @mildas for code

**Comment by shawndwells** [comment]
@all-contributors please add @adelton for code

**Comment by shawndwells** [comment]
@all-contributors please add @matusmarhefka for code

**Comment by shawndwells** [comment]
@all-contributors please add @redhat-rmcallis for code

**Comment by shawndwells** [comment]
@all-contributors please add @jhrozek for code

**Comment by shawndwells** [comment]
@all-contributors please add @xiruiyang for code

**Comment by shawndwells** [comment]
@all-contributors please add @lsteinke for code

**Comment by shawndwells** [comment]
@all-contributors please add @abergmann for code

**Comment by shawndwells** [comment]
@all-contributors please add @70k10 for code

**Comment by shawndwells** [comment]
@all-contributors please add @yuumasato for code

**Comment by shawndwells** [comment]
@all-contributors please add @yuumasato for code

**Comment by shawndwells** [comment]
@all-contributors please add @yuumasato for code

**Comment by shawndwells** [comment]
@all-contributors please add @iankko for code and bug and content

**Comment by shawndwells** [comment]
@all-contributors please add @iankko for blog, content, example, eventOrganizing, ideas, maintenance, platform, review, tool, talk

**Comment by shawndwells** [comment]
@all-contributors please add @jan-cerny for bug, blog, code, content, doc, example, ideas, maintenance, platform, question, review, tool, test, talk

**Comment by shawndwells** [comment]
@all-contributors please add @jeffblank for bug, business, code, content, doc, example, eventOrganizing, financial, fundingFinding, talk, tutorial, video

@all-contributors please add @cipherboy for code, blog

**Comment by shawndwells** [comment]
@all-contributors please add @jeffblank for bug, business, code, content, doc, example, eventOrganizing, financial, fundingFinding, talk, tutorial, video

**Comment by shawndwells** [comment]
@all-contributors please add @cipherboy for code, blog

**Comment by shawndwells** [comment]
@all-contributors please add @matejak for bug, blog, code, content, doc, example, eventOrganizing, ideas, maintenance, platform, review, tool, test, tutorial, talk

**Comment by shawndwells** [comment]
@all-contributors please add @ggbecker for bug, code, content, doc, maintenance, question, review, tool, test

**Comment by shawndwells** [comment]
@all-contributors please add @vojtapolasek for code, test, bug, review, question

**Comment by shawndwells** [comment]
@all-contributors please add @isimluk for bug, blog, code, content, doc, example, ideas, infra, maintenance, platform, plugin, question, review, tool, test, tutorial, talk, userTesting, video

**Comment by shawndwells** [comment]
@all-contributors please add @dahaic for bug, code, projectManagement, test, talk

**Comment by shawndwells** [comment]
@all-contributors please add @matusmarhefka for code, test, bugfix, review, question

**Comment by shawndwells** [comment]
@all-contributors please add @diastelo for code

**Comment by shawndwells** [comment]
@all-contributors please add @PThierry for code

**Comment by shawndwells** [comment]
@all-contributors please add @mildas for code, test

**Comment by shawndwells** [comment]
@all-contributors please add @redhat-rmcallis for code

**Comment by shawndwells** [comment]
@all-contributors please add @jhrozek for code

**Comment by shawndwells** [comment]
@all-contributors please add @xiruiyang for code

**Comment by shawndwells** [comment]
@all-contributors please add @70k10 for code

**Comment by shawndwells** [comment]
@all-contributors please add @konstruktoid for code

**Comment by shawndwells** [comment]
@all-contributors please add @maltek for code

**Comment by shawndwells** [comment]
@all-contributors please add @keithkjackson for code

**Comment by shawndwells** [comment]
@all-contributors please add @MollyJoBault for code

**Comment by shawndwells** [comment]
@all-contributors please add @eradot4027 for code

**Comment by shawndwells** [comment]
@all-contributors please add @electrosenpai for code

**Comment by shawndwells** [comment]
@all-contributors please add @JAORMX for code, test, ideas, review, test, talk

**Comment by shawndwells** [comment]
@all-contributors please add @Eric-Sparks for code

**Comment by shawndwells** [comment]
@all-contributors please add @redhatrises  for bug, blog, business, code, content, doc, design, example, eventOrganizing, fundingFinding, ideas, infra, maintenance, platform, projectManagement, question, review, tool, test, tutorial, talk, userTesting, video

**Comment by shawndwells** [comment]
@all-contributors please add @thenefield for code, test

**Comment by shawndwells** [comment]
@all-contributors please add @jcpunk

**Comment by shawndwells** [comment]
@all-contributors please add @jcpunk for code

**Comment by shawndwells** [comment]
@all-contributors please add @lkerner for blog, business, eventOrganizing, fundingFinding, ideas, tutorial, talk, video

**Comment by shawndwells** [comment]
@all-contributors please add @jamescassell for code

**Comment by shawndwells** [comment]
@all-contributors please add @DominiqueDevinci for code

**Comment by shawndwells** [comment]
@all-contributors please add @justin-stephenson for code

**Comment by shawndwells** [comment]
@all-contributors please add @pvrabec bug, blog, business, code, fundingFinding, ideas, projectManagement, question, review, tool, test, tutorial, talk, video

**Comment by shawndwells** [comment]
@all-contributors please add @pschneiders for code

**Comment by shawndwells** [comment]
@all-contributors please add @opoplawski for code

**Comment by shawndwells** [comment]
@all-contributors please add @mrogers950 for code

**Comment by shawndwells** [comment]
@all-contributors please add @mralph-rh for code

**Comment by shawndwells** [comment]
@all-contributors please add @maxrp for code

**Comment by shawndwells** [comment]
@all-contributors please add @jglemza for code

**Comment by shawndwells** [comment]
@all-contributors please add @finkr for code

**Comment by shawndwells** [comment]
@all-contributors please add @dthurston for code, business

**Comment by shawndwells** [comment]
@all-contributors please add @dhanushkar-wso2 for code

**Comment by shawndwells** [comment]
@all-contributors please add @VadimDor for code

**Comment by shawndwells** [comment]
@all-contributors please add @PThierry for code

**Comment by shawndwells** [comment]
@all-contributors please add @OnceUponALoop for code

**Comment by shawndwells** [comment]
@all-contributors please add @yasirimam1980 for code, business, talk

**Comment by shawndwells** [comment]
@all-contributors please add @rchayes for code

**Comment by shawndwells** [comment]
@all-contributors please add @mshoger for code, business

**Comment by shawndwells** [comment]
@all-contributors please add @jstookey for code

**Comment by shawndwells** [comment]
@all-contributors please add @ghylock for code

**Comment by shawndwells** [comment]
@all-contributors please add @angystardust for code

**Comment by shawndwells** [comment]
@all-contributors please add @Klaas- for code

**Comment by shawndwells** [comment]
@all-contributors please add @noslzzp for code, business, ideas

**Comment by shawndwells** [comment]
@all-contributors please add @termlen0 for code

**Comment by shawndwells** [comment]
@all-contributors please add @ajacocks for code, business, talk, video, tutorial

**Comment by shawndwells** [comment]
@all-contributors please add @gregelin for code, talks, video

**Comment by shawndwells** [comment]
@all-contributors please add @fcaviggia for code

**Comment by shawndwells** [comment]
@all-contributors please add @jaredhocutt for business, blog, ideas, talk, video

**Comment by shawndwells** [comment]
@all-contributors please add @dischord01 for business, ideas, talk, video

**Comment by shawndwells** [comment]
@all-contributors please add @dischord01 for tutorial

**Comment by shawndwells** [comment]
@all-contributors please add @matmille for business, ideas, talk, tutorial

**Comment by shawndwells** [comment]
@all-contributors please add @dudash for ideas, talk, tutorial

**Comment by shawndwells** [comment]
@all-contributors please add @donnydavis for ideas, talk, tutorial

**Comment by shawndwells** [comment]
@all-contributors please add @bhirsch70 for ideas, talk, tutorial, video

**Comment by shawndwells** [comment]
@all-contributors please add @rlucente-se-jboss for code, ideas, talk, tutorial

**Comment by shawndwells** [comment]
@all-contributors please add @lkinser for code, ideas, talk, tutorial

**Comment by shawndwells** [comment]
@all-contributors please add @cam1244 for code

**Comment by shawndwells** [comment]
@all-contributors please add mmsrubar for code

**Comment by shawndwells** [comment]
@all-contributors please add @xiruiyang for code

**Comment by shawndwells** [comment]
@all-contributors please add lamawithonel for code

**Comment by yuumasato** [comment]
@shawndwells Is there a way to automate this? Adding people manually is not sustainable and error prone.

**Comment by yuumasato** [comment]
Could this be automated in [utils/generate_contributors.py](https://github.com/ComplianceAsCode/content/blob/master/utils/generate_contributors.py)?

**Comment by ggbecker** [comment]
@yuumasato this can probably be closed as we generate contributors automatically right?

**Comment by matejak** [comment]
Yes.

**Comment by yuumasato** [comment]
I probably missed Becker's notification.
Yeah, the list of contributor is generated automatically, but this ticket was about automating Contributors in the README.
But this is not relevant anymore as they were removed in https://github.com/ComplianceAsCode/content/pull/8749
