### ISSUE TITLE
6.2.12 Ensure users' .netrc Files are not group or world accessible (Scored)

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#5504]
Needs rule.

Or more ideally, someone could work with CIS to modernize their guidance.

Current content does not allow netrc files at all: system/accounts/accounts-restrictions/password_storage/no_netrc_files/rule.yml

**Comment by marcusburghardt** [comment]
The requirement 6.2.13 should be removed in favor of the 6.2.15.
Ticket opened in CIS community: https://workbench.cisecurity.org/benchmarks/9520/tickets/16318

**Comment by marcusburghardt** [comment]
The requirement is already removed in CIS RHEL9. It should also be removed from RHEL8.
