### ISSUE TITLE
4.1.14 Ensure file deletion events by users are collected (Scored)

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#5514]

**Comment by yuumasato** [comment]
Probably covered already, for RHEL CIS, these are the selections:
    - audit_rules_file_deletion_events_unlink
    - audit_rules_file_deletion_events_unlinkat
    - audit_rules_file_deletion_events_rename
    - audit_rules_file_deletion_events_renameat
    # Opinionated selection
    - audit_rules_file_deletion_events_rmdir
