### ISSUE TITLE
rsyslog_files_permissions does not support /etc/rsyslog.d/

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#5518]
Currently rsyslog_files_permissions only checks /etc/rsyslog.conf. Needs to be extended for /etc/rsyslog.d/

Needed for 4.2.1.3 Ensure rsyslog default file permissions configured (Scored)

**Comment by marcusburghardt** [comment]
`/etc/rsyslog.d/` is already supported by this rule.
