### ISSUE TITLE
Pam module pam_faillock.so with value unlock_time=never causes OpenSCAP conversion error

### ISSUE THREAD

**Issue by yuumasato** [ComplianceAsCode/content#5544]
#### Description of problem:

When `pam_faillock.so` parameter is configured with `unlock_time=never`, OpenSCAP throws an error:
```
OpenSCAP Error: Conversion of the string "" to an integer (64 bits) failed: Invalid argument [oval_cmp.c:111]
Conversion of the string "" to an integer (64 bits) failed: Invalid argument [oval_cmp.c:111]
```

For `pam_faillock.so` settings `unlock_time=never` and `unlock_time=0` are equivalent, but for the OVAL content they are not. 
The check expects numbers, and the word `never`doesn't match, resulting in the error.

NOTE: The Content doesn't add `unlock_time=never`, but it can't cope with any added by other means.

##### Workaround
Change any occurrence of `unlock_time=never` to `unlock_time=0`.

#### SCAP Security Guide Version:
0.1.49

#### Steps to Reproduce:

1. `oscap xccdf eval --remediate --profile ncp --rule xccdf_org.ssgproject.content_rule_accounts_passwords_pam_faillock_unlock_time ./ssg-rhel7-ds.xml`
2. `sed -i 's/unlock_time=0/unlock_time=never/g' /etc/pam.d/system-auth`
3. `oscap xccdf eval --profile ncp --rule xccdf_org.ssgproject.content_rule_accounts_passwords_pam_faillock_unlock_time ./ssg-rhel7-ds.xml`
```
Title   Set Lockout Time for Failed Password Attempts
Rule    xccdf_org.ssgproject.content_rule_accounts_passwords_pam_faillock_unlock_time
Ident   CCE-26884-7
E: oscap:     Error occured when comparing a variable 'oval:ssg-var_accounts_passwords_pam_faillock_unlock_time:var:1' value '0' with collected item entity = ''
E: oscap:     Error occured when comparing a variable 'oval:ssg-var_accounts_passwords_pam_faillock_unlock_time:var:1' value '0' with collected item entity = ''
Result  error

OpenSCAP Error: Conversion of the string "" to an integer (64 bits) failed: Invalid argument [oval_cmp.c:111]
Conversion of the string "" to an integer (64 bits) failed: Invalid argument [oval_cmp.c:111]
```

#### Actual Results:
`Result error`

#### Expected Results:
`Result pass`

#### Addition Information/Debugging Steps:

- The OVAL check expects digits after `unlock_time`: https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_unlock_time/oval/shared.xml#L43
- The variable for unlock_time is a number: https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/var_accounts_passwords_pam_faillock_unlock_time.var#L7
  Although there is a selector `never`, it is assigned a value of `0`.

**Comment by redhatrises** [comment]
It is also configured as of 8.2 in the wrong place. It needs to be configured in `/etc/security/faillock.conf`

**Comment by yuumasato** [comment]
A bit of digging showed that in 0.1.38 the variable was a string: https://github.com/ComplianceAsCode/content/blob/v0.1.38/shared/xccdf/system/accounts/pam.xml#L254
And the OVAL check followed the same line and accepted chars: https://github.com/ComplianceAsCode/content/blob/v0.1.38/shared/checks/oval/accounts_passwords_pam_faillock_unlock_time.xml#L41
