### ISSUE TITLE
RHEL7 - service_rhnsd_disabled fails after kickstart installation

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#5714]
#### Description of problem:
Rule `service_rhnsd_disabled` fails after rhel7 kickstart installation with "Server with GUI" software selection and cis profile.

#### SCAP Security Guide Version:
9e403dd

#### Operating System Version:
RHEL 7.8

#### Steps to Reproduce:
1. Install RHEL 7.8 with `Server with GUI` software selection and `e8`, or `cis` security policy.
2. After installation scan the machine with the profile selected during the installation.

#### Actual Results:
`service_rhnsd_disabled` fails.

#### Expected Results:
`service_rhnsd_disabled` passes.

#### Addition Information/Debugging Steps:
The rule passes at remediation scan during installation but it fails after restart because the service is active.

**Comment by matusmarhefka** [comment]
Closing this, it was reported also in https://bugzilla.redhat.com/show_bug.cgi?id=1828871 and closed as wontfix for RHEL7.

There is also RHEL8 bug which should be resolved in future: https://bugzilla.redhat.com/show_bug.cgi?id=1834716
