### ISSUE TITLE
make: *** No targets specified and no makefile found.  Stop.

### ISSUE THREAD

**Issue by scott-mackenzie** [ComplianceAsCode/content#5727]
#### Description of problem:

**Following the build from source guide:**
https://bit.ly/3fh88bp
No make target is built using the defined approach.

Expected result is the ability to follow the build from source approach using single product and that the process works as described.  Result is error: 

make: *** No targets specified and no makefile found.  Stop.

#### SCAP Security Guide Version:

**Source version:**
https://github.com/ComplianceAsCode/content/releases/download/v0.1.49/scap-security-guide-0.1.49.tar.bz2

#### Operating System Version:

VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"

#### Steps to Reproduce:

1. Download source from above link to /usr/local/src
2. Uncompress source tar zjvf scap-security-guide-0.1.49.tar.bz2
3. cd scap-security-guide-0.1.49
4. Following the procedure: (1) https://github.com/ComplianceAsCode/content/blob/master/docs/manual/developer_guide.adoc#building within section **3.3 Building**

4a. ensure build director is present, if not create build directory --> then:
4b. ./build_product ubuntu1804
4.c cd build
4d. Following the procedure within **3.5. Testing** run command cmake ../
4e. run command make -j4

**Note:** running command ctest -j4 produces "all tests passed"

At this stage the below error is produced:
make: *** No targets specified and no makefile found.  Stop.

#### Actual Results:
make: *** No targets specified and no makefile found.  Stop.

#### Expected Results:
Successful build.  When building "all" sources this works.  When using the product specific procedure the process fails.

#### Addition Information/Debugging Steps:
N/A

**Comment by scott-mackenzie** [comment]
**Output from command: cmake ../**


-- SCAP Security Guide 0.1.49
-- (see /home/username/Projects/scap-security-guide-0.1.49/docs/manual/developer_guide.adoc for build instructions)
--
-- Found PY_json2html: /usr/local/lib/python3.8/dist-packages/json2html
-- CMake:
-- build type: Release
-- generator: Ninja
-- source directory: /home/username/Projects/scap-security-guide-0.1.49
-- build directory: /home/username/Projects/scap-security-guide-0.1.49/build
--
-- Tools:
-- python: /usr/bin/python3 (version: 3.8.2)
-- python yaml module: /usr/lib/python3/dist-packages/yaml
-- python jinja2 module: /usr/lib/python3/dist-packages/jinja2
-- oscap: /usr/local/bin/oscap (version: 1.3.3)
-- xsltproc: /usr/bin/xsltproc
-- xmllint: /usr/bin/xmllint
-- xmlwf: /usr/bin/xmlwf
-- sed: /usr/bin/sed
-- shellcheck (optional): SHELLCHECK_EXECUTABLE-NOTFOUND
-- linkchecker (optional): LINKCHECKER_EXECUTABLE-NOTFOUND
-- grep (optional): /usr/bin/grep
-- python pytest module (optional): /usr/lib/python3/dist-packages/pytest.py
-- ansible-playbook module (optional): /usr/bin/ansible-playbook
-- ansible-lint module (optional): ANSIBLE_LINT_EXECUTABLE-NOTFOUND
-- yamllint module (optional): YAMLLINT_EXECUTABLE-NOTFOUND
-- BATS framework (optional): BATS_EXECUTABLE-NOTFOUND
--
-- Build options:
-- SSG vendor string: ssgproject
-- Target OVAL version: 5.11
-- OVAL schematron validation: ON
-- shellcheck bash fixes validation: OFF
-- SVG logo in XCCDFs: ON
-- Separate SCAP files: ON
-- jinja2 cache: enabled
-- jinja2 cache dir: /home/username/Projects/scap-security-guide-0.1.49/build/jinja2_cache
--
-- Products:
-- Chromium: OFF
-- Debian 8: OFF
-- Debian 9: OFF
-- Debian 10: OFF
-- JBoss EAP 6: OFF
-- Example: OFF
-- Fedora: OFF
-- Firefox: OFF
-- JBoss Fuse 6: OFF
-- JRE: OFF
-- OCP3: OFF
-- OCP4: OFF
-- Oracle Linux 7: OFF
-- Oracle Linux 8: OFF
-- openSUSE: OFF
-- RHEL 6: OFF
-- RHEL 7: OFF
-- RHEL 8: OFF
-- RHOSP10: OFF
-- RHOSP13: OFF
-- RHV 4: OFF
-- SUSE 11: OFF
-- SUSE 12: OFF
-- Ubuntu 14.04: OFF
-- Ubuntu 16.04: OFF
-- Ubuntu 18.04: ON
-- WRLinux 8: OFF
-- WRLinux 1019: OFF
--
-- Scanning for dependencies of ubuntu1804 fixes (bash, ansible, puppet, anaconda and ignition)...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/username/Projects/scap-security-guide-0.1.49/build

**Comment by scott-mackenzie** [comment]
Ran again cleaning up all errors to ensure all tools in place:

>>
-- SCAP Security Guide 0.1.49
-- (see /home/username/Projects/scap-security-guide-0.1.49/docs/manual/developer_guide.adoc for build instructions)
--
-- CMake:
-- build type: Release
-- generator: Ninja
-- source directory: /home/username/Projects/scap-security-guide-0.1.49
-- build directory: /home/usernameProjects/scap-security-guide-0.1.49/build
--
-- Tools:
-- python: /usr/bin/python3 (version: 3.8.2)
-- python yaml module: /usr/lib/python3/dist-packages/yaml
-- python jinja2 module: /usr/lib/python3/dist-packages/jinja2
-- oscap: /usr/local/bin/oscap (version: 1.3.3)
-- xsltproc: /usr/bin/xsltproc
-- xmllint: /usr/bin/xmllint
-- xmlwf: /usr/bin/xmlwf
-- sed: /usr/bin/sed
-- shellcheck (optional): /usr/bin/shellcheck
-- linkchecker (optional): /usr/local/bin/linkchecker
-- grep (optional): /usr/bin/grep
-- python pytest module (optional): /usr/lib/python3/dist-packages/pytest.py
-- ansible-playbook module (optional): /usr/bin/ansible-playbook
-- ansible-lint module (optional): /usr/bin/ansible-lint
-- yamllint module (optional): /usr/bin/yamllint
-- BATS framework (optional): /usr/bin/bats
--
-- Build options:
-- SSG vendor string: ssgproject
-- Target OVAL version: 5.11
-- OVAL schematron validation: ON
-- shellcheck bash fixes validation: OFF
-- SVG logo in XCCDFs: ON
-- Separate SCAP files: ON
-- jinja2 cache: enabled
-- jinja2 cache dir: /home/username/Projects/scap-security-guide-0.1.49/build/jinja2_cache
--
-- Products:
-- Chromium: OFF
-- Debian 8: OFF
-- Debian 9: OFF
-- Debian 10: OFF
-- JBoss EAP 6: OFF
-- Example: OFF
-- Fedora: OFF
-- Firefox: OFF
-- JBoss Fuse 6: OFF
-- JRE: OFF
-- OCP3: OFF
-- OCP4: OFF
-- Oracle Linux 7: OFF
-- Oracle Linux 8: OFF
-- openSUSE: OFF
-- RHEL 6: OFF
-- RHEL 7: OFF
-- RHEL 8: OFF
-- RHOSP10: OFF
-- RHOSP13: OFF
-- RHV 4: OFF
-- SUSE 11: OFF
-- SUSE 12: OFF
-- Ubuntu 14.04: OFF
-- Ubuntu 16.04: OFF
-- Ubuntu 18.04: ON
-- WRLinux 8: OFF
-- WRLinux 1019: OFF
--
-- Scanning for dependencies of ubuntu1804 fixes (bash, ansible, puppet, anaconda and ignition)...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/username/Projects/scap-security-guide-0.1.49/build

**Comment by scott-mackenzie** [comment]
I have purged the "build" directory and started from /usr/local/src/scap-security-guide-0.1.49/ running the ./build_product ubuntu1804 and the logs are 100% clean without warning or error listed.  Same results...

**Comment by yuumasato** [comment]
Hi,

I checked out `0.1.49` locally and I see a failure on the guides only:
```
[dagobah build{(HEAD detached at v0.1.49)}]$ ctest -j4 -R linkchecker --output-on-failure
Test project /home/wsato/git/content/build
    Start 1: linkchecker-ssg-guides
    Start 2: linkchecker-ssg-tables
1/2 Test #2: linkchecker-ssg-tables ...........   Passed    0.22 sec
2/2 Test #1: linkchecker-ssg-guides ...........***Failed   10.46 secLinkChecker 9.4.0              Copyright (C) 2000-2014 Bastian Kleineidam
LinkChecker comes with ABSOLUTELY NO WARRANTY!
This is free software, and you are welcome to redistribute it
under certain conditions. Look at the file `LICENSE' within this
distribution.
Get the newest version at http://wummel.github.io/linkchecker/
Write comments and bugs to https://github.com/wummel/linkchecker/issues
Support this project at http://wummel.github.io/linkchecker/donations.html

Start checking at 2020-05-14 17:13:25+002
10 threads active,    19 links queued,    4 links in  36 URLs checked, runtime 1 seconds
10 threads active,    11 links queued,   32 links in  63 URLs checked, runtime 6 seconds

URL        `https://www.debian.org/doc/manuals/debian-faq/ch-pkgtools.en.html'
Name       `apt'
Parent URL file:///home/wsato/git/content/build/guides/ssg-ubuntu1804-guide-default.html, line 2630, col 75
Real URL   https://www.debian.org/doc/manuals/debian-faq/ch-pkgtools.en.html
Check time 0.191 seconds
Size       7KB
Result     Error: 404 Not Found

Statistics:
Downloaded: 3.16MB.
Content types: 0 image, 46 text, 0 video, 0 audio, 7 application, 0 mail and 0 other.
URL lengths: min=18, max=241, avg=60.

That's it. 53 links in 76 URLs checked. 0 warnings found. 1 error found.
Stopped checking at 2020-05-14 17:13:35+002 (9 seconds)


50% tests passed, 1 tests failed out of 2
```

This specific URL was already fixed in https://github.com/ComplianceAsCode/content/pull/5647
Latest upstream seems to be OK.

@scott-mackenzie  Could you try testing with `--output-on-failure` to check if the problematic URL is the same?

**Comment by yuumasato** [comment]
Re-open if the issue persists.

**Comment by ayushgupta9198** [comment]
**Hi all ,

This issue was solved by me you can find the solution in my profile

Thanks for your time**

**Comment by ggbecker** [comment]
> *Hi all ,
> 
> This issue was solved by me you can find the solution in my profile
> 
> Thanks for your time*

Ok, I think ^^^ this is some kind of spam ;)

Anyway I feel that the original issue of make not finding the target is that because the author's setup was using `Ninja` to build the system, this is automatically detected by the `build_product` script and used if it detects the presence of it. `Ninja` is supposed to build the content faster. In this case you should run `ninja` when rebuilding the content (https://complianceascode.readthedocs.io/en/latest/manual/developer/02_building_complianceascode.html#using-ninja-for-faster-builds)
