### ISSUE TITLE
Can't build content with python 3.9

### ISSUE THREAD

**Issue by vojtapolasek** [ComplianceAsCode/content#5816]
#### Description of problem:

Build of content fails on import error with Python 3.9, probably because the module cElementTree is no longer available.

#### SCAP Security Guide Version:

0.1.49 and possible more

#### Operating System Version:
Fedora Rawhide

#### Steps to Reproduce:

1. download sources for SSG 0.1.49
2. unpack and run: ./build_product fedora
3. see attachment for results.

#### Actual Results:
The build gets aborted.

#### Expected Results:
The build finishes successfully.

**Comment by jan-cerny** [comment]
Yes, cElementTree is deprecated and is removed in Python 3.9. We need a fix similar to the fix that has been done in OpenSCAP Daemon: https://github.com/OpenSCAP/openscap-daemon/pull/149
