### ISSUE TITLE
Problem with a regex | Version : 0.1.41

### ISSUE THREAD

**Issue by Corsecpas** [ComplianceAsCode/content#5842]
Hello everyone,

So I write a message about a regew who doesn't work. **Scap version : 0.1.41**

I'm working on a rule to detect specific local additions to the /etc/passwd file.

I thought in this way: There must be no "+" in the file. So creating a regex that detects all the signs except the "+" allows to know if there was an addition or not.

However it doesn't work. Does anyone have an idea about this problem ? 

here is the oval in question : 
<def-group oval_version="5.11">
  <definition class="compliance" id="remove_deprecated_nis_entries" version="1">
    <metadata>
      <title>Remove deprecated NIS entries</title>
      <affected family="unix">
        <platform>Red Hat Enterprise Linux 7</platform>
      </affected>
      <description>NIS and NIS+ entries must be removed from password, group and shadow files.</description>
    </metadata>
        <criteria operator="AND">
          <criterion comment="it's a test" test_ref="test_remove_deprecated_nis_entries"/>
        </criteria>
  </definition>

  <ind:textfilecontent54_test check="at least one" check_existence="all_exist" comment="It's a test" id="test_remove_deprecated_nis_entries" version="1" >
    <ind:object object_ref="obj_remove_deprecated_nis_entries" />
  </ind:textfilecontent54_test>

  <ind:textfilecontent54_object id="obj_remove_deprecated_nis_entries" version="2">
    <ind:filepath operation="equals">/etc/passwd</ind:filepath>
    <ind:pattern operation="pattern match">^(^[a-zA-Z0-9:/-]*\s*\r*$)*$</ind:pattern>
    <ind:instance operation="equals" datatype="int">1</ind:instance>
  </ind:textfilecontent54_object>

</def-group>

I know that there are an other problem who is that the sign "-" at the beginnning a line must be detected like an fail. 

Good day !

**Comment by vojtapolasek** [comment]
Hello, I believe we have already solved your problem.
https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_legacy_plus_entries_etc_passwd/oval/shared.xml#L13
Of course this holds if your problem is strictly with usage of OVAL. You can basically negate the test evaluation as done in this example.
If you would like to match it with general regex in some other case, I think you would need to use regex lookarounds.
Does this solve your problem?

**Comment by redhatrises** [comment]
Also,  https://regex101.com/ (make sure to use the PCRE option) is
extremely helpful for testing and visualizing regex matches against data,
and many have used and recommended it in the past.

**Comment by yuumasato** [comment]
@Corsecpas Hi, 

The rule pointed out by Vojtech seems to do what you are looking for.
Re-open, or open another issue if this is not what you meant.
