### ISSUE TITLE
Support for openSCAP for Raspberry Pi OS?

### ISSUE THREAD

**Issue by girishkumarbk** [ComplianceAsCode/content#5847]
#### Description of problem:
Scan on Raspberry pi OS results in report with "Not applicable" messages.

#### SCAP Security Guide Version:

15:36:24 | info | SCAP Workbench 1.1.5, compiled with Qt 4.8.7, using OpenSCAP 1.3.0

#### Operating System Version:
pi@k3smaster:~ $ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

#### Steps to Reproduce:

1. Install scap-workbench on MAC
2.Open the Scapulas-workbench from Mac and select Debian8 or Ubuntu 16/18 as OS for scan
3.Select remote raspberry pi as target for scan
4.Execute the scan

#### Actual Results:
<img width="819" alt="RaspberryPi-SCAP-Report" src="https://user-images.githubusercontent.com/6768794/84761128-9d065c00-afe6-11ea-9a85-1285086b35fa.png">

#### Expected Results:

Scan report for Raspberry Pi OS.

#### Addition Information/Debugging Steps:

Fix for above problem is detailed in this discussion at 
https://github.com/OpenSCAP/scap-workbench/issues/263

**Comment by ggbecker** [comment]
Probably the CPE check for this platform needs to be extended as described here: https://github.com/OpenSCAP/scap-workbench/issues/263#issuecomment-644650774

**Comment by evgenyz** [comment]
Can you please also add contents of `/etc/debian_version` file (if it exists)?

**Comment by girishkumarbk** [comment]
Here it is
 
pi@k3smaster:~ $ cat /etc/debian_version 
10.4

**Comment by evgenyz** [comment]
I can see from the screenshot you provided that you are using `ssg-ubuntu1604-ds.xml`. The Raspberry Pi OS is a flavour of Debian, not Ubuntu. You should try `ssg-debian10-ds.xml`.

**Comment by girishkumarbk** [comment]
Have tried Debian8 ... Debian10 option is not available in scap-workbench.
<img width="796" alt="RaspberryPi-SCAP-Report-Debian8" src="https://user-images.githubusercontent.com/6768794/84772337-6cc7b900-aff8-11ea-8939-80ad1e028322.png">

**Comment by evgenyz** [comment]
So, then you have an old SSG package. Debian 8 content is natuarlly *not applicable* to Debian 10. I could recommend building content DS from sources: https://github.com/ComplianceAsCode/content/blob/master/docs/manual/developer_guide.adoc. The product you're looking for is **debian10**: `./build_product debian10`, the Data Stream would be located in `./build/` directory.

**Comment by ggbecker** [comment]
> So, then you have an old SSG package. Debian 8 content is naturally _not applicable_ to Debian 10. I could recommend building content DS from sources: https://github.com/ComplianceAsCode/content/blob/master/docs/manual/developer_guide.adoc. The product you're looking for is **debian10**: `./build_product debian10`, the Data Stream would be located in `./build/` directory.

or @girishkumarbk can download the latest released version of ComplianceAsCode/content and extract the datastream for Debian10: https://github.com/ComplianceAsCode/content/releases/download/v0.1.50/scap-security-guide-0.1.50.zip

**Comment by girishkumarbk** [comment]
> > So, then you have an old SSG package. Debian 8 content is naturally _not applicable_ to Debian 10. I could recommend building content DS from sources: https://github.com/ComplianceAsCode/content/blob/master/docs/manual/developer_guide.adoc. The product you're looking for is **debian10**: `./build_product debian10`, the Data Stream would be located in `./build/` directory.
> 
> or @girishkumarbk can download the latest released version of ComplianceAsCode/content and extract the datastream for Debian10: https://github.com/ComplianceAsCode/content/releases/download/v0.1.50/scap-security-guide-0.1.50.zip

----------------------------
Voila!!!  With Debian10 SSG package openSCAP scan worked on Raspberry Pi OS.  Thanks for quick resolution!

<img width="791" alt="RaspberryPi-SCAP-Report-Debian10" src="https://user-images.githubusercontent.com/6768794/84777707-946e4f80-afff-11ea-99ee-bf8c82e0b579.png">
