### ISSUE TITLE
ocp3 runtime checks for etcd seems not to work correctly

### ISSUE THREAD

**Issue by mirogl** [ComplianceAsCode/content#5853]
![oval_test_1](https://user-images.githubusercontent.com/46027543/84863117-b950da00-b074-11ea-80fb-674d21bc6439.png)
![oval_test_2](https://user-images.githubusercontent.com/46027543/84863118-b9e97080-b074-11ea-8edc-79c9b163d1cc.png)
![oval_test_3](https://user-images.githubusercontent.com/46027543/84863119-b9e97080-b074-11ea-919c-e9946b99cea6.png)

#### Description of problem:
Hi
I have testet the ocp3 runttime checks on multiple clusters. All of the etcd checks fail, because the runtime check fails. But the configuration check is true.

As an example -  for the file ssg-ocp3-ds.xml with profile xccdf_org.ssgproject.content_profile_opencis-master and rule xccdf_org.ssgproject.content_rule_etcd_client_cert_auth

ETCD_CLIENT_CERT_AUTH=true
is set in /etc/etcd/etcd.conf

Node is rebootet - but the runtimecheck still always hows false for the runtime check.
This is the problem on all my clusters with all etcd checks. All parameter are set correctly in the  /etc/etcd/etcd.conf (result shown as true) - but runtime checks fails for every etcd check.

Can you please explain me, how this runtime check is implemented for etcd ? It seems to look for parameters, which are not there. I added a screenshot of the check result.

With which command (e.g. etcdctl) can i  manually check for the parameters on runtime ?

Many thanks

#### SCAP Security Guide Version:
latest master

#### Operating System Version:
Openshift 3.11 / RedHat Enterprise Linux 7.8

#### Steps to Reproduce:

1. oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_opencis-master --rule xccdf_org.ssgproject.content_rule_etcd_client_cert_auth --results /var/tmp/$(hostname)-hardening-ocp3-report.xml --report /var/tmp/$(hostname)-hardening-ocp3-report.html ssg-ocp3-ds.xml
2.
3.
4.

#### Actual Results:

runtime check for all etcd checks failes on master, but the configuration file parameters are correctly set and node is restartet.

#### Expected Results:
runtimecheck should also be true, since the calues are correct in the configuration file and node is restarted

**Comment by p-cunning** [comment]
Same, experiencing failures against all but 1 etcd checks for OCP3 against latest release (0.1.51)

**Comment by yuumasato** [comment]
Should be handled by https://github.com/ComplianceAsCode/content/blob/master/applications/openshift/etcd/etcd_client_cert_auth/rule.yml.
This rule evaluates to PASS by default .
