### ISSUE TITLE
ocp3 check wrong for xccdf_org.ssgproject.content_rule_api_server_anonymous_auth

### ISSUE THREAD

**Issue by mirogl** [ComplianceAsCode/content#5855]
#### Description of problem:

The pattern test for the file ssg-ocp3-ds.xml with profile xccdf_org.ssgproject.content_profile_opencis-master and rule xccdf_org.ssgproject.content_rule_api_server_anonymous_auth
is wrong.

the pattern check should look for "anonymous-auth"

apiServerArguments:
  anonymous-auth:
  - 'false'

but looks for "profiling" - which is from another rule

^[\s]*kubernetesMasterConfig\:(?:[^\n]*\n+)+?[\s]*apiServerArguments\:(?:[^\n]*\n+)+?[\s]*profiling\:[\s]*[\n]+[\s]*-[\s]+(\S+)[\s]*$

#### SCAP Security Guide Version:
lastest

#### Operating System Version:
OpenShift 3.11 / RedHat Enterprise Linux 7.8

#### Steps to Reproduce:

1. oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_opencis-master --rule xccdf_org.ssgproject.content_rule_api_server_anonymous_auth --results /var/tmp/$(hostname)-hardening-ocp3-report.xml --report /var/tmp/$(hostname)-hardening-ocp3-report.html /root/scap-security-guide-0.1.50/ssg-ocp3-ds.xml
2.
3.
4.

#### Actual Results:
Check result is false, since it searches for a  different rule

#### Expected Results:
Check Result should be true, if anonymous-auth: is seet to 'false'
![pattern_test](https://user-images.githubusercontent.com/46027543/84864807-852ae880-b077-11ea-9747-8a4ad8fc5fb9.PNG)

**Comment by rmetrich** [comment]
See #5860
