### ISSUE TITLE
ocp3 test wrong  for xccdf_org.ssgproject.content_rule_api_server_service_account_private_key

### ISSUE THREAD

**Issue by mirogl** [ComplianceAsCode/content#5856]
#### Description of problem:

The pattern test for the file ssg-ocp3-ds.xml with profile xccdf_org.ssgproject.content_profile_opencis-master and rule xccdf_org.ssgproject.content_rule_api_server_service_account_private_key
is wrong.
![pattern_test](https://user-images.githubusercontent.com/46027543/84865569-c079e700-b078-11ea-9a93-a0cd65325a0b.PNG)

Current search for "privateKeyFiles:", but should be "privateKeyFile:" - due to the documentation

^[\s]*serviceAccountConfig\:(?:[^\n]*\n+)+?[\s]*privateKeyFiles\:[\s]+(\S+)[\s]*$

#### SCAP Security Guide Version:
latest

#### Operating System Version:
OpenShift 3.11 / RedHat Linux 7.8

#### Steps to Reproduce:

1. oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_opencis-master --rule xccdf_org.ssgproject.content_rule_api_server_service_account_private_key --results /var/tmp/$(hostname)-hardening-ocp3-report.xml --report /var/tmp/$(hostname)-hardening-ocp3-report.html ssg-ocp3-ds.xml
2.
3.
4.

#### Actual Results:
false, if "privateKeyFile:" exists 

#### Expected Results:
true, if "privateKeyFile:" exists

**Comment by rmetrich** [comment]
See #5860

**Comment by yuumasato** [comment]
Fixed by #5860
