### ISSUE TITLE
Enable Kernel Page-Table Isolation (KPTI) Redhat CoreOS 4

### ISSUE THREAD

**Issue by cynthia-rempel** [ComplianceAsCode/content#5876]
#### Description of problem:
There appears to be no /etc/default/grub on Redhat CoreOS 4.3

#### SCAP Security Guide Version:
Guide to the Secure Configuration of Red Hat Enterprise Linux CoreOS 4
with profile NIST 800-53 Moderate-Impact Baseline for Red Hat Enterprise Linux CoreOS

#### Operating System Version:
Redhat CoreOS 4.3

#### Steps to Reproduce:

1. Deploy openshift-compliance operator
2. Run a worker scan
3. Look at Enable Kernel Page-Table Isolation (KPTI)
4. Do a cat etc/default/grub

#### Actual Results:
cat /etc/default/grub
cat: /etc/default/grub: No such file or directory

#### Expected Results:
There is a file there.

#### Addition Information/Debugging Steps:
So I looked at:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_monitoring_and_updating_the_kernel/configuring-kernel-command-line-parameters_managing-monitoring-and-updating-the-kernel

sudo ls /boot/loader/entries
sudo cat /boot/loader/entries/ostree-2-rhcos.conf

```
title Red Hat Enterprise Linux CoreOS 43.81.202004280317.0 (Ootpa) (ostree:1)
version 1
options $ignition_firstboot rhcos.root=crypt_rootfs console=tty0 console=ttyS0,115200n8 ignition.platform.id=metal rd.luks.options=discard ostree=/ostree/boot.0/rhcos/433e70f3654c3434de00ae89744cf58bb34517edf6a8828677a24f1f2455d363/0 
linux /ostree/rhcos-433e70f3654c3434de00ae89744cf58bb34517edf6a8828677a24f1f2455d363/vmlinuz-4.18.0-147.8.1.el8_1.x86_64
initrd /ostree/rhcos-433e70f3654c3434de00ae89744cf58bb34517edf6a8828677a24f1f2455d363/initramfs-4.18.0-147.8.1.el8_1.x86_64.img
```
sudo grubby --update-kernel=ALL --args="pti=on"
sudo cat /boot/loader/entries/ostree-2-rhcos.conf
```
title Red Hat Enterprise Linux CoreOS 43.81.202004280317.0 (Ootpa) (ostree:1)
version 1
options $ignition_firstboot rhcos.root=crypt_rootfs console=tty0 console=ttyS0,115200n8 ignition.platform.id=metal rd.luks.options=discard ostree=/ostree/boot.0/rhcos/433e70f3654c3434de00ae89744cf58bb34517edf6a8828677a24f1f2455d363/0 pti=on
linux /ostree/rhcos-433e70f3654c3434de00ae89744cf58bb34517edf6a8828677a24f1f2455d363/vmlinuz-4.18.0-147.8.1.el8_1.x86_64
initrd /ostree/rhcos-433e70f3654c3434de00ae89744cf58bb34517edf6a8828677a24f1f2455d363/initramfs-4.18.0-147.8.1.el8_1.x86_64.img
```
sudo systemctl reboot

sudo cat /boot/grub2/grubenv
```
# GRUB Environment Block
kernelopts=pti=on
```
Thanks!

Another way to document the rule might include the machine config operator...

**Comment by redhatrises** [comment]
I believe that this being worked or has already been addressed at #5285

**Comment by cynthia-rempel** [comment]
Thanks for letting me know to check /proc/cmdline! My main concern was I didn't see an /etc/default/grub file, so assumed that meant that wasn't how to fix the problem, so I think these are two related issues.

I will look attempt to figure out how to set pti=on in there.

**Comment by cynthia-rempel** [comment]
After checking, it appears:

sudo cat /proc/cmdline
BOOT_IMAGE=(hd0,gpt1)/ostree/rhcos-83263211d5d51cab10b785b1c37a5b941a4654635451f1d24281d9bc5b40a1b5/vmlinuz-4.18.0-147.8.1.el8_1.x86_64 rhcos.root=crypt_rootfs console=tty0 console=ttyS0,115200n8 ignition.platform.id=metal rd.luks.options=discard ostree=/ostree/boot.0/rhcos/83263211d5d51cab10b785b1c37a5b941a4654635451f1d24281d9bc5b40a1b5/0 pti=on

So setting  /boot/grub2/grubenv using grubby, then rebooting the node worked

**Comment by cynthia-rempel** [comment]
As ` sudo grubby --update-kernel=ALL --args="pti=on" && sudo systemctl reboot ` make the check compliant for both the ` /boot/grub2/grubenv ` and the `/proc/cmdline` , could the directions be updated?

**Comment by cynthia-rempel** [comment]
Ideally the remediation instructions might include a sysctl command instead of a reboot, but I wasn't able to find one.

**Comment by redhatrises** [comment]
@cynthia-rempel manually making changes to RHCOS is not recommended in this way at all. Work is being done for OCP cluster level remediation.

**Comment by cynthia-rempel** [comment]
Thanks!  Could the directions be changed to read using OCP cluster level remediation?

**Comment by cynthia-rempel** [comment]
Am I correct in assuming the directions should read:

Either create or modify 99_openshift-machineconfig_worker-kargs to have pti=on

Example: 99_openshift-machineconfig_worker-kargs

```
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99_openshift-machineconfig_worker-kargs
spec:
  kernelArguments:
    - 'pti=on'
```
Reference: https://docs.openshift.com/container-platform/4.3/installing/install_config/installing-customizing.html

**Comment by JAORMX** [comment]
@cynthia-rempel right, that should be what the directions should say.

If you would auto-remediate with the compliance-operator, you would get the following remediation:

https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/bootloader-grub2/grub2_pti_argument/kubernetes/shared.yml
