### ISSUE TITLE
CIS compiance

### ISSUE THREAD

**Issue by themeswordpress** [ComplianceAsCode/content#5891]
Can I use it for CIS compliance?

**Comment by redhatrises** [comment]
If I am understanding your question, the `CIS` profile should help with this assuming that the CIS profile is 100% complete.

**Comment by themeswordpress** [comment]
Can i use this tool for CISOC ios ? i mean to run cisco becnhmark ???

**Comment by redhatrises** [comment]
If you want to create content for CISCO IOS, then yes. However, as no content exists for Cisco IOS, I don't see a way of doing that.

**Comment by redhatrises** [comment]
Closing this issue as it seems like there is nothing more to discuss. Please re-open if there is more!
