### ISSUE TITLE
scap-security-guide package for Centos 8 missing ssg-centos*-ds.xml files

### ISSUE THREAD

**Issue by martinbydefault** [ComplianceAsCode/content#5895]
#### Description of problem:
The `scap-security-guide` RPM package in CentOS 8 (https://centos.pkgs.org/8/centos-appstream-x86_64/scap-security-guide-0.1.48-7.el8.noarch.rpm.html) does not contain the file: `/usr/share/xml/scap/ssg/content/ssg-centos8-ds.xml`.
In fact the rpm doesn't provide any `ssg-centos*` file.

While in the other hand, the package for centos 7 does contain all `ssg-centos*` files: https://centos.pkgs.org/7/centos-x86_64/scap-security-guide-0.1.46-11.el7.centos.noarch.rpm.html

Is there any reason for this? I'm not sure who is responsible for the maintenance of this package or is there any reason why this is happening?
I detected this problem because I have an automation using ansible where I use this in a template with system dependent variables: `/usr/share/xml/scap/ssg/content/ssg-{{distribution}}{{ansible_distribution_major_version}}-ds.xml` and it failed when running in Centos 8.

#### SCAP Security Guide Version:
0.1.48

#### Operating System Version:
CentOS Linux release 8.2.2004

#### Steps to Reproduce:

1. Install package ` scap-security-guide` with: `yum install scap-security-guide`
2. `cd` to folder `/usr/share/xml/scap/ssg/content`
3. There isn't any `ssg-centos*` file

#### Actual Results:
No `ssg-centos*` files are included in the rpm for Centos 8 when installed using `yum install scap-security-guide` and consequently the directory `/usr/share/xml/scap/ssg/content` doesn't have the centos files.

#### Expected Results:
The `ssg-centos*` files should be included in the rpm for Centos 8 when installed using `yum install scap-security-guide`.

**Comment by ggbecker** [comment]
Derivatives for Centos are currently disable in spec file used to build centos8 scap-security-guide package as you can see here:
https://git.centos.org/rpms/scap-security-guide/blob/c8s/f/SPECS/scap-security-guide.spec#_79

Centos maintainers need to update it similarly as they have for centos7: https://git.centos.org/rpms/scap-security-guide/blob/c7/f/SPECS/scap-security-guide.spec#_91

**Comment by martinbydefault** [comment]
My current workaround to get spec files for Centos 8 by adding the COPR repo first (https://github.com/ComplianceAsCode/content#from-copr) and then install `scap-security-guide`

@ggbecker thanks for the reference to the files producing this behavior.

So this is something that CentOS maintainers are responsible to update?
I'm not familiar with the process of reporting bugs to distribution maintainers, but I suppose in this case this should be reported at bugs.centos.org , right?

**Comment by ggbecker** [comment]
If you are using COPR, we might be able to change that. In particular I can't do that, but I guess others contributors can do since these builds IIRC are produced by us

**Comment by martinbydefault** [comment]
I meant that I solved this problem by using COPR repo in the meantime. There isn't a problem with the COPR repo, it solves my problem because it provides all the missing `ssg-centos*` files.

The problem occurs when installing `scap-security-guide` in a fresh CentOS 8 without any additional repo added.
I was asking how to report this problem to CentOS maintainers, in order to be able to get CentOS 8 profiles without needing to add COPR.

**Comment by ggbecker** [comment]
Understood. https://bugs.centos.org  seems the best place to get something changed in centos. I'm closing this issue since we cannot directly solve the issue with centos builds. Feel free to reopen if you think otherwise.

Regards.

**Comment by martinbydefault** [comment]
Thanks for pointing me in the right direction! 👍
