### ISSUE TITLE
ocp3 False positive for xccdf_org.ssgproject.content_rule_api_server_experimental_encryption_provider_config

### ISSUE THREAD

**Issue by myburneracct** [ComplianceAsCode/content#5909]
#### Description of problem:
I have an offline instance of OpenShift and I have implemented the "Configure the Encryption Provider" directive in my master-config.yaml.
/etc/origin/master/master-config.yaml:
<pre>
…
kubernetesMasterConfig:
  apiServerArguments:
    experimental-encryption-provider-config:
    - /etc/origin/master/encryption-config.yaml
…
</pre>
#### SCAP Security Guide Version:
Guide to the Secure Configuration of Red Hat Container Platform 3
SCAP Security Guide 0.1.50 for SCAP 1.3 for OCP3( https://access.redhat.com/sites/default/files/attachments/scap-security-guide-0.1.50-scap-1.3-ocp3.zip)

#### Operating System Version:
RHEL 7.6

#### Steps to Reproduce:

1. Loaded OCP3 content into SCC-5.2.1
2. Scanned master node and noted "Configure Encryption Provider" item in the output needed remediation.
3. Modified /etc/origin/master/master-config.yaml to comply with remediation recommendation. 
4. Restarted api and controllers
5. Rescanned the master node.

#### Actual Results:
Configure the Encryption Provider
Result: Fail

#### Expected Results:
Configure the Encryption Provider
Result: Pass

#### Addition Information/Debugging Steps:
I have configured the encryption provider as described in Chapter 35: Encrypting Data at Datastore Layer in the OpenShift Container Platform 3.11 Cluster Administration guide (2019-07-12). 

Ok so I have done a little more debugging with this and it appears that in the Tests, Object Requirements:
filepath must be equal to '/etc/origin/master/encryption-config.yaml' 
Should be:
filepath must be equal to '/etc/origin/master/master-config.yaml'

**Comment by yuumasato** [comment]
`experimental-encryption-provider-config` was removed in favor of `encryption-provider-config`, and we don't have any rule to configure the replacement flag.

There is a rule configuring the encryption provider cipher though:
https://github.com/ComplianceAsCode/content/blob/master/applications/openshift/api-server/api_server_encryption_provider_cipher/rule.yml
