### ISSUE TITLE
ocp3 implementing xccdf_org.ssgproject.content_rule_api_server_admission_control_plugin_EventRateLimit causes API failure

### ISSUE THREAD

**Issue by myburneracct** [ComplianceAsCode/content#5914]
#### Description of problem:
When I make the changes to the /etc/origin/master/master-config.yaml file in OpenShift 3.11 as described in the description of the control:
<pre>
admissionControl:
  pluginConfig:
    EventRateLimit:
      configuration:
        kind: DefaultAdmissionConfig
        apiVersion: v1
        disable: false
</pre>
And then I restart the api
<pre>
master-restart api
</pre>
I get the following error code:
<pre>
255
</pre>
when I review the master api logs, it indicates the following:
<pre>
F0707_10:29:18.485917     1 start_api.go:68] couldn't init admission plugin "EventRateLimit": limits: Invalid value: []eventratelimit.Limit(nil): must not be empty
</pre>

Are there more options I should be configuring? The CIS Benchmark for Kubernetes 1.2 (1.1.35)  looks as if there should be an external file referenced. However, the above stanza makes no mention of this and I can't seem to find much from the OpenShift documentation about this. I'm a little lost and out of my depth.

#### SCAP Security Guide Version:
0.1.50
Guide to the Secure Configuration of Red Hat Container Platform 3
SCAP Security Guide 0.1.50 for SCAP 1.3 for OCP3( https://access.redhat.com/sites/default/files/attachments/scap-security-guide-0.1.50-scap-1.3-ocp3.zip)
#### Operating System Version:
RHEL 7.6

#### Steps to Reproduce:

1. See above
2. If I remove the EventRateLimit stanza and restart the api server it loads without issue
3. If I set disable to true and restart the api server it loads without issue
4.

#### Actual Results:
<pre>
master-restart api
255
</pre>

#### Expected Results:
<pre>
master-restart api
2
</pre>

**Comment by yuumasato** [comment]
The rule configuring `EventRateLimit` in OCP3 was removed when its contents were deprecated.
