### ISSUE TITLE
sle15-playbook-cis.yml on openSUSE Tumbleweed 

### ISSUE THREAD

**Issue by marcredhat** [ComplianceAsCode/content#5923]
#### Description of problem:
I succesfully tested sle15-playbook-cis.yml on openSUSE Tumbleweed 20200708
as detailed at https://github.com/marcredhat/suse/blob/master/tumbleweed_Compliance_as_Code.adoc

However, I had to make several changes to sle15-playbook-cis.yml. 
My working playbook is at: https://github.com/marcredhat/suse/blob/master/sle15-playbook-cis.yml
Playbook result: https://github.com/marcredhat/suse/blob/master/sle15cisresult

#### SCAP Security Guide Version:
https://github.com/ComplianceAsCode/content/releases/download/v0.1.50/scap-security-guide-0.1.50.zip

#### Operating System Version:
Installation/config details at: https://github.com/marcredhat/suse/blob/master/tumbleweed_KVM_install.adoc
cat /usr/lib/os-release
NAME="openSUSE Tumbleweed"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20200708"

**Comment by redhatrises** [comment]
@marcredhat do you have a list of changes? If not, it is a lot of work to go through a playbook to identify what changes were done.

**Comment by ggbecker** [comment]
With a quick `diff` I was able to identify changes that he has made. I used the playbook from 0.1.50 release and the one he provided.
```
144a145
>       ignore_errors: true
163,165c164,168
<         - name: Gather the package facts
<           package_facts:
<             manager: auto
---
>         #- name: Gather the package facts
>           #ignore_errors: yes
>           #package_facts:
>           #  manager: auto
>           #ignore_errors: yes
172,173c175,176
<           when:
<             - '"audit" in ansible_facts.packages'
---
>             #when:
>             #- '"audit" in ansible_facts.packages'
3597c3600
<     - name: Ensure libselinux is installed
---
>     - name: Ensure libselinux1 is installed
3599c3602
<         name: libselinux
---
>         name: libselinux1
3693c3696
<         mode: '0640'
---
>         mode: '0400'
5223a5227
>           #ignore_errors: yes
5225a5230
>           ignore_errors: yes
5232,5233c5237,5238
<           when:
<             - '"chrony" in ansible_facts.packages'
---
>             #when:
>             #  - '"chrony" in ansible_facts.packages'
5646c5651
<     - name: Ensure tcp_wrappers is installed
---
>     - name: Ensure tcpd (proving tcp_wrappers) is installed
5648c5653
<         name: tcp_wrappers
---
>         name: tcpd
```

The error in `Gather the package facts` task is probably because of missing `python-apt` package (https://github.com/ansible/ansible/pull/60999)
```
TASK [Gather the package facts] ***********************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not detect a supported package manager from the following list: ['portage', 'rpm', 'pkg', 'apt'], or the required Python library is not installed. Check warnings for details."}
...ignoring
```

So the changes are basically different package names.
