### ISSUE TITLE
Some rules are failing after applying Ansible remediation

### ISSUE THREAD

**Issue by matusmarhefka** [ComplianceAsCode/content#5937]
#### Description of problem:
The following rules are failing even after applying their Ansible remediation:
```
configure_opensc_card_drivers
force_opensc_card_drivers
sssd_enable_smartcards
network_nmcli_permissions
```

#### SCAP Security Guide Version:
master

#### Operating System Version:
RHEL8

#### Steps to Reproduce:

1. Apply Ansible remediation of rules mentioned in the description and after that perform scan to verify that these rules are fixed.

**Comment by carlosmmatos** [comment]
@matusmarhefka What playbook were you using?

**Comment by matusmarhefka** [comment]
@carlosmmatos To reproduce you can for example use the one for `ism_o` profile (Australian Cyber Security Centre (ACSC) Information Security Manual (ISM) Official). It should contain all of these rules.
