### ISSUE TITLE
Rule uefi_no_removeable_media fails even on non-UEFI systems

### ISSUE THREAD

**Issue by matusmarhefka** [ComplianceAsCode/content#6028]
#### Description of problem:
Rule `uefi_no_removeable_media` fails even on non-UEFI systems, rule check should be made more robust to first verify if the system uses UEFI and only then to check the configuration.

#### SCAP Security Guide Version:
master

#### Operating System Version:
RHEL7

#### Steps to Reproduce:
Run the following on non-UEFI system:
`oscap xccdf eval --profile '(all)' --rule xccdf_org.ssgproject.content_rule_uefi_no_removeable_media ssg-rhel7-ds.xml`
and the rule will fail even though it should rather be not applicable or pass.

**Comment by ggbecker** [comment]
Do you know how one can identify UEFI systems?

**Comment by redhatrises** [comment]
I ultimately think CPE is the right way to go to turn applicability on/off. CPE should also be checked for ZIPL configurations.
For UEFI, I believe that a check for if `/sys/firmware/efi` directory exists that UEFI is in use.
