### ISSUE TITLE
ressource unavailable

### ISSUE THREAD

**Issue by aurelien-git** [ComplianceAsCode/content#6108]
#### Description of problem:
disa.mil resources are unavailable

#### SCAP Security Guide Version:
1.3

#### Operating System Version:
centos8

#### Steps to Reproduce:

1. read the doc and try to access all disa stuff like 
2. http://iase.disa.mil/stigs/Pages/stig-viewing-guidance.aspx
3.
4.

#### Actual Results:
no resource

#### Expected Results:
got the resource

**Comment by jan-cerny** [comment]
I think that they replaced iase.disa.mil by https://public.cyber.mil/.

This might be relevant: https://github.com/ComplianceAsCode/content/pull/4392/

**Comment by aurelien-git** [comment]
This sounds ok ... But it need to be confirmed by a team member.
It would be nice to correct the documentation with that links ... if they are the right one.
The trouble on my side is to use the STIG stuff correctly.
Thanks for all

**Comment by ggbecker** [comment]
There are no other open questions since upstream code is already using correct links for STIGs.

Closing issue. @aurelien-git feel free to reopen if you think this still requires some more answers.
