### ISSUE TITLE
RHEL7 STIG ids assigned to mutiple rules

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#6113]
#### Description of problem:

Following rules contain the same STIG ID (FYI @redhatrises):

- `RHEL-07-010010`
  - [rpm_verify_ownership](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_ownership/rule.yml#L38)
  - [rpm_verify_permissions](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_permissions/rule.yml#L56)

- `RHEL-07-010320`
  - [accounts_passwords_pam_faillock_deny](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_deny/rule.yml#L47)
  - [accounts_passwords_pam_faillock_interval](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_interval/rule.yml#L53)
  - [accounts_passwords_pam_faillock_unlock_time](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_unlock_time/rule.yml#L51)

- `RHEL-07-010481`
  - [require_emergency_target_auth](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-physical/require_emergency_target_auth/rule.yml#L28)
  - [require_singleuser_auth](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-physical/require_singleuser_auth/rule.yml#L40)

- `RHEL-07-021700`
  - [grub2_no_removeable_media](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/bootloader-grub2/grub2_no_removeable_media/rule.yml#L27)
  - [uefi_no_removeable_media](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/bootloader-grub2/uefi_no_removeable_media/rule.yml#L26)

- `RHEL-07-030340`
  - [auditd_data_retention_admin_space_left_action](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_retention_admin_space_left_action/rule.yml#L45)
  - [auditd_data_retention_space_left_action](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_retention_space_left_action/rule.yml#L42)

- `RHEL-07-030710`
  - [audit_rules_privileged_commands_newgrp](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_newgrp/rule.yml#L49)
  - [audit_rules_usergroup_modification](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_usergroup_modification/rule.yml#L54)

- `RHEL-07-030740`
  - [audit_rules_privileged_commands_mount](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_mount/rule.yml#L45)
  - [audit_rules_media_export](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_media_export/rule.yml#L49)

- `RHEL-07-032000`
  - [install_antivirus](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/software/integrity/endpoint_security_software/install_antivirus/rule.yml#L38)
  - [install_mcafee_antivirus](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/software/integrity/endpoint_security_software/mcafee_security_software/install_mcafee_antivirus/rule.yml#L27)

- `RHEL-07-040200`
  - [sssd_ldap_configure_tls_ca](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/services/sssd/sssd-ldap/sssd_ldap_configure_tls_ca/rule.yml#L35)
  - [sssd_ldap_configure_tls_ca_dir](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/services/sssd/sssd-ldap/sssd_ldap_configure_tls_ca_dir/rule.yml#L35)

#### Additional Information:

- Command used to generate the info:

`cd linux_os/guide/ && cat ../../shared/references/disa-stig-rhel7-v2r8-xccdf-manual.xml | grep -o "RHEL-07-[0-9]*<" | grep -o "RHEL-07-[0-9]*" | xargs -L 1 grep -R | grep -o "RHEL-07-[0-9]*" | sort | uniq -c | grep -v "1 " > duplicated`

**Comment by Mab879** [comment]
@ggbecker  It seems we are fine with many rules sharing tho same STIG ID now. Do we want to close this? 

Current stats with your script:

- 
-       2 RHEL-07-010010
-       3 RHEL-07-010270
-       3 RHEL-07-010320
-       2 RHEL-07-010481
-       3 RHEL-07-020019
-       2 RHEL-07-021700
-       2 RHEL-07-030340
-       2 RHEL-07-030710
-       2 RHEL-07-030740
-       2 RHEL-07-032000
-       2 RHEL-07-040200
-       2 RHEL-07-040340
-       2 RHEL-07-040730
-       2 RHEL-07-910055

**Comment by ggbecker** [comment]
Let's close this one. It should be fine to have them duplicate but we should record them so we can work with DISA to split wherever it makes sense.
