### ISSUE TITLE
RHEL7 STIG profile Ansible playbook failing

### ISSUE THREAD

**Issue by matusmarhefka** [ComplianceAsCode/content#6115]
#### Description of problem:
When remediating RHEL7 STIG Ansible playbook there is an error which causes that remediation is aborted. Task which fails and is responsible for the abort:
```
...

TASK [Replace all instances of SNMP RO strings] ********************************
fatal: [192.168.122.90]: FAILED! => {"changed": false, "msg": "Path /etc/snmp/snmpd.conf does not exist !", "rc": 257}

PLAY RECAP *********************************************************************
192.168.122.90             : ok=509  changed=254  unreachable=0    failed=1    skipped=100  rescued=0    ignored=0
```
Looks like ordering problem, the file `/etc/snmp/snmpd.conf` is provided by the `net-snmp` package.

#### SCAP Security Guide Version:
master

#### Operating System Version:
RHEL7

#### Steps to Reproduce:
`ansible-playbook rhel7-playbook-stig.yml`

**Comment by vojtapolasek** [comment]
The problem is that there is no rule for installing snmpd in the profile and snmpd is probably not installed on the system while testing. I think we need another platform.

**Comment by ggbecker** [comment]
> The problem is that there is no rule for installing snmpd in the profile and snmpd is probably not installed on the system while testing. I think we need another platform.

But I guess we have to check if the file exists or not in the remediation, because one can even try to apply individually this remediation and it shouldn't return any error. See: #6116

**Comment by ggbecker** [comment]
> The problem is that there is no rule for installing snmpd in the profile and snmpd is probably not installed on the system while testing. I think we need another platform.

I guess the platform CPE for snmpd is needed as well
