### ISSUE TITLE
"Ensure Red Hat GPG Key Installed" fails on CentOS 8

### ISSUE THREAD

**Issue by lentferj** [ComplianceAsCode/content#6149]
#### Description of problem:
Running this on CentOS 8 / aarch64 (8.2.2004 (Core))

Benchmark URL: /usr/share/xml/scap/ssg/content/ssg-centos8-ds.xml
Bechmark ID: xccdf_org.ssgproject.content_benchmark_RHEL-8
Benchmark version: 0.1.52
Profile ID: xccdf_org.ssgproject.content_profile_standard

The system is successfully registered to a Foreman/Katello host providing repositories and patch management. All keys are installed - but those are CentOS keys, not RedHat, naturally.

```
# rpm -q gpg-pubkey --qf '%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n'
gpg-pubkey-8483c65d-5ccc5b19    gpg(CentOS (CentOS Official Signing Key) <security@centos.org>)
gpg-pubkey-2f86d6a1-5cf7cefb    gpg(Fedora EPEL (8) <epel@fedoraproject.org>)
```

#### SCAP Security Guide Version:
0.1.52

#### Operating System Version:
CentOS 8 / aarch64 (8.2.2004 (Core))

#### Steps to Reproduce:

1. oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_standard --results-arf arf.xml  --report report.html /usr/share/xml/scap/ssg/content/ssg-centos8-ds.xml
2. "Ensure Red Hat GPG Key Installed" fails

#### Expected Results:
On CentOS the test should check for CentOS key and pass, when existing.

**Comment by ggbecker** [comment]
#6151 Should address this issue, but notice that it doesn't update any of the remediations... only the OVAL check was fixed to include CentOS8 GPG key
