### ISSUE TITLE
Aide remediation bash scripts add config to incorrect lines

### ISSUE THREAD

**Issue by gcampbell12** [ComplianceAsCode/content#6150]
#### Description of problem:
`aide_verify_acls`, `aide_verify_ext_attributes` and `aide_use_fips_hashes` bash remediation rules are adding content to incorrect lines in `/etc/aide.conf` since 0.1.52 (Assuming it's something to do with #5941, #5945 and #5972):

#### SCAP Security Guide Version:
0.1.52

#### Operating System Version:
RHEL 7.8
Aide 0.15.1

#### Steps to Reproduce:

1. Ensure the gzip_dbout and verbose config values are set (this may affect other config options too)
2. Run the aide remediations
3. Check the config file, the values should have been incorrectly appended with `+xattrs+acl+sha512`

#### Actual Results:
Diff between /etc/aide.conf from SSG 0.1.51 to 0.1.52:
```
-gzip_dbout=yes
+gzip_dbout = yes+xattrs+acl+sha512

-verbose=5
+verbose = 5+xattrs+acl+sha512
```
`aide -D` (config check)
```
[root@<host> ~]# aide -D
14:syntax error:yes+xattrs+acl+sha512
14:Error while reading configuration:yes+xattrs+acl+sha512
Configuration error
```

#### Expected Results:
Set the values only on the appropriate lines

**Comment by ggbecker** [comment]
That's because the remediation now considers that groups can be written in lowercase as well. Maybe it will be a good a idea to revert this behavior and only accept uppercase groups like:

`GROUP1=xattrs+acl+sha512`

**Comment by gcampbell12** [comment]
You could perhaps get away with it only changing lines starting with an uppercase character, all of AIDE's config options are lowercase, this way it would pick up the `All` group example in the STIG (that many may have copied) https://www.stigviewer.com/stig/red_hat_enterprise_linux_7/2017-07-08/finding/V-72073

**Comment by ggbecker** [comment]
> You could perhaps get away with it only changing lines starting with an uppercase character, all of AIDE's config options are lowercase, this way it would pick up the `All` group example in the STIG (that many may have copied) https://www.stigviewer.com/stig/red_hat_enterprise_linux_7/2017-07-08/finding/V-72073

That might be even better. I'll see what I can do. Thanks for the info.
