### ISSUE TITLE
A lot empty group in ubuntu1604 standard report

### ISSUE THREAD

**Issue by jingnanj** [ComplianceAsCode/content#6171]
#### Description of problem:
I am running Openscap on ubuntu 1604. But there is a lot of empty group in the report.

#### SCAP Security Guide Version:
~/content/build/ssg-ubuntu1604-ds.xml

#### Operating System Version:
Ubuntu 1604 Linux version 4.4.0-186-generic (buildd@lcy01-amd64-002) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) )

#### Steps to Reproduce:

1. cd/content/build
2. cmake ../
3. make -j4
4. oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_standard --report ubuntu16_test1.html ssg-ubuntu1604-ds.xml

#### Actual Results:
![image](https://user-images.githubusercontent.com/52295991/95548193-92773480-09d2-11eb-9772-996acd892b5e.png)

#### Expected Results:
I checked that all empty rule or group didn't select under the standard profile which <selected="false">.
I think those group shouldn't show up in the output report if there is no rule need to scam under those group as other systems.

**Comment by konstruktoid** [comment]
See https://github.com/ComplianceAsCode/content/issues/6112#issuecomment-698012266 as it probably covers this as well.

**Comment by jingnanj** [comment]
Thanks
