### ISSUE TITLE
Missing referenced OVAL

### ISSUE THREAD

**Issue by matejak** [ComplianceAsCode/content#6185]
During the build, following rules are reported as missing target of `extend_definition`. You can get the list by running `./build_product 2>&1 | grep 'extends non-existing'`.

Here is an exhaustive list for all products:

- audit_rules_file_deletion_events_rmdir
- audit_rules_kernel_module_loading_init
- audit_rules_login_events_tallylog
- audit_rules_unsuccessful_file_modification_creat
- enable_dconf_user_profile
- firewalld_sshd_port_enabled
- installed_OS_is_FIPS_certified
- install_mcafee_cma_rt
- ocp_service_runtime_config_streaming_connection_timeout
- package_aide_installed
- package_MFEhiplsm_installed
- package_openssh-server_removed
- package_pam_pkcs11_installed
- service_postfix_enabled
- sysctl_static_net_ipv6_conf_all_disable_ipv6

Concerning RHEL7,8 RHCOS4 and Fedora, there are only two issues:

- [x] package_MFEhiplsm_installed
- [x] package_pam_pkcs11_installed

An OVAL being taken out of the build because the required content is not available is a red flag, and either the referenced content should be made available, or the rule should be removed.

**Comment by vojtapolasek** [comment]
Note that this kind of issue is fixed for rhel7, rhel8 and fedora in current master.

**Comment by matejak** [comment]
A test would be nice. I will think of something.
