### ISSUE TITLE
Rule disable_prelink is selected in RHEL8 profiles

### ISSUE THREAD

**Issue by matusmarhefka** [ComplianceAsCode/content#6187]
#### Description of problem:
Rule `disable_prelink` is selected in RHEL8 profiles even though it is not applicable on RHEL8. The `prelink` package doesn't exist in RHEL8 and it has been replaced with the `execstack` package which is built from prelink sources but contains just the `execstack` binary.

#### SCAP Security Guide Version:
master

#### Operating System Version:
RHEL8

**Comment by redhatrises** [comment]
Is the execstack package going to be in base rhel? So far it is in codeready repos.

**Comment by matusmarhefka** [comment]
@redhatrises I would expect it will remain in codeready repos. AFAIK prelink functionality cannot be configured through `execstack` so I still think the rule `disable_prelink` should be removed from the RHEL8 profiles (as `prelink` is not shipped in RHEL8 you cannot enable it, therefore having a rule to disable it doesn't make sense). I have also checked and `prelink` package is not even in epel repo for RHEL8.

**Comment by redhatrises** [comment]
> @redhatrises I would expect it will remain in codeready repos. AFAIK prelink functionality cannot be configured through `execstack` so I still think the rule `disable_prelink` should be removed from the RHEL8 profiles (as `prelink` is not shipped in RHEL8 you cannot enable it, therefore having a rule to disable it doesn't make sense). I have also checked and `prelink` package is not even in epel repo for RHEL8.

@matusmarhefka agreed. Thanks for the investigation. Glad we no longer have to check prelink.
