### ISSUE TITLE
Add new package remove rule to rhel7

### ISSUE THREAD

**Issue by jingnanj** [ComplianceAsCode/content#6284]
#### Description of problem:
I'm trying to add a new package remove rule to ssg-rhel7-ds.xml

#### SCAP Security Guide Version:
~/content/build/ssg-rhel7-ds.xml

#### Operating System Version:
Red Hat Enterprise Linux Server 7.6 

#### Steps to Reproduce:

1. create folder package_networkmanager_removed under linux_os/services/obsolete
2. write a rule.yml file under that folder like the screenshot below
![image](https://user-images.githubusercontent.com/52295991/96667491-262bf780-1327-11eb-843c-998e56c2bf07.png)
3. add the folder name into rhel7/profiles/standard.profile
4 cd/content/build
5. cmake ../
6. make -j4
7. oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_standard --report newrule_test1.html ssg-rhel7-ds.xml
#### Actual Results:
![image](https://user-images.githubusercontent.com/52295991/96667424-11e7fa80-1327-11eb-807c-0c1aa4cf2caa.png)

#### Expected Results:
the result should be pass, but I don't know why I got not checked. I checked ssg-rhel7-ds.xml, oval file. it's all same as the other package removed rule (I'm using package_pybind_removed as an example). I also checked that rhel7 support Networkmanager and RPM have this package.

**Comment by ggbecker** [comment]
Are you using latest master? There was a limitation in the package removed template before that you had to name your rule with this format: `package_<PKGNAME>_removed` which in your case would mean: `package_NetworkManager_removed` (notice the capital letters)

Try doing that and if it doesn't solve the issue we can investigate more.

**Comment by jingnanj** [comment]
Thanks!
