### ISSUE TITLE
Oval file check issues when I try to build my own rule

### ISSUE THREAD

**Issue by jingnanj** [ComplianceAsCode/content#6294]
#### Description of problem:
I'm trying to add some new rules to check my company servers security by Openscap. I build an oval check file to check my custom rule, but I don't know why it can't match the right place with regular expression.

#### SCAP Security Guide Version:
~/content/build/ssg-rhel7-ds.xml

#### Operating System Version:
Red Hat Enterprise Linux Server 7.6

#### Steps to Reproduce:

1.Create folder high_risk_ports_disable under linux_os/services/test1
2.Write a rule.yml file under that folder like the screenshot below
![image](https://user-images.githubusercontent.com/52295991/96969195-199ecf00-14e0-11eb-8215-d8207e18a503.png)
3.Create folder oval under high_risk_ports_disable folder and write a shared.xml file under it as below
![image](https://user-images.githubusercontent.com/52295991/96970585-ea895d00-14e1-11eb-9182-8b8fb8bc255b.png)
It's an example, so I only wrote one check statement on this oval file.
4. add the folder name into rhel7/profiles/standard.profile
5. cd/content/build
6. cmake ../
7. make -j4
8. oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_standard --report newrule_test1.html ssg-rhel7-ds.xml

#### Actual Results:
![image](https://user-images.githubusercontent.com/52295991/96970850-48b64000-14e2-11eb-9f17-a56ae514fb13.png)
no matter I delete those service in /etc/service file or not. It dont influence the result.
![image](https://user-images.githubusercontent.com/52295991/96971236-d8f48500-14e2-11eb-999d-237819d7c4a9.png)

#### Expected Results:
In my opinion, the oval check file should go to the file path I set which is /etc/services (<ind:filepath>/etc/services</ind:filepath>) then use regular expression (<ind:pattern operation="pattern match">^ftp\s+21$</ind:pattern>) to check if there is any result coming out. if there is no result come out, check result should be pass as <check_existence="none_exists">. if there is any result come out, result should be fail.

I want to get some help to fix this problem and understand how is oval file work.  I think the reason made it happened should be the oval file use a different way or statement to match it with regular expression.

**Comment by jingnanj** [comment]
Is there any way to let pattern match support numbers?. I changed 21 to .* and it's work perfectly. But as you know it will match a lot of other port and service

**Comment by ggbecker** [comment]
The problem is in your regex: `^ftp\s+21$`. The dollar `$` sign is telling to the regex processor to find the end of the line, this way it would only match a line as such:

`ftp 21`

If you have any other content after `21` it will not match. Which in this case all occurrences have at least either `/tcp` or `/udp`.

You need then to increment your regex with something like:

`^ftp\s+21.*$` or something more specific, ``^ftp\s+21\/(tcp|udp).*$`

I highly recommend using [regex101.com](https://www.regex101.com) to test regexes, it's really helpful.

**Comment by ggbecker** [comment]
Next time, please post the content in text format please, images are nice but they require us to copy by hand and it's painful.

You can enclosure the content with triple ` and it should be nicely rendered, for example:

```
text surrounded by triple `
```

**Comment by jingnanj** [comment]
Thanks
