### ISSUE TITLE
Various ansible variables contain disallowed characters

### ISSUE THREAD

**Issue by justchris1** [ComplianceAsCode/content#6311]
#### Description of problem:
Attempting to skip jobs 'dnf-automatic_security_updates_only' by setting that variable to false did not work.  This is because the variable name 'dnf-automatic_security_updates_only' is not legal in ansible due to the hypen '-' character.  Changing it to an underscore fixed the issue.  Additional searches revealed the following variables that have the same issue:
* dnf-automatic_security_updates_only
* package_dnf-automatic_installed
* timer_dnf-automatic_enabled

#### SCAP Security Guide Version:
0.1.52

#### Operating System Version:
Centos 8

#### Steps to Reproduce:

1.  Download the redhatofficial.rhel8_cui role on a Centos 8 machine.
2.  Write a playbook to use that role, running in check mode, try setting any of the above to false will not cause the tasks to be skipped.
3.
4.

#### Actual Results:
The tasks are not skipped, even when set to false.

#### Expected Results:
The tasks are skipped when set to false.

**Comment by ggbecker** [comment]
This should be fixed by this pull request and you can find in the latest galaxy ansible roles already: https://github.com/ComplianceAsCode/content/pull/9240
