### ISSUE TITLE
Ansible fix of rule accounts_root_path_dirs_no_write fails (RHEL7, Fedora)

### ISSUE THREAD

**Issue by matusmarhefka** [ComplianceAsCode/content#6328]
#### Description of problem:
Ansible fix of the rule `accounts_root_path_dirs_no_write` fails with the following error:
```
...

TASK [Get root paths which are not symbolic links] *****************************
fatal: [192.168.122.167]: FAILED! => {"msg": "The conditional check 'ansible_user == \"root\"' failed. The error was: error while evaluating conditional (ansible_user == \"root\"): 'ansible_user' is undefined\n\nThe error appears to be in '/usr/share/scap-security-guide/ansible/rhel7-playbook-standard.yml': line 96, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Get root paths which are not symbolic links\n      ^ here\n"}
```
Found on RHEL7 using `rhel7-playbook-standard.yml` with `ansible-2.9.14-1.el7ae`.

#### SCAP Security Guide Version:
master

#### Operating System Version:
RHEL7
Fedora

#### Steps to Reproduce:
`ansible-playbook rhel7-playbook-standard.yml`

**Comment by vojtapolasek** [comment]
I did not manage to reproduce this. Let's wait for the next productization.

**Comment by vojtapolasek** [comment]
The issue no longer appears. Closing.
