### ISSUE TITLE
Add new profile to Centos7

### ISSUE THREAD

**Issue by jingnanj** [ComplianceAsCode/content#6337]
#### Description of problem:
I'm trying to add a new profile to the centos7. But I can't find any folder or script that I can add to the centos7.

#### SCAP Security Guide Version:
ssg-centos7-ds.xml 

#### Operating System Version:
Centos7/Redhat7.6

#### Steps to Reproduce:

1. cmake ../
2. make -j4 
3. make -j4 centos7 VERBOSE=1 > cetnos7makefile.txt
4. check all .py file and makefile

#### Actual Results:
There should have a place or way to build a profile for centos7. But I can't find it 
run oscap info ssg-centos7-ds.xml

Stream: scap_org.open-scap_datastream_from_xccdf_ssg-rhel7-xccdf-1.2.xml
Generated: (null)
Version: 1.3
Checklists:
	Ref-Id: scap_org.open-scap_cref_ssg-rhel7-xccdf-1.2.xml
WARNING: Datastream component 'scap_org.open-scap_cref_security-data-oval-com.redhat.rhsa-RHEL7.xml' points out to the remote 'https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml'. Use '--fetch-remote-resources' option to download it.
WARNING: Skipping 'https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml' file which is referenced from datastream
		Status: draft
		Generated: 2020-11-04
		Resolved: true
		Profiles:
			Title: Standard System Security Profile for Red Hat Enterprise Linux 7
				Id: xccdf_org.ssgproject.content_profile_standard
			Title: PCI-DSS v3.2.1 Control Baseline for Red Hat Enterprise Linux 7
				Id: xccdf_org.ssgproject.content_profile_pci-dss
		Referenced check files:
			ssg-rhel7-oval.xml
				system: http://oval.mitre.org/XMLSchema/oval-definitions-5
			ssg-rhel7-ocil.xml
				system: http://scap.nist.gov/schema/ocil/2
			security-data-oval-com.redhat.rhsa-RHEL7.xml
				system: http://oval.mitre.org/XMLSchema/oval-definitions-5
	Ref-Id: scap_org.open-scap_cref_ssg-rhel7-pcidss-xccdf-1.2.xml
#### Expected Results:
oscap info ssg-centos7-ds.xml should include my custom profile in it

	Ref-Id: scap_org.open-scap_cref_ssg-rhel7-xccdf-1.2.xml
WARNING: Datastream component 'scap_org.open-scap_cref_security-data-oval-com.redhat.rhsa-RHEL7.xml' points out to the remote 'https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml'. Use '--fetch-remote-resources' option to download it.
WARNING: Skipping 'https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml' file which is referenced from datastream
		Status: draft
		Generated: 2020-11-04
		Resolved: true
		Profiles:
			Title: Standard System Security Profile for Red Hat Enterprise Linux 7
				Id: xccdf_org.ssgproject.content_profile_standard
			Title: PCI-DSS v3.2.1 Control Baseline for Red Hat Enterprise Linux 7
				Id: xccdf_org.ssgproject.content_profile_pci-dss
                        Title: test Profile for Red Hat Enterprise Linux 7
				Id: xccdf_org.ssgproject.content_profile_test

**Comment by ggbecker** [comment]
Notice that centos7 is a derivative of rhel7, that means you need to put the new profile under `rhel7/profiles` directory, then you can run `./build_product rhel7 --derivatives`.

But first you need to take a look at these two places:
https://github.com/ComplianceAsCode/content/blob/master/ssg/xccdf.py#L16 (make sure your profile doesn't match those identifiers)
and
https://github.com/ComplianceAsCode/content/blob/master/ssg/constants.py#L82 (include your new profile there)

Closing this issue as I tested here and a new profile has been added to the datastream. If you feel that the information is not enough. Feel free to reopen.
