### ISSUE TITLE
Centos 8.2: hundreds of false positives for "Ensure Software Patches Installed"

### ISSUE THREAD

**Issue by markmal** [ComplianceAsCode/content#6371]
#### Description of problem:
oscap generates hundreds of false positives for "Ensure Software Patches Installed" OVAL rules, i.e. oval:com.redhat.rhba:tst:20193384074
oval:com.redhat.rhsa:tst:20204952002
etc
Even for packages that are not installed, like freetype-debugsource OSCAP reports False tor rule oval:com.redhat.rhsa:tst:20204952003 

#### SCAP Security Guide Version:
This is what is installed:
openscap-1.3.4-1.el8.x86_64
openscap-utils-1.3.4-1.el8.x86_64
openscap-devel-1.3.4-1.el8.x86_64
openscap-containers-1.3.4-1.el8.noarch
openscap-engine-sce-1.3.4-1.el8.x86_64
openscap-scanner-1.3.4-1.el8.x86_64

#### Operating System Version:
CentOS Linux release 8.2.2004 (Core)

#### Steps to Reproduce:

/bin/oscap xccdf eval --profile standard --oval-results --report /var/www/html/oscap/oscap-sce1.html --results /var/oscap/results/res-sce1.xml --fetch-remote-resources /usr/share/xml/scap/ssg/content/ssg-centos8-ds.xml

#### Actual Results:
Hundreds of false positive violations

#### Expected Results:
There are should not be that many because OS is up-to-date.

**Comment by konstruktoid** [comment]
Hi @markmal, this seems to be a duplicate of https://github.com/ComplianceAsCode/content/issues/5037

**Comment by markmal** [comment]
Hi konstruktoid,
Yes I see it is an old issue.

>  redhatrises commented on Dec 4, 2019
For the very simple reason that Red Hat Security OVAL feeds do not apply to CentOS and using them when CentOS doesn't guarantee security fixes is a huge security vulnerability. Closing this as there is an issue to fix for OpenSCAP where the discussion can continue.

RH OVAL feed still can be used for reporting (just by comparing versions of packages). I do not understand why this issue should be closed.
Currently oscap uses ssg-rhel?-oval.xml for Centos.
Probably a separate oval.xml should be created for Centos specifically, like for other systems?

**Comment by redhatrises** [comment]
The issue is that you are using rhel CVE oval for CentOS. This is unsupported, and the results are correct. CentOS != RHEL and the oval feeds will not and do not support CentOS as it is a different OS. Comparing versions do nothing in terms of verifying and validating that OVAL CVE feeds pass.

**Comment by redhatrises** [comment]
Just so everyone is clear. This repo does not create or support the OVAL CVE feeds themselves so asking and creating issues on these topics go nowhere as they cannot be addressed.
