### ISSUE TITLE
[RFE] Add option to check stricter file permissions on file_permissions template

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#6431]
Currently the file_permissions template only support checking a for specific file permissions value. It's not possible to check for stricter permissions, which in some cases is what security requirements look for:

- The OVAL template
  - https://github.com/ComplianceAsCode/content/blob/739c3635406e983d48dfe0e6d5dac8c634180151/shared/templates/file_permissions/oval.template#L22
- The input data processing
  - https://github.com/ComplianceAsCode/content/blob/739c3635406e983d48dfe0e6d5dac8c634180151/shared/templates/file_permissions/template.py#L12

#### Example on how to check for stricter permissions:
https://github.com/ComplianceAsCode/content/blob/739c3635406e983d48dfe0e6d5dac8c634180151/linux_os/guide/system/auditing/auditd_configure_rules/file_permissions_var_log_audit/oval/shared.xml#L36

Notice the `negate=true` which should do the trick to check for stricter permissions, it checks if there is any occurrence that would violate the permission. In case it's a stricter permission, it won't match any of those permission bits and the check pass if it's stricter.

**Comment by yuumasato** [comment]
If I try to rephrase it.
State`state_not_mode_0600` defines a mask that only allows more restrictive permissions.
