### ISSUE TITLE
Need help/guidance on "drop-in" config file support

### ISSUE THREAD

**Issue by Caligatio** [ComplianceAsCode/content#6439]
A number of services are adding support for "drop-in" config files so that users don't have to modify package manager-controlled config files.  I personally think is this great but it poses problems for this project as now settings can be in different files depending on distro/service version/config contents.

I ran into this issue trying to implement #5220 (but for Ubuntu) as `sudo` supports `/etc/sudoers.d`.  Going further down the rabbit hole I also noticed that the various `ssh` rules don't have support for the new `/etc/ssh/sshd_config.d` option either (this was added in OpenSSH v8.2 which is in Ubuntu 20.04 and Fedora).

I grep'ed through existing templates to see if any other rules support drop-in files to see if there was a best-practice for implementing this sort of functionality.  I found that the templates `kernel_module_disabled` and `sysctl` support drop-ins but they diverge on how the remediations work.  In the case of `kernel_module_disabled`, it both reads and writes to drop-in file locations (e.g. `/etc/modprobe.d/{{{ KERNMODULE }}}.conf`).  On the other hand, `sysctl` reads from drop-in files but only writes to the static config file location.

I'm looking for help/ideas/guidance on how to proceed here (I'm willing to try to implement whatever is decided on).  I think the options are:

- Ignore that drop-in config files exist
  - Pros: Easy
  - Cons: Remediations may not ultimately work as drop-in configs usually overwrite static configs
- Create service-specific OVALs and remediations
  - Pros: Supports drop-ins
  - Cons: Increased upkeep as more services adopt drop-in configs, need to account for drop-in support and whether such support is enabled in the config (e.g. `Include /etc/ssh/sshd_config.d/*.conf` needs to be in `/etc/ssh/sshd_config`).
  - Misc: Do we assume there's support if the distro matches? Test against software/service version? Check to make sure the "include" directive is in the config?  Where do remediations go?
- Try to create an uber-macro akin to `shell_lineinfile`
  - Pros: Trades per-service upkeep for what will inevitably be a complicated macro
  - Cons: Will never be smart enough to detect whether drop-ins are actually supported.

I'm thinking service-specific OVALs and remediations are the way to go but I really want some guidance before implementing.

**Comment by yuumasato** [comment]
Hi there,

I lean towards service-specific OVALs and remediations. One macro to handle it all could get very complex, as each service may have its own caveats.

- Support and inclusion of drop-in configuration:
I guess looking at the service version would be enough to check whether drop-in configs are supported. Unless for some reason a distro would ship/compile it disabled.
Another aspect to consider is whether the the drop-in configs by default, either by include statement or automagically.

- Override and ordering
I think in general, the drop-in configs override the static config. But if a service uses an `Include` statement, anything configured after it may actually override the drop-in config. I guess this doesn't happen often by default, but misconfigured files won't be caught if the OVAL check is not smart.
The OVAL would have to check if a non-compliant config is set after an `Include`, or if it is set before, ignore it when a drop-in config overrides it. The easiest approach is to just check that the static config doesn't contain the non-compliant config, but that leads me to the remediation aspect.

- Remediation
I think in general, writing the configs to drop-in configs is easier and cleaner.
But if the non-compliant config is set by default in the static config file, the remediation may need to edit it, depending on whether the OVAL knows it is overriding a drop-in config or not.

**Comment by marcusburghardt** [comment]
According to the issue mentioned in the description, I assume you are targeting the `sudo_add_use_pty` rule, which uses the `sudo_defaults_option` template. It would be nice to enable support for drop-in files in this template to. You can use the `sshd_lineinfile` template as inspiration.

**Comment by Mab879** [comment]
It appers based on the code below that this template supports drop in files:

https://github.com/ComplianceAsCode/content/blob/cf82959e3b2a704556427be44b511f82a56e1912/shared/templates/sudo_defaults_option/oval.template#L15
