### ISSUE TITLE
ACSC in description link broken

### ISSUE THREAD

**Issue by Victoremepunto** [ComplianceAsCode/content#6470]
#### Description of problem:
The one link in the Australian Cyber Security Centre (ACSC) Essential Eight profile description for RHEL7 is broken, it points to an apparently non-existent page, the link in question is [here](https://github.com/ComplianceAsCode/content/blob/master/rhel7/profiles/e8.profile#L18).

#### SCAP Security Guide Version:
latest as of today (1.53)

#### Operating System Version:
RHEL 7

#### Steps to Reproduce:

1. Visit the link from the Australian eight profile description

#### Actual Results:
The page does not exist (user gets a 404 error page)

#### Expected Results:
An existing page for further reference about the aforementioned profile. 

As this [Bugzilla suggests](https://bugzilla.redhat.com/show_bug.cgi?id=1906672) , it could be updated to the one from RHEL8, which seems right: https://www.cyber.gov.au/acsc/view-all-content/publications/hardening-linux-workstations-and-servers

it can be found [here](https://github.com/ComplianceAsCode/content/blob/master/rhel8/profiles/e8.profile#L18) in the codebase

**Comment by carlosmmatos** [comment]
I'll take a look - seems like we just need to use the link you provided in the expected results as I don't believe it's meant to be OS version specific.
