### ISSUE TITLE
Need new profile RHEL7 STIG +ANSSI

### ISSUE THREAD

**Issue by bennarim** [ComplianceAsCode/content#6486]
Hello
In order to harden our systems we selected many rules from STIG and ANSSI. 

My request is how to add a new profile that can contains all these rules and be able to get the ansible playbook for remediation and also the reporting. 

OS: RHEL7. 

THANKS

**Comment by carlosmmatos** [comment]
If you want to create your own custom profile - you can check out our [developer docs](https://complianceascode.readthedocs.io/en/latest/index.html) for helping you get started in setting up your system, and then creating/building your new profile.

Once you have your system setup and ready to build, the steps to making your own custom profile would be something like this:

- Create a new file in `rhel7/profiles` - ie custom.profile
- Modify the profile accordingly to your needs (use [this as reference](https://complianceascode.readthedocs.io/en/latest/manual/developer/03_creating_content.html#profiles))
- After you have selected your controls, then you need to build it.
`./build_projects rhel7`

Now in your build directory - you will find the necessary artifacts (ansible, bash, xccdf, HTML guide, etc).

**Comment by bennarim** [comment]
Hello,

Yes i did that in the few last days and it worked

**Comment by bennarim** [comment]
Fixed
