### ISSUE TITLE
Remove "upstart" legacy code

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#6503]
#### Description of problem:
Since the removal of RHEL6, which was the only product that still used "upstart", all code related to these differences can be removed safely. For example: https://github.com/ComplianceAsCode/content/blob/master/shared/macros-highlevel.jinja#L100

**Comment by FlorianHeigl** [comment]
Not sure if it is irrelevant for some reason - but Ubuntu 16 supports upstart & is still in support till 2024?

**Comment by cipherboy** [comment]
@ggbecker I'll leave it up to you if you want to remove 16.04 upstream. But as @FlorianHeigl points out, it will probably see use into ESM, which ends [in 2024](https://ubuntu.com/about/release-cycle).

**Comment by ggbecker** [comment]
I'm not talking about removing the Ubuntu 16.04 product. I'm talking about removing the code that handles `upstart` init system.

Despite Ubuntu 16.04 supports upstart, it already uses `init_system: systemd` in this project:

https://github.com/ComplianceAsCode/content/blob/49aa6118c766c7bc293c9e0c27eba45da55df626/ubuntu1604/product.yml#L11

So the question here is whether to remove this code that no product is using or keep it because someone else is using it with an in-house customized product.

**Comment by cipherboy** [comment]
@ggbecker Yeah it should be safe to remove; there is one reference to the older upstart system in the 16.04 CIS benchmark I believe (for ntp of all things) but the rest of the directions are for systemd so not sure what's up with that... :)

**Comment by marcusburghardt** [comment]
Concluded by #9452
