### ISSUE TITLE
Documentation on how to create new product is outdated with regards to new automated CPE mechanism

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#6518]
#### Description of problem:

Currently, CPE dictionaries are generated dynamically based on Yaml files and that should be reflected in the documentation on how to create new products in the project.

https://github.com/ComplianceAsCode/content/pull/6304

https://github.com/ComplianceAsCode/content/blob/master/example/README.md

**Comment by marcusburghardt** [comment]
@ggbecker is the current documentation enough?
https://complianceascode.readthedocs.io/en/latest/manual/developer/06_contributing_with_content.html#applicability-by-cpe

**Comment by ggbecker** [comment]
I believe so. Thanks.
