### ISSUE TITLE
CentOS files are missing when installed via yum

### ISSUE THREAD

**Issue by Skyler-Arnold** [ComplianceAsCode/content#6550]
#### Description of problem:
After installing `scap-security-guide` via yum in centOS 7, the `ssg-centos*.xml` files are missing in `/usr/share/xml/scap/ssg/content`. This seem like the intended behavior because these files are present when I download [the zip file for this release.](https://github.com/ComplianceAsCode/content/releases/tag/v0.1.52)

I notice that the ["CentOS CI Build" CI pipeline](https://ci.centos.org/job/openscap-scap-security-guide/) linked at the top of the main README is failing. I am not very familiar with this repo so that could be totally normal, but it seems kinda suspicious to me.

#### SCAP Security Guide Version:
0.1.52

Here's the package info:
```$ yum info scap-security-guide
Name        : scap-security-guide
Arch        : noarch
Version     : 0.1.52
Release     : 2.el7.centos
Size        : 225 M
Repo        : installed
From repo   : updates
Summary     : Security guidance and baselines in SCAP formats
URL         : https://github.com/ComplianceAsCode/content
License     : BSD-3-Clause
```

#### Operating System Version:
CentOS 7

#### Steps to Reproduce:

1. `yum update -y && yum install -y scap-security-guide`
2. `ls /usr/share/xml/scap/ssg/content`

#### Actual Results:
```
$ ls /usr/share/xml/scap/ssg/content/
ssg-firefox-cpe-dictionary.xml  ssg-firefox-xccdf.xml       ssg-jre-oval.xml              ssg-rhel6-ocil.xml            ssg-rhel7-ds.xml              ssg-rhel8-ds-1.2.xml
ssg-firefox-cpe-oval.xml        ssg-jre-cpe-dictionary.xml  ssg-jre-xccdf.xml             ssg-rhel6-oval.xml            ssg-rhel7-ocil.xml            ssg-rhel8-ds.xml
ssg-firefox-ds-1.2.xml          ssg-jre-cpe-oval.xml        ssg-rhel6-cpe-dictionary.xml  ssg-rhel6-xccdf.xml           ssg-rhel7-oval.xml            ssg-rhel8-ocil.xml
ssg-firefox-ds.xml              ssg-jre-ds-1.2.xml          ssg-rhel6-cpe-oval.xml        ssg-rhel7-cpe-dictionary.xml  ssg-rhel7-xccdf.xml           ssg-rhel8-oval.xml
ssg-firefox-ocil.xml            ssg-jre-ds.xml              ssg-rhel6-ds-1.2.xml          ssg-rhel7-cpe-oval.xml        ssg-rhel8-cpe-dictionary.xml  ssg-rhel8-xccdf.xml
ssg-firefox-oval.xml            ssg-jre-ocil.xml            ssg-rhel6-ds.xml              ssg-rhel7-ds-1.2.xml          ssg-rhel8-cpe-oval.xml
```

#### Expected Results:
`ssg-centos7-*.xml` files should show up

**Comment by yuumasato** [comment]
This should be fixed on the CentOS specfile. There is a PR to fix it: https://git.centos.org/rpms/scap-security-guide/pull-request/1

**Comment by ggbecker** [comment]
> This should be fixed on the CentOS specfile. There is a PR to fix it: https://git.centos.org/rpms/scap-security-guide/pull-request/1

This pull request is for CentOS 8, but nobody ever responded to that. There is even a bug: https://bugs.centos.org/view.php?id=17646

But the solution is the same, the derivative should be enable back for both cases.

**Comment by Skyler-Arnold** [comment]
Here's an identical PR for C7: https://git.centos.org/rpms/scap-security-guide/pull-request/2#

Could someone please review and merge these PR's?

**Comment by reenberg** [comment]
I have taken the time to fill out a BugZilla, as this also applies to CentOS Stream. 
Gonna be interesting to see how much Stream actually benefits of being made upstream to RHEL, or if this is going to be ignored just as much as the CentOS bug tracker. 

https://bugzilla.redhat.com/show_bug.cgi?id=1919583

**Comment by alex222efx** [comment]
Hi Guys,

I have the same issue with the missing ssg-centos7-ds file in /usr/share/xml/scap/ssg/content

Could you please let me know how to fix this? (SSG_CENTOS_DERIVATIVES_ENABLED to ON)
I can't understand if this should be modified on some file on the server or it's something that I can not fix locally.

Thank you,
Alex,

**Comment by ggbecker** [comment]
I know for a fact that Centos content is there now since we have updated the spec file to handle nicely the centos content and new Centos Stream 9 has also content enabled. I believe that's more than enough to close this issue. If you think otherwise than you can reopen the issue.
