### ISSUE TITLE
Test scenarios for rule sshd_allow_only_protocol2 that downgrade packages should be removed

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#6551]
#### Description of problem:
Test scenarios for rule [sshd_allow_only_protocol2](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/services/ssh/ssh_server/sshd_allow_only_protocol2/rule.yml) that downgrade packages should be removed. These test scenarios are not valid anymore.

On a RHEL7.9 machine, the command:

`yum downgrade -y openssh-6.6.1p1 openssh-clients-6.6.1p1 openssh-server-6.6.1p1`

returns:
```
No package openssh-6.6.1p1 available.
No package openssh-clients-6.6.1p1 available.
No package openssh-server-6.6.1p1 available.
```
So, the downgrade test scenario should probably go away.

#### SCAP Security Guide Version:
3ac4117621cf543fed31d924dada616880adea4d

**Comment by Mab879** [comment]
Test now appears to be gone.
