### ISSUE TITLE
issue with fix script in SGG for Centos

### ISSUE THREAD

**Issue by prmarino1k** [ComplianceAsCode/content#6560]
#### Description of problem:
I've found an illegal shell variable used in a fix script in a few SGG xml files on my system and it may exist in more.
i first found it in /usr/share/xml/scap/ssg/content/ssg-amzn2-ds.xml which I know you don't handle but then found it in the upstream file /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
the issue is the "$PATH" variable is used in a shell script snippet. this causes other scripts that use the which command that run after it for fail when you use OpenSCAP to generate a bash fix script.
starting on line 79202 here is the snippet that causes the issue
"
for PATH in "${LOG_FILE_PATHS[@]}"
do
        # Sanity check - if particular $PATH is empty string, skip it from further processing
        if [ -z "$PATH" ]
        then
                continue
        fi

        # Also for each log file check if its permissions differ from 600. If so, correct them
        if [ "$(/usr/bin/stat -c %a "$PATH")" -ne 600 ]
        then
                /bin/chmod 600 "$PATH"
        fi
done
"
this is  a sample of the error it causes

Remediating rule 64/212: 'xccdf_org.ssgproject.content_rule_package_rsyslog_installed'
which: no dnf in ()
which: no yum in ()
which: no apt-get in ()
Failed to detect available packaging system, tried dnf, yum and apt-get!
Aborting.

#### SCAP Security Guide Version:
according to the RPM scap-security-guide-0.1.40-12

#### Operating System Version:
Amazon Linux 2 and CentOS7 and possibly more

#### Steps to Reproduce:
on CentOS 7
1.  sudo  oscap xccdf generate fix --fix-type bash --profile C2S --output remdiations.sh  /usr/share/xml/scap/ssg/content/ssg-centos7-ds.xml
2. sudo ./remdiations.sh

#### Actual Results:
"
Remediating rule 64/212: 'xccdf_org.ssgproject.content_rule_package_rsyslog_installed'
which: no dnf in ()
which: no yum in ()
which: no apt-get in ()
Failed to detect available packaging system, tried dnf, yum and apt-get!
Aborting.
"

#### Expected Results:

Remediating rule 64/212: 'xccdf_org.ssgproject.content_rule_package_rsyslog_installed'
which: no dnf in (/sbin:/bin:/usr/sbin:/usr/bin)
/bin/yum
Remediating rule 65/212: 'xccdf_org.ssgproject.content_rule_sysctl_net_ipv6_conf_all_accept_redirects'

**Comment by jan-cerny** [comment]
This has been fixed by https://github.com/ComplianceAsCode/content/commit/08c0dc99adb608f6e7b741066f35250931b1e11f.
