### ISSUE TITLE
The auditd checks should process the actively running rules

### ISSUE THREAD

**Issue by trevor-vaughan** [ComplianceAsCode/content#6597]
#### Description of problem:

The default configuration of `auditd` will cause rules to not be loaded after the first failing rule. This means that, while the checks may pass, the actual rules loaded at runtime may be completely blank.

#### SCAP Security Guide Version:

All

#### Operating System Version:

Any

**Comment by yuumasato** [comment]
Checking the runtime environment with OVAL can be tricky, we can't just run the `auditctl -l` command.
Do you have ideas how this could be done?

**Comment by yuumasato** [comment]
Well, the answer is in the future with `auditdline_test`:
https://github.com/OVAL-Community/OVAL/pull/112

**Comment by gdidot** [comment]
The proposal is now present at  [OVAL-Community/OVAL#114](https://github.com/OVAL-Community/OVAL/issues/114)

**Comment by Mab879** [comment]
Until the above OVAL issue is closed we will close this issue.

No comment on the OVAL issue since 2021. :(
