### ISSUE TITLE
complianceascode.io renewal

### ISSUE THREAD

**Issue by shawndwells** [ComplianceAsCode/content#6610]
@matejak @dahaic just received the domain renewal notice for complianceascode.io. Is the project still using that domain? If so, is there someone I could transfer it to?

**Comment by dahaic** [comment]
Ahoj @shawndwells yes, we are using the domain and would like to use it more. It can be transferred to me. What information do you need for it?

**Comment by shawndwells** [comment]
Looks like we actually registered a few domains! 

![image](https://user-images.githubusercontent.com/5713754/108143974-b50f0d80-7096-11eb-85ba-248e1a2b2479.png)

If you have a gmail, I can add you to the domain admin list & you can transfer wherever you want.

**Comment by dahaic** [comment]
Yup, OK. My gmail is the same as my handle here - dahaic :)

**Comment by shawndwells** [comment]
Forgot I had the ticket muted. Added @dahaic into the domain access list so you can update billing information into your own name.

Note some of the domains expire this week. You'll want to have your credit card info put into the system today/tomorrow.

**Comment by dahaic** [comment]
Ok, I see it there, and I see the expiration date. Thanks! Will take care of that :)

**Comment by shawndwells** [comment]
Just got a notification the domains were not renewed. Went ahead and deleted them. You'll be able to re-register them (if desired) once all the registrars are updated.

**Comment by shawndwells** [comment]
![image](https://user-images.githubusercontent.com/5713754/114479557-c07e4100-9bce-11eb-8f43-a3d1fe9e13f8.png)

**Comment by dahaic** [comment]
Hello @shawndwells , sorry. I should have probably remove you as a manager, so the notification did not bother you. I have renewed `complianceascode.io` right at the moment you gave me access a month ago. It was renewed till March 2022. The rest I was kinda OK with expiring, but IMHO they still had one month to go. So here we go now, another 60 bucks down the drain I guess.

**Comment by dahaic** [comment]
FYI, I have set the `complianceascode.io` to get restored. It's still "in progress" Not sure how long will it take.
