### ISSUE TITLE
configure_opensc_nss_db rule errors after remediation

### ISSUE THREAD

**Issue by matusmarhefka** [ComplianceAsCode/content#6630]
#### Description of problem:
The rule `configure_opensc_nss_db` errors after remediation. Looks like the bash remediation script needs to be improved to first check if the `/usr/bin/pkcs11-switch` exists on the system:
```
line 6: [: !=: unary operator expected

Failed to verify applied fix: Checking engine returns: fail
```

#### SCAP Security Guide Version:
master

#### Operating System Version:
RHEL7

#### Steps to Reproduce:
`oscap xccdf eval --remediate --profile ncp --rule xccdf_org.ssgproject.content_rule_configure_opensc_nss_db ssg-rhel7-ds.xml`

#### Actual Results:
rule errors

#### Expected Results:
rule is fixed

#### Additional Information/Debugging Steps:
When looking into this issue it might be good to also look at https://github.com/ComplianceAsCode/content/issues/5778

**Comment by mildas** [comment]
I haven't seen this issue in latest test run. Closing
