### ISSUE TITLE
Microsoft Windows

### ISSUE THREAD

**Issue by dkp-01** [ComplianceAsCode/content#6657]
Will support for Microsoft Windows (workstation & server) be added at some point ?

**Comment by ggbecker** [comment]
Most likely not. The main active contributors of this repository are focused on Unix/Linux only.

I think a good start for Windows SCAP content can be the National Checklist Program by NIST: https://nvd.nist.gov/ncp/repository?keyword=Microsoft+Windows&startIndex=0

There you can find some content, but to be honest I don't know the details of it.

If you believe your question was not answered I recommend starting a topic on the discussions page: https://github.com/ComplianceAsCode/content/discussions

**Comment by jan-cerny** [comment]
@dkp-01 I would like to add that even if we won't work on Windows support, we are happy to accept pull requests that add Windows support.

**Comment by dkp-01** [comment]
Thank you @ggbecker, have been using National Checklist Program by NIST but was hoping for all major Operating systems to be included in one repo
