### ISSUE TITLE
Build fail if there is 0 rule with OCIL check

### ISSUE THREAD

**Issue by mgjadoul** [ComplianceAsCode/content#6664]
#### Description of problem:
After adding a new benchmark + product,

The build fail due to the lack of OCIL check: 

#### SCAP Security Guide Version:
0.1.55

#### Operating System Version:
fedora

#### Steps to Reproduce:

1.Create a benchmark with only 1 oval check
2.Create a product using this benchmark
3.build

#### Actual Results:
[  0%] Built target generate-internal-bash-remediation-functions.xml
[  0%] [dummyrhel8-content] compiling profiles
[  0%] [dummyrhel8-content] generating shorthand.xml
[  0%] Built target generate-internal-dummyrhel8-shorthand.xml
[  0%] [dummyrhel8-content] generating templated content
[  0%] Built target generate-internal-templated-content-dummyrhel8
[  0%] [dummyrhel8-content] collecting all kubernetes fixes
[  0%] Built target generate-internal-dummyrhel8-kubernetes-all-fixes
[  0%] [dummyrhel8-content] generating kubernetes-fixes.xml
[  0%] Built target generate-internal-dummyrhel8-kubernetes-fixes.xml
[  0%] [dummyrhel8-content] generating oval-unlinked.xml
[  0%] Built target generate-internal-dummyrhel8-oval-unlinked.xml
[  0%] [dummyrhel8-content] generating xccdf-unlinked-resolved.xml
[  0%] Built target generate-internal-dummyrhel8-xccdf-unlinked-resolved.xml
[  0%] [dummyrhel8-content] generating ocil-unlinked.xml
[  3%] Built target generate-internal-dummyrhel8-ocil-unlinked.xml
[  3%] [dummyrhel8-content] collecting all puppet fixes
[  3%] Built target generate-internal-dummyrhel8-puppet-all-fixes
[  3%] [dummyrhel8-content] generating puppet-fixes.xml
[  3%] Built target generate-internal-dummyrhel8-puppet-fixes.xml
[  3%] [dummyrhel8-content] generating xccdf-unlinked-ocilrefs.xml
[  7%] Built target generate-internal-dummyrhel8-xccdf-unlinked-ocilrefs.xml
[  7%] [dummyrhel8-content] collecting all bash fixes
[  7%] Built target generate-internal-dummyrhel8-bash-all-fixes
[  7%] [dummyrhel8-content] generating bash-fixes.xml
[  7%] Built target generate-internal-dummyrhel8-bash-fixes.xml
[ 11%] [dummyrhel8-content] collecting all ansible fixes
[ 11%] Built target generate-internal-dummyrhel8-ansible-all-fixes
[ 11%] [dummyrhel8-content] collecting all ignition fixes
[ 11%] Built target generate-internal-dummyrhel8-ignition-all-fixes
[ 11%] [dummyrhel8-content] generating ignition-fixes.xml
[ 11%] Built target generate-internal-dummyrhel8-ignition-fixes.xml
[ 11%] [dummyrhel8-content] generating ansible-fixes.xml
[ 11%] Built target generate-internal-dummyrhel8-ansible-fixes.xml
[ 11%] [dummyrhel8-content] collecting all anaconda fixes
[ 11%] Built target generate-internal-dummyrhel8-anaconda-all-fixes
[ 11%] [dummyrhel8-content] generating anaconda-fixes.xml
[ 11%] Built target generate-internal-dummyrhel8-anaconda-fixes.xml
[ 15%] [dummyrhel8-content] generating xccdf-unlinked.xml
[ 19%] Built target generate-internal-dummyrhel8-xccdf-unlinked.xml
[ 23%] [dummyrhel8-content] linking IDs, generating xccdf-linked.xml, oval-linked.xml, ocil-linked.xml
oval-unlinked.xml
None
Traceback (most recent call last):
  File "/home/myuser/GIT/dummy_content/build-scripts/relabel_ids.py", line 65, in <module>
    main()
  File "/home/myuser/GIT/dummy_content/build-scripts/relabel_ids.py", line 54, in main
    checks)
  File "/home/myuser/GIT/dummy_content/ssg/build_renumber.py", line 33, in __init__
    self.linked_fname = self.fname.replace("unlinked", "linked")
AttributeError: 'NoneType' object has no attribute 'replace'
make[3]: *** [dummyrhel8/CMakeFiles/generate-internal-dummyrhel8-linked-xccdf-oval-ocil.xml.dir/build.make:86: dummyrhel8/xccdf-linked.xml] Error 1
make[2]: *** [CMakeFiles/Makefile2:3464: dummyrhel8/CMakeFiles/generate-internal-dummyrhel8-linked-xccdf-oval-ocil.xml.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:3676: dummyrhel8/CMakeFiles/dummyrhel8.dir/rule] Error 2
make: *** [Makefile:1427: dummyrhel8] Error 2

#### Expected Results:
I expected to be able to build without adding OCIL check.

#### Additional Information/Debugging Steps:

It fait because there is no check of type OCIL in  FileLinker class initialisation:
   def __init__(self, translator, xccdftree, checks):
        self.translator = translator
        self.checks_related_to_us = self._get_related_checks(checks)
        self.fname = self._get_input_fname()
        self.tree = None
        self.linked_fname = self.fname.replace("unlinked", "linked")
        self.xccdftree = xccdftree

self.fname is initializes from the type of OCIL checks. There is no OCILcheck thus self.fname is NONE.

**Comment by marcusburghardt** [comment]
The steps to reproduce are not clear. It seems a very particular case but we need more detailed information to clarify what is the goal of this approach here. I am closing this issue but feel free to reopen it with more details if still relevant.
