### ISSUE TITLE
The value of xccdf_org.ssgproject.content_rule_auditd_data_retention_space_left_action should also allow 'syslog'

### ISSUE THREAD

**Issue by trevor-vaughan** [ComplianceAsCode/content#6688]
#### Description of problem:

The current prose recommendation for `xccdf_org.ssgproject.content_rule_auditd_data_retention_space_left_action` appears to be `email` but this is a less viable option than `syslog` for many (if not most) modern environments with correct log monitoring.

#### SCAP Security Guide Version:

`master` HEAD as of the date of issue creation.

#### Operating System Version:

EL8

**Comment by JAORMX** [comment]
This sounds reasonable to me.

**Comment by marcusburghardt** [comment]
The option is already available in the project: https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/auditing/configure_auditd_data_retention/var_auditd_space_left_action.var#L18

A tailored file can be created to choose an option different from the profile requirement.
