### ISSUE TITLE
Users should be told how to configure SNMP properly instead of turning it off.

### ISSUE THREAD

**Issue by trevor-vaughan** [ComplianceAsCode/content#6711]
#### Description of problem:

Best security practice indicates that we should monitor our systems and SNMPv3, if set up properly, is completely capable of doing so in a secure, vendor agnostic, manner.

However, there is a rule that says that SNMP should be disabled.

It would be better to tell people how to do it properly.

A puppet module that attempts to do so (with tests) can be found at https://github.com/simp/pupmod-simp-simp_snmpd/ for reference material.

**Comment by cipherboy** [comment]
Hi @trevor-vaughan -- this guidance comes from the [CIS benchmarks](https://www.cisecurity.org/cis-benchmarks/) from the distribution-independent section of their content.

If you have an external compliance specification that recommends and details the secure configuration of SNMP, the content could be discussed and added.

The CIS benchmarks technically allow it:

> Note: If SNMP is required:
>  - The server should be configured for SNMP v3 only. User Authentication and Message Encryption should be configured.
>  - If SNMP v2 is absolutely necessary, modify the community strings' values.

However, beyond that, there's no guidance. 


Unless you want to work with CIS to give guidance or have another benchmark with guidance, it likely is out of the scope of this project.

**Comment by marcusburghardt** [comment]
There are some rules in the project to satisfy most (probably all) SNMP related requirements from different benchmarks:
https://github.com/ComplianceAsCode/content/tree/master/linux_os/guide/services/snmp

These rules have in their descriptions more context for each case and also the reference for the benchmarks requirements.
I checked these rules now and confirmed that most of them are related to CIS benchmark. There is one rule from RHEL7 STIG.

Basically, the benchmarks are usually based on documentation and best practices to finally create a requirement. This project makes sure the requirement can be technically satisfied. So, if SNMP is used, its respective documentation should be checked to make sure it is properly configured. Then, if necessary to make sure the configuration is aligned with some benchmark requirement, these rules can help.

I am closing this issue as the comments and links seem valid for reference and there is no real issue in the context of this project.
