### ISSUE TITLE
grub2_bootloader_argument OVAL template lacks support for UEFI systems

### ISSUE THREAD

**Issue by freddieRv** [ComplianceAsCode/content#6716]
#### Description of problem:
This very issue has already been discussed on the [mailing list](https://lists.fedorahosted.org/archives/list/scap-security-guide@lists.fedorahosted.org/thread/VZDPWODPXZXKAWLYC6FCSS5NQMFARRLP/). However I couldn't find any issues/PRs directly addressing it.

In short: The grub2_bootloader_argument OVAL template has a hardocded path to the `grub.cfg` config file that is only valid for non-uefi systems, namely `/boot/grub2/grub.cfg`. While in UEFI systems it is `/boot/efi/EFI/redhat/grub.cfg`.

This causes false negatives on UEFI systems for the rules that use this template.

#### SCAP Security Guide Version:
0.1.54

#### Operating System Version:
Testing with OL7.9

#### Steps to Reproduce:
1. On a UEFI system, run a scan with any of the rules that use the grub2_bootloader_argument template (e.g. `grub2_vsyscall_argument`, `grub2_page_poison_argument`, `grub2_audit_backlog_limit_argument`).

#### Actual Results:
Scan always results in `fail` and remediation in `error` since the OVAL check looks for the config entry in a file that does not exist.

#### Expected Results:
Scan should result in `pass`/`fail` depending on if the looked for configuration is present or not

#### Additional Information/Debugging Steps:
A possible approach to fix this was suggested on the email thread linked above:

_"...So the approach forward could be to add UEFI versions of the rules
equivalent to the BIOS kernel argument rules; and updating the template to
handle both cases (by passing different arguments for each case, for
example)..."_

I will gladly implement this fix if it is an acceptable approach.

**Comment by ggbecker** [comment]
Hi @freddieRv

this still seems to be a valid issue and the approach suggested in the mailing list as you pointed out seems to be the best approach as of now.

So, new rules can be created adding the suffix `_uefi` to differentiate from non-uefi ones, and they may be moved to the correct subdirectory as seen here: [linux_os/guide/system/bootloader-grub2](https://github.com/ComplianceAsCode/content/tree/master/linux_os/guide/system/bootloader-grub2)

A new option to the template has to be added to be able to enable/disable the uefi behavior of the rule template.

The lines

https://github.com/ComplianceAsCode/content/blob/094f9dd860ea0445b5af12d7b5c064868fb54363/linux_os/guide/system/bootloader-grub2/uefi/group.yml#L8

and

https://github.com/ComplianceAsCode/content/blob/094f9dd860ea0445b5af12d7b5c064868fb54363/linux_os/guide/system/bootloader-grub2/non-uefi/group.yml#L8

Should make sure that any file inside these directories will have its applicability properly assessed.

Feel free to open a pull request and we can follow up there.

**Comment by freddieRv** [comment]
PR #8180 fixed this issue
