### ISSUE TITLE
Many Ansible remediations for SLES fail ansible-lint tests

### ISSUE THREAD

**Issue by vojtapolasek** [ComplianceAsCode/content#6726]
#### Description of problem:

As a part of the CI, we are running a test which checks Ansible remediations with ansible-lint (https://ansible-lint.readthedocs.io/en/latest/). Currently, te test is failing for rules present in sle12 and sle15 products. you can see results of CI tests here:
https://jenkins.complianceascode.io/job/scap-security-guide-lint-check/

Note that the test is turned off during regular builds such as builds you perform on your local machines. It is also not run during PR gating because it takes long time.

#### SCAP Security Guide Version:

master
#### Steps to Reproduce:

1. Within main CMakeLists.txt, change the line:

```
option(ANSIBLE_CHECKS "Set to ON to enable ansible-lint and yamllint checks" OFF)
```

to

```
option(ANSIBLE_CHECKS "Set to ON to enable ansible-lint and yamllint checks" ON)
```

2. build sle12 and sle15 products
3. run ctest and see results

#### Actual Results:

Ansible-lint tests for sle12 and sle15 are failing

#### Expected Results:

All tests are passing.

**Comment by vojtapolasek** [comment]
@guangyee @brett060102  could you please look into this? Thank you very much.

**Comment by brett060102** [comment]
Looking now.

**Comment by yuumasato** [comment]
> `option(ANSIBLE_CHECKS "Set to ON to enable ansible-lint and yamllint checks" OFF)`

You can also pass `-DANSIBLE_CHECKS=ON` during `cmake` command.

**Comment by guangyee** [comment]
Any reason why this option is not enabled in CI by default?

**Comment by brett060102** [comment]
@vojtapolasek should be handled with https://github.com/ComplianceAsCode/content/pull/6730

**Comment by yuumasato** [comment]
> Any reason why this option is not enabled in CI by default?

It takes some time to run so it is not part of CI for PRs, but it is ran nightly:
https://jenkins.open-scap.org/view/SCAP%20Security%20Guide/job/scap-security-guide-lint-check/

**Comment by marcusburghardt** [comment]
I just tried to reproduce this issue and it still valid. FYI @teacup-on-rockingchair

**Comment by teacup-on-rockingchair** [comment]
> I just tried to reproduce this issue and it still valid. FYI @teacup-on-rockingchair

Thanks @marcusburghardt also was able to reproduce it on my local setup, will make sure to handle it soon.
