### ISSUE TITLE
test_verify_all_rpms_mode is not generally useful

### ISSUE THREAD

**Issue by trevor-vaughan** [ComplianceAsCode/content#6742]
#### Description of problem:

Verification of RPM modes is reasonable as a check but:
* The severity should be **low** since a large number of these may be false positives
* The changes may be fixes for RPMs that have file modes that are too permissive
* The changes may be tightening of permissions past what the RPM provides by default

The remediation is to set the permissions back to the RPM defaults which will potentially leave the system is a less secure state than the currently configured state.

The checks should compare the current file mode with the RPM file mode and determine if the permissions are less restrictive instead of placing undue burden on the user to figure it out by hand.

#### SCAP Security Guide Version:

https://github.com/ComplianceAsCode/content/blob/c1aa29c927b976389abbfe94000b72c01f5aff08/linux_os/guide/system/software/integrity/software-integrity/rpm_verification/rpm_verify_permissions/oval/shared.xml

**Comment by trevor-vaughan** [comment]
It looks like installing `yum-plugin-verify` provides reasonable review output.

Get the list of affected RPMs and then run each one through `yum verify-rpm` to see what has changed.
```
rpm -Va | grep '^.M' | rev | cut -f1 -d' ' | rev` | sort -u
```

**Comment by Mab879** [comment]
Due limits of OVAL this is not possible.

Thanks for opening this issue.
