### ISSUE TITLE
accounts_tmout should check all files in /etc/profile.d and not ask users to modify /etc/profile

### ISSUE THREAD

**Issue by trevor-vaughan** [ComplianceAsCode/content#6746]
#### Description of problem:

`accounts_tmout` appears to be an antiquated check that tries to have the user modify `/etc/profile` directly.

Per the documentation at the top of that file in pretty much every OS I've checked, users should be updating files in `/etc/profile.d`.

The `TMOUT` variable should be used for BASH-style shells and the `autologout` variable should be used for CSH-style shells.

The name of the file should not matter.

Modifications to `/etc/profile` should be considered a finding.

#### SCAP Security Guide Version:

https://github.com/ComplianceAsCode/content/blob/22ef2f61b24ff4686d745ba68656ca3b88a99e27/linux_os/guide/system/accounts/accounts-session/accounts_tmout/rule.yml

**Comment by lenox-joseph** [comment]
Shouldn't this be closed @jan-cerny ?
