### ISSUE TITLE
Certain test scenarios have to be skipped by SSGTS when selecting a profile

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#6781]
In some test scenarios we assume that a certain value is wrong (to provoke a fail) and it can happen that this assumed value is actually selected by a profile which can make the test have unexpected results when running SSGTS with a selected profile.

These tests should either be skipped or treated in a different way. Further investigation is needed.

_Originally posted by @ggbecker in https://github.com/ComplianceAsCode/content/issues/6765#issuecomment-810042481_

**Comment by cipherboy** [comment]
Two thoughts:

Perhaps add a mechanism for selecting a test case only under certain scenarios. Either in dotted form in the script name (like `test_name.profile_name.pass/fail.sh`) or as part of a header section in the test (similar to platform, perhaps do `profile@platform` or similar). By default applies to everything, and could have negations perhaps (`!profile@platform` or `!platform`).

Perhaps we need to add jinja templating into the test cases. This might require we add a no-op status code but we could evaluate each test case in the environment of the rule+profile+product it is being run under (special casing `(all)` to the default), separately for each execution.

 This would allow us to:
   - Pull in the actual variable value we care about,
   - No-op execution when the profile/.. doesn't match one we care about (if we execute it, the former idea would allow us to skip these tests entirely),
   - Handle any (small) differences in product more easily than creating a new rule -- potentially handling different package names too.

One follow up question: do templates have test cases? If not yet, perhaps this would be a way to add them in a product-agnostic manner -- then we can validate that the prodtypes we _think_ they apply to, they actually will. Just a thought :)

**Comment by cipherboy** [comment]
Note that Jinja support for templates is going to be added in #7210 and support for tests under shared/templates is added under #7211. 

Currently Jinja support for templates doesn't do any detection of profile and variable values. But the infrastructure is now in place to pass through a platform specifier so passing through a profile as well wouldn't be too much work (though, some care as to how variables get loaded and exposed to Jinja templates at build time will need to be taken).

**Comment by Mab879** [comment]
This should be fixed now.
