### ISSUE TITLE
RHEL7 Tailoring File Not Excluding Remediation

### ISSUE THREAD

**Issue by mrabe142** [ComplianceAsCode/content#6790]
#### Description of problem:
Starting with SSG 0.1.53, there was a remediation added  (https://github.com/ComplianceAsCode/content/pull/6049) that is breaking cloud users in AWS. This is the first time I've attempted to create a tailoring file so I may have done something wrong. I attempted to create and apply a tailoring file to skip this rule but the remediation is still applied. I first tried just having the 'nopasswd' rule in the tailoring file but that did not seem to work. I expanded it to all 'sudo' rules and that did not work either.

#### SCAP Security Guide Version:
SSG 0.1.55
OpenSCAP 1.2.17-13.el7_9

#### Operating System Version:
RHEL 7.9

#### Steps to Reproduce:

1. Created a tailoring file: 
```
<?xml version="1.0" encoding="UTF-8"?>
<xccdf:Tailoring xmlns:xccdf="http://checklists.nist.gov/xccdf/1.2" id="xccdf_scap-workbench_tailoring_default">
  <xccdf:benchmark href="C:/Program Files (x86)/scap-workbench/ssg/ssg-rhel7-ds-1.2.xml"/>
  <xccdf:version time="2021-02-03T12:59:25">1</xccdf:version>
  <xccdf:Profile id="xccdf_org.ssgproject.content_profile_stig_customized" extends="xccdf_org.ssgproject.content_profile_stig">
    <xccdf:title xmlns:xhtml="http://www.w3.org/1999/xhtml" xml:lang="en-US" override="true">DISA STIG for Red Hat Enterprise Linux 7 [CUSTOMIZED]</xccdf:title>
    <xccdf:description xmlns:xhtml="http://www.w3.org/1999/xhtml" xml:lang="en-US" override="true">This profile contains configuration checks that align to the
DISA STIG for Red Hat Enterprise Linux V2R8.

In addition to being applicable to Red Hat Enterprise Linux 7, DISA recognizes this
configuration baseline as applicable to the operating system tier of
Red Hat technologies that are based on Red Hat Enterprise Linux 7, such as:

- Red Hat Enterprise Linux Server
- Red Hat Enterprise Linux Workstation and Desktop
- Red Hat Enterprise Linux for HPC
- Red Hat Storage
- Red Hat Containers with a Red Hat Enterprise Linux 7 image</xccdf:description>
    <xccdf:select idref="xccdf_org.ssgproject.content_rule_sudo_remove_nopasswd" selected="false"/>
    <xccdf:select idref="xccdf_org.ssgproject.content_rule_sudo_remove_no_authenticate" selected="false"/>
    <xccdf:select idref="xccdf_org.ssgproject.content_group_sudo" selected="false"/>
  </xccdf:Profile>
</xccdf:Tailoring>
```
2. Start automated AWS deployment with the provided cloud user that is configured for passwordless sudo to create a customized AMI.
3. Run scan + remediation as part of that automation: 
```
oscap xccdf eval \
      --remediate \
      --profile xccdf_org.ssgproject.content_profile_stig \
      --results /tmp/oscap-remediation-results.xml \
      --report /tmp/oscap-remediation-report.html \
      --fetch-remote-resources \
      --tailoring-file /tmp/openscap/ssg-rhel7-ds-tailoring.xml \
      /usr/share/scap-security-guide/ssg-rhel7-ds.xml
```

#### Actual Results:
Remediation for those rules is still applied and infrastructure automation fails while waiting for a password that doesn't exist.

#### Expected Results:
The remediation skips those rules and automation continues to work as it did prior to SSH 0.1.53.

**Comment by ggbecker** [comment]
You have to use the customized profile id instead:

--profile xccdf_org.ssgproject.content_profile_stig_**customized** \
