### ISSUE TITLE
RHEL8 STIG rules - missing IDs

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#6844]
#### Description of problem:
Some rules from rhel8 stig profile miss an ID.

List of the rules:
```
*** rules of 'stig' profile missing STIG IDs: 211 of 251 have them [15% missing]
   auditd_data_retention_space_left_action      
   configure_bind_crypto_policy                    configure_crypto_policy                      
   configure_kerberos_crypto_policy             
   configure_libreswan_crypto_policy            
   configure_openssl_crypto_policy              
   configure_ssh_crypto_policy                  
   dconf_gnome_banner_enabled                      enable_dracut_fips_module                    
   grub2_admin_username                            grub2_uefi_admin_username                    
   no_empty_passwords                           
   package_abrt-addon-ccpp_removed              
   package_abrt-addon-kerneloops_removed        
   package_abrt-addon-python_removed               package_abrt-cli_removed                     
   package_abrt-plugin-logger_removed           
   package_abrt-plugin-rhtsupport_removed       
   package_abrt-plugin-sosreport_removed           package_aide_installed                       
   package_audit_installed                      
   package_fapolicyd_installed                  
   package_firewalld_installed                  
   package_openssh-server_installed             
   package_rng-tools_installed                     package_tmux_installed                       
   package_usbguard_installed                      partition_for_var_tmp                        
   require_emergency_target_auth                
   set_password_hashing_algorithm_systemauth    
   sshd_disable_empty_passwords                    sshd_disable_kerb_auth                       
   sshd_set_keepalive_0                            sshd_use_strong_rng                          
   sysctl_crypto_fips_enabled                   
   sysctl_net_ipv4_conf_default_accept_source_route
   sysctl_net_ipv6_conf_all_accept_redirects    
   sysctl_net_ipv6_conf_all_accept_source_route 
   sysctl_net_ipv6_conf_default_accept_redirects
   sysctl_net_ipv6_conf_default_accept_source_route                 
```

#### SCAP Security Guide Version:
`master`

#### Steps to Reproduce:

`$ python3 build-scripts/profile_tool.py stats --benchmark build/ssg-rhel8-xccdf.xml --profile ospp --missing-ospp-refs --skip-stats`

#### Actual Results:
Rules miss IDs.

#### Expected Results:
No rule misses ID.

#### Additional Information/Debugging Steps:
Similar as #6842 and #6843 - we want to have STIG profile in gating test that checks missing references/ids, but we can't add it now because the test would fail and block PRs.

Ping me, if you want me to update the list of rules. I'm checking references against master branch.

**Comment by mildas** [comment]
@ggbecker can you look at it?

**Comment by ggbecker** [comment]
For most of these rules, we are waiting on DISA to update STIG. We have sent them requests to split rules and they are basically what is listed here. This should be addressed only in RHEL8 STIG V1R3. The next release is V1R2.

**Comment by carlosmmatos** [comment]
@mildas @ggbecker I plan on updating the the existing mapped rules with the appropriate stig id's and references soon. This may help with this as I believe this is saying that there are rules in the rhel8_stig.profile that don't have a corresponding `stigid@rhel8`.

**Comment by ggbecker** [comment]
> @mildas @ggbecker I plan on updating the the existing mapped rules with the appropriate stig id's and references soon. This may help with this as I believe this is saying that there are rules in the rhel8_stig.profile that don't have a corresponding `stigid@rhel8`.

These are pretty much sitg rules that are grouped into other rules. So we don't have the STIG ids to assign to them yet. I guess we could use what we have from the upcoming changes to assign the STIG ids. But they will have nothing to map against since the STIG document won't have them.
