### ISSUE TITLE
Updating CIS-CSC: new name and acronym?

### ISSUE THREAD

**Issue by cipherboy** [ComplianceAsCode/content#6855]
#### Description of problem:

As pointed out by @yuumasato in #6837:

> A side note, it doesn't seem to be called "Critical Security Controls" anymore, just Controls...
> Should we change all cis-cscuri references? And to what?

Also, what new acronym would we use? `cis-c`? `cisc`? 

We'd also need to update the [rule.yml](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/services/ssh/ssh_server/sshd_set_keepalive/rule.yml#L51) and build system...

```
shared/transforms/shared_constants.xslt:32:<xsl:variable name="cis-cscuri">https://www.cisecurity.org/wp-content/uploads/2017/03/Poster_Winter2016_CSCs.pdf</xsl:variable>
shared/transforms/shared_shorthand2xccdf.xslt:287:          <xsl:if test="$refsource = 'cis-csc'">
shared/transforms/shared_shorthand2xccdf.xslt:288:            <xsl:value-of select="$cis-cscuri" />
tests/unit/ssg-module/test_playbook_builder_data/rules/selinux_state.yml:25:references: {cis: 1.6.1.2, cis-csc: '1,11,12,13,14,15,16,18,3,4,5,6,8,9', cobit5: 'APO01.06,APO11.04,APO13.01,BAI03.05,DSS01.05,DSS03.01,DSS05.02,DSS05.04,DSS05.05,DSS05.07,DSS06.02,DSS06.03,DSS06.06,MEA02.01',
tests/unit/ssg-module/data/sshd_disable_root_login.yml:35:references: {cis: 5.2.8, cis-csc: '1,11,12,13,14,15,16,18,3,5',
tests/unit/ssg-module/data/file_owner_grub2_cfg.yml:25:references: {cis: 1.4.1, cis-csc: '12,13,14,15,16,18,3,5', cjis: 5.5.2.2, cobit5: 'APO01.06,DSS05.04,DSS05.07,DSS06.02',
```

Is there anywhere else I'm missing?

**Comment by marcusburghardt** [comment]
I just consulted the CIS Critical Security Controls Version 8 and noticed that both "CIS Critical Security Controls" and "CIS Controls" are interchangeably used.

Reference: https://learn.cisecurity.org/CIS-Controls-v8-guide-pdf

Therefore, the existing `cis-csc` acronym is correct. It is not necessary to be changed.
