### ISSUE TITLE
RHEL8 STIG Ansible Playbook - Configure removal-action - default file - fatal error

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#6857]
#### Description of problem:
RHEL8 STIG Ansible playbook is terminated by fatal error:
```
TASK [Configure removal-action - default file] *********************************
fatal: [192.168.122.71]: FAILED! => {"msg": "The conditional check 'dconf_gnome_lock_screen_on_smartcard_removal_config_files is defined and dconf_gnome_lock_screen_on_smartcard_removal_config_files.matched == 0' failed. The error was: error while evaluating conditional (dconf_gnome_lock_screen_on_smartcard_removal_config_files is defined and dconf_gnome_lock_screen_on_smartcard_removal_config_files.matched == 0): 'dict object' has no attribute 'matched'\n\nThe error appears to be in '/usr/share/scap-security-guide/ansible/rhel8-playbook-stig.yml': line 328, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Configure removal-action - default file\n      ^ here\n"}
```

#### SCAP Security Guide Version:
bae768b

#### Operating System Version:
rhel8

#### Steps to Reproduce:
1. `ansible-playbook -e ansible_python_interpreter=/usr/bin/python3 --skip-tags ensure_gpgcheck_never_disabled,configure_opensc_nss_db -i "192.168.122.71," /usr/share/scap-security-guide/ansible/rhel8-playbook-stig.yml`

#### Actual Results:
Fatal error

#### Expected Results:
No error

#### Additional Information/Debugging Steps:
Probably caused by `dconf_gnome_lock_screen_on_smartcard_removal` which was recently added to the STIG profile.

**Comment by ggbecker** [comment]
I'm going to take a look. Thank you for the report.

**Comment by ggbecker** [comment]
The previous task was skipped, which is the one that registers the variable to be used in the next task. The problem is that 
```
TASK [Detect if removal-action can be found on /etc/dconf/db/local.d/] *********
skipping: [192.168.122.71]
```

The problem is that the `when` clauses `'"gdm" in ansible_facts.packages'` and `ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]` have to come first in the list. In the previous task it was skipped because there are no additional `when` clauses.
```
      when:
        - dconf_gnome_lock_screen_on_smartcard_removal_config_files is defined and dconf_gnome_lock_screen_on_smartcard_removal_config_files.matched
          == 0
        - '"gdm" in ansible_facts.packages'
        - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]
```

**Comment by ggbecker** [comment]
This actually turned out to be a problem in the ansible remediation builder.
