### ISSUE TITLE
Oracle JRE Version match too restrictive

### ISSUE THREAD

**Issue by lordofhyphens** [ComplianceAsCode/content#6885]
#### Description of problem:
The version in the OVAL for JRE has a version "equals" for 1.8.0, while Oracle is now inserting the update # into the version string, so the version for 1.8u281 is 1.8.0_281 (as noted in the system info).

The using test 'oval:ssg-test_oracle_java_rhel:tst:1` requires that the version be exactly 1.8.0 to pass. 

#### SCAP Security Guide Version:

0.1.55

#### Operating System Version:
Red Hat Enterprise Linux 7

#### Steps to Reproduce:

1. Install Oracle JRE 1.8.0_281 Linux x64 RPM Package from https://www.oracle.com/java/technologies/javase-jre8-downloads.html
2. Attempt to perform an XCCDF scan with the datastream.
```bash
oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_stig ssg-jre-ds.xml
```

#### Actual Results:
All evaluation entries are `notapplicable`

#### Expected Results:
None of the evaluation entries are `notapplicable`

#### Additional Information/Debugging Steps:

Suggest adding a test set to bound the version to [1.8.0, 1.9.0) and include it for the JRE checks when dealing with oracle_java.

**Comment by cipherboy** [comment]
I don't have any answers here, but one additional question I have is how should we handle features/... only introduced in later JDK versions? A great example wold be TLSv1.3. Up until roughly JDK 1.8u275 (or 272? 268? Something in there) -- TLSv1.2 was the highest supported TLS version and so policy should probably notate that. However, as of that update, TLSv1.3 was backported and it would probably be best to disable TLSv1.0 and TLSv1.1 entirely going forward. Knowing batch updates might actually help us here.

Though in general, if it applies to all JDK8 versions, yes, that version check seems right.

**Comment by lordofhyphens** [comment]
@cipherboy Since, at least for Oracle Java, it's already going to be a finding to run an old versions of Java JRE. 

If it was important to keep track of the "best" for different ranges of versions, we would need to probably split those checks/rules out (and/or maintain different profiles).

**Comment by lordofhyphens** [comment]
I've went ahead and made a "minimum fix" to relax that version string for only Oracle JRE from Oracle itself (not the rhel string, etc).
