### ISSUE TITLE
Approved sshd ciphers: dependency on installed_OS_is_FIPS_certified?

### ISSUE THREAD

**Issue by cipherboy** [ComplianceAsCode/content#6901]
#### Description of problem:

I'm working on adding Ubuntu 20.04 CIS rules. CIS has the notion of an "approved" set of SSH ciphers/kex/MACs.

However, the `sshd_approved_ciphers` and `sshd_approved_macs` rules both depend on `installed_OS_is_FIPS_certified`. Is this strictly required?

Ubuntu does have FIPS support (see https://ubuntu.com/security/certifications) so my issue is not there (I am working out language and will propose an upstream PR to add it to `installed_OS_is_FIPS_certified` eventually). More, my thoughts are that the `sshd_approved_ciphers` rules appear to be better written (e.g., having a variable for allowed ciphers) than the corresponding "non-FIPS" `sshd_use_strong_ciphers` rules.

I'd prefer to drop the dependency on `installed_OS_is_FIPS_certified` and have profiles which strictly require FIPS to pull in `installed_OS_is_FIPS_certified` when necessary. And also, drop the "strong" versions of the rules in favor of the "approved"+variable versions.

Thoughts?

#### SCAP Security Guide Version:

`master` as of 5b5fd67837246ffa293f107c58c6e448646c3292.

**Comment by lordofhyphens** [comment]
I believe that DISA STIG also has moved to the "approved" list (at least it's own scanner is checking for an explicit list of ciphers/kex/MACs, so I don't think it'd go unused for RHEL.

**Comment by cipherboy** [comment]
> I believe that DISA STIG also has moved to the "approved" list (at least it's own scanner is checking for an explicit list of ciphers/kex/MACs, so I don't think it'd go unused for RHEL.

I do agree but note that DISA STIG (being part of DoD) has strict requirements to use FIPS. :-) So the dependency from `sshd_approved_ciphers` onto `installed_OS_is_FIPS_certified` (in the OVAL) makes perfect sense in the DISA profile case but not in the e.g., CIS case which is used by public sector.

**Comment by marcusburghardt** [comment]
FYI @dodys

**Comment by dodys** [comment]
> FYI @dodys

@marcusburghardt that question is from Alex when he was working at Canonical, so it is not a question strict to Ubuntu but rather to the whole of ComplianceAsCode.

If this doesn't fit the project intention then we should close this ticket.
