### ISSUE TITLE
RHEL-07-040530 fails check after remediation with upstream XCCDF

### ISSUE THREAD

**Issue by lordofhyphens** [ComplianceAsCode/content#6902]
#### Description of problem:
The DISA STIG also requires (at least w/r/t the SCAP checklist from pub.cyber.mil) that the `silent` flag is not present for `pam_lastlog.so` (as the STIG clearly states "must display" for STIG ID RHEL-07-040530).

This causes a failure when the system is later rescanned with the DISA checklist and OVAL definitions. 

#### SCAP Security Guide Version:

master @ 5b5fd67837246ffa293f107c58c6e448646c3292

#### Operating System Version:
Red Hat Enterprise Linux  7.9

#### Steps to Reproduce:

1. Scan and remediate a RHEL7 system with `content_profile_stig`. 
2. Re-scan the system with DISA's own checklist and  the MAC1-Classified profile.

#### Actual Results:
V-204605 is marked as failed by DISA's SCAP benchmark (https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/U_RHEL_7_V3R3_STIG_SCAP_1-2_Benchmark.zip)

#### Expected Results:
V-204605 is not marked as failed and the `silent` flag is not present.

**Comment by lordofhyphens** [comment]
I recommend the following:
* Revise [display_logon_attempts](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-pam/display_login_attempts/rule.yml#L5) rule to additionally check for the `silent` option and remove.

**Comment by lordofhyphens** [comment]
After looking closely at the profile lists to see where `display_login_attempts` gets used, seems like it's getting used by `stig`, `ncp`, `pci-dss`, and `rhelh-stig`.

Is there a reason why we would want `silent` for lastlog on `ncp` and `pci-dss`? If not, I'd suggest adding `rhel7` and `rhel8` to the platform list in the OVAL checks.

If there is a reason (I'm not an expert on `ncp` or `pci-dss`), we'd need to add an additional rule to split the behavior across the two profiles. 

@carlosmmatos any ideas?

**Comment by ggbecker** [comment]
Sounds like we should enable this SLE only code part also for RHEL7/8

https://github.com/ComplianceAsCode/content/blob/daf8697bedd11865a749b5c29d5ca228151c0bfa/linux_os/guide/system/accounts/accounts-pam/display_login_attempts/oval/shared.xml#L34

Regarding other profiles there needs to have more investigation. But most likely this behavior should be the same there as well.

**Comment by lordofhyphens** [comment]
* `pci-dss` https://www.pcidssguide.com/pci-dss-requirement-10/ 
   Looks like it only requires that it logs the failure. There's no text re: displaying that to users (or not doing so), so changing this behavior should be fine.
* `ncp` https://www.stigviewer.com/controls/800-53/AC-9 According to this, `ncp` should be displaying the output to the user.

**Comment by marcusburghardt** [comment]
This rule was already reworked. There is another issue (https://github.com/ComplianceAsCode/content/issues/9031) opened to improve the rule description on STIG.
