### ISSUE TITLE
Are STIGID and CIS identifiers or references?

### ISSUE THREAD

**Issue by cipherboy** [ComplianceAsCode/content#6905]
#### Description of problem:

If I understand correctly, references have historically been to external benchmarks. Identifiers have to be unique to a rule though.

Typically though, Identifiers are product-specific. Some products (such as SUSE and RHEL) have CCE numbers and assign them. Functionally, AFAICT, CCEs are the only identifiers in the build system.

References (with the exception of stigid and cis) are typically product-independent. They're not unique and multiple rules might have the same reference number and one rule might have multiple reference numbers.

But does this distinction matter?

Does it make sense to move stigid and cis to the identifier section and drop the strict uniqueness check? 

Especially with the auto-profile tool based on product-independent reference controls -- we'd either need to add product-specific-ness into this tooling if we wanted to add e.g., CIS or STIG (essentially, in my view, recreating profiles) -- or we could agree that the definitions of "identifier" and "references" are a bit loose, given that the rule_id is the _real_ identifier ;-)

My 2c. 

#### SCAP Security Guide Version:

`master`

**Comment by carlosmmatos** [comment]
This is a good question. We've had some discussions surrounding references lately in regards to which ones are product-specific and those that are not. I would like to understand the importance (or lack of) of having these in relation to how we utilize it. 

Currently, I think the definitions are a bit loose, but hopefully this will spark some good conversations.. I'm wondering if we should move this to the `Discussions` thread?

**Comment by cipherboy** [comment]
Sure, we can move wherever. Is this a Q&A or a Ideas thread? :)

Also, perhaps since we only have one type of identifier, we just want to combine everything down into a single YAML key (`references` maybe)? I dunno :)

**Comment by carlosmmatos** [comment]
I would classify this thread as somewhat of a mixture of the two - which I think is a good candidate to move to discussions. I'll go ahead and add a thread in there.

**Comment by carlosmmatos** [comment]
sorry - I misunderstood the original Q/A vs Ideas statement.. I think for this it might make sense to do Ideas in that at this point, we are kind of looking for ideas on figuring out how we want to use references/identifiers.

**Comment by cipherboy** [comment]
Moved to https://github.com/ComplianceAsCode/content/discussions/6920.
