### ISSUE TITLE
auditd_data_retention_space_left does not check properly

### ISSUE THREAD

**Issue by trevor-vaughan** [ComplianceAsCode/content#7015]
#### Description of problem:

Profile = STIG

When `space_left` is set to `space_left = 80` the check is failing.

#### SCAP Security Guide Version:

0.1.55

#### Operating System Version:

EL7

**Comment by marcusburghardt** [comment]
Any value different from the expected value according to the selected profile will fail, as expected.
Tailoring is an option if it is desired to remove any rule from the profile.
