### ISSUE TITLE
auditd_data_disk_error_action does not process properly

### ISSUE THREAD

**Issue by trevor-vaughan** [ComplianceAsCode/content#7020]
#### Description of problem:

Profile = STIG

Content of `/etc/audit/auditd.conf`:

```
disk_full_action = syslog
```

Check fails but the prose indicates that `syslog` is a valid value to pass.

#### SCAP Security Guide Version:

`v0.1.55`

#### Operating System Version:

EL8

**Comment by ggbecker** [comment]
which profile are you using to scan? This rule uses the variable https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/auditing/configure_auditd_data_retention/var_auditd_disk_full_action.var and it will depend on which one is selected

**Comment by yuumasato** [comment]
This rule checks for the `disk_error_action` and the rule prose is aligned to that. 
https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_disk_error_action/rule.yml#L10

The profile in use definitely plays a role in it.
But also, I noticed that the check has `<ind:instance datatype="int">1</ind:instance>`, meaning that it would check only the first match for `disk_error_action`. Could it be that there are multiple lines with the parameter?

**Comment by trevor-vaughan** [comment]
I'm using the STIG profile.

There's only one line that matches.

**Comment by trevor-vaughan** [comment]
Hrm...maybe update the request template to ask which profile is being used. I'll go update my recent tickets.

**Comment by Mab879** [comment]
In the STIG there is new rule (auditd_data_disk_error_action_stig) to address this.
