### ISSUE TITLE
auditd max_log_file_action check incorrect

### ISSUE THREAD

**Issue by trevor-vaughan** [ComplianceAsCode/content#7021]
#### Description of problem:

Profile = STIG

Scan fails with `/etc/audit/auditd.conf` containing:

```
max_log_file_action = rotate
```

The prose indicates that this value is acceptable.

#### SCAP Security Guide Version:

`v0.1.55`

#### Operating System Version:

EL 8

**Comment by marcusburghardt** [comment]
STIG expects `syslog` for RHEL8 and `rotate` for RHEL7.

Please, also see more context at https://github.com/ComplianceAsCode/content/issues/7022#issuecomment-927721902
