### ISSUE TITLE
auditd_data_disk_full_action check is incorrect

### ISSUE THREAD

**Issue by trevor-vaughan** [ComplianceAsCode/content#7022]
#### Description of problem:

Profile = STIG

Check fails with the following in `/etc/audit/auditd.conf`:

```
disk_full_action = syslog
```

This is noted as acceptable by the prose in the check.

#### SCAP Security Guide Version:

`v0.1.55`

#### Operating System Version:

EL 8

**Comment by marcusburghardt** [comment]
Hi @trevor-vaughan,

Although this `syslog` is a valid value for `disk_full_action` config, the rule will report fail if the value is not the expected one in the selected profile.
For example, the STIG profile for RHEL8 expect `halt` as correct value.
- RHEL8: https://github.com/ComplianceAsCode/content/blob/master/products/rhel8/profiles/stig.profile#L72

If the variable is not specified in the profile, the default value of `single` is considered:
https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/auditing/configure_auditd_data_retention/var_auditd_disk_full_action.var#L12
