### ISSUE TITLE
DISA STIG for Kubernetes on OCP

### ISSUE THREAD

**Issue by jharmison-redhat** [ComplianceAsCode/content#7033]
#### Description of problem:

There is no published STIG for OpenShift at this time, but there is a [published Kubernetes STIG](https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/U_Kubernetes_V1R1_STIG.zip). It would be helpful for organizations to be able to combine the DRAFT RHCOS STIG with the officially published Kubernetes STIG as a starting point for compliance. The CIS Benchmarks profile closely aligns with the DISA STIG for Kubernetes, but some additional DoD-specific tweaks are required.

#### SCAP Security Guide Version:

N/A

#### Operating System Version:

Red Hat OpenShift Container Platform 4.x

#### Steps to Reproduce:

1. Build a new ProfileBundle image and apply it to a running Compliance Operator
2. Attempt to STIG your OpenShift cluster using the available profiles

#### Actual Results:

Identify that you will need to have a conversation with your compliance auditor to determine whether they believe the NIST Moderate, CIS Benchmark, or some other profile would be best

#### Expected Results:

See an obvious STIG benchmark to apply without having to identify relevance to my organizational controls framework.

#### Additional Information/Debugging Steps:

There would need to be a few new rules authored to support the Kubernetes STIG above and beyond the rules that exist currently in the project. Some of the existing rules could use variable expansion tweaks for reusability across the existing benchmarks that use them and slight changes in the Kubernetes STIG.

Most importantly, the Kubernetes STIG points to several file locations that do not directly align with OCP. This is the case for places where the Kubernetes STIG expects a core Kubernetes service (controller-manager, kubelet, api-server, etc.) to be installed as a systemd unit, or for cases where the Kubernetes STIG expects configuration files to be present at a specific location and to belong to a specific user. In OpenShift, there are often ConfigMaps or MachineConfigs for static pod manifests that would be more appropriate to use for remediation, and the file locations on disk may not be the same for the checks. There would need to be some amount of translation to explain these differences, most probably with some annotation as to why the check and remediation differ from the STIG. I was recently part of an effort to apply the Kubernetes STIG to an OpenShift cluster, and made these changes and justifications to an auditor who deemed them reasonable and appropriate. Our work on that effort is currently encapsulated in a spreadsheet and a DISA STIGViewer .ckl file.

I understand that there is an ongoing effort to formalize a STIG for OCP4, but that effort is still early and will take a not-trivial amount of time to be published by DISA. I think that this stopgap measure, the Kubernetes STIG modified slightly and justified, would be beneficial to OpenShift users today.

I am willing to do all of this work (and indeed am already working on it right now), but I would like a place to discuss this approach and solicit feedback from the CaC maintainers and community, especially as it pertains to those modified checks and remediations, and their justifications.

**Comment by JAORMX** [comment]
@jharmison-redhat hey! Thanks for bringing this up! Indeed your work would be well appreciated. What approach are you thinking about taking? I noticed references to the Compliance Operator. Are you acquainted with how we're doing the CIS benchmarks there? If not, I'd be happy to chat and explain it further.

Also, for Kubernetes/OpenShift content, we have a self-paced lab for the Compliance Operator [1] that explains briefly how to build content. It might be useful.

Anyway, I welcome this initiative and would be happy to help as much as I can! Let me know if you want to sync further about this work.

[1] https://github.com/openshift/compliance-operator/tree/master/doc/tutorials

**Comment by jharmison-redhat** [comment]
- I'm familiar with how the CIS benchmarks are being accomplished, I believe. [Profiles](https://github.com/ComplianceAsCode/content/tree/master/ocp4/profiles) for the platform-level API checks and node checks are split for privilege separation, rules are [commented](https://github.com/ComplianceAsCode/content/blob/master/ocp4/profiles/cis.profile#L28) so that they are traceable to the source from the SRG rule IDs, and the rules are sourced from this repo where they are expressed using a [YAML syntax](https://github.com/ComplianceAsCode/content/blob/master/applications/openshift/api-server/api_server_anonymous_auth/rule.yml) that can use Jinja2 templates to define ocil clauses.
- I've been doing custom builds using the provided BuildConfig for working with the existing Dockerfiles for custom content and managing ProfileBundles to test different streams of content.
- Mostly I'd like to know if the approach of using the k8s STIG, with modifications to the way we're implementing some of the checks and a lot of the remediations, would be acceptable practice :)

**Comment by jharmison-redhat** [comment]
I'm going to close this issue as we have decided we don't want to provide a method to use the Kubernetes STIG on OpenShift (since it would really be unable to follow the Kubernetes STIG items anyways, our customers are having more success with other methods for their risk mitigation/management, and the OpenShift STIG effort is maturing nicely).
