### ISSUE TITLE
xccdf_org.ssgproject.content_rule_ensure_gpgcheck_local_packages based on yum

### ISSUE THREAD

**Issue by dhpinkerton** [ComplianceAsCode/content#7043]
#### Description of problem:
Tests xccdf_org.ssgproject.content_rule_clean_components_post_updating
xccdf_org.ssgproject.content_rule_ensure_gpgcheck_globally_activated
xccdf_org.ssgproject.content_rule_clean_components_post_updating

return notapplicable in Centos 8.3 because yum is not installed.

#### SCAP Security Guide Version:
0.1.55

#### Operating System Version:
CentOS 8.3

#### Steps to Reproduce:

1. modify content-master/rhel8/product.yml  :- pkg_manager: "dnf"
2. compile rhel8 profiles :- ./build_product --derivatives rhel8
2.add CentOS8 detection as per https://bugs.centos.org/view.php?id=16717
3.oscap -V | grep centos
Community Enterprise Operating System 5 - cpe:/o:centos:centos:5
Community Enterprise Operating System 6 - cpe:/o:centos:centos:6
Community Enterprise Operating System 7 - cpe:/o:centos:centos:7
Community Enterprise Operating System 8 - cpe:/o:centos:centos:8
4.oscap xccdf eval --verbose INFO --rule xccdf_org.ssgproject.content_rule_ensure_gpgcheck_local_packages --profile e8 ./build/ssg-rhel8-ds.xml 2>&1 | grep yum 
I: oscap: Evaluating definition 'oval:ssg-installed_env_has_yum_package:def:1': Package yum is installed.
I: oscap:   Evaluating rpminfo test 'oval:ssg-test_env_has_yum_installed:tst:1': system has package yum installed.
I: oscap:     Querying rpminfo object 'oval:ssg-obj_env_has_yum_installed:obj:1', flags: 0.
I: oscap:     Creating new syschar for rpminfo_object 'oval:ssg-obj_env_has_yum_installed:obj:1'.
I: oscap:     Package "yum" not found.
I: oscap:     Test 'oval:ssg-test_env_has_yum_installed:tst:1' requires that at least one object defined by 'oval:ssg-obj_env_has_yum_installed:obj:1' exists on the system.
I: oscap:     0 objects defined by 'oval:ssg-obj_env_has_yum_installed:obj:1' exist on the system.
I: oscap:     Test 'oval:ssg-test_env_has_yum_installed:tst:1' does not contain any state to compare object with.
I: oscap:     No item matching object 'oval:ssg-obj_env_has_yum_installed:obj:1' was found on the system. (flag=does not exist)
I: oscap:   Test 'oval:ssg-test_env_has_yum_installed:tst:1' evaluated as false.
I: oscap: Definition 'oval:ssg-installed_env_has_yum_package:def:1' evaluated as false.

#### Actual Results:
  Package "yum" not found.

#### Expected Results:
Use dnf

**Comment by ggbecker** [comment]
You would have to change this line as well: https://github.com/ComplianceAsCode/content/blob/master/shared/checks/oval/installed_env_has_yum_package.xml#L24

**Comment by dhpinkerton** [comment]
Many thanks for this.  It has resolved content_rule_ensure_gpgcheck_local_packages and content_rule_ensure_gpgcheck_globally_activated but content_rule_clean_components_post_updating is still looking for /etc/yum.conf
Evaluating definition 'oval:ssg-clean_components_post_updating:def:1': Ensure dnf Removes Previous Package Versions.
I: oscap:   Evaluating textfilecontent54 test 'oval:ssg-test_yum_clean_components_post_updating:tst:1': check value of clean_requirements_on_remove in /etc/yum.conf.
I: oscap:     Querying textfilecontent54 object 'oval:ssg-object_yum_clean_components_post_updating:obj:1', flags: 0.
I: oscap:     Creating new syschar for textfilecontent54_object 'oval:ssg-object_yum_clean_components_post_updating:obj:1'.
I: oscap:     Starting probe on URI 'queue://textfilecontent54'.
I: oscap:     I will run textfilecontent54_probe_main:
I: oscap:     Opening file '/etc/yum.conf'.
I: oscap:     Test 'oval:ssg-test_yum_clean_components_post_updating:tst:1' requires that every object defined by 'oval:ssg-object_yum_clean_components_post_updating:obj:1' exists on the system.
I: oscap:     0 objects defined by 'oval:ssg-object_yum_clean_components_post_updating:obj:1' exist on the system.
I: oscap:     Test 'oval:ssg-test_yum_clean_components_post_updating:tst:1' does not contain any state to compare object with.
I: oscap:     No item matching object 'oval:ssg-object_yum_clean_components_post_updating:obj:1' was found on the system. (flag=does not exist)
I: oscap:   Test 'oval:ssg-test_yum_clean_components_post_updating:tst:1' evaluated as false.
I: oscap: Definition 'oval:ssg-clean_components_post_updating:def:1' evaluated as false.

**Comment by marcusburghardt** [comment]
Solved according to the previous comment.
