### ISSUE TITLE
RHEL 8 - CIS 3.2.1 (Ensure source routed packets are not accepted) is not being implemented properly

### ISSUE THREAD

**Issue by alexhaydock** [ComplianceAsCode/content#7060]
#### Description of problem:

Using the latest version of CaC available in a RHEL Kickstart install, this particular control fails validation as one of the 4 sysctls does not appear to be being set correctly.

#### SCAP Security Guide Version:

0.1.54

#### Operating System Version:

RHEL 8.4

#### Steps to Reproduce:

Kickstart a RHEL 8.4 install with the following:
```
%addon org_fedora_oscap
        content-type = scap-security-guide
        profile = xccdf_org.ssgproject.content_profile_cis
%end
```

#### Actual Results:

After installation:
```bash
[root@rhel8]# grep 'source_route' /etc/sysctl.d/99-sysctl.conf
# Per CCE-81015-0: Set net.ipv6.conf.default.accept_source_route = 0 in /etc/sysctl.conf
net.ipv6.conf.default.accept_source_route = 0
# Per CCE-81013-5: Set net.ipv6.conf.all.accept_source_route = 0 in /etc/sysctl.conf
net.ipv6.conf.all.accept_source_route = 0
# Per CCE-80920-2: Set net.ipv4.conf.default.accept_source_route = 0 in /etc/sysctl.conf
net.ipv4.conf.default.accept_source_route = 0
```

As a result of not setting all 4 sysctls for this particular CIS control, a system will fail validation for this particular control.

#### Expected Results:
We would expect the three entries above, but also an entry setting `net.ipv4.conf.all.accept_source_route`, which should look something like this:
```
net.ipv4.conf.all.accept_source_route = 0
```

#### Additional Information/Debugging Steps:
I can't quite work out why this is happening the way it is, because looking at the [CIS profile file for 0.1.54](https://github.com/ComplianceAsCode/content/blob/v0.1.54/rhel8/profiles/cis.profile), we can see that all 4 of the relevant sysctl settings are included in the profile:
```
    ### 3.2.1 Ensure source routed packets are not accepted (Scored)
    #### net.ipv4.conf.all.accept_source_route = 0
    - sysctl_net_ipv4_conf_all_accept_source_route

    #### net.ipv4.conf.default.accept_source_route = 0
    - sysctl_net_ipv4_conf_default_accept_source_route

    #### net.ipv6.conf.all.accept_source_route = 0
    - sysctl_net_ipv6_conf_all_accept_source_route

    #### net.ipv6.conf.default.accept_source_route = 0
    - sysctl_net_ipv6_conf_default_accept_source_route
```

Similarly, I can't see any relevant changes that have happened to the rule file [for the missing rule](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_conf_all_accept_source_route/rule.yml) recently so I'm struggling to work this one out.

**Comment by ggbecker** [comment]
This seems to be one of the default values. Check the file `/usr/lib/sysctl.d/50-default.conf`.

Remember you can also check the HTML report after installation: `/root/openscap_data/eval_remediate_report.html`

**Comment by alexhaydock** [comment]
> This seems to be one of the default values. Check the file `/usr/lib/sysctl.d/50-default.conf`.

Ah, this makes sense. so CaC has logic to avoid writing to `99-sysctl.conf` if the setting is already the default as per `50-default.conf`.

That explains my issue then, as the "failure" here is flagged up by CIS's CIS CAT Pro Assessor tool, rather than by a CaC or OpenSCAP scan. It looks like rather than reading the active sysctl value to conduct its testing, CIS CAT prefers to see that the value is set on disk instead, in `/etc/sysctl.conf` or somewhere in `/etc/sysctl.d/*.conf`. I can see positives and negatives to this approach but I guess maybe this is an issue for CIS CAT, and I might suggest that they also read in `/usr/lib/sysctl.d/50-default.conf` when assessing a system.

**Comment by alexhaydock** [comment]
I've filed a bug upstream with CIS for this one: https://workbench.cisecurity.org/community/14/tickets/10371
