### ISSUE TITLE
maxpoll interval needs clarification

### ISSUE THREAD

**Issue by mralph-rh** [ComplianceAsCode/content#7094]
#### Description of problem:
"The maxpoll should be configured to 16 in /etc/ntp.conf or /etc/chrony.conf to continuously poll time servers. To configure maxpoll in /etc/ntp.conf or /etc/chrony.conf add the following: maxpoll 16" statement is misleading as just adding maxpoll 16 causes chronyd to fail. Looking through the man page and this should be added at the end of the server line, not a line by itself.

#### SCAP Security Guide Version:
SSG-RHEL8-DS

#### Operating System Version:
  RHEL 8

#### Steps to Reproduce:

1. add maxpoll to end of file.
2.
3.
4.

#### Actual Results:
Job for chronyd.service failed because the control process exited with error code.

#### Expected Results:
chronyd should restart successfully

**Comment by marcusburghardt** [comment]
The description update, as in the mentioned commit should be good.

**Comment by Mab879** [comment]
The rule has been adjusted.

Thank!
