### ISSUE TITLE
RHEL8 CIS profile - sudo_custom_logfile fail

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#7101]
#### Description of problem:
The `sudo_custom_logfile` fails on rhel8.

#### SCAP Security Guide Version:
749cd70

#### Operating System Version:
RHEL 8

#### Steps to Reproduce:
1. `python3 tests/test_suite.py profile --libvirt qemu:///system test_suite_vm --datastream build/ssg-rhel8-ds.xml --xccdf-id scap_org.open-scap_cref_ssg-rhel8-xccdf-1.2.xml --mode online --remediate-using oscap xccdf_org.ssgproject.content_profile_cis`

#### Actual Results:
xccdf_org.ssgproject.content_rule_sudo_custom_logfile - fail 

#### Expected Results:
No failure

**Comment by cipherboy** [comment]
@mildas Do you have a log? Could you try it after c074cb9f7573649c1f6b393a01ba78b786b56fa7 ?

**Comment by mildas** [comment]
@cipherboy I've rerun tests and it still fails. Commit 822cced
