### ISSUE TITLE
remediation for maxpoll not working on rhel 8 chrony.conf

### ISSUE THREAD

**Issue by mralph-rh** [ComplianceAsCode/content#7110]
#### Description of problem:
  When running scap workbench with remediation against a RHEL 8 server, it does not configure maxpoll in the chrony.conf file.

#### SCAP Security Guide Version:
scap-security-guide-0.1.56-1.fc34.noarch

#### Operating System Version:
Fedora 34

#### Steps to Reproduce:

1. Verify chronyd is running
2. Run RHEL 8 STIG with remediation
3.

#### Actual Results:
  Does not put in changes.

#### Expected Results:
  Changes should be added to the server/peer line in chrony.conf

**Comment by marcusburghardt** [comment]
Bash remediation is working fine. However, the Ansible remediation is restricted to `multi_platform_sle`:
https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/services/ntp/chronyd_or_ntpd_set_maxpoll/ansible/shared.yml#L1

It looks safe to include `multi_platform_rhel`, like this:
`# platform = multi_platform_sle,multi_platform_rhel`

@mralph-rh would you like to send a PR with this fix?

**Comment by marcusburghardt** [comment]
Fixed by #7910
