### ISSUE TITLE
Ansible replace module unsupported parameter (follow)

### ISSUE THREAD

**Issue by GlennBell** [ComplianceAsCode/content#7132]
## Problem:
Several instances of ansible.builtin.replace use the deprecated follow parameter, causing the following error:

```
virtualbox-iso: TASK [redhatofficial.rhel8_stig : Do not allow users to reuse recent passwords - system-auth (change)] ***
    virtualbox-iso: fatal: [default]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (replace) module: follow Supported parameters include: after, attributes, backup, before, encoding, group, mode, owner, path, regexp, replace, selevel, serole, setype, seuser, unsafe_writes, validate"}
```

A review of redhatofficial.rhel8_stig/tasks/main.yml identified the use of the follow parameter in the following tasks:
- name: Do not allow users to reuse recent passwords - system-auth (change)
- name: Do not allow users to reuse recent passwords - system-auth (add)
- name: Prevent Log In to Accounts With Empty Password - system-auth
- name: Prevent Log In to Accounts With Empty Password - password-auth

## Background
The latest [replace documentation notes](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/replace_module.html#notes) states:

- **Option follow has been removed in Ansible 2.5, because this module modifies the contents of the file so follow=no doesn’t make sense.**

## Suggested Action(s)
The *follow* parameter can be safely removed from the identified tasks. There is no substitute parameter available.

A patchfile correcting the issue is attached.

[redhatofficial.rhel8_stig_replace.patch.txt](https://github.com/ComplianceAsCode/content/files/6677266/redhatofficial.rhel8_stig_replace.patch.txt)

**Comment by ggbecker** [comment]
This has been fixed for quite some time, unfortunately the galaxy hub content was not updated accordingly.

https://github.com/ComplianceAsCode/content/commit/6bb063948e2ddbc9a482ba9270e484db36d52783#diff-46d6c3bd46142f78e3df189182c8844a6e178a9faa81bcb5a9035e4a93252da6

**Comment by ggbecker** [comment]
The ansible galaxy content should be eventually updated. I'm closing this one. Feel free to reopen if you want.
