### ISSUE TITLE
rule "xccdf_org.ssgproject.content_rule_postfix_prevent_unrestricted_relay" is failing even when we do not have postfix RPM installed on the host

### ISSUE THREAD

**Issue by Ultimate-etamitlU** [ComplianceAsCode/content#7145]
#### Description of problem:
The STIG rule "xccdf_org.ssgproject.content_rule_postfix_prevent_unrestricted_relay" is failing even when we do not have postfix RPM installed on the host

#### SCAP Security Guide Version:
OSCAP version 1.2.17 , I believe every release

#### Operating System Version:
RHEL 7.X

#### Steps to Reproduce:

1. Don't install postfix rpm
2. Run openScap STIG scan
3.
4.

#### Actual Results:
Failed for above rule

#### Expected Results:

Shall mark not applicable.

**Comment by ggbecker** [comment]
can you post the output from `rpm -qa scap-security-guide` ?

Later versions of the content should result in `pass` if the file [`/etc/postfix/main.cf`](https://github.com/ComplianceAsCode/content/blob/d7920bf18877552d19968277d688a8f7bb3d10e5/linux_os/guide/services/mail/postfix_harden_os/postfix_server_cfg/postfix_server_relay/postfix_prevent_unrestricted_relay/oval/shared.xml#L11) does not exist. But the applicability is something to be considered as an improvement.

**Comment by Ultimate-etamitlU** [comment]
Yeah, just checked that @ggbecker , nevermind was about to close this.
I'll check for the fact again, shall have scanned it before reporting issue.
Thank you!
