### ISSUE TITLE
replace_or_append corrupts the key parameter if it's an '=' character

### ISSUE THREAD

**Issue by richardmaciel-canonical** [ComplianceAsCode/content#7155]
#### Description of problem:
Consider the `database` parameter of the aide.conf configuration file, which is in the format `<key>:<value>`.

Now, the `<key>` itself can be something like `database=file`, with the `:` char as a separator and a path as a `<value>`.

E.g.: `database=file:/var/lib/aide.db`

To use the `replace_or_append` function, you fill the parameters as the following:

`replace_or_append '/etc/aide/aide.conf' '^database=file' '/var/lib/aide.db' '@CCENUM@' '%s:%s'`

when you execute it, the generated line will be like:
`databasefile:/var/lib/aide.db`, with the `=` char removed.

#### SCAP Security Guide Version:
1.2.16

#### Operating System Version:
Ubuntu 20.04

#### Steps to Reproduce:

1. Create a script which includes `shared/bash_remediation_functions/replace_or_append.sh`
2. Add line `replace_or_append '/etc/aide/aide.conf' '^database=file' '/var/lib/aide.db' '@CCENUM@' '%s:%s'` to the script
3. Execute script

#### Actual Results:
file `/etc/aide/aide.conf` contains the line `databasefile:/var/lib/aide.db`

#### Expected Results:
file `/etc/aide/aide.conf` contains the line `database=file/var/lib/aide.db`

**Comment by cipherboy** [comment]
The bug appears to be in these lines:

https://github.com/ComplianceAsCode/content/blob/master/shared/bash_remediation_functions/replace_or_append.sh#L60-L62 

But, I'm not sure as to the rationale behind them or why they were added. Perhaps they need to take `$key` into account? 

@matejak or @ggbecker  Do you have any additional context? It has been a long time since this file was added so I'm not sure if anyone remembers why :-)

**Comment by ggbecker** [comment]
Honestly I don't know why. We could try updating this remediation to use the bash jinja macro instead: `set_config_file`

As it is used here:
https://github.com/ComplianceAsCode/content/blob/5066f769a1dc041bd06e4d7196b5bd1ca1cb91d6/linux_os/guide/services/usbguard/configure_usbguard_auditbackend/bash/shared.sh#L6

Reference: https://github.com/ComplianceAsCode/content/blob/5066f769a1dc041bd06e4d7196b5bd1ca1cb91d6/shared/macros-bash.jinja#L446-L447
https://complianceascode.readthedocs.io/en/latest/jinja_macros/bash.html#template-set_config_file

**Comment by marcusburghardt** [comment]
It seems already fixed. Could you confirm @dodys ? Thanks

**Comment by dodys** [comment]
> It seems already fixed. Could you confirm @dodys ? Thanks

well, I'm not sure. The issue mentions the old `replace_or_append` which is now `bash_replace_or_append` but nevertheless we went in `aide_build_database` with our own bash script which doesn't rely on `bash_replace_or_append`, and also the shared bash script there doesn't use this bash macro. 
I'm closing this issue as for now it is not truly an issue in the mentioned rule. If this issue appears in some other rule, then we could verify it again.
