### ISSUE TITLE
RHEL 8 CIS 3.4.4.1.5 Ensure iptables is enabled and active (Automated)

### ISSUE THREAD

**Issue by alexhaydock** [ComplianceAsCode/content#7190]
Needs rule.

**Comment by alexhaydock** [comment]
Hi @yuumasato - can we add this to the "CIS for RHEL 8" project please? Thanks!

**Comment by marcusburghardt** [comment]
There is a rule: `service_iptables_enabled`

**Comment by alexhaydock** [comment]
Shouldn't this be added to the controls file before we can mark it as resolved?

https://github.com/ComplianceAsCode/content/blob/44c76e17547956494e4426d22801e67bd20d21d2/controls/cis_rhel8.yml#L1128-L1135

I think it needs to stay as non-automated, since otherwise it will conflict with control 3.4.2.1 and 3.4.2.2 which relate to firewalld.

**Comment by marcusburghardt** [comment]
Hi @alexhaydock , I just sent a PR to update the CIS RHEL8 to v2.0.0. The requirements were updated or reordered to keep alignment to v2.0.0. The next step would be to review the gaps and treat them. I saw you are providing great contributions to the CIS related rules. You are more than welcome to contribute reviewing the CIS RHEL8 coverage after this update.

**Comment by marcusburghardt** [comment]
#9154 is merged.
