### ISSUE TITLE
file_permissions_var_log failing

### ISSUE THREAD

**Issue by dodys** [ComplianceAsCode/content#7201]
#### Description of problem:
The file_permissions_var_log oval tries to validate that /var/log is 755 or less. The oval and bash are all created via template file_permissions.

```
 template:
     name: file_permissions
     vars:
         filepath: /var/log/
         filemode: '0755'
```

The current result I get in Ubuntu 18.04 is:
![image](https://user-images.githubusercontent.com/1580168/124492140-713d4c00-dd8a-11eb-8b3c-5f30634957c5.png)

The only way I got this to actually work was replacing the filepath to /var/log, without the '/' at the end.
![image](https://user-images.githubusercontent.com/1580168/124492194-82865880-dd8a-11eb-8a07-dea3afcad38b.png)

I wonder what is the correct approach when using file_permissions to check directories, should we include the '/' at the end or not.

#### SCAP Security Guide Version:

1.2.15

#### Operating System Version:

Ubuntu 18.04

#### Steps to Reproduce:

1. Build a product that includes such a rule
2. Check the result, is failing
3. Change file_permissions_var_log filepath to /var/log
4. Build again and check results

#### Actual Results:

Fail, see picture above

#### Expected Results:

Pass

#### Additional Information/Debugging Steps:

The difference between having or not the '/' in the end of the filepath is just as follows:
When passing /var/log:
```
     <unix:file_object comment="/var/log" id="object_file_permissions_var_log" version="1">
       <unix:filepath>/var/log</unix:filepath>
 
       <filter action="include">state_file_permissions_var_log_mode_not_0755</filter>
   </unix:file_object>
```

When passing /var/log/:
```
     <unix:file_object comment="/var/log/" id="object_file_permissions_var_log" version="1">
       <unix:path>/var/log/</unix:path>
       <unix:filename xsi:nil="true" />
 
       <filter action="include">state_file_permissions_var_log_mode_not_0755</filter>
   </unix:file_object>
```

**Comment by ggbecker** [comment]
I have tested this rule on a RHEL7 machine with openscap 1.2.17 and it worked with the extra slash.

I suspect it's related to: https://github.com/OpenSCAP/openscap/commit/e84dff0ca091edfe5b1c73c8836006a1d269e52e

which is not part of 1.2.15

**Comment by cipherboy** [comment]
In discussion with @dodys today, we identified the issue down to the reboot in the SSGTS profile runner: Ubuntu's rsyslog contains patches to provision `/usr/lib/tmpfiles.d/00rsyslog.conf` with contents `z /var/log 0775 root syslog -`, breaking the rule. :-)
