### ISSUE TITLE
RHEL 7 CIS kickstart installation - audit_rules_privileged_commands_* fail

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#7212]
#### Description of problem:
Rules failing after RHEL7 CIS kickstart installation:

- xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_rmmod
- xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_insmod
- xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_modprobe

#### SCAP Security Guide Version:
958709e

#### Operating System Version:
RHEL 7.9

#### Steps to Reproduce:

1. Install RHEL7.9 machine with CIS security policy
2. Perform oscap scan

#### Actual Results:
audit_rules_privileged_commands_* rules fail

#### Expected Results:
audit_rules_privileged_commands_* rules pass

#### Additional Information/Debugging Steps:
The fails are pretty much the same for all three rules.
audit_rules_privileged_commands_rmmod OVAL details from HTML report:

<h4><span class="label label-primary">audit augenrules rmmod</span> 
                    <span class="label label-danger">failed</span> because these items were missing:</h4><h5>Object <strong><abbr>oval:ssg-object_rmmod_augenrules:obj:1</abbr></strong> of type
                <strong>textfilecontent54_object</strong></h5>

Filepath | Pattern | Instance
-- | -- | --
^/etc/audit/rules\.d/.*\.rules$ | ^[\s]*-w[\s]+/sbin/rmmod[\s]+-p[\s]+x[\s]+-k[\s]+modules[\s]*$ | 1

<h4><span class="label label-primary">audit auditctl rmmod</span> 
                    <span class="label label-danger">failed</span> because these items were missing:</h4><h5>Object <strong><abbr>oval:ssg-object_rmmod_auditctl:obj:1</abbr></strong> of type
                <strong>textfilecontent54_object</strong></h5>

Filepath | Pattern | Instance
-- | -- | --
/etc/audit/audit.rules | ^[\s]*-w[\s]+/sbin/rmmod[\s]+-p[\s]+x[\s]+-k[\s]+modules[\s]*$ | 1

**Comment by ggbecker** [comment]
These rules don't have `bash` remediation. So I think they are not getting remediated at all.

**Comment by mildas** [comment]
@ggbecker Good point. But I'd say they should have remediation so it is valid issue.
