### ISSUE TITLE
RHEL 8 HIPAA/OSPP/STIG/CUI kickstart installation - disable_ctrlaltdel_reboot fail

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#7213]
#### Description of problem:
The `disable_ctrlaltdel_reboot` rule is failing after installing RHEL8 using HIPAA security policy.

#### SCAP Security Guide Version:
958709e

#### Operating System Version:
RHEL 8

#### Steps to Reproduce:

1. Install RHEL 8 with HIPAA security policy
2. Scan the machine with openscap

#### Actual Results:
disable_ctrlaltdel_reboot fails

#### Expected Results:
disable_ctrlaltdel_reboot passes

#### Additional Information/Debugging Steps:
OVAL details from HTML report:
<h4><span class="label label-primary">Disable Ctrl-Alt-Del key sequence override exists</span> 
        <span class="label label-default">oval:ssg-test_disable_ctrlaltdel_exists:tst:1</span> 
        <span class="label label-danger">false</span></h4><h5>Following items have been found on the system:</h5>

Filepath | Canonical path
-- | --
/etc/systemd/system/ctrl-alt-del.target | /usr/lib/systemd/system/reboot.target

**Comment by mildas** [comment]
It happens also for OSPP, for CUI, and for STIG profiles.

**Comment by ggbecker** [comment]
@mildas  This should be fixed by: https://github.com/ComplianceAsCode/content/pull/7393

We have detected another problem with the rule but it should be all good now.

**Comment by mildas** [comment]
@ggbecker Okey. I found it failing in last week productization. Closing it again
