### ISSUE TITLE
Warning during build about invalid selectors in RHEL7? 

### ISSUE THREAD

**Issue by cipherboy** [ComplianceAsCode/content#7222]
#### Description of problem:

When building RHEL7 content on Ubuntu 21.04 (OpenSCAP 1.2.17) I get:

```
[598/1004] [rhel7-bash-scripts] generating Bash remediation scripts for all profiles in ssg-rhel7-xccdf.xml
OpenSCAP Error: Invalid selector 'default' for xccdf:value/@id='var_sudo_logfile'. Using null value instead. [../../../src/XCCDF_POLICY/xccdf_policy.c:2126]
Could not resolve xccdf:sub/@idref='var_sudo_logfile'! [../../../src/XCCDF_POLICY/xccdf_policy_substitute.c:107]
A fix for Rule/@id="sudo_custom_logfile" was skipped: Text substitution failed. [../../../src/XCCDF_POLICY/xccdf_policy_remediate.c:712]
OpenSCAP Error: Invalid selector 'default' for xccdf:value/@id='var_sudo_logfile'. Using null value instead. [../../../src/XCCDF_POLICY/xccdf_policy.c:2126]
Could not resolve xccdf:sub/@idref='var_sudo_logfile'! [../../../src/XCCDF_POLICY/xccdf_policy_substitute.c:107]
A fix for Rule/@id="sudo_custom_logfile" was skipped: Text substitution failed. [../../../src/XCCDF_POLICY/xccdf_policy_remediate.c:712]
OpenSCAP Error: Invalid selector 'default' for xccdf:value/@id='var_sudo_logfile'. Using null value instead. [../../../src/XCCDF_POLICY/xccdf_policy.c:2126]
Could not resolve xccdf:sub/@idref='var_sudo_logfile'! [../../../src/XCCDF_POLICY/xccdf_policy_substitute.c:107]
A fix for Rule/@id="sudo_custom_logfile" was skipped: Text substitution failed. [../../../src/XCCDF_POLICY/xccdf_policy_remediate.c:712]
OpenSCAP Error: Invalid selector 'default' for xccdf:value/@id='var_sudo_logfile'. Using null value instead. [../../../src/XCCDF_POLICY/xccdf_policy.c:2126]
Could not resolve xccdf:sub/@idref='var_sudo_logfile'! [../../../src/XCCDF_POLICY/xccdf_policy_substitute.c:107]
A fix for Rule/@id="sudo_custom_logfile" was skipped: Text substitution failed. [../../../src/XCCDF_POLICY/xccdf_policy_remediate.c:712]
[602/1004] [rhel7-playbooks] generating Ansible Playbooks for all profiles in ssg-rhel7-xccdf.xml
OpenSCAP Error: Invalid selector 'default' for xccdf:value/@id='var_sudo_logfile'. Using null value instead. [../../../src/XCCDF_POLICY/xccdf_policy.c:2126]
Could not resolve xccdf:sub/@idref='var_sudo_logfile'! [../../../src/XCCDF_POLICY/xccdf_policy_substitute.c:107]
A fix for Rule/@id="sudo_custom_logfile" was skipped: Text substitution failed. [../../../src/XCCDF_POLICY/xccdf_policy_remediate.c:712]
Invalid selector 'default' for xccdf:value/@id='var_sudo_logfile'. Using null value instead. [../../../src/XCCDF_POLICY/xccdf_policy.c:2126]
Could not resolve xccdf:sub/@idref='var_sudo_logfile'! [../../../src/XCCDF_POLICY/xccdf_policy_substitute.c:107]
A fix for Rule/@id="sudo_custom_logfile" was skipped: Text substitution failed. [../../../src/XCCDF_POLICY/xccdf_policy_remediate.c:712]
OpenSCAP Error: Invalid selector 'default' for xccdf:value/@id='var_sudo_logfile'. Using null value instead. [../../../src/XCCDF_POLICY/xccdf_policy.c:2126]
Could not resolve xccdf:sub/@idref='var_sudo_logfile'! [../../../src/XCCDF_POLICY/xccdf_policy_substitute.c:107]
A fix for Rule/@id="sudo_custom_logfile" was skipped: Text substitution failed. [../../../src/XCCDF_POLICY/xccdf_policy_remediate.c:712]
Invalid selector 'default' for xccdf:value/@id='var_sudo_logfile'. Using null value instead. [../../../src/XCCDF_POLICY/xccdf_policy.c:2126]
Could not resolve xccdf:sub/@idref='var_sudo_logfile'! [../../../src/XCCDF_POLICY/xccdf_policy_substitute.c:107]
A fix for Rule/@id="sudo_custom_logfile" was skipped: Text substitution failed. [../../../src/XCCDF_POLICY/xccdf_policy_remediate.c:712]
OpenSCAP Error: Invalid selector 'default' for xccdf:value/@id='var_sudo_logfile'. Using null value instead. [../../../src/XCCDF_POLICY/xccdf_policy.c:2126]
Could not resolve xccdf:sub/@idref='var_sudo_logfile'! [../../../src/XCCDF_POLICY/xccdf_policy_substitute.c:107]
A fix for Rule/@id="sudo_custom_logfile" was skipped: Text substitution failed. [../../../src/XCCDF_POLICY/xccdf_policy_remediate.c:712]
Invalid selector 'default' for xccdf:value/@id='var_sudo_logfile'. Using null value instead. [../../../src/XCCDF_POLICY/xccdf_policy.c:2126]
Could not resolve xccdf:sub/@idref='var_sudo_logfile'! [../../../src/XCCDF_POLICY/xccdf_policy_substitute.c:107]
A fix for Rule/@id="sudo_custom_logfile" was skipped: Text substitution failed. [../../../src/XCCDF_POLICY/xccdf_policy_remediate.c:712]
OpenSCAP Error: Invalid selector 'default' for xccdf:value/@id='var_sudo_logfile'. Using null value instead. [../../../src/XCCDF_POLICY/xccdf_policy.c:2126]
Could not resolve xccdf:sub/@idref='var_sudo_logfile'! [../../../src/XCCDF_POLICY/xccdf_policy_substitute.c:107]
A fix for Rule/@id="sudo_custom_logfile" was skipped: Text substitution failed. [../../../src/XCCDF_POLICY/xccdf_policy_remediate.c:712]
Invalid selector 'default' for xccdf:value/@id='var_sudo_logfile'. Using null value instead. [../../../src/XCCDF_POLICY/xccdf_policy.c:2126]
Could not resolve xccdf:sub/@idref='var_sudo_logfile'! [../../../src/XCCDF_POLICY/xccdf_policy_substitute.c:107]
A fix for Rule/@id="sudo_custom_logfile" was skipped: Text substitution failed. [../../../src/XCCDF_POLICY/xccdf_policy_remediate.c:712]
```

#### SCAP Security Guide Version:

`master` at daa067e2543b8db8a6f23562e4d74665717ce9aa + Eduardo's PR. 

#### Operating System Version:

Ubuntu 21.04

OpenSCAP command line tool (oscap) 1.2.17
Copyright 2009--2017 Red Hat Inc., Durham, North Carolina.

#### Steps to Reproduce:

1. Issue a complete build of all products or just RHEL 7

#### Actual Results:

See above.

#### Expected Results:

No warnings? 

#### Additional Information/Debugging Steps:

What surprises me is that a default value is present:

```
options:
    default: "/var/log/sudo.log"
```

**Comment by cipherboy** [comment]
@vojtapolasek Just for the record, I think this is caused by this line:

https://github.com/ComplianceAsCode/content/blob/master/controls/cis_rhel7.yml#L1665

**Comment by vojtapolasek** [comment]
Hm, this is peculiar. It seems that we have a problem whenever the "default" keyword is used as a value for variable. You can try it with var_system_crypto_policy. I will investigate further.

**Comment by vojtapolasek** [comment]
@jan-cerny

**Comment by jan-cerny** [comment]
When the variable files (for example https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/selinux/var_selinux_state.var) are processed and converted to XCCDF, it creates an `<xccdf:value>` element for each of the entries in the `options` dictionary in the variable file (`.var`). 


For example, from  https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/selinux/var_selinux_state.var:

```
options:
    default: enforcing
    disabled: disabled
    enforcing: enforcing
    permissive: permissive

```
is converted to

```
        <xccdf-1.2:Value id="xccdf_org.ssgproject.content_value_var_selinux_state" type="string">
          <xccdf-1.2:title xml:lang="en-US">SELinux state</xccdf-1.2:title>
          <xccdf-1.2:description xml:lang="en-US">enforcing - SELinux security policy is enforced.
<html:br/>permissive - SELinux prints warnings instead of enforcing.
<html:br/>disabled - SELinux is fully disabled.</xccdf-1.2:description>
          <xccdf-1.2:value>enforcing</xccdf-1.2:value>
          <xccdf-1.2:value selector="disabled">disabled</xccdf-1.2:value>
          <xccdf-1.2:value selector="enforcing">enforcing</xccdf-1.2:value>
          <xccdf-1.2:value selector="permissive">permissive</xccdf-1.2:value>
        </xccdf-1.2:Value>
```

You can see that the item that has `default` before the colon is converted to an element that doesn't have the `selector` attribute. The value of the element with no `selector` attribute is considered a default value of the XCCDF Value.

I guess this is done here:
https://github.com/ComplianceAsCode/content/blob/452b4c298d7eb87671c19c6cc86e42543c1a0844/ssg/build_yaml.py#L622-L624

Therefore using `default` in the `options` list in a `.var` file has a special meaning.

I don't know at this moment what is the reason for this special meaning of `default`. It's something that we should investigate and then either remove or document.

However, I think you have 2 possible workarounds:
1) Don't set `var_sudo_logfile=default` in the profile or in controls files. As a result, the default value will be used implicitly.
2) Add a new entry in `options` dict in the `var_sudo_logfile.var` with the same value after the colon but something different before the colon, eg.: `var_log_sudo: "/var/log/sudo.log"`. Then, use the `var_sudo_logfile=var_log_sudo` in the profile or in controls files. See the previous example with SELinux, there is also `enforcing` twice in the `options` dict, with 2 different selectors, one of them is `default`.

I would prefer option 2 because it's more explicit.

I think that there isn't a bug in OpenSCAP, because there is no element with `selector="default"` attribute in the file, because our build system didn't generate that, so oscap correctly prints an error that there is no such selector.

**Comment by cipherboy** [comment]
@jan-cerny What about ignoring `var=default` entries? That allows the control/profile to be explicit (we're explicitly using this variable and taking the default value) but not clutter the generated XCCDF. Just a thought. :-)

**Comment by jan-cerny** [comment]
I think that can work as well, but to do that you would have to modify whatever code is responsible for that :)

**Comment by yuumasato** [comment]
> I don't know at this moment what is the reason for this special meaning of `default`. It's something that we should investigate and then either remove or document.

I think it is a widely used undocumented way to define a default value.
I.e.: to add a value without `selector` attribute in the variable.

From the XCCDF standard,  `6.4.5.5 @selector Attribute`:

```
...
If there are multiple instances of one
of these elements within a single <xccdf:Value> element, no more than one of the instances MAY
omit the @selector attribute, and every other instance MUST have a different value specified for its
@selector attribute.
...
In the absence of any profile or tailoring actions, the default <xccdf:value> or <xccdf:complex-
value> element in an <xccdf:Value> SHALL be the one with an empty or absent @selector. If
there is no <xccdf:value> or <xccdf:complex-value> element with an empty or absent
@selector, the first <xccdf:value> or <xccdf:complex-value> element in top-down
processing of the XML SHALL be the default element.
```

The idea of ignoring the `var=default` assignment is interesting (the profile would end up with no `refine-value` elements), but I think this may mislead/confuse people when profile extension comes into play. Example:
* Profile A sets a variable to something not default. (var=a)
* Profile B, witch extends A, wants it to have the default value. (var=default)
* If the default variable assignment is ignored, profile B will not have any `refine-value` to change the variable away from what profile A assigned.
* 

>     2\. Add a new entry in `options` dict in the `var_sudo_logfile.var` with the same value after the colon but something different before the colon, eg.: `var_log_sudo: "/var/log/sudo.log"`. Then, use the `var_sudo_logfile=var_log_sudo` in the profile or in controls files. See the previous example with SELinux, there is also `enforcing` twice in the `options` dict, with 2 different selectors, one of them is `default`.

I second this.
