### ISSUE TITLE
RHEL8 STIG - configure_openssl_tls_crypto_policy fail

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#7236]
#### Description of problem:
The configure_openssl_tls_crypto_policy rule fails in RHEL8 STIG profile.

#### SCAP Security Guide Version:
452b4c2

#### Operating System Version:
RHEL 8

#### Steps to Reproduce:
1. `python3 tests/test_suite.py profile --libvirt qemu:///system test_suite_vm --datastream /tmp/ssg-rhel8-ds.xml                         --xccdf-id scap_org.open-scap_cref_ssg-rhel8-xccdf-1.2.xml --mode online --remediate-using oscap xccdf_org.ssgproject.content_profile_stig`

#### Actual Results:
`xccdf_org.ssgproject.content_rule_configure_openssl_tls_crypto_policy - fail`

#### Expected Results:
`xccdf_org.ssgproject.content_rule_configure_openssl_tls_crypto_policy - pass`

#### Additional Information/Debugging Steps:
<span class="label label-default"><abbr title="OVAL details taken from arf:report with id='oval1'">OVAL test results details</abbr></span><div class="panel panel-default"><div class="panel-body"><h4><span class="label label-primary">tests the value of MinProtocol setting in the /etc/crypto-policies/back-ends/opensslcnf.config file</span> 
        <span class="label label-default">oval:ssg-test_configure_openssl_tls_crypto_policy:tst:1</span> 
        <span class="label label-danger">false</span></h4><h5>No items have been found conforming to the following objects:</h5><h5>Object <strong><abbr>oval:ssg-obj_configure_openssl_tls_crypto_policy:obj:1</abbr></strong> of type
                <strong>textfilecontent54_object</strong></h5>

Filepath | Pattern | Instance
-- | -- | --
/etc/crypto-policies/back-ends/opensslcnf.config | ^(?:.*\n)*\s*MinProtocol\s*=\s*(.+?)[ \t]*(?:$\|#) | 1

</div></div>

**Comment by yuumasato** [comment]
@mildas Hey, I cannot reproduce this.

**Comment by mildas** [comment]
@yuumasato Interesting, I can't reproduce it with SSGTS either. But RHEL8 installation using CIS kickstart still has the problem.
