### ISSUE TITLE
Rule xccdf_org.ssgproject.content_rule_service_systemd-coredump_disabled fails to work on RHEL 9

### ISSUE THREAD

**Issue by adelton** [ComplianceAsCode/content#7248]
#### Description of problem:

Even if systemd-coredump is masked, xccdf_org.ssgproject.content_rule_service_systemd-coredump_disabled seems to fail and remediation errors.

#### SCAP Security Guide Version:

scap-security-guide-0.1.57-1.git452b4c2.el9.noarch

#### Operating System Version:

Red Hat Enterprise Linux release 9.0 Beta (Plow)

#### Steps to Reproduce:

1. `systemctl status systemd-coredump`
2. `oscap xccdf eval --remediate --profile xccdf_org.ssgproject.content_profile_ospp --rule xccdf_org.ssgproject.content_rule_service_systemd-coredump_disabled /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml`

#### Actual Results:

```
○ systemd-coredump.service
     Loaded: masked (Reason: Unit systemd-coredump.service is masked.)
     Active: inactive (dead)
```
```
WARNING: Datastream component 'scap_org.open-scap_cref_security-data-oval-com.redhat.rhsa-RHEL9.xml' points out to the remote 'https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL9.xml'. Use '--fetch-remote-resources' option to download it.
WARNING: Skipping 'https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL9.xml' file which is referenced from datastream
WARNING: Skipping ./security-data-oval-com.redhat.rhsa-RHEL9.xml file which is referenced from XCCDF content
Title   Disable acquiring, saving, and processing core dumps
Rule    xccdf_org.ssgproject.content_rule_service_systemd-coredump_disabled
Ident   CCE-83974-6
Result  fail


 --- Starting Remediation ---
WARNING: Skipping ./security-data-oval-com.redhat.rhsa-RHEL9.xml file which is referenced from XCCDF content
Title   Disable acquiring, saving, and processing core dumps
Rule    xccdf_org.ssgproject.content_rule_service_systemd-coredump_disabled
Ident   CCE-83974-6
Result  error
```

#### Expected Results:

Either the rule should be happy that the service is already masked, or it should mask it some more.

**Comment by matejak** [comment]
This is a very strange error, we mask services by default, and those coredump services are no different from any other services - they use templated check and remediation content. If you could generate an ARF and [visualize results](https://complianceascode.github.io/template/2020/08/24/visualising-the-results-of-complex-security-rules-using-oval-graph-tool.html) using oval-graph package (that should still be in the compose) - that could make things easier for us.

**Comment by matejak** [comment]
This seems to be caused by #7280 It looks like that we will need to enhance the templated check.

**Comment by ggbecker** [comment]
> This seems to be caused by #7280 It looks like that we will need to enhance the templated check.

It's probably just a matter of removing the FragmentPath check from the OVAL
