### ISSUE TITLE
v0.1.57 has no release changelog?

### ISSUE THREAD

**Issue by msmeissn** [ComplianceAsCode/content#7269]
#### Description of problem:

v0.1.57 seems tagged, but has no changelog?

#### SCAP Security Guide Version:

v0.1.57

#### Operating System Version:

SLE 15

#### Steps to Reproduce:

1. look at release tag for v0.1.57 in github here.

#### Actual Results:

empty changes

#### Expected Results:

changes similar to 0.1.56 and older

**Comment by ggbecker** [comment]
We are going through an automation of release process and the tag (draft) you are seeing is part of some tests of this automation. The final release should have a similar structure as previous releases.

**Comment by msmeissn** [comment]
ah so its not the final 0.1.57 yet?

**Comment by ggbecker** [comment]
> ah so its not the final 0.1.57 yet?

No. it's not. Sorry for the noise. I'm gonna ask around to have them deleted.

Please refer to this link for the latest release: https://github.com/ComplianceAsCode/content/releases/latest

**Comment by heryxpc** [comment]
Hi @ggbecker , is there any proximate release date containing this changes?

**Comment by ggbecker** [comment]
> Hi @ggbecker , is there any proximate release date containing this changes?

It should happen soon. We are in the stabilization phase right now where we fix critical bugs before releasing it: https://github.com/ComplianceAsCode/content/tree/stable

**Comment by vojtapolasek** [comment]
Hello,
the Stable branch contains the last released content, e.g. 0.1.56. If you want to follow the current stabilization process of the 0.1.57 release, follow the "stabilization" branch.

**Comment by ggbecker** [comment]
The draft release does not exist anymore. Closing the issue. You can expect the official release to happen very soon.
