### ISSUE TITLE
systemd not following symlinks on FragmentPath on Ubuntu

### ISSUE THREAD

**Issue by cipherboy** [ComplianceAsCode/content#7280]
#### Description of problem:

In testing with @Mab879... :-)

On a RHEL 8.4 machine (and Fedora 33 with systemd 246), the system reports the FragmentPath correctly:

```
[ladmin@localhost ~]$ systemctl --version  
systemd 239 (239-45.el8_4.2) 
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=legacy
[ladmin@localhost ~]$ sudo systemctl mask cups 
Created symlink /etc/systemd/system/cups.service → /dev/null.
[ladmin@localhost ~]$ systemctl show cups | grep FragmentPath 
FragmentPath=/dev/null
```

However, on a Ubuntu 20.04 (and Ubuntu 21.10 testing -- with `248.3-1ubuntu2`) box we don't follow FragmentPath:

```
root@ubuntu-2004-base:~# systemctl --version
systemd 245 (245.4-4ubuntu3.11)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
root@ubuntu-2004-base:~# systemctl disable cups
Synchronizing state of cups.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable cups
Removed /etc/systemd/system/multi-user.target.wants/cups.path.
Removed /etc/systemd/system/sockets.target.wants/cups.socket.
Removed /etc/systemd/system/printer.target.wants/cups.service.
root@ubuntu-2004-base:~# systemctl mask cups
Created symlink /etc/systemd/system/cups.service → /dev/null.
root@ubuntu-2004-base:~# systemctl show cups | grep -i FragmentPath
FragmentPath=/etc/systemd/system/cups.service
root@ubuntu-2004-base:~# ls -alh /etc/systemd/system/cups.service
lrwxrwxrwx 1 root root 9 Jul 23 14:26 /etc/systemd/system/cups.service -> /dev/null
```

This behavior is consistent with the results of the [OVAL probe data](https://github.com/ComplianceAsCode/content/blob/master/shared/templates/service_disabled/oval.template#L52-L54):

![Screenshot from 2021-07-23 10-27-19](https://user-images.githubusercontent.com/914030/126796781-cec709c0-a578-4ddb-bf1f-0a3dac7e6be0.png)

**Question**:

Is FragmentPath necessary in this unit? Can we remove it? Or should we resolve it to a path (following symlinks) and only compare the followed version?

#### SCAP Security Guide Version:

`master`

#### Operating System Version:

RHEL 8.4, Fedora 33, Ubuntu 20.04

#### Steps to Reproduce:

1. Install cups package
2. `systemctl disable cups`
3. `systemctl mask cups`
4. `systemctl show cups | grep FragmentPath`

#### Actual Results:

`/etc/systemd/system/cups.service` on Ubuntu, causing the OVAL check to fail.

#### Expected Results:

`/dev/null` or OVAL check to pass.

**Comment by richardmaciel-canonical** [comment]
As we discussed, I do think this should be treated as a difference between distros with the proper macro selecting code. My reasoning is: if the issue is actually a bug, it's a low priority one, thus the responsibles will take a lot of time to make the fix available.

**Comment by Mab879** [comment]
This appears to be the same on F34.
```

$ cat /etc/redhat-release 
Fedora release 34 (Thirty Four)
```


```
$ systemctl --version
systemd 248 (v248.6-1.fc34)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
```
```
$ ls -alh /etc/systemd/system/cups.service
lrwxrwxrwx. 1 root root 9 Jul 27 08:23 /etc/systemd/system/cups.service -> /dev/null
```
```
$ systemctl show cups | grep FragmentPath
FragmentPath=/etc/systemd/system/cups.service

```

**Comment by matejak** [comment]
I can confirm this - it is probably also affecting RHEL9.

**Comment by Mab879** [comment]
Just as you suspected @matejak RHEL9 has this issue as well.

**Comment by cipherboy** [comment]
@matejak Interestingly though, that bug isn't marked as closed. I wonder if it was intentionally fixed or not? Might be worth someone at Red Hat asking some systemd folks...  :-) Still, I agree with @ggbecker's call to remove FragmentPath check, I've done something similar internally already. Seems easier than updating OpenSCAP or systemd...
