### ISSUE TITLE
Rules enable_fips_mode, enable_dracut_fips_module, and other commented out with not supported in RHEL9 ATM

### ISSUE THREAD

**Issue by adelton** [ComplianceAsCode/content#7282]
#### Description of problem:

When the RHEL 9 ospp.profile file was created in https://github.com/ComplianceAsCode/content/commit/215db1bbe08fdaf1139f563abf9515e8a15a6457, many of the rules got commented out with `not supported in RHEL9 ATM` message, among others

```
products/rhel9/profiles/ospp.profile:#    - enable_fips_mode  # not supported in RHEL9 ATM
products/rhel9/profiles/ospp.profile:#    - enable_dracut_fips_module  # not supported in RHEL9 ATM
```

Was there a specific reason (some tests failing?) for not having the RHEL 9 content en-par with RHEL 8 ospp.profile? What is the intended process to get these rules re-enabled?

#### SCAP Security Guide Version:

Master and scap-security-guide-0.1.57-1.git382b1ab.el9.noarch.rpm.

#### Operating System Version:

RHEL 9.

#### Steps to Reproduce:

1. `oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_ospp --rule xccdf_org.ssgproject.content_rule_enable_fips_mode /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml`

#### Actual Results:

```
WARNING: Datastream component 'scap_org.open-scap_cref_security-data-oval-com.redhat.rhsa-RHEL9.xml' points out to the remote 'https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL9.xml'. Use '--fetch-remote-resources' option to download it.
WARNING: Skipping 'https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL9.xml' file which is referenced from datastream
WARNING: Skipping ./security-data-oval-com.redhat.rhsa-RHEL9.xml file which is referenced from XCCDF content
OpenSCAP Error: Rule 'xccdf_org.ssgproject.content_rule_enable_fips_mode' not found in selected profile. [/builddir/build/BUILD/openscap-1.3.5/src/XCCDF_POLICY/xccdf_policy.c:2105]
```

#### Expected Results:

No OpenSCAP Error, clean Pass or Fail result.

**Comment by adelton** [comment]
Note that indeed, FIPS mode might prevent OpenSSL 3 from operating correctly (https://bugzilla.redhat.com/show_bug.cgi?id=1977318) so before enabling the rules, the impact needs to be tested.

Here I was primarily looking for the plan and process for re-enabling those rules (or removing them from RHEL 9 profile altogether).

**Comment by matejak** [comment]
Some rules were switched on by #7147, and the remaining ones will be handled and backported later. Those rules are mostly likely valid and applicable for RHEL9 with no to minor modifications.

**Comment by adelton** [comment]
The rules have been added via https://github.com/ComplianceAsCode/content/pull/7147 (and cherry picked to the stabilization branch via https://github.com/ComplianceAsCode/content/commit/3ce05d0103205b660149b31fd789367e94e4f432) but some of them fail to remediate. I've now filed the issues as
 
- https://bugzilla.redhat.com/show_bug.cgi?id=1987220
  -  enable_fips_mode
  - enable_dracut_fips_module
- https://bugzilla.redhat.com/show_bug.cgi?id=1987226
  - disable_ctrlaltdel_burstaction
- https://bugzilla.redhat.com/show_bug.cgi?id=1987227
  - configure_bashrc_exec_tmux
  - configure_tmux_lock_after_time
  - configure_tmux_lock_command
  - no_tmux_in_shells
- https://bugzilla.redhat.com/show_bug.cgi?id=1987231
  - grub2_uefi_password
