### ISSUE TITLE
RHEL8 STIG - service_auditd_enabled fail (pass in remediation phase, fail in final check)

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#7292]
#### Description of problem:
The `service_auditd_enabled` rule check fails after remediating a machine with STIG profile and restarting it.

#### SCAP Security Guide Version:
7eb7ef1

#### Operating System Version:
RHEL 8

#### Steps to Reproduce:
1. `python3 tests/test_suite.py profile --libvirt qemu:///system test_suite_vm --datastream /tmp/ssg-rhel8-ds.xml --xccdf-id scap_org.open-scap_cref_ssg-rhel8-xccdf-1.2.xml --mode online --remediate-using oscap xccdf_org.ssgproject.content_profile_stig`

#### Actual Results:
xccdf_org.ssgproject.content_rule_service_auditd_enabled - fail 

#### Expected Results:
xccdf_org.ssgproject.content_rule_service_auditd_enabled - pass 

#### Additional Information/Debugging Steps:
In the remediation phase, it shows the rule passed (package installed and service is active). However, in the final phase, after machine restart, it fails (audit package is installed, but the service is not running).

It might be that some audit configuration breaks it and it can't be started.

**Comment by freddieRv** [comment]
On OL7, the rule `auditd_overflow_action` breaks the auditd daemon after a reboot because the config option `overflow_action` is not supported. This might be an issue with the specific OL7 audit RPM though. The same option is supported on the audit shipped with OL8.

**Comment by ggbecker** [comment]
I believe these following changes fix the issue described originally here:

https://github.com/ComplianceAsCode/content/pull/6910

https://github.com/ComplianceAsCode/content/pull/6910/files#diff-6518a0e9b97463fd5d2a337b46c053367785594713c979dab64d0f6e0363bf2d

https://github.com/ComplianceAsCode/content/pull/6910/files#diff-6d36e8d97141aafdfd999784156ba4ff387d3c4a6ac9594198bfc3d059b0fc3c

It was basically a syntax error when editing the `/etc/audit/audit.conf` file which caused the service to fail when starting.

Can you double check it @mildas
