### ISSUE TITLE
SLE15 STIG wrong id assigned

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#7328]
https://github.com/ComplianceAsCode/content/blob/7dbbee025f83ceb0d5dd5be0465022b9ed7de9db/linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_mount/rule.yml#L50

@brett060102 I believe this reference actually belongs to: https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_media_export/rule.yml

**Comment by teacup-on-rockingchair** [comment]
Thanks @ggbecker :bow: will try to handle it as soon as possible

**Comment by teacup-on-rockingchair** [comment]
I think we have same problem with SLES-15-030360 in https://github.com/ComplianceAsCode/content/blob/7dbbee025f83ceb0d5dd5be0465022b9ed7de9db/linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_umount/rule.yml#L58, so will try to handle both in same context
