### ISSUE TITLE
RHEL 8 CIS 5.2.15 Ensure SSH warning banner is configured (Automated)

### ISSUE THREAD

**Issue by alexhaydock** [ComplianceAsCode/content#7336]
Needs rule.

The current `sshd_enable_warning_banner` rule is insufficient for the RHEL 8 CIS profile, as it configures the sshd warning banner to use `/etc/issue` instead of `/etc/issue.net` which the benchmark demands.

Potentially this could be resolved by tweaking the above rule to use a var to hold the value of the Banner file path on disk?

**Comment by marcusburghardt** [comment]
Already solved with the `sshd_enable_warning_banner_net` rule.
