### ISSUE TITLE
RHEL 8 CIS 5.4.2 Ensure lockout for failed password attempts is configured (Automated)

### ISSUE THREAD

**Issue by alexhaydock** [ComplianceAsCode/content#7337]
Needs rule.

Previously, we were using the following rules to implement this control but they do not align perfectly with the benchmark:
      - accounts_passwords_pam_faillock_deny
      - accounts_passwords_pam_faillock_unlock_time
      - var_accounts_passwords_pam_faillock_deny=5
      - var_accounts_passwords_pam_faillock_unlock_time=900

**Comment by marcusburghardt** [comment]
All `pam_faillock.so` related rules were already refactored.
