### ISSUE TITLE
RHEL-08-020041 is not implemented in a way to support the discussion

### ISSUE THREAD

**Issue by jharmison-redhat** [ComplianceAsCode/content#7341]
#### Description of problem:
The discussion of the vulnerability in the SRG/STIG is related to session timeouts and locking. The first paragraph in the new Ver 1, Rel 3 STIG reads:
> A session lock is a temporary action taken when a user stops work and moves away from the immediate physical vicinity of the information system but does not want to log out because of the temporary nature of the absence.

If I, as a user of a STIGged RHEL 8 system, SSH to a system and stay idle for 900 seconds, my session times out and I am disconnected (good). If I SSH back to the system after some period of time, I am provided with a new tmux session. Trying to attach to my old session (using `tmux att -t 0` for example), I am warned about nesting tmux sessions. I could execute a more complicated series of commands to identify the windows/panes on the other session and move them to my new session, killing the old session, but this does not seem like the expected level of effort when returning from a temporary absence.

#### SCAP Security Guide Version:
0.1.54-5.el8

#### Operating System Version:
RHEL 8.4

#### Steps to Reproduce:

1. Install a RHEL 8 system and apply the latest STIG profile at installation time
2. SSH to the machine, perform some action (ex. `less /etc/os-release`)
3. Wait 900 seconds for the timeout to disconnect you
4. SSH back to the machine

#### Actual Results:
You are dropped into a fresh session. You can execute `tmux ls` to see current tmux sessions, including the original one that still has `less` open.

#### Expected Results:
You are dropped back into the same session and can page your way around the file you were using.

#### Additional Information/Debugging Steps:
In order to have the experience better match the expected results, I propose two changes.

##### /etc/tmux.conf
Add the line `new-session -n $HOST`

##### /etc/bashrc
Change the `exec tmux` command to `exec tmux attach` - The recent STIG revision and the current SSG implementations differ on the conditions that cause us to exec into tmux, but they both use simply `exec tmux`.

With those two settings applied, tmux will always try to attach to an existing session if there is one, or create a new session if there is not one (and automatically attach to it). This isn't conducive to more advanced tmux usage broadly as it can interfere with session management for more advanced users, but is a simple way to implement what I believe to be the expected behavior based on the discussion.

**Comment by Mab879** [comment]
tmux is no longer in the RHELE 8 STIG, closing.
