### ISSUE TITLE
SLES15 STIG umount syscall on 64bit

### ISSUE THREAD

**Issue by apatard** [ComplianceAsCode/content#7386]
#### Description of problem:

The check for audit record of umount syscall is failing (rule SLES-15-030360).
From what I understand, it's looking for the umount syscall on 32 bits and 64 bits.
Except that the STIG manual is asking to check sys_umount only on 32bits and
for a good reason: it doesn't exist on 64bits.
See https://marcin.juszkiewicz.com.pl/download/tables/syscalls.html for instance.

SLES 15 STIG V1R3 Manual:
```
Check that the system calls are being audited by performing the following command:

> sudo auditctl -l | grep 'umount'

-a always,exit -F arch=b32 -S umount -F auid>=1000 -F auid!=-1 -k privileged-umount
-a always,exit -F arch=b32 -S umount2 -F auid>=1000 -F auid!=-1 -k privileged-umount
-a always,exit -F arch=b64 -S umount2 -F auid>=1000 -F auid!=-1 -k privileged-umoun
```

#### SCAP Security Guide Version:

0.1.57

#### Operating System Version:

SLES15SP2

#### Steps to Reproduce:

1. Download and extract latest release on a sles15 with SLES15 STIG rules applied. In particular
```
# grep umount /etc/audit/rules.d/01-stig.rules
-a always,exit -F arch=b32 -S umount -F auid>=1000 -F auid!=4294967295 -k privileged-umount
-a always,exit -F arch=b32 -S umount2 -F auid>=1000 -F auid!=4294967295 -k privileged-umount
-a always,exit -F arch=b64 -S umount2 -F auid>=1000 -F auid!=4294967295 -k privileged-umount
```
2. Run the bench, for instance with:
```
# oscap xccdf eval \
    --fetch-remote-resources \
    --profile xccdf_org.ssgproject.content_profile_stig \
    --report /tmp/report.html ssg-sle15-ds.xml
```

#### Actual Results:

Look at the results and notice that the check for SLES-15-030360 is failing

#### Expected Results:

Check to succeed

**Comment by ggbecker** [comment]
@brett060102 I believe this rule needs to have custom OVAL/remediation https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_umount/rule.yml#L39

and this rule should be removed: https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/auditing/auditd_configure_rules/audit_dac_actions/audit_rules_dac_modification_umount/rule.yml#L39

according to SLE STIG you should check for:
```
-a always,exit -F arch=b32 -S umount -F auid>=1000 -F auid!=4294967295 -k privileged-umount
-a always,exit -F arch=b32 -S umount2 -F auid>=1000 -F auid!=4294967295 -k privileged-umount
-a always,exit -F arch=b64 -S umount2 -F auid>=1000 -F auid!=4294967295 -k privileged-umount
```

b32 -> umount and umount2
b64 -> umount2

**Comment by brett060102** [comment]
@rumch-se @teacup-on-rockingchair @abergmann please look at this as well.

**Comment by teacup-on-rockingchair** [comment]
Definitely my bad here, thanks :bow: .
One question to @ggbecker , I understand and agree that we need to use custom oval checks and remediation in order to match the specifics of the umount call, but I didn't understand what should be removed , it seems to me that the same reference is used in the comment above. Thanks once again :bow:

**Comment by apatard** [comment]
From what I understand, the current check is currently looking for something like :
```
-a always,exit -F arch=b32 -S umount -F auid>=1000 -F auid!=-1 -k privileged-umount
-a always,exit -F arch=b64 -S umount -F auid>=1000 -F auid!=-1 -k privileged-umount
```
but it should check only for :
```
-a always,exit -F arch=b32 -S umount -F auid>=1000 -F auid!=-1 -k privileged-umount
```
