### ISSUE TITLE
SLES15 STIG "Record Unsuccessul Delete Attempts to Files"

### ISSUE THREAD

**Issue by apatard** [ComplianceAsCode/content#7387]
#### Description of problem:

The current check done for the following SLES15 STIG rules is partial :

- SLES-15-030710,
- SLES-15-030720,
- SLES-15-030730,
- SLES-15-030740,
- SLES-15-030750.

The STIG manual for SLES15 is asking to log **all** usages of the syscall, not only ``EACCESS``/``EPERM``.

For instance, SLES-15-030710:
```
Check that the system call is being audited by performing the following command:

> sudo auditctl -l | grep -w 'rename'

-a always,exit -F arch=b32 -S rename -F auid>=1000 -F auid!=-1 -k perm_mod
-a always,exit -F arch=b64 -S rename -F auid>=1000 -F auid!=-1 -k perm_mod
```

#### SCAP Security Guide Version:

0.1.57

#### Operating System Version:

SLES15SP2

#### Steps to Reproduce:

1. Download and extract latest release on a sles15 with SLES15 STIG rules applied. In particular:
```
# vim /etc/audit/rules.d/audit.rules
...
-a always,exit -F arch=b32 -S rename -F auid>=1000 -F auid!=4294967295 -k perm_mod
-a always,exit -F arch=b64 -S rename -F auid>=1000 -F auid!=4294967295 -k perm_mod
```
2. Run the bench, for instance with:
```
# oscap xccdf eval \
    --fetch-remote-resources \
    --profile xccdf_org.ssgproject.content_profile_stig \
    --report /tmp/report.html ssg-sle15-ds.xml
```

#### Actual Results:

The checks for the mentioned rules are failing

#### Expected Results:

The checks should succeed.

**Comment by ggbecker** [comment]
It looks like the identifiers were wrongly assigned to these rules, we already have rules that supposedly to the correct check, for example the `rename`: https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/auditing/auditd_configure_rules/audit_file_deletion_events/audit_rules_file_deletion_events_rename/rule.yml

@brett060102 you may want to take a look at this

**Comment by apatard** [comment]
fwiw, I've started writing something for this issue and it's available at https://github.com/apatard/content/tree/renameat. For the renameat2 syscall, I've copied it from renameat. This means that the descriptions / IDs are probably wrong and i've yet to run the testsuite but the tests are now the right ones.
[ That's why there's no PR ].

**Comment by marcusburghardt** [comment]
@teacup-on-rockingchair , perhaps this issue is already fixed?

**Comment by teacup-on-rockingchair** [comment]
> @teacup-on-rockingchair , perhaps this issue is already fixed?

will double-check it and handle it thanks

**Comment by teacup-on-rockingchair** [comment]
Currently SLES-15-030740 stig id is used for:
- audit_rules_unsuccessful_file_modification_unlink
- audit_rules_unsuccessful_file_modification_unlinkat
- audit_rules_unsuccessful_file_modification_rename
- audit_rules_unsuccessful_file_modification_renameat
- audit_rules_unsuccessful_file_modification_renameat2

After all of the above are remediated the configration audit file looks like:
```
-a always,exit -F arch=b32 -S renameat2 -S renameat -S rename -S unlink -S unlinkat -F exit=-EACCES -F auid>=1000 -F auid!=unset -F key=access
-a always,exit -F arch=b64 -S renameat2 -S renameat -S rename -S unlink -S unlinkat -F exit=-EACCES -F auid>=1000 -F auid!=unset -F key=access
-a always,exit -F arch=b32 -S renameat2 -S renameat -S rename -S unlink -S unlinkat -F exit=-EPERM -F auid>=1000 -F auid!=unset -F key=access
-a always,exit -F arch=b64 -S renameat2 -S renameat -S rename -S unlink -S unlinkat -F exit=-EPERM -F auid>=1000 -F auid!=unset -F key=access
```

,and with the above configuration oval checks for all of the 5 rules are passing
