### ISSUE TITLE
`sshd_set_maxstartups` does not use the variable `var_sshd_set_maxstartups` in the OVAL check

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#7399]
The OVAL check has a static value and it probably needs to be updated to use the XCCDF variable

https://github.com/ComplianceAsCode/content/blob/77e3267f60135ba74e66609b9e89037b3c71cc1e/linux_os/guide/services/ssh/ssh_server/sshd_set_maxstartups/oval/shared.xml#L42

cc @alexhaydock

**Comment by ggbecker** [comment]
This can be used as an example:
https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/services/ssh/ssh_server/sshd_use_approved_macs/oval/shared.xml#L57

**Comment by cipherboy** [comment]
@ggbecker Yeah, this was work I had originally been meaning to take... Let's see if I get to it in the last couple of days. :/
