### ISSUE TITLE
sshd_lineinfile template is using wrong ssh_config.d filename

### ISSUE THREAD

**Issue by comps** [ComplianceAsCode/content#7408]
#### Description of problem:

```
$ grep 'sshd_config.d/hardening' -R *
shared/templates/sshd_lineinfile/bash.template:touch /etc/ssh/sshd_config.d/hardening
shared/templates/sshd_lineinfile/bash.template:        path="/etc/ssh/sshd_config.d/hardening",
```
The file should be called `<number>-hardening.conf` as the order of files in `ssh_config.d` matters and only files with `.conf` are included:
```
# grep Include /etc/ssh/sshd_config
Include /etc/ssh/sshd_config.d/*.conf
```

#### SCAP Security Guide Version:
Latest master, 9bdb45c683.

#### Operating System Version:
RHEL-9 / Fedora

**Comment by ggbecker** [comment]
Update https://github.com/ComplianceAsCode/content/blob/9bdb45c683fc7a31392ea04f5861fc51e842e0bd/shared/templates/sshd_lineinfile/bash.template#L15

to something like:

`path="/etc/ssh/sshd_config.d/00-hardening.conf", `

**Comment by matejak** [comment]
That name really sucks, so what about `60-redhat_hardening.conf` as there is `50-redhat.conf` already?

**Comment by comps** [comment]
Note that you might need to comment out those options in `sshd_config` during remediation, and definitely use lower numbers as, for most options, the first occurence applies and others are ignored.

**Comment by ggbecker** [comment]
> That name really sucks, so what about `60-redhat-hardening.conf` as there is `50-redhat.conf` already?

embedding `redhat` to the filename doesn't seem to be the best solution from a community POV. So far it's only enabled on Fedora and RHEL9, but in future it can be enabled in more platforms.

**Comment by ggbecker** [comment]
> Note that you might need to comment out options changed by this file in `sshd_config` during remediation, and definitely use lower numbers as, for most options, the first occurence applies and others are ignored.

This should be done by the following lines if I'm not mistaken https://github.com/ComplianceAsCode/content/blob/9bdb45c683fc7a31392ea04f5861fc51e842e0bd/shared/templates/sshd_lineinfile/bash.template#L12-L13

but they completely remove the lines instead of commenting out.

**Comment by matejak** [comment]
> embedding `redhat` to the filename doesn't seem to be the best solution from a community POV. So far it's only enabled on Fedora and RHEL9, but in future it can be enabled in more platforms.

We could apply Jinja magic to use `redhat` on RHELs, but you are right, we could save ourselves some energy and have `60-complianceascode-hardening.conf` (the 60 or whatever else number may also cause issues though).
