### ISSUE TITLE
TASK [RedHatOfficial.rhel8_stig : Set gpgcheck=1 for each yum repo - Unexpected templating type error

### ISSUE THREAD

**Issue by crayroot** [ComplianceAsCode/content#7416]
#### Description of problem:
TASK [RedHatOfficial.rhel8_stig : Set gpgcheck=1 for each yum repo] **************************************************************************************************************************
task path: /root/.ansible/roles/RedHatOfficial.rhel8_stig/tasks/main.yml:3328
fatal: [10.192.13.136]: FAILED! => {
    "msg": "Unexpected templating type error occurred on ({{ repo_grep_results.stdout | regex_findall( '(.+\\\\.repo):\\\\[(.+)\\\\]\\\\n?' ) }}): expected string or buffer"
}

#### SCAP Security Guide Version:
DISA STIG for Red Hat Enterprise Linux 8 V1R2

#### Operating System Version:
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.4 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.4:GA"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.4"

#### Steps to Reproduce:

1. Launch RHEL 8 AMI in AWS (ami-0cca63ccd9a87f1b2 (64-bit x86)
2. Create playbook/hosts file specifying RedHatOfficial.rhel8_stig role
3. Execute playbook
4. Task failure in description is seen

#### Actual Results:
TASK [RedHatOfficial.rhel8_stig : Set gpgcheck=1 for each yum repo] **************************************************************************************************************************
task path: /root/.ansible/roles/RedHatOfficial.rhel8_stig/tasks/main.yml:3328
fatal: [10.192.13.136]: FAILED! => {
    "msg": "Unexpected templating type error occurred on ({{ repo_grep_results.stdout | regex_findall( '(.+\\\\.repo):\\\\[(.+)\\\\]\\\\n?' ) }}): expected string or buffer"
}

PLAY RECAP ***********************************************************************************************************************************************************************************
10.192.13.136              : ok=108  changed=72   unreachable=0    failed=1    skipped=11   rescued=0    ignored=0

#### Expected Results:
I would assume additional tasks would be completed and the playbook would finish.

**Comment by marcusburghardt** [comment]
It should be ok in the current version of RedHatOfficial.rhel8_stig.
