### ISSUE TITLE
Missing task/rule for RHEL-07-010118

### ISSUE THREAD

**Issue by Apteryks** [ComplianceAsCode/content#7419]
## Which products and profiles does the rule apply to?

RHEL7 STIG

## Describe the configuration setting enforced by this rule.
The Red Hat Enterprise Linux operating system must be configured so that /etc/pam.d/passwd implements /etc/pam.d/system-auth when changing passwords.

## Why is the configuration security relevant?
Pluggable authentication modules (PAM) allow for a modular approach to integrating authentication methods. PAM operates in a top-down processing model and if the modules are not listed in the correct order, an important security function could be bypassed if stack entries are not centralized.

## How to check the configuration?
Verify that /etc/pam.d/passwd is configured to use /etc/pam.d/system-auth when changing passwords:
```
# cat /etc/pam.d/passwd | grep -i substack | grep -i system-auth
password     substack     system-auth
```
If no results are returned, the line is commented out, this is a finding.

### Is it order dependent? (does it need to be at certain place in the file?)
No.

### What is correct and incorrect syntax?
Correct: 
password     substack    system-auth

Incorrect: missing or different value.

## How to remediate
Add the following line (or modify an existing one with the values below) to /etc/pam.d/system-auth:
```
password     substack    system-auth
```
### Does any command need to be run?

Grep/sed?

## Are there going to be other rules like this one in the future? Is it worth creating template? (similar configuration format, similar remediation process...)

No.

## Are there any caveats to be considered when testing?

No, AFAICT.

## Is the configuration loaded directly by the <software> or is it stored in some intermediate database (similar to dconf)? (We want to edit the lowest level possible, if appropriate)

Stored directly.

## Is it possible to check / remediate this configuration in offline mode? (scanning containers or offline systems)

This option can be checked in offline mode.

##  Please provide security policy references if possible e.g. STIG
RHEL-07-010118

**Comment by marcusburghardt** [comment]
The rule is implemented:
https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-pam/password_quality/passwd_system-auth_substack/rule.yml

Relates to https://github.com/ComplianceAsCode/content/issues/3371
