### ISSUE TITLE
Missing check for RHEL-07-010240 (minimum password lifetime)

### ISSUE THREAD

**Issue by Apteryks** [ComplianceAsCode/content#7423]
## Which products and profiles does the rule apply to?

RHEL

## Describe the configuration setting enforced by this rule.
The Red Hat Enterprise Linux operating system must be configured so that passwords are restricted to a 24 hours/1 day minimum lifetime.

## Why is the configuration security relevant?
Enforcing a minimum password lifetime helps to prevent repeated password changes to defeat the password reuse or history enforcement requirement. If users are allowed to immediately and continually change their password, the password could be repeatedly changed in a short period of time to defeat the organization's policy regarding password reuse.

## How to check the configuration?
Check whether the minimum time period between password changes for each user account is one day or greater.
```
# awk -F: '$4 < 1 {print $1 " " $4}' /etc/shadow
```
If any results are returned that are not associated with a system account, this is a finding.

### Is it order dependent? (does it need to be at certain place in the file?)
No.

### What is correct and incorrect syntax?
Correct: time period >= 24 hours, associated with system account
Incorrect time period <= 24 hours or not associated with system account

## How to remediate
Configure non-compliant accounts to enforce a 24 hours/1 day minimum password lifetime:

### Does any command need to be run?
```
# chage -m 1 [user]
```

## Are there going to be other rules like this one in the future? Is it worth creating template? (similar configuration format, similar remediation process...)
I don't know.

## Are there any caveats to be considered when testing?
If any results are returned that are not associated with a system account, this is a finding.

## Is it possible to check / remediate this configuration in offline mode? (scanning containers or offline systems)
Yes.
##  Please provide security policy references if possible e.g. STIG
RHEL-07-010240

**Comment by marcusburghardt** [comment]
Here is the relevant rule which needs an OVAL check:

https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_set_min_life_existing/rule.yml#L34

**Comment by marcusburghardt** [comment]
https://github.com/ComplianceAsCode/content/pull/7183
