### ISSUE TITLE
Missing check for RHEL-07-010260 (maximum pw lifetime for existing users)

### ISSUE THREAD

**Issue by Apteryks** [ComplianceAsCode/content#7424]
## Which products and profiles does the rule apply to?
RHEL
## Describe the configuration setting enforced by this rule.
The Red Hat Enterprise Linux operating system must be configured so that existing passwords are restricted to a 60-day maximum lifetime.

## Why is the configuration security relevant?
Any password, no matter how complex, can eventually be cracked. Therefore, passwords need to be changed periodically. If the operating system does not limit the lifetime of passwords and force users to change their passwords, there is the risk that the operating system passwords could be compromised.

## How to check the configuration?
Check whether the maximum time period for existing passwords is restricted to 60 days.
```
# awk -F: '$5 > 60 {print $1 " " $5}' /etc/shadow
```
If any results are returned that are not associated with a system account, this is a finding.

### Is it order dependent? (does it need to be at certain place in the file?)
No.

### What is correct and incorrect syntax?
The values returned by the above check commands should be > 60.
Incorrect: < 60.

## How to remediate
Configure non-compliant accounts to enforce a 60-day maximum password lifetime restriction.

### Does any command need to be run?

```
# chage -M 60 [user]
```
## Are there going to be other rules like this one in the future? Is it worth creating template? (similar configuration format, similar remediation process...)
No.
## Are there any caveats to be considered when testing?
None.

## Is the configuration loaded directly by the <software> or is it stored in some intermediate database (similar to dconf)? (We want to edit the lowest level possible, if appropriate)
Directly.

## Is it possible to check / remediate this configuration in offline mode? (scanning containers or offline systems)
Yes.

##  Please provide security policy references if possible e.g. STIG
RHEL-07-010260

**Comment by marcusburghardt** [comment]
https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_set_max_life_existing/rule.yml#L33

**Comment by marcusburghardt** [comment]
Covered in this PR: https://github.com/ComplianceAsCode/content/pull/7183
