### ISSUE TITLE
Ansible RHEL STIG usability issue w.r.t. task names

### ISSUE THREAD

**Issue by Apteryks** [ComplianceAsCode/content#7433]
#### Description of problem:
Many tasks are nested in in Ansible 'block's. Unfortunately Ansible does not print out the block name, so for example all we see in the output for the DISA-STIG-RHEL-07-010300 associated block named "Disable SSH Access via Empty Passwords" is:

```
TASK [RedHatOfficial.rhel7_stig : Check for duplicate values] ******************************************************************************************************************************************************
ok: [hmg]

TASK [RedHatOfficial.rhel7_stig : Deduplicate values from /etc/ssh/sshd_config] ************************************************************************************************************************************
skipping: [hmg]

TASK [RedHatOfficial.rhel7_stig : Insert correct line to /etc/ssh/sshd_config] *************************************************************************************************************************************
```

Which is indifferentiable from the output of DISA-STIG-RHEL-07-010470 (the block named "Disable Host-Based Authentication").

#### Steps to Reproduce:

1. Run the official redhatofficial.rhel7_stig playbook.

#### Actual Results:
See above.

#### Expected Results:
The block name should be part of the nested task name so they can be linked to the task block that emitted them.  Also see: https://github.com/ComplianceAsCode/content/issues/7418

**Comment by marcusburghardt** [comment]
There is already Style Guide for Ansible remediation and one rule is about Task Names prefix, which should solve this kind of issue.
- https://complianceascode.readthedocs.io/en/latest/manual/developer/04_style_guide.html#ansible

However, existing Ansible remediations are being gradually updated.
Any contribution would be welcome. I am closing this issue now.
