### ISSUE TITLE
Improve CCE expansion in remediations

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#7446]
#### Description of problem:
During @j-ode 's work on #7378 we found that a lot of bash remeditations use the string `@CCENUM@`.

The `@CCENUM@` is a string that is replaced at a later phase of the build process by the rule CCE number. It's done by the XSLT template `/shared/transforms/xccdf-addremediations.xslt` on lines 68 - 81. Notice that in `/build/<product>/fixes/bash` you will see the `@CCENUM@` string, but in the generated SCAP source data stream (`ssg-<product>-ds.xml`) you will see that it got replaced by the rule's CCE number. Or, it's replaced by an empty string if the rule doesn't have a CCE number. For example, in Fedora we don't assign CCEs.

I think that the mechanism isn't transparent and it was surprising that something modifies the remediation. I think that the same resul could be achieved using Jinja macros which are our preferred mechanism for text expansion.

Also, the Jinja macro `bash_replace_or_append` should be changed to not have the `cce` parameter because the macro is always called with this parameter set to `@CCENUM@`.

#### SCAP Security Guide Version:
current upstream as of 2021-08-23

#### Operating System Version:
all

#### Steps to Reproduce:

1. use `@CCENUM@` in a bash remediation script.
2. build content
3. see the generated code in `/build/fixes/<product>/bash`
4. see the generated SCAP source data stream, eg. ssg-rhel8-ds.xml
5. compare step 3 with step 4

#### Actual Results:
`@CCENUM@` is used to put the CCE number into the remediation body

#### Expected Results:
a documented Jinja macro can be used to put the CCE number into the remediation body

#### Additional Information/Debugging Steps:
no

**Comment by Mab879** [comment]
#5608 might be related

**Comment by jan-cerny** [comment]
Fixed in #7657
