### ISSUE TITLE
shared/templates/mount_option_removable_partitions/bash.template should not return

### ISSUE THREAD

**Issue by msmeissn** [ComplianceAsCode/content#7459]
#### Description of problem:

shared/templates/mount_option_removable_partitions/bash.template
emits during shell script mitigation:

"return can only return from a function or resourced script.

The "return 1" in the else branch can probably be just removed?

#### SCAP Security Guide Version:
0.1.57

#### Operating System Version:

SUSE Linux Enterprise Server 15 SP3

#### Steps to Reproduce:

1. run sle15-script-stig.sh
2.
3.
4.

#### Actual Results:

error regarding incorrect use of return is displayed

#### Expected Results:

no error displayed

**Comment by marcusburghardt** [comment]
FYI @teacup-on-rockingchair
