### ISSUE TITLE
gnome login message display has some left over regexps

### ISSUE THREAD

**Issue by msmeissn** [ComplianceAsCode/content#7463]
#### Description of problem:

After applying the sle15 stig bash remediation, the popup after GNOME login shows some unreplaced regular expressions.

#### SCAP Security Guide Version:

0.1.57

#### Operating System Version:

SUSE Linux Enterprise 15 SP3

#### Steps to Reproduce:

1. apply bash remediation for sle15 stig
2.
3.
4.

#### Actual Results:

Text mostly correct, just some regexp left in.

#### Expected Results:

Text correct.

**Comment by msmeissn** [comment]
hmm, tried to attach the image.  uploaded here https://pasteboard.co/KhwDkVK6.png

**Comment by ggbecker** [comment]
The bash remediation [banner_etc_gdm_banner](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-banners/gui_login_banner/banner_etc_gdm_banner/bash/shared.sh) needs to be updated similarly as it is done in [banner_etc_issue](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-banners/banner_etc_issue/bash/shared.sh).

@brett060102 @guangyee please tag the right people here.

**Comment by brett060102** [comment]
@rumch-se @teacup-on-rockingchair @abergmann  can one of you please take a look. Thanks.

**Comment by Mab879** [comment]
This should be fixed in #7504.

**Comment by rumch-se** [comment]
Hello @msmeissn and @brett060102  - the expected correction was done and merged into master.

**Comment by yuumasato** [comment]
This should be fixed in 0.1.59 after https://github.com/ComplianceAsCode/content/pull/7784 and https://github.com/ComplianceAsCode/content/pull/7861.
Please reopen if the issue persists.
