### ISSUE TITLE
Associate RHEL-07-030840 with audit_rules_privileged_commands_kmod

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#7485]
Associate RHEL-07-030840 with https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/auditing/auditd_configure_rules/audit_privileged_commands/audit_rules_privileged_commands_kmod/rule.yml

This rule needs to be fixed for other products, I think it's kinda broken for ubuntu since it's using the templated content for that same as RHEL8 but the audit line is similar to SLE... One idea is to separate the RHEL8 rule as it is the only that deviates from the other products (the actual audit configuration line).

**Comment by lenox-joseph** [comment]
Duplicates #6766 and should be fixed by #9338
