### ISSUE TITLE
SSGTS variables metadata cannot have comma as a separator

### ISSUE THREAD

**Issue by matusmarhefka** [ComplianceAsCode/content#7553]
#### Description of problem:
In cases that XCCDF variable contains commas it is impossible to define `variables` test scenario metadata.
Example can be the `sshd_use_approved_ciphers` rule with variable `sshd_approved_ciphers` where the default is
`default: aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc,rijndael-cbc@lysator.liu.se`.

We need to update a separator to be something different, preferably a character which is not used in our XCCDF variables.

**Comment by jan-cerny** [comment]
@matusmarhefka BTW Why do we use the value and not the selector?

**Comment by cipherboy** [comment]
@jan-cerny I think because with the `# variables` keyword, we want to support non-selected variable values that we don't necessarily want to ship in our final product.
