### ISSUE TITLE
Skip unreasonable templated test scenarios with a warning

### ISSUE THREAD

**Issue by yuumasato** [ComplianceAsCode/content#7612]
#### Description of problem:

Templated test scenarios for `package_openssh-server_installed` and `package_openssh-clients_installed` don't work on VMs and they need to be skipped by `test_suite.py`. (Do we also SSH when running Test Suite on containers?)

This is a design flaw, the Test Suite uses SSH to connect and run the tests.
Removing `openssh-server` removes the server, and `oscap-ssh` doesn't work.
Removing `openssh-clients` removes `scp` and other utilities, preventing transfer of the test scenarios.

#### SCAP Security Guide Version:
0.1.58+

#### Steps to Reproduce:

1. python3 tests/test_suite.py rule --libvirt QEMU:://SESSION VM --datastream ./build/ssg-rhel8-ds.xml package_openssh-clients_installed

#### Actual Results:

```
ERROR - Script package-installed-removed.fail.sh using profile (all) found issue:
ERROR - Rule xccdf_org.ssgproject.content_rule_package_openssh-clients_installed has not been evaluated! Wrong profile selected in test scenario?
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_package_openssh-clients_installed'.
INFO - Script package-installed.pass.sh using profile (all) OK
ERROR - Script package-removed.fail.sh using profile (all) found issue:
ERROR - Rule xccdf_org.ssgproject.content_rule_package_openssh-clients_installed has not been evaluated! Wrong profile selected in test scenario?
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_package_openssh-clients_installed'.
INFO - xccdf_org.ssgproject.content_rule_package_openssh-server_installed
ERROR - Script package-installed-removed.fail.sh using profile (all) found issue:
ERROR - Rule xccdf_org.ssgproject.content_rule_package_openssh-server_installed has not been evaluated! Wrong profile selected in test scenario?
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_package_openssh-server_installed'.
INFO - Script package-installed.pass.sh using profile (all) OK
ERROR - Script package-removed.fail.sh using profile (all) found issue:
ERROR - Rule xccdf_org.ssgproject.content_rule_package_openssh-server_installed has not been evaluated! Wrong profile selected in test scenario?
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_package_openssh-server_installed'.
```

#### Expected Results:
1. These can't be tested by Test Suite, so they should be skipped with a warning.

**Comment by yuumasato** [comment]
We cannot remove `crypto-policies` as well.

```
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
STDERR: Warning: Permanently added '192.168.122.136' (ECDSA) to the list of known hosts.
+ rpm -q --quiet crypto-policies
+ yum remove -y --setopt protected_packages= crypto-policies
Error: 
 Problem: The operation would result in removing the following protected packages: kernel-core
```

**Comment by yuumasato** [comment]
@mildas @matusmarhefka CC

**Comment by marcusburghardt** [comment]
This PR may provides some insights about possible solutions: https://github.com/ComplianceAsCode/content/pull/7559

In the specific case of this PR, a variable was introduced to permit different behavior for "bash_package_remove" macro when called by SSG Test Suite.

**Comment by matusmarhefka** [comment]
Another rule which would need such exception is `package_openscap-scanner_installed`:
```
INFO - xccdf_org.ssgproject.content_rule_package_openscap-scanner_installed
ERROR - Script package-removed.fail.sh using profile (all) found issue:
ERROR - Rule xccdf_org.ssgproject.content_rule_package_openscap-scanner_installed has not been evaluated! Wrong profile selected in test scenario?
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_package_openscap-scanner_installed'.
INFO - Script package-installed.pass.sh using profile (all) OK
ERROR - Script package-installed-removed.fail.sh using profile (all) found issue:
ERROR - Rule xccdf_org.ssgproject.content_rule_package_openscap-scanner_installed has not been evaluated! Wrong profile selected in test scenario?
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_package_openscap-scanner_installed'.
```

**Comment by mildas** [comment]
We will need a mechanism to skip specific templated test scenarios.
Now, we can't test crypto-policies, openssh-server, or openscap-scanner package removals, because openscap scan can't be done after that. And there might be more in future.

What options do we have?
1. Skipping rules in template metadata
```
$ cat /home/mlysonek/SCAP/content/shared/templates/package_installed/tests/package-removed.fail.sh
#!/bin/bash
# skip: package_openscap-scanner_installed

{{{ bash_package_remove(PKGNAME) }}}
```
2. Skipping test scenarios in `rule.yml`
```
template:
    name: package_installed
    vars:
        pkgname: openscap-scanner
    skip-tests: package-removed.fail.sh package-installed-removed.fail.sh
```
3. File which will indicate that all templated test scenarios should be skipped
```
$ ls -a /home/mlysonek/SCAP/content/linux_os/guide/system/software/system-tools/package_openscap-scanner_installed/tests
.  ..  .skip_templated_tests
```
4. New option for SSGTS where rules to skip will be listed
5. Internal SSGTS variable with list of rules (rules+test scenarios?) that can't be tested


Unfortunately, everything mentioned above is not so easy to implement and it needs changes in build system (?) and SSGTS. @yuumasato @matusmarhefka What do you think? Any ideas how we could solve it? Do you prefer any of my options? Some kind of combination is also possible (e.g. `no-tests: yes` in `rule.yml` to not create any templated test).

**Comment by vojtapolasek** [comment]
I must say that I like the option 3 the most. I think this information should be kept close to the rule, because it is rule specific. That's why I think that the option 1 is a bad idea.
At the same time, option 2 puts it inside the rule definition. That is close to the rule, but I don't think that rule definition should contain hints about how we test the rule.
The option 4 would require that the tester knows about all peculiar rules in the content.
How about using some ssgts.yml file in the <rule>/tests directory? Currently, there could be only one thing, something like
```
skip_templated_tests: True
```
But in the future this can be handy for other enhancements.

**Comment by matejak** [comment]
Also got some observations:

1. Tested rules depend on the template, so making the template also aware of individual rules so those rules don't use this would be unfortunate - a simpler solution is that the rule can opt itself out right away.
2. Again tests of rules depend on the rule yaml, as it may define OVAL/bash content of the rule. Therefore, rule yaml shouldn't depend on implementation details of tests - and whether a template is written in a way that is compatible with that rule at the moment is an implementation detail of both the rule and tests template. Moreover, test suite could have issues parsing yaml files with all that product-specific jinja.
3. This sounds right, having that information close to the surface where the friction is observable, in this case close to other test scenarios.
4. This sounds useful, although it can't fix the issue completely. Think of tests of a a mixed bag of templated rules - you would have to separate good and bad ones, and test one batch with templated tests, and another without them.
5. Similar to point 2 and to point 3 - that variable would have to know of interactions between templated tests and rules, and no variable should be told that directly by us. Let's store the information close to its source, which typically is a failed test run, and by extension the concerned rule's `tests` directory.

**Comment by matejak** [comment]
#8052 could help

**Comment by yuumasato** [comment]
From my point of view what makes a rule not testable by template is its specific role in the product or test 
environment. So I agree that the information whether a rule should skip templated test scenarios should be close or in the rule, so ideas 2 and 3 make the most sense to me.

But I think the testability of a rule is closely tied to the product, so I like idea 2 the most.

Take template `package_removed` for example, on RHEL we cannot remove `openssh-clients` because it also removes `scp` which the test harness needs. But let's say other distros don't remove `scp` or other tools needed by the testing harness, then the rule could be tested by the template in that distro.

There can also be situation where disabling a service is not so simple, for example, on RHEL, stopping `auditd` is not just about `systemctl stop, other distros may differ.
```
[root@localhost ~]# systemctl stop auditd.service
Failed to stop auditd.service: Operation refused, unit auditd.service may be requested by dependency only (it is configured to refuse manual start/stop).
See system logs and 'systemctl status auditd.service' for details.
```

**Comment by mildas** [comment]
Thank you @matejak for the solution! Works nicely
