### ISSUE TITLE
content_rule_chronyd_or_ntpd_specify_multiple_servers doesn't check pool

### ISSUE THREAD

**Issue by IgorMilavec** [ComplianceAsCode/content#7693]
#### Description of problem:
I have configured Chrony to synchronize with the local Active Directory domain controllers.
The easiest was is to specify:
pool mydomain.local
as all the AD DCs register an A record for mydomain.local. Now if we change a DC, we don't need to go reconfigure all the RHEL servers.

"chronyc sources" shows 3 valid sources, but this rule still fails...

#### SCAP Security Guide Version:
Um... latest? 8-)

#### Operating System Version:
RHEL 8.4

#### Steps to Reproduce:

1. Remove all "server" options from chrony.conf
2. Add "pool mydomain.local ..."

#### Actual Results:
Title   Specify Additional Remote NTP Servers
Rule    xccdf_org.ssgproject.content_rule_chronyd_or_ntpd_specify_multiple_servers
Ident   CCE-80764-4
Result  fail

#### Expected Results:
Result  pass

**Comment by Mab879** [comment]
This should be fixed now. Let us know if you need more help.
