### ISSUE TITLE
Rule postfix_network_listening_disabled fails after kickstart install (RHEL7 CIS Workstation L2)

### ISSUE THREAD

**Issue by matusmarhefka** [ComplianceAsCode/content#7728]
#### Description of problem:
Rule `postfix_network_listening_disabled` fails after installing RHEL-7.9 with kickstart for CIS Workstation L2 profile.

#### SCAP Security Guide Version:
master (57fc344)

#### Operating System Version:
RHEL-7.9 installed with `Server with GUI` package group and latest content from master

#### Steps to Reproduce:

1. Install RHEL 7.9 with `Server with GUI` software selection and CIS Workstation L2 profile.
2. After installation scan the machine with the profile selected during the installation.

#### Actual Results:
`postfix_network_listening_disabled` fails

#### Expected Results:
`postfix_network_listening_disabled` passes

#### Additional Information/Debugging Steps:
The rule is passing during installation (so openscap doesn't remediate it), but additional scan once the system is installed reports `postfix_network_listening_disabled` as fail (OVAL detects that `/etc/postfix/main.cf` contains `inet_interfaces = localhost` instead of `inet_interfaces = loopback-only`).

**Comment by ggbecker** [comment]
Sounds like a first boot remediation type of issue.

**Comment by mildas** [comment]
@ggbecker The OVAL result is strange there. As Matus wrote in additional information, `/etc/postfix/main.cf` contains `inet_interfaces = localhost` and that's something I would expect to be correct even without first boot remediation.

**Comment by ggbecker** [comment]
> @ggbecker The OVAL result is strange there. As Matus wrote in additional information, `/etc/postfix/main.cf` contains `inet_interfaces = localhost` and that's something I would expect to be correct even without first boot remediation.

taking a quick look a the oval... it might be that the service is not enabled and the check will pass during installation:
```
    <criteria operator="OR">
      <!-- postfix package not installed or postfix service not configured to start -->
      <extend_definition comment="Postfix installed and configured to start" negate="true" definition_ref="service_postfix_enabled" />
      <!-- postfix network listening disabled -->
      <criterion comment="Check inet_interfaces in /etc/postfix/main.cf" test_ref="test_postfix_network_listening_disabled" />
    </criteria>
```

**Comment by mildas** [comment]
Aha, makes sense. In that case, it is first boot remediation issue.

**Comment by mildas** [comment]
Closing. We can't fix it in content.

This issue would be fixed by first boot remediation update in OAA, but RHEL7 installed won't get this update.
