### ISSUE TITLE
Fail test scenario for service_debug-shell_disabled errors with Ansible remediation (RHEL7)

### ISSUE THREAD

**Issue by matusmarhefka** [ComplianceAsCode/content#7734]
#### Description of problem:
Fail test scenario for the rule `service_debug-shell_disabled` errors with Ansible remediation on RHEL-7.9:
```
$ python3 test_suite.py rule --libvirt qemu:///session ssgts_79 --datastream ../build/ssg-rhel7-ds.xml --remediate-using ansible service_debug-shell_disabled
INFO - xccdf_org.ssgproject.content_rule_service_debug-shell_disabled
INFO - Script service_disabled.pass.sh using profile (all) OK
INFO - Script service_enabled.fail.sh using profile (all) OK
ERROR - Rule evaluation resulted in fail, instead of expected pass during final stage 
ERROR - The check after remediation failed for rule 'xccdf_org.ssgproject.content_rule_service_debug-shell_disabled'.
```

#### SCAP Security Guide Version:
57fc344

#### Operating System Version:
RHEL-7.9

#### Steps to Reproduce:

1. `python3 test_suite.py rule --libvirt qemu:///session ssgts_79 --datastream ../build/ssg-rhel7-ds.xml --remediate-using ansible service_debug-shell_disabled`

#### Actual Results:
Test scenario `service_enabled.fail.sh` errors.

#### Expected Results:
Test scenario `service_enabled.fail.sh` passes.

**Comment by ggbecker** [comment]
The `ActiveState` property is reporting `failed` and the OVAL only allows `inactive`:

https://github.com/ComplianceAsCode/content/blob/f1783363f8a042cfbba66bfff42a144a59b9a4f9/shared/templates/service_disabled/oval.template#L29

A quick fix is to allow only the `failed` state which should be enough in case of service disabled.

`<linux:value operation="pattern match">inactive|failed</linux:value>`
