### ISSUE TITLE
RHEL9 failing rules per profile

### ISSUE THREAD

**Issue by matusmarhefka** [ComplianceAsCode/content#7752]
#### Description of problem:
See the section per each RHEL9 profile which contains rules failing even after remediation.

#### SCAP Security Guide Version:
master (57fc344)

#### Operating System Version:
RHEL9 Beta

#### Steps to Reproduce:
1. Run installation of RHEL9 Beta with a profile kickstart file (from https://github.com/ComplianceAsCode/content/tree/master/products/rhel9/kickstart)
2. Scan the system after installation with the profile based on kickstart which was used to install the system.

#### OSPP, CUI
`service_auditd_enabled` (in SSGTS profile mode)
`no_tmux_in_shells` (in SSGTS profile mode)

#### CIS Workstation Level 2 (GUI)
~`dconf_gnome_login_banner_text`~
~`selinux_confinement_of_daemons` - no remediation, but finds many breakages~

#### HIPAA
`rpm_verify_hashes` - detects issue in `systemd` package (`/usr/lib/systemd/system/rescue.service`)
~`auditd_audispd_syslog_plugin_activated`~

#### HIPAA (GUI)
`rpm_verify_hashes` - detects issue in `systemd` package (`/usr/lib/systemd/system/rescue.service`)
`rpm_verify_permissions` - detects issues in `accountsservice`, `gdm` and `fprintd` packages
~`auditd_audispd_syslog_plugin_activated`~

#### PCI-DSS
~`configure_opensc_card_drivers` - no Bash remediation~
~`force_opensc_card_drivers` - no Bash remediation~

#### PCI-DSS (GUI)
`rpm_verify_permissions` - detects issues in `accountsservice`, `gdm` and `fprintd` packages
~`auditd_audispd_syslog_plugin_activated`~

#### STIG
`no_tmux_in_shells` (SSGTS profile mode)
`configure_firewalld_ports`
`accounts_password_set_min_life_existing` (SSGTS profile mode)
`sshd_set_idle_timeout`

#### STIG_GUI (GUI)
`no_tmux_in_shells` (SSGTS profile mode)
`accounts_password_set_min_life_existing` (SSGTS profile mode)
`configure_firewalld_ports`
`sshd_set_idle_timeout`

#### ANSSI BP-028 High (results for both, no GUI and GUI)
~`accounts_polyinstantiated_tmp`~ - fails only after kickstart installation, needs to be remediated once more
~`accounts_polyinstantiated_var_tmp`~ - fails only after kickstart installation, needs to be remediated once more
~`file_permissions_sshd_private_key`~ - fails only after kickstart installation, because SSH keys are generated after oscap remediations. Remediation should be run once more

#### ISM_O
`rpm_verify_hashes` - detects issue in `systemd` package (`/usr/lib/systemd/system/rescue.service`)
`network_nmcli_permissions` (SSGTS profile mode)
`configure_firewalld_ports`
~`file_permissions_sshd_private_key`~ - https://github.com/ComplianceAsCode/content/issues/7833

#### ISM_O (GUI)
`rpm_verify_hashes` - detects issue in `systemd` package(`/usr/lib/systemd/system/rescue.service`)
`rpm_verify_permissions` - detects issues in `accountsservice`, `gdm` and `fprintd` packages
`network_nmcli_permissions` (SSGTS profile mode)
`configure_firewalld_ports`
~`file_permissions_sshd_private_key`~ - fails only after kickstart installation, because SSH keys are generated after oscap remediations. Remediation should be run once more

**Comment by mildas** [comment]
List has been updated.

It would be great if `auditd_audispd_syslog_plugin_activated` rule is fixed, because it's the only failing rule with remediation implemented in few profiles. Remediation output:
```
grep: /etc/audisp/plugins.d/syslog.conf: No such file or directory
/tmp/oscap.eoJiUI/fix-XXw6aNCb: line 32: /etc/audisp/plugins.d/syslog.conf: No such file or directory
/tmp/oscap.eoJiUI/fix-XXw6aNCb: line 33: /etc/audisp/plugins.d/syslog.conf: No such file or directory
```

**Comment by ggbecker** [comment]
> List has been updated.
> 
> It would be great if `auditd_audispd_syslog_plugin_activated` rule is fixed, because it's the only failing rule with remediation implemented in few profiles. Remediation output:
> 
> ```
> grep: /etc/audisp/plugins.d/syslog.conf: No such file or directory
> /tmp/oscap.eoJiUI/fix-XXw6aNCb: line 32: /etc/audisp/plugins.d/syslog.conf: No such file or directory
> /tmp/oscap.eoJiUI/fix-XXw6aNCb: line 33: /etc/audisp/plugins.d/syslog.conf: No such file or directory
> ```

I think this #7971 should fix the issue

**Comment by ggbecker** [comment]
> OVAL details after kickstart installation:
> sshd_set_idle_timeout

RHEL9 uses sshd distributed configuration so ssh parameters are put under `/etc/ssh/sshd_config.d`. Then this check fails: https://github.com/ComplianceAsCode/content/blob/0d5c0ea25bffe16984269b860dd405effe8b3baa/linux_os/guide/services/ssh/ssh_server/sshd_set_idle_timeout/oval/shared.xml#L30

we need to extend the check or add a new one to allow configuration from .d directories as well.

**Comment by vojtapolasek** [comment]
I think the problem with the rule network_nmcli_permissions is that if the "polkit" package is not installed, the directory /etc/polkit-1 does not exist at all. So the check fails and the fix as well.
Maybe we can later make the rule applicable only if polkit is installed?

**Comment by mildas** [comment]
Closing because most of the issues were already fixed. If we notice some of them still failing, we can open issue for the individual rule - it will be more clear.
