### ISSUE TITLE
Add option to SSGTS to skip templated test scenarios if custom tests are found

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#7756]
#### Description of problem:

Sometimes templated test scenarios don't cover all possible cases a template can be used. As it's in the case of https://github.com/ComplianceAsCode/content/pull/7405/files#diff-66fb572257ded0d27ec50b0c7c6f8073df416494e02dcbc58a15a50ffefff704 where we can't easily implement generic tests for that. In this case we have custom test scenarios but current implementation of templated tests will evaluate generic tests anyway unless we override all the tests scenarios. Having an option/mechanism to skip templated test scenarios is desired in these situations.

**Comment by Mab879** [comment]
Does "test_config.yml" like in `linux_os/guide/system/software/system-tools/package_openscap-scanner_installed/tests/test_config.yml` help?

**Comment by Mab879** [comment]
This is fixed now.

**Comment by ggbecker** [comment]
Fixed by #8052

**Comment by marcusburghardt** [comment]
For reference: https://complianceascode.readthedocs.io/en/latest/tests/README.html#augmenting-using-shared-templates
