### ISSUE TITLE
https://public.cyber.mil/    don't have access to

### ISSUE THREAD

**Issue by rtczza** [ComplianceAsCode/content#7764]
#### Description of problem:
https://public.cyber.mil/    don't have access to

#### SCAP Security Guide Version:
scap-security-guide-0.1.48-10

#### Operating System Version:
fedora-34

#### Steps to Reproduce:

1.Browser opens ：https://public.cyber.mil/ 
2.
3.
4.

#### Actual Results:
This website cannot be accessed

#### Expected Results:
Normal access

#### Additional Information/Debugging Steps:

Generate the stig_overlay.xml file using the utils/create-stig-overlay.py script

**Comment by ggbecker** [comment]
either way, this is not a problem related to this project. Closing the issue.
