### ISSUE TITLE
Help...Ansible Playbook/

### ISSUE THREAD

**Issue by manglo00** [ComplianceAsCode/content#7828]
#### Description of problem:
Experiencing issues when running ansible playbook, rhel8-playbook-stig.yml on fresh RHEL 8.4 system, where playbook does not appear to fully remediate system. Once playbook is applied, rebooted, i run an ACAS scan against the system.  Couple issues, is that I also ran the DISA SCC SCAP tool to compare scan results, and do get better results, so it appears it could be issue on Tenable side, however...I also run the OSCAP bash script, rhel8-script-stig.sh, and this FULLY remediates the RHEL 8 system, per ACAS, posting ZERO high findings.  Lastly, i'm using the SCAP workbench, to pick and choose which remediations i want applied, and the desired output of the selected remediations is ansible, which as stated, has not been remediating, per ACAS.  Here are details, 
(help much appreciated, and apologies is not the correct place to post issue.)

ACAS Audit file (found on Tenable Website): DISA_STIG_Red_Hat_Enterprise_Linux_8_v1r3.audit
Initial Scan (Pre-Ansible): 331 High Findings (estimated)
Post Scan (after ansible): 260 High Findings 

I also used the DISA SCC SCAP Tool to scan, and get better results
Initial Scan (Pre-Ansible): 31.85 % 79 PASS, 169 Fail
Post Scan (Post-Ansible): 74% 184 PASS 64 Fail

#### SCAP Security Guide Version:
0.1.59

#### Operating System Version:
RHEL 8.4

#### Steps to Reproduce:

1.
2.
3.
4.

**Comment by marcusburghardt** [comment]
Coverage is gradually improving.
