### ISSUE TITLE
Multiple NIC RHEL7 with DISA STIG Security Configuration - Rule CCE-80447-6 

### ISSUE THREAD

**Issue by dxcSithLord** [ComplianceAsCode/content#7839]
#### Description of problem:
The script used to apply the ZONE=public to network interfaces on Red Hat 7 builds – with more than one interface will not apply correctly due to the way the remediation script (as defined [
https://static.open-scap.org/ssg-guides/ssg-rhel7-guide-stig.html#xccdf_org.ssgproject.content_rule_configure_firewalld_ports
](
https://static.open-scap.org/ssg-guides/ssg-rhel7-guide-stig.html#xccdf_org.ssgproject.content_rule_configure_firewalld_ports
) does not handle multiple NIC devices.  When multiple devices are installed, the following file is created:
/etc/sysconfig/network-scripts/ifcfg-NIC1\nNIC2

where NIC1 and NIC2 are "eth" or "en" network interface names.  The newline character shows as a newline, so the second NIC name appears at the start of the next line.  
Use "ls | od -xc" to confirm control character in filename,

The file contains "ZONE=Public" setting with comment referencing CCE-80447-6 – with the file name contains a newline character.  The files ifcfg-NIC1 and ifcfg-NIC2 are not modified.

#### SCAP Security Guide Version:

DISA STIG for Red Hat Enterprise Linux V3R4

#### Operating System Version:

Red Hat Enterprise Linux 7.8

#### Steps to Reproduce:

1.  Build RedHat 7 server, with two Network interfaces defined
2.  under the security setting, select the  DISA STIG Security option to be applied and configure the server appropriately.
3.  Once applied the file will exist in /etc/sysconfig/network-scripts/ifcfg-NIC1\nNIC2
4.  Specific instance identified in ClearSwift SEG and SWG Appliances (Confirmed in V5.0 and V5.2 base builds (based on RHEL7.8), but current recommended code referenced by rule identified as source of problem.

#### Actual Results:

An additional file is created that includes the expected setting, but doesn't match a single interface name.

#### Expected Results:

The ZONE=public entry is added to the first NIC interface file in /etc/sysconfig/network-scripts.  It is not defined in the remediation script what happens to the other network interfaces.  What should happen to the other interfaces is outside the scope of this (coding) problem.

#### Additional Information/Debugging Steps:

The “suggested” script uses two methods to access values in the string value of $eth_interface_list, one which loops around the whitespace separated string and the other attempts to index the first entry with array syntax.  As this is a string and not an array, this returns the whole string, which includes the newline character.  

This "recommended" code segment works correctly:
============== EXISTING CODE SEGMENT ==========
`eth_interface_list=$(ip link show up | cut -d ' ' -f2 | cut -d ':' -s -f1 | grep -E '^(en|eth)')`
`for interface in $eth_interface_list; do`
`    if grep -q "ZONE=$firewalld_sshd_zone" /etc/sysconfig/network-scripts/ifcfg-$interface; then`
`        nic_bound=true`
`        break;`
`    fi`
`done`
============= END OF CODE SEGMENT =========

This segment does not work as expected:
====== EXISTING CODE SEGMENT =======
 `       # If the key exists, change it. Otherwise, add it to the config_file.`
 `       # We search for the key string followed by a word boundary (matched by \>),`
 `       # so if we search for 'setting', 'setting2' won't match.`
 `       if LC_ALL=C grep -q -m 1 -i -e "^ZONE=\\>" "/etc/sysconfig/network-scripts/ifcfg-${eth_interface_list[0]}"; then`
`            "${sed_command[@]}" "s/^ZONE=\\>.*/$formatted_output/gi" "/etc/sysconfig/network-scripts/ifcfg-${eth_interface_list[0]}"`
`        else`
`            # \n is precaution for case where file ends without trailing newline`
`            printf '\n# Per %s: Set %s in %s\n' "$cce" "$formatted_output" "/etc/sysconfig/network-scripts/ifcfg-${eth_interface_list[0]}" >> "/etc/sysconfig/network-scripts/ifcfg-${eth_interface_list[0]}"`
`            printf '%s\n' "$formatted_output" >> "/etc/sysconfig/network-scripts/ifcfg-${eth_interface_list[0]}"`
`        fi`
=========== END CODE SEGMENT =========
The problem is with the use of ${eth_interface_list[0]} -  which for a string would just return the single element, which is the whole string.
To demonstrate – the following is used to create the “list” – with an octal dump of Hex and characters to show the exact return
ip link show up | cut -d ' ' -f2 | cut -d ':' -s -f1 | grep -E '^(en|eth)' | od -xc

alternative should be 
set -a eth_interfaces
eth_interface_list=( $(ip link show up | cut -d ' ' -f2 | cut -d ':' -s -f1 | grep -E '^(en|eth)') )

Then the array references will work.

for loop would change to
for interface in ${eth_interface_list[@]); do

Then the ${eth_interface_list[0]} will then work as coded.

Alternatively, perhaps :
firewall-cmd --set-default-zone=public

**Comment by marcusburghardt** [comment]
This rule was refactored and this case was also covered.
