### ISSUE TITLE
NFS Server no anonymous exports

### ISSUE THREAD

**Issue by jcpunk** [ComplianceAsCode/content#7846]
## Which products and profiles does the rule apply to?

RHEL8/RHEL9/Fedora

## Describe the configuration setting enforced by this rule.

Ban the use of anonymous exports

```
/pub  *(ro,all_squash)
```

From the manpage (man 5 exports):
```
       anonymous
              This is specified by a single * character (not  to  be  confused
              with the wildcard entry above) and will match all clients.
```

## Why is the configuration security relevant?

Shared content can be restricted to valid DNS, IP Ranges, or Netgroups for most sites.  Having content with no restrictions on the clients is unexpected and may lead to unplanned clients across unexpected networks.

## How to check the configuration?

```
sudo grep '[[:space:]]\*(' /etc/exports
sudo grep '[[:space:]]\*(' /etc/exports.d/*
```

### Is it order dependent? (does it need to be at certain place in the file?)

This is not order dependent

### What is correct and incorrect syntax?

The use of `*` should be replaced with something site dependent

## How to remediate

Replace with the right qualifiers.

### Does any command need to be run?

The Kernel NFS server will need to be notified.

## Are there going to be other rules like this one in the future? Is it worth creating template? (similar configuration format, similar remediation process...)

Yes, there are other rule restrictions that sites might want to build for local customization.  For example, NFS Exports only to  *.unix.example.com or NFS Exports must not have `no_root_squash` or must have `all_squash`.

## Are there any caveats to be considered when testing?

Only applicable to hosts that have the NFS Server software.

## Is the configuration loaded directly by the <software> or is it stored in some intermediate database (similar to dconf)? (We want to edit the lowest level possible, if appropriate)

Loaded by exportfs from either `/etc/exports` or `/etc/exports.d/*`

## Is it possible to check / remediate this configuration in offline mode? (scanning containers or offline systems)

This option can be checked in offline mode.

##  Please provide security policy references if possible e.g. STIG
None

**Comment by Mab879** [comment]
Since there are no references we don't want to create a rule at this time.

If you have a reference we will take another look.
