### ISSUE TITLE
Rule dconf_gnome_login_banner_text errors with STIG profile

### ISSUE THREAD

**Issue by matusmarhefka** [ComplianceAsCode/content#7850]
#### Description of problem:
Rules ~~`banner_etc_issue`~~ (fixed by https://github.com/ComplianceAsCode/content/pull/7842) and `dconf_gnome_login_banner_text` error when remediated using STIG profile on RHEL8 (tested with kickstart installation).

#### SCAP Security Guide Version:
17eed51

#### Operating System Version:
RHEL8

#### Steps to Reproduce:

1. Install RHEL8 with STIG kickstart
2. Scan system with oscap after the install

#### Actual Results:
Rules ~~`banner_etc_issue`~~ and `dconf_gnome_login_banner_text` fail.

#### Expected Results:
Rules ~~`banner_etc_issue`~~ and `dconf_gnome_login_banner_text` pass.

**Comment by Mab879** [comment]
Does #7842 fix this issue?

**Comment by matusmarhefka** [comment]
> Does #7842 fix this issue?

Yes, it resolved the issue for `banner_etc_issue`, but the `dconf_gnome_login_banner_text` still errors.

**Comment by Mab879** [comment]
Possible fix in #7861

**Comment by Mab879** [comment]
Possible duplicate of #7463

**Comment by yuumasato** [comment]
Closing, reopen if issue still persists.
