### ISSUE TITLE
Ansible playbooks error on RHEL9

### ISSUE THREAD

**Issue by matusmarhefka** [ComplianceAsCode/content#7874]
#### Description of problem:
Ansible playbooks for certain profiles error when applied on RHEL9 compose.

#### Configure Periodic Execution of AIDE
Affected profile playbooks: `rhel9-playbook-cis.yml`, `rhel9-playbook-cis_workstation_l2.yml`
Package group: Minimal install
```
TASK [Configure Periodic Execution of AIDE] ************************************
[WARNING]: The value 5 (type int) in a string field was converted to '5' (type
string). If this does not look like what you expect, quote the entire value to
ensure it does not change.
[WARNING]: The value 4 (type int) in a string field was converted to '4' (type
string). If this does not look like what you expect, quote the entire value to
ensure it does not change.
[WARNING]: The value 0 (type int) in a string field was converted to '0' (type
string). If this does not look like what you expect, quote the entire value to
ensure it does not change.
fatal: [192.168.122.158]: FAILED! => {"changed": false, "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}
```

#### Configure System Cryptography Policy
Affected profile playbooks: `rhel9-playbook-ospp.yml`, `rhel9-playbook-cui.yml`, `rhel9-playbook-e8.yml`, `rhel9-playbook-hipaa.yml`, `rhel9-playbook-ism_o.yml`, `rhel9-playbook-stig.yml`
Package group: Minimal install
```
TASK [Configure System Cryptography Policy] ************************************
fatal: [192.168.122.158]: FAILED! => {"changed": false, "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}
```

#### Stage AIDE Database
Affected profile playbooks: `rhel9-playbook-pci-dss.yml`
Package group: Minimal install
```
TASK [Stage AIDE Database] *****************************************************
fatal: [192.168.122.158]: FAILED! => {"changed": false, "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}
```

#### get current kernel parameters
Affected profile playbooks: `rhel9-playbook-anssi_bp28_high.yml`, `rhel9-playbook-cis_workstation_l2.yml`, `rhel9-playbook-cui.yml`, `rhel9-playbook-hipaa.yml`, `rhel9-playbook-ospp.yml`, `rhel9-playbook-pci-dss.yml`, `rhel9-playbook-stig_gui.yml`
Package group: Server with GUI
```
TASK [get current kernel parameters] *******************************************
fatal: [192.168.122.83]: FAILED! => {"changed": false, "cmd": "/usr/bin/grub2-editenv - list | grep \"kernelopts=\"", "delta": "0:00:00.012150", "end": "2021-11-06 13:42:12.770830", "msg": "non-zero return code", "rc": 1, "start": "2021-11-06 13:42:12.758680", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```

#### Ensure libsemanage-python installed
Affected profile playbooks: `rhel9-playbook-ism_o.yml`
```
TASK [Ensure libsemanage-python installed] *************************************
fatal: [192.168.122.83]: FAILED! => {"changed": false, "failures": ["No package libsemanage-python available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
```

#### SCAP Security Guide Version:
17eed51

#### Operating System Version:
RHEL9

#### Steps to Reproduce:
Run profile playbook or specific Ansible tasks directly.

#### Actual Results:
Listed Ansible tasks result in error (which prevents profile plabooks to finish remediating all configurations).

#### Expected Results:
Listed Ansible tasks do not error.

**Comment by ggbecker** [comment]
My findings so far:

---
> TASK [Configure System Cryptography Policy] ************************************
> fatal: [192.168.122.158]: FAILED! => {"changed": false, "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}

We should make sure that the package `python3-libselinux` is installed

---

> TASK [Ensure libsemanage-python installed] *************************************
> fatal: [192.168.122.83]: FAILED! => {"changed": false, "failures": ["No package libsemanage-python available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}


We need to extend this jinja if to include RHEL9
https://github.com/ComplianceAsCode/content/blob/30b991031616c490edf2a002580f0237d7177233/shared/templates/sebool/ansible.template#L16


---

> TASK [get current kernel parameters] *******************************************
> fatal: [192.168.122.83]: FAILED! => {"changed": false, "cmd": "/usr/bin/grub2-editenv - list | grep \"kernelopts=\"", "delta": "0:00:00.012150", "end": "2021-11-06 13:42:12.770830", "msg": "non-zero return code", "rc": 1, "start": "2021-11-06 13:42:12.758680", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

We need to add `ignore_errors: yes` to the task:

https://github.com/ComplianceAsCode/content/blob/30b991031616c490edf2a002580f0237d7177233/shared/templates/grub2_bootloader_argument/ansible.template#L32
