### ISSUE TITLE
Possible typo in audit_immutable_login_uids rule

### ISSUE THREAD

**Issue by ansasaki** [ComplianceAsCode/content#7880]
The following line mentions ``login UIDs`` and ``login UUIDs``:

https://github.com/ComplianceAsCode/content/blob/0d6ccd25f16adf938c1d4f4779f2d744980a37fa/linux_os/guide/system/auditing/policy_rules/audit_immutable_login_uids/rule.yml#L14

Are they referring to different things or is this a typo?

**Comment by Mab879** [comment]
That appears to be a typo, I will get that fixed. Thanks for reporting this.
