### ISSUE TITLE
Rule sudo timestamp_timeout regex match should allow spaces around the '=' character. The check should also check /etc/sudoers.d/* files

### ISSUE THREAD

**Issue by Mosibi** [ComplianceAsCode/content#7882]
https://github.com/ComplianceAsCode/content/blob/5ba05c306b39273048ec08732bdeb8d5dc64b6ee/linux_os/guide/system/software/sudo/sudo_require_reauthentication/oval/shared.xml#L16

**Comment by dmc5179** [comment]
This was resolved by another issue: https://github.com/ComplianceAsCode/content/commit/573ae69742cf372d41da6c56a3051745326055cd

**Comment by ggbecker** [comment]
Only he `/etc/sudoers.d/*` has been addressed by https://github.com/ComplianceAsCode/content/commit/573ae69742cf372d41da6c56a3051745326055cd

The OVAL check still doesn't allow spaces around the `=` character.
