### ISSUE TITLE
cockpit display login banner from `/etc/issue`

### ISSUE THREAD

**Issue by jcpunk** [ComplianceAsCode/content#7888]
## Which products and profiles does the rule apply to?

fedora,ol7,ol8,rhel7,rhel8,rhel9

## Describe the configuration setting enforced by this rule.

Ensure the cockpit service shows the login banner describing rights and limitations.  Similar to what is done for GDM.

## Why is the configuration security relevant?

    Display of a standardized and approved use notification before granting
    access to the operating system ensures privacy and security notification
    verbiage used is consistent with applicable federal laws, Executive Orders,
    directives, policies, regulations, standards, and guidance.

## How to check the configuration?

`/etc/cockpit/cockpit.conf` will contain:

```
[Session]
Banner=/etc/issue
```

### Is it order dependent? (does it need to be at certain place in the file?)

The `Banner` keyword is only valid within the `[Session]` block.

### What is correct and incorrect syntax?

Correct:

```
[Session]
Banner=/etc/issue
```

Incorrect:

```
Banner=/etc/issue
[Session]
```

Incorrect:

```
[Session]
[WebService]
Banner=/etc/issue
```

## How to remediate

Ensure the relevant line is in the correct place within the config.

### Does any command need to be run?

The cockpit service will need to be restarted to see the change.

## Are there going to be other rules like this one in the future? Is it worth creating template? (similar configuration format, similar remediation process...)

Yes, there are other potential security related settings for the `cockpit` service.  The config file itself is in `ini` syntax which may already have a template.

## Are there any caveats to be considered when testing?

No

## Is the configuration loaded directly by the <software> or is it stored in some intermediate database (similar to dconf)? (We want to edit the lowest level possible, if appropriate)

The file is used as is

## Is it possible to check / remediate this configuration in offline mode? (scanning containers or offline systems)

This option can be checked in offline mode.

##  Please provide security policy references if possible e.g. STIG

This is probably related to the required interactive login banner notices in various profiles.

**Comment by Mab879** [comment]
Since there are no references we don't want to create a rule at this time.

There is lack of policy around cockpit as this time. 

If you have a reference we will take another look.
