### ISSUE TITLE
Typo in aescbc encryption rules

### ISSUE THREAD

**Issue by rbedia** [ComplianceAsCode/content#7900]
In the following two rules there is a typo in the check instructions. **aescdc** should be **aescbc**.

https://github.com/ComplianceAsCode/content/blob/e132d62d29d9c63c9134220177670b98d51725e5/applications/openshift/api-server/api_server_encryption_provider_cipher/rule.yml#L37
https://github.com/ComplianceAsCode/content/blob/e132d62d29d9c63c9134220177670b98d51725e5/applications/openshift/api-server/api_server_encryption_provider_config/rule.yml#L44

**Comment by JAORMX** [comment]
Oops! Thanks for letting us know!
