### ISSUE TITLE
Clean build of RHEL8 profiles on RHEL7 fails when delta tailoring is enabled

### ISSUE THREAD

**Issue by lenox-joseph** [ComplianceAsCode/content#7911]
#### SCAP Security Guide Version:
557db6a936fa20044b3c289ade450dca785bc6e7

#### Operating System Version:
RHEL 7.9

#### Steps to Reproduce:

1. Extract a clean tree on a RHEL7 system with `python-jinja2` installed and python2 installed only.
2. Build with the following options:
```
cmake ${SOURCE_DIRECTORY} -DSSG_PRODUCT_DEFAULT=OFF\
                             -DSSG_PRODUCT_FIREFOX=ON\
                             -DSSG_PRODUCT_RHEL7=ON\
                             -DSSG_PRODUCT_RHEL8=ON\
                             -DSSG_PRODUCT_JRE=ON
make -j4
```

#### Actual Results:
Build of `rhel8-generate-ssg-delta` fails due to "no such file or directory: ssg-rhel8-ds.xml".
Traceback is through `utils/create_scap_delta_tailoring.py`

#### Expected Results:
Builds with no failure.

#### Additional Information/Debugging Steps:

EDIT: fixed the paste with the build options

**Comment by yuumasato** [comment]
Hi @lenox-joseph I cannot reproduce the issue. I'm on a RHEL-7.9 box with the following packages:
```
Installed:
  PyYAML.x86_64 0:3.10-11.el7
  cmake.x86_64 0:2.8.12.2-2.el7
  git.x86_64 0:1.8.3.1-23.el7_8
  make.x86_64 1:3.82-24.el7
  openscap-utils.x86_64 0:1.2.17-11.el7
  python-jinja2.noarch 0:2.7.2-4.el7
```
Python3 is not installed.

I ran the following commands after RHEL-7.9 install:
```
yum install cmake make openscap-utils openscap-scanner PyYAML python-jinja2 git
git clone https://github.com/ComplianceAsCode/content.git
cd content/build
git checkout 557db6a
cmake -DSSG_PRODUCT_DEFAULT=OFF\
                             -DSSG_PRODUCT_FIREFOX=ON\
                             -DSSG_PRODUCT_RHEL7=ON\
                             -DSSG_PRODUCT_RHEL8=ON\
                             -DSSG_PRODUCT_JRE=ON\
                             ../
make -j4
```

**Comment by Mab879** [comment]
RHEL 7 is no longer supported, closing.
