### ISSUE TITLE
False Negative on NTP checks when using DNS records to find NTP servers

### ISSUE THREAD

**Issue by 39th-step** [ComplianceAsCode/content#7938]
OpenSCAP scripts 
xccdf_org.ssgproject.content_rule_chronyd_or_ntpd_specify_multiple_server
xccdf_org.ssgproject.content_rule_service_chronyd_or_ntpd_enabled
are failing, in our situation because they expect to find available NTP server addresses in /etc/chrony.conf.

But we are using SRV records: (like dig -t srv _ntp._udp.example.com) 
so that /usr/libexec/chrony-helper enable-dnssrv _ntp._udp.$DOMAIN knows which NTP servers are available.

**Comment by Mab879** [comment]
This goes against the CIS and STIG policies as they require static configuration time servers.

So we decline to do this change.
