### ISSUE TITLE
SCE support broken in v0.1.59

### ISSUE THREAD

**Issue by nightmared** [ComplianceAsCode/content#7946]
Hello,

#### Description of the problem:
I cannot use SCE tests with the SCAP Security Guide v0.1.59, which is a regression from v0.1.58.

SCE checks are marked as `nonchecked` when running them through OpenSCAP. After some investigation, I believe OpenSCAP is innocent in this matter and the culprit is the fact the ComplianceAsCode build system. Indeed, the content of SCE checks is not embedded inside the datastream. Additionally, the rules with SCE checks don't have a `<xccdf-1.2:check system="http://open-scap.org/page/SCE">...</xccdf-1.2:check>` section (which is probably for the best, as it would reference a non-existent object otherwise).

#### Operating System Version:
Fedora 36 (Workstation Edition Prerelease)

#### Steps to Reproduce:

1. Checkout the tag `v0.1.59`
2. Compile the ubuntu20.04 profiles with `-DSSG_PRODUCT_UBUNTU2004:BOOL=OFF` (In truth, I am using my own SCE checks, and I actually target the RHEL8 OS, but ubuntu 20.04 is the only operating system with a SCE check available upstream, and it is sufficient to demonstrate the issue)
3. The content of the SCE check was not embedded inside the datastream, yet it should.

#### Additional Information/Debugging Steps:

I was able to fix the problem with the following patch:
```
commit 6d106c145611590af8ecbd7be71ee338823ffe4d (HEAD)
Author: THOBY Simon <Simon.THOBY@viveris.fr>
Date:   Wed Dec 1 15:52:35 2021 +0100

    fix the SCE generation

diff --git a/ssg/build_yaml.py b/ssg/build_yaml.py
index ea0347a2e89e..dc1dec55f111 100644
--- a/ssg/build_yaml.py
+++ b/ssg/build_yaml.py
@@ -1258,6 +1258,7 @@ class Rule(XCCDFEntity):
         requires=lambda: list(),
         platform=lambda: None,
         platforms=lambda: set(),
+        sce_metadata=lambda: dict(),
         inherited_platforms=lambda: list(),
         template=lambda: None,
         cpe_platform_names=lambda: set(),
```

It appears the SCE metadata was not forwarded to the intermediate file (`<product>/checks/sce/<check_name>.sh`), so the condition at https://github.com/ComplianceAsCode/content/blob/v0.1.59/ssg/build_yaml.py#L1554 was never true, hence we never wrote the `<check></check>` section in https://github.com/ComplianceAsCode/content/blob/v0.1.59/ssg/build_yaml.py#L1585, and finally I guess the content of the SCE file itself were "garbage-collected" because no check referenced it.

Hope this helps. Feel free to notify me if you want me to test patches, I would be happy to give them a try.

**Comment by yuumasato** [comment]
Hi, your analysis look correct, but the patch doesn't seem to fix the issue. I did not get a ubuntu2004 DS with `<xccdf-1.2:check system="http://open-scap.org/page/SCE">...</xccdf-1.2:check>`.

Maybe something else is needed?

**Comment by nightmared** [comment]
Hmm, on my system with SSG_SCE_ENABLED, it appeared to generate a proper datastream...
Did you enable SCE when building CaC (I think it's disabled by default)?

**Comment by yuumasato** [comment]
@nightmared Yeah, I had not enabled SCE.

The suggested patch seems to work, would you be willing to open a PR?
