### ISSUE TITLE
RHEL9 - dconf_db_up_to_date rule - unexpected pass

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#7947]
#### Description of problem:
Rule `dconf_db_up_to_date` passes when it should fail - when we update dconf configuration and do not run `dconf update`, the rule must fail. However, on RHEL9 it passes.

#### SCAP Security Guide Version:
972b5e7

#### Operating System Version:
RHEL9

#### Steps to Reproduce:

1. `echo "[org/gnome/login-screen]" > /etc/dconf/db/gdm.d/00-security-settings`
2. `oscap xccdf eval --profile '(all)' --rule xccdf_org.ssgproject.content_rule_dconf_db_up_to_date  /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml`

#### Actual Results:
```
Title   Make sure that the dconf databases are up-to-date with regards to respective keyfiles
Rule    xccdf_org.ssgproject.content_rule_dconf_db_up_to_date
Ident   CCE-87295-2
Result  pass
```

#### Expected Results:
```
Title   Make sure that the dconf databases are up-to-date with regards to respective keyfiles
Rule    xccdf_org.ssgproject.content_rule_dconf_db_up_to_date
Ident   CCE-81003-6
Result  fail
```

#### Additional Information/Debugging Steps:
RHEL8 works fine:
```
[root@vm ~]# oscap xccdf eval --profile '(all)' --rule xccdf_org.ssgproject.content_rule_dconf_db_up_to_date  /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml
Title   Make sure that the dconf databases are up-to-date with regards to respective keyfiles
Rule    xccdf_org.ssgproject.content_rule_dconf_db_up_to_date
Ident   CCE-81003-6
Result  pass

[root@vm ~]# echo "[org/gnome/login-screen]" > /etc/dconf/db/gdm.d/00-security-settings
[root@vm ~]# oscap xccdf eval --profile '(all)' --rule xccdf_org.ssgproject.content_rule_dconf_db_up_to_date  /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml
Title   Make sure that the dconf databases are up-to-date with regards to respective keyfiles
Rule    xccdf_org.ssgproject.content_rule_dconf_db_up_to_date
Ident   CCE-81003-6
Result  fail

[root@vm ~]# dconf update
[root@vm ~]# oscap xccdf eval --profile '(all)' --rule xccdf_org.ssgproject.content_rule_dconf_db_up_to_date  /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml
Title   Make sure that the dconf databases are up-to-date with regards to respective keyfiles
Rule    xccdf_org.ssgproject.content_rule_dconf_db_up_to_date
Ident   CCE-81003-6
Result  pass
```

**Comment by ggbecker** [comment]
We probably need to include RHEL9 here:

**Comment by ggbecker** [comment]
There must be still some cases where we have these kind of jinja if statements where RHEL9 should be included as well

**Comment by ggbecker** [comment]
Actually, maybe the OVAL check should be extended to include the variable:

https://github.com/ComplianceAsCode/content/blob/46bf3c1408b81d722ea25a7b88509d3f12968f53/products/rhel9/product.yml#L20

**Comment by mildas** [comment]
> There must be still some cases where we have these kind of jinja if statements where RHEL9 should be included as well

Might be. I haven't noticed any other rule with this issue, but maybe we don't have it covered in tests and it's there. Definitely, we should check, but I don't see other rules as priority now. However, `dconf_db_up_to_date` should be prioritized and hopefully fixed in 0.1.60.

**Comment by mildas** [comment]
Reopening, still fails in 05831dc

**Comment by mildas** [comment]
It was issue in the test scenario. Closing
