### ISSUE TITLE
Regex sudoers_explicit_command_args false positive with some "Default" entries

### ISSUE THREAD

**Issue by ghost** [ComplianceAsCode/content#7954]
Hi,

The rule "Explicit arguments in sudo specifications" fail with the entry

```
 Defaults secure_path = "/sbin:/bin:/usr/sbin:/usr/bin"
```
should the regex be modified to ignore lines with a start in _Defaults_

**Comment by 0aKRJbtzneyeQKvJbX0D** [comment]
Suggested regex
```
^(?!Defaults)(?:\s*[^#=]+)=(?:\s*(?:\([^\)]+\))?\s*(?!\s*\()[^,\s]+(?:[ \t]+[^,\s]+)+[ \t]*,)*(\s*(?:\([^\)]+\))?\s*(?!\s*\()[^,\s]+[ \t]*(?:,|$))
```

**Comment by Mab879** [comment]
This fixed now.

**Comment by ggbecker** [comment]
Duplicate of https://github.com/ComplianceAsCode/content/issues/12349 which has been fixed already
