### ISSUE TITLE
RHEL7 and RHEL8 - STIG and ISM_O profile get stuck during kickstart installation

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#7965]
#### Description of problem:
When installing RHEL7/RHEL8 hardened with STIG or ISM_O, installation gets stuck.
Both variants - `Server` and `Server with GUI` are affected.

#### SCAP Security Guide Version:
a24252a

#### Operating System Version:
RHEL7 and RHEL8

#### Steps to Reproduce:

1. Perform STIG or ISM_O hardened RHEL7/RHEL8 installation

#### Actual Results:
installation is stuck

#### Expected Results:
installation finishes

**Comment by ggbecker** [comment]
I believe this should fix the problem: https://github.com/ComplianceAsCode/content/pull/7966

**Comment by ggbecker** [comment]
#7966 fixed the problem. Closing the issue.
