### ISSUE TITLE
EKS is causing nightly builds to fail

### ISSUE THREAD

**Issue by Mab879** [ComplianceAsCode/content#7981]
I noticed that the [nightly builds](https://jenkins.complianceascode.io/view/SCAP%20Security%20Guide/) are failing. It appears to be an issues with the EKS product.

```
The following tests FAILED:
	143 - validate-ssg-eks-cpe-oval.xml (Failed)
	148 - validate-ssg-eks-oval.xml (Failed)
	150 - validate-ssg-eks-ds-1.2.xml (Failed)
```

**Comment by ggbecker** [comment]
These PRs fix issues around eks and ocp products in regards to SCAP validation. They also disable some tests for EKS which are expected to fail in case OpenSCAP is < 1.4.0.
