### ISSUE TITLE
Fail test scenario for service_pcscd_enabled errors with Ansible remediation (RHEL9)

### ISSUE THREAD

**Issue by Achilleasein** [ComplianceAsCode/content#8002]
#### Description of problem:
For the following rule: smart_card_login/rule_pcscd_enabled
the ansible rule check fails. 

#### SCAP Security Guide Version:
scap-security-guide-0.1.57-5.el9 and higher

#### Operating System Version:
RHEL8.6|9

### Steps to Reproduce:
1. `python3 tests/test_suite.py rule --libvirt qemu:///session test-suite-rhel9 --remediate-using ansible --datastream build/ssg-rhel9-ds.xml --scenario service_disabled service_pcscd_enabled`

**Comment by Mab879** [comment]
This rule appears to used only in the PCI-DSS profile in RHEL9.

**Comment by mildas** [comment]
Updated with steps how to reproduce.
