### ISSUE TITLE
Requesting checksums be provided alongside the release binaries

### ISSUE THREAD

**Issue by mjmst74** [ComplianceAsCode/content#8017]
#### Description of problem:
Would it be possible to start providing checksums, or GPG signatures, along with the binaries on the https://github.com/ComplianceAsCode/content/releases/ page?

**Comment by yuumasato** [comment]
Hi, I believe it should be simple to start providing checksums, not sure about GPG signatures, would have to take a look into it.

**Comment by lenox-joseph** [comment]
I suspect if you want signatures and you're targeting a Linux platform, it's probably better to wait on a packager to get to it.

**Comment by marcusburghardt** [comment]
Checksums are already provided.
