### ISSUE TITLE
Templating of test scenarios in the test suite is messy

### ISSUE THREAD

**Issue by matejak** [ComplianceAsCode/content#8053]
How templated tests are handled:

- Templated tests are [picked up at the moment of rule collection](https://github.com/ComplianceAsCode/content/blob/ba20d1597265070ea934353662d7d86ab395cefe/tests/ssg_test_suite/common.py#L577).
- Duplicate scenarios are f[iltered out by default](https://github.com/ComplianceAsCode/content/blob/ba20d1597265070ea934353662d7d86ab395cefe/tests/ssg_test_suite/rule.py#L215) (if tests of multiple rules of the same template are requested)
- Tests are [aggregated by the rule ID](https://github.com/ComplianceAsCode/content/blob/ba20d1597265070ea934353662d7d86ab395cefe/tests/ssg_test_suite/common.py#L320) (including templated scenarios), and dispatched to the remote machine.
- Tests are executed - previous events ensure that requested scenarios are available on the remote environment.

Issues with this:

- Templated tests are identified twice - once so scenarios can be collected, and for the second time so that they can get transferred to the testing machine. This increases maintenance costs. A cleaner approach would be to make a list once and then just pass it on in a read-only mode.
- The function [rule_should_be_tested](https://github.com/ComplianceAsCode/content/blob/ba20d1597265070ea934353662d7d86ab395cefe/tests/ssg_test_suite/rule.py#L225) got really complex, it is no longer clear what are the criteria that result in "pass".
- The preference of rule scenarios over templated ones is achieved by performing file copy in a certain order, the intention to prefer something doesn't have any imprint in the source code.

**Comment by jan-cerny** [comment]
Some of the items will be improved by https://github.com/ComplianceAsCode/content/pull/8751

**Comment by jan-cerny** [comment]
The templated tests are no longer collected twice since https://github.com/ComplianceAsCode/content/pull/8883
