### ISSUE TITLE
Amazon AWS Centos instance issues 

### ISSUE THREAD

**Issue by ggd97** [ComplianceAsCode/content#8065]
#### Description of problem:
when running the application on a freshly configured ( with updates only) after the program is finished i am unable to use sudo with the default "centos" account.     this account if i am not mistaken is tied to the Pem cert that was utilized when the instance was created,.  if this is the case then that account is covered by the cert already and is secured that way ( you can't log in with username or password with that account)

#### SCAP Security Guide Version:
Content 0.1.59

#### Operating System Version:
Centos 7

#### Steps to Reproduce:

1. created a fresh centos 7 instance from the AMI's
2.did a "sudo yum update" to update the instance to current packages 
3. installed epel-release, scap-security-guide ansible python3  
4. ran the following command: sudo ansible-playbook -i "localhost," -c local /usr/share/scap-security-guide/ansible/rhel7-playbook-stig.yml 
5. the script completes with no errors 

#### Actual Results:
the instance is STIG'ed  to DOD standards and completely locked the user out of the instance

#### Expected Results:
expected results that the software would seen that this was an AWS instance and not locked down the "centos" account as that is the only account that is able to log into the box and "covered" by the instance certificate that was used/ created with the instance.

#### Additional Information/Debugging Steps:
really like the software as i can script a lock down via a script instead of having to mess with all the intricacies of the stig..  other than this one small thing.

**Comment by ggbecker** [comment]
Skipping the following rules (using --skip-tags from ansible) should enable the user to use the public key authentication and sudo privelege escalation without password, although this makes the system non-compliant with certain requirements present in the STIG.

```
sudo ansible-playbook --skip-tags "sshd_disable_empty_passwords,sudo_remove_nopasswd,sudo_restrict_privilege_elevation_to_authorized" -i "localhost," -c local /usr/share/scap-security-guide/ansible/rhel7-playbook-stig.yml
```
