### ISSUE TITLE
[RHEL/6] File permissions and masks...shows how to get ext4 partitions

### ISSUE THREAD

**Issue by iankko** [ComplianceAsCode/content#807]
File permissions and masks...shows how to get ext4 partitions. What about tempfs? We also want /dev/shm to have specific mount options and it might be important to add tempfs partitions to the lists.

**Comment by yuumasato** [comment]
> We also want /dev/shm to have specific mount options and it might be important to add tempfs partitions to the lists.

We have rules for `/dev/shm` mount options:

- [mount_option_dev_shm_nodev](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/permissions/partitions/mount_option_dev_shm_nodev)
- [mount_option_dev_shm_noexec](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/permissions/partitions/mount_option_dev_shm_noexec)
- [mount_option_dev_shm_nosuid](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/permissions/partitions/mount_option_dev_shm_nosuid)

I'm closing this. If any other `tmpfs` rule is needed, please open a new issue.
