### ISSUE TITLE
rhel8 ospp is missing auditd_audispd_syslog_plugin_activated

### ISSUE THREAD

**Issue by comps** [ComplianceAsCode/content#8074]
#### Description of problem:
The current git version is missing `auditd_audispd_syslog_plugin_activated` in `rhel8/ospp.profile` even though other remote-rsyslog-logging related rules are there. Please add this rule to the profile, it seems it was missed while reverting the remote logging disablement, thanks.

#### SCAP Security Guide Version:
becb55f28

**Comment by matejak** [comment]
Correct, removal in #5158 was followed by revert in #6167 and related additions in #5181 and #6181, but `auditd_audispd_syslog_plugin_activated` didn't make it back.

**Comment by marcusburghardt** [comment]
The `auditd_audispd_syslog_plugin_activated` rule is still not in `rhel8/ospp.profile`. Is it intentional?

**Comment by Mab879** [comment]
> The `auditd_audispd_syslog_plugin_activated` rule is still not in `rhel8/ospp.profile`. Is it intentional?

Still true as of today as well.
