### ISSUE TITLE
Multiple files are missing from the release package (or documentation is out-of-date)

### ISSUE THREAD

**Issue by konstruktoid** [ComplianceAsCode/content#8132]
#### Description of problem:

The instructions at https://static.open-scap.org/openscap-1.3/oscap_user_manual.html or https://complianceascode.readthedocs.io/en/latest/manual/developer/02_building_complianceascode.html or https://github.com/ComplianceAsCode/content/blob/master/README.md is missing up-to-date information on how to use or build the content.

#### SCAP Security Guide Version:

scap-security-guide-0.1.60

#### Operating System Version:

Ubuntu 20.04

##### README.md
1.  Follow https://github.com/ComplianceAsCode/content/blob/master/README.md#from-release-zip-files
2. `wget https://github.com/ComplianceAsCode/content/releases/download/v0.1.60/scap-security-guide-0.1.60.tar.bz2`
3. `tar -jvxf scap-security-guide-0.1.60.tar.bz2`
4.  `$ find scap-security-guide-0.1.60/ -iname '*-ds.xml' | wc -l`
`0`
5.  https://github.com/ComplianceAsCode/content/blob/master/README.md#oscap-tool, there's no file named `ssg-rhel7-ds.xml`

##### oscap_user_manual.html

1. Follow https://static.open-scap.org/openscap-1.3/oscap_user_manual.html
2. See above list.

##### 02_building_complianceascode.html

1. Follow https://complianceascode.readthedocs.io/en/latest/manual/developer/02_building_complianceascode.html#downloading-the-source-code
2. `$ export ssg_version="0.1.60" && wget "https://github.com/ComplianceAsCode/content/releases/download/v$ssg_version/scap-security-guide-$ssg_version.tar.bz2"`
3. `$ sha256sum scap-security-guide-0.1.60.tar.bz2`
`dd987cd2c97b5b109f7e8c6123fb8f1d285bc8cff463e542413aef6e9663f357  scap-security-guide-0.1.60.tar.bz2`
4. `$ cd scap-security-guide-0.1.60/build`
`-bash: cd: scap-security-guide-0.1.60/build: No such file or directory`
5. `$ cd scap-security-guide-0.1.60`
`$ bash -x ./build_product ubuntu2004`
`[...]`
`+ test off = on`
`+ set -e`
`+ rm -rf 'build/*'`
`+ cd build`
`./build_product: line 370: cd: build: No such file or directory`

#### Addition information

Building from source works when cloning the repository, but multiple files are missing from the release package.

**Comment by yuumasato** [comment]
Hi,

>     3. `tar -jvxf scap-security-guide-0.1.60.tar.bz2`
> 
>     4. `$ find scap-security-guide-0.1.60/ -iname '*-ds.xml' | wc -l`
>        `0`
> 
>     5. https://github.com/ComplianceAsCode/content/blob/master/README.md#oscap-tool, there's no file named `ssg-rhel7-ds.xml`

The `tar.bz2` is just the source tarball, it doesn't contain the pre-build content, so `ssg-rhel7-ds.xml` is not expected to be there.
For the pre-built content download the `zip` file:
https://github.com/ComplianceAsCode/content/releases/download/v0.1.60/scap-security-guide-0.1.60.zip

 
> ##### 02_building_complianceascode.html
> 
>     1. Follow https://complianceascode.readthedocs.io/en/latest/manual/developer/02_building_complianceascode.html#downloading-the-source-code
> 
>     2. `$ export ssg_version="0.1.60" && wget "https://github.com/ComplianceAsCode/content/releases/download/v$ssg_version/scap-security-guide-$ssg_version.tar.bz2"`
> 
>     3. `$ sha256sum scap-security-guide-0.1.60.tar.bz2`
>        `dd987cd2c97b5b109f7e8c6123fb8f1d285bc8cff463e542413aef6e9663f357  scap-security-guide-0.1.60.tar.bz2`
> 
>     4. `$ cd scap-security-guide-0.1.60/build`
>        `-bash: cd: scap-security-guide-0.1.60/build: No such file or directory`
> 
>     5. `$ cd scap-security-guide-0.1.60`
>        `$ bash -x ./build_product ubuntu2004`
>        `[...]`
>        `+ test off = on`
>        `+ set -e`
>        `+ rm -rf 'build/*'`
>        `+ cd build`
>        `./build_product: line 370: cd: build: No such file or directory`

What seems to be missing is just the `build` directory. I don't know the reason why it is not in the tarball, but I could look it up.

**Comment by konstruktoid** [comment]
From https://github.com/ComplianceAsCode/content/blob/master/README.md#from-release-zip-files:
"Download pre-built SSG zip archive from the release page. Each zip file is an archive with ready-made SCAP source datastreams."

From https://static.open-scap.org/openscap-1.3/oscap_user_manual.html#_getting_scap_content:
"The SCAP content will be installed in the /usr/share/xml/scap/ssg/content/ directory.

On other platforms, you can download the upstream release from GitHub."

**Comment by konstruktoid** [comment]
> 
> The `tar.bz2` is just the source tarball, it doesn't contain the pre-build content, so `ssg-rhel7-ds.xml` is not expected to be there. For the pre-built content download the `zip` file: https://github.com/ComplianceAsCode/content/releases/download/v0.1.60/scap-security-guide-0.1.60.zip
> 

Why is the content different between the .zip and .tar.bz2 files? And where can I find that info?

**Comment by evgenyz** [comment]
The `.tar.bz2` package contains *source code* of the content. The `.zip` package contains *built content*, that it ready to use.

**Comment by evgenyz** [comment]
> From https://static.open-scap.org/openscap-1.3/oscap_user_manual.html#_getting_scap_content:
> "The SCAP content will be installed in the /usr/share/xml/scap/ssg/content/ directory.

This section of the OpenSCAP manual refers to the `scap-security-guide` package which indeed does exactly that when installed. The `ComplianceAsCode` content is the upstream base for `scap-security-guide`.

**Comment by konstruktoid** [comment]
Thanks for the info.
