### ISSUE TITLE
Templated test scenarios for sshd_lineinfile (those who echo bad_value) fail for ansible remediation because of validation

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#8143]
Test scenarios that echo `bad_val` to the ssh config file fail with Ansible remediation because the ansible remediation tries to validate the configuration file and `bad_val` is not a valid configuration for ssh.

`/usr/sbin/sshd -t -f %s`

https://github.com/ComplianceAsCode/content/blob/2d0d6d97760579506bca5027df5d6674f4e886b7/shared/macros-ansible.jinja#L179

_Originally posted by @ggbecker in https://github.com/ComplianceAsCode/content/issues/7525#issuecomment-1024413059_

Solution proposed by @mildas:

`
We can extend problematic templated test scenarios with condition that will select a wrong value based on the correct one, e.g “yes” is correct -> use “no”. But only for common cases (values like yes, no, or 0). Otherwise, add rule specific test scenarios to overwrite the templated ones.
`

The bash remediation doesn't validate the sshd configuration. This might be an opportunity to unify the behavior of both Bash and Ansible remediation.

**Comment by Mab879** [comment]
This has been fixed.
