### ISSUE TITLE
Unable to building content with two groups using separate file paths

### ISSUE THREAD

**Issue by rhmdnd** [ComplianceAsCode/content#8190]
#### Description of problem:

The build process fails if I I create a group to contain rules that happens to share the same name as another group in the benchmark root.

We have dedicated logging rules for OpenShift, and those rules live in `applications/openshift/logging`. In the process of adding another benchmark to target EKS (another kubernetes distribution), I created a similar group for logging checks specific to the EKS platform `applications/kubernetes/eks/logging/`. Building the content failed because there were multiple `logging` groups, even though they live in separate file paths.

#### Steps to Reproduce:

1. Create a new group `applications/foo/logging`
2. Create a new rule in the `logging` group `applications/foo/logging/bar.yml`
3. Build the content

#### Actual Results:

```
[ 38%] [eks-content] generating xccdf-unlinked-resolved.xml
File '/home/lbragstad/Projects/content/build/eks/shorthand.xml' line 951: Element '{http://checklists.nist.gov/xccdf/1.1}Rule': Duplicate key-sequence ['audit_logging'] in key identity-constraint '{http://checklists.nist.gov/xccdf/1.1}selectableItemIdKey'.
File '/home/lbragstad/Projects/content/build/eks/shorthand.xml' line 951: Element '{http://checklists.nist.gov/xccdf/1.1}Rule': Duplicate key-sequence ['audit_logging'] in key identity-constraint '{http://checklists.nist.gov/xccdf/1.1}ruleIdKey'.
File '/home/lbragstad/Projects/content/build/eks/shorthand.xml' line 951: Element '{http://checklists.nist.gov/xccdf/1.1}Rule': Duplicate key-sequence ['audit_logging'] in key identity-constraint '{http://checklists.nist.gov/xccdf/1.1}itemIdKey'.
File '/home/lbragstad/Projects/content/build/eks/shorthand.xml' line 947: Element '{http://checklists.nist.gov/xccdf/1.1}Group': Duplicate key-sequence ['logging'] in key identity-constraint '{http://checklists.nist.gov/xccdf/1.1}selectableItemIdKey'.
File '/home/lbragstad/Projects/content/build/eks/shorthand.xml' line 947: Element '{http://checklists.nist.gov/xccdf/1.1}Group': Duplicate key-sequence ['logging'] in key identity-constraint '{http://checklists.nist.gov/xccdf/1.1}groupIdKey'.
File '/home/lbragstad/Projects/content/build/eks/shorthand.xml' line 947: Element '{http://checklists.nist.gov/xccdf/1.1}Group': Duplicate key-sequence ['logging'] in key identity-constraint '{http://checklists.nist.gov/xccdf/1.1}itemIdKey'.
```

#### Expected Results:

The content renders as expected.

#### Additional Information/Debugging Steps:

I noticed this when working on the following PR: https://github.com/ComplianceAsCode/content/pull/8189

**Comment by Mab879** [comment]
Due to the effort needed this will not happen.
