### ISSUE TITLE
Issues with package: ypserv in multiple profiles

### ISSUE THREAD

**Issue by Achilleasein** [ComplianceAsCode/content#8193]
#### Description of problem:
All the profiles in rhel9 that use ansible have been failing in regression testing.

#### SCAP Security Guide Version:
0.1.61-1.gitcd6de5a.el9

#### Operating System Version:
RHEL-9.0.0-20220206.3

#### Steps to Reproduce:

1. Run the CIS profile using our own scripts.

#### Actual Results:
TASK [Disable service ypserv] **************************************************
fatal: [xxx.xxx.xxx.xxx]: FAILED! => {"changed": false, "msg": "Could not find the requested service ypserv.service: host"}

#### Expected Results:

Remediation to work normally.

#### Additional Information/Debugging Steps:

* There are more fatal messages in log files but the seem unrelated to this error.
* The whole profile fails before running any rule.

**Comment by Achilleasein** [comment]
Found new error about those profiles:
fatal: [xxx.xxx.xxx.xxx]: FAILED! => {"changed": false, "msg": "Could not find the requested service autofs.service: host"}

**Comment by mildas** [comment]
This has been fixed in #8226
