### ISSUE TITLE
Failing test scenario: abrt-plugin-logger_removed 

### ISSUE THREAD

**Issue by Achilleasein** [ComplianceAsCode/content#8243]
#### Description of problem:
Test scenario: abrt-plugin-logger_removed fails, package not found, cannot install/uninstall

#### SCAP Security Guide Version:
scap-security-guide-0.1.61-1.git95cd193.el8

#### Operating System Version:
RHEL-8.6.0-20220213.3

#### Steps to Reproduce:

1. Install latest rhel8.6
2. yum install abrt-plugin-logger

#### Actual Results:
Error: Unable to find a match: abrt-plugin-logger

#### Expected Results:

Packaged removed/installed properly.

#### Additional Information/Debugging Steps:

All the other tests for abrt execute install/remove normally.

**Comment by marcusburghardt** [comment]
@mildas can we close this issue or is it still valid?

**Comment by Mab879** [comment]
This package isn't in RHEL 8, no action needed.
