### ISSUE TITLE
Remediations for usbguard do not all have conditionals to regard containers as not applicable.

### ISSUE THREAD

**Issue by younkfunk** [ComplianceAsCode/content#8248]
#### Description of problem:
Remediations for usbguard do not all have conditionals to ignore containers. When generating the remediation script, it includes installing usbguard and this will cause automated builds to fail. 

USBguard is actually not included in the RHEL UBI8 Repositories and it will not install. 

I apologize if this is the wrong space for this, if someone could please redirect me if possible.

#### SCAP Security Guide Version:
scap-security-guide-0.1.61

#### Operating System Version:
RHEL UBI8 8.5 (All RHEL UBI8's)

#### Steps to Reproduce:
1. wget -O ssg-rhel8-ds-1.2.xml https://github.com/RedHatGov/rhel8-stig-latest/blob/master/ssg-rhel8-ds-1.2.xml
2. oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_stig --results-arf arf.xml --fetch-remote-resources ssg-rhel8-ds-1.2.xml
3. oscap xccdf generate fix --result-id xccdf_org.open-scap_testresult_xccdf_org.ssgproject.content_profile_stig --fix-type bash arf.xml > remediation.sh
3. Run the remediation

#### Actual Results:
yum install -y "usbguard"
Red Hat Universal Base Image 8 (RPMs) - BaseOS                                                                                                                          649 kB/s | 796 kB     00:01
Red Hat Universal Base Image 8 (RPMs) - AppStream                                                                                                                       1.9 MB/s | 2.6 MB     00:01
Red Hat Universal Base Image 8 (RPMs) - CodeReady Builder                                                                                                                19 kB/s |  16 kB     00:00
No match for argument: usbguard
Error: Unable to find a match: usbguard

This causes builds on RHEL UBI8 to fail

#### Expected Results:
Applicable remediations are applied successfully (usbguard is not applicable to containers and is skipped) and build continues.

#### Additional Information/Debugging Steps:
In the fix section of ssg-rhel8-ds-1.2.xml where it's building the remediation script. 2 of the 7 usbguard related scripts have containers as not applicable.

Incomplete Logic:
BASH = if ! grep -q s390x /proc/sys/kernel/osrelease; then

Expected Logic:
BASH = if ! grep -q s390x /proc/sys/kernel/osrelease &amp;&amp; { [ ! -f /.dockerenv ] &amp;&amp; [ ! -f /run/.containerenv ]; }; then
Ansible = ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]

Missing from:
xccdf_org.ssgproject.content_rule_package_usbguard_installed
xccdf_org.ssgproject.content_rule_configure_usbguard_auditbackend
xccdf_org.ssgproject.content_rule_usbguard_allow_hid
xccdf_org.ssgproject.content_rule_usbguard_allow_hid_and_hub
xccdf_org.ssgproject.content_rule_usbguard_allow_hub

Included in:
xccdf_org.ssgproject.content_rule_service_usbguard_enabled 
xccdf_org.ssgproject.content_rule_usbguard_generate_policy

**Comment by ggbecker** [comment]
A similar line: 
https://github.com/ComplianceAsCode/content/blob/58239389c6678621cd5557e5c988651fd5cead1a/linux_os/guide/services/usbguard/service_usbguard_enabled/rule.yml#L17

Should be added to all these rules:
[
xccdf_org.ssgproject.content_rule_package_usbguard_installed](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/services/usbguard/package_usbguard_installed/rule.yml)
[xccdf_org.ssgproject.content_rule_configure_usbguard_auditbackend](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/services/usbguard/configure_usbguard_auditbackend/rule.yml)
[xccdf_org.ssgproject.content_rule_usbguard_allow_hid](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/services/usbguard/usbguard_allow_hid/rule.yml)
[xccdf_org.ssgproject.content_rule_usbguard_allow_hid_and_hub](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/services/usbguard/usbguard_allow_hid_and_hub/rule.yml)
[xccdf_org.ssgproject.content_rule_usbguard_allow_hub](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/services/usbguard/usbguard_allow_hub/rule.yml)

**Comment by ggbecker** [comment]
This is the correct place to post this issue @younkfunk

**Comment by younkfunk** [comment]
Closing this issue to move focus to https://github.com/RedHatGov/rhel8-stig-latest/issues/83

**Comment by ggbecker** [comment]
If we believe that those rules should not be applicable to containers in general, no matter the distro, then we should mark them as `platform: machine`, even though you can install these packages in some containers.
