### ISSUE TITLE
firewalld failure of rhel7 stig  

### ISSUE THREAD

**Issue by ggd97** [ComplianceAsCode/content#8260]
found that if i run the playbook on an Amazon AWS instance that the playbook will fail when it attempts to configure the firewalld portion of the playbook.    however i have found a fix for this by using the following code at the beginning of the playbook:
`   tasks:
    - name: "Install packages"
      become: yes
      yum:
	name:
         - firewalld
        state: latest`

i placed this code right after the vars. and i ran the playbook and it worked flawlessly.

**Comment by ggd97** [comment]
i did use root   as it was in the playbook and it failed..  however when i added the code it worked like a champ..

**Comment by marcusburghardt** [comment]
It is about permissions on executing the playbook.
