### ISSUE TITLE
RHEL7- stig AIDE issue

### ISSUE THREAD

**Issue by ggd97** [ComplianceAsCode/content#8270]
when i am running the Rhel7 stig  i get the following error message: 
[WARNING]: The value 5 (type int) in a string field was converted to u'5' (type string). If this does not look like what you expect, quote the entire value to ensure it does not change.
[WARNING]: The value 4 (type int) in a string field was converted to u'4' (type string). If this does not look like what you expect, quote the entire value to ensure it does not change.
[WARNING]: The value 0 (type int) in a string field was converted to u'0' (type string). If this does not look like what you expect, quote the entire value to ensure it does not change.
fatal: [10.4.0.189]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "backup": false, 
            "cron_file": null, 
            "day": "*", 
            "disabled": false, 
            "env": null, 
            "hour": "4", 
            "insertafter": null, 
            "insertbefore": null, 
            "job": "/usr/sbin/aide --check", 
            "minute": "5", 
            "month": "*", 
            "name": "run AIDE check", 
            "reboot": false, 
            "special_time": null, 
            "state": "present", 
            "user": "root", 
            "weekday": "0"
        }
    }, 
    "msg": "must be privileged to use -u\n"

i have never ran into this issue before when i have used this playbook in the past..  did something change?
i am running RHEL 7.9

**Comment by ggbecker** [comment]
This is probably some problem with the package itself. Try running:

`rpm --setperms cronie-anacron-1.4.11-24.el7_9.x86_64`

manually and see the results if it returns the same

**Comment by ggbecker** [comment]
The message: `"msg": "must be privileged to use -u\n"` indicates that maybe you need to run the playbook as root or with sudo. Feel free to reopen this issue if it still affects you.
