### ISSUE TITLE
Ubuntu 20.04 Disable Core Dumps for SUID programs conflicts with 'apport'

### ISSUE THREAD

**Issue by tbalbers** [ComplianceAsCode/content#8284]
#### Description of problem:
When running oscap-ssh using the newest Ubuntu guide, ssg-ubuntu2004-ds-1.2.xml

Rule ID: xccdf_org.ssgproject.content_rule_sysctl_fs_suid_dumpable

Fails, because fs.suid_dumpable = 2, even though a file in /etc/sysctl.d set it = 0.

Cause: apport-2.20.11-0ubuntu27.21 has an initialization script: /etc/init.d/apport which sets the value:
echo 2 > /proc/sys/fs/suid_dumpable         # in line 59.

#### SCAP Security Guide Version:
0.1.6.0

#### Operating System Version:
oscap-ssh(openscap-1.3.5-6) runs on a RHEL 8.5
scanned host is a Ubuntu 20.04 server(libopenscap8-1.2.16-2ubuntu3.2), freshly updated running in FIPS-mode.

#### Steps to Reproduce:

1. Have a freshly installed Ubuntu 20.04 server
2. run: oscap-ssh --sudo scapadm@127.0.0.1 2222 xccdf eval --datastream-id scap_org.open-scap_datastream_from_xccdf_ssg-ubuntu2004-xccdf-1.2.xml --xccdf-id scap_org.open-scap_cref_ssg-ubuntu2004-xccdf-1.2.xml --profile xccdf_org.ssgproject.content_profile_cis_level2_server --oval-results --results /tmp/xccdf-results.xml --results-arf /tmp/arf.xml --report /tmp/report.html ssg-ubuntu2004-ds-1.2.xml
3. The check for fs.suid_dumpable=0 fails
4.
5.

#### Actual Results:
The check for fs.suid_dumpable=0 fails

#### Expected Results:
Unknown, it shouldn't conflict with 'apport'. 

#### Additional Information/Debugging Steps:
Removal of 'apport' is not feasible, since this removes 'ubuntu server' metapackage which is essential for managing updates to the OS.

**Comment by rossengeorgiev** [comment]
You can disable apport without removing: `sed -i 's/^enabled=1/enabled=0/g' /etc/default/apport`

**Comment by tbalbers** [comment]
great, thanks!

**Comment by konstruktoid** [comment]
> Removal of 'apport' is not feasible, since this removes 'ubuntu server' metapackage which is essential for managing updates to the OS.

Is it? In what way?
I've been removing `apport`, `popularity-contest`, `whoopsie` and a few others (https://github.com/konstruktoid/ansible-role-hardening/blob/master/defaults/main/packages.yml#L3-L22) for quite some time without any issues.

**Comment by rossengeorgiev** [comment]
Yeah, should be fine to remove. I did at some point encounter removal of `apport` trying to remove other packages. Disabling it via config file is the most persistent option as other packages may reintroduce the package or dist-upgrade most certainly will. The alternative then is to config `apt` to ignore it, essentially blacklisting.
