### ISSUE TITLE
Build warning on FC34 around shared/references/disa-os-srg-v2r1.xm

### ISSUE THREAD

**Issue by lenox-joseph** [ComplianceAsCode/content#8290]
#### Description of problem:
Spotted this when running a build for my PR on the Fedora Core 34 
```
warning: failed to load external entity "/__w/content/content/shared/references/disa-os-srg-v2r1.xml"
```

https://github.com/ComplianceAsCode/content/runs/5414923376?check_suite_focus=true#step:6:838

#### SCAP Security Guide Version:
dfad74d379efa75d4ceeef039b8decf51e5be087

#### Operating System Version:
Fedora Core 34 (build agent)

**Comment by Mab879** [comment]
Fixed by #8370
