### ISSUE TITLE
Ubuntu 20.04 + AIDE documentation errors

### ISSUE THREAD

**Issue by slodplaadmin** [ComplianceAsCode/content#8305]
#### Description of problem:

See:  https://static.open-scap.org/ssg-guides/ssg-ubuntu2004-guide-index.html

There are multiple errors with the AIDE sections.

- Rule "Build and Test AIDE Database" instructs the reader to use "/usr/sbin/aide" as the executable.  However, in Ubuntu 20.04, the "apt-get install aide" puts the executable under "/usr/bin/aide".

- Rule "Configure Periodic Execution of AIDE" cites as crontab entries:  "05 4 * * * root --check".  This is incorrect you are failing to specify the command to be run by cron...you are only specifying the "--check" option to be run with an unspecified command.

- In addition to correcting the path to the AIDE binary, it seems as though maybe "/usr/bin/aide.wrapper" should be used instead of the "/usr/bin/aide" binary?

#### SCAP Security Guide Version:

0.1.60

#### Operating System Version:

Ubuntu 20.04

#### Steps to Reproduce:

Begin by installing AIDE on an Ubuntu 20.04 system:
1.  apt-get install aide

For Rule:  "Build and Test AIDE Database"
2.  /usr/sbin/aide --init         # error will occur
3.  /usr/sbin/aide --check     # error will occur

For aide.wrapper vs. aide binary:
4.  /usr/bin/aide --check        # error will occur
5.  /usr/bin/aide --init            # error will occur

#### Actual Results:

**"/usr/sbin" vs. "/usr/bin":**

root@server:~# ls /usr/sbin/aide*
/usr/sbin/aideinit

root@server:~# ls /usr/bin/aide*
/usr/bin/aide  /usr/bin/aide-attributes  /usr/bin/aide.wrapper

**"aide" binary vs. "aide.wrapper" script:**

root@server:~# /usr/bin/aide --init
Couldn't open file /var/lib/aide/please-dont-call-aide-without-parameters/aide.db.new for writing

root@server:~# /usr/bin/aide --check
Couldn't open file /var/lib/aide/please-dont-call-aide-without-parameters/aide.db for reading

#### Expected Results:

**"aide" binary vs. "aide.wrapper" script:**

root@server:~# /usr/bin/aide.wrapper --check
Start timestamp: 2022-03-07 20:03:24 +0000 (AIDE 0.16.1)
AIDE found differences between database and filesystem!!
Verbose level: 6
(stuff snipped for brevity)
End timestamp: 2022-03-07 20:09:50 +0000 (run time: 6m 26s)

root@server:~# /usr/bin/aide.wrapper --init
Start timestamp: 2022-03-07 20:14:46 +0000 (AIDE 0.16.1)
AIDE initialized database at /var/lib/aide/aide.db.new
Verbose level: 6
(stuff snipped for brevity)
End timestamp: 2022-03-07 20:20:58 +0000 (run time: 6m 12s)

**Comment by ggbecker** [comment]
> * Rule "Build and Test AIDE Database" instructs the reader to use "/usr/sbin/aide" as the executable.  However, in Ubuntu 20.04, the "apt-get install aide" puts the executable under "/usr/bin/aide".
> 
> * Rule "Configure Periodic Execution of AIDE" cites as crontab entries:  "05 4 * * * root --check".  This is incorrect you are failing to specify the command to be run by cron...you are only specifying the "--check" option to be run with an unspecified command.

https://github.com/ComplianceAsCode/content/pull/8315 should fix at least these two problems

**Comment by dodys** [comment]
I believe that what you will actually want to use is  `/usr/sbin/aideinit` for building and testing the database.

for more context: https://www.rapid7.com/blog/post/2017/06/30/how-to-install-and-configure-aide-on-ubuntu-linux/

**Comment by huornlmj** [comment]
Need to manually install aideinit by
```console
$ sudo apt install aide-common
```

**Comment by dodys** [comment]
> Need to manually install aideinit by
> 
> ```
> $ sudo apt install aide-common
> ```

if you run:
`sudo apt install aide`

it should install aide-common as well, that should all be part of package_aide_installed rule.

**Comment by ggbecker** [comment]
> I believe that what you will actually want to use is `/usr/sbin/aideinit` for building and testing the database.
> 
> for more context: https://www.rapid7.com/blog/post/2017/06/30/how-to-install-and-configure-aide-on-ubuntu-linux/

The ansible snippet needs to be update to use aideinit in case of Ubuntu: https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/software/integrity/software-integrity/aide/aide_build_database/ansible/shared.yml#L13

either that or create a new `ubuntu.yml` file that will be included in Ubuntu related datastreams.

**Comment by huornlmj** [comment]
@ggbecker is it safe to change that file in the repo though?  I see the following in the Ansible playbook, suggesting that it's perhaps not the correct place to issue the fix, and that perhaps it's in the SCAP profile instead:

```console
# This file was generated by OpenSCAP 1.3.6 using:
# $ oscap xccdf generate fix --profile xccdf_org.ssgproject.content_profile_cis_level1_server --fix-type ansible xccdf-file.xml
#
# This Ansible Playbook is generated from an OpenSCAP profile without preliminary evaluation.
```

**Comment by dodys** [comment]
do note that we (Canonical) don't fully support ansible and more rules might need ansible fixes in order to work.

**Comment by konstruktoid** [comment]
Example Ansible task for both `ansible_os_family == "Debian"` and `ansible_os_family == "RedHat"`: https://github.com/konstruktoid/ansible-role-hardening/blob/master/tasks/aide.yml

**Comment by crouth-redge** [comment]
There are also issues with the AIDE DB init checks.

None of these DB checks should be failing. We have the correct configuration and the DB is initialized. However it fails them.

The bash remediation script doesn't even change anything, because it has exactly the correct configuration.

![Screenshot 2023-10-05 at 3 36 01 PM](https://github.com/ComplianceAsCode/content/assets/142341488/0872eab0-a442-48cd-aa25-56d3f271d214)
![Screenshot 2023-10-05 at 3 36 10 PM](https://github.com/ComplianceAsCode/content/assets/142341488/5648c64e-1a4b-48b5-9326-e072538301b1)

aide.conf:
```
database_in=file:/var/lib/aide/aide.db
database_out=file:/var/lib/aide/aide.db.new
database_new=file:/var/lib/aide/aide.db.new
```

/var/lib/aide:
```
root@ip-192-168-6-86:~# ls -lhs /var/lib/aide/
total 76M
38M -rw------- 1 root root 38M Oct  5 15:27 aide.db
38M -rw------- 1 root root 38M Oct  5 15:27 aide.db.new

```

**Comment by dodys** [comment]
> There are also issues with the AIDE DB init checks.
> 

Please open a new bug for it and give full instructions on what you are running as this does not relate to this bug report

I'm closing this bug since a lot changed since report.
