### ISSUE TITLE
Template `audit_rules_syscall_events` lacks documentation

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#8323]
#### Description of problem:

The template `audit_rules_syscall_events` introduced in https://github.com/ComplianceAsCode/content/pull/7529 lacks documentation similar to documentation from https://complianceascode.readthedocs.io/en/latest/templates/template_reference.html#available-templates

**Comment by ggbecker** [comment]
@rumch-se It would be great if could add the documentation for this template.

**Comment by rumch-se** [comment]
@ggbecker - I have added the documentation requested. https://github.com/ComplianceAsCode/content/pull/8324
