### ISSUE TITLE
Maintainership of the project doesn't scale

### ISSUE THREAD

**Issue by matejak** [ComplianceAsCode/content#8344]
## Description of problem:

There is a high rate of activity in the project, but the count of PRs that are not merged is really high - over 40. This is unpleasant, as it leads to frustration both on the side of maintainers who are pressured to review them, and on side of contributors, whose PRs are stuck.

The base of project's maintainers needs to expand accordingly, and some sort of rule set should support this and assure that chaos won't break out.

There as a need to:
- Allow independent groups in the content project to work at their own pace on parts of the project that don’t influence each other.
- Introduce enter and exit criteria for roles with elevated privileges so the hierarchy can self-organize.
- Define a framework for organizations to join the project and assume responsibilities.
- Make sure that the project stays coherent and individual parts contribute to its value, and the project doesn’t become a disgusting spaghetti soup.

**Comment by marcusburghardt** [comment]
@matejak , I believe this issue can already be closed.

The mentioned points are already covered in the [Governance Rules](https://complianceascode.readthedocs.io/en/latest/manual/developer/01_introduction.html#governance)
And the process was already executed with success:
- #9684 
- #9713 
- #9731 

I do believe it is scalable and transparent. Do you agree to close this issue?

**Comment by matejak** [comment]
I agree and I will gladly do so - thank you for your involvement!
