### ISSUE TITLE
RHEL 8 - `accounts_umask_interactive_users` results in `error` during oscap scan

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#8353]
#### Description of problem:
After STIG with GUI kickstart installation, during oscap scan (only check, no `--remediate`!), `accounts_umask_interactive_users` rule results in `error`.

#### SCAP Security Guide Version:
ece8437

#### Operating System Version:
RHEL 8

#### Steps to Reproduce:

1. Install latest RHEL 8 using kickstart with STIG with GUI profile
2. `oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_stig_gui --results xccdf_org.ssgproject.content_profile_stig_gui-xccdf-results.xml /tmp/ssg-rhel8-ds.xml`

#### Actual Results:
 `accounts_umask_interactive_users` results in `error`

#### Expected Results:
`accounts_umask_interactive_users` results in `pass`

#### Additional Information/Debugging Steps:
OVAL details:

<h4><span class="label label-primary">Umask must not be defined in user initialization files</span> 
        <span class="label label-default">oval:ssg-test_accounts_umask_interactive_users:tst:1</span> 
        <span class="label label-danger">error</span></h4><h5>No items have been found conforming to the following objects:</h5><h5>Object <strong><abbr title="Umask value from initialization files">oval:ssg-object_accounts_umask_interactive_users:obj:1</abbr></strong> of type
                <strong>textfilecontent54_object</strong></h5>

Path | Filename | Pattern | Instance
-- | -- | -- | --
/home/admin /home/testuser | ^\..* | ^[\s]*umask\s* | 1

Notice the `Path` in OVAL details. It seems 2 paths are being checked in single object.

**Comment by nightmared** [comment]
Hello, I have also seen this behavior in the past on a RHEL8 workstation system (albeit maybe for different reasons).

When looking into it, I discovered that the presence of some binary files (like the authentication cookies pulseaudio creates in `/home/<username>/.esd_auth`) can cause the test to error out (seems like openscap doesn't like performing regexps on binary files, which is quite understandable).
Deleting the pulseaudio cookies is often enough to pass the test.

Maybe there is an OVAL parameter I'm unaware of that could exclude binary files (or simply ignore regexp errors)?

**Comment by nightmared** [comment]
Whoops, sorry about that then. Never mind me!

**Comment by jan-cerny** [comment]
Yes, it's a problem in OpenSCAP, not in content. It would be hard to workaround it in content because you can't detect binary files in OVAL and maintaining a list of offending files isn't feasible.

There is a PR that will fix it: https://github.com/OpenSCAP/openscap/pull/1849

> <p dir="auto">Notice the <code>Path</code> in OVAL details. It seems 2 paths are being checked in single object.</p>

This is actually normal  in OVAL. In this case the file path is specified using an OVAL variable that is backed by OVAL object that matches multiple items, therefore the variable has multiple values and a scanner is supposed to check all of them. But, the visualization of this situation in HTML report is bad.
