### ISSUE TITLE
RHEL 7 - `accounts_users_home_files_permissions` fails even though file permissions are correct

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#8355]
#### Description of problem:
After running `$ sudo chmod 0750 -R /home/USER`, `accounts_users_home_files_permissions` results in `fail`.
But rule itself suggests the command:
> Set the mode on files and directories in the local interactive user home directory with the following command:
> $ sudo chmod 0750 /home/USER/FILE_DIR

#### SCAP Security Guide Version:
ece8437

#### Operating System Version:
RHEL 7.9

#### Steps to Reproduce:
1. Install RHEL 7.9 using kickstart with STIG profile. In the kickstart, add user in post section, e.g. via `useradd -G wheel testuser`
2. After installation, `chmod -R 0750 /home/testuser` to have expected permissions, because we add user in post section that runs after OAA
3. `oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_stig --report  xccdf_org.ssgproject.content_profile_stig.html /tmp/ssg-rhel7-ds.xml 2>stderr.txt`

#### Actual Results:
`accounts_users_home_files_permissions` fails

#### Expected Results:
`accounts_users_home_files_permissions` passes

#### Additional Information/Debugging Steps:
OVAL details:
<h4><span class="label label-primary">All home directories have proper permissions</span> 
                <span class="label label-danger">failed</span> because of these items:</h4>

Path | Type | UID | GID | Size (B) | Permissions
-- | -- | -- | -- | -- | --
/home/testuser/.bash_logout | regular | 1000 | 1000 | 18 | rwxr-x---
/home/testuser/.bash_profile | regular | 1000 | 1000 | 193 | rwxr-x---
/home/testuser/.bashrc | regular | 1000 | 1000 | 231 | rwxr-x---
/home/testuser/.ssh/authorized_keys | regular | 1000 | 1000 | 211 | rwxr-x---
/home/testuser/oscap_version | regular | 1000 | 1000 | 5613 | rwxr-x---
/home/testuser/stderr.txt | regular | 1000 | 1000 | 541 | rw-rw-r--

`/home/testuser/stderr.txt` permissions are not correct as the file is created during `oscap xccdf eval` (expected).
However, other permissions seem to be correct - 0750 - and those files should not be listed at all.

**Comment by yuumasato** [comment]
@mildas Is this issue about the files in the HTML report?

I think the report doesn't filter the OVAL results to only show the items that caused the rule to fail, so the single file that caused the rule to fail is reported together with the other passing files.

**Comment by mildas** [comment]
@yuumasato Yes, the list of files is taken from HTML report. Aha, thanks for the information. I will try it again with correct permissions on all files.

**Comment by yuumasato** [comment]
> I think the report doesn't filter the OVAL results to only show the items that caused the rule to fail, so the single file that caused the rule to fail is reported together with the other passing files.

@jan-cerny Do you have more info about this?

**Comment by jan-cerny** [comment]
@yuumasato @mildas The HTML report shows all items that match the OVAL object. It shows both items that match the OVAL state and that don't match the OVAL state. So it shows also items that are OK. Unfortunately, the OVAL results doesn't contain information whether an item doesn't match the state, so it isn't possible to filter out not-offending items from the HTML report.  Check this template: https://github.com/OpenSCAP/openscap/blob/367170182664bf34536266b5495c12580b4ddb8b/xsl/xccdf-report-oval-details.xsl#L69 So I think the problem here is the stderr.txt.
