### ISSUE TITLE
Transform `user_list` into a product attribute (follow up from #8426)

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#8429]
#### Description of problem:

The jinja variable used by rules changed in https://github.com/ComplianceAsCode/content/pull/8426 should be transformed into a product attribute that can be overridden. Essentially this attribute can be a list and then processed by the build system to create the correct regex string to be used by the OVAL checks.

Some pointers in the code where to change:
https://github.com/ComplianceAsCode/content/blob/master/ssg/products.py#L38
https://github.com/ComplianceAsCode/content/blob/master/ssg/constants.py#L462-L463

**Comment by marcusburghardt** [comment]
@ggbecker , maybe this is no longer necessary after https://github.com/ComplianceAsCode/content/pull/10215 . What do you think?

**Comment by ggbecker** [comment]
Sounds reasonable.
