### ISSUE TITLE
grub2_audit_argument unrecognized argument

### ISSUE THREAD

**Issue by dodys** [ComplianceAsCode/content#8464]
#### Description of problem:
Commit id fac0aeb351 introduced the `--update-kernel=ALL` option to `update-grub` command.
This fails on Ubuntu 20.04:
```
Remediating rule 53/184: 'xccdf_org.ssgproject.content_rule_grub2_audit_argument'
 + '[' '!' -f /.dockerenv ']'
 + '[' '!' -f /run/.containerenv ']'
 + grep -q installed
 + dpkg-query --show '--showformat=${db:Status-Status}\n' grub2-common
 + grep -q '^GRUB_CMDLINE_LINUX=.*audit=.*"' /etc/default/grub
 + sed -i 's/\(^GRUB_CMDLINE_LINUX=".*\)"/\1 audit=1"/' /etc/default/grub
 + update-grub --update-kernel=ALL --args=audit=1
 Unrecognized option `--update-kernel=ALL'
```

FYI @matejak 

#### SCAP Security Guide Version:
5.11, 

#### Operating System Version:
Ubuntu 20.04

#### Steps to Reproduce:

1. ./build_product -j4 ubuntu2004 -o'5.11'
2. ./test_suite.py profile --libvirt 'qemu:///system' 'cac-focal-amd64' --datastream ../build/ssg-ubuntu2004-ds-1.2.xml --remediate-using bash stig
3. check results and remediation log

#### Actual Results:
Rule failing

#### Expected Results:
Rule to pass

**Comment by matejak** [comment]
What should be the right set of options to pass? Would `update-grub --args=audit=1` work?

**Comment by dodys** [comment]
> What should be the right set of options to pass? Would `update-grub --args=audit=1` work?

No, `update-grub` doesn't accept args, except:
```
  -o, --output=FILE       output generated config to FILE [default=stdout]
  -h, --help              print this message and exit
  -v, --version           print the version information and exit
```

So I agree with PR #8578
