### ISSUE TITLE
Remove rules not applicable in RHEL9 STIG from SRG mapping

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#8472]
https://github.com/ComplianceAsCode/content/blob/0dbd1dea7d85332494bf5dc2e444c205dad3c7e0/controls/stig_rhel9/SRG-OS-000073-GPOS-00041.yml#L11-L12

@Mab879

**Comment by ggbecker** [comment]
These two rules are not part of RHEL8 STIG so there is a high chance that they won't be part of the RHEL9 STIG:

https://github.com/ComplianceAsCode/content/blob/b1397138a0dc989efd6bc3d83a6376c9e6fbde65/controls/srg_gpos/SRG-OS-000073-GPOS-00041.yml#L11-L13

**Comment by ggbecker** [comment]
@Mab879 shall we remove them from the SRGs?

**Comment by Mab879** [comment]
Yes, if they don't need to be in the STIG.
