### ISSUE TITLE
RHEL 8 CIS Server Level 2 - ansible-playbook fatal error on `Deactivate Wireless Network Interfaces` task

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#8485]
#### Description of problem:
During CIS Server Level 2 `ansible-playbook`, the playbooks is terminated by fatal error caused by `Deactivate Wireless Network Interfaces` task.

#### SCAP Security Guide Version:
a8eee3a

#### Operating System Version:
RHEL 8

#### Steps to Reproduce:

1. `ansible-playbook --skip-tags ensure_gpgcheck_never_disabled,configure_opensc_nss_db --private-key=/root/.ssh/ssg_id_ecdsa -i "192.168.122.178," /usr/share/scap-security-guide/ansible/rhel8-playbook-cis.yml`

#### Actual Results:
```
TASK [Deactivate Wireless Network Interfaces] **********************************
fatal: [192.168.122.178]: FAILED! => {"changed": true, "cmd": ["nmcli", "radio", "wifi", "off"], "delta": "0:00:50.056494", "end": "2022-04-02 10:19:07.257086", "msg": "non-zero return code", "rc": 1, "start": "2022-04-02 10:18:17.200592", "stderr": "Error: failed to set Wi-Fi radio: Timeout was reached", "stderr_lines": ["Error: failed to set Wi-Fi radio: Timeout was reached"], "stdout": "", "stdout_lines": []}
```

#### Expected Results:
Ansible playbook finishes successfully

**Comment by mildas** [comment]
Yes, it might be related to the environment, because there is no wi-fi module available. Customers that don't have wi-fi module will hit this issue.

**Comment by marcusburghardt** [comment]
> Yes, it might be related to the environment, because there is no wi-fi module available. Customers that don't have wi-fi module will hit this issue.

I tried to reproduce also in VMs without wi-fi devices and no wi-fi related modules loaded. The `nmcli` command always returned success and never returned `timeout`. Then I tried to break the `nmcli` requirements, but this also returned errors different from `timeout`.
