### ISSUE TITLE
Staled content image: `quay.io/complianceascode/ocp4:latest`

### ISSUE THREAD

**Issue by Vincent056** [ComplianceAsCode/content#8495]
Description of problem:

The `quay.io/complianceascode/ocp4:latest` image seems stale, the last update to it was from two months ago. We use this image as our compliance operator upstream image as well as in our CI.

**Comment by rhmdnd** [comment]
Thanks for filing the bug. Providing some additional context.

I'm getting the following error when I run the tests locally:

```
helpers.go:808: E2E-FAILURE: The expected result for the enable_fips_mode rule didn't match. Expected 'PASS', Got 'FAIL'
<snip>
=== RUN   TestE2e/We_should_have_the_same_number_of_check_results_in_each_scan
    e2e_test.go:130: There amount of check results are the same: init -> 472  end 472
=== RUN   TestE2e/We_should_have_less_failures
    e2e_test.go:140: There are less failures now: init -> 370  end 4
=== RUN   TestE2e/We_should_have_no_errors_or_invalid_results
--- FAIL: TestE2e (3457.01s)
    --- PASS: TestE2e/Parameter_setup_and_validation (3.68s)
    --- PASS: TestE2e/Operator_setup (40.96s)
    --- PASS: TestE2e/Prereqs_setup (68.80s)
    --- FAIL: TestE2e/Run_first_compliance_scan (232.81s)
    --- PASS: TestE2e/Wait_for_Remediations_to_apply (1130.61s)
    --- PASS: TestE2e/Apply_manual_remediations (3.41s)
    --- PASS: TestE2e/Wait_for_manual_Remediations_to_apply (761.38s)
    --- PASS: TestE2e/Check_for_remediations_with_dependencies_before_scan_2 (0.13s)
    --- PASS: TestE2e/Run_compliance_scan_#2 (128.98s)
    --- PASS: TestE2e/Scan_2:_Wait_for_Remediations_to_apply (870.85s)
    --- PASS: TestE2e/Check_for_remediations_with_dependencies_before_scan_3 (0.11s)
    --- FAIL: TestE2e/Run_compliance_scan_#3 (155.28s)
    --- PASS: TestE2e/We_should_have_the_same_number_of_check_results_in_each_scan (0.00s)
    --- PASS: TestE2e/We_should_have_less_failures (0.00s)
    --- PASS: TestE2e/We_should_have_no_errors_or_invalid_results (0.00s)
FAIL
FAIL    github.com/ComplianceAsCode/ocp4e2e     3457.026s
FAIL
make: *** [Makefile:20: e2e] Error 1
```

Which causes the scans to fail even though the issue was fixed upstream [0].

[0] https://github.com/ComplianceAsCode/content/pull/8348

**Comment by tmishina** [comment]
Hi, I'd like to understand the status of this issue because I need to use the latest `ocp4` content with Compliance Operator installed via OperatorHub, which automatically uses `quay.io/complianceascode/ocp4:latest`. Is there any plan to fix this? Thanks.

**Comment by rhmdnd** [comment]
We are planning to fix this and we're working on a solution to update the content. Hopefully we'll have something running this week.

**Comment by tmishina** [comment]
Hi, is there any update on this issue? Although I can personally use self-built image, customers using public CO instances such as installed via OperatorHub rely on this public image.

**Comment by rhmdnd** [comment]
We have new content available here https://quay.io/repository/compliance-operator/compliance-operator-content

**Comment by rhmdnd** [comment]
The CI against openshift/compliance-operator is running with the new content. @JAORMX has a patch to push additional content images to ghcr.io, too.
