### ISSUE TITLE
Missing content in title for control SRG-OS-000355-GPOS-00143

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#8515]
https://github.com/ComplianceAsCode/content/blob/3753283b2f00f3dcbf396bd5f66e7053e390dc12/controls/stig_rhel9/SRG-OS-000355-GPOS-00143.yml#L5-L8

it should be:

`
The operating system must, for networked systems, compare internal information system clocks at least every 24 hours with a server which is synchronized to one of the redundant United States Naval Observatory (USNO) time servers, or a time server designated for the appropriate DoD network (NIPRNet/SIPRNet), and/or the Global Positioning System (GPS).
`

It might be a good idea to regenerate the title for every control we have and see if there is any other discrepancy

**Comment by ggbecker** [comment]
@Mab879

**Comment by Mab879** [comment]
The script used to create the files could be changed change the title. Also, we can double check the changelog for the GPOS SRG V2R2 as well to see what titles might need updating.

**Comment by ggbecker** [comment]
> The script used to create the files could be changed change the title. Also, we can double check the changelog for the GPOS SRG V2R2 as well to see what titles might need updating.

Indeed, the script can be enhanced to update fields in case the file already exists

**Comment by ggbecker** [comment]
this makes me think that the whole process should be dynamic which generates all the required files during the build system. Otherwise we can endup with outdated files when a new rule comes in place that covers some other aspect of an SRG item for example. We need to think how to handle this.

**Comment by jan-cerny** [comment]
Fixed in https://github.com/ComplianceAsCode/content/pull/8621
