### ISSUE TITLE
RHEL8 - Not possible to install STIG with GUI using kickstart

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#8527]
#### Description of problem:
It is not possible to install RHEL8 using STIG with GUI kickstart because of package conflict.

#### SCAP Security Guide Version:
49a3e57

#### Operating System Version:
RHEL 8.6

#### Steps to Reproduce:

1. Try to install RHEL8 with STIG with GUI security policy (select `Server with GUI` package selection)

#### Actual Results:
Failed to install

#### Expected Results:
Successfully installed

#### Additional Information/Debugging Steps:
```
[  164.648114] anaconda[1703]: packaging: 
 Problem: package anaconda-gui-33.16.6.7-1.el8.x86_64 requires anaconda-core = 33.16.6.7-1.el8, but none of the providers can be installed
  - package anaconda-core-33.16.6.7-1.el8.x86_64 requires libreport-anaconda >= 2.0.21-1, but none of the providers can be installed
  - package initial-setup-gui-0.3.81.7-1.el8.x86_64 requires anaconda-gui >= 33.16.3.1-1, but none of the providers can be installed
  - package libreport-anaconda-2.9.5-15.el8.x86_64 requires libreport-plugin-rhtsupport = 2.9.5-15.el8, but none of the providers can be installed
  - conflicting requests
  - package libreport-plugin-rhtsupport-2.9.5-15.el8.x86_64 is filtered out by exclude filtering
```

**Comment by ggbecker** [comment]
It seems that it didn't like this new rule: https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/software/system-tools/package_libreport-plugin-rhtsupport_removed/rule.yml

which came to replace the obsolete rule 
https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/software/system-tools/package_abrt-plugin-rhtsupport_removed/rule.yml

the rule needs to be removed from the profile and maybe even from the project if it's really required for OS installation.

**Comment by mildas** [comment]
It's problematic only for STIG GUI installation. We can exclude it same as we do with `xwindows_remove_packages` - https://github.com/ComplianceAsCode/content/blob/master/products/rhel8/profiles/stig_gui.profile

The rule can stay in the `stig` profile. However, we need to keep in mind it is GUI blocking rule and do not include it elsewhere if it can be avoided.
