### ISSUE TITLE
Variables that are not explicitly set in SRG controls files are not exported into SRG spreadsheets

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#8530]
#### Description of problem:
If the variable is not defined in the controls files it won't get substituted. Which means default values are not being taken into account in https://github.com/ComplianceAsCode/content/blob/master/utils/create_srg_export.py

We need to either explicitly set all required values into the control files or load default values.

@Mab879 FYI

**Comment by ggbecker** [comment]
For example:
```
diff --git a/controls/stig_rhel9/SRG-OS-000077-GPOS-00045.yml b/controls/stig_rhel9/SRG-OS-000077-GPOS-00045.yml
index 5642dd2077..4fb8a942c7 100644
--- a/controls/stig_rhel9/SRG-OS-000077-GPOS-00045.yml
+++ b/controls/stig_rhel9/SRG-OS-000077-GPOS-00045.yml
@@ -7,4 +7,5 @@ controls:
             - accounts_password_pam_pwhistory_remember_password_auth
             - accounts_password_pam_pwhistory_remember_system_auth
             - accounts_password_pam_unix_remember
+            - var_password_pam_remember=5
         status: automated
```

**Comment by Mab879** [comment]
I think having the default values would be good idea. 

We also may need someway to ensure that we are defining all variables we are using.

**Comment by Mab879** [comment]
Idea: Make the spreadsheets not compile if a variable is undefined.

**Comment by ggbecker** [comment]
> Idea: Make the spreadsheets not compile if a variable is undefined.

maybe a warning message can be thrown at the output saying that a default value is being used
