### ISSUE TITLE
/usr/share/scap-security-guide/ansible/ol8-playbook-stig.yml fails in yum GPG check

### ISSUE THREAD

**Issue by ThiloSolbrig** [ComplianceAsCode/content#8586]
#### Description of problem:
ansible Playbook /usr/share/scap-security-guide/ansible/ol8-playbook-stig.yml fails in tasks
* Ensure GPG check is globally activated (yum)
* Ensure GPG check Enabled for Local Packages (Yum)

TASK [Ensure GPG check is globally activated (yum)] ************************************************************************************************************************************************************
fatal: [c-tso-19c-single-01.test.aspicon.lan]: FAILED! => {"msg": "The conditional check '(ansible_distribution == \"RedHat\" or ansible_distribution == \"CentOS\" or ansible_distribution == \"Scientific\" or yum_config_file.stat.exists)' failed. The error was: error while evaluating conditional ((ansible_distribution == \"RedHat\" or ansible_distribution == \"CentOS\" or ansible_distribution == \"Scientific\" or yum_config_file.stat.exists)): 'dict object' has no attribute 'stat'\n\nThe error appears to be in '/misc/drop/ol8-playbook-stig.yml': line 1609, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Ensure GPG check is globally activated (yum)\n      ^ here\n"}

#### SCAP Security Guide Version:
scap-security-guide-0.1.57-5.0.3.el8.noarch

#### Operating System Version:
Oracle Linux Server release 8.5

#### Steps to Reproduce:

1. Run playbook /usr/share/scap-security-guide/ansible/ol8-playbook-stig.yml against OEL8 machine
2.
3.
4.

#### Actual Results:
Task fails due to 'dict object' has no attribute 'stat'

#### Expected Results:
Task passes

#### Additional Information/Debugging Steps:
Issue seems to be caused by missing ansible_distribution=="OracleLinux" in when-Condition of the both tasks (lines 525 and 632). None of distribution checks in when-clause matches "OracleLinux" yet. Thus the conditional falls back to "or yum_config_file.stat.exists". However, yum_config_file variable has stat attribute set only on Fedora, as of stats tasks in lines 486 and 599.

**Comment by ggbecker** [comment]
This has been fixed by https://github.com/ComplianceAsCode/content/pull/8101 some time ago.

Now it's just a matter of having the fix brought to the distribution on a new update.

I'm closing this as there is nothing left to be done here.
