### ISSUE TITLE
create_srg_export.py script doesn't expand the variable selector

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#8612]
The example below renders the text with `15_minutes` instead of `900` which is the actual value when the datastream is built.

The script needs to find the variable file and load exactly the value to be expanded.

```
{'inactivity_timeout_value': '15_minutes', 'var_screensaver_lock_delay': '5_seconds'}
```
```
To check the current idle time-out value, run the following command:
<pre>$ gsettings get org.gnome.desktop.session idle-delay</pre>
If properly configured, the output should be <tt>'uint32 <sub idref="inactivity_timeout_value" />'</tt>.
To ensure that users cannot change the screensaver inactivity timeout setting, run the following:
<pre>$ grep idle-delay /etc/dconf/db/local.d/locks/*</pre>
If properly configured, the output should be <tt>/org/gnome/desktop/session/idle-delay</tt>
```

**Comment by ggbecker** [comment]
this is also related to default values for variables, if we detect no variable selection it would mean the default value should be used

**Comment by ggbecker** [comment]
The following selection is not valid:
https://github.com/ComplianceAsCode/content/blob/f51f214bcb5daa09384e0c47b17c32fb0b021447/controls/srg_gpos/SRG-OS-000356-GPOS-00144.yml#L9
`
ValueError: Value 'var_time_service_set_maxpoll' in profile 'srg_gpos' uses the selector '16'. This is not possible, as only selectors ['36_hours', '18_hours', 'default', 'system_default'] are available. Either change the selector used in the profile, or add the selector-value pair to the variable definition.
`

**Comment by ggbecker** [comment]
Another question: If a variable appears in more than one control file, which one should be used? The file loading is not ordered as my local machine was generating different results for the above case in which the variable was selected in two different control files.

**Comment by Mab879** [comment]
> Another question: If a variable appears in more than one control file, which one should be used? The file loading is not ordered as my local machine was generating different results for the above case in which the variable was selected in two different control files.

It should error out. Similar to how [`SelectionHandler`](https://github.com/ComplianceAsCode/content/blob/f51f214bcb5daa09384e0c47b17c32fb0b021447/ssg/build_yaml.py#L182) the base class for `Control` [does this](https://github.com/ComplianceAsCode/content/blob/f51f214bcb5daa09384e0c47b17c32fb0b021447/ssg/build_yaml.py#L209).

**Comment by jan-cerny** [comment]
Thanks for opening the GH issue! I run into the same problem 2 weeks ago in the PR https://github.com/ComplianceAsCode/content/pull/8555 and now it manifested also in https://github.com/ComplianceAsCode/content/pull/8596.
