### ISSUE TITLE
Create a script that will generate PCI-DSS reverse mapping and coverage stats

### ISSUE THREAD

**Issue by mpreisler** [ComplianceAsCode/content#866]
Blocked by #865

We have mapping from our XCCDF rules to PCI-DSS requirements, when #865 is finished we will have a granular "specific" mapping. We need the reverse mapping - from PCI-DSS requirements to our rules. From this mapping we need to generate coverage statistics - how many requirements are covered, how many need to be checked manually.

**Comment by mpreisler** [comment]
Related to #801

**Comment by matejak** [comment]
The rule description is vague - it is unclear what else needs to be done besides #801.
