### ISSUE TITLE
Evaluate replacing `operating system` with macro value `{{{ full_name }}}` in every field of rule.yml files

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#8671]
For example: https://github.com/ComplianceAsCode/content/pull/8610#discussion_r862726354

**Comment by Mab879** [comment]
A better find and replace string might be `the operating system`. Because that is usually what I want replaced.

**Comment by ggbecker** [comment]
Closing as done because we have already established the process for these macro replacements.
