### ISSUE TITLE
RHEL 9 - not possible to SSH to machine installed with ANSSI High kickstart

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#8677]
#### Description of problem:
After ANSSI BP-028 (High) kickstart installation, it is not possible to connect to freshly installed machine.

#### SCAP Security Guide Version:
fcede01

#### Operating System Version:
RHEL 9.0

#### Steps to Reproduce:
1. Install machine with ANSSI High security policy

#### Actual Results:
Not possible to SSH to machine

#### Expected Results:
SSH connection works

#### Additional Information/Debugging Steps:

I haven't found anything suspicious in anaconda installation log. It finished successfully:
```
...
[  784.866607] anaconda[1758]: program: Copying generated kickstart file...
[  784.882602] anaconda[1758]: program: Done.
Installation complete

Use of this product is subject to the license agreement found at:
/usr/share/redhat-release/EULA

[  784.910205] anaconda[1758]: program: Running in chroot '/mnt/sysroot'... /bin/sh /tmp/ks-script-3ozhsiin
[  784.917728] anaconda[1758]: anaconda: kickstart.script: All kickstart %%post script(s) have been run
[  784.924720] anaconda[1758]: anaconda: progress: Run post installation scripts
[  784.930531] anaconda[1758]: anaconda: installation: All tasks in the installation queue are done. Installation successfully finished.
...
```

Probably a new rule that blocks SSH connection in the profile? The SSH connection was tested using `testuser` with ssh key.

**Comment by mildas** [comment]
SSH connection didn't work in both installations - Server and Server with GUI.

I have tried rerunning the test and SSH connection worked, but there is 50 failing rules. I will do more testing, do not start investigations yet.

**Comment by yuumasato** [comment]
> Probably a new rule that blocks SSH connection in the profile?

Just want to add ANSSI High didn't change recently.

**Comment by mildas** [comment]
I wasn't successful with reproducing SSH connection issue, but I found failing `sysctl` rules (reported new issue #8686 ).

Closing this issue now. I will reopen it if it appears again.
