### ISSUE TITLE
RHEL 9 - sysctl rules are not properly remediated

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#8686]
#### Description of problem:
During kickstart installation, sysctl rules are not properly remediated. After kickstart installation, almost all sysctl rules (there is few exceptions) fail.

#### SCAP Security Guide Version:
f7d3441

#### Operating System Version:
RHEL 9.0

#### Steps to Reproduce:

1. Kickstart installation with ANSSI High profile

#### Actual Results:
sysctl rules fail

#### Expected Results:
sysctl rules pass

#### Additional Information/Debugging Steps:
Remediation scripts finish with code 0, but OVAL check fail:
```
Evaluation messages

info 
Fix execution completed and returned: 0

info 
Failed to verify applied fix: Checking engine returns: fail
```

See reports from kickstart installation (report created by OAA and after installation scan report):
[HTML reports.zip](https://github.com/ComplianceAsCode/content/files/8610224/HTML.reports.zip)

In RHEL 9 ANSSI High, 3 sysctl rules pass:
- sysctl_net_ipv4_conf_default_accept_source_route
- sysctl_kernel_exec_shield
- sysctl_kernel_kptr_restrict

the rest of sysctl rules fails

**Comment by ggbecker** [comment]
probably due to symlinks that systemd package creates and our check do not allow more than one occurrence to be set:

```
systemd spec file:

# /etc/sysctl.conf compat
install -Dm0644 %{SOURCE6} %{buildroot}/etc/sysctl.conf
ln -s ../sysctl.conf %{buildroot}/etc/sysctl.d/99-sysctl.conf
```
