### ISSUE TITLE
Evaluate the need for per rule requirements 

### ISSUE THREAD

**Issue by Mab879** [ComplianceAsCode/content#8695]
Some SRGs have many rules; however, each rule has the same generic requirement. We need to figure out how to account for this.

**Comment by ggbecker** [comment]
I'm not sure if I understood what the problem is. Can you give an example of this situation?

**Comment by Mab879** [comment]
The temporary and emergency account rules have the same requirement but need one word changed.

For temporary accounts this is fine
> Red Hat Enterprise Linux 9 must automatically remove or disable temporary user accounts after 72 hours.

For emergency accounts we need to change the word "temporary" to "emergency".

**Comment by Mab879** [comment]
Another example:
From the SRG
> Red Hat Enterprise Linux 9 must audit all account creations.

Should be
> Red Hat Enterprise Linux 9 must generate audit records for all account creations, modifications, disabling, and termination events that affect /etc/sudoers.

**Comment by ggbecker** [comment]
It sounds like the `rule.yml` should be able to override the Requirement text that comes from the SRG.

Another thing I may have noticed is that when the Requirement text will have the text of the first SRG a rule is part of in the case of a rule belonging to multiple SRGs. That reminds me of the concern I had of what Requirement text should be selected if the rule is part of multiple SRGs, in my opinion it should be the one that is the most relevant to the rule.
