### ISSUE TITLE
SRG Export VulnDiscussion can be more than the Rationale

### ISSUE THREAD

**Issue by Mab879** [ComplianceAsCode/content#8696]
Sometimes the Vuln Discussion field on the SRG export needs more text, but the `rationale` doesn't seem to be the best place for it. Where should we place this text?

**Comment by ggbecker** [comment]
Is this still relevant @Mab879 ?

**Comment by Mab879** [comment]
I think that will depend on the feedback we get from DISA, if we need to make sweeping changes to our VulnDiscussion sections.
