### ISSUE TITLE
content_rule_file_permissions_unauthorized_sgid reports directories with sgid set

### ISSUE THREAD

**Issue by ThiloSolbrig** [ComplianceAsCode/content#8819]
#### Description of problem:
content_rule_file_permissions_unauthorized_sgid also reports directories with sgid set, not only files. sgid set on directories has a different meaning than on files and thus might not be a security problem. sgid on directory just makes new files to inherit the group owner from the directory group owner.

#### SCAP Security Guide Version:
0.1.62

#### Operating System Version:
Oracle Linux Server release 8.6

#### Steps to Reproduce:

1. Create directory with sgid bit set
2. Run oscap security scan
3.
4.

#### Actual Results:
On my test host, /run/log/journal/bceb68c643eb4109b764877b8f9a3a55 was reported, while this is not a file but a directory:
`[root@c-tso-scap ~]# ls -ld /run/log/journal/bceb68c643eb4109b764877b8f9a3a55`
`drwxr-s---+ 2 root systemd-journal 60 May 20 15:43 /run/log/journal/bceb68c643eb4109b764877b8f9a3a55`

#### Expected Results:
Directories with sgid bit set shouldn't be reported

**Comment by ThiloSolbrig** [comment]
Doesn't reproduce when root runs oscap, which might be intended account to scan

**Comment by Mab879** [comment]
This should be fixed now.
