### ISSUE TITLE
AIDE v0.17 changed config makes xccdf_org.ssgproject.content_rule_aide_build_database rule to fail

### ISSUE THREAD

**Issue by remy-tiitre** [ComplianceAsCode/content#8838]
#### Description of problem:
AIDE v0.17 config has some changes that make xccdf_org.ssgproject.content_rule_aide_build_database rule to fail https://github.com/aide/aide/releases/tag/v0.17. Based on changelog I assume that thats when they stopped using DBNAME variable. There is no DBNAME variable in the aide.conf file anymore. Also the 'database' config option is now deprecated, and we should start using 'database_in' instead.
Also the config file location is perhaps changed but on my clean 20.04 install AIDE config is at /etc/aide/aide.conf and not /etc/aide.conf

So when I took the sl version of the variables definition and changed the config location, tests started to perform correctly. Unfortunately I'm too inexperienced to suggest a PR that can test different versions of the AIDE config. Thats why I changed it locally as I know that all systems use the latest AIDE version.

#### SCAP Security Guide Version:
1.61

#### Operating System Version:
Ubuntu 20.04.4

#### Additional Information/Debugging Steps:
So these work:
```
        <ind:textfilecontent54_object id="oval:object_aide_build_new_database_filename:obj:1" version="1">
          <ind:filepath>/etc/aide/aide.conf</ind:filepath>
          <ind:pattern operation="pattern match">^database_out=file:/([/a-z.]+)$</ind:pattern>
          <ind:instance operation="equals" datatype="int">1</ind:instance>
        </ind:textfilecontent54_object>
        <ind:textfilecontent54_object id="oval:object_aide_operational_database_filename:obj:1" version="1">
          <ind:filepath>/etc/aide/aide.conf</ind:filepath>
          <ind:pattern operation="pattern match">^database=file:/([/a-z.]+)$</ind:pattern>
          <ind:instance operation="equals" datatype="int">1</ind:instance>
        </ind:textfilecontent54_object>
        <oval-def:local_variable id="oval:ssg-variable_aide_build_new_database_absolute_path:var:1" datatype="string" comment="Absolute path of Aide build database file" version="1">
          <oval-def:concat>
            <oval-def:literal_component>/</oval-def:literal_component>
            <oval-def:object_component object_ref="oval:object_aide_build_new_database_filename:obj:1" item_field="subexpression" />
          </oval-def:concat>
        </oval-def:local_variable>
        <oval-def:local_variable id="oval:ssg-variable_aide_operational_database_absolute_path:var:1" datatype="string" comment="Absolute path of Aide build database file" version="1">
          <oval-def:concat>
            <oval-def:literal_component>/</oval-def:literal_component>
            <oval-def:object_component object_ref="oval:object_aide_operational_database_filename:obj:1" item_field="subexpression" />
          </oval-def:concat>
        </oval-def:local_variable>

```

**Comment by dodys** [comment]
I believe PR #9957 probably solves your problem.
Do note that we still use 'database=' as it is now still just a warning, and database_in is not backward compatible.

**Comment by dodys** [comment]
I'm closing this issue. Let us know in case of issues still.
