### ISSUE TITLE
Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by huornlmj** [ComplianceAsCode/content#8849]
## Which products and profiles does the rule apply to?

Ubuntu 22.04

**Comment by Mab879** [comment]
A discussion (#8465) was opened in March about Ubuntu 22.04, and it didn't get any response.

Tagging @dodys he might have more insights on this.

**Comment by huornlmj** [comment]
@dodys  had you also asked for a 22.04 profile?

**Comment by dodys** [comment]
Hi Jason, I'm not sure if I understood your question, but so far we are waiting for the certifications drafts to be published.

**Comment by huornlmj** [comment]
Sorry - I may have submitted the request in the wrong way, but there is no profile for Ubuntu 22.04 LTS systems yet, and the request is to add one.

**Comment by dodys** [comment]
thanks for clarifying it.
We should be adding a new profile whenever the drafts get published

**Comment by whoami-ru** [comment]
Hi, everyone! FYI, CIS Ubuntu Linux 22.04 LTS Benchmark v1.0.0 was published 30th 2022 =)

**Comment by antonr-p2p** [comment]
wow, nice! When can we expect profile for 22.04?

**Comment by antonr-p2p** [comment]
does anyone have an answer?

**Comment by dodys** [comment]
We should have an ETA by the end of October/beginning of November. We are currently at the end of the cycle and any new work will only start on the next cycle. I will let you know in case this changes.

**Comment by dodys** [comment]
PR #9953 adds the base for CIS on Ubuntu 22.04. Over the beginning of the next year I will continue adding the missing rules.

**Comment by dodys** [comment]
I will close this issue while we continue to add CIS for 22.04 and we should be able to have it completely done in the next month or so.
If you have any doubts about it, please use the #8465 or if you find any issues please open a new ticket.
Thanks!
