### ISSUE TITLE
Couple of PAM rules fail on RHEL9 during kickstart installation

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#8857]
#### Description of problem:
The following rules fail during kickstart installation of RHEL9 machine using `anssi_bp28_high` and other profiles:

```
xccdf_org.ssgproject.content_rule_accounts_password_pam_unix_rounds_password_auth - fail
xccdf_org.ssgproject.content_rule_accounts_password_pam_unix_rounds_system_auth - fail
```

#### Reports:

[xccdf_org.open-scap_testresult_xccdf_org.ssgproject.content_profile_anssi_bp28_high | OpenSCAP Evaluation Report.html.txt](https://github.com/ComplianceAsCode/content/files/8804403/xccdf_org.open-scap_testresult_xccdf_org.ssgproject.content_profile_anssi_bp28_high.OpenSCAP.Evaluation.Report.html.txt)

[xccdf_org.open-scap_testresult_xccdf_org.ssgproject.content_profile_anssi_bp28_high | OpenSCAP Evaluation Report_remediation.html.txt](https://github.com/ComplianceAsCode/content/files/8804405/xccdf_org.open-scap_testresult_xccdf_org.ssgproject.content_profile_anssi_bp28_high.OpenSCAP.Evaluation.Report_remediation.html.txt)

It seems the remediation is not being applied because it detects changes that were not made by authselect.

#### Additional rules with the same problem

`xccdf_org.ssgproject.content_rule_no_empty_passwords`

**Comment by jan-cerny** [comment]
There are different PAM rules failing as of scap-security-guide-0.1.63-1.git46faa00.el9.noarch:
* For the ANSSI High profiles, the rule xccdf_org.ssgproject.content_rule_set_password_hashing_algorithm_systemauth fails on both RHEL 9.1 and 8.7.
* For CIS Server Level 2 profiles and CIS Workstation Level 2 profiles, the rules xccdf_org.ssgproject.content_rule_accounts_password_pam_retry and xccdf_org.ssgproject.content_rule_set_password_hashing_algorithm_systemauth fail  on both RHEL 9.1 and 8.7.

@marcusburghardt I think they are related and I can see them modified in #9017
