### ISSUE TITLE
xccdf_org.ssgproject.content_rule_chronyd_run_as_chrony_user for Ubuntu is incorrect

### ISSUE THREAD

**Issue by remy-tiitre** [ComplianceAsCode/content#8872]
#### Description of problem:
xccdf_org.ssgproject.content_rule_chronyd_run_as_chrony_user validation and remediation seems to be incorrect for Ubuntu. At least I configure this is in /etc/default/chrony file and I set DAEMON_OPTS="-u _chrony". 

#### SCAP Security Guide Version:
1.61

#### Operating System Version:
20.04.4

**Comment by rossengeorgiev** [comment]
Yes, seems to expect `chrony` as the user, which is correct in RHEL, but in ubuntu the package creates `_chrony`

**Comment by dodys** [comment]
This was fixed in commit 37fd35ed 
Please let us know if you still find issues on it.
Closing this for now.
