### ISSUE TITLE
Rule file_permissions_etc_audit_rulesd gets broken by some other remediation

### ISSUE THREAD

**Issue by matusmarhefka** [ComplianceAsCode/content#8947]
#### Description of problem:
When remediating STIG profile the rule `file_permissions_etc_audit_rulesd` is reported as `pass` in the initial scan, but in the scan after remediation it fails. Most likely, it gets broken by some other rule remediation. Problem is not occurring when installing a system using STIG kickstart and OAA, only when remediating an installed running system.

#### SCAP Security Guide Version:
master

#### Operating System Version:
RHEL8 and RHEL9

#### Steps to Reproduce:
`python3 test_suite.py profile --libvirt qemu:///system test_suite_vm --mode online --remediate-using oscap xccdf_org.ssgproject.content_profile_stig`

**Comment by mildas** [comment]
`audit_immutable_login_uids` breaks it.
The problem is `file_permissions_etc_audit_rulesd` passes during initial scan (0640 on all files in `/etc/audit/rules.d/`, but `audit_immutable_login_uids` creates `/etc/audit/rules.d/11-loginuid.rules` file with 0644 permissions.

However, `audit_immutable_login_uids` fixtext states:

>     If the file doesn't exist, it can be copied from <tt>/usr/share/audit/sample-rules</tt>
>     using the next command
>     cp /usr/share/audit/sample-rules/11-loginuid.rules /etc/audit/rules.d/
>     Then, run the following commands:
>     $ sudo chmod o-rwx "/etc/audit/rules.d/11-loginuid.rules"
>     $ sudo augenrules --load

So current `lineinfile` template approach doesn't cover it as it doesn't set `o-rwx` and doesn't load it. @ggbecker Thoughts?

**Comment by mildas** [comment]
Related to #8860

**Comment by jan-cerny** [comment]
@mildas  This is a great finding! The lineinfile template is more flexible, but unlinke the audit_file_contents it doesn't change the file permissions and also doesn't run augenrules --load. 

We could revert #8860, but we would loose the flexibility, the rule would fail if there is any different rule in the audit rules file.

So I think that we could create a new template which would be similar to the lineonfile template but in addition the remediations would change the file permissions and also run the augenrules command. WDYT?

**Comment by mildas** [comment]
I don't think the audit rule needs flexibility. We should be conservative and offer what is provided by audit package as the audit sample files are created by audit proficient people - if someone thinks the file misses audit configuration, they should report it to audit packagers. And if I'm not mistaken, if anyone wants additional custom audit configurations, they can have it in separate file to not break the existing one.

Moreover, `/usr/share/audit/sample-rules/11-loginuid.rules` content might change and get multiple rules which would make lineinfile not suitable template.

**Comment by jan-cerny** [comment]
@mildas so Do you agree with reverting the #8860?

**Comment by mildas** [comment]
@jan-cerny Yes, that's only solution I see there
