### ISSUE TITLE
Rule ocp4-configure-network-policies fails on cluster with Calico CNI

### ISSUE THREAD

**Issue by rtheis** [ComplianceAsCode/content#9047]
#### Description of problem:

Rule [ocp4-configure-network-policies](https://github.com/ComplianceAsCode/content/blob/master/applications/openshift/networking/configure_network_policies/rule.yml
) fails on cluster with Calico CNI. Calico supports network policies and should be an acceptable CNI option.

#### SCAP Security Guide Version:

N/A

#### Operating System Version:

N/A

#### Steps to Reproduce:

Run the OpenShift compliance operator `ocp4-configure-network-policies` rule on a [Red Hat OpenShift on IBM Cloud](https://cloud.ibm.com/docs/openshift?topic=openshift-getting-started) cluster.

#### Actual Results:

Fail

#### Expected Results:

Pass

#### Additional Information/Debugging Steps:

N/A

**Comment by jhrozek** [comment]
Thanks for the bug report. At least according to our docs, bare OCP (which is what I have access to) doesn't support calico, but if ROKS does, I guess we should adjust the rule then.

With your Calico install, what does `oc get network cluster -oyaml -ojsonpath='{.spec.networkType}'` say? Is it just 'Calico' ?

**Comment by rtheis** [comment]
Thank you.  Yes, it is just `Calico`.

```
$ oc get network cluster -oyaml -ojsonpath='{.spec.networkType}'
Calico
```
