### ISSUE TITLE
var_auditd_max_log_file_action default does not match hardcoded value

### ISSUE THREAD

**Issue by BloodBlight** [ComplianceAsCode/content#9056]
#### Description of problem:
I opened this issue on OpenSCAP side:
https://github.com/OpenSCAP/openscap/issues/1868

The default value for the variable is not the same as the "hardcoded" value in the content.  See the post above for links the the exact locations.

#### SCAP Security Guide Version:
openscap-1.3.6-3.el8.x86_64

#### Operating System Version:
Red Hat Enterprise Linux \ 8.6 (Ootpa)

#### Steps to Reproduce:

1. Deploy default STIG profile to RHEL 8.

#### Actual Results:
Value is not changed to rotate.

#### Expected Results:
Value should be changed to rotate.

#### Additional Information/Debugging Steps:
Manually setting var_auditd_max_log_file_action in the tailoring file resolved the issue.  

Also see screenshots at:
https://imgur.com/a/k8qD8sO

**Comment by Mab879** [comment]
This is now fixed.
