### ISSUE TITLE
Linux PAM documentation page went missing

### ISSUE THREAD

**Issue by yuumasato** [ComplianceAsCode/content#9096]
#### Description of problem:

Link http://www.linux-pam.org/Linux-PAM-html/sag-configuration-file.html referenced in group https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-pam/group.yml is resulting in 404 error.

#### Actual Results:
Error 404

#### Expected Results:

Link to System Administrator's Guide works

#### Additional Information/Debugging Steps:
I was able to find a PDF of what was likely the resource being pointed at:
https://fossies.org/linux/Linux-PAM-docs/doc/sag/Linux-PAM_SAG.pdf

But not sure this is the best resource to point at.

**Comment by mildas** [comment]
The proposed link seems as good fit.
