### ISSUE TITLE
Ansible playbook with PAM macros unexpectedly report a task as changed on second round

### ISSUE THREAD

**Issue by marcusburghardt** [ComplianceAsCode/content#9117]
#### Description of problem:

By the https://github.com/ComplianceAsCode/content/pull/9097 PR, new Ansible macros were introduced to standardize and simplify the remediation for PAM related rules. These macros are in alignment to the equivalent Bash macros introduced by https://github.com/ComplianceAsCode/content/pull/9017.

The remediation is working pretty much as expected. However, while testing the generated Playbooks individually, it was noticed a strange behavior. The playbook correctly fix everything in the first round. So, it is expected the second round no task will be reported as `changed`. That is not the case, the following Ansible task (following example from the `accounts_password_pam_pwhistory_remember_system_auth` rule) reports `changed` even if the file is already in compliant:

```
 TASK [Limit Password Reuse: password-auth - Ensure the required value for "remember" PAM option from "pam_pwhistory.so" in /etc/authselect/custom/hardening/password-auth] ***
 Thursday 07 July 2022  15:27:43 +0200 (0:00:00.039)       0:02:13.082 *********
 changed: [rhel87n]
```
However, if the Playbook is execute again twice or more, only the second round reports `changed`. The third and following rounds report no change, as expected after the first round.

This is a strange behavior that I couldn't identify the cause. However, it has no negative impact for the remediation. Is just something visual, but weird enough to demand more investigation.

#### SCAP Security Guide Version:

master

#### Operating System Version:

RHEL8 and RHEL9

#### Steps to Reproduce:

1. ./build_product rhel8
2. ansible-playbook -i "rhel8," -v --tags accounts_password_pam_pwhistory_remember_system_auth build/ansible/rhel8-playbook-stig.yml
3. ansible-playbook -i "rhel8," -v --tags accounts_password_pam_pwhistory_remember_system_auth build/ansible/rhel8-playbook-stig.yml
4. ansible-playbook -i "rhel8," -v --tags accounts_password_pam_pwhistory_remember_system_auth build/ansible/rhel8-playbook-stig.yml

Observe and compare the results from the First, Second and Third rounds, more specifically in the task:
`TASK [Limit Password Reuse: password-auth - Ensure the required value for "remember" PAM option from "pam_pwhistory.so" in /etc/authselect/custom/hardening/password-auth]`

#### Actual Results:

Note that the task report `changed` in the `first` round: correct and expected because changes were indeed done.
Note that the task report `changed` in the `second` round: unexpected because changes were already applied in the `first` round.
Note that the task report `ok` in the `third` round: correct and expected.

#### Expected Results:

The task reports `changed` only in the `first` round. All next round should report `ok` or `skipped`.

#### Additional Information/Debugging Steps:

There were some discussions and output examples in https://github.com/ComplianceAsCode/content/pull/9097 PR.

**Comment by mildas** [comment]
I've tried it and 2nd run resulted in no chanes:
```
PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost                  : ok=19   changed=0    unreachable=0    failed=0    skipped=58   rescued=0    ignored=0 
```
Closing as resolved
