### ISSUE TITLE
PCI-DSS v4 was released on March 2022

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#9161]
#### Description of problem:
Current PCI-DSS profiles (e.g. [rhel8/pci-dss](https://github.com/ComplianceAsCode/content/blob/master/products/rhel8/profiles/pci-dss.profile)) follow version 3.2.1 from 2018. A new version (4.0) was released on March 2022 and can be used to align profiles to this newer version.

https://www.pcisecuritystandards.org/document_library/?category=pcidss&document=pci_dss

**Comment by tmishina** [comment]
Is there a plan to update [the PCI-DSS profile for OCP4](https://github.com/ComplianceAsCode/content/blob/master/controls/pcidss_ocp4.yml), which currently supports v3.2.1?

**Comment by jhrozek** [comment]
> Is there a plan to update [the PCI-DSS profile for OCP4](https://github.com/ComplianceAsCode/content/blob/master/controls/pcidss_ocp4.yml), which currently supports v3.2.1?

I know we talked about it but I don't find the card in our jira now. Let's ask on Slack.
