### ISSUE TITLE
Non-templated OVAL check files are not used by the build system

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#9166]
These files are for now only for the purpose of human inspection, so one can easily find out how the OVAL will look like after it's processed by the build system. But we may want to integrate to the build system to be in accordance with the rest of the project.

```
This is an irregularity of the build system - everything else (rules, remediations) is processed, written to a file and then loaded from a file in later step. This works this way also the for the templated OVAL checks. Only not-templated OVAL are  an exception. Now, it can be confusing that the "compiled" files are actually unused when other "compiled" files are loaded in the build system.

Nevertheless, it would be a task for a separate PR.
```
_Originally posted by @jan-cerny in https://github.com/ComplianceAsCode/content/pull/9157#discussion_r923369712_

**Comment by jan-cerny** [comment]
This has been solved by implementing OVAL object model.
