### ISSUE TITLE
RHEL8 CIS v2.0.0: `2.2.18` requirement

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#9196]
#### Share the context
`2.2.18: Ensure nfs-utils is not installed or the nfs-server service is masked` requires either `nfs-utils` not installed or `nfs-server` service masked.

#### Description of problem:
As the `nfs-utils` is GUI package set requirement, we should cover only the latter part of `2.2.18`. 

#### Proposed change:
`package_nfs-utils_removed` is not part of CIS profiles.
New rule covering `2.2.18` by `nfs-server` service mask is introduced.

#### References:
CIS v2.0.0 benchmark:
```
Many of the libvirt packages used by Enterprise Linux virtualization are dependent on
the nfs-utils package. If the nfs-package is required as a dependency, the nfs-server
should be disabled and masked to reduce the attack surface of the system.
```

**Comment by mildas** [comment]
@marcusburghardt

**Comment by marcusburghardt** [comment]
This makes sense. We already have a rule to mask `nfs-server`. I will send a PR.
