### ISSUE TITLE
Support Python3: minor infrastructure changes needed

### ISSUE THREAD

**Issue by isimluk** [ComplianceAsCode/content#933]
Our current build infrastructure is not compatible with python3.

There shouldn't be too much work except for the `print` to `sys.write` migration.

A list of python scripts affected can be seen at https://github.com/OpenSCAP/scap-security-guide/pull/928

**Comment by shawndwells** [comment]
RHEL7 uses python 2.7, so guessing this is for Fedora-based devs.

@mpreisler @yuumasato is this an issue or can we resolve ticket?

**Comment by mpreisler** [comment]
@shawndwells This is still an issue. A lot of our infrastructure is now python3 compatible but we still have ways to go.

This is a RHEL8 and Fedora thing. Python3 will definitely replace Python2 in the future.

**Comment by redhatrises** [comment]
I believe that the majority of this work has been done. Closing.
