### ISSUE TITLE
Nightly builds are failing

### ISSUE THREAD

**Issue by Mab879** [ComplianceAsCode/content#9336]
#### Description of problem:
Both OVAL 5.11 and 5.10 nightly builds are failing.

#### SCAP Security Guide Version:
https://github.com/ComplianceAsCode/content/commit/72fc6ad44ae45e32448b697e9988ab88914766c3

#### Steps to Reproduce:

1. [Nightly builds](https://github.com/ComplianceAsCode/content/actions/runs/2829784896)

#### Actual Results:
Build Fails

#### Expected Results:
Build Pass

#### Additional Information/Debugging Steps:
``` The following tests FAILED:
	234 - verify-references-ssg-ol7-ds.xml (Failed)
	244 - verify-references-ssg-ol8-ds.xml (Failed)
	254 - verify-references-ssg-ol9-ds.xml (Failed)
	350 - verify-references-ssg-ubuntu1604-ds.xml (Failed)
```

**Comment by ggbecker** [comment]
I also noticed that, but couldn't figure it out why.

I know that the test is failing here:

https://github.com/ComplianceAsCode/content/blob/c8a22b82337bdf3e4ed9d0ac2507a01baa3ace12/build-scripts/verify_references.py#L158

ovalfiles has two entries and contains the cve feed oval reference and the regular oval reference, but wasn't able to identify why only for those products there are two entries in that list.
