### ISSUE TITLE
Limit password reuse remediation fails

### ISSUE THREAD

**Issue by kingsleyzissou** [ComplianceAsCode/content#9341]
#### Description of problem:
The limit password remediation fails if the `authselect` package is installed but no profile is currently selected.

#### SCAP Security Guide Version:
scap-security-guide-0.1.60-7.el8.noarch

#### Operating System Version:
RHEL8.7

#### Steps to Reproduce:

1. Create an image with `osbuild-composer` with `oscap` configurations
2. `authselect` package is installed
3. Current profile: "No existing configuration detected."

#### Actual Results:
Remediation fails for:
`xccdf_org.ssgproject.content_rule_accounts_password_pam_pwhistory_remember_password_auth`
`xccdf_org.ssgproject.content_rule_accounts_password_pam_pwhistory_remember_system_auth`

#### Expected Results:
Both rules to be fixed

**Comment by ggbecker** [comment]
In theory, profiles that select these rules will also select the `enable_authselect` rule that enables an sssd profile and the remediation can be applied. https://github.com/ComplianceAsCode/content/blob/master/controls/cis_rhel8.yml#L29

We need more information to understand what's happening here.

**Comment by marcusburghardt** [comment]
If you are trying to remediate these two mentioned rules directly and there is no authselect profile selected, the remediation will return a warning message informing why it wasn't executed. To make sure PAM rules remediation works fine in RHEL8, make sure an authselect profile is selected:

- By manually selecting one. E.g.: `authselect select sssd`
- By applying the `enable_authselect` remediation
- By hardening the system based on a profile, like CIS, STIG, etc.

**Comment by kingsleyzissou** [comment]
> In theory, profiles that select these rules will also select the enable_authselect rule that enables an sssd profile and the remediation can be applied. https://github.com/ComplianceAsCode/content/blob/master/controls/cis_rhel8.yml#L29
> We need more information to understand what's happening here.

Apologies, I missed this. We are using the [osbuild-composer](https://github.com/osbuild/osbuild-composer) tool to build images and then remediate them at build time... currently we don't select the authselect profile at build time but that could possibly be done going forward.

cc @evgenyz for visibility
