### ISSUE TITLE
net.ipv4.conf.default.rp_filter FAILS even though it is set correctly as far as the O/S is concerned.

### ISSUE THREAD

**Issue by Delta-One-Two** [ComplianceAsCode/content#9376]
## Description of problem:

Under RHEL9, I noticed that net.ipv4.conf.default.rp_filter was being flagged as failing when in fact the value set was correct. This appears to be down to the setting appearing twice (/usr/lib/sysctl.d/50-redhat.conf and 50-default.conf), with 50-default.conf setting it to 2 and 50-redhat.conf setting it to 1. Precedence means the desired value (1) is the value the system ends up with.

This is an unmodified RHEL9 install. The settings/files supplied are those from RedHat. I can make the test PASS if I add the desired setting to a config file under /etc/sysctl.d but this seems odd to have a setting defined 3 times!

I can also make the test PASS if I change the 2 to a 1 (tried out of curiosity to see if it made a difference).

#### SCAP Security Guide Version:

openscap-1.3.6-3.el9.x86_64
openscap-scanner-1.3.6-3.el9.x86_64
scap-security-guide-0.1.60-6.el9_0.noarch

#### Operating System Version:
RHEL9

#### Steps to Reproduce:

[root@rhel9dev01 reports]# sysctl -a |grep net.ipv4.conf.default.rp_filter
net.ipv4.conf.default.rp_filter = 1

[root@rhel9dev01 reports]# grep net.ipv4.conf.default.rp_filter /usr/lib/sysctl.d/*
/usr/lib/sysctl.d/50-default.conf:net.ipv4.conf.default.rp_filter = 2
/usr/lib/sysctl.d/50-redhat.conf:net.ipv4.conf.default.rp_filter = 1

#### Actual Results:

xccdf_org.ssgproject.content_rule_sysctl_net_ipv4_conf_default_rp_filter FAILS even though the system reports a correct setting.

#### Expected Results:

xccdf_org.ssgproject.content_rule_sysctl_net_ipv4_conf_default_rp_filter should PASS

**Comment by marcusburghardt** [comment]
@yuumasato , I know you have worked on some changes related to sysctl rules. Could you confirm if this issue was covered by any of the recent improvements, please?

**Comment by Delta-One-Two** [comment]
We've confirmed it appears to be a problem with anything related to sysctl settings, and it's to do with precedence now that RedHat has adopted an init style mechanism for applying such settings. 

We have opened a case with RedHat too (#03317696).

I did an additional test using net.ipv4.ip_forward

[root@rhel9dev01 ~]# for name in `cat ct3.txt`; do grep $name /usr/lib/sysctl.d/*; done
/usr/lib/sysctl.d/50-default.conf:-net.ipv4.conf.all.accept_source_route
/usr/lib/sysctl.d/50-default.conf:-net.ipv4.conf.all.rp_filter
/usr/lib/sysctl.d/50-redhat.conf:-net.ipv4.conf.all.rp_filter
/usr/lib/sysctl.d/50-default.conf:net.ipv4.conf.default.accept_source_route = 0
/usr/lib/sysctl.d/50-default.conf:net.ipv4.conf.default.rp_filter = 2
/usr/lib/sysctl.d/50-redhat.conf:net.ipv4.conf.default.rp_filter = 1
/usr/lib/sysctl.d/50-default.conf:net.ipv4.ip_forward = 1
/usr/lib/sysctl.d/50-redhat.conf:net.ipv4.ip_forward = 0

The system sets it correctly:

[root@rhel9dev01 ~]# sysctl -a |grep  net.ipv4.ip_forward
net.ipv4.ip_forward = 0
net.ipv4.ip_forward_update_priority = 1
net.ipv4.ip_forward_use_pmtu = 0

The rule still fails despite the correct setting:

Title   Disable Kernel Parameter for IP Forwarding on IPv4 Interfaces
Rule    xccdf_org.ssgproject.content_rule_sysctl_net_ipv4_ip_forward
Ident   CCE-83998-5
Result  fail

**Comment by yuumasato** [comment]
@Delta-One-Two Witch profile are you using?

@marcusburghardt This is still an issue, mainly because the sysctl rules try to be aligned with DISA STIG.
Although the sysctl runtime is correct, and thus the static configuration should be correct too, the STIG imposes some restrictions in `*.conf` files.

In the STIG update release in FY22Q2, the sysctl config was restricted to allow the option be be defined in only one file: See for example: https://stigaview.com/products/rhel8/v1r6/RHEL-08-010671/

In the STIG update released in Q3, they restriction allowed the option to be defined in multiple files, as long as they were the same: https://stigaview.com/products/rhel8/v1r7/RHEL-08-010671/

Moreover, it is very complex to ensure that the runtime configuration will be compliant just by checking the `*.conf`.

**Comment by Mab879** [comment]
This is now fixed.

**Comment by marcusburghardt** [comment]
I agree. The rule uses `sysctl` template which already deal with conflicting settings.
