### ISSUE TITLE
Ubuntu ansible stig fails when nmcli is not installed

### ISSUE THREAD

**Issue by ckhordiasma** [ComplianceAsCode/content#9380]
#### Description of problem:
ansible script fails if nmcli is not installed. nmcli is not always installed by default on ubuntu 20.04, for example on cloud images

#### SCAP Security Guide Version:
v0.1.63

#### Operating System Version:
ubuntu 20.04

#### Steps to Reproduce:

1. install ansible
2. download ssg zip file from releases page and cd into it
3. run `ansible-playbook -i "localhost," -c local ansible/ubuntu2004-playbook-stig.yml`
4. wait until error shows up

#### Actual Results:
```
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "nmcli radio wifi off", "msg": "[Errno 2] No such file or directory: b'nmcli'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```

#### Expected Results:
```
ok: [localhost]
```

#### Additional Information/Debugging Steps:

current workaround is to install network-manager before attempting ansible stig script

**Comment by dodys** [comment]
Ubuntu does not support ansible remediation. 
If you want to, propose a fix and maintainers will review it.
