### ISSUE TITLE
Rules selected in profiles do not get validated if they exist or not anymore

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#9408]
> 

we already have something like this:

https://github.com/ComplianceAsCode/content/blob/a2fd04690005ff6ac0b08d913196388dc8f0d08c/ssg/build_yaml.py#L677

but probably because of `controls` file code, it's not being reached. So the rule gets filtered out earlier in the process.

_Originally posted by @ggbecker in https://github.com/ComplianceAsCode/content/issues/9405#issuecomment-1227458225_

**Comment by ggbecker** [comment]
@matejak maybe you can easily identify the reason why.

**Comment by yuumasato** [comment]
@ggbecker Would you say this is a duplicate of https://github.com/ComplianceAsCode/content/issues/8870?

**Comment by ggbecker** [comment]
most certainly is. Let's close this as dupe. Thanks.
