### ISSUE TITLE
Remove - Ubuntu 16.04 - End of Life

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#9409]
#### Product to be removed:
Ubuntu 16.04 - End of Life

#### Reason for Product removal:

* Product End-Of-Life (EOL) was on  April 30th 2021 according to the following source:
  * [Inform where the information can be validated.](https://computing.cs.cmu.edu/news/2020/eol-ubuntu-1604)

#### Deadline to receive comments or objections:

September 2022 (UTC)

**Comment by ggbecker** [comment]
FYI

@richardmaciel-canonical 
@dodys

**Comment by dodys** [comment]
Ubuntu 16.04 is not EOL, it is just Out of Standard Support. 
For more information:
https://ubuntu.com/about/release-cycle
https://wiki.ubuntu.com/Releases

**Comment by ggbecker** [comment]
Ok, let's close the issue then. Thanks for the information.
