### ISSUE TITLE
RHEL9 is not part of the galaxy ansible roles

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#9411]
#### Description of problem:

Start shipping RHEL9 ansible content on galaxy. https://galaxy.ansible.com/RedHatOfficial

https://github.com/ComplianceAsCode/content/blob/87768ea76b8ff21fdcc546fc9cce231bef1c85e7/utils/ansible_playbook_to_role.py#L57-L60

**Comment by azrdev** [comment]
now it is? https://galaxy.ansible.com/ui/standalone/roles/RedHatOfficial/rhel9_stig/

**Comment by Mab879** [comment]
@azrdev looks like you are correct, closing.
