### ISSUE TITLE
Rule audit_rules_kernel_module_loading_create is misaligned with DISA

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#9425]
#### Description of problem:
Rule xccdf_org.ssgproject.content_rule_audit_rules_kernel_module_loading_create from our RHEL 7 data stream is misaligned with rule 
xccdf_mil.disa.stig_rule_SV-204559r833169_rule from disa-stig-rhel7-v3r8-xccdf-scap.xml.

#### SCAP Security Guide Version:

current upstream as of 2022-08-29 as of HEAD https://github.com/ComplianceAsCode/content/commit/2bcaad252bfc53f65ee54b51f994338fe6359055

#### Operating System Version:
RHEL 7.9

#### Steps to Reproduce:

1. evaluate RHEL 7 STIG profile
2. evaluate disa-stig-rhel7-v3r8-xccdf-scap.xml

#### Actual Results:
xccdf_org.ssgproject.content_rule_audit_rules_kernel_module_loading_create: notselected
xccdf_mil.disa.stig_rule_SV-204559r833169_rule: fail

#### Expected Results:
both rules fail

**Comment by ggbecker** [comment]
The rule is not being selected in our RHEL7 STIG profile. We should select it and most likely it will start to pass
