### ISSUE TITLE
Rule audit_rules_privileged_commands_kmod is misaligned with DISA

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#9426]
#### Description of problem:
Rule xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_kmod from our RHEL 7 data stream isn't aligned with rule 
xccdf_mil.disa.stig_rule_SV-204563r603261_rule from disa-stig-rhel7-v3r8-xccdf-scap.xml.

#### SCAP Security Guide Version:
current upstream as of 2022-08-29 as of HEAD https://github.com/ComplianceAsCode/content/commit/2bcaad252bfc53f65ee54b51f994338fe6359055

#### Operating System Version:
RHEL 7.9

#### Steps to Reproduce:

1.    evaluate RHEL 7 STIG profile
2.    evaluate disa-stig-rhel7-v3r8-xccdf-scap.xml

#### Actual Results:
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_kmod: fail
xccdf_mil.disa.stig_rule_SV-204563r603261_rule: pass

#### Expected Results:
bot rules are the same

**Comment by ggbecker** [comment]
This PR most likely fixes this problem since there was an issue on the OVAL side and now they should match: #9434

**Comment by ggbecker** [comment]
https://github.com/ComplianceAsCode/content/issues/9434 fixed this. I have just confirmed in the test results.

**Comment by ggbecker** [comment]
`CCE-86110-4 SV-86815 - SV-204563r603261_rule audit_rules_privileged_commands_kmod                                       pass`
