### ISSUE TITLE
Rule auditd_name_format is misaligned with DISA

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#9429]
#### Description of problem:
Rule xccdf_org.ssgproject.content_rule_auditd_name_format from our RHEL 7 data stream isn't aligned with rule xccdf_mil.disa.stig_rule_SV-204508r603261_rule from disa-stig-rhel7-v3r8-xccdf-scap.xml

#### SCAP Security Guide Version:
current upstream as of 2022-08-29 as of HEAD https://github.com/ComplianceAsCode/content/commit/2bcaad252bfc53f65ee54b51f994338fe6359055

#### Operating System Version:
RHEL 7.9

#### Steps to Reproduce:

1. evaluate RHEL 7 STIG profile
2. execute Ansible remediations for the RHEL 7 STIG
3. evaluate disa-stig-rhel7-v3r8-xccdf-scap.xml

#### Actual Results:
xccdf_org.ssgproject.content_rule_auditd_name_format: fail
xccdf_mil.disa.stig_rule_SV-204508r603261_rule: pass

#### Expected Results:
both rules are the same

**Comment by jan-cerny** [comment]
@vojtapolasek it might be influenced by the Ansible Playbook error, which is tracked in https://github.com/ComplianceAsCode/content/issues/9431 and is already fixed

**Comment by ggbecker** [comment]
@vojtapolasek that's definitely an inconsistency, EL7 products should use `/etc/audisp/audispd.conf` and EL8 products should use `/etc/audit/auditd.conf` according to STIGs.
