### ISSUE TITLE
Rule audit_rules_usergroup_modification_shadow fails after remediation and reboot

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#9433]
#### Description of problem:
In the machine-hardening STIG test, rule audit_rules_usergroup_modification_shadow  fails after remediation and reboot.

#### SCAP Security Guide Version:
for RHEL 7.9 and 8.1: current upstream as of 2022-08-29 as of HEAD 2bcaad252bfc53f65ee54b51f994338fe6359055
for RHEL 9.1: current upstream as of 2022-08-29 as of HEAD  dcbae8c

#### Operating System Version:
RHEL 7.9, RHEL 8.7,  RHEL 9.1

#### Steps to Reproduce:

For RHEL 8:

1. oscap xccdf eval --progress --remediate --profile xccdf_org.ssgproject.content_profile_stig --report /stig_remediate_report.html ssg-rhel8-ds.xml
2. reboot 
3. oscap xccdf eval --progress --profile xccdf_org.ssgproject.content_profile_stig --results stig-xccdf-results.xml --report stig.html ssg-rhel8-ds.xml

analogically for RHEL 7 and RHEL 9

#### Actual Results:
xccdf_org.ssgproject.content_rule_audit_rules_usergroup_modification_shadow - fail 

#### Expected Results:
xccdf_org.ssgproject.content_rule_audit_rules_usergroup_modification_shadow - pass

#### Additional Information/Debugging Steps:
This issue is also a part of https://github.com/ComplianceAsCode/content/issues/9432

**Comment by mildas** [comment]
We also have bugzilla for it https://bugzilla.redhat.com/show_bug.cgi?id=2119356
