### ISSUE TITLE
Rule audit_rules_privileged_commands_kmod fails after remediation and reboot

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#9434]
#### Description of problem:
In the machine-hardening STIG test, rule xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_kmod fails after remediation and reboot.

#### SCAP Security Guide Version:
current upstream as of 2022-08-29 as of HEAD https://github.com/ComplianceAsCode/content/commit/2bcaad252bfc53f65ee54b51f994338fe6359055

#### Operating System Version:
RHEL 7.9

#### Steps to Reproduce:

1. oscap xccdf eval --progress --remediate --profile xccdf_org.ssgproject.content_profile_stig --report /stig_remediate_report.html ssg-rhel7-ds.xml
2. reboot
3. oscap xccdf eval --progress --profile xccdf_org.ssgproject.content_profile_stig --results stig-xccdf-results.xml --report stig.html ssg-rhel7-ds.xml

#### Actual Results:
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_kmod - fail 

#### Expected Results:
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_kmod - pass

#### Additional Information/Debugging Steps:
This issue can be related to https://github.com/ComplianceAsCode/content/issues/9426 which is about the same rule being misaligned with DISA.

**Comment by jan-cerny** [comment]
Moreover, this rule also fails after the kickstart installation of the RHEL 7 STIG with GUI using ssg-rhel7-stig_gui-ks.cfg.

**Comment by jan-cerny** [comment]
Moreover, this rule fails also in the "test-profiles-remediation PCI-DSS, OSPP, STIG" test, where the Automatus is executed in "profile" mode on a RHEL 7 VM this way: python3 /tmp/tmp.a0IvWME14W/rpmbuild/BUILD/scap-security-guide-0.1.64/tests/test_suite.py profile                         --libvirt qemu:///system test_suite_vm                         --datastream /tmp/ssg-rhel7-ds.xml                         --xccdf-id scap_org.open-scap_cref_ssg-rhel7-xccdf-1.2.xml                         --mode online                         --remediate-using oscap                         xccdf_org.ssgproject.content_profile_stig

**Comment by jan-cerny** [comment]
Moreover, this rule also fails after the kickstart installation of the RHEL 7 STIG using ssg-rhel7-stig-ks.cfg.

**Comment by ggbecker** [comment]
The pull request: https://github.com/ComplianceAsCode/content/pull/9338 introduced new custom content for RHEL7 that broke the checks. We need to fix that. But actually, we are requesting DISA to make it the same as in RHEL8.
