### ISSUE TITLE
RHEL 9 STIG Ansible Playbook fatal error due to authselect

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#9437]
#### Description of problem:
RHEL 9 STIG Ansible Playbook contain fatal error due to authselect use in macro ansible_check_authselect_integrity() .

#### SCAP Security Guide Version:
current upstream as of 2022-08-29 as of HEAD https://github.com/ComplianceAsCode/content/commit/2bcaad252bfc53f65ee54b51f994338fe6359055

#### Operating System Version:
RHEL 9.1

#### Steps to Reproduce:

1. ansible-playbook  --skip-tags ensure_gpgcheck_never_disabled,configure_opensc_nss_db --private-key=/root/.ssh/ssg_id_ecdsa -i "$your_ip," /usr/share/scap-security-guide/ansible/rhel9-playbook-stig.yml

#### Actual Results:
```
TASK [Ensure PAM Displays Last Logon/Access Notification - Informative message based on the authselect integrity check result] ***
fatal: [192.168.122.13]: FAILED! => {
    "assertion": "result_authselect_check_cmd is success",
    "changed": false,
    "evaluated_to": false,
    "msg": [
        "authselect integrity check failed. Remediation aborted!",
        "This remediation could not be applied because an authselect profile was not selected or the selected profile is not intact.",
        "It is not recommended to manually edit the PAM files when authselect tool is available.",
        "In cases where the default authselect profile does not cover a specific demand, a custom authselect profile is recommended."
    ]
}
```

#### Expected Results:
the RHEL 9 STIG playbook doesn't terminate prematurely due to fatal error

#### Additional Information/Debugging Steps:
There are more fatal errors but they are ignored I guess because they have `ignore_errors: yes` set.

**Comment by marcusburghardt** [comment]
The `enable_authselect` rule is missing in STIG profile for RHEL9. I will send a fix.

**Comment by jan-cerny** [comment]
This problem also occurred during the productization test "test-profiles-ansible-remediation PCI-DSS, OSPP, STIG" on RHEL 9.1, where we run Automatus in profile mode and we execute this command:

python3 /tmp/tmp.bya64c0e7z/rpmbuild/BUILD/scap-security-guide-0.1.64/tests/test_suite.py profile                         --libvirt qemu:///system test_suite_vm                         --datastream /tmp/ssg-rhel9-ds.xml                         --xccdf-id scap_org.open-scap_cref_ssg-rhel9-xccdf-1.2.xml                         --mode online                         --remediate-using ansible                         xccdf_org.ssgproject.content_profile_stig
