### ISSUE TITLE
Rule tftpd_uses_secure_mode needs new OVAL and remediations for RHEL9

### ISSUE THREAD

**Issue by matusmarhefka** [ComplianceAsCode/content#9511]
Rule `tftpd_uses_secure_mode` needs a new RHEL9 specific OVAL, Bash and Ansible remediations, and update of test scenarios. The rule has changed on RHEL9 and it differs compared to older RHELs, see https://github.com/ComplianceAsCode/content/pull/9509/files#diff-b3fcc19cd5ee8ac9552af3d08d1088b04a5faf56e27bacdce6ef9b1c381319cb

**Comment by Mab879** [comment]
Fixed with https://github.com/ComplianceAsCode/content/pull/12436
