### ISSUE TITLE
RHEL9 STIG fails to connect to SSH after installation (unclear)

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#9528]
#### Description of problem:
The log contains:

```
pyanaconda.errors.NonInteractiveError: Non interactive installation failed: Wrong configuration detected!
/boot/efi must be on a separate partition or logical volume and has to be created in the partitioning layout before installation can occur with a security profile
The installation should be aborted.
```

It's uncertain whether this is actually a problem with the installation or something related to EFI.

Note: The following PR didn't really help: https://github.com/ComplianceAsCode/content/pull/9525

**Comment by matejak** [comment]
If a system decides to install in the UEFI mode, it needs to have the separate e.g. 200 MB VFAT EFI partition. It may be a good idea to maybe create that partition proactively, because there is no harm in having it while not using it.

**Comment by ggbecker** [comment]
I think I've figured out what the problem is:

Logs contain:
```
[  112.078086] org.fedoraproject.Anaconda.Addons.OSCAP[1847]: INFO:anaconda.threading:Thread Failed: AnaTaskThread-EvaluateRulesTask-1 (140616450307648)
[  112.086218] org.fedoraproject.Anaconda.Addons.OSCAP[1847]: ERROR:anaconda.modules.common.task.task:Thread AnaTaskThread-EvaluateRulesTask-1 has failed: Traceback (most recent call last):
[  112.092796] org.fedoraproject.Anaconda.Addons.OSCAP[1847]:   File "/usr/lib64/python3.9/site-packages/pyanaconda/threading.py", line 275, in run
[  112.098005] org.fedoraproject.Anaconda.Addons.OSCAP[1847]:     threading.Thread.run(self)
[  112.101338] org.fedoraproject.Anaconda.Addons.OSCAP[1847]:   File "/usr/lib64/python3.9/threading.py", line 917, in run
[  112.105734] org.fedoraproject.Anaconda.Addons.OSCAP[1847]:     self._target(*self._args, **self._kwargs)
[  112.109512] org.fedoraproject.Anaconda.Addons.OSCAP[1847]:   File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/common/task/task.py", line 96, in _thread_run_callback
[  112.115730] org.fedoraproject.Anaconda.Addons.OSCAP[1847]:     self._task_run_callback()
[  112.119021] org.fedoraproject.Anaconda.Addons.OSCAP[1847]:   File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/common/task/task.py", line 109, in _task_run_callback
[  112.125344] org.fedoraproject.Anaconda.Addons.OSCAP[1847]:     self._set_result(self.run())
[  112.128794] org.fedoraproject.Anaconda.Addons.OSCAP[1847]:   File "/usr/share/anaconda/addons/org_fedora_oscap/service/installation.py", line 127, in run
[  112.134288] org.fedoraproject.Anaconda.Addons.OSCAP[1847]:     self._evaluate_rules(rule_data)
[  112.137834] org.fedoraproject.Anaconda.Addons.OSCAP[1847]:   File "/usr/share/anaconda/addons/org_fedora_oscap/service/installation.py", line 150, in _evaluate_rules
[  112.143737] org.fedoraproject.Anaconda.Addons.OSCAP[1847]:     terminate("\n".join(msg_lines))
[  112.147260] org.fedoraproject.Anaconda.Addons.OSCAP[1847]:   File "/usr/share/anaconda/addons/org_fedora_oscap/service/installation.py", line 57, in terminate
[  112.152979] org.fedoraproject.Anaconda.Addons.OSCAP[1847]:     raise NonCriticalInstallationError(message)
[  112.156897] org.fedoraproject.Anaconda.Addons.OSCAP[1847]: pyanaconda.modules.common.errors.installation.NonCriticalInstallationError: Wrong configuration detected!
[  112.164258] org.fedoraproject.Anaconda.Addons.OSCAP[1847]: /boot/efi must be on a separate partition or logical volume and has to be created in the partitioning layout before installation can occur with a security profile
[  112.172054] org.fedoraproject.Anaconda.Addons.OSCAP[1847]: The installation should be aborted.
```

Which means the installation is being aborted by OAA because of missing separate `/boot/efi` partition. The following rule selected in the profile is causing this even though it shouldn't be applicable to a non-uefi system:

RHEL9
https://github.com/ComplianceAsCode/content/blob/6f56693f25661f06090e4a3cecaea8559c6736cf/controls/srg_gpos/SRG-OS-000480-GPOS-00227.yml#L110

RHEL8
https://github.com/ComplianceAsCode/content/blob/6f56693f25661f06090e4a3cecaea8559c6736cf/products/rhel8/profiles/stig.profile#L391

The rule: [mount_option_boot_efi_nosuid](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/permissions/partitions/mount_option_boot_efi_nosuid/rule.yml)

The anaconda remediation for this rule is imposing that a `/boot/efi` separate partition needs to exist even when:

https://github.com/ComplianceAsCode/content/blob/6f56693f25661f06090e4a3cecaea8559c6736cf/linux_os/guide/system/permissions/partitions/mount_option_boot_efi_nosuid/rule.yml#L39

One option is to completely disable the Anaconda remediation, so OAA will not recognize as a required separate partition. The other would be to generate non-empty Anaconda remediation when the `mount_has_to_exist: "yes"`.

But this will affect on UEFI systems to not require the separate partition.
