### ISSUE TITLE
Login issues after anssi profile remediation with image-builder images

### ISSUE THREAD

**Issue by kingsleyzissou** [ComplianceAsCode/content#9536]
#### Description of problem:
I am unable to login to a system that has been built with image-builder and remediated using the anssi enhanced profile, the anssi high profile or the anssi intermediary profile - all three profiles produce the same selinux error.

#### SCAP Security Guide Version:
scap-security-guide-0.1.60-7.el8.noarch

#### Operating System Version:
RHEL 8.7

#### Steps to Reproduce:

1. using [osbuild-composer](https://github.com/osbuild/osbuild-composer) to build an image on-prem, create a blueprint with the following customizations:

```
[customizations.openscap]
profile_id = "bp28_enhanced"  # or bp28_high or bp28_intermediary
datastream = "/usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml"
```

2. Once the image has been built, boot it up and attempt login

#### Actual Results:
The session starts and the user is logged out with the message: `Cannot make/remove an entry for the specified session`

#### Expected Results:
To be able to login normally either through the console or via ssh.

#### Additional Information/Debugging Steps:
I have managed to extract the logs and will add them to the issue, running `audit2why`, I get the following error:

```
type=AVC msg=audit(1663240843.821:59): avc:  denied  { mounton } for  pid=1796 comm="login" path="/" dev="dm-0" ino=128 scontext=system_u:system_r:local_login_t:s0-s0:c0.c1023 tcontext=system_u:object_r:root_t:s0 tclass=dir permissive=0

	Was caused by:
	The boolean polyinstantiation_enabled was set incorrectly. 
	Description:
	Enable polyinstantiated directory support.

	Allow access by executing:
	# setsebool -P polyinstantiation_enabled 1
```

Remediation logs:
[image-builder-remediation.txt](https://github.com/ComplianceAsCode/content/files/9599505/image-builder-remediation.txt)

Audit logs:
[audit.log](https://github.com/ComplianceAsCode/content/files/9599522/audit.log)

Secure logs:
[secure.log](https://github.com/ComplianceAsCode/content/files/9599520/secure.log)

**Comment by evgenyz** [comment]
So, what would be the proper way to change a selinuxboolean value persistently in the build stage?

**Comment by kingsleyzissou** [comment]
So I've had a chance to look into this and we set a env variable for every stage in [osbuild](https://github.com/osbuild/osbuild/blob/145a0cc273c731126543e62db633a664815a6b71/osbuild/buildroot.py#L297).
Container gets set to bwrap-osbuild
