### ISSUE TITLE
FIPS enabled profiles built in offline mode with image-builder won't boot

### ISSUE THREAD

**Issue by kingsleyzissou** [ComplianceAsCode/content#9559]
#### Description of problem:
Images built with image-builder on-prem using the `ospp`, `cui` & `stig` profiles won't boot. The issue is that these profiles enable fips mode and the images won't boot with `/boot` on a separate partition. A workaround for this is to add `/boot/<PARTITION>` to the kernal arguments.

#### SCAP Security Guide Version:
scap-security-guide-0.1.60-7.el8.noarch

#### Operating System Version:
RHEL 8.7

#### Steps to Reproduce:

1. using [osbuild-composer](https://github.com/osbuild/osbuild-composer) to build an image on-prem, create a blueprint with the following customizations:

```
[customizations.openscap]
profile_id = "ospp"  # or cui
datastream = "/usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml"
```

2. Attempt to boot the image

#### Actual Results:
The image enters dracut recovery mode

#### Expected Results:
Boot and use the image

#### Additional Information/Debugging Steps:
Remediation logs:
[image-builder-remediation.txt](https://github.com/ComplianceAsCode/content/files/9634398/image-builder-remediation.txt):

Boot log:
[rdsosreport.txt](https://github.com/ComplianceAsCode/content/files/9634399/rdsosreport.txt)

**Comment by ggbecker** [comment]
tail of rdsosreport.txt:

```
[   33.670240] XFS (dm-0): Mounting V5 Filesystem
[   33.678574] XFS (dm-0): Starting recovery (logdev: internal)
[   33.682992] XFS (dm-0): Ending recovery (logdev: internal)
[   33.991882] dracut: Remounting /dev/disk/by-uuid/985dd6e1-5f23-41a8-98c2-e2fcbe704ea7 with -o defaults
[   34.008675] dracut: Mounted root filesystem /dev/mapper/rootvg-rootlv
[   58.657819] dracut: Checking integrity of kernel
[   58.687076] dracut Warning: /boot//.vmlinuz-4.18.0-381.el8.x86_64.hmac does not exist
[   58.698600] dracut: FATAL: FIPS integrity test failed
[   58.702996] dracut: Refusing to continue
[   58.716251] dracut Warning: Signal caught!
[   58.727786] dracut Warning: dracut: FATAL: FIPS integrity test failed
[   58.729926] dracut Warning: dracut: Refusing to continue
+ '[' -f /run/initramfs/init.log ']'
```

**Comment by marcusburghardt** [comment]
It seems the FIPS requires to inform the boot partition in boot options when it is in a separate partition. I don't think that including `boot=<partition>` kernel argument is a workaround but actually is the proper solution to use a separate /boot partition when FIPS is enabled.

**Comment by evgenyz** [comment]
Proposed fix:

Extend https://github.com/ComplianceAsCode/content/blob/master/shared/templates/mount/blueprint.template with 
```
[customizations.kernel]
append = "boot={{{ MOUNTPOINT }}}"
```
only for `/boot` mount point. This feels a bit hackish, but it should do the trick.

**Comment by evgenyz** [comment]
So, the initial assessment was incorrect. The `boot=UUID=` argument is set:

```
Command line: BOOT_IMAGE=(hd0,gpt4)/vmlinuz-4.18.0-381.el8.x86_64 root=UUID=985dd6e1-5f23-41a8-98c2-e2fcbe704ea7 console=tty0 console=ttyS0,115200n8 no_timer_check net.ifnames=0 crashkernel=auto slub_debug=P page_poison=1 v
syscall=none pti=on random.trust_cpu=on audit_backlog_limit=8192 audit=1 boot=UUID=BC13C2FF-59E6-4262-A352-B275FD6F7172 fips=1
```

However, the `UUID` used there (`BC13C2FF-59E6-4262-A352-B275FD6F7172`) is wrong:

```
/dev/vda1: PARTUUID="fac7f1fb-3e8d-4137-a512-961de09a5549"
/dev/vda2: SEC_TYPE="msdos" UUID="7B77-95E7" BLOCK_SIZE="512" TYPE="vfat" PARTUUID="68b2905b-df3e-4fb3-80fa-49d1e773aa33"
/dev/vda3: UUID="jqguF0-IgAn-lymg-s7J3-XFlJ-xkma-Os4IPr" TYPE="LVM2_member" PARTUUID="6264d520-3fb9-423f-8ab8-7a0a8e3d3562"
/dev/vda4: UUID="0add71ca-f74b-467f-b5a2-ef1534dd6159" BLOCK_SIZE="512" TYPE="xfs" PARTUUID="654b72eb-0467-4b67-8b9f-5a5d885c29f8"
/dev/sda1: LABEL="TEST" UUID="F5AC-1212" BLOCK_SIZE="512" TYPE="vfat" PARTUUID="ada7cf7c-01"
/dev/mapper/rootvg-rootlv: LABEL="root" UUID="985dd6e1-5f23-41a8-98c2-e2fcbe704ea7" BLOCK_SIZE="512" TYPE="xfs"
/dev/mapper/rootvg-homelv: UUID="04d94288-726d-4926-b418-11b355c66477" BLOCK_SIZE="512" TYPE="xfs"
/dev/mapper/rootvg-varlv: UUID="445e9139-fefa-4a14-829d-e01127082ee6" BLOCK_SIZE="512" TYPE="xfs"
/dev/mapper/rootvg-var_loglv: UUID="ceb3145e-865d-4a19-bd87-fbeb573e7c01" BLOCK_SIZE="512" TYPE="xfs"
/dev/mapper/rootvg-var_log_auditlv: UUID="651867ee-40c6-4a24-969a-1bfc49165627" BLOCK_SIZE="512" TYPE="xfs"
/dev/mapper/rootvg-var_tmplv: UUID="ca55e866-8be7-493e-ad5a-df5d2f93c8e5" BLOCK_SIZE="512" TYPE="xfs"
```

**Comment by evgenyz** [comment]
The way https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/software/integrity/fips/grub2_enable_fips_mode/bash/shared.sh rule fetch UUID has to be changed for *osbuild* environment.

**Comment by evgenyz** [comment]
It is interesting that the root partition UUID is correct.

**Comment by evgenyz** [comment]
@kingsleyzissou Do you have any insight into what is happening with boot partition in the pipeline? Is it being re-created somehow?

**Comment by evgenyz** [comment]
I could be that better way to find `/boot` mount point in this case would be `findmnt --noheadings --output uuid --fstab --mountpoint /boot`.

**Comment by kingsleyzissou** [comment]
Hmmm that is very odd that it changes/isn't correct. Off the top of my head I don't have any answers... but I can do some digging around and try find that out for you

**Comment by kingsleyzissou** [comment]
I created a small stage in osbuild just to test what was happening.

Basically `findmnt` fails to run in osbuild without the `--fstab` option set:
`findmnt: can't read /proc/mounts: No such file or directory`

Additionally, I had to run `findmnt` in `chroot` in the osbuild stage for it to get the correct uuid - but I think this is not an issue since oscap is run in `chroot` in osbuild already.

**Comment by evgenyz** [comment]
Unfortunately in RHEL8 and later boot options are configured with the help of `fips-mode-setup` (crypto-policies).

See: https://gitlab.com/redhat-crypto/fedora-crypto-policies/-/blob/master/fips-mode-setup#L191

This is how they detect the boot partition:

```bash
boot_device="$(df -P /boot | tail -1)"
echo "$boot_device" | grep -q ' /$' && boot_device='/' || boot_device=$(echo "$boot_device" | cut -d ' ' -f 1)
```
