### ISSUE TITLE
Rule kernel_module_dccp_disabled was  removed from RHEL9

### ISSUE THREAD

**Issue by yuumasato** [ComplianceAsCode/content#9579]
#### Description of problem:
One of the stabilization tests detected that rule `kernel_module_dccp_disabled` was removed from RHEL9 (https://github.com/ComplianceAsCode/content/pull/9335)

The rule doesn't make sense on RHEL9 since `dccp` module is not available, but just wanted to be sure it wouldn't create other problems.
CC: @mildas 

#### SCAP Security Guide Version:
v0.1.64

**Comment by mildas** [comment]
We must add the rule back to RHEL9. We can't remove rule from datastream that was already made available for customers, because they might already have tailoring and the removal would break it.

**Comment by yuumasato** [comment]
@mildas Thanks, fix submitted.
