### ISSUE TITLE
Rule auditd_data_retention_max_log_file_action_stig fails in stabilization branch

### ISSUE THREAD

**Issue by yuumasato** [ComplianceAsCode/content#9584]
#### Description of problem:
Rule `auditd_data_retention_max_log_file_action_stig` fails on `stabilization` branch.
This was already fixed in master by https://github.com/ComplianceAsCode/content/commit/d541c51b912, but it is part of a much larger PR (#9512).

Do you think the single commit should be backported?
What are your thoughts?

#### SCAP Security Guide Version:
stabilization-v0.1.64

#### Operating System Version:
RHEL9

#### Steps to Reproduce:

1. Evaluate a RHEL9 with GUI with `stig_gui` profile.

#### Actual Results:
Rule `auditd_data_retention_max_log_file_action_stig` results in `fail`

#### Expected Results:
Rule `auditd_data_retention_max_log_file_action_stig` results in `pass`

**Comment by yuumasato** [comment]
@Mab879 @mildas what are your thoughts on this?

**Comment by Mab879** [comment]
I think we can cherry-pick commit from master. I can create a PR backport it.

**Comment by yuumasato** [comment]
Fixed by the linked PR.
