### ISSUE TITLE
Many Ubuntu 20.04 rules not being corrected in Ansible playbooks when compared to OSCAP scan report.

### ISSUE THREAD

**Issue by huornlmj** [ComplianceAsCode/content#9628]
#### Description of problem:
If I take a vanilla Ubuntu 20.04 system and deploy the "ubuntu2004-playbook-cis_level1_server.yml" Ansible playbook, it will run through and make adjustments.  The changes observed are not many, around 40 or so, given the play recap:

```console
PLAY RECAP *********************************************************************************************************************************************************************************
192.168.75.133             : ok=35   changed=1    unreachable=0    failed=1    skipped=6    rescued=0    ignored=0
```
If I then measure the target using oscap:

```console
oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_cis_level1_server --results results.xml --report $(hostname)-cis-l1-server.html --oval-results ssg-ubuntu2004-ds-1.2.xml
```
And I then look at the HTML report, the report shows 94 rules passed but 84 failed and 8 other.

![image](https://user-images.githubusercontent.com/28444739/193877862-bc7e4834-b13f-40ad-9a27-cb7c304e4c96.png)

I was expecting mostly all passing with no failing rules.  Am I wrong to expect that the Ubuntu 20.04 CIS level 1 server Ansible playbook should put a system into a condition that the matching OSCAP scan measure would match?

As an example, I see "Set Password Maximum Age" failed, and it wasn't included in the Ansible playbook.

**Comment by marcusburghardt** [comment]
This is related to the profile coverage for the specific product (Ubuntu2004). A profile, in this case the CIS Level1 Server, is composed by many different rules which together attend the Benchmark (CIS) requirement for that product.

In case of Ubuntu2004, it is possible to check the coverage in this file:
https://github.com/ComplianceAsCode/content/blob/master/products/ubuntu2004/profiles/cis_level1_server.profile

Note that many requirements are noted with "Needs rule" or it is also possible that some requirements are only partially covered by rules. I know that some other products have a much higher coverage for CIS. So, possibly this product profile could be updated to cover more rules. Any contribution is always welcome.

**Comment by marcusburghardt** [comment]
I am closing this issue since the question was already answered.

@huornlmj , feel free to join us on Gitter: https://gitter.im/Compliance-As-Code-The/content
There you can more easily approach the maintainers, including the Ubuntu maintainers.
