### ISSUE TITLE
Bash remediation of rsyslog_remote_tls does not fix the rule on freshly installed system

### ISSUE THREAD

**Issue by vojtapolasek** [ComplianceAsCode/content#9631]
#### Description of problem:

After installing the fresh system, the rule rsyslog_remote_tls fails. Remediation does not fix it. But test scenarios are working as expected.

#### SCAP Security Guide Version:

a45b8763e4d59aa330f2f00a486328e206494d8b

#### Operating System Version:

RHEL 9, RHEL 8

#### Steps to Reproduce:

1.Install a fresh RHEL 9 / RHEL 8 system
2. upload the datastream to the system
3. oscap xccdf eval --remediate --rule xccdf_org.ssgproject.content_rule_rsyslog_remote_tls ssg-rhel9-ds.xml

#### Actual Results:

The rule fails and remediation results in error.

#### Expected Results:

The rule fails and remediation results in fixed.

**Comment by Mab879** [comment]
To truly fix this rule, you need a rsyslog server. This rule is running right on the line of not being able to have automatic remediation, at least to me, as you have to tailor the profile to make it worthwhile.

Thoughts @vojtapolasek @ggbecker @mildas?

**Comment by vojtapolasek** [comment]
@Mab879  you are correct that the datastream should be modified before applying it to contain true name of the rsyslog server... but I believe this issue is purely technical - the Bash remediation does not make the check passing, no matter what value of the related XCCDF variable you configure.
