### ISSUE TITLE
Rocky Linux | Full evaluation cannot be proceeded against profile dedicated to RHEL

### ISSUE THREAD

**Issue by Ricky-Tigg** [ComplianceAsCode/content#9668]
#### Description of problem:
Full evaluation cannot be proceeded. That may not be an issue since no profile dedicated to Rocky Linux release 9.0 is reported present. Nevertheless ii cannot be sure that it means that it is not supported by this project since Rocky Linux releases are known to be designed to be **entirely bug-for-bug compatible with RHEL releases**.
```
$ pwd
/usr/share/xml/scap/ssg/content
$ ls
ssg-rhel9-ds.xml  ssg-rl9-ds.xml
```
#### SCAP Security guide version:
1.63
#### Operating system version: 
Rocky Linux release 9.0 (Blue Onyx)
#### Steps to reproduce:
Rocky Linux (x86_64 DVD) Installed with defaults as virtual machine in platform virt-manager v. 4.1.0.
```
$ oscap xccdf eval --verbose ERROR --fetch-remote-resources --profile xccdf_org.ssgproject.content_profile_pci-dss ssg-rl9-ds.xml
Downloading: https://access.redhat.com/security/data/oval/com.redhat.rhsa-RHEL9.xml.bz2 ... ok
--- Starting Evaluation ---
Title   Verify File Hashes with RPM
Rule    xccdf_org.ssgproject.content_rule_rpm_verify_hashes
```
#### Actual result:
The evaluation does not continue beyond that task
#### Expected result:
The evaluation to continue beyond that task
#### Additional information/debugging steps:
Unknown to me

**Comment by ggbecker** [comment]
You could try to skip this rule to check if other rules would be processed as usual.

Try also `--verbose DEVEL` for a more detailed log. `ERROR` will only report if there would be a fatal error.

**Comment by Ricky-Tigg** [comment]
Well, that task lasts about seven minutes to be proceeded –it _passed_– in my computer and that virtual machine settings. All it needed was a patient user, which i certainly was not at the time i reported – i had waited about four and half minutes.
