### ISSUE TITLE
Replace workflows' `set-output` with new way of defining variables in GH actions

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#9679]
Github workflows should use https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

instead of `set-output` directive. For example:

https://github.com/ComplianceAsCode/content/blob/1e6e5eb0e7babb4a4cea573b8b9f4305812a202c/.github/workflows/automatus-cs8.yaml#L33

Reference: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by marcusburghardt** [comment]
Fixed by https://github.com/ComplianceAsCode/content/pull/10588
