### ISSUE TITLE
Request Merge Rights

### ISSUE THREAD

**Issue by freddieRv** [ComplianceAsCode/content#9684]
#### Github ID:

* https://github.com/freddieRv

#### About me:

* I am a software developer currently working as a security assurance engineer at Oracle
* I am the technical leader for the scap-security-guide project inside Oracle.
* My interactions with the ComplianceAsCode/content project consist mostly of updating and introducing content for the different Oracle products
* Also occasionally improving/introducing shared content used by oracle products as well as others

#### Reason for having merge rights:

I would like to be granted merge/commit rights on the following areas
* Products (for Oracle products)
* Product-specific profiles (also for profiles for the Oracle products)

#### List of PRs:

1. https://github.com/ComplianceAsCode/content/pull/9337
1. https://github.com/ComplianceAsCode/content/pull/9000
1. https://github.com/ComplianceAsCode/content/pull/9057
1. https://github.com/ComplianceAsCode/content/pull/9099
1. https://github.com/ComplianceAsCode/content/pull/9207
1. https://github.com/ComplianceAsCode/content/pull/9007

**Comment by Mab879** [comment]
Thank you for apply for merge permissions and all you have done for the project.

I approve the adding of merge permissions. Two other maintainers must as well per the [project governance](https://complianceascode.readthedocs.io/en/latest/manual/developer/01_introduction.html#individual-pr-approve-and-merge-rights).

**Comment by ggbecker** [comment]
I approve.

**Comment by vojtapolasek** [comment]
I also approve merge permissions for you. Thank you for helping with the project.

**Comment by matejak** [comment]
Thank you for your application, I also approve.

**Comment by marcusburghardt** [comment]
@freddieRv , thanks for the contributions you have made for the project. I hope much more are coming. : )
I also approve the request.

Since this request already achieved 2 more approvals than the necessary, it would be great to give you a live welcome in order to conclude this process. I will contact you via Gitter to find a suitable time. Thanks again.

**Comment by jan-cerny** [comment]
I also like this proposal very much and I approve it. Thank you very much for all your great contributions and I look forward to working together in future!

**Comment by marcusburghardt** [comment]
The "Merge Rights" are officially granted to Federico.

Welcome Federico!! : )
