### ISSUE TITLE
Request Merge Rights - Eduardo Barretto (Canonical/Ubuntu)

### ISSUE THREAD

**Issue by dodys** [ComplianceAsCode/content#9713]
#### Github ID:

* https://github.com/dodys

#### About me:

* I am a Senior Software Engineer at Canonical.
* I've done the tasks of implementing, upstreaming and maintaining Ubuntu 20.04 DISA STIG. I shall be doing the same and reviewing other colleagues contributions on Ubuntu 22.04 CIS/STIG.
* Also, I've been helping testing (and reporting issues for) the changes on upstream; contributing fixes when changes committed affect Ubuntu in a not so clear way and ultimately replying to bugs/discussions here regarding Ubuntu and project improvements.

#### Reason for having merge rights:

* Products (for Canonical products)
* Product-specific profiles (also for profiles for the Canonical products)
* Shared resources (mainly on templates and improvements that can benefit everyone)

#### List of PRs:

I've opened about 60 PRs over the course of an year and currently sit in 16th place on the contributors list. I've not explicitly picked 6 PRs but instead I'm listing here all the closed PRs I've authored.
1. https://github.com/ComplianceAsCode/content/pulls?q=is%3Apr+author%3Adodys+is%3Aclosed

**Comment by ggbecker** [comment]
I approve.

**Comment by jan-cerny** [comment]
I also like this proposal very much and I approve it. Thank you very much for all your great contributions and I look forward to working together in future!

**Comment by mildas** [comment]
I approve.

**Comment by marcusburghardt** [comment]
I also approve. Thanks Eduardo.

**Comment by marcusburghardt** [comment]
The "Merge Rights" are officially granted to Eduardo Barreto.

Welcome Eduardo!! : )
