### ISSUE TITLE
openscap 1.2.16 not able to build complianceascode

### ISSUE THREAD

**Issue by msmeissn** [ComplianceAsCode/content#9718]
#### Description of problem:

openscap 1.2.16 in SLES15 GA currently cannot build CaC 0.1.64.... 0.1.63 has built fine.

It fails in generation the "fix" scripts. For some reason I think it wants the external OVAL CVE/RPM data present.

Note with openscap 1.2.9 it builds fine, also 1.3.6 works fine.

#### SCAP Security Guide Version:

0.1.64

#### Operating System Version:

SLES 15 GA

#### Steps to Reproduce:

1. built CaC
2.
3.
4.

#### Actual Results:

(sample, all xcddf generate fix  with embedded remote resources fail)

oscap xccdf generate fix --skip-valid --benchmark-id xccdf_org.ssgproject.content_benchmark_SLE-12 --profile xccdf_org.ssgproject.content_profile_cis_server_l1 --template urn:xccdf:fix:script:sh ./ssg-sle12-ds.xml

WARNING: Datastream component 'scap_org.open-scap_cref_pub-projects-security-oval-suse.linux.enterprise.12.xml' points out to the remote 'https://ftp.suse.com/pub/projects/security/oval/suse.linux.enterprise.12.xml'. Use '--fetch-remote-resources' option to download it.
WARNING: Skipping 'https://ftp.suse.com/pub/projects/security/oval/suse.linux.enterprise.12.xml' file which is referenced from datastream
OpenSCAP Error: Could not extract scap_org.open-scap_cref_ssg-sle12-xccdf-1.2.xml with all dependencies from datastream. [ds_sds_session.c:211]

#### Expected Results:

successful rule creation.

**Comment by ggbecker** [comment]
@jan-cerny any idea on what that could be?

**Comment by jan-cerny** [comment]
@msmeissn @ggbecker I haven't verified but I think that it's because of the SCAP 1.3 way of using the CVE OVAL feeds - they are now a remote component of data streams, before they were just referenced from the XCCDF. I have found in the GitHub history that we were fixing the very same error message in https://github.com/OpenSCAP/openscap/pull/1324, but this PR was done after 1.2.16 release.

**Comment by msmeissn** [comment]
thanks for the pointer. I added commit bbcbffcf6f901cb67ca5645307d170a32504a491 to my build of openscap 1.2.16 and it now can build 0.1.64 CaC
