### ISSUE TITLE
Request Merge Rights

### ISSUE THREAD

**Issue by anivan-suse** [ComplianceAsCode/content#9731]
#### Github ID:

[anivan-suse](https://github.com/anivan-suse)

#### About me:

A SUSE employee working on SCAP projects.

#### Reason for having merge rights:

* Please, consult the [list of project areas](https://complianceascode.readthedocs.io/en/latest/manual/developer/01_introduction.html#decomposition) and specify in which area would you like to get merge rights. This will help us to understand the context.
Project areas relevant to me:
- Products (SUSE) 
- Product-specific profiles 
- Shared resources

#### List of PRs:

1. [#9705](https://github.com/ComplianceAsCode/content/pull/9705)
2. [#9672](https://github.com/ComplianceAsCode/content/pull/9672)
3. [#9645](https://github.com/ComplianceAsCode/content/pull/9645)
4. [#9633](https://github.com/ComplianceAsCode/content/pull/9633)
5. [#8927](https://github.com/ComplianceAsCode/content/pull/8927)
6. [#9362](https://github.com/ComplianceAsCode/content/pull/9362)

**Comment by Mab879** [comment]
Thanks for your contributions. 

I approve.

**Comment by matejak** [comment]
Thank you for your application, I approve as well.

**Comment by marcusburghardt** [comment]
Thanks for the contributions. I also approve.

**Comment by marcusburghardt** [comment]
The "Merge Rights" are officially granted to Anastasija.

Welcome Anastasija!! : )
