### ISSUE TITLE
Stop checking for key in case of Audit rules

### ISSUE THREAD

**Issue by vojtapolasek** [ComplianceAsCode/content#9741]
#### Description of problem:

Many rules which are checking for content of Audit rules check for the Audit key.
This key is  denoted by either
```
-k <key>
```

or

```
-F key=<key>
```

The key serves only anotating purpose - it makes it easier to search for rules with certain key in logs. But it does not impact security posture of the system.

I suggest that all OVALS of rules checking for Audit rules are modified so that they do not check for the key parameter.

Inspiration can be found here: https://github.com/ComplianceAsCode/content/pull/9463/files

#### SCAP Security Guide Version:

Master

#### Operating System Version:

RHEL 7/8/9

#### Steps to Reproduce:

1. go through each rule which checks for Audit configuration. They are found in auditd_configure_rules group. They are either templated or they have their specific OVAL.
2. Check their OVAL.

#### Actual Results:

In many cases the regex present in the OVAL check for -k or -F key parameter.

#### Expected Results:

The regex does not check for presence of -k or -F key= in Audit rule.

**Comment by marcusburghardt** [comment]
There is already an agreement to not check for `keys`. They are used to support humans and don't affect the collection of events. If any rule is not yet updated, they can be addressed individually.
