### ISSUE TITLE
Reopen #9456 (umask in login.defs)

### ISSUE THREAD

**Issue by merillr** [ComplianceAsCode/content#9758]
#### Description of problem:
#9490 was merged to fix #9456, but does not fix the original issue. If the ansible playbook is run multiple times, the _var_accounts_user_umask_ is continuously appended to the umask value in the file. This can be fixed with a correction on the regexp so the entire line is replaced, instead of the substring.

#### Operating System Version:
RHEL 8.6

#### Steps to Reproduce:

1. Run playbook with redhatofficial.rhel8_stig role and DISA-STIG-RHEL-08-020351 tag

#### Actual Results:
`/etc/login.defs` (first run)
UMASK 077 022  

`/etc/login.defs` (second run)
UMASK 077 077 022

#### Expected Results:
UMASK 077 022

#### Additional Information/Debugging Steps:
Possible fix may be to change
regexp: ^UMASK
to
regexp: ^UMASK.*

**Comment by ggbecker** [comment]
The changes made here have not been released yet. So the ansible galaxy playbook doesn't have the updates for this snippet. That's what might be causing the problem.

Are you using the snippet that is generated from the latest main branch or from ansible galaxy?

**Comment by ggbecker** [comment]
Yes, when a new release happens. The next release is scheduled to happen in the end of this month.

**Comment by ggbecker** [comment]
Let's close this one until a new release happens and you are able to test it again. If it doesn't work then you may reopen it again.
