### ISSUE TITLE
scap-security-guide package not found

### ISSUE THREAD

**Issue by ansiblejunky** [ComplianceAsCode/content#9759]
#### Description of problem:
Performing `dnf install scap-security-guide` on RHEL8 container results in:

```
No match for argument: scap-security-guide
Error: Unable to find a match: scap-security-guide
```

#### Operating System Version:
RHEL 8 container

#### Steps to Reproduce:
See above

#### Actual Results:
No match for argument: scap-security-guide
Error: Unable to find a match: scap-security-guide

#### Expected Results:
Install package as described in the OpenSCAP documentation.

**Comment by ggbecker** [comment]
which container you are using? ubi/ubi-minimal or something else?

**Comment by ansiblejunky** [comment]
yeah:
docker run -it --name test registry.access.redhat.com/ubi9/ubi:latest bash

**Comment by ggbecker** [comment]
I guess the `scap-security-guide` was never part of the ubi image repositories. So probably nothing to be done here for now other than poke redhat and see if there is any real reason to be like that. Closing for now. Feel free to reopen the issue.
