### ISSUE TITLE
Performance regression in STIG GUI profile

### ISSUE THREAD

**Issue by jan-cerny** [ComplianceAsCode/content#9765]
#### Description of problem:
During upstream productization we were not able to complete the test "/CoreOS/scap-security-guide/Sanity/ssg-kickstarts for STIG (GUI)". We rerun this test many times but each time the test has timed out and prematurely terminated.

However, this issue doesn't happen on the same compose when using scap-security-guide-0.1.63-5.el9. Therefore, we think that there is a new issue between  scap-security-guide-0.1.63-5.el9 and current master.

#### SCAP Security Guide Version:
Current upstream as of 2022-10-29 as of HEAD 4b5551f

This situation already happened a week before when we used SSG as of HEAD 3748e7b.

#### Operating System Version:
RHEL 9.1

#### Steps to Reproduce:

irt-install --name=test_suite_vm             --memory=4096 --vcpus=1 --hvm             --network bridge=virbr0,mac=00:16:3e:00:00:28 --disk path=/var/lib/libvirt/images/stig/test,size=30             --location <INSERT LOCATION HERE> --initrd-inject ssg-rhel9-stig_gui-ks.cfg --wait 0             --graphics vnc --extra-args "inst.ks=file:/ssg-rhel9-stig_gui-ks.cfg inst.addrepo=AppStream,<INSERT LOCATION HERE> inst.addrepo=ssg,http://192.168.122.1/ssg console=ttyS0 inst.graphical notmux systemd.journald.forward_to_console=1" --noautoconsole

#### Actual Results:
Installation takes many hours which leads to time out and test ends in a WARN state.

#### Expected Results:
installation finishes in an acceptable time frame so that it doesn't time out and the test can 

#### Additional Information/Debugging Steps:

Notice the long time span between the messages from Anaconda.
```
[   86.506925] anaconda[1772]: anaconda: threading: Thread Done: OSCAPguiWaitForDataFetchThread (139976431871552)
[   91.648105] systemd[1]: systemd-localed.service: Deactivated successfully.
[  100.879109] systemd[1]: systemd-hostnamed.service: Deactivated successfully.
[  208.534841] chronyd[2074]: Source 65.100.46.166 replaced with 38.229.62.9 (2.rhel.pool.ntp.org)
[  907.209531] systemd[1]: Starting Cleanup of Temporary Directories...
[  907.237171] systemd[1]: systemd-tmpfiles-clean.service: Deactivated successfully.
[  907.238979] systemd[1]: Finished Cleanup of Temporary Directories.
[ 2269.150857] chronyd[2074]: Source 216.218.254.202 replaced with 129.250.35.251 (2.rhel.pool.ntp.org)
```

**Comment by yuumasato** [comment]
It looks like RHEL7 is affected as well....

**Comment by mildas** [comment]
In last productization run, it passed on RHEL7 and RHEL8. But RHEL9 is still affected.

**Comment by jan-cerny** [comment]
amazing, but we haven't found the cause, so we aren't sure if this isn't just a conicidence

**Comment by mildas** [comment]
Analysis:
It is not a performance issue, STIG with GUI installation can't be performed at all.
5857f15 is the commit where it started. For the specific commit there are actually two installation blocking warnings are there:
`/boot/efi must be on a separate partition or logical volume and has to be created in the partitioning layout before installation can occur with a security profile`
`nfs-utils` has been added to the list of excluded packages, but it can't be removed from the current software selection without breaking the installation`

As there was no `/boot/efi` partition defined in kickstart, it's understandable what is problem there. But the `/boot/efi` issue is not there anymore (latest master). However, the second warning about `nfs-utils` is still there and it is a requirement for Server wtih GUI package set.
