### ISSUE TITLE
Controls file format does not prevent using unsupported parameters

### ISSUE THREAD

**Issue by ggbecker** [ComplianceAsCode/content#9772]
#### Description of problem:
Controls file format does not support usage of `rule` parameter although it's being used by some of the control files in the project:

```
controls/cis_sle_15.yml:
  1566      status: automated
  1567:     rule:
  1568        - file_groupowner_at_allow

  1749      status: automated
  1750:     rule:
  1751        - sshd_enable_warning_banner

  2199      status: automated
  2200:     rule:
  2201        - group_unique_id

controls/cis_sle12.yml:
  1397      automated: yes
  1398:     rule:
  1399      - file_groupowner_at_allow

  1581      automated: yes
  1582:     rule:
  1583      - sshd_enable_warning_banner
```

The function below parses the parameters but does not warn the user in case some unsupported parameter is being used:

https://github.com/ComplianceAsCode/content/blob/a0f2b1e8044cffe6cd0741cf2525a77c1016f1b4/ssg/controls.py#L97

This basically means that the rules under `rule` will not be processed. The function needs to be extended to restrict which parameters are accepted and throw an error in case something that is not in the list is being used.

**Comment by yuumasato** [comment]
When loading content that uses classes based on XCCDFEntity, like  [Rule](https://github.com/ComplianceAsCode/content/blob/a0f2b1e8044cffe6cd0741cf2525a77c1016f1b4/ssg/build_yaml.py#L695) for example, unparsed data is flagged out during build time:

https://github.com/ComplianceAsCode/content/blob/a0f2b1e8044cffe6cd0741cf2525a77c1016f1b4/ssg/entities/common.py#L175

**Comment by marcusburghardt** [comment]
There are profiles using `automated: yes` and maybe other parameter before the definition of the `status` parameter. Therefore, they are not wrong but just outdated and, for compatibility purposes, should not be restricted now. In fact, the respective control files should be updated before restricting parameters which were used in the past but there is a current replacement.

Instead of restricting this now and triggering a wave of errors, I would recommend to simply alert about this but keep accepting until we are sure all control files are updated.

**Comment by ggbecker** [comment]
> There are profiles using `automated: ` and maybe other parameter before the definition of the `status` parameter. Therefore, they are not wrong but just outdated and, for compatibility purposes, should not be restricted now. In fact, the respective control files should be updated before restricting parameters which were used in the past but there is a current replacement.
> 
> Instead of restricting this now and triggering a wave of errors, I would recommend to simply alert about this but keep accepting until we are sure all control files are updated.

Agree, but in case of `rule`, the parameter will not get loaded and rules will not be present in the built profile, which is a major issue.
