### ISSUE TITLE
accounts_passwords_pam_faillock_deny fails build on RHEL-7

### ISSUE THREAD

**Issue by comps** [ComplianceAsCode/content#9829]
#### Description of problem:
```
/usr/bin/cmake -E cmake_progress_report /root/rpmbuild/BUILD/scap-security-guide-0.1.65/build/CMakeFiles  30
[ 43%] Built target generate-rhel7-profile-table-ospp
Traceback (most recent call last):
  File "/root/rpmbuild/BUILD/scap-security-guide-0.1.65/utils/gen_profile_table.py", line 71, in <module>
    renderer.process_rules(reference)
  File "/root/rpmbuild/BUILD/scap-security-guide-0.1.65/utils/gen_profile_table.py", line 47, in process_rules
    super(HtmlOutput, self).process_rules(reference)
  File "/root/rpmbuild/BUILD/scap-security-guide-0.1.65/utils/tables/table_renderer.py", line 91, in process_rules
    eligible_rules = self._get_eligible_rules(reference.id)
  File "/root/rpmbuild/BUILD/scap-security-guide-0.1.65/utils/gen_profile_table.py", line 35, in _get_eligible_rules
    return [ssg.build_yaml.Rule.from_yaml(f, self.env_yaml) for f in filenames]
  File "/root/rpmbuild/BUILD/scap-security-guide-0.1.65/ssg/build_yaml.py", line 760, in from_yaml
    rule = super(Rule, cls).from_yaml(yaml_file, env_yaml, product_cpes)
  File "/root/rpmbuild/BUILD/scap-security-guide-0.1.65/ssg/entities/common.py", line 203, in from_yaml
    raise RuntimeError(msg)
RuntimeError: Error loading a Rule from /root/rpmbuild/BUILD/scap-security-guide-0.1.65/build/rhel8/rules/accounts_passwords_pam_faillock_deny.yml: EOF read where object expected
make[3]: *** [tables/table-rhel8-anssirefs-bp28_enhanced.html] Error 1
```

#### SCAP Security Guide Version:
master as of 2022-11-15

#### Operating System Version:
RHEL-7.9 with EUS updates

#### Steps to Reproduce:

1. run https://src.fedoraproject.org/tests/scap-security-guide/blob/main/f/Sanity/smoke-test

#### Additional Information/Debugging Steps:
Executed 4 times in total, likely not a random infra issue.

**Comment by jan-cerny** [comment]
It can also be that the cmake targets are built in parallel and the result is that the output is messy.

If you take a close look to the output in the issue description you can see that the error is actually in RHEL 8 ANSSI enhanced profile table generator:
```
make[3]: *** [tables/table-rhel8-anssirefs-bp28_enhanced.html] Error 1
```

**Comment by marcusburghardt** [comment]
I am working in some other issues and removed my assignment. It would be great is someone could assume this issue, try to reproduce it and share more information.

**Comment by matejak** [comment]
Investigation revealed that cmake dependencies are set correctly - no new jobs are started before the `compile_all` script finishes. Reproducing the issue on Fedora running on a laptop was not successful at all.
The error indicates that a subsequent build step encountered a rule file that was being written. I see no other explanation that a delay caused by buffer flushes taking a long time and happening in a random order.

**Comment by marcusburghardt** [comment]
I haven't seen this error popping up again in the last few tests I've reviewed. I'm closing this question now. We can reopen it if the error reappears.

**Comment by matejak** [comment]
This problem can be reproduced on e.g. RHEL7 systems with high-enough parallelization of the build, e.g. by running `./build_product -j16`. It looks like that something involving the older versions of the toolchain, Jinja (cache?) and parallel build of multiple products doesn't work properly.
The crash either references a jinja file directly, or it is about source files that contain jinja substitutions that are malformed, and it is actually easily reproduced.
Conversely, this unknown issue doesn't manifest on systems with Python3 package set s.a. RHEL8, and even the original issue has a simple workaround of limiting the number of simultaneous processes to 4 and less, so it is not worth fixing.
