### ISSUE TITLE
Rule sshd_set_keepalive is misaligned with DISA

### ISSUE THREAD

**Issue by mildas** [ComplianceAsCode/content#9830]
#### Description of problem:
SSG content passes, but DISA contet fails. Looking at arf results:

SSG content resulted as true for `Tests the value of the ClientAliveCountMax setting in the /etc/ssh/sshd_config file` for pattern
```
^[\s]*(?i)ClientAliveCountMax[\s]+([\d]+)[\s]*(?:#.*)?$
```

However, DISA content results in false for `/etc/ssh/sshd_config:ClientAliveCountMax = 0` for pattern
```
^\s*(?i)ClientAliveCountMax(?-i)\s+"?(\d+)"?\s*(?:|(?:#.*))?$
```

#### SCAP Security Guide Version:
06c64d

#### Operating System Version:
RHEL8

#### Steps to Reproduce:

1. Install machine hardened with STIG with GUI
2. Scan using SSG content and using DISA content

#### Actual Results:
Results are misaligned

#### Expected Results:
Results are aligned

**Comment by marcusburghardt** [comment]
From sshd man:
```
ClientAliveCountMax
             Sets the number of client alive messages which may be sent without sshd(8) receiving any messages back from the client.  If this threshold is reached while client alive messages are being sent, sshd will disconnect the
             client, terminating the session.  It is important to note that the use of client alive messages is very different from TCPKeepAlive.  The client alive messages are sent through the encrypted channel and therefore will
             not be spoofable.  The TCP keepalive option enabled by TCPKeepAlive is spoofable.  The client alive mechanism is valuable when the client or server depend on knowing when a connection has become unresponsive.

             The default value is 3.  If ClientAliveInterval is set to 15, and ClientAliveCountMax is left at the default, unresponsive SSH clients will be disconnected after approximately 45 seconds.  Setting a zero
             ClientAliveCountMax disables connection termination.
```
The `sshd_set_keepalive` rule asks to set a timeout. However, if the `ClientAliveCountMax` value is `0`, the timeout is actually disabled, the opposite of the rule requirement.

So, it is not expected to pass if the `ClientAliveCountMax` is set to `0` and the DISA assessment is correct.
The SSG content have to be updated. I am preparing a PR for this.

**Comment by marcusburghardt** [comment]
It misalignment is still appearing. We should review if something new appeared.

**Comment by matusmarhefka** [comment]
Misalignment still appearing as of master commit e7502af.

**Comment by marcusburghardt** [comment]
I take a look again on this and it seems DISA is expecting a value of `0` in their check:
```
        <textfilecontent54_test xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5#independent" check="all" check_existence="at_least_one_exists" comment="/etc/ssh/sshd_config:ClientAliveCountMax = 0" id="oval:mil.disa.stig.rhel8:tst:11501" version="2">
          <object object_ref="oval:mil.disa.stig.rhel8:obj:11501" />
          <state state_ref="oval:mil.disa.stig.rhel8:ste:17100" />
        </textfilecontent54_test>
...
        <textfilecontent54_object xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5#independent" id="oval:mil.disa.stig.rhel8:obj:11501" version="2">
          <filepath>/etc/ssh/sshd_config</filepath>
          <pattern operation="pattern match">^\s*(?i)ClientAliveCountMax(?-i)\s+"?(\d+)"?\s*(?:|(?:#.*))?$</pattern>
          <instance datatype="int" operation="greater than or equal">1</instance>
        </textfilecontent54_object>
...
        <textfilecontent54_state xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5#independent" id="oval:mil.disa.stig.rhel8:ste:17100" version="1">
          <subexpression datatype="string" operation="equals">0</subexpression>
```

Probably something changed since this issue was created because now, according to these OVAL objects extracted from `disa-stig-rhel8-v1r7-xccdf-scap.xml`, the `textfilecontent54_state` in DISA DS is wrong.

It should be like this:
`<subexpression datatype="string" operation="equals">1</subexpression>`

instead of:
`<subexpression datatype="string" operation="equals">0</subexpression>`

@ggbecker , @Mab879 , @yuumasato FYI.

**Comment by yuumasato** [comment]
This issue has been fixed on  DISA's SCAP content `Red Hat Enterprise Linux 8 STIG Benchmark - Ver 1, Rel 8`.
Ref: https://github.com/ComplianceAsCode/content/pull/10078/commits/df24f2352cca70afc107358c62bae3386b66d839
