### ISSUE TITLE
Rule sshd_set_keepalive is not aligned with DISA STIG benchmark

### ISSUE THREAD

**Issue by marcusburghardt** [ComplianceAsCode/content#9846]
Description of problem:
Rule `xccdf_org.ssgproject.content_rule_sshd_set_keepalive` is misaligned with rule `xccdf_mil.disa.stig_rule_SV-230244r858697_rule` from the DISA content in `disa-stig-rhel8-v1r7-xccdf-scap.xml`.

SCAP Security Guide Version:
current upstream `master` branch as of 2022-11-19

Operating System Version:
RHEL 8

Steps to Reproduce:
evaluate RHEL 8 STIG profile
evaluate disa-stig-rhel8-v1r7-xccdf-scap.xml
Actual Results:
xccdf_org.ssgproject.content_rule_sshd_set_keepalive : pass
xccdf_mil.disa.stig_rule_SV-230244r858697_rule : fail

Expected Results:
both rules pass

Additional Information/Debugging Steps:
This problem occurs also with the "STIG with GUI" profile.

**Comment by mildas** [comment]
Already reported https://github.com/ComplianceAsCode/content/issues/9830 and I wouldn't say it's blocked - further analyses is needed to check if the problem is on our side or not.
