### ISSUE TITLE
Missing '/usr/share/selinux' entry in the 'content_rule_audit_rules_mac_modification' rule

### ISSUE THREAD

**Issue by VikasGothwal** [ComplianceAsCode/content#9853]
**Script:** rhel7-script-cis_server_l1_l2.sh (Center for Internet Security® Red Hat Enterprise Linux 7 Benchmark, v3.1.1, released 05-21-2021.)

**Rule:** 'content_rule_audit_rules_mac_modification'

**Issue:** Missing '/usr/share/selinux' entry

#### Description of problem:

As per the Center for Internet Security Red Hat Enterprise Linux 7 Benchmark, v3.1.1, released 05-21-2021,

The remediation says to add the following 2 lines to the .rules file:

```
-w /etc/selinux/ -p wa -k MAC-policy
-w /usr/share/selinux/ -p wa -k MAC-policy
```

However, our bash script is only adding '/etc/selinux' and not '/usr/share/selinux'.

I checked this in RHEL 7 script, however, this is the same case in all other scripts for all CIS benchmarks.

#### Proposed change:

Update the existing remediation rule 'content_rule_audit_rules_mac_modification' to include the entry for '/usr/share/selinux'

#### References:

1. CIS Red Hat Enterprise Linux 7 Benchmark v3.1.1 - 05-21-2021 
2. 4.1.6 Ensure events that modify the system's Mandatory Access Controls are collected (Automated)

**Comment by marcusburghardt** [comment]
Thanks for reporting @VikasGothwal . Reviewing this issue I confirmed the `/usr/share/selinux` file is already covered by the `audit_rules_mac_modification_usr_share` rule and is already present in CIS profiles for RHEL.
