### ISSUE TITLE
platform_package_overrides not working with automatus

### ISSUE THREAD

**Issue by dodys** [ComplianceAsCode/content#9869]
#### Description of problem:

Back before automatus, it was possible to run rule tests and for packages that were defined in platform_package_overrides would be correctly picked. Now this does not seem to be the case anymore.
For example, this commit was added to make the test pass back in the old test_suite:
https://github.com/ComplianceAsCode/content/pull/7574/commits/56cf904b75052cece57a421ba56f4409045f3ee7

Now the same test doesn't work anymore, and fails with:
```
 DEBIAN_FRONTEND=noninteractive apt install -y audit
 STDOUT: Reading package lists...
 Building dependency tree...
 Reading state information...
 
 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
 
 E: Unable to locate package audit
```

#### SCAP Security Guide Version:
master as of 2022-11-16

#### Operating System Version:
Ubuntu 20.04 LTS

#### Steps to Reproduce:

1. Try to execute a rule tests that contains a package defined in platform_package_overrides.

#### Actual Results:
Failing because it tries to install the package defined in test file instead of the one in platform_package_overrides.

#### Expected Results:
Test to correctly install the package as defined in platform_package_overrides

**Comment by dodys** [comment]
you can see that this issue already caused contributors to do things like commit [8410cd12](https://github.com/ComplianceAsCode/content/commit/8410cd12c62e30b9#diff-9a67c3856235380b390780d7b1efab73d3cd341506616306ae7075889bbea966R2)

I would prefer that to be dealt as it was before through platform_package_overrides, instead of adding a lot of checks to make tests work again.

**Comment by ggbecker** [comment]
We never had this implemented, but it should be really simple to add support to something similar like for example:

```
diff --git a/linux_os/guide/system/auditing/auditd_configure_rules/file_group_ownership_var_log_audit/tests/correct_value_default_file.pass.sh b/linux_os/guide/system/auditing/auditd_configure_rules/file_group_ownership_var_log_audit/tests/correct_value_default_file.pass.sh
index 35682937f2..85abbf4360 100644
--- a/linux_os/guide/system/auditing/auditd_configure_rules/file_group_ownership_var_log_audit/tests/correct_value_default_file.pass.sh
+++ b/linux_os/guide/system/auditing/auditd_configure_rules/file_group_ownership_var_log_audit/tests/correct_value_default_file.pass.sh
@@ -1,9 +1,5 @@
 #!/bin/bash
-{{% if "ubuntu" in product %}}
-# packages = auditd
-{{% else %}}
-# packages = audit
-{{% endif %}}
+# packages = {{{ pkg_conditional("audit") }}}

 source common.sh

diff --git a/shared/macros/10-bash.jinja b/shared/macros/10-bash.jinja
index 0e36931464..92ae70902f 100644
--- a/shared/macros/10-bash.jinja
+++ b/shared/macros/10-bash.jinja
@@ -1775,6 +1775,13 @@ JINJA MACRO ERROR - Unknown package system '{{{ pkg_system }}}'.
 {{%- endmacro -%}}


+{{%- macro pkg_conditional(package) -%}}
+{{%- if package in platform_package_overrides -%}}
+  {{%- set package = platform_package_overrides[package] -%}}
+{{%- endif -%}}
+{{{ package }}}
+{{%- endmacro -%}}
+
 {{#
   This macro creates a Bash conditional which uses rpm to check if a package passed as a parameter is installed.
 #}}
```

**Comment by dodys** [comment]
> We never had this implemented, but it should be really simple to add support to something similar like for example:

I find it hard to believe, as I can run the test in the test_suite pre-automatus.
Maybe the issue is not in automatus itself but somewhereelse that isn't using platform_package_overrides correctly anymore.

**Comment by dodys** [comment]
> > We never had this implemented, but it should be really simple to add support to something similar like for example:
> 
> I find it hard to believe, as I can run the test in the test_suite pre-automatus. Maybe the issue is not in automatus itself but somewhereelse that isn't using platform_package_overrides correctly anymore.

I'm mistaken, sorry about that. I see that it never got upstreamed PR#7295
So yeah, adding something like you mentioned or like Alex tried to add would make things easier and cleaner.

**Comment by dodys** [comment]
we already have: bash_pkg_conditional in macros-bash.jinja
Could we re-use it in tests?

**Comment by ggbecker** [comment]
> we already have: bash_pkg_conditional in macros-bash.jinja Could we re-use it in tests?

I think we would need a new macro, as I pasted in the snippet... the bash condition macro does something different, but it can probably be a composition of macros or something

**Comment by dodys** [comment]
> > we already have: bash_pkg_conditional in macros-bash.jinja Could we re-use it in tests?
> 
> I think we would need a new macro, as I pasted in the snippet... the bash condition macro does something different, but it can probably be a composition of macros or something.
> 
> And would be ideal to do this change project wide, meaning replacing in every applicable test scenario to keep things consistent

ack, thanks!
A colleague of mine will take a look on implementing it, but let us know if anyone is already taking a look at that.
