### ISSUE TITLE
[RHEL/6] [RHEL/7] [Fedora] Port LDAP client rules from nss-pam-ldapd to sssd

### ISSUE THREAD

**Issue by iankko** [ComplianceAsCode/content#987]
Based on:
- &nbsp; &nbsp; [1] https://access.redhat.com/solutions/55840
- &nbsp; &nbsp; [2] https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Deployment_Guide/ch-Directory_Servers.html#s2-ldap-pam

`sssd` daemon approach is recommended over `nss-pam-ldapd` approach.

Therefore the existing:
- ```
  <Rule id="ldap_client_start_tls" severity="medium">
  <title>Configure LDAP Client to Use TLS For All Transactions</title>

``````
and

* ```
<Rule id="ldap_client_tls_cacertpath" severity="medium">
<title>Configure Certificate Directives for LDAP Use of TLS</title>
``````

should be ported to `sssd` approach (this includes updating all of existing XCCDFs, OVALs, and remediation scripts):
&nbsp; &nbsp; [3] https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Deployment_Guide/Configuring_Domains-Configuring_a_Native_LDAP_Domain.html

**Comment by marcusburghardt** [comment]
This issue is over 6 years old and refers to legacy technology. I no longer can validate it, so I am closing.
