### ISSUE TITLE
Checks for enabling smartcards via SSSD should check for the values in drop-in files (/etc/sssd/conf.d) instead of just /etc/sssd/sssd.conf

### ISSUE THREAD

**Issue by michael-riddle** [ComplianceAsCode/content#9970]
#### Description of problem:
The check for content_rule_sssd_enable_smartcards isn't flexible enough to check for configurations under /etc/sssd/conf.d. If the remediation happens within one of the configs under this directory, the rule will still pop as a failure in scans because it doesn't live directly under /etc/sssd/sssd.conf. These checks should account for drop-in files.

#### SCAP Security Guide Version:
0.1.63

#### Operating System Version:
RHEL 8
RHEL 7
OEL 8
OEL 7
CentOS 8
CentOS 7

#### Steps to Reproduce:

1. Remediate the rule via a dropin file in /etc/sssd/conf.d and run a scan, the check for this rule will fail.

#### Actual Results:
The rule fails

#### Expected Results:
The rule passes because the appropriate value is in the configuration, but inside of a drop-in file.

**Comment by marcusburghardt** [comment]
I just checked the `sssd_enable_smartcards` rule and it is also considering drop-in files. The rule was updated in the meantime and this issue was already resolved.
